### ISSUE TITLE
Test:  TestPackageManager_UpgradePackageFor_TopParentProject_Success is flaky

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#10208]
TestPackageManager_UpgradePackageFor_TopParentProject_Success is flaky.

In dev it has failed 3/15 runs (20%).

In private branches it has failed 11/40 runs (27.5%).

```
Assert.True() Failure\r\nExpected: True\r\nActual:   False

   at NuGet.PackageManagement.VisualStudio.Test.CpsPackageReferenceProjectTests.<TestPackageManager_UpgradePackageFor_TopParentProject_Success>d__10.MoveNext() in C:\A\1\50\s\test\NuGet.Clients.Tests\NuGet.PackageManagement.VisualStudio.Test\CpsPackageReferenceProjectTests.cs:line 878
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by dtivel** [comment]
29 Nov 2020:  Failed again in private branch build 5.9.0.13872.
