### ISSUE TITLE
package add does not use credential provider when authentication is required

### ISSUE THREAD

**Issue by danieljbfaustino** [NuGet/Home#10305]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): `Nuget.exe` and `dotnet.exe`

NuGet version (x.x.x.xxx): `5.8.0.6930`
- Although it is present starting on `5.8.0.6753` and newer.

dotnet.exe --version (if appropriate): `5.0.100`

OS version (i.e. win10 v1607 (14393.321)): `win10-x64 10.0.19042`

Worked before? If so, with which NuGet version: `5.3.0.6251`
- Most probably also working on `5.8.0.6725`
- When running out of `XPlat` the fix in https://github.com/NuGet/NuGet.Client/pull/3335 is needed.

## Detailed repro steps so we can see the same problem

"Pre-requisites:"
1. Make sure a package source requiring authentication is added to your `NuGet.Config` and the corresponding credential provider setup. For example, when using an Azure Artifacts feed requiring authentication, make sure to also have the Azure Artifacts Credential Provider setup.
2. Do not authenticate yet!

Using `dotnet`:
1. Run `dotnet new classlib -n testproj -o .` to have a sample empty project.
2. Run `dotnet add package [package_from_source_requiring_authentication] --interactive`
3. Notice how the command will fail. It will not use the credential provider.

Using `nuget`. Issue is present in the `NuGet.CommandLine.XPlat` application.
1. Run `dotnet new classlib -n testproj -o .` to have a sample empty project.
2. Run `dotnet [path_to_xplat]/NuGet.CommandLine.XPlat.dll package add --package [package_from_source_requiring_authentication] -p ./testproj.csproj -d ./obj/testproj.csproj.nuget.dgspec.json --interactive`
3. Notice how the command will fail. It will not use the credential provider.

### More information (from digging around)
- Seems to have been introduced in https://github.com/NuGet/NuGet.Client/pull/3480
- Issue seems to be related to the changes done in `AddPackageReferenceCommandRunner.cs` where the package source is being accessed to obtain a NugetVersion before the credential provider is setup.
- Maybe there should be a test case in `AddPackageCommandUtilityTests.cs` to cover situations where credentials are not present in `NuGet.config`?
- Add `DefaultCredentialServiceUtility.SetupDefaultCredentialService(packageReferenceArgs.Logger, !packageReferenceArgs.Interactive);` before this line https://github.com/NuGet/NuGet.Client/blob/release-5.8.0-assemblyVersion-6930/src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageReferenceCommands/AddPackageReferenceCommandRunner.cs#L106 to see it work "well".
- **Question:** Would it be worth it reporting this issue in dotnet repo as well, linking to this report?

#### Log from `dotnet` command (I could not find a way of specifying verbosity)

```
  Determining projects to restore...
  Writing [redacted]
info : Adding PackageReference for package '[package_from_source_requiring_authentication]' into project 'C:\[redacted]\testproj.csproj'.
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/[package_from_source_requiring_authentication]/index.json
info :   NotFound https://api.nuget.org/v3/registration5-gz-semver2/[package_from_source_requiring_authentication]/index.json 716ms
error: Unable to load the service index for source [package_source_requiring_authentication]/nuget/v3/index.json.
error:   Response status code does not indicate success: 401 (Unauthorized).
```

#### Log from `nuget` (XPlat).

**5.8.0.6930 does not seem to have the `--verbosity` flag.** (bug?) The following is when running out of Visual Studio so I could set it to `Debug`.

```
trace: NuGet Command Line Version: 5.8.0.0
info : Adding PackageReference for package '[package_from_source_requiring_authentication]' into project 'C:/[redacted]/testproj.csproj'.
debug: Reading project Dependency Graph
debug: Project Dependency Graph Read
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/[package_from_source_requiring_authentication]/index.json
info :   NotFound https://api.nuget.org/v3/registration5-gz-semver2/[package_from_source_requiring_authentication]/index.json 162ms
error: Unable to load the service index for source [package_source_requiring_authentication]/nuget/v3/index.json.
error:   Response status code does not indicate success: 401 (Unauthorized).
trace: System.AggregateException: One or more errors occurred. (Unable to load the service index for source [package_source_requiring_authentication]/nuget/v3/index.json.) ---> NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source [package_source_requiring_authentication]/nuget/v3/index.json. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
trace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
trace:    at NuGet.Protocol.HttpSource.<>c__DisplayClass14_0`1.<<GetAsync>b__0>d.MoveNext() in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\HttpSource\HttpSource.cs:line 154
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Common\ConcurrencyUtilities.cs:line 96
trace:    at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Common\ConcurrencyUtilities.cs:line 111
trace:    at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\HttpSource\HttpSource.cs:line 78
trace:    at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\Providers\ServiceIndexResourceV3Provider.cs:line 133
trace:    --- End of inner exception stack trace ---
trace:    at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\Providers\ServiceIndexResourceV3Provider.cs:line 170
trace:    at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\Providers\ServiceIndexResourceV3Provider.cs:line 72
trace:    at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\SourceRepository.cs:line 157
trace:    at NuGet.Protocol.PackageMetadataResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\Providers\PackageMetadataResourceV3Provider.cs:line 23
trace:    at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\SourceRepository.cs:line 157
trace:    at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]() in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\SourceRepository.cs:line 140
trace:    at NuGet.CommandLine.XPlat.Utility.AddPackageCommandUtility.GetLatestVersionFromSourceAsync(PackageSource source, ILogger logger, String packageId, Boolean prerelease) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.CommandLine.XPlat\Utility\AddPackageCommandUtility.cs:line 70
trace:    at NuGet.CommandLine.XPlat.Utility.AddPackageCommandUtility.GetLatestVersionFromSourcesAsync(IList`1 sources, ILogger logger, String packageId, Boolean prerelease) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.CommandLine.XPlat\Utility\AddPackageCommandUtility.cs:line 45
trace:    at NuGet.CommandLine.XPlat.AddPackageReferenceCommandRunner.GetLatestVersionAsync(PackageSpec originalPackageSpec, String packageId, ILogger logger, Boolean prerelease) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.CommandLine.XPlat\Commands\PackageReferenceCommands\AddPackageReferenceCommandRunner.cs:line 239
trace:    at NuGet.CommandLine.XPlat.AddPackageReferenceCommandRunner.ExecuteCommand(PackageReferenceArgs packageReferenceArgs, MSBuildAPIUtility msBuild) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.CommandLine.XPlat\Commands\PackageReferenceCommands\AddPackageReferenceCommandRunner.cs:line 108
trace:    --- End of inner exception stack trace ---
trace:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
trace:    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
trace:    at NuGet.CommandLine.XPlat.Program.MainInternal(String[] args, CommandOutputLogger log) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.CommandLine.XPlat\Program.cs:line 97
trace: ---> (Inner Exception #0) NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source [package_source_requiring_authentication]/nuget/v3/index.json. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
trace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
trace:    at NuGet.Protocol.HttpSource.<>c__DisplayClass14_0`1.<<GetAsync>b__0>d.MoveNext() in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\HttpSource\HttpSource.cs:line 154
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Common\ConcurrencyUtilities.cs:line 96
trace:    at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Common\ConcurrencyUtilities.cs:line 111
trace:    at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\HttpSource\HttpSource.cs:line 78
trace:    at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\Providers\ServiceIndexResourceV3Provider.cs:line 133
trace:    --- End of inner exception stack trace ---
trace:    at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\Providers\ServiceIndexResourceV3Provider.cs:line 170
trace:    at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\Providers\ServiceIndexResourceV3Provider.cs:line 72
trace:    at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\SourceRepository.cs:line 157
trace:    at NuGet.Protocol.PackageMetadataResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\Providers\PackageMetadataResourceV3Provider.cs:line 23
trace:    at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\SourceRepository.cs:line 157
trace:    at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]() in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.Protocol\SourceRepository.cs:line 140
trace:    at NuGet.CommandLine.XPlat.Utility.AddPackageCommandUtility.GetLatestVersionFromSourceAsync(PackageSource source, ILogger logger, String packageId, Boolean prerelease) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.CommandLine.XPlat\Utility\AddPackageCommandUtility.cs:line 70
trace:    at NuGet.CommandLine.XPlat.Utility.AddPackageCommandUtility.GetLatestVersionFromSourcesAsync(IList`1 sources, ILogger logger, String packageId, Boolean prerelease) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.CommandLine.XPlat\Utility\AddPackageCommandUtility.cs:line 45
trace:    at NuGet.CommandLine.XPlat.AddPackageReferenceCommandRunner.GetLatestVersionAsync(PackageSpec originalPackageSpec, String packageId, ILogger logger, Boolean prerelease) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.CommandLine.XPlat\Commands\PackageReferenceCommands\AddPackageReferenceCommandRunner.cs:line 239
trace:    at NuGet.CommandLine.XPlat.AddPackageReferenceCommandRunner.ExecuteCommand(PackageReferenceArgs packageReferenceArgs, MSBuildAPIUtility msBuild) in C:\Git\third-party\NuGet.Client\src\NuGet.Core\NuGet.CommandLine.XPlat\Commands\PackageReferenceCommands\AddPackageReferenceCommandRunner.cs:line 108<---
```

**Comment by nkolev92** [comment]
> Question: Would it be worth it reporting this issue in dotnet repo as well, linking to this report?

Nope, this is perfect. 

Thanks for detailed investigation @danieljbfaustino 

You are absolutely right, the credential provider set-up needs to done prior to accessing the sources and that changed with NuGet/NuGet.Client#3480
