### ISSUE TITLE
System.InvalidOperationException: The operation failed as details for project foo.App could not be loaded when trying to update nuget packages

### ISSUE THREAD

**Issue by MagicAndre1981** [NuGet/Home#10371]
After updating VS2019 16.9 Preview 1 to Preview 2, I get error messages when working with nuget package manager UI to update packages.

## Details about Problem

VS version (if appropriate): VS16.9.0 Preview 2.0

OS version: Win10 1803, 17134.1902

## Detailed repro steps so we can see the same problem

1. open sln

2. try to update nuget references

...

### Verbose Logs

```
System.InvalidOperationException: The operation failed as details for project foo.App could not be loaded.
at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.GetPackageSpecsAndAdditionalMessagesAsync(DependencyGraphCacheContext context)
at NuGet.PackageManagement.DependencyGraphRestoreUtility.<GetSolutionRestoreSpecAndAdditionalMessages>d__10.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.PackageManagement.DependencyGraphRestoreUtility.<GetSolutionRestoreSpec>d__9.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at NuGet.PackageManagement.DependencyGraphRestoreUtility.<PreviewRestoreProjectsAsync>d__5.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)at NuGet.PackageManagement.NuGetPackageManager.<PreviewBuildIntegratedProjectsActionsAsync>d__81.MoveNext()
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.PackageManagement.NuGetPackageManager.<PreviewBuildIntegratedProjectActionsAsync>d__80.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at NuGet.PackageManagement.NuGetPackageManager.<PreviewUpdatePackagesForBuildIntegratedAsync>d__59.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.PackageManagement.NuGetPackageManager.<>c__DisplayClass56_1.<<PreviewUpdatePackagesAsync>b__1>d.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)at NuGet.PackageManagement.NuGetPackageManager.<PreviewUpdatePackagesAsync>d__56.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<>c__DisplayClass19_0.<<GetUpdateActionsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<CatchAndRethrowExceptionAsync>d__26`1.MoveNext()
```

**Comment by kartheekp-ms** [comment]
I can't reproduce this issue when I followed below steps.

- Created .NET Core Console App project in VS 2019 16.9 Preview 2
- Opened NuGet Package Manger UI
- Cleared NuGet cache `dotnet nuget locals all --clear`
- Installed and older version of  `Newtonsoft.json` package 
- Updated the same package to latest version

All the above steps completed successfully. can you please upload a sample project or steps to reproduce the issue?

**Comment by MagicAndre1981** [comment]
I opened an already created sln file and haven't created a new one like you.

I checked the [client code and the throw is by design](https://github.com/NuGet/NuGet.Client/blob/f51de2ce3558ae63a4eae275ce42ed1ce6bfa373/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/CpsPackageReferenceProject.cs#L155).

So some cache data failed to read for what ever reason. What kind of cache is this? The already written .csproj.nuget files and project.assets.json and project.nuget.cache?
In this case I use a Directory.Build.props to move obj folder in `solution root\obj\_nuget\projectname\`. Maybe such moving is sometimes causing issues.

Today I opened some solutions and haven't seen this again.

The error messages should be improved in future instead of throwing System.InvalidOperationException which only shows in  VS error list without details. I got the details via activitylog.xml.

**Comment by zkat** [comment]
Not much we can do without a repro here. Sorry you ran into this, and this is clearly an issue. If you ever do run into it again, please go ahead and create a new issue and we'll definitely look into it. Thanks for taking the time to file this!

**Comment by MagicAndre1981** [comment]
> Not much we can do without a repro here. 

As I have no idea which cache files fail to read, I can't give you details. Update the Exception with more details about the files that fail to read.
