### ISSUE TITLE
InvalidOperationException during package restore for Roslyn solution

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#1047]
This is with VS 2015 + Win10 RTM.

1. Open Roslyn.sln on GitHub.com/dotnet/roslyn 
2. Build
3. Look into output window:
```
Error occurred while restoring NuGet packages: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGet.Commands.RestoreCommand.RestoreMSBuildFiles(PackageSpec project, IEnumerable`1 targetGraphs, NuGetv3LocalRepository repository, RemoteWalkContext context)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.BuildIntegratedRestoreUtility.<RestoreAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.BuildIntegratedRestoreUtility.<RestoreAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.BuildIntegratedRestoreUtility.<RestoreAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGetVSExtension.OnBuildPackageRestorer.<BuildIntegratedProjectRestoreAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGetVSExtension.OnBuildPackageRestorer.<RestoreBuildIntegratedProjectsAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGetVSExtension.OnBuildPackageRestorer.<>c__DisplayClass48_0.<<BuildEvents_OnBuildBegin>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGetVSExtension.OnBuildPackageRestorer.BuildEvents_OnBuildBegin(vsBuildScope scope, vsBuildAction Action)
```

**Comment by zhili1208** [comment]
@davkean can you please provide your nuget version? thanks

**Comment by davkean** [comment]
3.1.60717.741.

**Comment by zhili1208** [comment]
@davkean  can't repro this. I got a clean machine, git clone Roslyn solution, ran .nuget\NuGetRestore.ps1, open solution and build, everything works well. 
did you run the NuGetRestore.ps1？

**Comment by davkean** [comment]
No I didn't run NuGetRestore.ps1. Can you try it without that (delete .nuget from your user profile)?

**Comment by zhili1208** [comment]
I tried that, but still can't get repro. I'm wondering how those things can be build without run NuGetRestore.ps1. looks like this script restored packages like System.Collections.Immutable.
when I build the solution without using NuGetRestore.ps1, I will got error like can't find system.collections.immutable....

**Comment by davkean** [comment]
NuGet VS integration itself should be attempting to restore those from NuGet.org, or there would be another bug here.

**Comment by zhili1208** [comment]
the problem is they didn't specify any of those packages in project package.config files. How NuGet VS can restore some packages which don't exist in project package.config.

**Comment by davkean** [comment]
Hmm, I see. 

I've already run NuGetRestore.ps1 on my box now, and I'm still running into this:

Error occurred while restoring NuGet packages: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGet.Commands.RestoreCommand.RestoreMSBuildFiles(PackageSpec project, IEnumerable`1 targetGraphs, NuGetv3LocalRepository repository, RemoteWalkContext context)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.BuildIntegratedRestoreUtility.<RestoreAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.BuildIntegratedRestoreUtility.<RestoreAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.BuildIntegratedRestoreUtility.<RestoreAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGetVSExtension.OnBuildPackageRestorer.<BuildIntegratedProjectRestoreAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGetVSExtension.OnBuildPackageRestorer.<RestoreBuildIntegratedProjectsAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGetVSExtension.OnBuildPackageRestorer.<>c__DisplayClass48_0.<<BuildEvents_OnBuildBegin>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGetVSExtension.OnBuildPackageRestorer.BuildEvents_OnBuildBegin(vsBuildScope scope, vsBuildAction Action)

I've got diagnostic build turned on - __Tools__ -> __Options__ -> __Projects and Solutions__ -> __Build and Run__ -> __MSBuild project build output verbosity__, perhaps the difference?

**Comment by zhili1208** [comment]
thanks, looks like a bug somewhere, is there any project.json files in your solution?

**Comment by davkean** [comment]
Yes, for example, https://github.com/dotnet/roslyn/tree/master/src/Compilers/CSharp/CscCore

**Comment by zhili1208** [comment]
please pull latest Roslyn code, looks like they already fixed this

**Comment by davkean** [comment]
Thanks, but NuGet should handle this and not output these (unhelpful) errors into the Output window. Instead, it should say that "frameworks" is missing.

**Comment by zhili1208** [comment]
tracked the message issue in https://github.com/NuGet/Home/issues/1039
