### ISSUE TITLE
ServiceActivationFailedException: Activating the "Microsoft.VisualStudio.NuGet.NuGetProjectService (1.0)" service failed

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#10520]
Tracking issue for AzDO bug 1240336.

No repro steps (yet).

```
10/29/2020 12:13:29 Coordinated Universal Time: Error : 1 :[devenv:1344] Unexpected exception: System.AggregateException: One or more errors occurred.
 ---> Microsoft.ServiceHub.Framework.ServiceActivationFailedException: Activating the "Microsoft.VisualStudio.NuGet.NuGetProjectService (1.0)" service failed. ---> System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.VisualStudio.Shell.Interop.IVsShell7.LoadPackageAsync(Guid& guidPackage)
   at Microsoft.VisualStudio.Services.VSGlobalBrokeredServiceContainer.PackageServiceRegistration.<LoadProfferingPackageAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.<LoadProfferingPackageAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.<TryGetProfferingSourceAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.<GetProxyAsync>d__19`1.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.<GetProxyAsync>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService.<ProcessWorkQueueWorkerAsync>d__33.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.ErrorReporting.WatsonExtensions.SetCallstackIfEmpty(Exception exception)
---> (Inner Exception #0) Microsoft.ServiceHub.Framework.ServiceActivationFailedException: Activating the "Microsoft.VisualStudio.NuGet.NuGetProjectService (1.0)" service failed. ---> System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.VisualStudio.Shell.Interop.IVsShell7.LoadPackageAsync(Guid& guidPackage)
   at Microsoft.VisualStudio.Services.VSGlobalBrokeredServiceContainer.PackageServiceRegistration.<LoadProfferingPackageAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.<LoadProfferingPackageAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.<TryGetProfferingSourceAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.<GetProxyAsync>d__19`1.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.<GetProxyAsync>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by ParthP-Adappt** [comment]
Microsoft.ServiceHub.Framework.ServiceActivationFailedException: 
Activating the &quot;Microsoft.VisualStudio.FileSystem.LocalFileSystemProvider (1.0)&quot; 
service failed. ---&gt; System.InvalidCastException: Unable to cast object of type &apos;
Microsoft.VisualStudio.PlatformUI.Packages.FileSystem.LocalFileSystemProvider&apos; to type &apos;Microsoft.VisualStudio.RpcContracts.FileSystem.IRemoteFileSystemProvider&apos;
.&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.ProfferedServiceFactory.&lt;GetProxyAsync&gt;
d__28`1.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;  
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   
 at System.Threading.Tasks.ValueTask`1.get_Result()&#x000D;&#x000A;   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()&#x000D;&#x000A;   
 at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.&lt;GetProxyAsync&gt;d__19`1.MoveNext()&#x000D;&#x000A;  
 --- End of inner exception stack trace ---</description>

**Comment by zivkan** [comment]
@parth1408 NuGet doesn't use Visual Studio's FileSystem abstraction (IRemoteFileSystemProvider, LocalFileSystemProvider). Therefore, I believe you are reporting a problem not related to NuGet.


I recommend you [report that error with Visual Studio's report a problem feature](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022).  None of types reported in the error message you copy-pasted are NuGet, and therefore I don't believe we're able to help with this.

**Comment by zivkan** [comment]
AzDO bug 1240336 was closed in April.  Closing this issue.
