### ISSUE TITLE
Nuget replacement tokens not reading from AssemblyInfo class unless you Unblock nuget.exe in explorer

### ISSUE THREAD

**Issue by fmir864** [NuGet/Home#10630]
## Details about Problem

NuGet product used: NuGet.exe

Product version: 5.9.0

Worked before? If so, with which NuGet version: 5.5.1

## Repro steps and/or sample project

1. Create a C# class library Project with .net framework 4.8
2. Modify `AssemblyInfo` as follows;

```
[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion("2.0.0.0")]
[assembly: AssemblyInformationalVersion("2.0.0")]
```
3. Create a `nuspec` file using below command
`nuget spec MyProject.csproj`

4. `nuspec` generated as below;

```
<?xml version="1.0" encoding="utf-8"?>
<package >
  <metadata>
    <id>$id$</id>
    <version>$version$</version>
    <title>$title$</title>
    <authors>$author$</authors>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>$description$</description>
    <releaseNotes></releaseNotes>
    <copyright>$copyright$</copyright>
    <tags>tags1 tags2</tags>
  </metadata>
</package>
```

5. Pack with following command;

`nuget pack .\MyProject.csproj -verbosity detailed `

6. Getting an error as follows;

```
NuGet Version: 5.9.0.7134
Attempting to build package from 'MyProject.csproj'.
MSBuild auto-detection: using msbuild version '16.4.0.56107' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from 'E:\Clone\MyProject\MyProject\bin\Debug'.
Could not load file or assembly 'file:///E:\bin\nuget.exe' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Using 'MyProject.nuspec' for metadata.
Authors is required.
Description is required.
System.Exception: Authors is required.
Description is required.
   at NuGet.Packaging.Manifest.Validate(Manifest manifest)
   at NuGet.Packaging.Manifest.ReadFrom(Stream stream, Func`2 propertyProvider, Boolean validateSchema)
   at NuGet.CommandLine.ProjectFactory.ProcessNuspec(PackageBuilder builder, String basePath)
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

7. I gave values for author and description in the `nuspec` file and ran `pack` again (Given in `AssemblyInfo` but it's not replacing the tokens)

```
NuGet Version: 5.9.0.7134
Attempting to build package from 'MyProject.csproj'.
MSBuild auto-detection: using msbuild version '16.4.0.56107' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from 'E:\Clone\MyProject\MyProject\bin\Debug'.
Could not load file or assembly 'file:///E:\bin\nuget.exe' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Using 'MyProject.nuspec' for metadata.
Add file 'E:\Clone\MyProject\MyProject\bin\Debug\MyProject.dll' to package as 'lib\net48\MyProject.dll'
Found packages.config. Using packages listed as dependencies

Id: MyProject
Version: 1.0.0
Authors: AA
Description: AA
Tags: tags1, tags2
Dependencies: log4net [2.0.12, ), Microsoft.ReportingServices.ReportViewerControl.Winforms [150.1440.0, ), Microsoft.SqlServer.Types [14.0.1016.290, ), System.Runtime.CompilerServices.Unsafe [5.0.0, ), System.Windows.Interactivity.WPF [2.0.20525, ), Unity [5.11.10, )

Added file '[Content_Types].xml'.
Added file '_rels/.rels'.
Added file 'MyProject.nuspec'.
Added file 'lib/net48/MyProject.dll'.
Added file 'package/services/metadata/core-properties/3e75407b72454e6eb1bcbe849f8fcc10.psmdcp'.

WARNING: NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below:
- Add a dependency group for .NETFramework4.8 to the nuspec
Successfully created package 'E:\Clone\MyProject\MyProject\MyProject.1.0.0.nupkg'.
```

8. Now `nupkg` created but always with version 1.0.0, the error I've noticed is `Could not load file or assembly 'file:///E:\bin\nuget.exe' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)`. This somehow ignores the metadata tokens replaced from `AssemblyInfo`
9. Tested with 5.7, 5.8.1 as well, same result but 5.5.1 works fine

### Verbose Logs

```
NuGet Version: 5.9.0.7134
Attempting to build package from 'MyProject.csproj'.
MSBuild auto-detection: using msbuild version '16.4.0.56107' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from 'E:\Clone\MyProject\MyProject\bin\Debug'.
Could not load file or assembly 'file:///E:\bin\nuget.exe' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Using 'MyProject.nuspec' for metadata.
Authors is required.
Description is required.
System.Exception: Authors is required.
Description is required.
   at NuGet.Packaging.Manifest.Validate(Manifest manifest)
   at NuGet.Packaging.Manifest.ReadFrom(Stream stream, Func`2 propertyProvider, Boolean validateSchema)
   at NuGet.CommandLine.ProjectFactory.ProcessNuspec(PackageBuilder builder, String basePath)
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by rrelyea** [comment]
i debugged this in nuget.exe and saw it working. but also tried nuget.exe 5.9, and it was failing.
then i searched for existing issues, cause i thought it might have been fixed in a recent build.

see fix here: 
https://github.com/NuGet/Home/issues/9954#issuecomment-754952859

(go "unblock" the download of nuget.exe)..and it should work as needed.
