### ISSUE TITLE
Unable to push NuGet packages to GitHub Packages from Azure Pipelines, Error 400

### ISSUE THREAD

**Issue by arashcomsense** [NuGet/Home#10638]
## Details about Problem

We're running the build pipeline on an in-house hosted build agent (Windows) and it fails to push the generated NuGet packages to GitHub Package due to error 400 (Bad Request). 

Product version: 

Worked before? If so, with which NuGet version: Never

Simply include the following script in your YAML file:

```
task: PowerShell@2
  displayName: 'PowerShell to push the NuGet package to GitHub'
  inputs:
    targetType: 'inline'
    script: 'dotnet nuget push "$(Build.ArtifactStagingDirectory)\*.nupkg" --source "https://nuget.pkg.github.com/MyMaskedRepo/index.json" --api-key 1112233-abcdef-secret-PAT-key --skip-duplicate'

```
**Note 1:** `MyMaskedRepo` is just a fictitious name to hide the real private repo's name.
**Note 2:** The command listed above works fine from the development computer when trying to push the NuGet package manually to GitHub Packages.

### Verbose Logs

```
2021-03-08T15:53:31.0145937Z System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
2021-03-08T15:53:31.0146506Z    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
2021-03-08T15:53:31.0147482Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.EnsureSuccessStatusCode(HttpResponseMessage response, Nullable`1 codeNotToThrow, ILogger logger)
2021-03-08T15:53:31.0148192Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c__DisplayClass24_0.<PushPackageToServer>b__0(HttpResponseMessage response)
2021-03-08T15:53:31.0148756Z    at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__19`1.MoveNext()
2021-03-08T15:53:31.0149225Z --- End of stack trace from previous location where exception was thrown ---
2021-03-08T15:53:31.0149684Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-03-08T15:53:31.0150185Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-03-08T15:53:31.0150710Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__24.MoveNext()
2021-03-08T15:53:31.0151208Z --- End of stack trace from previous location where exception was thrown ---
2021-03-08T15:53:31.0151676Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-03-08T15:53:31.0152170Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-03-08T15:53:31.0152687Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__20.MoveNext()
2021-03-08T15:53:31.0153179Z --- End of stack trace from previous location where exception was thrown ---
2021-03-08T15:53:31.0153636Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-03-08T15:53:31.0154133Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-03-08T15:53:31.0154635Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushAll>d__19.MoveNext()
2021-03-08T15:53:31.0155116Z --- End of stack trace from previous location where exception was thrown ---
2021-03-08T15:53:31.0155570Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-03-08T15:53:31.0156232Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-03-08T15:53:31.0156763Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__18.MoveNext()
2021-03-08T15:53:31.0157280Z --- End of stack trace from previous location where exception was thrown ---
2021-03-08T15:53:31.0157746Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-03-08T15:53:31.0158250Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-03-08T15:53:31.0158764Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__14.MoveNext()
2021-03-08T15:53:31.0159220Z --- End of stack trace from previous location where exception was thrown ---
2021-03-08T15:53:31.0159676Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-03-08T15:53:31.0160174Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-03-08T15:53:31.0160648Z    at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
2021-03-08T15:53:31.0161073Z --- End of stack trace from previous location where exception was thrown ---
2021-03-08T15:53:31.0161527Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-03-08T15:53:31.0162021Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-03-08T15:53:31.0162523Z    at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__36.MoveNext()
2021-03-08T15:53:31.0162972Z --- End of stack trace from previous location where exception was thrown ---
2021-03-08T15:53:31.0163420Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-03-08T15:53:31.0163913Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-03-08T15:53:31.0164355Z    at NuGet.CommandLine.Command.Execute()
2021-03-08T15:53:31.0164759Z    at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
2021-03-08T15:53:31.0165313Z   PUT https://nuget.pkg.github.com/MyMaskedRepo/
2021-03-08T15:53:31.0166019Z WARNING: No destination repository detected. Ensure the source project has a 'RepositoryUrl' property defined. If you're using a nuspec file, ensure that it has a repository element with the required 'type' and 'url' attributes.
2021-03-08T15:53:31.0166753Z   BadRequest https://nuget.pkg.github.com/MyMaskedRepo// 164ms
```

**Comment by aortiz-msft** [comment]
Hi there. We think GPR requires the RepositoryUrl for a successful push. See: WARNING: No destination repository detected. Ensure the source project has a 'RepositoryUrl' property defined. If you're using a nuspec file, ensure that it has a repository element with the required 'type' and 'url' attributes.

**Comment by aortiz-msft** [comment]
We are closing for now but feel free to comment if that does not work for you. Thanks!

**Comment by arashcomsense** [comment]
@aortiz-msft Please do not close this issue as the issue still persists. Our nuspec file has had the repository info per the following definition: `<repository url=https://github.com/masked1/masked2 />`. I changed it to `<repository type="git" url="https://github.com/masked1/masked2"/>` and got the following error message **(please do continue reading my comments after the error message)**:

> 2021-03-12T12:17:39.3378695Z ##[error]The nuget command failed with exit code(1) and error(Response status code does not indicate success: 401 (Unauthorized).
> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
>    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
>    at NuGet.Protocol.Core.Types.PackageUpdateResource.EnsureSuccessStatusCode(HttpResponseMessage response, Nullable`1 codeNotToThrow, ILogger logger)
>    at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c__DisplayClass24_0.<PushPackageToServer>b__0(HttpResponseMessage response)
>    at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__19`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__24.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__20.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushAll>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__18.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__14.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__36.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NuGet.CommandLine.Command.Execute()
>    at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args))
> 2021-03-12T12:17:39.3408301Z ##[debug]Processed: ##vso[task.issue type=error;]The nuget command failed with exit code(1) and error(Response status code does not indicate success: 401 (Unauthorized).%0D%0ASystem.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).%0D%0A   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()%0D%0A   at NuGet.Protocol.Core.Types.PackageUpdateResource.EnsureSuccessStatusCode(HttpResponseMessage response, Nullable`1 codeNotToThrow, ILogger logger)%0D%0A   at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c__DisplayClass24_0.<PushPackageToServer>b__0(HttpResponseMessage response)%0D%0A   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__19`1.MoveNext()%0D%0A--- End of stack trace from previous location where exception was thrown ---%0D%0A   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()%0D%0A   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)%0D%0A   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__24.MoveNext()%0D%0A--- End of stack trace from previous location where exception was thrown ---%0D%0A   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()%0D%0A   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)%0D%0A   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__20.MoveNext()%0D%0A--- End of stack trace from previous location where exception was thrown ---%0D%0A   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()%0D%0A   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)%0D%0A   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushAll>d__19.MoveNext()%0D%0A--- End of stack trace from previous location where exception was thrown ---%0D%0A   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()%0D%0A   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)%0D%0A   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__18.MoveNext()%0D%0A--- End of stack trace from previous location where exception was thrown ---%0D%0A   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()%0D%0A   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)%0D%0A   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__14.MoveNext()%0D%0A--- End of stack trace from previous location where exception was thrown ---%0D%0A   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()%0D%0A   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)%0D%0A   at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()%0D%0A--- End of stack trace from previous location where exception was thrown ---%0D%0A   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()%0D%0A   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)%0D%0A   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__36.MoveNext()%0D%0A--- End of stack trace from previous location where exception was thrown ---%0D%0A   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()%0D%0A   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)%0D%0A   at NuGet.CommandLine.Command.Execute()%0D%0A   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args))

Microsoft Azure DevOps team is already aware of this issue and they were able to reproduce it as well. Please have a look at[ this thread too](https://developercommunity.visualstudio.com/t/azure-devops-build-pipeline-is-unable-to-push-nuge/1318028?from=email). I would contact with your colleagues at Microsoft to try to resolve this issue collaboratively. As a side note, I am able to push the packages manually to GitHub packages successfully from my development machine but Azure DevOps pipeline fails.
