### ISSUE TITLE
nuget 5.9 pack crashes

### ISSUE THREAD

**Issue by adnan-kamili** [NuGet/Home#10685]
## Details about Problem

NuGet product used (NuGet.exe):

Product version: 5.9.0

Worked before? If so, with which NuGet version: 5.8.1

## Repro steps and/or sample project

Here is the error caused in 5.9.0:

https://github.com/cryptlex/lexactivator-dotnet/runs/2181577286?check_suite_focus=true 

in Pack Nuget Package step.

and it worked till 5.8.1

https://github.com/cryptlex/lexactivator-dotnet/runs/1976606695?check_suite_focus=true 

### Verbose Logs
```
nuget pack src\Cryptlex.LexActivator\Cryptlex.LexActivator.nuspec -NonInteractive -OutputDirectory nupkg -Properties Configuration=Release -Verbosity Detailed
NuGet Version: 5.9.0.7134
Attempting to build package from 'Cryptlex.LexActivator.nuspec'.
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Packaging.PackageBuilder.<>c.<ValidateReferenceAssemblies>b__173_1(NuGet.Frameworks1204688.NuGetFramework groupFramework)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at NuGet.Packaging.PackageBuilder.ValidateReferenceAssemblies(IEnumerable`1 files, IEnumerable`1 packageAssemblyReferences)
   at NuGet.Packaging.PackageBuilder.Save(Stream stream)
   at NuGet.Commands.PackCommandRunner.BuildPackage(PackageBuilder builder, String outputPath, Boolean symbolsPackage)
   at NuGet.Commands.PackCommandRunner.BuildFromNuspec(String path)
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
Error: Process completed with exit code 1.
```

**Comment by heng-liu** [comment]
Hi @adnan-kamili , thanks for reporting this issue!
I tried to use a class library project but failed to repro.
May I have a repro project and repro steps so that we could repro locally? Thanks.

**Comment by adnan-kamili** [comment]
Yes, here it is:

https://github.com/cryptlex/lexactivator-dotnet

**Comment by heng-liu** [comment]
I could repro with following steps:
1. Run `git clone https://github.com/cryptlex/lexactivator-dotnet.git`
2. Run `cd C:\repos\lexactivator-dotnet\src\Cryptlex.LexActivator`
3. Run `msbuild /t:restore`
4. Run `cd C:\repos\lexactivator-dotnet`
5. Run `msbuild Cryptlex.LexActivator.sln /p:platform="Any CPU" /p:configuration="Release" /p:VisualStudioVersion="16.0" `
6. Run script: `.\post-build.ps1`
7. Download nuget.exe 5.9.0, run `nuget pack src\Cryptlex.LexActivator\Cryptlex.LexActivator.nuspec -NonInteractive -OutputDirectory nupkg -Properties Configuration=Release -Verbosity Detailed`
8. Could see the same error with that in the description.
9. If doing from 1-6 again and use nuget.exe 5.8.0 in step 7, the pack is successful. The output is:
```
NuGet Version: 5.8.0.6930
Attempting to build package from 'Cryptlex.LexActivator.nuspec'.

Id: Cryptlex.LexActivator
Version: 3.14.6
Authors: Cryptlex
Description: Cryptlex lets you license your software apps effortlessly. You can easily generate license keys using the REST API or Dashboard and validate the license keys in your software apps using LexActivator (Cryptlex client library).
Project Url: https://cryptlex.com/
Tags: lexactivator, cryptlex, licensing-library
Dependencies:

Added file '[Content_Types].xml'.
Added file '_rels/.rels'.
Added file 'build/Cryptlex.LexActivator.targets'.
Added file 'Cryptlex.LexActivator.nuspec'.
Added file 'lib/net45/Cryptlex.LexActivator.dll'.
Added file 'lib/net45/Cryptlex.LexActivator.xml'.
Added file 'lib/netstandard1.1/Cryptlex.LexActivator.dll'.
Added file 'lib/netstandard1.1/Cryptlex.LexActivator.xml'.
Added file 'package/services/metadata/core-properties/6b06eaddd0e04f6aa3ed606ccbefc1f0.psmdcp'.
Added file 'runtimes/linux-musl-x64/native/libLexActivator.so'.
Added file 'runtimes/linux-x64/native/libLexActivator.so'.
Added file 'runtimes/osx-x64/native/libLexActivator.dylib'.
Added file 'runtimes/win-x64/native/LexActivator.dll'.
Added file 'runtimes/win-x86/native/LexActivator32.dll'.

WARNING: NU5131: References were found in the nuspec, but some reference assemblies were not found in both the nuspec and ref folder. Add the following reference assemblies:
- Add Cryptlex.LexActivator.dll to the ref/any/ directory

Successfully created package 'C:\repos\lexactivator-dotnet\nupkg\Cryptlex.LexActivator.3.14.6.nupkg'.
```

**Comment by nkolev92** [comment]
Duplicate might be available in https://github.com/NuGet/Home/issues/10663
