### ISSUE TITLE
CpsPackageReferenceProjectTests.TestPackageManager_PreviewProjectsUninstallPackageAsync_AllProjects_UninstallExistingPackage_Success test is flaky

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#10719]
`TestPackageManager_PreviewProjectsUninstallPackageAsync_AllProjects_UninstallExistingPackage_Success` is flaky. It failed on few [1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4615033&view=ms.vss-test-web.build-test-results-tab&runId=20317228&resultId=115623&paneView=debug), [2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4596916&view=ms.vss-test-web.build-test-results-tab&runId=20129492&resultId=115718), [3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4598257&view=ms.vss-test-web.build-test-results-tab&runId=20169506&resultId=115547) builds but passed on re-run.

I reproduced it only once while debugging the test in VS and here is the call stack. 

The `predicate` used in the following line of code is throwing that exception because `string` is null. I tried 3 or 4 times but reproduced this exception only once.

https://github.com/NuGet/NuGet.Client/blob/606dcb613eefc5d28cc2af29176f76105f588ff8/test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/CpsPackageReferenceProjectTests.cs#L2442

```
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.1 (32-bit Desktop .NET 4.0.30319.42000)
[xUnit.net 00:00:02.00]   Starting:    NuGet.PackageManagement.VisualStudio.Test
[xUnit.net 00:04:29.74]     NuGet.PackageManagement.VisualStudio.Test.CpsPackageReferenceProjectTests.TestPackageManager_PreviewProjectsUninstallPackageAsync_AllProjects_UninstallExistingPackage_Success [FAIL]
[xUnit.net 00:04:29.74]       System.NullReferenceException : Object reference not set to an instance of an object.
[xUnit.net 00:04:29.74]       Stack Trace:
[xUnit.net 00:04:29.74]         C:\repos\NuGet.Client\test\NuGet.Clients.Tests\NuGet.PackageManagement.VisualStudio.Test\CpsPackageReferenceProjectTests.cs(2442,0): at NuGet.PackageManagement.VisualStudio.Test.CpsPackageReferenceProjectTests.<>c.<TestPackageManager_PreviewProjectsUninstallPackageAsync_AllProjects_UninstallExistingPackage_Success>b__22_2(String l)
[xUnit.net 00:04:29.74]            at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
[xUnit.net 00:04:29.74]            at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
[xUnit.net 00:04:29.74]            at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
[xUnit.net 00:04:29.74]         C:\repos\NuGet.Client\test\NuGet.Clients.Tests\NuGet.PackageManagement.VisualStudio.Test\CpsPackageReferenceProjectTests.cs(2442,0): at NuGet.PackageManagement.VisualStudio.Test.CpsPackageReferenceProjectTests.<TestPackageManager_PreviewProjectsUninstallPackageAsync_AllProjects_UninstallExistingPackage_Success>d__22.MoveNext()
[xUnit.net 00:04:29.74]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:04:29.74]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:04:29.74]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:04:29.74]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:04:29.74]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:04:29.74]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:04:29.74]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:04:29.74]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:04:29.74]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:04:29.76]   Finished:    NuGet.PackageManagement.VisualStudio.Test
========== Test run finished: 1 Tests (0 Passed, 1 Failed, 0 Skipped) run in 4.9 min =========
```

It looks like this test was added recently in https://github.com/NuGet/NuGet.Client/pull/3703.

@erdembayar any idea what could have caused this issue?

**Comment by erdembayar** [comment]
@kartheekp-ms 
I think this one is connected: https://github.com/NuGet/NuGet.Client/pull/3800#pullrequestreview-552054122
There are many activities were going on that (CpsPackageReferenceProject.cs file), but don't know exactly which one is causing the failure. I suspect [weakReference](https://github.com/NuGet/NuGet.Client/blob/a0671e946ce71dc59def5cc8a67c6457d66f33bf/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/CpsPackageReferenceProject.cs#L241) has something to do with it.

**Comment by donnie-msft** [comment]
After 100 runs of this test, there were 5 failures.
The original error occurred 1 time.

The following error occurred 4 times:
**System.IndexOutOfRangeException : Index was outside the bounds of the array.**

```
NuGet.PackageManagement.VisualStudio.Test.CpsPackageReferenceProjectTests.TestPackageManager_PreviewProjectsUninstallPackageAsync_AllProjects_UninstallExistingPackage_Success [STARTING]
    NuGet.PackageManagement.VisualStudio.Test.CpsPackageReferenceProjectTests.TestPackageManager_PreviewProjectsUninstallPackageAsync_AllProjects_UninstallExistingPackage_Success [FAIL]
      System.IndexOutOfRangeException : Index was outside the bounds of the array.
      Stack Trace:
           at System.Collections.Generic.List`1.Add(T item)
        test\TestUtilities\Test.Utility\ProjectManagement\TestNuGetProjectContext.cs(41,0): at Test.Utility.TestNuGetProjectContext.Log(ILogMessage message)
        src\NuGet.Core\NuGet.PackageManagement\ProjectContextLogger.cs(24,0): at NuGet.PackageManagement.ProjectContextLogger.Log(ILogMessage message)
        src\NuGet.Core\NuGet.Common\Logging\LoggerBase.cs(29,0): at NuGet.Common.LoggerBase.Log(LogLevel level, String data)
        src\NuGet.Core\NuGet.Common\Logging\LoggerBase.cs(70,0): at NuGet.Common.LoggerBase.LogVerbose(String data)
        src\NuGet.Core\NuGet.Commands\RestoreCommand\RestoreRunner.cs(240,0): at NuGet.Commands.RestoreRunner.<ExecuteAsync>d__7.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        src\NuGet.Core\NuGet.Commands\RestoreCommand\RestoreRunner.cs(314,0): at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__10.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        src\NuGet.Core\NuGet.Commands\RestoreCommand\RestoreRunner.cs(146,0): at NuGet.Commands.RestoreRunner.<RunWithoutCommit>d__3.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        src\NuGet.Core\NuGet.PackageManagement\BuildIntegration\DependencyGraphRestoreUtility.cs(238,0): at NuGet.PackageManagement.DependencyGraphRestoreUtility.<PreviewRestoreProjectsAsync>d__5.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        src\NuGet.Core\NuGet.PackageManagement\NuGetPackageManager.cs(2922,0): at NuGet.PackageManagement.NuGetPackageManager.<PreviewBuildIntegratedProjectsActionsAsync>d__81.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        src\NuGet.Core\NuGet.PackageManagement\NuGetPackageManager.cs(2135,0): at NuGet.PackageManagement.NuGetPackageManager.<PreviewBuildIntegratedNuGetProjectsUninstallPackageInternalAsync>d__72.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        src\NuGet.Core\NuGet.PackageManagement\NuGetPackageManager.cs(2070,0): at NuGet.PackageManagement.NuGetPackageManager.<PreviewProjectsUninstallPackageAsync>d__71.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        test\NuGet.Clients.Tests\NuGet.PackageManagement.VisualStudio.Test\CpsPackageReferenceProjectTests.cs(2420,0): at NuGet.PackageManagement.VisualStudio.Test.CpsPackageReferenceProjectTests.<TestPackageManager_PreviewProjectsUninstallPackageAsync_AllProjects_UninstallExistingPackage_Success>d__22.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    NuGet.PackageManagement.VisualStudio.Test.CpsPackageReferenceProjectTests.TestPackageManager_PreviewProjectsUninstallPackageAsync_AllProjects_UninstallExistingPackage_Success [FINISHED] Time: 2.7512579s
  Finished:    NuGet.PackageManagement.VisualStudio.Test
=== TEST EXECUTION SUMMARY ===
   NuGet.PackageManagement.VisualStudio.Test  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 2.873s
xUnit.net Console Runner v2.4.1 (64-bit Desktop .NET 4.7, runtime: 4.0.30319.42000)
```

**Comment by erdembayar** [comment]
> After 100 runs of this test, there were 5 failures.
> The original error occurred 1 time.
> 
> The following error occurred 4 times:
> **System.IndexOutOfRangeException : Index was outside the bounds of the array.**
> 
> ```
> NuGet.PackageManagement.VisualStudio.Test.CpsPackageReferenceProjectTests.TestPackageManager_PreviewProjectsUninstallPackageAsync_AllProjects_UninstallExistingPackage_Success [STARTING]
>     NuGet.PackageManagement.VisualStudio.Test.CpsPackageReferenceProjectTests.TestPackageManager_PreviewProjectsUninstallPackageAsync_AllProjects_UninstallExistingPackage_Success [FAIL]
>       System.IndexOutOfRangeException : Index was outside the bounds of the array.
>       Stack Trace:

Thank you for looking into this issue.
Did you get this call stack log from your local or CI/CD?
