### ISSUE TITLE
DirectoryNotFoundException in PackTask PathResolver

### ISSUE THREAD

**Issue by abeehler** [NuGet/Home#10716]
## Details about Problem

NuGet product used: dotnet.exe

Product version: 5.0.201

## Repro steps and/or sample project

I'm relatively new to nuget package creation.  I'm attempting to pack a .NET Standard project with 3rd party .NET Framework dll dependencies.
csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net472</TargetFrameworks>
    <PackageTags>Laserfiche SEA ESI "Texas A&amp;M"</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <version>1.0.1.5</version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.1.5</FileVersion>
    <Company>Texas A&amp;M System Offices</Company>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
    <!--<IncludeSymbols>true</IncludeSymbols>-->
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <NuspecFile>SEALaserfiche.nuspec</NuspecFile>
  </PropertyGroup>
```

SEALaserfiche.nuspec:

```
<?xml version="1.0" encoding="utf-8" ?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>SEALaserfiche</id>
    <version>1.0.1.5</version>
    <authors>Andrew Beehler</authors>
    <description>Test</description>
    <copyright>Test</copyright>
    <dependencies>
      <group targetFramework=".NETFramework4.7.2" />
      <group targetFramework=".NETStandard2.0" />
    </dependencies>
  </metadata>
  <files>
    <file src="bin\$config$\netstandard2.0\*.dll" target="lib\netstandard2.0\" />
    <file src="bin\$config$\net472\*.dll" target="lib\net472\" />
  </files>
</package>
```

I attempt to run the following command:

```dotnet pack -p:config=debug```

...and get this error: `"C:\Program Files\dotnet\sdk\5.0.201\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): error : Could not find a part of the path 'C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\bin\netstandard2.0'."`

not sure why it's not looking in "\bin\debug\netstandard2.0"

### Verbose Logs

Here's the section of the output we're probably interested in.  shows the stack trace.  tried going through nuget code on github.  have not yet been able to determine where the "\bin\netstandard2.0" is coming from; why it doesn't have "\debug\" in the path.

```
Using "PackTask" task from assembly "C:\Program Files\dotnet\sdk\5.0.201\Sdks\NuGet.Build.Tasks.Pack\build
CrossTargeting\..\CoreCLR\NuGet.Build.Tasks.Pack.dll".
                   Task "PackTask" (TaskId:100)
                     Task Parameter:
                         TargetPathsToSymbols=
                             C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\obj\Debug\net472\SEALaserfich
e.pdb
                                     FinalOutputPath=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\bin\D
ebug\net472\SEALaserfiche.pdb
                                     MSBuildSourceProjectFile=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfi
che\SEALaserfiche.csproj
                                     MSBuildSourceTargetName=_GetDebugSymbolsWithTfm
                                     OriginalItemSpec=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\SEAL
aserfiche.csproj
                                     TargetFramework=net472
                                     TargetPath=SEALaserfiche.pdb
                             C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\obj\Debug\netstandard2.0\SEAL
aserfiche.pdb
                                     FinalOutputPath=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\bin\D
ebug\netstandard2.0\SEALaserfiche.pdb
                                     MSBuildSourceProjectFile=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfi
che\SEALaserfiche.csproj
                                     MSBuildSourceTargetName=_GetDebugSymbolsWithTfm
                                     OriginalItemSpec=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\SEAL
aserfiche.csproj
                                     TargetFramework=netstandard2.0
                                     TargetPath=SEALaserfiche.pdb (TaskId:100)
                     Task Parameter:AssemblyName=SEALaserfiche (TaskId:100)
                     Task Parameter:Tags=Laserfiche SEA ESI "Texas A&M" (TaskId:100)
                     Task Parameter:RequireLicenseAcceptance=False (TaskId:100)
                     Task Parameter:RestoreOutputPath=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\obj\
 (TaskId:100)
                     Task Parameter:Authors=SEALaserfiche (TaskId:100)
                     Task Parameter:TreatWarningsAsErrors=false (TaskId:100)
                     Task Parameter:PackageId=SEALaserfiche (TaskId:100)
                     Task Parameter:
                         AllowedOutputExtensionsInPackageBuildOutputFolder=
                             .dll
                             .exe
                             .winmd
                             .json
                             .pri
                             .xml (TaskId:100)
                     Task Parameter:AllowedOutputExtensionsInSymbolsPackageBuildOutputFolder=.pdb (TaskId:100)
                     Task Parameter:SymbolPackageFormat=snupkg (TaskId:100)
                     Task Parameter:ContinuePackingAfterGeneratingNuspec=True (TaskId:100)
                     Task Parameter:WarningsAsErrors=;NU1605 (TaskId:100)
                     Task Parameter:IncludeBuildOutput=True (TaskId:100)
                     Task Parameter:PackageVersion=1.0.1.5 (TaskId:100)
                     Task Parameter:PackageOutputPath=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\bin\
Debug\ (TaskId:100)
                     Task Parameter:
                         TargetFrameworks=
                             net472
                             netstandard2.0 (TaskId:100)
                     Task Parameter:Description=Package Description (TaskId:100)
                     Task Parameter:NoWarn=1701;1702 (TaskId:100)
                     Task Parameter:NuspecFile=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\SEALaserfic
he.nuspec (TaskId:100)
                     Task Parameter:BuildOutputFolders=lib (TaskId:100)
                     Task Parameter:
                         BuildOutputInPackage=
                             C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\obj\Debug\net472\SEALaserfich
e.dll
                                     FinalOutputPath=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\bin\D
ebug\net472\SEALaserfiche.dll
                                     IsKeyOutput=true
                                     MSBuildSourceProjectFile=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfi
che\SEALaserfiche.csproj
                                     MSBuildSourceTargetName=_GetBuildOutputFilesWithTfm
                                     OriginalItemSpec=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\obj\
Debug\net472\SEALaserfiche.dll
                                     TargetFramework=net472
                                     TargetPath=SEALaserfiche.dll
                             C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\obj\Debug\netstandard2.0\SEAL
aserfiche.dll
                                     FinalOutputPath=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\bin\D
ebug\netstandard2.0\SEALaserfiche.dll
                                     IsKeyOutput=true
                                     MSBuildSourceProjectFile=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfi
che\SEALaserfiche.csproj
                                     MSBuildSourceTargetName=_GetBuildOutputFilesWithTfm
                                     OriginalItemSpec=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\obj\
Debug\netstandard2.0\SEALaserfiche.dll
                                     TargetFramework=netstandard2.0
                                     TargetPath=SEALaserfiche.dll (TaskId:100)
                     Task Parameter:Deterministic=True (TaskId:100)
                     Task Parameter:
                         ContentTargetFolders=
                             content
                             contentFiles (TaskId:100)
                     Task Parameter:NuspecOutputPath=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\obj\D
ebug\ (TaskId:100)
                     Task Parameter:PackItem=C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\SEALaserfiche
.csproj (TaskId:100)
13:34:49.357  1:15>C:\Program Files\dotnet\sdk\5.0.201\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack
.targets(221,5): error : Could not find a part of the path 'C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfich
e\bin\netstandard2.0'. [C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\SEALaserfiche.csproj]
                     System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\esi\CommonClasses\SEALaserfi
che\SEALaserfiche_DEV\SEALaserfiche\bin\netstandard2.0'.
                        at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotF
ound)
                        at System.IO.Enumeration.FileSystemEnumerator`1.Init()
                        at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, Enumera
tionOptions options)
                        at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, Enum
erationOptions options, Boolean isNormalized)
                        at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, E
numerationOptions options)
                        at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchT
arget, EnumerationOptions options)
                        at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
                        at NuGet.Common.PathResolver.PerformWildcardSearch(String basePath, String searchPath, Boolean includ
eEmptyDirectories, String& normalizedBasePath)
                        at NuGet.Packaging.PackageBuilder.ResolveSearchPattern(String basePath, String searchPath, String tar
getPath, Boolean includeEmptyDirectories)
                        at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String
 exclude)
                        at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files)
                        at NuGet.Packaging.PackageBuilder.ReadManifest(Stream stream, String basePath, Func`2 propertyProvide
r)
                        at NuGet.Packaging.PackageBuilder..ctor(String path, String basePath, Func`2 propertyProvider, Boolea
n includeEmptyDirectories, Boolean deterministic)
                        at NuGet.Commands.PackCommandRunner.CreatePackageBuilderFromNuspec(String path)
                        at NuGet.Commands.PackCommandRunner.BuildFromNuspec(String path)
                        at NuGet.Commands.PackCommandRunner.BuildPackage(String path)
                        at NuGet.Commands.PackCommandRunner.RunPackageBuild()
                        at NuGet.Build.Tasks.Pack.PackTaskLogic.BuildPackage(PackCommandRunner runner)
                        at NuGet.Build.Tasks.Pack.PackTask.Execute() (TaskId:100)
                   Done executing task "PackTask" -- FAILED. (TaskId:100)
13:34:49.366  1:15>Done building target "GenerateNuspec" in project "SEALaserfiche.csproj" -- FAILED.: (TargetId:160)
13:34:49.367  1:15>Done Building Project "C:\esi\CommonClasses\SEALaserfiche\SEALaserfiche_DEV\SEALaserfiche\SEALaserfiche.cs
proj" (pack target(s)) -- FAILED.
```

**Comment by dominoFire** [comment]
Can you first try building the project and then packing the NuGet ?

```
dotnet build -p:Configuration=Debug
dotnet pack -p:Configuration=Debug
```

**Comment by nkolev92** [comment]
When packing an SDK project with a nuspec, properties need to be passed through a `NuspecProperties` property.

Please refer to the following doc: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-using-a-nuspec-file
