### ISSUE TITLE
Unit Test is system Timezone dependent: `NuGet.CommandLine.Test.NuGetRestoreCommandTest.RestoreCommand_PreservesPackageFilesTimestamps`

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#10722]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): N/A

Product version: N/A

Worked before? If so, with which NuGet version: 

A test failed for me, and a quick look seems to indicate the Actual timestamp is pertinent to my timezone.
Tests should be passing regardless of the system's timezone.

## Repro steps and/or sample project

```
<test name="NuGet.CommandLine.Test.NuGetRestoreCommandTest.RestoreCommand_PreservesPackageFilesTimestamps" type="NuGet.CommandLine.Test.NuGetRestoreCommandTest" method="RestoreCommand_PreservesPackageFilesTimestamps" time="0.6542857" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 1985-11-20T12:00:00.0000000\r\nActual:   1985-11-20T07:00:00.0000000-05:00]]></message>
          <stack-trace><![CDATA[   at NuGet.CommandLine.Test.NuGetRestoreCommandTest.<RestoreCommand_PreservesPackageFilesTimestamps>d__37.MoveNext() in C:\NuGet.Client\test\NuGet.Clients.Tests\NuGet.CommandLine.Test\NuGetRestoreCommandTest.cs:line 1906
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)]]></stack-trace>
        </failure>
</test>
```

**Comment by nkolev92** [comment]
Another timezone issue in https://github.com/NuGet/Home/issues/10564

Whoever fixes this can probably fix that one just as easily.
