### ISSUE TITLE
Package restore fails on Ubuntu 20 with This package was not repository signed with a certificate listed by this repository.

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#10723]
## Details about Problem

Ubuntu 20.04.2 LTS
dotnet SDK 5.0.102

Worked before? If so, with which NuGet version: 
It works fine on Windows.

## Repro steps and/or sample project

```ps1
dotnet new classlib
dotnet add package Nerdbank.GitVersioning --version 3.4.179-rc
```

```
  Determining projects to restore...
  Writing /tmp/tmpidqMU4.tmp
info : Adding PackageReference for package 'Nerdbank.GitVersioning' into project '/tmp/nbgvtest/nbgvtest.csproj'.
info : Restoring packages for /tmp/nbgvtest/nbgvtest.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/nerdbank.gitversioning/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/nerdbank.gitversioning/3.4.179-rc/nerdbank.gitversioning.3.4.179-rc.nupkg
info : Installing Nerdbank.GitVersioning 3.4.179-rc.
info : Package 'Nerdbank.GitVersioning 3.4.179-rc' from source 'https://api.nuget.org/v3/index.json': Signature Hash Algorithm: SHA256
info : Package 'Nerdbank.GitVersioning 3.4.179-rc' from source 'https://api.nuget.org/v3/index.json': Timestamp: 03/25/2021 06:05:34
info : Package 'Nerdbank.GitVersioning 3.4.179-rc' from source 'https://api.nuget.org/v3/index.json': Verifying author primary signature's timestamp with timestamping service certificate:

info :   Subject Name: CN=DigiCert Timestamp 2021, O="DigiCert, Inc.", C=US
info :   SHA1 hash: E1D782A8E191BEEF6BCA1691B5AAB494A6249BF3
info :   SHA256 hash: B3109006BC0AD98307915729E04403415C83E3292B614F26964C8D3571ECF5A9
info :   Issued by: CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US
info :   Valid from: 12/31/2020 17:00:00 to 01/05/2031 17:00:00
info : Package 'Nerdbank.GitVersioning 3.4.179-rc' from source 'https://api.nuget.org/v3/index.json': Signature type: Author
info : Package 'Nerdbank.GitVersioning 3.4.179-rc' from source 'https://api.nuget.org/v3/index.json': Verifying the author primary signature with certificate:
info :   Subject Name: CN=Nerdbank (.NET Foundation), O=Nerdbank (.NET Foundation), L=Redmond, S=Washington, C=US, SERIALNUMBER=603 389 068
info :   SHA1 hash: FCDF2332A1D8DB415EA421193F7AC5A6BD4F515D
info :   SHA256 hash: 1F891E64936D15DE5FAE22D910CD39F3E9860213C92F20CF9638A245B1249D2B
info :   Issued by: CN=.NET Foundation Projects Code Signing CA, O=.NET Foundation, C=US
info :   Valid from: 03/08/2020 18:00:00 to 03/14/2023 06:00:00
error: NU3034: Package 'Nerdbank.GitVersioning 3.4.179-rc' from source 'https://api.nuget.org/v3/index.json': This package was not repository signed with a certificate listed by this repository.
info : Package 'Nerdbank.GitVersioning' is compatible with all the specified frameworks in project '/tmp/nbgvtest/nbgvtest.csproj'.
error: Value cannot be null. (Parameter 'path1')
```

Note that:
1. the new project has no nuget.config to even require signed packages. 
2. version 3.3.37 of the same package installs just fine. (nuget.org used a different cert to sign it between these two versions)
3. Besides the claim about not being signed, there's also an ArgumentNullException error message on the last line, suggesting another(?) bug.

**Comment by dominoFire** [comment]
Recently, there was a certificate update on nuget.org; see https://github.com/NuGet/Announcements/issues/53

Your package might be affected by this update.

Can you run dotnet add again with `NUGET_SHOW_STACK` set to `true` to see full call stack from the exception?

```
dotnet new classlib
NUGET_SHOW_STACK=true dotnet add package Nerdbank.GitVersioning --version 3.4.179-rc
```

**Comment by AArnott** [comment]
Thanks, @dominoFire. Here is the result:

```
NUGET_SHOW_STACK=true dotnet add package Nerdbank.GitVersioning --version 3.4.179-rc
  Determining projects to restore...
  Writing /tmp/tmpHvFCxH.tmp
info : Adding PackageReference for package 'Nerdbank.GitVersioning' into project '/tmp/nbgvtest/nbgvtest.csproj'.
info : Restoring packages for /tmp/nbgvtest/nbgvtest.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/nerdbank.gitversioning/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/nerdbank.gitversioning/3.4.179-rc/nerdbank.gitversioning.3.4.179-rc.nupkg
info : Installing Nerdbank.GitVersioning 3.4.179-rc.
info : Package 'Nerdbank.GitVersioning 3.4.179-rc' from source 'https://api.nuget.org/v3/index.json': Signature Hash Algorithm: SHA256
info : Package 'Nerdbank.GitVersioning 3.4.179-rc' from source 'https://api.nuget.org/v3/index.json': Timestamp: 03/25/2021 06:05:34
info : Package 'Nerdbank.GitVersioning 3.4.179-rc' from source 'https://api.nuget.org/v3/index.json': Verifying author primary signature's timestamp with timestamping service certificate:
info :   Subject Name: CN=DigiCert Timestamp 2021, O="DigiCert, Inc.", C=US
info :   SHA1 hash: E1D782A8E191BEEF6BCA1691B5AAB494A6249BF3
info :   SHA256 hash: B3109006BC0AD98307915729E04403415C83E3292B614F26964C8D3571ECF5A9
info :   Issued by: CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US
info :   Valid from: 12/31/2020 17:00:00 to 01/05/2031 17:00:00
info : Package 'Nerdbank.GitVersioning 3.4.179-rc' from source 'https://api.nuget.org/v3/index.json': Signature type: Author
info : Package 'Nerdbank.GitVersioning 3.4.179-rc' from source 'https://api.nuget.org/v3/index.json': Verifying the author primary signature with certificate:
info :   Subject Name: CN=Nerdbank (.NET Foundation), O=Nerdbank (.NET Foundation), L=Redmond, S=Washington, C=US, SERIALNUMBER=603 389 068
info :   SHA1 hash: FCDF2332A1D8DB415EA421193F7AC5A6BD4F515D
info :   SHA256 hash: 1F891E64936D15DE5FAE22D910CD39F3E9860213C92F20CF9638A245B1249D2B
info :   Issued by: CN=.NET Foundation Projects Code Signing CA, O=.NET Foundation, C=US
info :   Valid from: 03/08/2020 18:00:00 to 03/14/2023 06:00:00
error: NU3034: Package 'Nerdbank.GitVersioning 3.4.179-rc' from source 'https://api.nuget.org/v3/index.json': This package was not repository signed with a certificate listed by this repository.
info : Package 'Nerdbank.GitVersioning' is compatible with all the specified frameworks in project '/tmp/nbgvtest/nbgvtest.csproj'.
error: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'path1'))
error:  ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
error:    at System.IO.Path.Combine(String path1, String path2)
error:    at NuGet.CommandLine.XPlat.AddPackageReferenceCommandRunner.GenerateLibraryDependency(PackageSpec project, PackageReferenceArgs packageReferenceArgs, RestoreResultPair restorePreviewResult, IEnumerable`1 userSpecifiedFrameworks, PackageDependency packageDependency)
error:    at NuGet.CommandLine.XPlat.AddPackageReferenceCommandRunner.ExecuteCommand(PackageReferenceArgs packageReferenceArgs, MSBuildAPIUtility msBuild)
error:    --- End of inner exception stack trace ---
error:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
error:    at System.Threading.Tasks.Task`1.get_Result()
error:    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass56_0.<OnExecute>b__0()
error:    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
error:    at NuGet.CommandLine.XPlat.Program.MainInternal(String[] args, CommandOutputLogger log)


Usage: NuGet.CommandLine.XPlat.dll package add [options]

Options:
  -h|--help               Show help information
  --force-english-output  Forces the application to run using an invariant, English-based culture.
  --package               Id of the package to be added.
  --version               Version of the package to be added.
  -d|--dg-file            Path to the dependency graph file to be used to restore preview and compatibility check.
  -p|--project            Path to the project file.
  -f|--framework          Frameworks for which the package reference should be added.
  -n|--no-restore         Do not perform restore preview and compatibility check. The added package reference will be unconditional.
  -s|--source             Specifies NuGet package sources to use during the restore.
  --package-directory     Directory to restore packages in.
  --interactive           Allow the command to block and require manual action for operations like authentication.
  --prerelease            Allows prerelease packages to be installed.
```

**Comment by loic-sharma** [comment]
Hello, I wasn't able to repro this on Ubuntu 20.04 and .NET SDK 5.0.201. Could you try clearing NuGet's cache with these commands:

```
dotnet nuget locals http-cache -c
dotnet nuget locals temp -c
```

Please let us know if the issue still reproduces after clearing your cache.

EDIT: Fixed `-c` casing

**Comment by AArnott** [comment]
Thanks. That fixed it up (after fixing your second command to use lowercase `-c`).

Here are the steps that on my machine led up to the failure:

```
git clone https://github.com/microsoft/vs-validation/
cd vs-validation
git checkout 47b3041cda92fefa1f1ec994252e87ae2ff2ac41
```

Update [this line](https://github.com/microsoft/vs-validation/blob/47b3041cda92fefa1f1ec994252e87ae2ff2ac41/Directory.Build.props#L30) to `3.4.179-rc`:

```diff
-    <PackageReference Include="Nerdbank.GitVersioning" Version="3.3.37" PrivateAssets="all" />
+    <PackageReference Include="Nerdbank.GitVersioning" Version="3.4.179-rc" PrivateAssets="all" />
```

Run:

```
dotnet restore
```

This failed because the repository cert didn't match [this fingerprint](https://github.com/microsoft/vs-validation/blob/47b3041cda92fefa1f1ec994252e87ae2ff2ac41/nuget.config#L15-L18). So I then added the new fingerprint:

```diff
    <repository name="nuget" serviceIndex="https://api.nuget.org/v3/index.json">
      <owners>Microsoft;xunit;manuel.roemer;sharwell;jamesnk;aarnott;MarcoRossignoli;Thecentury;kzu;castleproject</owners>
      <certificate fingerprint="0e5f38f57dc1bcc806d8494f4f90fbcedd988b46760709cbeec6f4219aa6157d" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
+     <certificate fingerprint="5a2901d6ada3d18260b9c6dfe2133c95d74b9eef6ae0e5dc334c8454d1477df4" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
    </repository>
```


But restore still failed. I then proceeded to try brand new projects without the nuget.config file and it just kept failing, but only on Ubunto 20 (Windows was fine).

**Comment by heng-liu** [comment]
Hi @AArnott , thanks for reporting this issue.
I could repro without adding new repository certificate in the NuGet.Config file, but once I added the new repository certificate, it restores successfully. So I assume you don't have this issue now, right? Pls correct me if my understanding is wrong. Thanks!

I would like to clarify that, if you add `trusted-signers` section in NuGet.Config file, even if you didn't specify require mode, it's in require mode. And only the packages signed with the signers in the `trusted-signers` would be considered as valid. Sorry that we didn't clarify that in our document https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-trusted-signers

Since the package Nerdbank.GitVersioning (3.4.179-rc) is signed with new repository certificate, if we would like to be in require mode, we need to add the new repository certificate into the `trusted-signers` section.

**Comment by heng-liu** [comment]
Raised an issue about the document at https://github.com/NuGet/docs.microsoft.com-nuget/issues/2377

**Comment by AArnott** [comment]
Yes, curiously enough the repro steps doesn't repro the problem for me any more. Thank you.

**Comment by heng-liu** [comment]
You might need to run `dotnet nuget locals global-packages -c` to clear the extracted `Nerdbank.GitVersioning` package. (Or go to the global package folder and only delete Nerdbank.GitVersioning folder.
The verification is done during extraction in restore. If the verification is good, the package will be extracted into global package folder.
Next time, when you run restore, if the package is already extracted in global package folder, the verification will be skipped.
That might be the reason why you could not repro any more.

**Comment by AArnott** [comment]
> That might be the reason why you could not repro any more.

Not in my case. I had in fact deleted the package from the global cache. I also tried restoring to an alternate cache by setting `NUGET_PACKAGES` to some other location.
