### ISSUE TITLE
Version range with build metadata no longer parsed

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#10861]
## Details about Problem

NuGet product used: NuGet.Versioning
Product version: 5.10.0-preview.2.7185
Worked before? If so, with which NuGet version: 5.9.1

## Repro steps and/or sample project

Version: `[1.0.0+git, 1.0.0-beta.1]`

Works:
https://nugettoolsdev.azurewebsites.net/5.9.1/parse-version-range?versionRange=%5B1.0.0%2Bgit%2C+1.0.0-beta.1%5D

Does not work:
https://nugettoolsdev.azurewebsites.net/5.10.0-preview.2.7185/parse-version-range?versionRange=%5B1.0.0%2Bgit%2C+1.0.0-beta.1%5D

### Verbose Logs
Exception:
```
Unhandled exception. System.ArgumentException: '[1.0.0+git, 1.0.0-beta.1]' is not a valid version string.
   at NuGet.Versioning.VersionRange.Parse(String value, Boolean allowFloating)
   at NuGet.Versioning.VersionRange.Parse(String value)
   at ConsoleApp1.Program.Main(String[] args) in C:\z\s\GitHub\NuGet\NuGet.Client\ConsoleApp1\Program.cs:line 10
```

**Comment by joelverhagen** [comment]
@nkolev92 pointed out that the range is nonsense and that's why it is throwing. In my example, the max of the range is less than the min. Closing as by design.
