### ISSUE TITLE
ArgumentException with invalid command+arg

### ISSUE THREAD

**Issue by mausch** [NuGet/Home#10905]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): 

dotnet.exe

Product version: 

```
$ dotnet --version
5.0.100

$ dotnet nuget --version
NuGet Command Line
5.8.0.6930
```

Worked before? If so, with which NuGet version: 

No idea tbh.

## Repro steps and/or sample project

```
$ dotnet nuget kk ''
System.ArgumentException: Value cannot be null or whitespace. (Parameter 'token')
   at Microsoft.DotNet.Cli.CommandLine.OptionError..ctor(String message, String token, AppliedOption option) in /_/src/source/CommandLine/OptionError.cs:line 21
   at Microsoft.DotNet.Cli.CommandLine.Parser.UnrecognizedArg(String arg) in /_/src/source/CommandLine/Parser.cs:line 170
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Microsoft.DotNet.Cli.CommandLine.Parser.Parse(IReadOnlyCollection`1 rawArgs, Boolean isProgressive) in /_/src/source/CommandLine/Parser.cs:line 107
   at Microsoft.DotNet.Cli.CommandLine.Parser.Parse(String[] args) in /_/src/source/CommandLine/Parser.cs:line 31
   at Microsoft.DotNet.Cli.ParserExtensions.ParseFrom(Parser parser, String context, String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by dominoFire** [comment]
Thanks for your report, @mausch 

Could you try using latest dotnet SDK (5.0.300) ? https://dotnet.microsoft.com/download/dotnet/5.0

Which OS are you using?

Are you setting `SHOW_NUGET_STACK` environment variable, as documented [here](https://docs.microsoft.com/nuget/reference/cli-reference/cli-ref-environment-variables) ?

**Comment by mausch** [comment]
Same exception with 5.0.300 :

`docker run --rm -it mcr.microsoft.com/dotnet/sdk:5.0.300-buster-slim dotnet nuget kk ''`

I'm not setting `SHOW_NUGET_STACK` (or `NUGET_SHOW_STACK` according to the docs?)

**Comment by dominoFire** [comment]
Yes, `NUGET_SHOW_STACK` is the correct environment variable. Sorry for the confusion.
