### ISSUE TITLE
NuGet generating incorrect binding redirects for Net Framework 4.7.2 console app and PackageReference

### ISSUE THREAD

**Issue by richardjm** [NuGet/Home#10970]
## Details about Problem

Visual Studio: 16.10.2

Product version: 

Unclear if ever worked before

## Repro steps and/or sample project

 - Create a new project in Visual Studio
 - Nuget Package Manager settings in Visual Studio
 
![image](https://user-images.githubusercontent.com/2081919/123383127-b099ba80-d58a-11eb-949e-c33bb2e11949.png)

 - Add a C# console app targeting .Net Framework 4.7.2
 - Add a C# library to the solution targeting .Net Framework 4.7.2
 - Add a project reference to the C# console app of the C# console library
 - Add a PackageReference to the library of `Microsoft.Data.SqlClient 3.0.0`
 - Add a PackageReference to the library of `Azure Identity 1.4.0` (note: Microsoft.Data.SqlClient references Azure.Identity 1.3.0)
 - Add a PackageReference to the console of `Newtsonsoft 13.0.1`
 - Add the [sample line to connect to a database using azure authentication](https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver15#setting-azure-active-directory-authentication) (it doesn't matter what settings as it fails before attempting to run with a binding failure)
 ```csharp
    static void Main(string[] args)
    {
      string ConnectionString = @"Server=demo.database.windows.net; Authentication=Active Directory Password; Database=testdb; User Id=user@domain.com; Password=***";

      using (SqlConnection conn = new SqlConnection(ConnectionString))
      {
        conn.Open();
      }
    }
```
 - Rebuild solution in Visual Studio
 - Run Console application - get binding failure at runtime

(Solution attached) - I believe this also fails for SDK-style Net Framework projects as that was where we encountered the issue, but for reproduction simplicity I kept the instructions as simple as possible.

### What's expected
Binding redirects contains an entry for Azure.Identity 0.0.0.0-1.4.0.0 in the C# console application assemblyBinding redirects (others redirects are present but not enough)

### What happens
Binding redirect is not present (others are such as System.ValueTuple and System.Memory

Attempting to run the console application fails with a binding error at runtime

```
System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'Azure.Core, Version=1.6.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=Microsoft.Data.SqlClient
  StackTrace:
   at Microsoft.Data.SqlClient.ActiveDirectoryAuthenticationProvider.AcquireTokenAsync(SqlAuthenticationParameters parameters)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.GetFedAuthToken(SqlFedAuthInfo fedAuthInfo)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OnFedAuthInfo(SqlFedAuthInfo fedAuthInfo)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover, Boolean isFirstTransparentAttempt, Boolean disableTnir)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, ServerCertificateValidationCallback serverCallback, ClientCertificateRetrievalCallback clientCallback, DbConnectionPool pool, String accessToken, SqlClientOriginalNetworkAddressInfo originalNetworkAddressInfo, Boolean applyTransientFaultHandling)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\****\source\repos\ConsoleApp2\ConsoleApp2\Program.cs:line 13
```

### Verbose Logs
[diagnosticbuild.txt](https://github.com/NuGet/Home/files/6714454/diagnosticbuild.txt)

[ConsoleApp2.zip](https://github.com/NuGet/Home/files/6714417/ConsoleApp2.zip)

**Comment by nkolev92** [comment]
Hey @richardjm 

Thanks for the detailed issue, we really appreciate you getting a repro! 

In PackageReference, NuGet doesn't deal with the binding redirects, they are instead handled by other components, such as `MSBuild` or `SDK` depending on the project style. 

I see that in your console app, `AutoGenerateBindingRedirects` is set to `true`, which is what I would've suggested, https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection

Given that this issue is better suited in a different component area, we can do a few things. 

1. I can move this issue to MSBuild, given that it's dealing with legacy projects.
2. You can re-create the repro with SDK based projects and open an issue on .NET SDK side and close this.
