### ISSUE TITLE
[Bug]: Invalid character in the given encoding. Line 1, position 1.

### ISSUE THREAD

**Issue by brunocampiol** [NuGet/Home#11037]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK 5.0.301, MS Build 16, Nuget 5.10.0.7240, VS2019, Net Core 3.1

### Impact

It's more difficult to complete my work

### Repro Steps & Context

**Whenever I open a new project visual studio says on "Package Manager" output:**

NuGet package restore failed. Please see Error List window for detailed warnings and errors.
Error occurred while restoring NuGet packages: The operation failed as details for project Obd.UserManagement.SmokeTests could not be loaded.
Time Elapsed: 00:00:00.4696117
========== Finished ==========
Invalid character in the given encoding. Line 1, position 1.

**Error list in visual studio does not give me any file... Only a description**

Severity	Code	Description	Project	File	Line	Suppression State
Error		Invalid character in the given encoding. Line 1, position 1.				

Any thoughts on what is causing this? Everytime I need to clear all nuget packages and restore them to properly work

![VSERROR1](https://user-images.githubusercontent.com/1672440/125941888-fca53840-c764-4ee7-aa5d-836a32fcd52d.PNG)
![VSERROR2](https://user-images.githubusercontent.com/1672440/125941895-a5c3bdf0-9b5a-48c6-ab2e-1a9007cad5c2.PNG)

**Comment by brunocampiol** [comment]
Restoring packages for C:\Gitlab\project\test\smoke\SmokeTests\SmokeTests.csproj...
System.Xml.XmlException: Invalid character in the given encoding. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.InvalidCharRecovery(Int32& bytesCount, Int32& charsCount)
   at System.Xml.XmlTextReaderImpl.GetChars(Int32 maxCharsCount)
   at System.Xml.XmlTextReaderImpl.ReadData()
   at System.Xml.XmlTextReaderImpl.SwitchEncoding(Encoding newEncoding)
   at System.Xml.XmlTextReaderImpl.SwitchEncodingToUTF8()
   at System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(Boolean isTextDecl)
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.Packaging.Core.NuspecCoreReaderBase.LoadXml(Stream stream, Boolean leaveStreamOpen)
   at NuGet.Packaging.Core.NuspecCoreReaderBase..ctor(Stream stream, Boolean leaveStreamOpen)
   at NuGet.Protocol.LocalPackageFileCache.GetNuspec(String manifestPath, String expandedPath)
   at NuGet.Protocol.LocalPackageFileCache.<>c__DisplayClass6_1.<GetOrAddNuspec>b__1()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---

**Comment by heng-liu** [comment]
Hi @brunocampiol , thanks for filing this issue!
It looks like there is some issue in a nuspec file of a certain package.
Could you help us narrow down the issue? Like, which package brings in this issue?
You may try to create a sample project, and each time adding one package and restore, until you have this issue.
It would be great if you could help us provide the repro steps. Thanks!

**Comment by zkat** [comment]
We should really improve the error messaging here, so I'm closing this in favor of https://github.com/NuGet/Home/issues/11045

**Comment by dliedke** [comment]
I created a simple tool to find and delete bad corrupted nuget packages in the cache, it can be found at:

https://github.com/dliedke/FixNugetCache

After running the tool, just restore the packages again in VS.NET and it should work.

Thanks!
