### ISSUE TITLE
[Bug]: VS 2022: Pack action generates GetPackOutputItemsTask error

### ISSUE THREAD

**Issue by MiYanni** [NuGet/Home#11102]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Version 17.0.0 Preview 3.0 [31514.198.main]

### Worked before?

Not sure, sorry.

### Impact

I'm unable to use this version

## Repro Steps
1. Open VS 2022 (main branch version).
2. Create a new .NET 6 class library project (C#).
3. Right click on the project in Solution Explorer and select `Pack`.
4. Observe that the build starts, but fails with the error below.

### Error
```batch
Error	MSB4018	The "GetPackOutputItemsTask" task failed unexpectedly.
System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
   at System.Collections.Generic.List`1.Add(T item)
   at NuGet.Build.Tasks.Pack.GetPackOutputItemsTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ClassLibrary2	C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets	111	
```

## Additional Info
I've tried a few different projects including .NET 6 application and .NET Standard 2.1 class library. All fail with the same error.

**Comment by MiYanni** [comment]
Updated my main branch to `Version 17.0.0 Preview 3.0 [31528.315.main]` and this issue is no longer there. Closing.
