### ISSUE TITLE
9 signing tests failed on MacOS, as root certificate is removed from trusted store on MacOS

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#11178]
The following 9 tests failed on Mac:
```
Verify_MultipleSignedPackagesWithWildCardAndDetailedVerbosity_MixedResults
Verify_SignedPackageWithAllowedCertificate_Succeeds
Verify_AuthorSignedAndTimestampedPackageWithOptionAll_Succeeds

GetTrustResultAsync_WithUnavailableRevocationInformationAndAllowUnknownRevocation_WithOnlineRevocationMode_WarnsAsync
GetTrustResultAsync_WithUnavailableRevocationInformationInAcceptMode_DoesNotWarnAsync
GetTrustResultAsync_WithUnavailableRevocationInformationAndAllowUnknownRevocation_WithOfflineRevocationMode_WarnsAsync
GetTrustResultAsync_WithUnavailableRevocationInformationInRequireMode_WarnsAsync
GetTrustResultAsync_WithUnavailableRevocationInformationAndAllowIllegal_WarnsAsync
GetTrustResultAsync_WithUnavailableRevocationInformationInVerify_WarnsAsync
```
The error message:
```
Expected result.AllOutput "Verifying TestPackage.AuthorSigned.1.0.0
/Users/runner/work/1/s/.test/work/55da137a/7fcf4313/TestPackage.AuthorSigned.1.0.0.nupkg
Signature Hash Algorithm: SHA256
Signature type: Author
Verifying the author primary signature with certificate:
Subject Name: CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
SHA1 hash: F404000FB11E61F446529981C7059A76C061631E
SHA256 hash: 3F9001EA83C560D712C24CF213C3D312CB3BFF51EE89435D3430BD06B5D0EECE
Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
Valid from: 2/26/2018 12:00:00 AM to 1/27/2021 12:00:00 PM
trace:       Subject Name: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:       SHA1 hash: 92C1588E85AF2201CE7915E8538B492F605B80C6
trace:       SHA256 hash: 51044706BD237B91B89B781337E6D62656C69F0FCFFBE8E43741367948127862
trace:       Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:       Valid from: 10/22/2013 12:00:00 PM to 10/22/2028 12:00:00 PM
trace:             Subject Name: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:             SHA1 hash: 0563B8630D62D75ABBC8AB1E4BDFB5A899B24D43
trace:             SHA256 hash: 3E9099B5015E8F486C00BCEA9D111EE721FABA355A89BCF1DF69561E3DC6325C
trace:             Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:             Valid from: 11/10/2006 12:00:00 AM to 11/10/2031 12:00:00 AM
debug: The author primary signature's certificate chain validation failed with error(s): NotTimeValid, RevocationStatusUnknown
Timestamp: 2/28/2018 9:53:09 PM
Verifying author primary signature's timestamp with timestamping service certificate:
Subject Name: CN=Symantec SHA256 TimeStamping Signer - G2, OU=Symantec Trust Network, O=Symantec Corporation, C=US
SHA1 hash: 625AEC3AE4EDA1D169C4EE909E85B3BBC61076D3
SHA256 hash: CF7AC17AD047ECD5FDC36822031B12D4EF078B6F2B4C5E6BA41F8FF2CF4BAD67
Issued by: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
Valid from: 1/2/2017 12:00:00 AM to 4/1/2028 11:59:59 PM
trace:       Subject Name: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
trace:       SHA1 hash: 6FC9EDB5E00AB64151C1CDFCAC74AD2C7B7E3BE4
trace:       SHA256 hash: F3516DDCC8AFC808788BD8B0E840BDA2B5E23C6244252CA3000BB6C87170402A
trace:       Issued by: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
trace:       Valid from: 1/12/2016 12:00:00 AM to 1/11/2031 11:59:59 PM
trace:             Subject Name: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
trace:             SHA1 hash: 3679CA35668772304D30A5FB873B0FA77BB70D54
trace:             SHA256 hash: 2399561127A57125DE8CEFEA610DDF2FA078B5C8067F4E828290BFB860E84B3C
trace:             Issued by: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
trace:             Valid from: 4/2/2008 12:00:00 AM to 12/1/2037 11:59:59 PM
debug: author primary signature's timestamp
Finished with 2 errors and 1 warnings.
warn : NU3018: The author primary signature found a chain building issue: RevocationStatusUnknown: An incomplete certificate revocation check occurred.
error: NU3037: The author primary signature validity period has expired.
error: NU3028: The author primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
Package signature validation failed.
Verifying Test.Reposigned.1.0.0
/Users/runner/work/1/s/.test/work/c23f5cb0/c74fef21/Test.Reposigned.1.0.0.nupkg
Sign
```

Stack trace
  ```
 at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.StringAssertions.Contain(String expected, String because, Object[] becauseArgs)
   at Dotnet.Integration.Test.DotnetVerifyTests.Verify_MultipleSignedPackagesWithWildCardAndDetailedVerbosity_MixedResults() in /Users/runner/work/1/s/test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetVerifyTests.cs:line 137
```

**Comment by heng-liu** [comment]
Tried to run `dotnet nuget verify` on a package from nuget.org on Mac. It failed for the same reason:
`ExplicitDistrust: The trust setting for this policy was set to Deny.`
So MacOS distrusts the Symantec root cert recently.

After discussing offline, we will skip those 9 tests and enable them when we have CTL, or when we have new TSA to timestamp packages on nuget.org(then we need to timestamp the pre-generated packages by the new TSA).

**Comment by xStrato** [comment]
I was facing the same problem by adding packages in .csproj
Running ```dotnet nuget verify``` on any package gives me the message:

> error: NU3028: The repository primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
error:
error: Package signature validation failed.

But after running ```dotnet clean``` the error is not showing at build/restore anymore...

**Comment by heng-liu** [comment]
Hi @xStrato , thanks for adding the comments.
Yes, there is no verification on Linux and Mac during restore if not setting a environment variable to opt in (pls refer to https://github.com/NuGet/Home/issues/10742). But the verify command will still do the verification.
And since the certificate is recently distrust on MacOS, the verify command detect the issue in the certificate as expected.
Pls refer to [.NET 5 NuGet Restore Failures on Linux distributions using NSS or ca-certificates](https://devblogs.microsoft.com/nuget/net-5-nuget-restore-failures-on-linux-distributions-using-nss-or-ca-certificates/)
and https://github.com/NuGet/Announcements/issues/56 for similar issue on Linux.

**Comment by aortiz-msft** [comment]
Currently, signature validation on Mac is not supported.
