### ISSUE TITLE
Re-enable flaky Apex tests failing due to IPC errors

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#11308]
Since switching to new Visual Studio testing infrastructure, we're getting a high rate of tests failing with IPC errors:

> System.AggregateException : One or more errors occurred.
> ---- System.Runtime.Remoting.RemotingException : Failed to read from an IPC Port: The pipe has been ended.

All these errors appear to be coming from two places in our code:

https://github.com/NuGet/NuGet.Client/blob/892375745964db627494305fd605496454b5ad0a/test/NuGet.Tests.Apex/NuGet.Tests.Apex/Utility/CommonUtility.cs#L451

https://github.com/NuGet/NuGet.Client/blob/892375745964db627494305fd605496454b5ad0a/test/NuGet.Tests.Apex/NuGet.Tests.Apex/Apex/ApexTestContext.cs#L54

Interestingly though, it appears that a small number of tests are the ones that keep failing.

Below is an example stack trace reported in Azure DevOps' test results view:

```
----- Inner Stack Trace #1 (System.Runtime.Remoting.RemotingException) -----

Server stack trace: 
   at System.Runtime.Remoting.Channels.Ipc.IpcPort.Read(Byte[] data, Int32 offset, Int32 length)
   at System.Runtime.Remoting.Channels.Ipc.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   at System.Runtime.Remoting.Channels.Ipc.IpcClientHandler.ReadHeaders()
   at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Test.Apex.VisualStudio.Solution.SolutionService.SaveAndClose()
   at NuGet.Tests.Apex.ApexTestContext.Dispose() in D:\a\_work\1\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\Apex\ApexTestContext.cs:line 54
   at NuGet.Tests.Apex.AuthorSignedPackageTestCase.<UpdateUnsignedToSignedVersionFromPMCForPC_SucceedAsync>d__4.MoveNext() in D:\a\_work\1\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\NuGetPackageSigningTests\AuthorSignedPackageTestCase.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace #2 (System.Runtime.Remoting.RemotingException) -----

Server stack trace: 
   at System.Runtime.Remoting.Channels.Ipc.IpcPort.Read(Byte[] data, Int32 offset, Int32 length)
   at System.Runtime.Remoting.Channels.Ipc.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   at System.Runtime.Remoting.Channels.Ipc.IpcClientHandler.ReadHeaders()
   at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.
```

**Comment by donnie-msft** [comment]
Build did fail on a test we previously skipped, but this is not an IPC failure. It looks like a different flaky problem.
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5499639&view=ms.vss-test-web.build-test-results-tab&runId=29493686&resultId=100032&paneView=debug

> **NuGet.Tests.Apex.NetCoreProjectTestCase.WithSourceMappingEnabled_InstallAndUpdatePackageFromPMUIFromExpectedSource_Succeeds**
> "Expected boolean to be true because A PackageReference with Contoso.a/2.0.0 was not found in C:\Users\TestUser\AppData\Local\Temp\NuGetTestFolder\07eef7bc\6c05fa83\solution\TestProject\TestProject.csproj, but found False."

**Comment by zivkan** [comment]
In late (November?) 2021, Donnie contacted ApexDisc asking for help, but all we got was something along the lines of "IPC/RPC error probably means that devenv crashed".

**Comment by zivkan** [comment]
In December 2022, I contacted VSEngHelp, asking for help trying to get [the ProcDumpCollector](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/892/ProcDumpCollector) to work. The dmp files are attached to the results root, not an individual test. However, there were no devenv.dmp files.

In early January 2023, we got a reply saying this probably means that devenv did not crash in a way that Windows' system debugger can catch. But they told us Apex has some built-in crash detection functionality.

**Comment by zivkan** [comment]
Using Intellisense in VS, I found that [`ExternalProcessHostConfiguration` has a property `DebuggerCaptureCrashDumps`](https://dev.azure.com/devdiv/DevDiv/_git/VS?path=/src/Omni/Apex/Framework/Hosts/Configuration/ExternalProcessHostConfiguration.cs&version=GBmain&line=145&lineEnd=146&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)

When I tried setting it to true, Apex threw exceptions with message

> System.InvalidOperationException : The host configuration's DebuggerCaptureCrashDumps is enabled but the debugging tools for Microsoft.Test.Apex.Hosts.CdbHostProcessDebugger are not installed

@martinrrm pinged me on Teams, telling me he'd like to learn more about Apex. Therefore, I'm asking him to take over this investigation, particularly as he's in the same timezone as VS experts, VSEng, Apex experts, etc.
