### ISSUE TITLE
[Bug]: nuget restore - Illegal characters in path

### ISSUE THREAD

**Issue by jozefizso** [NuGet/Home#11319]
### NuGet Product Used

NuGet.exe

### Product Version

5.11.0.10

### Impact

I'm unable to use this version

### Repro Steps & Context

Use GitHub actions to run a .NET Desktop app build workflow. Call `nuget restore` and it will fail.

**build.yml**
```yaml
name: Build

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.3

    - run: nuget restore *.sln -verbosity detailed
```

Other command does not work as well:

```
nuget restore *.sln
nuget restore '*.sln'
nuget restore "*.sln"
```

### Verbose Logs

```shell
nuget restore *.sln -verbosity detailed
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
NuGet Version: 5.11.0.10
Illegal characters in path.
System.ArgumentException: Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at NuGet.CommandLine.RestoreCommand.<DetermineRestoreInputsAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
Error: Process completed with exit code 1.
```

**Comment by erdembayar** [comment]
It looks `nuget.exe restore` doesn't support globbing.
Not sure about Gibhub action, but for Azure I you can use powershell inside it. You can find all the *.sln files and iterate over it. Below is just mock idea, may have syntax error. 

```
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      Write-Host "Hello world"
      Get-ChildItem *.sln -Recurse | foreach { nuget restore $_.FullName }
```

It looks Github action has similar support.

```
        shell: pwsh
        run: |
          Write-Host "Hello world"
          Get-ChildItem *.sln -Recurse | foreach { nuget restore $_.FullName }
```

Please let me know if above resolves your issue.

**Comment by jozefizso** [comment]
Yes, the issue was * pattern. Which is unfortunate because we can use it in Azure Pipelines action but apparently it is handled by the action and not nuget.exe
