### ISSUE TITLE
Mac signing tests timed out for adding certificate to trusted store

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#11321]
Mac tests timed out very often recently.
Failed tests log :
```
 Failed NuGet.Commands.Test.TrustedSignerActionsProviderTests.AddTrustedSignerAsync_ServiceIndexAlreadyExists_ThrowsAsync [8 m 1 s]
EXEC : warning Message:  [/Users/runner/work/1/s/build/build.proj]
     System.TimeoutException : bash timed out: -c "sudo security add-trusted-cert -d -r trustRoot -k "/Library/Keychains/System.keychain" "/tmp/67E9FD9C07CF784E09765E5EA66BD0E8C766C6BC.cer""
    Stack Trace:
       at NuGet.Test.Utility.CommandRunner.Run(String process, String workingDirectory, String arguments, Boolean waitForExit, Int32 timeOutInMilliseconds, Action`1 inputAction, IDictionary`2 environmentVariables) in /Users/runner/work/1/s/test/TestUtilities/Test.Utility/CommandRunner.cs:line 95
     at Test.Utility.Signing.TrustedTestCert`1.RunMacCommand(String cmd) in /Users/runner/work/1/s/test/TestUtilities/Test.Utility/Signing/TrustedTestCert.cs:line 161
     at Test.Utility.Signing.TrustedTestCert`1.AddCertificateToStoreForMacOSX() in /Users/runner/work/1/s/test/TestUtilities/Test.Utility/Signing/TrustedTestCert.cs:line 134
     at Test.Utility.Signing.TrustedTestCert`1..ctor(T source, Func`2 getCert, StoreName storeName, StoreLocation storeLocation, Nullable`1 maximumValidityPeriod) in /Users/runner/work/1/s/test/TestUtilities/Test.Utility/Signing/TrustedTestCert.cs:line 81
     at Test.Utility.Signing.TestCertificate.WithTrust() in /Users/runner/work/1/s/test/TestUtilities/Test.Utility/Signing/TestCertificate.cs:line 46
     at Test.Utility.Signing.SigningTestUtility.GenerateTrustedTestCertificate() in /Users/runner/work/1/s/test/TestUtilities/Test.Utility/Signing/SigningTestUtility.cs:line 572
     at NuGet.Commands.Test.TrustedSignerActionsProviderTests.AddTrustedSignerAsync_ServiceIndexAlreadyExists_ThrowsAsync() in /Users/runner/work/1/s/test/NuGet.Core.Tests/NuGet.Commands.Test/TrustedSignerActionsProviderTests.cs:line 423
  --- End of stack trace from previous location ---

```

**Comment by heng-liu** [comment]
Thanks for:
@kartheekp-ms finding out the error message when running command to add cert to trusted store is:
exit error = SecTrustSettingsSetTrustSettings: errSecInternalComponent
@Erick raising ICM ticket https://portal.microsofticm.com/imp/v3/incidents/details/267776895/home
@zivkan raising the PR to skip those affected tests.
