### ISSUE TITLE
[Bug]: After adding key via `nuget setApiKey`, push commands error with `Key not valid for use in specified state.` & exit with code 1

### ISSUE THREAD

**Issue by fluffynuts** [NuGet/Home#11428]
### NuGet Product Used

NuGet.exe

### Product Version

5.11.0.10

### Worked before?

Worked before a machine reload, so I have to assume the problem is more with setApiKey than with push perhaps?

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1. generate an api key at nuget.org
2. `nuget setApiKey {key} -source nuget.org`
3. `nuget.exe push {package} -NonInteractive -Source nuget.org -Timeout 300 -SkipDuplicate`
4. process exits with code 1 and an error about the key state

### Verbose Logs

```shell
➜ nuget.exe push .\.release-packages\PeanutButter.XmlUtils.2.0.50.nupkg -NonInteractive -SOurce nuget.org -Timeout 300 -SkipDuplicate -verbosity detailed
NuGet Version: 5.4.0.6315
Pushing PeanutButter.XmlUtils.2.0.50.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Conflict https://www.nuget.org/api/v2/package/ 7430ms
Package 'C:\code\opensource\PeanutButter\.\.release-packages\PeanutButter.XmlUtils.2.0.50.nupkg' already exists at feed 'https://www.nuget.org/api/v2/package'.
Key not valid for use in specified state.
System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.

   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at NuGet.Configuration.EncryptionUtility.DecryptString(String encryptedString)
   at NuGet.Configuration.SettingsUtility.GetDecryptedValueForAddItem(ISettings settings, String section, String key, Boolean isPath)
   at NuGet.Commands.CommandRunnerUtility.GetApiKey(ISettings settings, String endpoint, String source, String defaultApiKey, Boolean isSymbolApiKey)
   at NuGet.Commands.PushRunner.<>c__DisplayClass0_0.<Run>b__1(String symbolsEndpoint)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by erdembayar** [comment]
@fluffynuts 
I was not able to repro this with nuget 5.1.1. It looks you have issue with your `nuget.config` file (%APPDATA%\Roaming\NuGet\NuGet.config on Windows, ~/.nuget/NuGet/NuGet.config on Linux/Mac). Please note encrypted value which red marked below is [specific per user](https://github.com/NuGet/Home/issues/7850#issuecomment-481475456).
![image](https://user-images.githubusercontent.com/8766776/144499992-97979239-3259-4085-8b0b-2f5db493156d.png)

Please backup existing nuget.config file and create new `nuget.config`(`dotnet new nugetconfig`) file then repeat everything. Please let me know if it resolves your issue.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
