### ISSUE TITLE
[Bug]: Unable to install a different version in an existing PackageReference project.

### ISSUE THREAD

**Issue by martinrrm** [NuGet/Home#11427]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Version 17.1.0 Preview 2.0 [31930.463.main]

### Worked before?

Yes

### Impact

I'm unable to use this version

### Repro Steps & Context

Root cause likely not on NuGet side, [1444702](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1444702)

1. Create a new console project (dotnet 6.0).
2. Open Project PM UI and install latest version of Newtonsoft.Json
3. Change to Installed tab
4. Change the version of Newtonsoft.Json and install
5. Close VS using the X on the upper right corner
6. Save the project changes
7. Open the project again
8. Open Project PM UI and install a different version of Newtonsoft.Json

To work around this you can install a new package and this will let you change the version of the packages again.

### Verbose Logs

```shell
Restoring packages for C:\Users\mruizmares\source\repos\ConsoleApp6\ConsoleApp6\ConsoleApp6.csproj...
Installing NuGet package Newtonsoft.Json 10.0.1.
System.NotSupportedException: Specified method is not supported.
   at Microsoft.VisualStudio.ProjectSystem.ProjectSerialization.CachedProject.GetItemProvenance(String itemToMatch, String itemType, EvaluationContext evaluationContext)
   at Microsoft.VisualStudio.ProjectSystem.Items.MSBuildGlobUtilities.TryGetLatestExactMetadataElement(ProjectItem item, ProjectRootElement containingProjectXml)
   at Microsoft.VisualStudio.ProjectSystem.Properties.ItemProperties.ProjectMetadataElementCache.<GetValueAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.Properties.ItemProperties.<GetProjectItemAndMetaElementAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Properties.ItemProperties.<SetPropertyValueAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Properties.ItemPropertiesWithCatalog.<SetPropertyValueAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Properties.ProjectPropertiesBase.<>c__DisplayClass31_0.<<Microsoft-VisualStudio-ProjectSystem-Properties-IProjectProperties-SetPropertyValueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.<ExecuteWithinLockAsync>d__129.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.<ExecuteWithinLockAsync>d__129.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.<InstallPackageAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteBuildIntegratedProjectActionsAsync>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__77.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<>c__DisplayClass18_0.<<ExecuteActionsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<CatchAndRethrowExceptionAsync>d__28.MoveNext()
Time Elapsed: 00:00:01.1332797
========== Finished ==========
```

**Comment by arunchndr** [comment]
Fixed internally. It should flow out in P2

**Comment by LittleLittleCloud** [comment]
@arkalyanms 
Hitting this error as well, could you share your solution on how fixing it internally?

Regards

**Comment by arunchndr** [comment]
I was OOF and just got back. @LittleLittleCloud did the latest preview update unblock you?

**Comment by LittleLittleCloud** [comment]
@arkalyanms haven't try it yet, could you share with me the latest preview version.

**Comment by arunchndr** [comment]
The fix is on the VS side. Updating to the latest VS version should do it.

**Comment by LittleLittleCloud** [comment]
I update to the latest preview build but now I get a new error
```
Installing nuget package, package ID: Microsoft.ML.TimeSeries, package Version: 1.7.0
Package restore failed. Rolling back package changes for 'ConsoleApp1'.
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteBuildIntegratedProjectActionsAsync>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

This is probably because I'm updating a package (Microsoft.ML.TimeSeries 1.7.0) that depends on another referenced package (Microsoft.ML 1.6.0) under the same project, which causes a restore error. So I should probably update Microsoft.ML first, then Microsoft.ML.TimeSeries. But I want to avoid hard-coding the update order.

Any suggestions on fixing this? Is there a way to update several packages at the same time or simply skip the restore error when it occurs.

**Comment by arunchndr** [comment]
@nkolev92 who might be able to answer the restore order question.

**Comment by nkolev92** [comment]
@LittleLittleCloud 

Anything more to the error you're getting? 
There should hopefully be actionable details in the error list.

**Comment by nkolev92** [comment]
The original issue doesn't repro anymore on the latest preview. 

Thanks for fixing this @arkalyanms
