### ISSUE TITLE
Install Package Error at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()

### ISSUE THREAD

**Issue by Lywx** [NuGet/Home#1146]
Attempting to gather dependencies information for package 'FSharp.Compiler.Service.1.4.0.1' with respect to project 'Project', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for package 'FSharp.Compiler.Service.1.4.0.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'FSharp.Compiler.Service.1.4.0.1'
Resolved actions to install package 'FSharp.Compiler.Service.1.4.0.1'
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.Core.v3.DependencyInfo.Utils.<LoadResource>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.Core.v3.DependencyInfo.Utils.<LoadRanges>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.Core.v3.RegistrationResourceV3.<GetPackageMetadata>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.Core.v3.RegistrationResourceV3.<GetPackageMetadata>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.VisualStudio.UIMetadataResourceV3.<GetMetadata>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<GetPackageMetadataAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<GetPackageMetadataAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<CheckLicenseAcceptanceAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()
========== Finished ==========

**Comment by Lywx** [comment]
Note that I install package "FSharp.Compiler.Service.1.4.0.1'" from local directory after several attempt to install from nuget.org. Sadly, neither works well.

**Comment by yishaigalatzer** [comment]
Can you please provide us with more feedback

1. What version of NuGet are you using? What version of Visual Studio are you using?
2. Repro steps - Project type, what other packages are installed, if you can reproduce this from file->new project even better.

**Comment by Lywx** [comment]
Hi yishaigalatzer.

I'm using Visual Studio 2015 Community in Windows 10.

NuGet for Visual Studio 2015, Version 3.1.60724.766

**Comment by Lywx** [comment]
I got the problem from a MonoGame 3.4 Project template.

I am working to reproduce this issue.

C# Console Project worked well installing from local nupkg.

**Comment by Lywx** [comment]
But after upgrading to Visual Studio 2015 I lost the existing template files. I would try to reproduce this with new templates.

**Comment by Lywx** [comment]
New MonoGame 3.4 Project worked well.

**Comment by Lywx** [comment]
Sorry but I have trouble reproducing this.

More information, alongside package are:

1. NUnit.2.6.4
2. FSharp.Core

**Comment by Lywx** [comment]
I retry on previous problematic project, it worked now!

**Comment by yishaigalatzer** [comment]
@Lywx thanks for the report. I'm going to close it for now. If you have a consistent repro, this is something we can dig deeper into.
