### ISSUE TITLE
[Bug]: push fail when Credential Provider fail even if ApiKey is passed on command line

### ISSUE THREAD

**Issue by qlikTERror** [NuGet/Home#11533]
### NuGet Product Used

NuGet.exe

### Product Version

6.0.0.280

### Worked before?

Before credential providers

### Impact

I'm unable to use this version

### Repro Steps & Context

We are trying to push a package to GitHub packages. We verified that our Source and ApiKey works correctly. As Source we use **https://nuget.pkg.github.com/<owner>/index.json** where **<owner>** is replaced with our correct owner. As ApiKey we use a PAT that has been verified to work.

If we run the command in a clean situation we obtain an 401 (Unauthorized).

We added a nuget,config in the current directory, adding to it as package source the previous url and as username and password for that source some random values that are totally invalid.

If we run the command it works and with verbosity detailed we see the Credential Provider never kicks in. If we use a wrong ApiKey it stops to be able to push, as expected.

At this point, if we change the current directory and move to another path or if we delete the nuget.config that we just created the push command keeps working with the correct ApiKey and fails if a wrong one is used.

If we also delete the v3-cache folder that host the http-cache of nuget.exe we are returning to the situation were the command stops to be able to push and we have again the logs attached to this issue.

It seems that adding a pair of credentials, even wrong, for the source allows us to correctly use the ApiKey parameter. Otherwise Credential Providers kicks in (before trying the ApiKey parameter) and if they fails the ApiKey is never tried.

 

### Verbose Logs

```shell
NuGet Version: 6.0.0.280
MSBuild auto-detection: using msbuild version '16.11.2.50704' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Using C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\NuGet\Plugins\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe as a credential provider plugin.
    [CredentialProvider.162340]Running in plug-in mode
    [CredentialProvider.162340]Command-line v0.1.23+3902a1eadc037829d4a161d287d8579f1fb2168e: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\NuGet\Plugins\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe" -Plugin
    [CredentialProvider.162340]Handling 'Request' 'Initialize'. Time elapsed in ms: 4 - Payload: {"ClientVersion":"6.0.0","Culture":"en-US","RequestTimeout":"00:00:05"}
    [CredentialProvider.162340]Sending response: 'Request' 'Initialize'. Time elapsed in ms: 5
    [CredentialProvider.162340]Time elapsed in milliseconds after sending response 'Request' 'Initialize': 6
    [CredentialProvider.162340]Handling 'Request' 'GetOperationClaims'. Time elapsed in ms: 0 - Payload: {}
    [CredentialProvider.162340]Sending response: 'Request' 'GetOperationClaims'. Time elapsed in ms: 8
    [CredentialProvider.162340]Time elapsed in milliseconds after sending response 'Request' 'GetOperationClaims': 23
    [CredentialProvider.162340]Handling 'Request' 'SetLogLevel'. Time elapsed in ms: 2 - Payload: {"LogLevel":"Debug"}
    [CredentialProvider]Sending response: 'Request' 'SetLogLevel'. Time elapsed in ms: 3
    [CredentialProvider]Time elapsed in milliseconds after sending response 'Request' 'SetLogLevel': 7
    [CredentialProvider]Handling 'Request' 'GetAuthenticationCredentials'. Time elapsed in ms: 2 - Payload: {"Uri":"https://nuget.pkg.github.com/XXXXXXXXX-trial/index.json","IsRetry":false,"IsNonInteractive":true,"CanShowDialog":true}
    [CredentialProvider]Creating a progress reporter with interval: 00:00:02
    [CredentialProvider]Handling auth request, Uri: https://nuget.pkg.github.com/XXXXXXXXX-trial/index.json, IsRetry: False, IsNonInteractive: True, CanShowDialog: True
    [CredentialProvider]URI: https://nuget.pkg.github.com/XXXXXXXXX-trial/index.json
    [CredentialProvider]VstsBuildTaskServiceEndpointCredentialProvider - This credential provider must be run under the Team Build tasks for NuGet with external endpoint credentials. Appropriate environment variable needs to be set.
    [CredentialProvider]Skipping NuGetCredentialProvider.CredentialProviders.VstsBuildTaskServiceEndpoint.VstsBuildTaskServiceEndpointCredentialProvider, cannot provide credentials for https://nuget.pkg.github.com/XXXXXXXXX-trial/index.json
    [CredentialProvider]VstsBuildTaskCredentialProvider - This credential provider must be run under the Team Build tasks for NuGet. Appropriate environment variables must be set.
    [CredentialProvider]Skipping NuGetCredentialProvider.CredentialProviders.VstsBuildTask.VstsBuildTaskCredentialProvider, cannot provide credentials for https://nuget.pkg.github.com/XXXXXXXXX-trial/index.json
    [CredentialProvider]GET https://nuget.pkg.github.com/XXXXXXXXX-trial/index.json
WARNING: The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
    [CredentialProvider]VstsCredentialProvider - https://nuget.pkg.github.com/XXXXXXXXX-trial/index.json is not an Azure Artifacts feed.
    [CredentialProvider]Skipping NuGetCredentialProvider.CredentialProviders.Vsts.VstsCredentialProvider, cannot provide credentials for https://nuget.pkg.github.com/XXXXXXXXX-trial/index.json
    [CredentialProvider]Unable to acquire credentials.
    [CredentialProvider]Sending response: 'Request' 'GetAuthenticationCredentials'. Time elapsed in ms: 415
    [CredentialProvider]Time elapsed in milliseconds after sending response 'Request' 'GetAuthenticationCredentials': 418
Unable to load the service index for source https://nuget.pkg.github.com/XXXXXXXXX-trial/index.json.
  Response status code does not indicate success: 401 (Unauthorized).
NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://nuget.pkg.github.com/XXXXXXXXX-trial/index.json. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass15_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<GetAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<GetServiceIndexResourceV3>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<GetServiceIndexResourceV3>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<TryCreate>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.PackageUpdateResourceV3Provider.<TryCreate>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.CommandRunnerUtility.<GetPackageUpdateResource>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by dominoFire** [comment]
Does this also happen with `dotnet nuget push` ? https://docs.microsoft.com/dotnet/core/tools/dotnet-nuget-push

**Comment by nkolev92** [comment]
Hey @qlikTERror 

The API key and the general authentication have 2 different purposes here. 

The general auth is something that a source can enforce as they see fit, but API keys are generally used for push scenarios *only*.

The credential provider will kick in 401/403 scenarios, and in this case it's when getting the service index, *before* you can push a package. 

Basically, you to be able to access the feed, before you can use something for your user with an API key. 

Have you attempted to run nuget.exe and allowing the plugin to ask for auth? 
It looks it tried, but it couldn't, because interactive mode was disabled: 

> The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`

**Comment by zivkan** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
