### ISSUE TITLE
[Bug]: NuGet.exe depends on Microsoft.Build.Framework.dll 4.0.0.0 from the GAC

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#11538]
### NuGet Product Used

NuGet.exe

### Product Version

6.0.0.280

### Worked before?

No

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Nuget.exe references Microsoft.Build.Framework.dll and Microsoft.Build.Utilities.v4.0.dll which are both loaded from the GAC:

```
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Framework\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Framework.dll
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Utilities.v4.0\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Utilities.v4.0.dll
```

If you unGAC all MSBuild dlls on the machine, nuget.exe stops working:

```
Could not load file or assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   --- End of inner exception stack trace ---
   at NuGet.CommandLine.Program.Initialize(IFileSystem fileSystem, IConsole console)
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

I love that nuget.exe is almost truly standalone, but those two old MSBuild dependencies ruin it. Sometimes we ask customers to  UnGAC MSBuild .dlls, but after that various tools stop breaking. 

I think it would be nice if nuget.exe was truly standalone.

**Comment by nkolev92** [comment]
That might be coming from: https://github.com/NuGet/NuGet.Client/blame/4af7d7a3f4d8644f2329eb00b1c29d64eb553119/src/NuGet.Core/NuGet.Build.Tasks/NuGet.Build.Tasks.csproj#L46-L47. 

It looks like we're already using the package versions in other cases, but for some reason we're not doing that for NuGet.exe.
