### ISSUE TITLE
[Bug]: Restore fails in VS with NullReferenceException when unloaded project uses lock file

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#11590]
### NuGet Product Used

Other/NA

### Product Version

17.1

### Impact

It's more difficult to complete my work

### Repro Steps & Context

From internal issue: https://developercommunity.visualstudio.com/t/Restoring-nuget-packages-in-a-solution-w/1659149

Normally when you have a project reference to project that is not in the solution, and it has not yet been restored/built, you get an NU1105 error.

However, if the project uses a lock file, then VS will report a null reference exception. This makes it very difficult to determine what the problem is, and even if you happen to know that it's missing a project in the solution, the NRE doesn't tell us which project isn't in the solution.

[unloadedWithLockFile.zip](https://github.com/NuGet/Home/files/8051829/unloadedWithLockFile.zip)

Open sln2.sln, and if you ever build/restore MyLib or sln1.sln, then make sure to delete the obj/ folders in order to repro the bug when opening sln2.sln again. 

### Verbose Logs

```shell
Error occurred while restoring NuGet packages: System.NullReferenceException: Object reference not set to an instance of an object.
at NuGet.ProjectModel.PackagesLockFileUtilities.IsLockFileValid(DependencyGraphSpec dgSpec, PackagesLockFile nuGetLockFile)
at NuGet.Commands.RestoreCommand.<EvaluatePackagesLockFileAsync>d__46.MoveNext()
```

**Comment by danielsada** [comment]
Any update on this? @zivkan :)?

**Comment by zivkan** [comment]
Please add a 👍 reaction to the original commit in this issue, so that this issue can bubble up [our issues sorted by 👍 ](https://github.com/NuGet/Home/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). Also consider upvoting the developercommunity issue. This helps us prioritize based on impact.

**Comment by aortiz-msft** [comment]
This also reproduces in 16.11.

**Comment by markusschaber** [comment]
This one has just bitten me :-(

**Comment by markusschaber** [comment]
> Also consider upvoting the developercommunity issue. This helps us prioritize based on impact.

The developercommunit issue cannot be voted, as it's "closed-duplicate" with reference to this github issue. 👎
