### ISSUE TITLE
[Bug]: asp.net core in IIS 

### ISSUE THREAD

**Issue by jmecosta** [NuGet/Home#11674]
### NuGet Product Used

NuGet SDK

### Product Version

6.1.0

### Impact

I'm unable to use this version

### Repro Steps & Context

create a asp.net core app and run on IIS
```
      <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" hostingModel="inprocess">
        <environmentVariables>
          <environmentVariable name="COMPLUS_ForceENC" value="1" />
          <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Production" />
        </environmentVariables>
      </aspNetCore>
```

on a IHostedServive, use:
```
ILogger logger = NullLogger.Instance;
            CancellationToken cancellationToken = CancellationToken.None;
            SourceCacheContext cache = new SourceCacheContext();
            SourceRepository repository = Repository.Factory.GetCoreV3(feedUrl);
            FindPackageByIdResource resource = await repository.GetResourceAsync<FindPackageByIdResource>();
```

This will throw the following exception:

```
Application: w3wp.exe
CoreCLR Version: 5.0.1422.5710
.NET Version: 5.0.14
Description: The process was terminated due to an unhandled exception.
Exception Info: NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source http://ts-nuget.teklaad.tekla.com/nuget/ts-nuget/v3/index.json.
 ---> System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\config\systemprofile' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at NuGet.Configuration.Settings.LoadUserSpecificSettings(String root, String configFileName, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at NuGet.Configuration.Settings.LoadSettingsForSpecificConfigs(String root, String configFileName, List`1 validSettingFiles, IMachineWideSettings machineWideSettings, Boolean loadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
   at NuGet.Configuration.Settings.LoadSettings(String root, String configFileName, IMachineWideSettings machineWideSettings, Boolean loadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
   at NuGet.Configuration.Settings.LoadDefaultSettings(String root, String configFileName, IMachineWideSettings machineWideSettings, SettingsLoadingContext settingsLoadingContext)
   at NuGet.Configuration.Settings.LoadDefaultSettings(String root, String configFileName, IMachineWideSettings machineWideSettings)
   at NuGet.Configuration.ProxyCache.FromDefaultSettings()
   at NuGet.Configuration.ProxyCache.<>c.<.cctor>b__18_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at NuGet.Configuration.ProxyCache.get_Instance()
   at NuGet.Protocol.HttpHandlerResourceV3Provider.CreateResource(PackageSource packageSource)
   at NuGet.Protocol.HttpHandlerResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
   at NuGet.Protocol.HttpSource.CreateHttpClientAsync()
   at NuGet.Protocol.HttpSource.EnsureHttpClientAsync()
   at NuGet.Protocol.HttpSource.GetThrottledResponse(Func`1 requestFactory, TimeSpan requestTimeout, TimeSpan downloadTimeout, Int32 maxTries, Boolean isRetry, Boolean isLastAttempt, Guid sessionId, ILogger log, CancellationToken cancellationToken)
   at NuGet.Protocol.HttpSource.<>c__DisplayClass15_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   --- End of inner exception stack trace ---
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
   at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResourceProvider.TryCreate(SourceRepository sourceRepository, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
   at TeklaQualityHub.Services.TsPackageService.getLatestVersionFromFeedByPackage(String packageName, String feedUrl) in D:\prod\BatTools\teklaqualityhub\TeklaQualityHub\Services\TsPackageService.cs:line 207
   at TeklaQualityHub.Services.TsPackageService.UpdateVersion(TsPackage package, String urlFeed) in D:\prod\BatTools\teklaqualityhub\TeklaQualityHub\Services\TsPackageService.cs:line 190
   at TeklaQualityHub.Services.TsPackageService.SetLatestVersionsFromFeed(IConfiguration configuration) in D:\prod\BatTools\teklaqualityhub\TeklaQualityHub\Services\TsPackageService.cs:line 172
   at TeklaQualityHub.Services.TsPackageService.DoWork(Object state) in D:\prod\BatTools\teklaqualityhub\TeklaQualityHub\Services\TsPackageService.cs:line 117
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Changing the permissions of C:\Windows\system32\config\systemprofile for IIS_USRS makes the exception go away but the application no longer works as it worked earlier so this is not an option

Ive changed NUGET_PACKAGES to c:\Temp\packages without success. 

How to configure the cache so it goes to write location for the IIS_USR user

thanks in advance

**Comment by jeffkl** [comment]
The code is attempting to create a default `NuGet.Config` under `%USERPROFILE% which happens to be an inaccessible path in this scenario.  Can you trying setting the `USERPROFILE` to a path that is writable?

**Comment by jmecosta** [comment]
Would this be any different than making the system 32 folder writable which i did? When I did this the exception was gone but as I mention the all IIS no longer worked

I'm not so comfortable changing system parameters under IIS user because that might cause other problems that I would rather avoid

There is also the a very good reason why those folders are not writable. This is a web server and allowing IIS to have write access to it might cause security issues

**Comment by jeffkl** [comment]
I would not recommend changing file permissions.  NuGet currently expects to run as a "user" or at least in a context where it has a user profile that is writable.  Redirecting the UserProfile when NuGet is running to a folder that is writable should fix the problem.

**Comment by jmecosta** [comment]
Ok thanks I can try to work around it to have a writable folder before calling the api.

Though it would be nice if we could simple disable cache since that was also possible in the nuget cli
