### ISSUE TITLE
"Illegal characters in path" (Solution Directory)

### ISSUE THREAD

**Issue by papeh** [NuGet/Home#11764]
Attempting a `nuget install` with an incorrect solution directory gives the cryptic error "Illegal characters in path." The first assumption is that there is a problem with the PATH environment variable, but [the line in question](https://github.com/NuGet/NuGet.Client/blob/f7208c454ebf18fc37b15fda3438d6a5ece6cdd7/src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs#L115) combines the Solution Directory with ".nuget". This clue seems to indicate illegal characters in the solution directory, but the solutionDirectory specified on my command line is legal.

The real problem is that the solution is at `C:\repos\repo\src\Solution.sln`, but the specified solution directory is `C:\repos\repo\build\`. This is a legal path, so I assume that some other code has changed the path from the command line to something illegal, but the message doesn't give much help:
```
C:\repos\repo\build>"C:\repos\repo\build\/nuget.exe" install BuildTasks -verbosity detail -excludeVersion -version 2.3.1 -solutionDirectory "C:\repos\repo\build\"
NuGet Version: 6.1.0.106
Illegal characters in path.
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at NuGet.CommandLine.InstallCommand.CalculateEffectiveSettings()
   at NuGet.CommandLine.InstallCommand.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

_Originally posted by @papeh in https://github.com/NuGet/Home/issues/8373#issuecomment-1104447279_

@chris1248 also suggests an improved message in https://github.com/NuGet/Home/issues/8373#issuecomment-656985569

https://github.com/NuGet/NuGet.Client/pull/4586 improves the message.

**Comment by papeh** [comment]
Output after wrapping exceptions:
```
C:\repos\repo\build>"C:\repos\repo\build\/nuget.exe" install BuildTasks -verbosity detail -excludeVersion -version 2.3.1 -solutionDirectory "C:\repos\repo\build\"
NuGet Version: 6.3.0.32767
Invalid solution directory: 'C:\repos\repo\build"'
  Illegal characters in path.
System.ArgumentException: Invalid solution directory: 'C:\repos\repo\build"' ---> System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at NuGet.CommandLine.InstallCommand.CalculateEffectiveSettings()
   --- End of inner exception stack trace ---
   at NuGet.CommandLine.InstallCommand.CalculateEffectiveSettings()
   at NuGet.CommandLine.InstallCommand.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

I added another commit to NuGet/NuGet.Client#4586 to trim `"` from paths passed to `Path.Combine` but then realized that it may be better to trim `"` from all paths as soon as they're passed on the command line, since quoting paths is common on Windows, and the command line processor is retaining them in some cases when it shouldn't. I'm happy to create a separate issue and PR for this, but only if the maintainers like the idea.
