### ISSUE TITLE
[Feature]: dotnet list [project | solution] package does not work with solution filters

### ISSUE THREAD

**Issue by DOMZE** [NuGet/Home#11789]
### NuGet Product Used

dotnet.exe

### Product Version

6.0.202

### Impact

It's more difficult to complete my work

### Repro Steps & Context

`dotnet restore` works with [solution filters](https://docs.microsoft.com/en-us/visualstudio/msbuild/solution-filters?view=vs-2022).

`dotnet list solution.slnf package --vulnerable` fails with

```
error: Parameter "xml" cannot be null.

Usage: NuGet.CommandLine.XPlat.dll package list [arguments] [options]
```

Not sure if this is a bug or a feature that has not been implemented.

### Verbose Logs

```shell
dotnet list solution.slnf package --vulnerable

The following sources were used:
   https://api.nuget.org/v3/index.json
   C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

error: Parameter "xml" cannot be null.


Usage: NuGet.CommandLine.XPlat.dll package list [arguments] [options]

Arguments:
  <PROJECT | SOLUTION>  A path to a project, solution file or directory.

Options:
  -h|--help               Show help information
  --force-english-output  Forces the application to run using an invariant, English-based culture.
  --framework             Specifies the target framework for which the packages will be listed.
  --deprecated            Displays only the packages marked deprecated by the authors.
  --outdated              Displays only the packages that need updates with the latest version from the sources.
  --vulnerable            Displays only the packages flagged as vulnerable.
  --include-transitive    Includes transitive packages too in the result.
  --include-prerelease    Considers prerelease versions when looking for latest. Works only with `--outdated`.
  --highest-patch         Considers only the versions with matching minor and major. Works only with `--outdated`.
  --highest-minor         Considers only the versions with matching major. Works only with `--outdated`.
  --source                Sources to lookup for latest versions. Works only with `--outdated`.
  --config                A path to a config file to specify sources. Works only with `--outdated`.
  --interactive           Allow the command to block and require manual action for operations like authentication.
  -v|--verbosity          Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].
```

**Comment by martinrrm** [comment]
My understanding is that Solution Filters only works with msbuild, not dotnet, when you do a `dotnet restore` it is going to restore the `.sln`. You can do a msbuild -r to restore the `.slnf`. 

You can try using [msbuild commands](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022) and see if you can do it. If you think this should be a feature you can open a feature request so the community can vote on it.

**Comment by martinrrm** [comment]
Reopening, after talking with the team, they explained me that Solution Filter works with dotnet

**Comment by dalibor-florian** [comment]
I have same problem while listing packages.
I'm using command `dotnet list <csproj> package --outdated`.
It worked on version 7.0.200 but today after upgrade to 7.0.201 i am getting same error as above.

```
error: Parameter "xml" cannot be null.


Usage: NuGet.CommandLine.XPlat.dll package list [arguments] [options]

Arguments:
  <PROJECT | SOLUTION>  A path to a project, solution file or directory.

Options:
  -h|--help               Show help information
  --force-english-output  Forces the application to run using an invariant, English-based culture.
  --framework             Specifies the target framework for which the packages will be listed.
  --deprecated            Displays only the packages marked deprecated by the authors.
  --outdated              Displays only the packages that need updates with the latest version from the sources.
  --vulnerable            Displays only the packages flagged as vulnerable.
  --include-transitive    Includes transitive packages too in the result.
  --include-prerelease    Considers prerelease versions when looking for latest. Works only with `--outdated`.
  --highest-patch         Considers only the versions with matching minor and major. Works only with `--outdated`.
  --highest-minor         Considers only the versions with matching major. Works only with `--outdated`.
  --source                Sources to lookup for latest versions. Works only with `--outdated`.
  --config                A path to a config file to specify sources. Works only with `--outdated`.
  --format                Set the report output format. 
  --output-version        The version of report output.
  --interactive           Allow the command to block and require manual action for operations like authentication.
  -v|--verbosity          Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].

```

**Comment by Sumit10612** [comment]
just wondering, is there any update on this?
is there any plan to make this work with solution filters? as the rest of the `dotnet` command does support `.slnf`.

**Comment by Psyk0loge** [comment]
Had a very similar issue where I just tried to run: "dotnet list package --vulnerable" in the command line and received this: 
"error: Parameter "xml" cannot be null." 

I later realized I had done a change in the code and it would not compile anymore...
When fixing the issue the command worked again...

the command seems to only work if you code complies...

Don't 100% know if it is related to the issue of op

**Comment by CedX** [comment]
Same issue with a solution file using the new `.slnx` format.

```shell
dotnet list solution.slnx package --outdated
# error: Parameter "xml" cannot be null.
```

**Comment by belav** [comment]
I ran into this when using the new `.slnx` format. Net9 is able to run the command against it, but net8 cannot.

**Comment by tcrory** [comment]
I ran into this today using .NET version 9.0.203 on Windows 10.0.22631.

Running with diagnostic level verbosity gave the following result:

```
PS C:\path\to\directory> dotnet list hidden.sln package -v diag
error: Parameter "xml" cannot be null.
trace: System.AggregateException: One or more errors occurred. (Parameter "xml" cannot be null.)
trace:  ---> System.ArgumentNullException: Parameter "xml" cannot be null.
trace:    at Microsoft.Build.Shared.ErrorUtilities.ThrowArgumentNull(String parameterName, String resourceName)
trace:    at Microsoft.Build.Evaluation.Project..ctor(ProjectRootElement xml, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext, IDirectoryCacheFactory directoryCacheFactory, Boolean interactive)
trace:    at Microsoft.Build.Evaluation.Project..ctor(ProjectRootElement xml)
trace:    at NuGet.CommandLine.XPlat.MSBuildAPIUtility.GetProject(String projectCSProjPath)
trace:    at NuGet.CommandLine.XPlat.ListPackageCommandRunner.GetProjectMetadataAsync(String projectPath, ListPackageReportModel listPackageReportModel, MSBuildAPIUtility msBuild, ListPackageArgs listPackageArgs)
trace:    at NuGet.CommandLine.XPlat.ListPackageCommandRunner.GetReportDataAsync(ListPackageArgs listPackageArgs)
trace:    at NuGet.CommandLine.XPlat.ListPackageCommandRunner.ExecuteCommandAsync(ListPackageArgs listPackageArgs)
trace:    at NuGet.CommandLine.XPlat.ListPackageCommand.<>c__DisplayClass0_1.<<Register>b__1>d.MoveNext()
trace:    --- End of inner exception stack trace ---
trace:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
trace:    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
trace:    at NuGet.CommandLine.XPlat.Program.MainInternal(String[] args, CommandOutputLogger log, IEnvironmentVariableReader environmentVariableReader)
```

**Comment by zivkan** [comment]
roadblock: NuGet uses MSBuild's API to load solution files, but [MSBuild don't want to make supporting solution filters public](https://github.com/dotnet/msbuild/issues/9981)

The VS team that is responsible for solution files created a package, but [the PR to add slnf support has been open for months](https://github.com/microsoft/vs-solutionpersistence/pull/86)

So, currently the only options are to use reflection to get private data out of MSBuild's API, and hope they don't rename anything causing the reflection to fail.  Or duplicate other people's effort and implement our own slnf file parsing. Given the simplicity of the slnf format that seems easy enough, but if newer versions of VS & the .NET SDK change the format, then duplicated code will require maintenance.

**Comment by baronfel** [comment]
The tracking issue for slnf support in VS-SolutionPersistence is https://github.com/microsoft/vs-solutionpersistence/issues/85.

I'd suggest taking the code from the SDK (it's been static for _quite_ some time), and then across nuget/SDK/MSBuild/format/all the other .NET tools we can approach the Solution team about the feature.
