### ISSUE TITLE
The NuGet CLI stops listing packages if it fails to parse one of them

### ISSUE THREAD

**Issue by PhilipAtz** [NuGet/Home#11815]
The NuGet CLI will throw an exception and stop listing packages if one of the packages in the repo fails to parse (i.e. if it throws while parsing the version number from the filename). I have tested this with version 6.1.0. The expected behaviour would be to perhaps complain about the offending package but continue with listing the rest of the packages in the repo. We shouldn't be trashing an entire repo just because an offending package got in! Also, if NuGet does complain, it should display a proper error message (including the name of the offending file) rather than dumping a cryptic exception.

Here is a sample stack trace from such an occurrence:
```
'$VERSION$' is not a valid version string.
Parameter name: value
System.ArgumentException: '$VERSION$' is not a valid version string.
Parameter name: value
   at NuGet.Versioning.NuGetVersion.Parse(String value)
   at NuGet.Protocol.MetadataReferenceCache.GetVersion(String s)
   at NuGet.Protocol.V2FeedParser.ParsePackage(String id, XElement element, MetadataReferenceCache metadataCache)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at NuGet.Protocol.V2FeedParser.<QueryV2FeedAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.V2FeedParser.<GetSearchPageAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EnumeratorAsync.<MoveNextAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Common.AggregateEnumeratorAsync`1.<MoveNextAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Commands.ListCommandRunner.<PrintPackages>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.ListCommandRunner.<ExecuteCommand>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.ListCommand.<ExecuteCommandAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by nkolev92** [comment]
@PhilipAtz 

In nearly all scenarios, NuGet employs a fail fast approach with a misbehaving feed that has unparsable data. 

Changing this everywhere would be a big change. 
Not sure if we'd want to consider changing list only at this point.
