### ISSUE TITLE
[Bug]: PM UI cannot uninstall packages in multitargeting projects

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#11914]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

VS 2022 Enterprise, Version 17.2.5

### Worked before?

No, this does not work in VS2019

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Create a new console project.

Edit the project file to look like the following:

```xml
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net5.0;net472</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup Condition="$(TargetFramework) == 'net6.0'">
		<PackageReference Include="Text2Xml.Lib" Version="1.1.4" />
		<PackageReference Include="Newtonsoft.json" Version="13.0.1" />
		<PackageReference Include="Polly.Extensions.Http" Version="3.0.0" />
	</ItemGroup>

	<ItemGroup Condition="$(TargetFramework) == 'net472'">
		<PackageReference Include="Newtonsoft.json" Version="12.0.1" />
		<PackageReference Include="Polly.Extensions.Http" Version="2.0.1" />
	</ItemGroup>

</Project>
```

Right click on the project in Solution Explorer and select 'Manage NuGet Packages'

Uninstall package in 'Polly.Extensions.Http'.

### Expected
 
Polly.extensions.http package is uninstalled

### Actual

Package is not uninstalled. See screenshot below.

![image](https://user-images.githubusercontent.com/1192347/175352616-a158531e-3495-40ff-ba7f-57f8eb7f15e5.png)

### Verbose Logs

```shell
Restoring packages for C:\Users\feaguila.REDMOND\source\repos\ConsoleAppMultitargeting2022\ConsoleAppMultitargeting2022\ConsoleAppMultitargeting2022.csproj...
System.ArgumentException: Package with id "Polly.Extensions.Http" does not exist.
   at Microsoft.VisualStudio.ProjectSystem.References.PackageReferencesService.<>c__DisplayClass3_0.<<RemoveAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.<ExecuteWithinLockAsync>d__129.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.<ExecuteWithinLockAsync>d__129.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.<UninstallPackageAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteBuildIntegratedProjectActionsAsync>d__87.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__83.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<>c__DisplayClass18_0.<<ExecuteActionsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<CatchAndRethrowExceptionAsync>d__29.MoveNext()
Time Elapsed: 00:00:00.1476767
========== Finished ==========
```

**Comment by donnie-msft** [comment]
I repro'd this today on `Version 17.6.0 Preview 3.0 [33522.577.main]` without multitargeting projects. This package targets `net6.0` 
My single project:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Iot.Device.Bindings" Version="2.0.0-prerelease.21574.2" />
  </ItemGroup>

</Project>

```

**Comment by donnie-msft** [comment]
Manually deleted PackageReference. Reopened PM UI. Installed Package using UI. Uninstalled package using UI, and this time no repro. 
It's the same project, but maybe the install did something different last time that messed up the state (of GPF?)
