### ISSUE TITLE
[Bug]: Unable to browse or restore packages via Nuget 

### ISSUE THREAD

**Issue by bradleypearce** [NuGet/Home#11987]
### NuGet Product Used

NuGet.exe

### Product Version

6.2.1

### Impact

I'm unable to use this version

### Repro Steps & Context

My colleague and I were working on a project together and updating their Nuget.config to include an additional package source we've been unable to retrieve from Nuget due to error:

[nuget.org] Unable to load the service index for source https://api.nuget.org/v3/index.json
An error occurred while sending the request.
  The underlying connection was closed: An unexpected error occurred on a send.
  Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
  An existing connection was forcibly closed by the remote host
NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://api.nuget.org/v3/index.json. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host

We've tried adjusting TLS settings, uninstalling and reinstalling visual studio and using different versions of the nuget cli but to no avail. This seems to be isolated to my colleague's machine and we've tried multiple projects and visual studio versions. 

I've attached separate logs of nuget restore and dotnet restore. Can anyone identify and help us resolve the issue please?

[nugetrestoretest.txt](https://github.com/NuGet/Home/files/9190209/nugetrestoretest.txt)
[dotnetrestorediag.txt](https://github.com/NuGet/Home/files/9190215/dotnetrestorediag.txt)

### Verbose Logs

```shell
Microsoft Windows [Version 10.0.19042.1766]
(c) Microsoft Corporation. All rights reserved.

C:\UCAS\ucas.rpa.api>nuget restore -verbosity detailed
NuGet Version: 5.11.0.10
Restoring NuGet packages for solution C:\UCAS\ucas.rpa.api\Ucas.Rpa.sln.
MSBuild auto-detection: using msbuild version '17.2.1.25201' from 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
MSBuild P2P timeout [ms]: 120000
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin\msbuild.exe "C:\Users\rhyss\AppData\Local\Temp\1\NuGetScratch\xgo4qsix.ux0.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\rhyss\AppData\Local\Temp\1\NuGetScratch\nnrbk24j.txk.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="C:\ProgramData\chocolatey\lib\nuget.commandline\tools\nuget.exe" /p:RestoreSolutionDirectory="C:\UCAS\ucas.rpa.api\\" /p:SolutionDir="C:\UCAS\ucas.rpa.api\\" /p:SolutionName="Ucas.Rpa"

Running restore with 8 concurrent jobs.
Reading project file C:\UCAS\ucas.rpa.api\Ucas.Rpa.Ui\Ucas.Rpa.Ui.csproj.
Reading project file C:\UCAS\ucas.rpa.api\Ucas.Rpa.IntegrationTests\Ucas.Rpa.IntegrationTests.csproj.
Reading project file C:\UCAS\ucas.rpa.api\Ucas.Rpa.UnitTests\Ucas.Rpa.UnitTests.csproj.
Reading project file C:\UCAS\ucas.rpa.api\Ucas.Rpa.Submission\Ucas.Rpa.Submission.csproj.
Reading project file C:\UCAS\ucas.rpa.api\Ucas.Rpa.Status\Ucas.Rpa.Status.csproj.
Reading project file C:\UCAS\ucas.rpa.api\Ucas.Rpa.Db.Sync.Tests\Ucas.Rpa.Db.Sync.Tests.csproj.
Reading project file C:\UCAS\ucas.rpa.api\Ucas.Rpa.Dto\Ucas.Rpa.Dto.csproj.
Reading project file C:\UCAS\ucas.rpa.api\Ucas.Rpa.Core\Ucas.Rpa.Core.csproj.
The restore inputs for 'Ucas.Rpa.Ui' have not changed. No further actions are required to complete the restore.
The restore inputs for 'Ucas.Rpa.Dto' have not changed. No further actions are required to complete the restore.
The restore inputs for 'Ucas.Rpa.Status' have changed. Continuing restore.
The restore inputs for 'Ucas.Rpa.UnitTests' have changed. Continuing restore.
The restore inputs for 'Ucas.Rpa.Core' have changed. Continuing restore.
The restore inputs for 'Ucas.Rpa.Submission' have changed. Continuing restore.
The restore inputs for 'Ucas.Rpa.Db.Sync.Tests' have changed. Continuing restore.
The restore inputs for 'Ucas.Rpa.IntegrationTests' have changed. Continuing restore.
Committing restore...
Committing restore...
Restoring packages for C:\UCAS\ucas.rpa.api\Ucas.Rpa.Status\Ucas.Rpa.Status.csproj...
Assets file has not changed. Skipping assets file writing. Path: C:\UCAS\ucas.rpa.api\Ucas.Rpa.Ui\obj\project.assets.json
No-Op restore. The cache will not be updated. Path: C:\UCAS\ucas.rpa.api\Ucas.Rpa.Ui\obj\project.nuget.cache
Restoring packages for C:\UCAS\ucas.rpa.api\Ucas.Rpa.Submission\Ucas.Rpa.Submission.csproj...
Restoring packages for C:\UCAS\ucas.rpa.api\Ucas.Rpa.IntegrationTests\Ucas.Rpa.IntegrationTests.csproj...
Restoring packages for C:\UCAS\ucas.rpa.api\Ucas.Rpa.UnitTests\Ucas.Rpa.UnitTests.csproj...
Restoring packages for C:\UCAS\ucas.rpa.api\Ucas.Rpa.Db.Sync.Tests\Ucas.Rpa.Db.Sync.Tests.csproj...
Restoring packages for C:\UCAS\ucas.rpa.api\Ucas.Rpa.Core\Ucas.Rpa.Core.csproj...
Restored C:\UCAS\ucas.rpa.api\Ucas.Rpa.Ui\Ucas.Rpa.Ui.csproj (in 130 ms).
Assets file has not changed. Skipping assets file writing. Path: C:\UCAS\ucas.rpa.api\Ucas.Rpa.Dto\obj\project.assets.json
No-Op restore. The cache will not be updated. Path: C:\UCAS\ucas.rpa.api\Ucas.Rpa.Dto\obj\project.nuget.cache
Reading project file C:\UCAS\ucas.rpa.api\Ucas.Rpa.Db\Ucas.Rpa.Db.csproj.
Restored C:\UCAS\ucas.rpa.api\Ucas.Rpa.Dto\Ucas.Rpa.Dto.csproj (in 125 ms).
Reading project file C:\UCAS\ucas.rpa.api\Ucas.Rpa.Db.Sync\Ucas.Rpa.Db.Sync.csproj.
The restore inputs for 'Ucas.Rpa.Db.Sync' have changed. Continuing restore.
Restoring packages for C:\UCAS\ucas.rpa.api\Ucas.Rpa.Db.Sync\Ucas.Rpa.Db.Sync.csproj...
The restore inputs for 'Ucas.Rpa.Db' have changed. Continuing restore.
Restoring packages for C:\UCAS\ucas.rpa.api\Ucas.Rpa.Db\Ucas.Rpa.Db.csproj...
Restoring packages for .NETCoreApp,Version=v6.0...
Restoring packages for .NETCoreApp,Version=v6.0...
Restoring packages for .NETCoreApp,Version=v6.0...
Restoring packages for .NETCoreApp,Version=v6.0...
Restoring packages for .NETCoreApp,Version=v6.0...
Restoring packages for .NETCoreApp,Version=v6.0...
Restoring packages for .NETCoreApp,Version=v6.0...
Restoring packages for .NETCoreApp,Version=v6.0...
Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  The underlying connection was closed: An unexpected error occurred on a send.
  Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
  An existing connection was forcibly closed by the remote host
NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://api.nuget.org/v3/index.json. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.ServerWarningLogHandler.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.StsAuthenticationHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.HttpSourceAuthenticationHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpRetryHandler.<>c__DisplayClass2_1.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.TimeoutUtility.<StartWithTimeout>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.HttpRetryHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<GetThrottledResponse>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<>c__DisplayClass15_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<GetAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<GetServiceIndexResourceV3>d__9.MoveNext()
   --- End of inner exception stack trace ---
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<GetServiceIndexResourceV3>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<TryCreate>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResourceProvider.<TryCreate>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.SourceRepositoryDependencyProvider.<EnsureResource>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.SourceRepositoryDependencyProvider.<FindLibraryCoreAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.SourceRepositoryDependencyProvider.<>c__DisplayClass19_0.<<FindLibraryAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.SourceRepositoryDependencyProvider.<FindLibraryAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.DependencyResolver.ResolverUtility.<>c__DisplayClass9_1.<<FindLibraryFromSourcesAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.DependencyResolver.ResolverUtility.<FindLibraryFromSourcesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.DependencyResolver.ResolverUtility.<FindLibraryByVersionAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.DependencyResolver.ResolverUtility.<FindPackageLibraryMatchAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.DependencyResolver.ResolverUtility.<FindLibraryMatchAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.DependencyResolver.ResolverUtility.<FindLibraryEntryAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
```

**Comment by bradleypearce** [comment]
we've also tried delete nuget.config in %AppData% and numerous other things but no closer to fixing this.

**Comment by bradleypearce** [comment]
Can anyone help please? My colleague's nuget is in an unrecoverable state at the moment.

**Comment by martinrrm** [comment]
Hi! I have some questions so we can know exactly what can be causing this error:

- What OS are you using? 
- Are you using a proxy? 
- Are you able to open https://api.nuget.org/v3/index.json in the browser? 
- Can you try and create a minimal C# application so we can test the connection? You can look at this https://github.com/NuGet/Home/issues/10414#issuecomment-752085971

**Comment by bradleypearce** [comment]
Hi thanks for the reply.

We're using Windows 10
No proxy 
Yes we only have a problem when using nuget, browser works fine 
We have tried this also, nothing seems to help and we can't get anything working.

**Comment by martinrrm** [comment]
Yes please, if possible, add the exception

**Comment by bradleypearce** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/7002788/182123147-a70f546b-3a04-4052-9465-6fd8af39268f.png)
After running the test code we get this exception
