### ISSUE TITLE
SikuliIntegrator 1.1.0 : Click action working fine but getting exceptions for Wait and DoubleClick

### ISSUE THREAD

**Issue by hariom4me** [NuGet/Home#1208]
Exception for SikuliAction.Wait :

Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\hariom\AppData\Local\Temp\tmplib\Win32Util.dll: Can't find dependent libraries
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
    at java.lang.Runtime.load0(Runtime.java:795)
    at java.lang.System.load(System.java:1062)
    at com.wapmx.nativeutils.jniloader.NativeLoader.loadLibrary(NativeLoader.java:44)
    at org.sikuli.script.Win32Util.<clinit>(Win32Util.java:19)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:190)
    at org.sikuli.script.Env.getOSUtil(Env.java:91)
    at org.sikuli.script.ScreenHighlighter.init(ScreenHighlighter.java:180)
    at org.sikuli.script.ScreenHighlighter.<init>(ScreenHighlighter.java:293)
    at org.sikuli.script.Screen.initBounds(Screen.java:105)
    at org.sikuli.script.Screen.<init>(Screen.java:117)
    at com.sikuliintegrator.Operation.Wait(Operation.java:222)
    at com.sikuliintegrator.Pointer.main(Pointer.java:122)

---

Note: I have added "D:\Hari Om\Sikuli\Sikuli-IDE\libs;" to PATH of Environment.
I am using portable version of Sekuli(Sikuli-X-1.0rc3 (r905)-win32.zip). I have extracted the Sekuli files to path "D:\Hari Om\Sikuli\Sikuli-IDE".
Java version is "1.7.0_45"

**Comment by yishaigalatzer** [comment]
We don't provide support for individual nuget packages. You can use the following link to contact the owner  - https://www.nuget.org/packages/SikuliIntegrator/ContactOwners
