### ISSUE TITLE
Test NuGet.Protocol.FuncTest.PluginTests.GetOrCreateAsync_WithUnhandledExceptionInPlugin_Throws is flaky

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#12122]
It's been failing very regularly recently: 
![image](https://user-images.githubusercontent.com/5030577/192705205-73d1046a-3e9f-47cb-bd8e-abde9d802d24.png)

Test error message:

```text
Plugin 'Plugin.Testable' failed within 10.139 seconds with exit code 57005.
Expected: True
Actual:   False
```

Stack trace:

```text
   at NuGet.Protocol.FuncTest.PluginTests.<GetOrCreateAsync_WithUnhandledExceptionInPlugin_Throws>d__7.MoveNext() in D:\a\_work\1\s\test\NuGet.Core.FuncTests\NuGet.Protocol.FuncTest\PluginTests.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by dominoFire** [comment]
The exit code 57005 in hexadecimal is 0xDEAD ; does this ring a bell, @jeffkl ?

**Comment by jeffkl** [comment]
`0xDEAD` means that Azure Watson intercepted a crash and captured a memory dump.  You can search for the machine and process name at https://aka.ms/azurewatson
