### ISSUE TITLE
[Bug]: MSB4242: SDK Resolver Failure due to System.Threading.AbandonedMutexException

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#12159]
### NuGet Product Used

dotnet.exe

### Product Version

SDK 6.0.402

### Impact

I'm unable to use this version

### Repro Steps & Context

Tracking issue for https://github.com/dotnet/sdk/issues/28488. Essentially, this issue can be hit if solution has multiple projects trying to download custom SDKs using NuGet resolver functionality.

**Comment by kartheekp-ms** [comment]
Same error is reported in the following 2 GitHub action runs.

- https://github.com/vezel-dev/cathode/actions/runs/3239525805/jobs/5309017199#step:4:1
- https://github.com/vezel-dev/zig-sdk/actions/runs/3239510618/jobs/5308984814#step:4:1

**Comment by kartheekp-ms** [comment]
Sorry for the inconvenience caused by this bug. For folks who are hitting this issue, as a workaround, would it be possible to execute `dotnet nuget --version` command before running the restore. In that way we don't hit the race condition that is causing these failures intermittently.

**Comment by alexrp** [comment]
I just ran into another failure that seems like it could be related (this is with the aforementioned workaround applied): https://github.com/vezel-dev/niru/actions/runs/3260762897/jobs/5354602659#step:4:15

```
Package "sourcelink" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
```

This one seems rare - it's the first time I've seen it since applying the workaround and it didn't happen on a subsequent run.

**Comment by breidikl** [comment]
The workaround has been working in our environment so far, thanks.

**Comment by VemundH** [comment]
I initially reported here: https://developercommunity.visualstudio.com/t/NuGet---race-condition-NuGetCommonMigr/10175710
Looks like the same issue

**Comment by cliffchapmanrbx** [comment]
Thanks for getting this fixed! Our team just ran into it as well. Is there a good place to set up a notification for when this ships? Or a particular dotnet SDK version it'll end up in we can watch out for?

**Comment by kartheekp-ms** [comment]
As far as I know, customers can hit this bug only if they have multiple projects trying to download custom SDKs using NuGet resolver functionality.

**Comment by cliffchapmanrbx** [comment]
> As far as I know, customers can hit this bug only if they have multiple projects trying to download custom SDKs using NuGet resolver functionality.

Yes, we have multiple projects trying to download custom SDKs using NuGet.

**Comment by kartheekp-ms** [comment]
@breidikl @cliffchapmanrbx @alexrp @VemundH @brunolins16 - sorry for the direct ping. This issue is fixed in preview versions of .NET 8. Would it be possible to install preview versions of .NET 8 & check whether the restore succeeds or not? Thanks for your help in advance.
https://github.com/dotnet/installer/blob/main/README.md#table

**Comment by cliffchapmanrbx** [comment]
Thank you for the information!

Our current automation harness makes it a little difficult to test this in-situ, I will see if we can construct an isolated environment to test it.

**Comment by brunolins16** [comment]
@kartheekp-ms Is that issue fixed in .NET 7 as well?

**Comment by kartheekp-ms** [comment]
> Is that issue fixed in .NET 7 as well?

@brunolins16 - Not yet. The fix is currently in .NET 8 preview versions. Hence asking the community to help us to validate the fix by installing .NET 8 preview version.

**Comment by kartheekp-ms** [comment]
NuGet's CI build also failed with this error message while running [cross verification tests job](https://github.com/NuGet/NuGet.Client/blob/340d447dfc6eaa0cb5d8c25df69fe7f235e37d62/eng/pipelines/templates/CrossFramework_Tests_On_Windows.yml#L65-L70).

```
Run Cross Verify Tests (stop on error)

View raw log

Starting: Run Cross Verify Tests (stop on error)
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script
Version      : 1.2.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
==============================================================================
. 'C:\Users\VssAdministrator\AppData\Local\Temp\081d613b-729c-4cc0-860e-a8b23716ad52.ps1' 
  Determining projects to restore...
##[error]Unhandled exception. System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitOne(TimeSpan timeout, Boolean exitContext)
   at NuGet.Common.Migrations.MigrationRunner.Run()
   at NuGet.CommandLine.XPlat.Program.MainInternal(String[] args, CommandOutputLogger log)
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)
```

<img width="987" alt="image" src="https://user-images.githubusercontent.com/52756182/202822803-598bb234-70d6-43d8-a6aa-a616ae2df182.png">

**Comment by kartheekp-ms** [comment]
Another NuGet's CI build also failed with this error message while [running cross verify tests job](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6997210&view=logs&j=0caed565-dcc2-5613-b65c-1dbd87b73411&t=6e5c9ba3-eccb-5294-9708-377fa554607c&l=11).

```log
Run Cross Verify Tests (stop on error)

[View raw log](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_apis/build/builds/6997210/logs/133)

Starting: Run Cross Verify Tests (stop on error)
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script
Version      : 1.2.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
==============================================================================
. 'C:\Users\VssAdministrator\AppData\Local\Temp\04ff27a5-dc15-4dc5-a390-16aad32157d0.ps1' 
  Determining projects to restore...
##[error]Unhandled exception. System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitOne(TimeSpan timeout, Boolean exitContext)
   at NuGet.Common.Migrations.MigrationRunner.Run()
   at NuGet.CommandLine.XPlat.Program.MainInternal(String[] args, CommandOutputLogger log)
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)
Unhandled exception. System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitOne(TimeSpan timeout, Boolean exitContext)
   at NuGet.Common.Migrations.MigrationRunner.Run()
   at NuGet.CommandLine.XPlat.Program.MainInternal(String[] args, CommandOutputLogger log)
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)
```
cc @dominoFire

**Comment by kartheekp-ms** [comment]
[Another NuGet's CI build](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7016143&view=logs&j=0caed565-dcc2-5613-b65c-1dbd87b73411&t=6e5c9ba3-eccb-5294-9708-377fa554607c&s=96a6d890-a73a-518a-a34d-9348ed71ca98) failed with the same error message. cc @erdembayar 

![image](https://user-images.githubusercontent.com/52756182/204365070-ab347644-3b8e-4a8d-a337-c88efc4c4b54.png)

**Comment by brunolins16** [comment]
@kartheekp-ms we are getting different errors during the migrations. Do you think it is related?

Pipeline: 
https://dev.azure.com/dnceng-public/public/_build/results?buildId=102152&view=logs&j=b72e85ab-3386-5aa9-6405-3837662d9688&t=5d75deca-26a1-543d-80c0-3108c555a3cb
PR: https://github.com/dotnet/aspnetcore/pull/45461/checks?check_run_id=9898841275

``` log
2022-12-05T18:42:53.1844981Z   Determining projects to restore...
2022-12-05T18:42:55.3973271Z [39;49m[31m/mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22531.1/NuGet.targets(132,5): error MSB4018: The "RestoreTask" task failed unexpectedly. [/tmp/88fd2929-aece-48eb-9b51-32ecd3394fd9/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22575.1/tools/Tools.proj]
2022-12-05T18:42:55.4229281Z ##[error].dotnet/sdk/8.0.100-alpha.1.22531.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) The "RestoreTask" task failed unexpectedly. [/tmp/88fd2929-aece-48eb-9b51-32ecd3394fd9/restore.csproj]
2022-12-05T18:42:55.4249527Z [39;49m[31m/mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22531.1/NuGet.targets(132,5): error MSB4018: System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations' [/tmp/88fd2929-aece-48eb-9b51-32ecd3394fd9/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22575.1/tools/Tools.proj]
2022-12-05T18:42:55.4258516Z ##[error].dotnet/sdk/8.0.100-alpha.1.22531.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations' [/tmp/88fd2929-aece-48eb-9b51-32ecd3394fd9/restore.csproj]
2022-12-05T18:42:55.4264481Z [39;49m[31m/mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22531.1/NuGet.targets(132,5): error MSB4018: at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew) [/tmp/88fd2929-aece-48eb-9b51-32ecd3394fd9/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22575.1/tools/Tools.proj]
2022-12-05T18:42:55.4275185Z ##[error].dotnet/sdk/8.0.100-alpha.1.22531.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew) [/tmp/88fd2929-aece-48eb-9b51-32ecd3394fd9/restore.csproj]
2022-12-05T18:42:55.4279966Z [39;49m[31m/mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22531.1/NuGet.targets(132,5): error MSB4018: at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name) [/tmp/88fd2929-aece-48eb-9b51-32ecd3394fd9/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22575.1/tools/Tools.proj]
2022-12-05T18:42:55.4287482Z ##[error].dotnet/sdk/8.0.100-alpha.1.22531.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name) [/tmp/88fd2929-aece-48eb-9b51-32ecd3394fd9/restore.csproj]
2022-12-05T18:42:55.4294697Z [39;49m[31m/mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22531.1/NuGet.targets(132,5): error MSB4018: at NuGet.Common.Migrations.MigrationRunner.Run() [/tmp/88fd2929-aece-48eb-9b51-32ecd3394fd9/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22575.1/tools/Tools.proj]
2022-12-05T18:42:55.4301739Z ##[error].dotnet/sdk/8.0.100-alpha.1.22531.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at NuGet.Common.Migrations.MigrationRunner.Run() [/tmp/88fd2929-aece-48eb-9b51-32ecd3394fd9/restore.csproj]
2022-12-05T18:42:55.4306707Z [39;49m[31m/mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22531.1/NuGet.targets(132,5): error MSB4018: at NuGet.Build.Tasks.RestoreTask.Execute() [/tmp/88fd2929-aece-48eb-9b51-32ecd3394fd9/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22575.1/tools/Tools.proj]
2022-12-05T18:42:55.4314752Z ##[error].dotnet/sdk/8.0.100-alpha.1.22531.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at NuGet.Build.Tasks.RestoreTask.Execute() [/tmp/88fd2929-aece-48eb-9b51-32ecd3394fd9/restore.csproj]
2022-12-05T18:42:55.4319646Z [39;49m[31m/mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22531.1/NuGet.targets(132,5): error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/tmp/88fd2929-aece-48eb-9b51-32ecd3394fd9/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22575.1/tools/Tools.proj]
2022-12-05T18:42:55.4327412Z ##[error].dotnet/sdk/8.0.100-alpha.1.22531.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/tmp/88fd2929-aece-48eb-9b51-32ecd3394fd9/restore.csproj]
2022-12-05T18:42:55.4333214Z [39;49m[31m/mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22531.1/NuGet.targets(132,5): error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/tmp/88fd2929-aece-48eb-9b51-32ecd3394fd9/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22575.1/tools/Tools.proj]
2022-12-05T18:42:55.4343392Z ##[error].dotnet/sdk/8.0.100-alpha.1.22531.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/tmp/88fd2929-aece-48eb-9b51-32ecd3394fd9/restore.csproj]
2022-12-05T18:42:56.3098031Z   
2022-12-05T18:42:56.3127467Z   Package "dotnet-serve" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
2022-12-05T18:42:56.3129341Z      at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
2022-12-05T18:42:56.3131966Z      at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
2022-12-05T18:42:56.3134155Z      at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
2022-12-05T18:42:56.3141284Z   
2022-12-05T18:42:56.3142951Z   Tool 'dotnet-dump' (version '6.0.322601') was restored. Available commands: dotnet-dump
2022-12-05T18:42:56.3144776Z   Tool 'dotnet-ef' (version '8.0.0-alpha.1.22605.6') was restored. Available commands: dotnet-ef
2022-12-05T18:42:56.3146492Z   Tool 'microsoft.playwright.cli' (version '1.2.3') was restored. Available commands: playwright
```

**Comment by kartheekp-ms** [comment]
@brunolins16 - A similar was issue reported in https://github.com/dotnet/runtime/pull/78062#issuecomment-1314259386. May be this error has the same root cause mentioned in https://github.com/dotnet/runtime/issues/36823 which was created as a follow-up for https://github.com/PowerShell/PSReadLine/issues/1464.

**Comment by nikolaidk** [comment]
Got the same error in devops pipeline. Error seems related, in my case,  to 'tools' that comes with 'ubuntu-latest' image :

No error running: 
MSBuild version 17.4.0+18d5aef85 for .NET

Fails when running:
MSBuild version 17.4.1+9a89d02ff for .NET

FIX in my situation. Changed from ubuntu-latest to ubuntu-20.04 and installed net6.0 and net7.0 in seperate steps:
....
 vmImage: 'ubuntu-20.04'
....
- task: UseDotNet@2
  condition: true
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
- task: UseDotNet@2
  condition: true
  displayName: Use .NET 7.0
  inputs:
    packageType: 'sdk'
    version: '7.0.x'
....

ERROR:
MSBuild version 17.4.1+9a89d02ff for .NET
  Successfully created package '/home/vsts/work/1/s/packages/Shared.GeneratedCode.Utils.0.0.385.484.nupkg'.
  Successfully created package '/home/vsts/work/1/s/packages/Shared.GeneratedCode.Utils.0.0.385.484.symbols.nupkg'.
MSBuild version 17.4.1+9a89d02ff for .NET
/usr/share/dotnet/sdk/7.0.102/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(221,5): warning NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below: [/home/vsts/work/1/s/Shared.GeneratedCode/Shared.GeneratedCode.csproj]
/usr/share/dotnet/sdk/7.0.102/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(221,5): warning NU5128: - Add lib or ref assemblies for the netstandard2.0 target framework [/home/vsts/work/1/s/Shared.GeneratedCode/Shared.GeneratedCode.csproj]
  Successfully created package '/home/vsts/work/1/s/packages/Shared.GeneratedCode.0.0.385.484.nupkg'.
  Successfully created package '/home/vsts/work/1/s/packages/Shared.GeneratedCode.0.0.385.484.symbols.nupkg'.
System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
##[error]PowerShell exited with code '1'.

AFTER FIX:

Time Elapsed 00:00:07.74
MSBuild version 17.4.1+9a89d02ff for .NET
  Successfully created package '/home/vsts/work/1/s/packages/Shared.GeneratedCode.Utils.0.0.385.494.nupkg'.
  Successfully created package '/home/vsts/work/1/s/packages/Shared.GeneratedCode.Utils.0.0.385.494.symbols.nupkg'.
MSBuild version 17.4.1+9a89d02ff for .NET
/opt/hostedtoolcache/dotnet/sdk/7.0.102/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(221,5): warning NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below: [/home/vsts/work/1/s/Shared.GeneratedCode/Shared.GeneratedCode.csproj]
/opt/hostedtoolcache/dotnet/sdk/7.0.102/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(221,5): warning NU5128: - Add lib or ref assemblies for the netstandard2.0 target framework [/home/vsts/work/1/s/Shared.GeneratedCode/Shared.GeneratedCode.csproj]
  Successfully created package '/home/vsts/work/1/s/packages/Shared.GeneratedCode.0.0.385.494.nupkg'.
  Successfully created package '/home/vsts/work/1/s/packages/Shared.GeneratedCode.0.0.385.494.symbols.nupkg'.
MSBuild version 17.4.1+9a89d02ff for .NET
  Determining projects to restore...
  Restored /home/vsts/work/1/s/Shared.Test.Init/Shared.Test.Init.csproj (in 197 ms).
  Shared.Test.Init -> /home/vsts/work/1/s/Shared.Test.Init/bin/Debug/net7.0/Shared.Test.Init.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

**Comment by kartheekp-ms** [comment]
The patch fixing this issue has been released in February 2023 .NET SDK servicing release.

https://dotnet.microsoft.com/en-us/download/dotnet/6.0
https://dotnet.microsoft.com/en-us/download/dotnet/7.0
