### ISSUE TITLE
Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#12166]
I just ran into another failure that seems like it could be related (this is with the aforementioned workaround applied): https://github.com/vezel-dev/niru/actions/runs/3260762897/jobs/5354602659#step:4:15

```
Package "sourcelink" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
```

This one seems rare - it's the first time I've seen it since applying the workaround and it didn't happen on a subsequent run.

_Originally posted by @alexrp in https://github.com/NuGet/Home/issues/12159#issuecomment-1280048054_

**Comment by kartheekp-ms** [comment]
@alexrp - I just created this new issue for traceability because the error message is different and https://github.com/vezel-dev/niru/actions/runs/3260762897/jobs/5354602659 log says that few `dotnet tools` installed successfully. 

```
Run dotnet nuget --version # TODO: https://github.com/NuGet/Home/issues/12159
NuGet Command Line
6.4.0.94

Package "sourcelink" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)

Tool 'dotnet-counters' (version '6.0.328102') was restored. Available commands: dotnet-counters
Tool 'dotnet-dump' (version '6.0.328102') was restored. Available commands: dotnet-dump
Tool 'dotnet-gcdump' (version '6.0.328102') was restored. Available commands: dotnet-gcdump
Tool 'dotnet-sos' (version '6.0.328102') was restored. Available commands: dotnet-sos
Tool 'dotnet-stack' (version '6.0.328102') was restored. Available commands: dotnet-stack
Tool 'dotnet-symbol' (version '1.0.335501') was restored. Available commands: dotnet-symbol
Tool 'dotnet-trace' (version '6.0.328102') was restored. Available commands: dotnet-trac
```

Would it be possible to run the `dotnet tool install` command by passing `--verbosity detailed` option so that we can get some additional information about the reason for the error. Passing `--verbosity detailed` option on CI will write too much information into the logs but it would be helpful to reproduce or understand the root cause of the error.
