### ISSUE TITLE
Flaky test PackCommand_PackConsoleAppWithRID_NupkgValid

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#12194]
According to CI pipeline [failed/flaky test report](https://github.com/NuGet/Entropy/pull/94) in last 30 days `PackCommand_PackConsoleAppWithRID_NupkgValid` test failed 1 time on official pipeline and 6 times on private pipeline.

1. Official pipeline: [FailedTestsReport-OfficialBranch-2022-10-24.xlsx](https://github.com/NuGet/Home/files/9864590/FailedTestsReport-OfficialBranch-2022-10-24.xlsx)
2. Private pipeline:
![image](https://user-images.githubusercontent.com/8766776/198171853-95ed4270-a4cc-41e1-be60-ea0a50f2019a.png)

Please use `[PlatformTheory(Platform.Windows)]` test attribute when you re-enable this test.

[Stack trace 1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6811620&view=ms.vss-test-web.build-test-results-tab&runId=56876372&resultId=100261)

```
Error message
System.TimeoutException : dotnet.exe timed out: restore ConsoleApp1.csproj
Output:  Determining projects to restore...
D:\a_work\1\s.test\work\d4a81125\0bdf57b9\sdk\6.0.400-preview.22330.6\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.1' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [D:\a_work\1\s.test\work\d61b1eb7\9c43ceeb\ConsoleApp1\ConsoleApp1.csproj]
D:\a_work\1\s.test\work\d4a81125\0bdf57b9\sdk\6.0.400-preview.22330.6\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.1' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [D:\a_work\1\s.test\work\d61b1eb7\9c43ceeb\ConsoleApp1\ConsoleApp1.csproj]

Error:


Stack trace
[at NuGet.Test.Utility.CommandRunner.Run(String process, String workingDirectory, String arguments, Boolean waitForExit, Int32 timeOutInMilliseconds, Action`1 inputAction, IDictionary`2 environmentVariables) in D:\a\_work\1\s\test\TestUtilities\Test.Utility\CommandRunner.cs:line 95](https://devdiv.visualstudio.com/DevDiv/_git/60d5b0d2-d018-4a26-bae5-a3118091e051?path=%2Ftest%2FTestUtilities%2FTest.Utility%2FCommandRunner.cs&version=GBdev&_a=contents&line=95&lineEnd=96&lineStartColumn=1&lineEndColumn=1&lineStyle=plain)
[at Dotnet.Integration.Test.MsbuildIntegrationTestFixture.RestoreProjectOrSolution(String workingDirectory, String fileName, String args, Boolean validateSuccess) in D:\a\_work\1\s\test\NuGet.Core.FuncTests\Dotnet.Integration.Test\MsbuildIntegrationTestFixture.cs:line 199](https://devdiv.visualstudio.com/DevDiv/_git/60d5b0d2-d018-4a26-bae5-a3118091e051?path=%2Ftest%2FNuGet.Core.FuncTests%2FDotnet.Integration.Test%2FMsbuildIntegrationTestFixture.cs&version=GBdev&_a=contents&line=199&lineEnd=200&lineStartColumn=1&lineEndColumn=1&lineStyle=plain)
[at Dotnet.Integration.Test.PackCommandTests.PackCommand_PackConsoleAppWithRID_NupkgValid(Boolean includeSymbols) in D:\a\_work\1\s\test\NuGet.Core.FuncTests\Dotnet.Integration.Test\PackCommandTests.cs:line 459](https://devdiv.visualstudio.com/DevDiv/_git/60d5b0d2-d018-4a26-bae5-a3118091e051?path=%2Ftest%2FNuGet.Core.FuncTests%2FDotnet.Integration.Test%2FPackCommandTests.cs&version=GBdev&_a=contents&line=459&lineEnd=460&lineStartColumn=1&lineEndColumn=1&lineStyle=plain)
```

[Stack trace 2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6815400&view=ms.vss-test-web.build-test-results-tab&runId=57010312&resultId=100603)

```
System.TimeoutException : dotnet.exe timed out: restore ConsoleApp1.csproj
Output:  Determining projects to restore...
D:\a_work\1\s.test\work\65c18185\81434131\sdk\7.0.100-rtm.22510.17\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.1' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [D:\a_work\1\s.test\work\6cc16f98\8be22a1b\ConsoleApp1\ConsoleApp1.csproj]
D:\a_work\1\s.test\work\65c18185\81434131\sdk\7.0.100-rtm.22510.17\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.1' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [D:\a_work\1\s.test\work\6cc16f98\8be22a1b\ConsoleApp1\ConsoleApp1.csproj]
Retrying 'FindPackagesByIdAsync' for source 'https://pkgs.dev.azure.com/dnceng/xxx/v3/flat2/microsoft.netcore.dotnethostpolicy/index.json'.
Response status code does not indicate success: 503 (Service Unavailable).
Retrying 'FindPackagesByIdAsync' for source 'https://pkgs.dev.azure.com/dnceng/xxxxxx/v3/flat2/microsoft.netcore.dotnethostpolicy/index.json'.
Response status code does not indicate success: 503 (Service Unavailable).

Error:


Stack trace
at NuGet.Test.Utility.CommandRunner.Run(String process, String workingDirectory, String arguments, Boolean waitForExit, Int32 timeOutInMilliseconds, Action`1 inputAction, IDictionary`2 environmentVariables) in D:\a\_work\1\s\test\TestUtilities\Test.Utility\CommandRunner.cs:line 95
at Dotnet.Integration.Test.MsbuildIntegrationTestFixture.RestoreProjectOrSolution(String workingDirectory, String fileName, String args, Boolean validateSuccess) in D:\a\_work\1\s\test\NuGet.Core.FuncTests\Dotnet.Integration.Test\MsbuildIntegrationTestFixture.cs:line 208
at Dotnet.Integration.Test.PackCommandTests.PackCommand_PackConsoleAppWithRID_NupkgValid(Boolean includeSymbols) in D:\a\_work\1\s\test\NuGet.Core.FuncTests\Dotnet.Integration.Test\PackCommandTests.cs:line 460
```

**Comment by zivkan** [comment]
@erdembayar can you please copy-paste test failure information. Was an exception thrown? What was the exception message and stack trace?

**Comment by erdembayar** [comment]
> @erdembayar Erick Yondon FTE can you please copy-paste test failure information. Was an exception thrown? What was the exception message and stack trace?

Added stack trace, looks like `503` error from internal hosting causing this.
