### ISSUE TITLE
Test HttpRetryHandler_HandlesNameResolutionFailure is flaky

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#12191]
According to CI pipeline [failed/flaky test report](https://github.com/NuGet/Entropy/pull/94) in last 30 days `HttpRetryHandler_HandlesNameResolutionFailure` test failed 1 time on official pipeline and 10 times on private pipeline.

1. Official pipeline: [FailedTestsReport-OfficialBranch-2022-10-24.xlsx](https://github.com/NuGet/Home/files/9864590/FailedTestsReport-OfficialBranch-2022-10-24.xlsx)
2. Private pipeline:
![image](https://user-images.githubusercontent.com/8766776/197912203-86190aeb-0754-44cc-9c2e-ff9802d58f65.png)

[Stack trace 1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6847814&view=ms.vss-test-web.build-test-results-tab&runId=57928482&resultId=110320)

```
Error message
Assert.Equal() Failure
↓ (pos 0)
Expected: Name or service not known
Actual:   Resource temporarily unavailable
↑ (pos 0)


Stack trace
   at NuGet.Core.FuncTest.HttpRetryHandlerTests.HttpRetryHandler_HandlesNameResolutionFailure() in /home/vsts/work/1/s/test/NuGet.Core.FuncTests/NuGet.Protocol.FuncTest/HttpRetryHandlerTests.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
```

[Stack trace 2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6874995&view=ms.vss-test-web.build-test-results-tab&runId=58625610&resultId=109745)

```
Assert.Equal() Failure
↓ (pos 0)
Expected: Name or service not known
Actual:   Resource temporarily unavailable
↑ (pos 0)


Stack trace
   at NuGet.Core.FuncTest.HttpRetryHandlerTests.HttpRetryHandler_HandlesNameResolutionFailure() in /home/vsts/work/1/s/test/NuGet.Core.FuncTests/NuGet.Protocol.FuncTest/HttpRetryHandlerTests.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by zivkan** [comment]
@erdembayar can you please copy-paste test failure information. Was an exception thrown? What was the exception message and stack trace?

**Comment by erdembayar** [comment]
> @erdembayar Erick Yondon FTE can you please copy-paste test failure information. Was an exception thrown? What was the exception message and stack trace?

Added failure information, not much useful details here, no exception, probably need logging here.

**Comment by zivkan** [comment]
There is useful information. It tells us that there may be more than one "mode" (exception message) for DNS resolution failures. At least on our CI agents. But many customers use Azure DevOps for their CI as well, so they might experience the same exception messages.
