### ISSUE TITLE
Possible race condition in ConfigurationDefaults.Instance.DefaultPackageSources

### ISSUE THREAD

**Issue by awinki** [NuGet/Home#12246]
### NuGet Product Used

dotnet.exe

### Product Version

6.0.402

### Impact

It's more difficult to complete my work

### Repro Steps & Context

On our build server we get a random "Collection was modified" error when executing a dotnet restore with our solution.

The detailed build log shows an InvalidOperationException at _NuGet.Configuration.PackageSourceProvider.LoadConfigurationDefaultSources()_ while iterating the configurationDefaultSources parameter, which comes from _ConfigurationDefaults.Instance.DefaultPackageSources_.

It looks to me that there's a race conditon in _ConfigurationDefaults.Instance.DefaultPackageSources_ initializing it's member _defaultPackageSources.

### Verbose Logs

```shell
C:\Program Files\dotnet\sdk\6.0.402\NuGet.targets(132,5): error : Collection was modified; enumeration operation may not execute.
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at NuGet.Configuration.PackageSourceProvider.LoadConfigurationDefaultSources(IEnumerable`1 configurationDefaultSources)
   at NuGet.Configuration.PackageSourceProvider..ctor(ISettings settings, IEnumerable`1 configurationDefaultSources, Boolean enablePackageSourcesChangedEvent)
   at NuGet.Configuration.PackageSourceProvider..ctor(ISettings settings, Boolean enablePackageSourcesChangedEvent)
   at NuGet.Commands.RestoreArgs.GetEffectiveSourcesCore(ISettings settings, IList`1 dgSpecSources)
   at NuGet.Commands.RestoreArgs.<>c__DisplayClass101_0.<GetEffectiveSources>b__1(String root)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NuGet.Commands.RestoreArgs.GetEffectiveSources(ISettings settings, IList`1 dgSpecSources)
   at NuGet.Commands.DependencyGraphSpecRequestProvider.Create(String projectNameToRestore, ExternalProjectReference project, HashSet`1 projectReferenceClosure, RestoreArgs restoreArgs, DependencyGraphSpec projectDgSpec, SettingsLoadingContext settingsLoadingContext)
   at NuGet.Commands.DependencyGraphSpecRequestProvider.<>c__DisplayClass6_0.<GetRequestsFromItems>b__2(String projectNameToRestore)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass32_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

**Comment by erdembayar** [comment]
Given this is race condition I don't believe I can repro now. 
Looks like issue is here. 

https://github.com/NuGet/NuGet.Client/blob/20be995d651808feb5cd48f30cb97197e497377c/src/NuGet.Core/NuGet.Configuration/Settings/ConfigurationDefaults.cs#L58

**Comment by awinki** [comment]
I'm not sure how to reproduce the error either. It appears randomly on our build servers.

@erdembayar the line of code you mentioned, seems to me as problematic if two threads access the property simultaneously like the stacktrace might show.

**Comment by erdembayar** [comment]
> I'm not sure how to reproduce the error either. It appears randomly on our build servers.
> 
> @erdembayar the line of code you mentioned, seems to me as problematic if two threads access the property simultaneously like the stacktrace might show.

No problem, there's no need to reproduce the error. As I mentioned it's hard to reproduce right now, we'll discuss this during our triage meeting.

**Comment by dukorama** [comment]
I think the special circumstance here is that we first do a "nuget restore" in one build step and a "dotnet restore" immediately afterwards. And what I can remember this error only occurres since we switched to these 2 restore steps (we unfortunately need due to certain constraints). As far as I know, only build configurations with these 2 restore steps are concerned by this bug.

**Comment by erdembayar** [comment]
> I think the special circumstance here is that we first do a "nuget restore" in one build step and a "dotnet restore" immediately afterwards. And what I can remember this error only occurres since we switched to these 2 restore steps (we unfortunately need due to certain constraints). As far as I know, only build configurations with these 2 restore steps are concerned by this bug.

Please upvote the issue if hit this issue, we prioritize based on user feedback.

**Comment by MichaelKetting** [comment]
@erdembayar upvote via thunbs-up on the issue post itself? 

It's something I can confirm and it's really annoying when it happens. Would love to see a fix :)

**Comment by zivkan** [comment]
@erdembayar 

> Given this is race condition I don't believe I can repro now.

Since you linked to code, we can make a guess based on what the code is doing. I bet you can reproduce this with fairly reliability hit percentage, if you create a console app that references NuGet.Configuration and calls `ConfigurationDefaults.Instance.DefaultPackageSources in multiple threads at the same time.
