### ISSUE TITLE
Central Package Management restore fails for solutions containing .sfproj project

### ISSUE THREAD

**Issue by kmitawojciech** [NuGet/Home#12324]
### NuGet Product Used

dotnet.exe, MSBuild.exe, NuGet.exe, Other/NA

### Product Version

dotnet 6.0.4, msbuild 17.4, nuget 6.4

### Worked before?

Using packages.props instead Directory.Packages.props

### Impact

I'm unable to use this version

### Repro Steps & Context

Consider an application consisting of a project based on .net6 and a .sfproj project:

- src
  - Lib1
    - Lib1.csproj (using .NET6 and package reference )
  - App1
    - App1.sfproj (using .NET48 and packages.config)
    - packages.config   
  - Directory.Packages.props
  - App1.sln

The solution builds fine form Visual Studio. But when trying to restore the solution from tools like **dotnet, msbuild, nuget** it returns an error similar to this:
**error : Invalid restore input. Invalid target framework 'unsupported'. Input files: **..\src\App\*.sfproj.****
A sample command used:
**C:\ag\_work\_tool\dotnet\dotnet.exe restore C:\src\App1.sln --packages C:\src\App1\packages --configfile C:\ag\_work\278\Nuget\tempNuGet_697647.config --verbosity Detailed /p:Configuration=Debug /p:Platform=x64**

When using the Microsoft.Build.CentralPackageVersions and Packages.props than everything works fine. It works also fine when there are project files targeting .net48 of csproj type instead of sfproj type.

### Verbose Logs

```shell
C:\ag\_work\_tool\dotnet\dotnet.exe restore C:\src\App1.sln --packages C:\src\App1\packages --configfile C:\ag\_work\278\Nuget\tempNuGet_697647.config --verbosity Detailed /p:Configuration=Debug /p:Platform=x64

2:5>Done building target "_GenerateProjectRestoreGraphCurrentProject" in project "App1.sfproj".
   2:5>Target "_GenerateRestoreDependencies" in file "C:\ag\_work\_tool\dotnet\sdk\6.0.404\NuGet.targets" from project "C:\src\App1\App1.sfproj" (target "_GenerateProjectRestoreGraph" depends on it):
   2:5>Done building target "_GenerateRestoreDependencies" in project "App1.sfproj".
   2:5>Target "_GenerateProjectRestoreGraph" in file "C:\ag\_work\_tool\dotnet\sdk\6.0.404\NuGet.targets" from project "C:\src\App1\App1.sfproj" (entry point):
   2:5>Done building target "_GenerateProjectRestoreGraph" in project "App1.sfproj".
   2:5>Done Building Project "C:\src\App1\App1.sfproj" (_GenerateProjectRestoreGraph target(s)).
     1>Done executing task "MSBuild".
     1>Done building target "_GenerateRestoreGraph" in project "App1.sln".
     1>Target "Restore" in file "C:\ag\_work\_tool\dotnet\sdk\6.0.404\NuGet.targets" from project "C:\src\App1\App1.sfproj" (entry point):
       Task "RemoveDuplicates"
       Done executing task "RemoveDuplicates".
       Using "RestoreTask" task from assembly "C:\ag\_work\_tool\dotnet\sdk\6.0.404\NuGet.Build.Tasks.dll".
       Task "RestoreTask"
         (in) RestoreGraphItems Count '96'
         (in) RestoreDisableParallel 'False'
         (in) RestoreNoCache 'False'
         (in) RestoreIgnoreFailedSources 'False'
         (in) RestoreRecursive 'True'
         (in) RestoreForce 'False'
         (in) HideWarningsAndErrors 'False'
         (in) RestoreForceEvaluate 'False'
         (in) RestorePackagesConfig 'False'
         X.509 certificate chain validation will use the default trust store selected by .NET.
1>C:\ag\_work\_tool\dotnet\sdk\6.0.404\NuGet.targets(132,5): error : Invalid restore input. Invalid target framework 'unsupported'. Input files: C:\src\App1\App1.sfproj. [C:\src\App1.sln]
         NuGet.Commands.RestoreSpecException: Invalid restore input. Invalid target framework 'unsupported'. Input files: C:\src\App1\App1.sfproj.
            at NuGet.Commands.SpecValidationUtility.ValidateFrameworks(PackageSpec spec, IEnumerable`1 files)
            at NuGet.Commands.SpecValidationUtility.ValidateProjectSpecPackageReference(PackageSpec spec, IEnumerable`1 files)
            at NuGet.Commands.SpecValidationUtility.ValidateProjectSpec(PackageSpec spec)
            at NuGet.Commands.SpecValidationUtility.ValidateDependencySpec(DependencyGraphSpec spec, HashSet`1 projectsToSkip)
            at NuGet.Commands.DependencyGraphSpecRequestProvider.GetRequestsFromItems(RestoreArgs restoreContext, DependencyGraphSpec dgFile)
            at NuGet.Commands.DependencyGraphSpecRequestProvider.CreateRequests(RestoreArgs restoreContext)
            at NuGet.Commands.RestoreRunner.CreatePreLoadedRequests(RestoreArgs restoreContext)
            at NuGet.Commands.RestoreRunner.GetRequests(RestoreArgs restoreContext)
            at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token)
            at NuGet.Build.Tasks.BuildTasksUtility.RestoreAsync(DependencyGraphSpec dependencyGraphSpec, Boolean interactive, Boolean recursive, Boolean noCache, Boolean ignoreFailedSources, Boolean disableParallel, Boolean force, Boolean forceEvaluate, Boolean hideWarningsAndErrors, Boolean restorePC, Boolean cleanupAssetsForUnsupportedProjects, ILogger log, CancellationToken cancellationToken)
            at NuGet.Build.Tasks.RestoreTask.ExecuteAsync(ILogger log)
       Done executing task "RestoreTask" -- FAILED.
     1>Done building target "Restore" in project "App1.sln" -- FAILED.
```

**Comment by erdembayar** [comment]
@kmitawojciech 
Could you be able to share us simple repro code including `sfproj`? I'm not sure any of us have previous experience with service fabric project, so having existing repro code is handy for us.
