### ISSUE TITLE
installation rolling back always with VS 2015

### ISSUE THREAD

**Issue by WinDevInd** [NuGet/Home#1239]
Facing issue with package installation via nuget on project created with Visual Studio 2013 and running in Visual studio 2015.

It ends up with below mention error.

Resolved actions to install package 'Newtonsoft.Json.7.0.1'

For adding package 'Newtonsoft.Json.7.0.1' to project 'Analytics' that targets 'portable45-net45+win8+wp8+wpa81'.

For adding package 'Newtonsoft.Json.7.0.1' to project 'Analytics' that targets 'portable45-net45+win8+wp8+wpa81'.

Package 'Newtonsoft.Json.7.0.1' already exists in folder 'C:\Users\jay.k\Documents\WindowsRepo\WinRT\JI.WinRT\packages'

Removed reference 'Newtonsoft.Json.dll' from project 'Analytics'

Added reference 'Newtonsoft.Json' to project 'Analytics'.

Added package 'Newtonsoft.Json.7.0.1' to 'packages.config'

Added file 'packages.config' to project 'Analytics'.

For adding package 'Newtonsoft.Json.7.0.1' to project 'Analytics' that targets 'portable45-net45+win8+wp8+wpa81'.

Executing script file 'C:\Users\jay.k\Documents\WindowsRepo\WinRT\JI.WinRT\packages\Newtonsoft.Json.7.0.1\tools\install.ps1'...

Successfully installed 'Newtonsoft.Json.7.0.1' to Analytics

Install failed. Rolling back...

Removed file 'packages.config' from folder 'C:\Users\jay.k\Documents\WindowsRepo\WinRT\JI.WinRT\Analytics'.

Removed package 'Newtonsoft.Json.7.0.1' from 'packages.config'

Removed file 'packages.config'

Removed reference 'Newtonsoft.Json.dll' from project 'Analytics'

System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.

at VSLangProj.Reference.get_SourceProject()

at NuGet.PackageManagement.VisualStudio.EnvDTEProjectUtility.GetLocalProjectAssemblies(Project envDTEProject)

at NuGet.PackageManagement.VisualStudio.EnvDTEProjectUtility.GetAssemblyClosure(Project envDTEProject, IDictionary`2 visitedProjects)

at NuGet.PackageManagement.VisualStudio.EnvDTEProjectUtility.GetAssemblyClosure(Project envDTEProject, IDictionary`2 visitedProjects)

at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<addbindingredirectsasync>d__3.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<addbindingredirectsasync>d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<addbindingredirectsasync>d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<addbindingredirectsasync>d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.<<addbindingredirects>b__55_0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()

at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddBindingRedirects()

at NuGet.ProjectManagement.MSBuildNuGetProject.PostProcessAsync(INuGetProjectContext nuGetProjectContext, CancellationToken token)

at NuGet.PackageManagement.NuGetPackageManager.<executenugetprojectactionsasync>d__42.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

at NuGet.PackageManagement.NuGetPackageManager.<executenugetprojectactionsasync>d__42.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at NuGet.PackageManagement.UI.UIActionEngine.<executeactionsasync>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at NuGet.PackageManagement.UI.UIActionEngine.<performactionasync>d__3.MoveNext()

========== Finished ==========

It is happening with any packages I tried to install.
It happen in ApplicationInsights package, Caliburn package.
It's not specific to 'Newtonsoft'.
It's problem with Nuget only in the situation Where Project is created in Visual studio 2013 in now modified in Visual studio 2015 that time is it' throwing this error.

Project structure is large
- Windows phone 8.1 Project
- Windows 8.1 project
- Windows 10 UWP project
- Windows 10 UWP class library
- Windows 8.1 Class library
- Windows phone 8.1 class library
- 16 Portable class library

**Comment by emgarten** [comment]
From the stack trace it looks like this is failing when creating the binding redirects at the end.

> at VSLangProj.Reference.get_SourceProject()

You might be able to work around this by finding the unresolved C++ project reference and fixing it.

**Comment by yishaigalatzer** [comment]
@emgarten  I recall you fixing something like this in 3.2?

@WinDevInd are you able to provide a simple repro following this suggestion? We would like to be sure we fixed your exact scenario or can fix it if we didn't

**Comment by WinDevInd** [comment]
I have 2 C++ project also apart from list of projects I described above

**Comment by WinDevInd** [comment]
@emgarten Thank you so much. You pointed out exact problem.
I have 2 C++ native project Which was referenced in another Class library, and that class library was referenced in main Phone project. I tried to install package after removing the C++ project reference and it worked perfectly.
Thank you so much :)

**Comment by emgarten** [comment]
@yishaigalatzer this was fixed for project.json restores, but it looks like the calls to add binding redirects can run into the same issue. It will need to be fixed there also.

@WinDevInd glad to hear that worked. We'll get this fixed in the client.

**Comment by WinDevInd** [comment]
@emgarten Thank you :)

**Comment by emgarten** [comment]
Unresolved references will now be skipped when walking project references to find binding redirects.

NuGet/NuGet.VisualStudioExtension@98acbf4ae5856ea7fdec5078ae2cef9070a01016

**Comment by somewhatabstract** [comment]
I have VS2015 Update 3 and have just started having this issue. I cannot work out what is causing it.
