### ISSUE TITLE
An error “Failed to update binding redirects for [ProjectName].csproj: Exception has been thrown by the target of an invocation.” occurred when installing package EntityFramework 

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#12396]
### NuGet Product Used

Visual Studio Package Manager Console

### Product Version

NuGet Client Dev\6.6.0.15

### Impact

It bothers me. A fix would be nice

#### Repro Steps:  

1. Start a new instance of visual studio (Don’t open PMC while executing this test). 

2. Create a new C# Class Library (.NET Framework 4.8.1). 

3. Install “EntityFramework” package with packages.config format in PM UI. 

4. Check install logs in output window, and make sure it has executed init scripts while installing. 

#### Expected:  

No error occurs. 

#### Actual:  

An error “Failed to update binding redirects for [ProjectName].csproj: Exception has been thrown by the target of an invocation.” occurred as below screenshot.  
  
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/84695155/215727128-69bfac66-d84e-40ca-985a-f76b2a8338d0.png)

#### Note:  

1. The issue doesn’t repro when installing a package with Package Reference format.

**Comment by nkolev92** [comment]
Team Triage: @CiciLi1 Is this a 100% repro?

**Comment by nkolev92** [comment]
@CiciLi1, @v-luzh 
When you verify the bugs can you please let us know how consistent this repro is?

thanks

**Comment by CiciLi1** [comment]
> @CiciLi1, @v-luzh When you verify the bugs can you please let us know how consistent this repro is?
> 
> thanks

This issue is not 100% repro, the frequency of repro of this issue is about 60%.

**Comment by v-luzh** [comment]
Hi @donnie-msft, we can still repro it on VS Main\33507.155 + NuGet Client Dev\6.6.0.42 as below. Please help to take a look, thanks. Repro rate is about 60%.
![image](https://user-images.githubusercontent.com/20632625/223612791-f6e0c588-66f2-429d-a573-a0e46c35b354.png)

**Comment by ghost** [comment]
This issue has been automatically marked as stale because we have not received a response in 14 days. It will be closed if no further activity occurs within another 14 days of this comment.

**Comment by donnie-msft** [comment]
@nkolev92 answer above to your question about repro rate. Trying to put back on Triage's radar.

**Comment by jeffkl** [comment]
Team Triage: At the very least we could add more exception information to the log so that we have an idea of what's going wrong.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectSystems/VsMSBuildProjectSystem.cs#L513

**Comment by dperez83** [comment]
I have this very same problem now with Package Manager Console Host 6.5.0.154. Very annoying that it cannot update the binding redirects and no real reason it written to the console. Please at least write on the console the real error behind the exception "Exception has been thrown by the target of an invocation.”.

**Comment by julealgon** [comment]
Started seeing this today as well with all of my old-style csproj with packages.config.

I've done various package updates recently (a couple months ago) and didn't run into this issue. I'm now using latest VS version 17.6.3 and have the problem.

I'm unsure exactly what update triggered this problem but our solution or project structure hasn't changed at all since when it was working.

EDIT: I think this might be related to another issue. If I run `add-bindingredirect` command on the Package Manager Console, I get this error:
> Loading this assembly would produce a different grant set from other instances.
- https://stackoverflow.com/questions/76049195/add-bindingredirect-loading-this-assembly-would-produce-a-different-grant-set

I have no idea what is causing the second issue as well, if that matters. People are reporting that downgrading VS solves it (in that SO post).

**Comment by donnie-msft** [comment]
Repro'd this myself today with a new packages.config project. I have Newtonsoft.Json 13.0.2 installed. 
What I see below concurs with what @julealgon saw. Seems that when trying to add binding redirects, some assembly load failure occurs. The project is .NET 4.8.1, so this might be expected due to the different TFM? 

/cc @jeffkl who often has quick insight on this sort of thing.

Thrown at: https://github.com/NuGet/NuGet.Client/blob/2bd89a3bc9089714b46536d01b71b7e7638176a0/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Runtime/RemoteAssembly.cs#L77

**typeof(T).Assembly.FullName** = `NuGet.PackageManagement.VisualStudio, Version=6.7.0.32767, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a`
**typeof(T).FullName** = `NuGet.PackageManagement.VisualStudio.RemoteAssembly`

`Message = "Loading this assembly would produce a different grant set from other instances. (Exception from HRESULT: 0x80131401)"`

path="<solution dir>\ConsoleApp13\packages\Newtonsoft.Json.13.0.2\lib\net45\Newtonsoft.Json.dll"
   ```
at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName)
   at NuGet.PackageManagement.VisualStudio.RemoteAssembly.CreateInstance[T](AppDomain domain) in C:\NuGet.Client\src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\Runtime\RemoteAssembly.cs:line 96
   at NuGet.PackageManagement.VisualStudio.RemoteAssembly.LoadAssembly(String path, AppDomain domain) in C:\NuGet.Client\src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\Runtime\RemoteAssembly.cs:line 77
   at NuGet.PackageManagement.VisualStudio.BindingRedirectResolver.<GetAssemblies>d__6.MoveNext() in C:\NuGet.Client\src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\Runtime\BindingRedirectResolver.cs:line 125
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.PackageManagement.VisualStudio.BindingRedirectResolver.GetBindingRedirects(IEnumerable`1 assemblies) in C:\NuGet.Client\src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\Runtime\BindingRedirectResolver.cs:line 70
   at NuGet.PackageManagement.VisualStudio.BindingRedirectResolver.GetBindingRedirects(IEnumerable`1 assemblyPaths, AppDomain domain) in C:\NuGet.Client\src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\Runtime\BindingRedirectResolver.cs:line 55
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__5.MoveNext() in C:\NuGet.Client\src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\Utility\RuntimeHelpers.cs:line 147
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__3.MoveNext() in C:\NuGet.Client\src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\Utility\RuntimeHelpers.cs:line 93
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__0.MoveNext() in C:\NuGet.Client\src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\Utility\RuntimeHelpers.cs:line 38
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.PackageManagement.VisualStudio.VsMSBuildProjectSystem.<>c__DisplayClass51_0.<<AddBindingRedirects>b__0>d.MoveNext() in C:\NuGet.Client\src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\ProjectSystems\VsMSBuildProjectSystem.cs:line 498

```

Code where thrown: 
https://github.com/NuGet/NuGet.Client/blob/2bd89a3bc9089714b46536d01b71b7e7638176a0/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectSystems/VsMSBuildProjectSystem.cs#L512

**Comment by nkolev92** [comment]
The framework shouldn't matter too much. 

Did you capture the name of the assembly that we're attempting to load in the app domain?

**Comment by donnie-msft** [comment]
Everything I captured is above. Not sure if it's the VS assembly or the Newtonsoft assembly.

**Comment by Trigger2991** [comment]
I'm having the same issue. I then tried to run `Get-Project –All | Add-BindingRedirect` from the package manager console and got the error 
```
Add-BindingRedirect : Loading this assembly would produce a different grant set from other instances. (Exception from HRESULT: 0x80131401)
```

I found [THIS answer on another thread for modifying the registry](https://github.com/DataDog/dd-trace-dotnet/issues/475#issuecomment-529124597). So I closed Visual Studio, updated the registry and ran `iisreset` and then when re-opening Visual Studio I no longer received the error when updating the same nuget package, and binding redirects were automatically updated.
I then reverted the registry change and did `iisreset` again due to the warning in the comment after the solution.

**Comment by v-luzh** [comment]
It also reproes on VS 17.14.30 [37202.16.d17.14] with implicit NuGet release-6.14.x-MSRC/6.14.3.1 when installing package 'Autofac.Wcf' in PMC as the screenshot below.

<img width="1429" height="352" alt="Image" src="https://github.com/user-attachments/assets/82ef0019-ab23-4532-be48-ab3bb8f232c6" />
