### ISSUE TITLE
MSB4066 "The attribute 'Version' in element <PackageReference> is unrecognized." error in NuGet CLI 6.4.0

### ISSUE THREAD

**Issue by splatteredbits** [NuGet/Home#12390]
### NuGet Product Used

NuGet.exe

### Product Version

nuget.exe 6.4.0

### Worked before?

6.3.1

### Impact

I'm unable to use this version

### Repro Steps & Context

1. Create a .csproj file with this content:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{A4366E0A-29F0-4F5E-B6CD-C35F022FB924}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>NUnit2PassingTest</RootNamespace>
    <AssemblyName>NUnit2PassingTest</AssemblyName>
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="nunit.framework, Version=2.6.4.14350, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77, processorArchitecture=MSIL">
      <HintPath>packages\NUnit.2.6.4\lib\nunit.framework.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="TestFixture.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>
```
2. Run `NuGet.exe restore PATH_TO_CSPROJ_FILE -SolutionDirectory PATH_TO_CSPROJ_DIRECTORY`
3. Note you'll see this error:
```
C:\Users\appveyor\AppData\Local\Temp\1\NuGetScratch\ztu053ia.0tn.nugetrestore.targets(199,25): error MSB4066: The attribute "Version" in element <PackageReference> is unrecognized. [C:\Users\appveyor\AppData\Local\Temp\1\NuGetScratch\unf55omt.uun.nugetinputs.targets]
```

### Verbose Logs

```shell
> .\NuGet.CommandLine.6.4.0\tools\NuGet.exe restore .\Test\Assemblies\NUnit2PassingTest\NUnit2
PassingTest.csproj -solutiondirectory .\Test\assemblies\NUnit2PassingTest -verbosity detailed
NuGet Version: 6.4.0.123
MSBuild P2P timeout [ms]: 120000
MSBuild auto-detection: using msbuild version '12.0.40629.0 built by: REL' from 'C:\Program Files (x86)\MSBuild\12.0\Bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
C:\Program Files (x86)\MSBuild\12.0\Bin\msbuild.exe "C:\Users\appveyor\AppData\Local\Temp\1\NuGetScratch\byoybwms.d1c.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\appveyor\AppData\
Local\Temp\1\NuGetScratch\muiuyf0f.qw2.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:DisableCheckingDuplicateNuGetItems="True" /p:RestoreTaskAssemblyFile="C:\projects\whiskey\NuGet.CommandLine.6.4.0\tools\NuGet.exe" /p:Res
toreSolutionDirectory="C:\projects\whiskey\Test\assemblies\NUnit2PassingTest\\" /p:SolutionDir="C:\projects\whiskey\Test\assemblies\NUnit2PassingTest\\" /p:RestoreBuildInParallel="False" /p:RestoreUseSkipNonexistentTargets="False"
C:\Users\appveyor\AppData\Local\Temp\1\NuGetScratch\muiuyf0f.qw2.nugetrestore.targets(199,25): error MSB4066: The attribute "Version" in element <PackageReference> is unrecognized. [C:\Users\appveyor\AppData\Local\Temp\1\NuGetScratch\byoybw
ms.d1c.nugetinputs.targets]

NuGet.CommandLine.ExitCodeException: Exception of type 'NuGet.CommandLine.ExitCodeException' was thrown.
   at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__6.MoveNext() in D:\a\_work\1\s\src\NuGet.Clients\NuGet.CommandLine\MsBuildUtility.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__68.MoveNext() in D:\a\_work\1\s\src\NuGet.Clients\NuGet.CommandLine\Commands\RestoreCommand.cs:line 683
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__63.MoveNext() in D:\a\_work\1\s\src\NuGet.Clients\NuGet.CommandLine\Commands\RestoreCommand.cs:line 549
```

**Comment by jeffkl** [comment]
@splatteredbits it seems like you're using MSBuild 12.0 which does not support setting metadata like `Version` as an attribute.  You'll need to use MSBuild 15.0 or above, or specify your metadata as a child element:

```xml
<PackageReference Include="SomePackage">
  <Version>1.0.0</Version>
</PackageReference>
```
