### ISSUE TITLE
SSL error on dotnet restore

### ISSUE THREAD

**Issue by smadurange** [NuGet/Home#12474]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet sdk 7.0.103, 3.1.426, 3.0.103

### Worked before?

Yes, but can't remember the version

### Impact

I'm unable to use this version

### Repro Steps & Context

I'm using vscode (Microsoft build) as my IDE on Arch Linux. When I tried restoring the projects using the IDE or by running `dotnet restore`, the restore is failing. This only seems to be happening with plugin 'CredentialProvider.Microsoft'.

### Verbose Logs

```shell
Determining projects to restore...
Terminating plugin 'CredentialProvider.Microsoft' due to an unrecoverable fault:  NuGet.Protocol.Plugins.ProtocolException: A plugin protocol exception occurred.
 ---> NuGet.Protocol.Plugins.ProtocolException: The SSL connection could not be established, see inner exception.
   at NuGet.Protocol.Plugins.OutboundRequestContext`1.HandleFault(Message fault)
   at NuGet.Protocol.Plugins.MessageDispatcher.OnMessageReceived(Object sender, MessageEventArgs e)
   at NuGet.Protocol.Plugins.Connection.OnMessageReceived(Object sender, MessageEventArgs e)
   at NuGet.Protocol.Plugins.Receiver.FireMessageReceivedEvent(Message message)
   at NuGet.Protocol.Plugins.StandardOutputReceiver.OnLineRead(Object sender, LineReadEventArgs e)
   --- End of inner exception stack trace ---
```

**Comment by smadurange** [comment]
This seems to be an issue with the credentials provider plugin. I will move this issue there.
