### ISSUE TITLE
VS crashed when installing a package with “package config” format in C# Class Library (.NET Framework) project 

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#12481]
### NuGet Product Used

Visual Studio Package Management UI, Visual Studio Package Manager Console

### Product Version

NuGet Client Dev\6.6.0.44

### Impact

It's more difficult to complete my work

#### Repro Steps:    

1. Create a C# Class Library (.NET Framework) project in VS.  

2. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open PM UI.  

3. Click settings button (top-right of right panel), check "Allow format selection on first package install" in "General" tab and click “OK” button.  

4. Go to "Browse" tab, select a package (for example "Newtonsoft.Json") and click install button. 

5. Check "packages.config" in "Choose NuGet Package Manager Format", click “OK” button and click “OK” button in the "Preview Changes" window. 

#### Expected:    

The package should be installed successfully. 

#### Actual:    

VS crashed when installing a package with “package config” format as below screenshot:  
![MicrosoftTeams-image](https://user-images.githubusercontent.com/84695155/224635331-5e98a8aa-c3e0-48bb-9088-b978387a855a.png)
#### Notes: 

1.It doesn’t repro on VS Main\33508.150 + NuGet Client Dev\6.6.0.43 

2.It still reproes when using PMC install package. 

3.The repro rate is 100%. 

4.Added dump file to this path(\\\mlangfs1\public\v-cicili\Bug0313).

### Verbose Logs:
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at VSLangProj157.References3.AddFiles(System.Array, System.Array ByRef)
   at NuGet.PackageManagement.VisualStudio.VsMSBuildProjectSystem+<>c__DisplayClass76_0+<<AddReferenceAsync>b__0>d.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory+SingleExecuteProtector.TryExecute()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by erdembayar** [comment]
@nkolev92 
I can repro this, I feel it's project system regression. 
![image](https://user-images.githubusercontent.com/8766776/224879576-34fe97d9-77f9-42c0-a7b4-3c6810d01bbe.png)
![image](https://user-images.githubusercontent.com/8766776/224880096-08f6ec7c-4b96-491b-8552-57775959b9d0.png)

**Comment by erdembayar** [comment]
@drewnoakes
Does this ring any bell?

**Comment by erdembayar** [comment]
@drewnoakes @nkolev92 @aortiz-msft 
I can confirm it's the regression, it works with VS 17.4, but not with latest int Preview 17.6.
![image](https://user-images.githubusercontent.com/8766776/225098355-51cb0f15-8c4d-4d94-9fd9-7c84b3a492f0.png)

**Comment by nkolev92** [comment]
The exception is the old project system, so @drewnoakes probably isn't the person for this.

Let's create an internal issue and mark this as `External` of a different product. 

We might want to put a high priority on the internal issue as a potential regression.

**Comment by erdembayar** [comment]
Created internal issue. https://developercommunity.visualstudio.com/t/VS-crashed-when-installing-a-package-wit/10309708

**Comment by drewnoakes** [comment]
I'll ping someone on the platform side here too as I believe there were changes to reference manager recently, though I don't know the details. I heard about them in the context of CPS, but they may also impact legacy projects.

**Comment by ladipro** [comment]
This was a crash in CSProj that existed in VS Main between builds 33509.73 and 33512.67 (inclusive). It didn't make it into any publicly available build.
