### ISSUE TITLE
nuget.exe restore (v3.1) fails with "Could not find a part of the path"

### ISSUE THREAD

**Issue by alecor191** [NuGet/Home#1251]
Version used: http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe
### Repro steps
- In my case I have a solution with both ASP.NET 5 (beta 6) projects and "regular" .csproj class library projects.
- run "nuget.exe restore (path_to_solution)"
### Result

NuGet shows an error in the console:
_Could not find a part of the path 'C:\test\myproject\myproject.xproj\project.json'._

As you can see the last directory in the printed path doesn't exist, as it's the name of the .xproj file. The path where project.json acutally exists is the following:

C:\test\myproject\project.json

and not

C:\test\myproject\**myproject.xproj**\project.json

Is there anything I'm missing or is this an issue in the latest version of nuget.exe?
### Details

Here the exception stack printed when using "-verbosity detailed":

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\test\myproject\myproject.xproj\project.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at NuGet.CommandLine.RestoreCommand.<PerformNuGetV3RestoreAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__17.MoveNext()

**Comment by emgarten** [comment]
nuget.exe doesn't support project.json for DNX currently.

https://github.com/NuGet/Home/issues/1227

**Comment by yishaigalatzer** [comment]
Thanks for the report, I'm going to be closing as a duplicate. Feel free to open if you feel otherwise.
