### ISSUE TITLE
6.6.0 - NuGetProtocolVersionNotSupportedException (nugetclient over azuredevops)

### ISSUE THREAD

**Issue by Marco4Git** [NuGet/Home#12595]
### NuGet Product Used

NuGet.exe

### Product Version

 6.6.0.61 / 6.6.0-preview.3+0fa557836fa35aee7d60776ef0c88176dbcd22ac.0fa557836fa35aee7d60776ef0c88176dbcd22ac

### Worked before?

6.5.0

### Impact

I'm unable to use this version

### Repro Steps & Context

Hi
After upgrading nuget.client to version 6.6.x the push command returns the exception 

**VstsNuGetPush.NuGetProtocolVersionNotSupportedException: The supplied URL appears to be a NuGet V2 URL. This command only supports the NuGet V3 protocol.**

Restoring to the previous version (6.5.x) the command works.
Is it a wrapper problem (VstsNuGetPush.exe)?

### Verbose Logs

```shell
2023-05-18T08:39:55.9878808Z ##[section]Starting: nuget push
2023-05-18T08:39:56.0125701Z ==============================================================================
2023-05-18T08:39:56.0126002Z Task         : NuGet
2023-05-18T08:39:56.0126153Z Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Azure Artifacts and MyGet. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
2023-05-18T08:39:56.0126601Z Version      : 2.220.2
2023-05-18T08:39:56.0126709Z Author       : Microsoft Corporation
2023-05-18T08:39:56.0126869Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/nuget
2023-05-18T08:39:56.0127050Z ==============================================================================
2023-05-18T08:39:57.6175788Z [command]C:\Windows\system32\chcp.com 65001
2023-05-18T08:39:57.6444477Z Active code page: 65001
2023-05-18T08:39:58.9734932Z Detected NuGet version 6.6.0.61 / 6.6.0-preview.3+0fa557836fa35aee7d60776ef0c88176dbcd22ac.0fa557836fa35aee7d60776ef0c88176dbcd22ac
2023-05-18T08:39:59.3503036Z [command]D:\a\_tasks\NuGetCommand_333b11bd-d341-40d9-afcf-b32d5ce6f23b\2.220.2\VstsNuGetPush\0.19.0\tools\VstsNuGetPush.exe D:\a\1\s\Source\mypack\bin\Release\mypack.0.0.2.37676.nupkg -Source https://myorg.pkgs.visualstudio.com/b80d423f-059b-4782-9a75-77a18e0e3f40/_packaging/bdf05d42-c9c3-7e40-bb9f-ba227d12dc45/nuget/v2 -AccessToken *** -NonInteractive -Verbosity Detailed
2023-05-18T08:40:03.1267253Z Error:
2023-05-18T08:40:03.1267774Z VstsNuGetPush.NuGetProtocolVersionNotSupportedException: The supplied URL appears to be a NuGet V2 URL. This command only supports the NuGet V3 protocol.
2023-05-18T08:40:03.1268319Z    at VstsNuGetPush.NuGetServiceIndexHttpClient.<>c__DisplayClass2_0.<<GetServiceIndexAsync>b__0>d.MoveNext()
2023-05-18T08:40:03.1269177Z --- End of stack trace from previous location where exception was thrown ---
2023-05-18T08:40:03.1269605Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2023-05-18T08:40:03.1270052Z    at VstsNuGetPush.RetryHelper.<RetryOnExceptionHelperAsync>d__0`1.MoveNext()
2023-05-18T08:40:03.1270688Z --- End of stack trace from previous location where exception was thrown ---
2023-05-18T08:40:03.1271092Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2023-05-18T08:40:03.1271554Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2023-05-18T08:40:03.1272065Z    at VstsNuGetPush.NuGetServiceIndexHttpClient.<GetServiceIndexAsync>d__2.MoveNext()
2023-05-18T08:40:03.1272727Z --- End of stack trace from previous location where exception was thrown ---
2023-05-18T08:40:03.1273143Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2023-05-18T08:40:03.1273628Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2023-05-18T08:40:03.1274148Z    at VstsNuGetPush.HttpServiceIndexProvider.<Get>b__4_0(VssClientCredentials credentials)
2023-05-18T08:40:03.1275067Z    at VstsNuGetPush.CredentialSelector.TrySelectCredential[TResult](Func`2 func, IVssCredentialStorage vssClientCredentialStorage, CredentialPromptType promptType, TResult& result)
2023-05-18T08:40:03.1275670Z    at VstsNuGetPush.CredentialSelector.Select[TResult](Func`2 func)
2023-05-18T08:40:03.1276100Z    at VstsNuGetPush.Patterns.Helpers.FactoryAdaptorChain`2.Get()
2023-05-18T08:40:03.1276465Z    at System.Lazy`1.CreateValue()
2023-05-18T08:40:03.1276769Z    at System.Lazy`1.LazyInitValue()
2023-05-18T08:40:03.1277323Z    at VstsNuGetPush.VstsNuGetPushCommand.MainCore(ILogger logger)
2023-05-18T08:40:03.1277746Z    at VstsNuGetPush.VstsNuGetPushCommand.Main()
2023-05-18T08:40:03.1278093Z Trying to authenticate with auth token.
2023-05-18T08:40:03.1278652Z Authentication and request took 00:00:03.2569899
2023-05-18T08:40:03.1907716Z ##[error]Error: An unexpected error occurred while trying to push the package with VstsNuGetPush.exe. Exit code(1) and error(Error:
VstsNuGetPush.NuGetProtocolVersionNotSupportedException: The supplied URL appears to be a NuGet V2 URL. This command only supports the NuGet V3 protocol.
   at VstsNuGetPush.NuGetServiceIndexHttpClient.<>c__DisplayClass2_0.<<GetServiceIndexAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at VstsNuGetPush.RetryHelper.<RetryOnExceptionHelperAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VstsNuGetPush.NuGetServiceIndexHttpClient.<GetServiceIndexAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VstsNuGetPush.HttpServiceIndexProvider.<Get>b__4_0(VssClientCredentials credentials)
   at VstsNuGetPush.CredentialSelector.TrySelectCredential[TResult](Func`2 func, IVssCredentialStorage vssClientCredentialStorage, CredentialPromptType promptType, TResult& result)
   at VstsNuGetPush.CredentialSelector.Select[TResult](Func`2 func)
   at VstsNuGetPush.Patterns.Helpers.FactoryAdaptorChain`2.Get()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at VstsNuGetPush.VstsNuGetPushCommand.MainCore(ILogger logger)
   at VstsNuGetPush.VstsNuGetPushCommand.Main())
2023-05-18T08:40:03.1931604Z ##[error]Packages failed to publish
2023-05-18T08:40:03.1934130Z ##[section]Finishing: nuget push
```

**Comment by Marco4Git** [comment]
From yaml (azure devops)
    - task: NuGetToolInstaller@1
     ....
     - task: NuGetCommand@2
      displayName: 'nuget push'
      inputs:
        command: 'push'
        feedsToUse: 'select'
        packagesToPush: '$(Build.SourcesDirectory)/**/*.nupkg;!$(Build.SourcesDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'b80d423f-059b-4782-9a75-77a18e0e3f40/310c4bf2-d5a7-41e1-89aa-1894b2680eb4'
        versioningScheme: 'off'
        allowPackageConflicts: true

**Comment by ransagy** [comment]
We've come across this as well today, though in classic UI based pipelines. I imagine the task behind it is similar/the behavior is in the background NuGet binaries themselves.

**Comment by williamoconnorme** [comment]
@ransagy It would be the same with classic pipelines so long as you are also using the NugetCommand@v2 task.

We are also experiencing this issue with nuget 6.6.0 but have mitigated like OP by reverting to 6.5.0

**Comment by heldersousa-planetpayment** [comment]
I have the same issue with version 6.6.0

**Comment by mattgwagner** [comment]
This hit us yesterday -- builds worked at 4:05pm and failed with the exact same code at 4:42pm (EST).

**Comment by TCN-CW** [comment]
Hi, this is an issue for us as well. We have reverted to v6.5.0 until 6.6.0 is blessed

**Comment by donnie-msft** [comment]
Hello, I deployed `6.6.0.61` by mistake which has the `preview.3` release label. I've now deployed `6.6.0.62` which is labelled as `6.6.0`. Please let me know if the error mentioned is persisting after obtaining `nuget.exe` 6.6.0 again from nuget.org. Thank you!

**Comment by heldersousa-planetpayment** [comment]
@donnie-msft it works again. thanks.

**Comment by donnie-msft** [comment]
Closing since there's feedback that this is resolved. Please do let us know if it still occurs for anyone (be sure to re-download from nuget.org). 
Have a nice day!
