### ISSUE TITLE
Accessing request body in HttpSource throws NullReferenceException 

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#12605]
### NuGet Product Used

NuGet SDK

### Product Version

6.6.0

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Accessing `HttpResponseMessage.RequestMessage.Content.SerializeToStream()` in the delegate passed to `HttpSource.ProcessResponseAsync` throws a `NullReferenceException`. This makes it harder to provide diagnostic logging on the HTTP session (i.e. logging request and response). A workaround I found is rerunning the `HttpRequestMessage` factory to get another copy of the request. This feels wrong since this pattern is quite possible with vanilla `HttpClient` as shown in the sample below. Also, an NRE feels wrong :)

Here is a full repro:
```csharp
using NuGet.Common;
using NuGet.Protocol;
using NuGet.Protocol.Core.Types;

// HttpClient -- works
using var httpClient = new HttpClient();
var response = await httpClient.SendAsync(new HttpRequestMessage(HttpMethod.Delete, "https://www.nuget.org/api/v2/package/Knapcode.TorSharp/2.14.0")
{
    Content = new StringContent("some content"),
});
Console.WriteLine("HttpClient: " + await response.RequestMessage!.Content!.ReadAsStringAsync());

// NuGet client SDK -- throws NRE
using var cache = new SourceCacheContext();
var repository = Repository.Factory.GetCoreV3("https://api.nuget.org/v3/index.json");
var resource = await repository.GetResourceAsync<HttpSourceResource>();

var requestBody = await resource.HttpSource.ProcessResponseAsync(
    new HttpSourceRequest(() => new HttpRequestMessage(HttpMethod.Delete, "https://www.nuget.org/api/v2/package/Knapcode.TorSharp/2.14.0")
    {
        Content = new StringContent("some content"),
    }),
    async response =>
    {
        return await response.RequestMessage!.Content!.ReadAsStringAsync();
    },
    NullLogger.Instance,
    CancellationToken.None);

Console.WriteLine("NuGet client SDK: " + requestBody);
```

### Verbose Logs

```shell
Output is here:

HttpClient: some content
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Protocol.HttpRequestMessageExtensions.HttpContentWrapper.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsync(Int64 maxBufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.ReadAsStringAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.ReadAsStringAsync()
   at Program.<>c.<<<Main>$>b__0_1>d.MoveNext() in C:\Users\jver\Desktop\ConsoleApp2\ConsoleApp2\Program.cs:line 25
--- End of stack trace from previous location ---
   at NuGet.Protocol.HttpSource.ProcessResponseAsync[T](HttpSourceRequest request, Func`2 processAsync, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   at Program.<Main>$(String[] args) in C:\Users\jver\Desktop\ConsoleApp2\ConsoleApp2\Program.cs:line 18
   at Program.<Main>(String[] args)
```
```

**Comment by jebriede** [comment]
I was able to repro. It looks like the NRE is being thrown here https://github.com/NuGet/NuGet.Client/blob/a05cda05be4d51d155eaf711e776271e187eae47/src/NuGet.Core/NuGet.Protocol/HttpSource/HttpRequestMessageExtensions.cs#LL69C17-L69C17 when the _httpContent is null. This `HttpContentWrapper` seems to set the _httpContent in the constructor and allows a null value, but then assumes it's not null in the code I linked and in other places in this class.
