### ISSUE TITLE
NuGet does not respect the system certificate chain

### ISSUE THREAD

**Issue by LucHeart** [NuGet/Home#12613]
### NuGet Product Used

dotnet.exe

### Product Version

.NET 7.0.302 | NuGet 6.6.0.61

### Impact

Other

### Repro Steps & Context

I am trying to build a ASP.NET Core 7 application in a docker multistep build inside a bitbucket runner (Bitbuckets CI system).
However it fails when trying to contact our for now legacy teamcity nuget feed to grab a nuget package off it. It uses our self signed company wide root ca. So I though i would just include our ca in the build container, well it worked for curl, but nuget still seems to just ignore it... Can I somehow specify the the cert store to be used? Or why does it ignore the system one in the first place. Same happens with the "7.0" tag of the sdk. Alpine or not does not seem to change anything.

Repro:
1. Have a nuget feed with a self signed HTTPS certificate
2. Use one of those packages in a project & configure nuget.config to use the nuget feed
3. Try to build / nuget restore the project inside a docker multistep build

Dockerfile, this is all that the CI executes after checking out the git repo.
```
FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build

WORKDIR /src
COPY . .
COPY ["agenda-root-ca.crt", "/usr/local/share/ca-certificates/"] # copying our self signed ca
RUN update-ca-certificates # update the system certs

# this FAILS if the above two commands would not setup the certificate!!!
RUN curl https://teamcity-nuget.agenda.de/guestAuth/app/nuget/feed/_Root/default/v3/index.json # debug only

WORKDIR "/src/BrainLogApi"

RUN dotnet restore --verbosity d # debug only, publish already does it
RUN dotnet publish "BrainLogApi.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Agenda.BrainLogApi.dll"]
```

I also saw that package add prints the inner exception so here it is. This is from a container I manually created from the base build image I also use in the docker build, to simulate the whole thing and possibly find a solution. 

```
/brain-log-api/BrainLogApi # dotnet add package Agenda.Common
  Determining projects to restore...
  Writing /tmp/tmpDnhfdC.tmp
info : X.509 certificate chain validation will use the fallback certificate bundle at '/usr/share/dotnet/sdk/7.0.302/trustedroots/codesignctl.pem'.
info : X.509 certificate chain validation will use the fallback certificate bundle at '/usr/share/dotnet/sdk/7.0.302/trustedroots/timestampctl.pem'.
info : Adding PackageReference for package 'Agenda.Common' into project '/brain-log-api/BrainLogApi/BrainLogApi.csproj'.
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/agenda.common/index.json
info :   NotFound https://api.nuget.org/v3/registration5-gz-semver2/agenda.common/index.json 785ms
error: Unable to load the service index for source https://teamcity-nuget/guestAuth/app/nuget/feed/_Root/default/v3/index.json.
error:   The SSL connection could not be established, see inner exception.
error:   The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot


Usage: NuGet.CommandLine.XPlat.dll package add [options]

Options:
  -h|--help               Show help information
  --force-english-output  Forces the application to run using an invariant, English-based culture.
  --package               Id of the package to be added.
  --version               Version of the package to be added.
  -d|--dg-file            Path to the dependency graph file to be used to restore preview and compatibility check.
  -p|--project            Path to the project file.
  -f|--framework          Frameworks for which the package reference should be added.
  -n|--no-restore         Do not perform restore preview and compatibility check. The added package reference will be unconditional.
  -s|--source             Specifies NuGet package sources to use during the restore.
  --package-directory     Directory to restore packages in.
  --interactive           Allow the command to block and require manual action for operations like authentication.
  --prerelease            Allows prerelease packages to be installed.
```

### Verbose Logs

```shell
Too large, http://pastebin.com/yQa5Y4dZ
```

**Comment by zivkan** [comment]
@zLucPlayZ if you use a test program that uses HTTP client to request the URL, but does not need any nuget packages to build, does the test program run successfully in docker?

```csharp
var response = await new HttpClient().GetAsync("https://teamcity-nuget.agenda.de/guestAuth/app/nuget/feed/_Root/default/v3/index.json");
Console.WriteLine("Response code: " + respose.StatusCode);
```

**Comment by LucHeart** [comment]
A http client in general seems to ignore my system certificates. 

```
root@11228b42ea3e:/app/NugetTests/bin/Debug/net7.0# dotnet NugetTests.dll
Unhandled exception. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Program.<Main>$(String[] args) in /app/NugetTests/Program.cs:line 1
   at Program.<Main>(String[] args)
Aborted (core dumped)
```

strange since I installed the certificate in a way, where it does indeed work for e.g. CURL
I guess this is more of an issue with dotnet it self than nuget then.

**Comment by jeffkl** [comment]
Closing this issue for now, please let us know if you're able to determine its a problem with NuGet.
