### ISSUE TITLE
Nuget.exe - exception when finding dependencies during pack

### ISSUE THREAD

**Issue by ALiwoto** [NuGet/Home#12617]
### NuGet Product Used

NuGet.exe

### Product Version

NuGet Version: 6.5.0.154

### Worked before?

According to issue #5406, [this was fixed](https://github.com/NuGet/Home/issues/5406#issuecomment-348049367) in v4.4.1; but the issue is still there in 6.5.0.154

### Impact

I'm unable to use this version

### Repro Steps & Context

> Note: Exact same thing is happening as #5406

This is the command I used:
```cmd
C:\Util\Nuget\nuget.exe pack C:\TFSAgent\_work\83\s\Company.Controls.Win.csproj -OutputDirectory C:\TFSAgent\_work\83\a -Properties "Configuration=debug" -IncludeReferencedProjects -Verbosity Detailed -MSBuildPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin" -ConfigFile "C:\Users\TFSAdmin\AppData\Roaming\NuGet\NuGet.Config"
```

Inside of NuGet.Config file, we have our feed saved.
There is a `packages.config` file which lists dependencies (and `nuget restore` command works perfectly).
Here is a small sample of the file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Spire.Pdf" version="6.3.10" targetFramework="net40" />
  <!-- and many other packages here -->
</packages>
```

The error message is just too vague, all it says is `The given key was not present in the dictionary.`
After spending hours and trying to narrow down the issue, I found out removing this line of `packages.config` will solve the error:
```xml
<package id="Spire.Pdf" version="6.3.10" targetFramework="net40" />
```

I checked our nuget feed (which is inside of Azure DevOps 2022), and found out the package id is `Spire.PDF`.

`nuget restore` command is case insensitive, but it looks like `nuget pack` command is case sensitive.

### Verbose Logs

```shell
NuGet Version: 6.5.0.154
Attempting to build package from 'Company.Controls.Win.csproj'.
Using Msbuild from 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin'.
Packing files from 'C:\TFSAgent\_work\83\s\Output'

Found packages.config. Using packages listed as dependencies
The given key was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NuGet.CommandLine.ProjectFactory.ProcessDependencies(PackageBuilder builder)
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by jeffkl** [comment]
It looks like here we need to specify that the dictionary is case insensitive: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/ProjectFactory.cs#L929

**Comment by nkolev92** [comment]
Team Triage: We don't think we'll be able to get this soon, but we'd happily consider a contribution as per the comment above.
