### ISSUE TITLE
OutputPath contains double path separator leading to NU5019 in nuget pack

### ISSUE THREAD

**Issue by pharring** [NuGet/Home#12628]
### NuGet Product Used

dotnet.exe

### Product Version

.NET 8 Preview 4 SDK

### Worked before?

.NET 7 SDK

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Originally reported at https://github.com/dotnet/sdk/issues/32971

### Describe the bug
.NET 8 Preview 4 SDK
Requires: A .NET SDK project with multi-targeting (TargetFrameworks plural) and a custom .nuspec
The OutputPath property ends up with a double slash (path separator) because PlatformName is undefined.
Nuget pack doesn't like the double-slash, leading to a NU5019 (file not found) error.

### To Reproduce
Here's a gist:
https://gist.github.com/pharring/aef107238843a1c6c7ea9f0be87795d6

Copy the three files to a local directory and build it with `dotnet build`
Output:
```
Build FAILED.

C:\Program Files\dotnet\sdk\8.0.100-preview.4.23260.5\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): error NU5019: File not found: 'b
in\\Debug\foo.txt'. [C:\throwaway\foo2\foo.csproj]
```

### Exceptions (if any)
Note that this repros only with multitargeting. If you change `TargetFrameworks` to `TargetFramework` (singular), then it works.
The problem seems to be that `PlatformName` is not set in the multitargeting case (it should default to `AnyCpu`) so `OutputPath` gets initialized with a double path separator.

### Further technical details
- Output of `dotnet --info`:
```
.NET SDK:
 Version:   8.0.100-preview.4.23260.5
 Commit:    2268e7b15c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.4.23260.5\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.4.23259.5
  Architecture: x64
  Commit:       84a3d0e37e

.NET SDKs installed:
  7.0.400-preview.23274.1 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.4.23260.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.4.23260.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.4.23259.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.4.23260.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```
 
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2022 17.7 Preview 2

### Verbose Logs

```shell
The complete log is too long to fit here. This is the relevant piece, I think:


1:11>Target "_GetPackageFiles" in file "C:\Program Files\dotnet\sdk\8.0.100-preview.4.23260.5\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets" from project "C:\throwaway\foo\foo.csproj" (target "GenerateNuspec" depends on it):
  1:11>Done building target "_GetPackageFiles" in project "foo.csproj".
  1:11>Target "SetNuspecProperties" in project "C:\throwaway\foo\foo.csproj" (target "GenerateNuspec" depends on it):
       Task "Message"
         Platform = AnyCPU
       Done executing task "Message".
       Task "Message"
         PlatformName = 
       Done executing task "Message".
       Task "Message"
         OutputPath = bin\\Release\
       Done executing task "Message".
  1:11>Done building target "SetNuspecProperties" in project "foo.csproj".
  1:11>Target "_GetAbsoluteOutputPathsForPack" in file "C:\Program Files\dotnet\sdk\8.0.100-preview.4.23260.5\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets" from project "C:\throwaway\foo\foo.csproj" (target "_GetOutputItemsFromPack" depends on it):
       Task "ConvertToAbsolutePath"
       Done executing task "ConvertToAbsolutePath".
       Task "ConvertToAbsolutePath"
       Done executing task "ConvertToAbsolutePath".
       Task "ConvertToAbsolutePath"
       Done executing task "ConvertToAbsolutePath".
  1:11>Done building target "_GetAbsoluteOutputPathsForPack" in project "foo.csproj".
  1:11>Target "_GetOutputItemsFromPack" in file "C:\Program Files\dotnet\sdk\8.0.100-preview.4.23260.5\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets" from project "C:\throwaway\foo\foo.csproj" (target "_CalculateInputsOutputsForPack" depends on it):
       Assembly loaded during TaskRun: NuGet.Build.Tasks.Pack, Version=6.7.0.20, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (location: C:\Program Files\dotnet\sdk\8.0.100-preview.4.23260.5\Sdks\NuGet.Build.Tasks.Pack\CoreCLR\NuGet.Build.Tasks.Pack.dll, MVID: 7989af01-cc0c-4237-82b7-99060fb0a512, AppDomain: [Default])
       Using "GetPackOutputItemsTask" task from assembly "C:\Program Files\dotnet\sdk\8.0.100-preview.4.23260.5\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\..\CoreCLR\NuGet.Build.Tasks.Pack.dll".
       Task "GetPackOutputItemsTask"
       Done executing task "GetPackOutputItemsTask".
  1:11>Done building target "_GetOutputItemsFromPack" in project "foo.csproj".
  1:11>Target "_CalculateInputsOutputsForPack" in file "C:\Program Files\dotnet\sdk\8.0.100-preview.4.23260.5\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets" from project "C:\throwaway\foo\foo.csproj" (target "GenerateNuspec" depends on it):
  1:11>Done building target "_CalculateInputsOutputsForPack" in project "foo.csproj".
       Target "_GetProjectReferenceVersions" skipped, due to false condition; ('$(NuspecFile)' == '') was evaluated as ('foo.nuspec' == '').
       Target "_InitializeNuspecRepositoryInformationProperties" skipped, due to false condition; ('$(SourceControlInformationFeatureSupported)' == 'true') was evaluated as ('' == 'true').
  1:11>Target "GenerateNuspec" in file "C:\Program Files\dotnet\sdk\8.0.100-preview.4.23260.5\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets" from project "C:\throwaway\foo\foo.csproj" (target "Pack" depends on it):
       Building target "GenerateNuspec" completely.
       Output file "C:\throwaway\foo\bin\Release\foo.1.0.0.nupkg" does not exist.
       Task "ConvertToAbsolutePath"
       Done executing task "ConvertToAbsolutePath".
       Using "PackTask" task from assembly "C:\Program Files\dotnet\sdk\8.0.100-preview.4.23260.5\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\..\CoreCLR\NuGet.Build.Tasks.Pack.dll".
       Task "PackTask"
         Assembly loaded during TaskRun (NuGet.Build.Tasks.Pack.PackTask): System.Linq.Parallel, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0-preview.4.23259.5\System.Linq.Parallel.dll, MVID: eb5dd35b-7504-47fe-a24a-f1e015205dd7, AppDomain: [Default])
  1:11>C:\Program Files\dotnet\sdk\8.0.100-preview.4.23260.5\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): error NU5019: File not found: 'bin\\Release\netstandard2.0\foo.txt'. [C:\throwaway\foo\foo.csproj]
         Assembly loaded during TaskRun (NuGet.Build.Tasks.Pack.PackTask): System.Diagnostics.StackTrace, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0-preview.4.23259.5\System.Diagnostics.StackTrace.dll, MVID: b61d4061-c3a1-4f42-bf39-6feedf83f3f4, AppDomain: [Default])
         NuGet.Packaging.Core.PackagingException: File not found: 'bin\\Release\netstandard2.0\foo.txt'.
            at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude)
            at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files)
            at NuGet.Packaging.PackageBuilder..ctor(String path, String basePath, Func`2 propertyProvider, Boolean includeEmptyDirectories, Boolean deterministic)
            at NuGet.Commands.PackCommandRunner.CreatePackageBuilderFromNuspec(String path)
            at NuGet.Commands.PackCommandRunner.BuildFromNuspec(String path)
            at NuGet.Build.Tasks.Pack.PackTask.Execute()
       Done executing task "PackTask" -- FAILED.
  1:11>Done building target "GenerateNuspec" in project "foo.csproj" -- FAILED.
  1:11>Done Building Project "C:\throwaway\foo\foo.csproj" (pack target(s)) -- FAILED.
```

**Comment by pharring** [comment]
This is a regression from the .NET 7 SDK where the build succeeded.
I believe it's because of the modifications in and around Microsoft.NET.DefaultOutputPaths.targets when $(UseArtifactsOutput) is not true.

**Comment by jeffkl** [comment]
This appears to happen for any path that contains double directory separators and the regression is going to be in the SDK including them when it didn't do that previously.

Relevant code is here where NuGet could replace `\\` with `\` possibly?

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs#L1108

Our code uses regex matching and instead could possibly use file system matching instead.

A workaround is to fix up the paths before Pack is called.

**Comment by pharring** [comment]
I re-opened the original issue in the donet/sdk repo.

**Comment by pharring** [comment]
@jeffkl I was going to close this since the dotnet/sdk folks have a fix. However, you indicated above that you might want to handle double-slashes in PackageBuilder. I'll let you decide whether to keep this active.

**Comment by nkolev92** [comment]
https://github.com/NuGet/Home/issues/13909 has good details for the root cause of the issue.
