### ISSUE TITLE
Allow the loading of packages from a repository which contains a corrupted package

### ISSUE THREAD

**Issue by quailstorm** [NuGet/Home#12925]
### NuGet Product(s) Affected

NuGet.exe, NuGet SDK

### Current Behavior

In case a local NuGet repository folder contains a corrupted NuGet package, NuGet.Protocol throws an unhandled exception showing the error message and naming the faulty package. This makes the repository unusable, nothing will load from it until all of the corrupted packages are cleared.
See the error log. To reproduce, just delete some bytes in an existing nupkg file, or delete the last few hundred bytes of it. The real life case is an interrupted download or network copy.
[nuget_exception.txt](https://github.com/NuGet/Home/files/12832301/nuget_exception.txt)

### Desired Behavior

For my use case, it would be better if the faulty packages would be omitted from the resulting list and only added to the log. The repository would remain usable and the user could remove faulty packages all at once, instead of getting the error package by package.
Without adding the logging, the fix is very simple:
_NuGet.Core\NuGet.Protocol\Utility\LocalFolderUtility.cs_
**GetPackagesFromNupkgs** function
`return files.Select(file => GetPackageFromNupkg(file)).Where(packageInfo => packageInfo != null);`
The Where statement is new.

**GetPackageFromNupkg** function
Add a new catch statement:
`catch (InvalidDataException) {return null; }`

This way the content of the local repository is properly enumerated, the corrupted package is ignored.

### Additional Context

Adding the logging would make the current functions a little bit messy. Is it acceptable to expand the chain of calls with a logger parameter? Is it worth making a PR, or would this behavior change be refused immediately by the NuGet team?
I need this change in a proprietary desktop application which uses the NuGet Client SDK as a C# library. I cannot workaround this behavior by externally wrapping and processing the NuGet output. Having a forked NuGet is not allowed, it has to be in one of the future official releases.

### Error log of current behavior

```
C:\Users\User\.nuget\packages\nuget.commandline\6.7.0\tools>nuget search -Source c:\invalidTest -PreRelease -Verbosity detailed
NuGet Version: 6.7.0.127
'c:\invalidTest\ArchitectDemo.1.0.0-pre20230914122119.nupkg' is not a valid nupkg file. Error: 'Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.'.
  Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.
NuGet.Protocol.Core.Types.FatalProtocolException: 'c:\invalidTest\ArchitectDemo.1.0.0-pre20230914122119.nupkg' is not a valid nupkg file. Error: 'Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.'. ---> System.IO.InvalidDataException: Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.
   at System.IO.Compression.ZipArchive.ReadCentralDirectory()
   at System.IO.Compression.ZipArchive.get_Entries()
   at NuGet.Packaging.ZipArchiveExtensions.GetFiles(ZipArchive zipArchive) in D:\a\_work\1\s\src\NuGet.Core\NuGet.Packaging\PackageExtraction\ZipArchiveExtensions.cs:line 33
   at NuGet.Packaging.PackageReaderBase.GetNuspecFile() in D:\a\_work\1\s\src\NuGet.Core\NuGet.Packaging\PackageReaderBase.cs:line 104
   at NuGet.Packaging.PackageReaderBase.GetNuspec() in D:\a\_work\1\s\src\NuGet.Core\NuGet.Packaging\PackageReaderBase.cs:line 99
   at NuGet.Packaging.PackageReaderBase.get_NuspecReader() in D:\a\_work\1\s\src\NuGet.Core\NuGet.Packaging\PackageReaderBase.cs:line 118
   at NuGet.Protocol.LocalFolderUtility.GetPackageFromNupkg(FileInfo nupkgFile) in D:\a\_work\1\s\src\NuGet.Core\NuGet.Protocol\Utility\LocalFolderUtility.cs:line 1222
   --- End of inner exception stack trace ---
   at NuGet.Protocol.LocalFolderUtility.GetPackageFromNupkg(FileInfo nupkgFile) in D:\a\_work\1\s\src\NuGet.Core\NuGet.Protocol\Utility\LocalFolderUtility.cs:line 1239
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at NuGet.Protocol.LocalFolderUtility.<GetDistinctPackages>d__39.MoveNext() in D:\a\_work\1\s\src\NuGet.Core\NuGet.Protocol\Utility\LocalFolderUtility.cs:line 1129
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at NuGet.Protocol.LocalPackageSearchResource.<CollapseToHighestVersion>d__8.MoveNext() in D:\a\_work\1\s\src\NuGet.Core\NuGet.Protocol\LocalRepositories\LocalPackageSearchResource.cs:line 181
   at System.Linq.Enumerable.<SkipIterator>d__31`1.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__25`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NuGet.Protocol.LocalPackageSearchResource.<>c__DisplayClass2_0.<SearchAsync>b__0() in D:\a\_work\1\s\src\NuGet.Core\NuGet.Protocol\LocalRepositories\LocalPackageSearchResource.cs:line 63
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.LocalPackageSearchResource.<SearchAsync>d__2.MoveNext() in D:\a\_work\1\s\src\NuGet.Core\NuGet.Protocol\LocalRepositories\LocalPackageSearchResource.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.CommandLine.SearchCommand.<ExecuteCommandAsync>d__13.MoveNext() in D:\a\_work\1\s\src\NuGet.Clients\NuGet.CommandLine\Commands\SearchCommand.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.Command.Execute() in D:\a\_work\1\s\src\NuGet.Clients\NuGet.CommandLine\Commands\Command.cs:line 157
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args) in D:\a\_work\1\s\src\NuGet.Clients\NuGet.CommandLine\Program.cs:line 158
```

**Comment by nkolev92** [comment]
Team Triage: Having corrupt packages on a source can lead to various types of failures across the NuGet scenarios.
Search - Searching for packages from a flat nupkg local source will lead to failure to enumerate the packages there.
Restore - When installing a new package in the global packages folder, it would require enumeration of all packages from the feed and that would fail. 

We recommend that you delete the corrupted package from the feed. 
nupkgs are zip files, so we'd expect zip utility to fail to open them as well.

**Comment by quailstorm** [comment]
In my opinion the enumeration can just skip the corrupt package and log a warning. My suggestion also allows to see the complete list of corrupted packages in a source with a single command, instead of stopping on the first error one by one.

Can you take a look at my proposed "naive" solution? https://github.com/NuGet/NuGet.Client/commit/5aef5d90ea10cfd02f88bb1280b0b049e114bbb8


```
C:\Users\User\source\repos\NuGet_forked\NuGet.Client\artifacts\NuGet.CommandLine\bin\Debug\net472>NuGet.exe search -PreRelease -Source c:\invalidTest
WARNING: 'c:\invalidTest\ArchitectDemo.1.0.0-pre20230914122119.nupkg' is not a valid nupkg file. Error: 'Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.'.
====================
Source: c:\invalidTest
--------------------
> ConvertingToolbox | 4.0.0-pre20230712152354 | Downloads: N/A
  #descr_en#The Converting Toolbox module enables the configuration and generation of motion control a...
--------------------
> ModuleEssentials | 2.1.8 | Downloads: N/A
  #descr_en##descr_de##descr_zh##rnote_en##rnote_de##rnote_zh#
--------------------
> PrintStandard | 4.0.0 | Downloads: N/A
  #descr_en#The Print Standard software package comprises Motion Control functions and concepts for pr...
--------------------
> SIMITBuilder | 4.0.0 | Downloads: N/A
  #descr_en#
  #descr_de#
  #rnote_en#
  #rnote_de#
--------------------
```

**Comment by nkolev92** [comment]
@quailstorm That change is in core NuGet and affects restore and not just search. 
NuGet's general policy of dealing with package sources is fail fast. 
It's unfortunate since that's not ideal in your situation, but we're not certain we want to add that complexity at this point.

**Comment by quailstorm** [comment]
It is unfortunate in our case indeed. I can no longer reproduce receiving the partial list which has elements before the first consumed corrupt package which happened only with ListAsync's AsyncEnumerable in older versions as I have been told. So I have no arguments left for the change request.
