### ISSUE TITLE
[Bug]: msb4018 - seems like msbuild is not able to resolve cousin dependencies from project reference & package reference 

### ISSUE THREAD

**Issue by dxynnez** [NuGet/Home#12999]
### NuGet Product Used

dotnet.exe

### Product Version

.net sdk 7.0.403

### Worked before?

N/A

### Impact

It's more difficult to complete my work

### Repro Steps & Context

So we have a project (A) with transitive dependency to a package (pkg1 >= 1.0.0) which introduce another transitive dependency to another package (pkg2 ≥ 1.0.0). It also explicitly references pkg2's latest version (≥ 1.1.0).

We have another project (B) with project reference to the project A, and then a package references to pkg3 (>= 1.0.0) which also reference a higher version of the pkg2 ( ≥ 1.0.5)

Note: In the latest version of pkg1, the dependency on pkg 2 is removed.

When building (dotnet build) project B, the following error pops up:

0>Microsoft.PackageDependencyResolution.targets(266,5): Error MSB4018 : The "ResolvePackageAssets" task failed unexpectedly.
System.ArgumentException: An item with the same key has already been added. Key: ******
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](List`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at Microsoft.NET.Build.Tasks.ProjectContext.GetTopLevelDependencies(LockFile lockFile, LockFileTarget lockFileTarget)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.ComputePackageExclusions()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

If I then explicitly installed pkg2 (≥ 1.1.0) in project B then the build would succeed.

To verify there isn't any actual conflicts between all the dependencies, I created another new project with direct reference to package pkg1 (>= 1.0.0) and pkg2 (>= 1.1.0) and package 3 (>= 1.0.0) and I was able to build it - I was expecting project B would just work too as the resolved dependencies should be pkg1 >= 1.0.0, pkg2 ≥ 1.1.0 and pkg3 >= 1.0.0.

It seems like if the cousin dependencies are introduced by project reference & package reference then nuget would not be able to resolve them.

Let me know if the bug should be filed in the msbuild repo instead.

**Comment by jeffkl** [comment]
Thanks for taking the time to file this.  Unfortunately, the ResolvePackageAssets task is actually developed at https://github.com/dotnet/NuGet.BuildTasks

There is an existing issue that matches your problem which is marked as fixed: https://github.com/dotnet/NuGet.BuildTasks/issues/86

Please follow-up with that repository for more support for this component.

**Comment by dxynnez** [comment]
Thanks @jeffkl .

I think the linked issue is irrelevant as I still see the same error when building with the .Net 7.0.200 sdk.

Per our validation, this seems to be a bug in the legacy Central Package Versioning SDK.

After [MIGRATED to the new Central Package Management](https://github.com/microsoft/MSBuildSdks/blob/main/src/CentralPackageVersions/Migration.md#migrate-from-central-package-versioning-cpv-to-central-package-management-cpm) the error went away.

Since the CPV is a legacy tool I guess there isn't much action to take. 

Thanks again.
