### ISSUE TITLE
Error when trying to use NuGet.Protocol form Blazor WebAssembly app

### ISSUE THREAD

**Issue by vnbaaij** [NuGet/Home#12995]
### NuGet Product Used

NuGet SDK

### Product Version

.NET 8 RC2 SDK, NuGet packages 6.7

### Impact

I'm unable to use this version

### Repro Steps & Context

- Create a Standalone Blazor WebAssembly application
- Add the NuGet.Protocol package (6.7.0)
- In the `Home.razor` file add the following code:
```
<button @onclick="DoNuGetAsync">Search</button>

@code {
    private async Task DoNuGetAsync()
    {
// more code comes here
    }
}
```
- At the 'more code comes here' position paste the code from https://github.com/NuGet/Samples/blob/ec30a2b7c54c2d09e5a476444a2c7a8f2f289d49/NuGetProtocolSamples/Program.cs#L20-L335

Running the sample generates the following error:
fail: Microsoft.AspNetCore.Components.Web.ErrorBoundary[0]
      NuGet.Configuration.NuGetConfigurationException: Unexpected failure reading NuGet.Config. Path: '/home/web_user/.nuget/NuGet/NuGet.Config'.
       ---> System.DllNotFoundException: libc
         at NuGet.Configuration.FileSystemUtility.AddFile(String fullPath, Action`1 writeToStream)
         at NuGet.Configuration.FileSystemUtility.GetOrCreateDocument(XDocument content, String fullPath)
         at NuGet.Configuration.SettingsFile.<>c__DisplayClass23_0.<.ctor>b__0()
         at NuGet.Configuration.SettingsFile.<>c__DisplayClass32_0.<ExecuteSynchronized>b__0()
         --- End of inner exception stack trace ---
         at NuGet.Configuration.SettingsFile.<>c__DisplayClass32_0.<ExecuteSynchronized>b__0()
         at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLocked(String filePath, Action action)
         at NuGet.Configuration.SettingsFile.ExecuteSynchronized(Action ioOperation)
         at NuGet.Configuration.SettingsFile..ctor(String directoryPath, String fileName, Boolean isMachineWide, Boolean isReadOnly)
         at NuGet.Configuration.Settings.ReadSettings(String settingsRoot, String settingsPath, Boolean isMachineWideSettings, Boolean isAdditionalUserWideConfig, SettingsLoadingContext settingsLoadingContext)
         at NuGet.Configuration.Settings.LoadUserSpecificSettings(String root, String configFileName, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)+MoveNext()
         at System.Collections.Generic.List`1[[NuGet.Configuration.SettingsFile, NuGet.Configuration, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].AddRange(IEnumerable`1 collection)
         at NuGet.Configuration.Settings.LoadSettingsForSpecificConfigs(String root, String configFileName, List`1 validSettingFiles, IMachineWideSettings machineWideSettings, Boolean loadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
         at NuGet.Configuration.Settings.LoadSettings(String root, String configFileName, IMachineWideSettings machineWideSettings, Boolean loadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
         at NuGet.Configuration.Settings.LoadDefaultSettings(String root, String configFileName, IMachineWideSettings machineWideSettings, SettingsLoadingContext settingsLoadingContext)
         at NuGet.Configuration.Settings.LoadDefaultSettings(String root, String configFileName, IMachineWideSettings machineWideSettings)
         at NuGet.Configuration.ProxyCache.FromDefaultSettings()
         at NuGet.Configuration.ProxyCache.<>c.<.cctor>b__18_0()
         at System.Lazy`1[[NuGet.Configuration.ProxyCache, NuGet.Configuration, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ViaFactory(LazyThreadSafetyMode mode)
         at System.Lazy`1[[NuGet.Configuration.ProxyCache, NuGet.Configuration, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
         at System.Lazy`1[[NuGet.Configuration.ProxyCache, NuGet.Configuration, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].CreateValue()
         at System.Lazy`1[[NuGet.Configuration.ProxyCache, NuGet.Configuration, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].get_Value()
         at NuGet.Configuration.ProxyCache.get_Instance()
         at NuGet.Protocol.HttpHandlerResourceV3Provider..ctor()
         at NuGet.Protocol.Core.Types.Repository.ProviderFactory.<>c.<GetCoreV3>b__0_12()
         at System.Lazy`1[[NuGet.Protocol.Core.Types.INuGetResourceProvider, NuGet.Protocol, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ViaFactory(LazyThreadSafetyMode mode)
         at System.Lazy`1[[NuGet.Protocol.Core.Types.INuGetResourceProvider, NuGet.Protocol, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
         at System.Lazy`1[[NuGet.Protocol.Core.Types.INuGetResourceProvider, NuGet.Protocol, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].CreateValue()
         at System.Lazy`1[[NuGet.Protocol.Core.Types.INuGetResourceProvider, NuGet.Protocol, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].get_Value()
         at NuGet.Protocol.Core.Types.SourceRepository.<>c.<Init>b__17_0(Lazy`1 p)
         at System.Linq.Lookup`2[[System.Type, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Lazy`1[[NuGet.Protocol.Core.Types.INuGetResourceProvider, NuGet.Protocol, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer…xt()
   at System.Collections.Generic.List`1[[NuGet.Configuration.SettingsFile, NuGet.Configuration, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].AddRange(IEnumerable`1 collection)
   at NuGet.Configuration.Settings.LoadSettingsForSpecificConfigs(String root, String configFileName, List`1 validSettingFiles, IMachineWideSettings machineWideSettings, Boolean loadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
   at NuGet.Configuration.Settings.LoadSettings(String root, String configFileName, IMachineWideSettings machineWideSettings, Boolean loadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
   at NuGet.Configuration.Settings.LoadDefaultSettings(String root, String configFileName, IMachineWideSettings machineWideSettings, SettingsLoadingContext settingsLoadingContext)
   at NuGet.Configuration.Settings.LoadDefaultSettings(String root, String configFileName, IMachineWideSettings machineWideSettings)
   at NuGet.Configuration.ProxyCache.FromDefaultSettings()
   at NuGet.Configuration.ProxyCache.<>c.<.cctor>b__18_0()
   at System.Lazy`1[[NuGet.Configuration.ProxyCache, NuGet.Configuration, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[NuGet.Configuration.ProxyCache, NuGet.Configuration, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[NuGet.Configuration.ProxyCache, NuGet.Configuration, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].CreateValue()
   at System.Lazy`1[[NuGet.Configuration.ProxyCache, NuGet.Configuration, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].get_Value()
   at NuGet.Configuration.ProxyCache.get_Instance()
   at NuGet.Protocol.HttpHandlerResourceV3Provider..ctor()
   at NuGet.Protocol.Core.Types.Repository.ProviderFactory.<>c.<GetCoreV3>b__0_12()
   at System.Lazy`1[[NuGet.Protocol.Core.Types.INuGetResourceProvider, NuGet.Protocol, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[NuGet.Protocol.Core.Types.INuGetResourceProvider, NuGet.Protocol, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[NuGet.Protocol.Core.Types.INuGetResourceProvider, NuGet.Protocol, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].CreateValue()
   at System.Lazy`1[[NuGet.Protocol.Core.Types.INuGetResourceProvider, NuGet.Protocol, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].get_Value()
   at NuGet.Protocol.Core.Types.SourceRepository.<>c.<Init>b__17_0(Lazy`1 p)
   at System.Linq.Lookup`2[[System.Type, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Lazy`1[[NuGet.Protocol.Core.Types.INuGetResourceProvider, NuGet.Protocol, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2[[System.Lazy`1[[NuGet.Protocol.Core.Types.INuGetResourceProvider, NuGet.Protocol, Version=6.7.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Type, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetEnumerator()
   at NuGet.Protocol.Core.Types.SourceRepository.Init(IEnumerable`1 providers)
   at NuGet.Protocol.Core.Types.SourceRepository..ctor(PackageSource source, IEnumerable`1 providers, FeedType feedTypeOverride)
   at NuGet.Protocol.Core.Types.Repository.CreateSource(IEnumerable`1 resourceProviders, PackageSource source, FeedType type)
   at NuGet.Protocol.Core.Types.Repository.CreateSource(IEnumerable`1 resourceProviders, PackageSource source)
   at NuGet.Protocol.Core.Types.Repository.CreateSource(IEnumerable`1 resourceProviders, String sourceUrl)
   at NuGet.Protocol.FactoryExtensionsV3.GetCoreV3(RepositoryFactory factory, String source)
   at BlazorApp1.Pages.Home.ListPackageVersionsAsync() in D:\Source\Temp\BlazorApp1\BlazorApp1\Pages\Home.razor:line 65
   at BlazorApp1.Pages.Home.DoNuGetAsync() in D:\Source\Temp\BlazorApp1\BlazorApp1\Pages\Home.razor:line 25
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)…

**Comment by jebriede** [comment]
@vnbaaij Blazor WebAssembly (WASM) apps run in the browser sandbox, and they are limited to the browser's capabilities. As a result, they cannot access the file system, which is why you're encountering issues with NuGet.Protocol.

NuGet.Protocol requires access to your machine's NuGet.config file, which is not possible within the browser context. If your app needs direct access to files on the system, you may want to consider using a different hosting model for your Blazor app.

For more information on the limitations of Blazor WebAssembly, you can refer to the official documentation here: https://learn.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-7.0#blazor-webassembly. You'll also find a useful comparison chart of the various hosting models and their capabilities on the same page, here: https://learn.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-7.0#which-blazor-hosting-model-should-i-choose
