### ISSUE TITLE
 SDK resolver produces huge ugly stack trace instead of nice error when a feed returns 401 unauthorized.

### ISSUE THREAD

**Issue by danmoseley** [NuGet/Home#13005]
I got the following doing a restore on Ubuntu with 8.0.100-rtm.23512.16.

I don't know what the repo is, but this issue is to change one frame here, perhaps `NuGet.Commands.RestoreRunner.RunWithoutCommit`, to handle AggregateException/FatalProtocolException and produce an error message instead of a callstack.

```
/home/dan/git/runtime/artifacts/toolset/restore.proj : error : Could not resolve SDK "Microsoft.DotNet.Arcade.Sdk". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :   SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" returned null.
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :   System.AggregateException: One or more errors occurred. (Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/internal/_packaging/dotnet-libraries-internal/nuget/v3/index.json.)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :  ---> NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/internal/_packaging/dotnet-libraries-internal/nuget/v3/index.json.
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :  ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Protocol.HttpSource.<>c__DisplayClass15_0`1.<<GetAsync>b__0>d.MoveNext()
/home/dan/git/runtime/artifacts/toolset/restore.proj : error : --- End of stack trace from previous location ---
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(dan@danmose50:~/git/runtime$
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    --- End of inner exception stack trace ---
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Protocol.Providers.VulnerabilityInfoResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Commands.VulnerabilityInformationProvider.GetVulnerabilityInfoAsync()
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Commands.VulnerabilityInformationProvider.GetVulnerabilityInformationAsync(CancellationToken cancellationToken)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Commands.Restore.Utility.AuditUtility.GetAllVulnerabilityDataAsync(CancellationToken cancellationToken)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Commands.Restore.Utility.AuditUtility.CheckPackageVulnerabilitiesAsync(CancellationToken cancellationToken)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Commands.RestoreCommand.PerformAuditAsync(EnabledValue enableAudit, IEnumerable`1 graphs, TelemetryActivity telemetry, CancellationToken token)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at NuGet.Commands.RestoreRunner.RunWithoutCommit(IEnumerable`1 restoreRequests, RestoreArgs restoreContext)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    --- End of inner exception stack trace ---
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :    at Microsoft.Build.NuGetSdkResolver.NuGetSdkResolver.NuGetAbstraction.GetSdkResult(SdkReference sdk, Object nuGetVersion, SdkResolverContext context, SdkResultFactory factory)
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :   MSB4276: The default SDK resolver failed to resolve SDK "Microsoft.DotNet.Arcade.Sdk" because directory "/home/dan/git/runtime/.dotnet/sdk/8.0.100-rtm.23512.16/Sdks/Microsoft.DotNet.Arcade.Sdk/Sdk" did not exist.
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :     [CredentialProvider]Warning: Cannot persist Microsoft authentication token cache securely!
/home/dan/git/runtime/artifacts/toolset/restore.proj : error :     [CredentialProvider]Warning: Using plain-text fallback token cache
/home/dan/git/runtime/artifacts/toolset/restore.proj : error : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
/home/dan/git/runtime/artifacts/toolset/restore.proj : error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.
```

**Comment by danmoseley** [comment]
Oh, inspecting the output above, it's just got a 401 unauthorized from one of the feeds. The error is not a bug in Nuget, the bug in Nuget is that it should not produce a raw stack trace.
