### ISSUE TITLE
Flaky test: Transitive packages are missing in Apex test `SearchTransitivePackageInInstalledTabFromUI`

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#13033]
There's no exception available, as it indicates:

>   NuGet.Tests.Apex.NuGetUITestCase.SearchTransitivePackageInInstalledTabFromUI failed due to an exception, but the stack trace was unavailable. Refer to the mstest log if necessary.

Example failure from build 6.9.0.379:

```
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NuGet.Tests.Apex.NuGetUIProjectTestExtension.AssertPackageNameAndType(String packageId, PackageLevel packageLevel)
   at NuGet.Tests.Apex.NuGetUITestCase.<SearchTransitivePackageInInstalledTabFromUI>d__32.MoveNext() in D:\a\_work\1\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\NuGetEndToEndTests\NuGetUITestCase.cs:line 763

```

The attached screenshot clearly shows that no transitive packages are being displayed in the Installed tab.
![image](https://github.com/NuGet/Home/assets/49205731/6c3fb175-77bd-451e-a814-9e745db7dc39)

**Comment by nkolev92** [comment]
@v-luzh Can one of you please take a stab at this as this was a new test case added?

cc @jeffkl just in case this is an infrastructure issue.

**Comment by v-luzh** [comment]
@nkolev92 OK, we will investigate the flaky test and try to update the old version with more reliable code.
