### ISSUE TITLE
Adding a `GlobalPackageReference` silently breaks `RestorePackagesConfig` throughout the repo

### ISSUE THREAD

**Issue by johnterickson** [NuGet/Home#13093]
### NuGet Product Used

MSBuild.exe

### Product Version

17.9.0-preview-23578-04+5fcddc790

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

I made some changes to my repo and unrelated projects in the repo failed to `Build` because of missing dependencies - though still `Restore`d fine.  This made no sense.

After a bunch of digging, I discovered that when I added a `GlobalPackageReference` to a `Directory.Packages.props`, NuGet then would _silently_ ignore `<RestorePackagesConfig>true</RestorePackagesConfig>`. 

I could have saved a lot of time had there been a warning that said something like "You are using both GlobalPackageReference and RestorePackagesConfig, but they are incompatible, so ignoring RestorePackagesConfig".

Again, I'm not asking to make the combination work - just to warn about this footgun. Thanks!

Andy mentioned that @jeffkl might be interested in this issue.

**Comment by nkolev92** [comment]
The opt-in for PackageReference is having a PackageReference declared or a RestoreProjectStyle of PackageReference. 

Given that a GlobalPackageReference is a syntactic sugar for a PackageReference, it effectively ends up opting in every project to PackageReference, so the restore packages config becomes irrelevant.

**Comment by johnterickson** [comment]
Great point about syntactic sugar, @nkolev92!

In that light, the issue I am talking about here is probably better described as:

MSBuild/NuGet should emit a warning when both:
1. The project author has clearly indicated an intent to use packages.config (e.g. `RestorePackagesConfig`==`true` and/or a `packages.config` exists)
2. `packages.config` will not be used because of the implicit consequence of another property/configuration.

**Comment by nkolev92** [comment]
I think we'd need a solution that's not dependent on the `RestorePackagesConfig` property, because that's not going to address the issue in VS or nuget.exe which are not dependent on a RestorePackagesConfig property. 

I think the challenge is within VS, where for legacy projects, we don't have enough information to differentiate between a global package reference and a regular one, and we can't make any sort of distinction. CLI restore can raise warnings/provide some indicators.

**Comment by nkolev92** [comment]
Although, rereading your comment now, a warning that happens sometimes is better than no warning. 

We have that trade for example for the duplicate PackageReference warning, where it doesn't work in VS for legacy projects or nuget.exe

**Comment by andrewimcclement** [comment]
I have a similar issue where my solution include C++ projects which use packages.config. I tried to make the GlobalPackageReference conditional `Condition="'$(MSBuildProjectExtension)'=='.csproj'"` but while this allowed nuget.exe to restore packages correctly, msbuild still failed with the error:
```
Microsoft.NuGet.targets(198,5): Error : Sequence contains no elements at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.GiveErrorForMissingFramework()
at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.GetTargetOrAttemptFallback(JObject lockFile, Boolean needsRuntimeIdentifier)
at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.GetReferences(JObject lockFile)
at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.ExecuteCore()
at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.Execute()
```
for all C++ projects in the solution.

Why doesn't the conditional logic work appropriately?

**Comment by dfederm** [comment]
This should mitigate projects from falling away from packages.config when global package references are defined. Note that of course the projects *won't* have those "global" package references anymore.

```xml
<RestoreEnableGlobalPackageReference>false</RestoreEnableGlobalPackageReference>
```

That effectively turns off the translation of GlobalPackageReference -> PackageReference in whatever project(s) that property is set in.
