### ISSUE TITLE
Cannot install globally a .NET tool on Linux when the version contains uppercase

### ISSUE THREAD

**Issue by meziantou** [NuGet/Home#13275]
### NuGet Product Used

dotnet.exe

### Product Version

8.0.200

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Be sure to run `dotnet tool update` on Linux or a case-sensitive file-system

````
dotnet new console
dotnet pack /p:PackAsTool=true /p:version=1.0.0-abc
dotnet pack /p:PackAsTool=true /p:version=1.0.0-Dummy

# works
dotnet tool update test --version 1.0.0-abc --global --add-source ./bin/Release/

# crash
dotnet tool update test --version 1.0.0-Dummy --global --add-source ./bin/Release/
````

### Verbose Logs

```
Skipping NuGet package signature verification.
Unhandled exception: System.IO.FileNotFoundException: Could not find file '/home/repro/.dotnet/tools/.store/.stage/pfgaxwyq.dh2/test/1.0.0-dummy/test.1.0.0-dummy.nupkg'.
File name: '/home/repro/.dotnet/tools/.store/.stage/pfgaxwyq.dh2/test/1.0.0-dummy/test.1.0.0-dummy.nupkg'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.Protocol.LocalFolderUtility.<>c__DisplayClass48_0.<GenerateNupkgMetadataFile>b__0()
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLocked(String filePath, Action action)
   at NuGet.Repositories.NuGetv3LocalRepository.GetPackage(String packageId, NuGetVersion version, String path)
   at NuGet.Repositories.NuGetv3LocalRepository.FindPackageImpl(String packageId, NuGetVersion version)
   at NuGet.Repositories.NuGetv3LocalRepository.FindPackage(String packageId, NuGetVersion version)
   at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.CreateAssetFile(PackageId packageId, NuGetVersion version, DirectoryPath packagesRootPath, DirectoryPath assetFileDirectory, String runtimeJsonGraph, String targetFramework)
   at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.<>c__DisplayClass8_0.<InstallPackage>b__0()
   at Microsoft.DotNet.Cli.TransactionalAction.Run[T](Func`1 action, Action commit, Action rollback)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.<>c__DisplayClass18_0.<Execute>b__1()
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.RunWithHandlingInstallError(Action installAction)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()
   at Microsoft.DotNet.Tools.Tool.Update.ToolUpdateGlobalOrToolPathCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

**Comment by nkolev92** [comment]
@meziantou 

The consumer for this code is in the https://github.com/dotnet/sdk. 


Can you move that issue there? (I can move it but it's better if the issue comes from you.)

**Comment by meziantou** [comment]
Will do! 

Based on the call stack `at NuGet.Protocol.LocalFolderUtility.<>c__DisplayClass48_0.<GenerateNupkgMetadataFile>b__0()`, I thought this was related to this repo.

**Comment by meziantou** [comment]
https://github.com/dotnet/sdk/issues/39105

**Comment by nkolev92** [comment]
> Will do!
> 
> Based on the call stack `at NuGet.Protocol.LocalFolderUtility.<>c__DisplayClass48_0.<GenerateNupkgMetadataFile>b__0()`, I thought this was related to this repo.

They're basically calling those APIs. 
It seems like the code is not accounting for the fact that nupkgs always get normalized versions (lowercase))
