### ISSUE TITLE
Assertion failure when restoring with project.json with multiple frameworks in imports

### ISSUE THREAD

**Issue by dsplaisted** [NuGet/Home#1337]
Create a project.json with an imports element with multiple frameworks separated by a semicolon, for example:

``` json
{
  "supports": {
    "net46.app": {},
    "uwp.10.0.app": {},
    "dnxcore50.app": {}
  },
  "dependencies": {
    "Microsoft.NETCore": "5.0.0",
    "Microsoft.NETCore.Portable.Compatibility": "1.0.0"
  },
  "frameworks": {
    "dotnet": {
      "imports": "portable-net452+win81;aspnetcore50"
    }
  }
}
```

Then run NuGet restore on it.

**EXPECTED:** Either the restore runs successfully, or it prints an appropriate error message
**ACTUAL:** Assertion failure:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
invalid folder name, this appears to contain multiple frameworks



   at NuGet.Frameworks.NuGetFramework.Parse(String folderName, IFrameworkNameProvider mappings)

   at NuGet.Frameworks.NuGetFramework.Parse(String folderName)

   at NuGet.ProjectModel.JsonPackageSpecReader.GetImports(JObject properties)

   at NuGet.ProjectModel.JsonPackageSpecReader.BuildTargetFrameworkNode(PackageSpec packageSpec, KeyValuePair`2 targetFramework)

   at NuGet.ProjectModel.JsonPackageSpecReader.BuildTargetFrameworks(PackageSpec packageSpec, JObject rawPackageSpec)

   at NuGet.ProjectModel.JsonPackageSpecReader.GetPackageSpec(Stream stream, String name, String packageSpecPath)

   at NuGet.ProjectModel.JsonPackageSpecReader.GetPackageSpec(String json, String name, String packageSpecPath)

   at NuGet.CommandLine.RestoreCommand.<PerformNuGetV3RestoreAsync>d__20.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at NuGet.CommandLine.RestoreCommand.PerformNuGetV3RestoreAsync(String packagesDir, String inputPath)

   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__18.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

   at NuGet.CommandLine.RestoreCommand.ExecuteCommandAsync()

   at NuGet.CommandLine.Command.Execute()

   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)

   at NuGet.CommandLine.Program.Main(String[] args)


---------------------------
Abort   Retry   Ignore   
---------------------------
```

If you make this change to the project.json of a project in Visual Studio and then try building, you'll get this assertion and VS will crash.

**Comment by emgarten** [comment]
Logging an error would be helpful here. I get the assert when trying this but VS does not crash and the restore completes successfully.

**Comment by yishaigalatzer** [comment]
@dsplaisted if you get a crash, can you please share a callstack or dump?

If we don't get a crash than this is just a low priority error message, since we currently do not encourage people to edit the project.json by hand (which is how you get in trouble at the moment :) )

**Comment by yishaigalatzer** [comment]
This was because we used to build debug accidentally. This is now fixed.

Please validate you don't see the issue again.

**Comment by dsplaisted** [comment]
Great!  I don't see the crash anymore.
