### ISSUE TITLE
"Nuget search take" throws if the value exceeds actual number of nugets in the feed

### ISSUE THREAD

**Issue by DmitryLukyanov** [NuGet/Home#13509]
### NuGet Product Used

NuGet.exe

### Product Version

NuGet Version: 6.9.1.3

### Worked before?

yes, checked 1 week ago

### Impact

I'm unable to use this version

### Repro Steps & Context

When the take number is bigger than number of packages:

        PS C:\> nuget search -take 1335 -Source SourceName
        Error converting value "file://C:%5CUsers%5CAdministrator%5Cbuildkite-agent%5Cbuilds%5Cpm-build%5Cpostman%5Capp-package-and-deploy/resources/postman-prod.ico" to type 'System.Uri'. Path 'data[1334].iconUrl', line 1, position 6811849.
          Could not cast or convert from System.String to System.Uri.

When the same or less than number of packages:
        
        PS C:\> nuget search -take 1334 -Source SourceName
        ====================
        Source: SourceName
        --------------------
        > System.Runtime....
        ...

### Verbose Logs

```shell
PS C:\> nuget search -take 1335 -Source SourceName -verbosity detailed
NuGet Version: 6.9.1.3
Found 1 search endpoints.
Querying
https://%address%/api/nuget/v3/nuget/query?q=&skip=0&take=1335&prerelease=false&semVerLevel=2.0.0
Error converting value "file://C:%5CUsers%5CAdministrator%5Cbuildkite-agent%5Cbuilds%5Cpm-build%5Cpostman%5Capp-package-and-deploy/resources/postman-prod.ico" to type 'System.Uri'. Path 'data[1334].iconUrl', line 1, position 6811730.
  Could not cast or convert from System.String to System.Uri.
Newtonsoft.Json.JsonSerializationException: Error converting value "file://C:%5CUsers%5CAdministrator%5Cbuildkite-agent%5Cbuilds%5Cpm-build%5Cpostman%5Capp-package-and-deploy/resources/postman-prod.ico" to type 'System.Uri'. Path 'data[1334].iconUrl', line 1, position 6811730. ---> System.ArgumentException: Could not cast or convert from System.String to System.Uri.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at NuGet.Protocol.Converters.V3SearchResultsConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at NuGet.Protocol.PackageSearchResourceV3.<ProcessHttpStreamWithoutBufferingAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.PackageSearchResourceV3.<ProcessHttpStreamTakeCountedItemAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<>c__DisplayClass17_0`1.<<ProcessHttpStreamAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<ProcessHttpStreamAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.PackageSearchResourceV3.<SearchPage>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.PackageSearchResourceV3.<Search>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.PackageSearchResourceV3.<Search>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.PackageSearchResourceV3.<SearchAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.CommandLine.SearchCommand.<ExecuteCommandAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by martinrrm** [comment]
I wasn't able to reproduce locally, looking at the error it looks like the icon from package is not correct. It tries to create an URL from "..resources/postman-prod.ico" which doesn't end in ".icon", is that enough for it to not be recognized as URL?

**Comment by jeffkl** [comment]
@DmitryLukyanov it looks like the feed contains a package with an icon URL that is a local path:
```
file://C:%5CUsers%5CAdministrator%5Cbuildkite-agent%5Cbuilds%5Cpm-build%5Cpostman%5Capp-package-and-deploy/resources/postman-prod.ico
```

That package happens to be the 1,335th package in the list so its where the exception occurs as NuGet is calling Newtonsoft.Json to deserialize the string as a Uri.  Can you tell us what package is doing this?  NuGet shouldn't be failing in this way but we want to be able to reproduce the problem.

**Comment by DmitryLukyanov** [comment]
@jeffkl , I can't reproduce it today locally, not sure why, will try it in pipeline a bit later

**Comment by DmitryLukyanov** [comment]
I don't see this error in the pipeline anymore too. So, I'm not sure whether the solution is on my side (a problematic package has been redeployed) or on nuget. In any case, I hope the possible problematic place has been highlighted.
