### ISSUE TITLE
`PackCommand_ReferencedProjectWithJsonFile` is flaky

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#13536]
> System.TimeoutException : D:\a_work\1\s\test\NuGet.Clients.Tests\NuGet.CommandLine.Test\bin\Debug\net472\NuGet\NuGet.exe pack proj1.csproj -build -IncludeReferencedProjects timed out after 62.05 seconds
> 
> Stack trace
>    at NuGet.Test.Utility.CommandRunner.Run(String filename, String workingDirectory, String arguments, Int32 timeOutInMilliseconds, Action`1 inputAction, IDictionary`2 environmentVariables, ITestOutputHelper testOutputHelper) in D:\a\_work\1\s\test\TestUtilities\Test.Utility\CommandRunner.cs:line 89
>    at NuGet.CommandLine.Test.NuGetPackCommandTest.PackCommand_ReferencedProjectWithJsonFile() in D:\a\_work\1\s\test\NuGet.Clients.Tests\NuGet.CommandLine.Test\NuGetPackCommandTest.cs:line 1578

**Comment by nkolev92** [comment]
This test has been deleted.
