### ISSUE TITLE
Missing CPM PackageVersion causes an NRE in PM UI due to restore errors

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#13627]
Affected Branch: main
Affected Build: Version 17.12.0 Preview 1.0 [35110.85.main]
Affected Product Language: English/All

Steps to reproduce:

1.  Construct a package using Central Package Management but miss a PackageVersion for one of the PackageReference items
2. Open in Visual Studio
3. Solution Explorer -> Right click on Solution node -> Manage Nuget Packages for Solution...
4. Displayed yellow bar for "Error Occurred"
![a84f0746-a42c-4932-9edf-b8b7f3b6fdc8](https://github.com/user-attachments/assets/61a3e033-4ba6-4efe-8191-1755fe0c4420)

5. Click on "Show Errors in Output"
RESULT:
![d589c0b5-b09a-496a-869d-53eda3f23316](https://github.com/user-attachments/assets/c62cc054-f2d7-4bea-bf22-97b19a9ff9c6)

EXPECT:

I see errors in several places in this condition, but for all of them, they say "Value cannot be null, Parameter name: versionRange".  If they included what package was the issue, then I can track it down.  In fact, because the version is empty/null/not displayed, the only piece of information I have to track this down is the packageName.  If it had a version and the version was simply not valid SemVer or not found in a source, I could look at the small set of packages with that version to find the cause.

NOTE
There is a warning in the Error List: 
Severity Code Description Project File Line Suppression State Details
Error NU1010 The PackageReference items Microsoft.VisualStudio.Editor do not have corresponding PackageVersion. EntityDesigner D:\dd\ef6tools\src\EFTools\EntityDesignEntityDesigner\EntityDesigner.csproj 1

But the link in the UI brings me to the Package Manager Output window, which doesn't have such a clear message.

**Comment by exaiwitmx** [comment]
I also have this error after converting to Central Package References:
![image](https://github.com/user-attachments/assets/835698cb-4574-4e6a-933d-2fd50b45ca75)

By conversion, I mean the following:
- Removed all version numbers from PackageReference elements in project files (*.csproj).
- Added PackageVersion elements to Directory.Packages.props located in root directory of solution.

I've double-checked that all PackageReference elements present in any project file have a corresponding PackageVersion  element in Directory.Packages.props.

I also get an error in the error list, but no project name/path mentioned there:
![image](https://github.com/user-attachments/assets/e46f1910-5577-4fe8-bcce-b502c0d5798b)

If I try to restore the Nuget Packages for the solution, I get a few errors like this one:
`The PackageReference items Microsoft.Graph;Microsoft.Identity.Client do not have corresponding PackageVersion.`
But the corresponding PackageVersion elements are present in Directory.Packages.props.


Visual Studio Professional 2022 (64bit), Version 17.10.0

**Comment by exaiwitmx** [comment]
Never mind - I was actually checking/editing the wrong Directory.Packages.props in a different working copy. The relevant one was actually missing some PackageVersion elements.

Time to have a break, I guess.

**Comment by ardalis** [comment]
Running into this as well trying to use a private GitHub org NuGet feed. I'm trying to "Manage NuGet Packages for Solution in VS 2022:
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.10.5

Output:
![image](https://github.com/user-attachments/assets/91b78c9e-409d-4382-98d9-eff0579c35f9)

Looking at an individual project works - it's when I try for the whole solution that the error occurs.

**Comment by SueSu01** [comment]
This issue also reproes for creating iOS App (Xamarin).

Repro steps:
1. Create a iOS App (Xamarin)(iPhone Master-Detail App)
2. Right-click the project in Solution Explorer and select “Manage NuGet Packages…” menu item to open PM UI. 
3. Displayed yellow bar for "Error Occurred"
![image](https://github.com/user-attachments/assets/caf4b915-92ea-4fb5-b5b1-1f5b87dead00)

**Comment by voroninp** [comment]
> Error occurred while restoring NuGet packages: System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.ProjectModel.PackagesLockFileUtilities.<>c.<HasDirectPackageDependencyChanged>b__6_3(LibraryDependency e)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at NuGet.ProjectModel.PackagesLockFileUtilities.HasDirectPackageDependencyChanged(IEnumerable`1 newDependencies, IEnumerable`1 lockFileDependencies, NuGetFramework nuGetFramework)
   at NuGet.ProjectModel.PackagesLockFileUtilities.IsLockFileValid(DependencyGraphSpec dgSpec, PackagesLockFile nuGetLockFile)
   at NuGet.Commands.RestoreCommand.<EvaluatePackagesLockFileAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<ExecuteAndCommitAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Commands.RestoreRunner.<RunAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<RestoreAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<>c__DisplayClass29_0.<<RestorePackageSpecProjectsAsync>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.RestoreOperationLogger.<RunWithProgressAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.SolutionRestoreManager.RestoreOperationLogger.<RunWithProgressAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestorePackageSpecProjectsAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<ExecuteAsync>d__26.MoveNext()
Value cannot be null.
Parameter name: versionRange

**Comment by donnie-msft** [comment]
> This issue also reproes for creating iOS App (Xamarin).
> 
> Repro steps:
> 
> 1. Create a iOS App (Xamarin)(iPhone Master-Detail App)
> ...

@SueSu01 this sounds like a different issue. Could you check this one I filed recently and comment there if you feel it's what you encountered? I see your Restore hasn't completed, so thinking it might be that restore is disabled and not related to CPM.

https://github.com/NuGet/Home/issues/13722

**Comment by donnie-msft** [comment]
Developer Community VS Feedback ticket: https://developercommunity.visualstudio.com/t/ResolvePackageAssets-fails-when-using-ce/10740120

**Comment by IanKemp** [comment]
@donnie-msft I don't believe the linked issue (which I reported) is quite the same as this one? This one appears to be for a `PackageReference` sans its `PackageVersion`, while mine is for an entirely missing `PackageReference` in `Directory.Packages.props`.

I have no objection if you wish to group the two together as it's likely the same area of code and it makes sense to fix two bugs in one pull request, but I do want to make sure that the two issues don't get conflated such that only one of them actually gets fixed.

**Comment by donnie-msft** [comment]
@IanKemp Understood. Whether it's missing completely or missing attributes, there is an NRE in PM UI either way. Thanks!

**Comment by ppvario** [comment]
I had a similar issue with my .NET project.
.NET Version: 9.0.100

One of the solution's nuget packages were not getting restored and I was getting the following error on build:
`The PackageReference items FastEndpoints.Security;Microsoft.AspNetCore.Authentication.JwtBearer do not have corresponding PackageVersion.`
Additionally, I am was also getting the following when I try to open the Nuget Package Manager for that project:

```
Value cannot be null.
Parameter name: versionRange
```

I also had an exclamation marks on my packages under dependencies and they didn't had the version numbers listed:
![image](https://github.com/user-attachments/assets/7d7607ea-42da-4ad2-9939-7d24095c1932)

The culprit was 
`<Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.1.3" />`

When I added the new packages using Nuget Package Manager, it did not update the Directory.Packages.Props with those packages.
So after manually adding them, I was able to get my build to succeed.

I spent way too much time trying to debug this issue. It would have been very helpful if Nuget could give some better error log. Hope this helps someone who's in a similar situation.

Thanks!
