### ISSUE TITLE
MSB4018 When using central package managing and package is not specified in Directory.Packages.props 

### ISSUE THREAD

**Issue by voroninp** [NuGet/Home#13631]
### NuGet Product Used

MSBuild.exe

### Product Version

dotnet 8.0303

### Worked before?

I do not know =)

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

I just coppied some projects into my solution.
Those projects contain `PackageReference` but existing `Directory.Packages.props` files does not contain those projects in the list, that is no `PackageVersion` entry. 

When I try to build the solution, I get a very ugly message:
```
MSB4018	The "ResolvePackageAssets" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NET.Build.Tasks.ProjectContext.<>c__DisplayClass31_0.<GetTopLevelDependencies>b__3(String projectFileDependency)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.ComputePackageExclusions()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	
C:\Program Files\dotnet\sdk\8.0.303\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets
```

See the repro: https://github.com/voroninp/FailingMsBuild
IMO, the message shoud be developer-friendy and tell me that `PackageVersion` element is not specified.

**Comment by jgonz120** [comment]
Hello! When I tried to repro with your GitHub repo I'm getting a different error. 
```
PS C:\src\FailingMsBuild> dotnet --version
8.0.303
PS C:\src\FailingMsBuild> dotnet build
  Determining projects to restore...
C:\src\FailingMsBuild\FailingMsBuild.csproj : error NU1008: Projects that use central package version management should
 not define the version on the PackageReference items but on the PackageVersion items: NuGetizer. [C:\src\FailingMsBuil
d\FailingMsBuild.sln]
  Failed to restore C:\src\FailingMsBuild\FailingMsBuild.csproj (in 57 ms).

Build FAILED.

C:\src\FailingMsBuild\FailingMsBuild.csproj : error NU1008: Projects that use central package version management should
 not define the version on the PackageReference items but on the PackageVersion items: NuGetizer. [C:\src\FailingMsBuil
d\FailingMsBuild.sln]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.78
```
Which seems more useful than what you're seeing. Are these the right steps?

**Comment by voroninp** [comment]
Hm...
![image](https://github.com/user-attachments/assets/d7d5b948-4ff6-4aca-820a-a2e36fc78eaa)
I can reproduce it both in 
```
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.10.4
```
and with latest preview:
```
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.11.0 Preview 4.0
```
It fails when I have `global.json` and when I don't

Here's the output of `dotnet --info`:
```
.NET SDK:
 Version:           9.0.100-preview.6.24328.19
 Commit:            ef4c241666
 Workload version:  9.0.100-manifests.7e18eb25
 MSBuild version:   17.11.0-preview-24318-05+4a45d5633

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.6.24328.19\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [android]
   Installation Source: SDK 9.0.100-preview.6, VS 17.11.35111.106, VS 17.10.35027.167
   Manifest Version:    34.99.0-preview.6.340/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.android\34.99.0-preview.6.340\WorkloadManifest.json
   Install Type:              Msi

 [aspire]
   Installation Source: SDK 9.0.100-preview.6, VS 17.10.35027.167
   Manifest Version:    8.0.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.2\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: SDK 9.0.100-preview.6, VS 17.11.35111.106, VS 17.10.35027.167
   Manifest Version:    17.2.9714-net9-p6/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.ios\17.2.9714-net9-p6\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: SDK 9.0.100-preview.6, VS 17.11.35111.106, VS 17.10.35027.167
   Manifest Version:    17.2.9714-net9-p6/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.maccatalyst\17.2.9714-net9-p6\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: SDK 9.0.100-preview.6, VS 17.11.35111.106, VS 17.10.35027.167
   Manifest Version:    9.0.0-preview.6.24327.7/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.maui\9.0.0-preview.6.24327.7\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools]
   Installation Source: SDK 9.0.100-preview.6, VS 17.11.35111.106, VS 17.10.35027.167
   Manifest Version:    9.0.0-preview.6.24327.7/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.workload.mono.toolchain.current\9.0.0-preview.6.24327.7\WorkloadManifest.json
   Install Type:              Msi


Host:
  Version:      9.0.0-preview.6.24327.7
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  7.0.410 [C:\Program Files\dotnet\sdk]
  8.0.303 [C:\Program Files\dotnet\sdk]
  8.0.400-preview.0.24324.5 [C:\Program Files\dotnet\sdk]
  9.0.100-preview.6.24328.19 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.6.24328.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24327.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.6.24327.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
```

**Comment by voroninp** [comment]
Surprisingly, when I just run `dotnet build` I get the same message as you do:

> C:\Users\pavel\source\repos\voroninp\FailingMsBuild\FailingMsBuild.csproj : error NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: NuGetizer. [C:\Users\pavel\source\repos\voroninp\FailingMsBuild\FailingMsBuild.sln]

**Comment by nkolev92** [comment]
~Likely~ Dup of https://github.com/NuGet/Home/issues/13563. 


Fixed in https://github.com/NuGet/NuGet.Client/commit/ae8c3e443cce585cfc973075a8d9c7a809c549fd.

**Comment by tcartwright** [comment]
I wrote this powershell to scan for this: https://gist.github.com/tcartwright/a3d5b57c46ae58024bf16f53d5e956fd 

```ps
Clear-Host

<#
  PURPOSE: To scan all of the projects in a directory and compare the PackageReferences to the
  Directory.Packages.props PackageVersions. Outputs if any are missing from the Directory.Packages.props
#>

$solutionFolder = "C:\..solution path..\"
$files = (Get-ChildItem $solutionFolder -Recurse -Filter "*.csproj").FullName

$xmlFilePath2 = "C:\..path..\Directory.Packages.props"
# Load the XML file
$xml2 = [xml](Get-Content $xmlFilePath2 -Raw)
$packageVersions = ($xml2.Project.ItemGroup.PackageVersion).Include

foreach ($file in $files) {

    # Load the XML file
    $xml = [xml](Get-Content $xmlFilePath -Raw)

    # Get the PackageReference nodes
    $packageReferences = ($xml.Project.ItemGroup.PackageReference).Include

    $compares = Compare-Object -ReferenceObject $packageReferences -DifferenceObject $packageVersions  

    Write-Host -ForegroundColor Yellow $file
    #$compares | Out-Host
    # IF ANY SHOW IN THIS LIST THEY NEED TO BE ADDED TO THE PROPS FILE
    $compares | Where-Object { $_.SideIndicator -eq "<=" } | Out-Host
}
```

**Comment by nkolev92** [comment]
NuGet raises an NU1008 warning telling you exactly which version is missing. 
This bug is because the build errors are just too many and they pretty much lead to the NU1008 errors getting hidden. 

I meant to close this bug earlier, so closing now.
