### ISSUE TITLE
Can not install signed package with certificate chain building issue

### ISSUE THREAD

**Issue by Ilchert** [NuGet/Home#13643]
### NuGet Product Used

dotnet.exe, MSBuild.exe, NuGet.exe

### Product Version

dotnet 8.0.303, dev nuget.exe

### Worked before?

According to https://github.com/mbdavid/LiteDB/issues/1874 may worked in dotnet 3.1

### Impact

It's more difficult to complete my work

### Repro Steps & Context

This bug is related to https://github.com/mbdavid/LiteDB/issues/1874.

We are trying to install/restore LiteDB, which is signed with certificate, issued by ssl.com. 
![image](https://github.com/user-attachments/assets/35940b88-b4d2-4b4b-90f8-3915d14e1081)

For CI/CD we are using Windows Server 2022 21H2 20348.2461 without SSL.com trusted root certificate installed, but with [certificate trust list](http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/authrootstl.cab), and on this list, we have an issue with certificate in the chain.

![image](https://github.com/user-attachments/assets/c22a5443-fd43-429f-a343-8736d1b3876f)

I understand that we have to fix issue with certificate, but I expect that nuget should be able to install this package in `signatureValidationMode=accept`.

The problem starts here 

https://github.com/NuGet/NuGet.Client/blob/46f80a3f1a83f3c5f33a20fa9fb72871e1e2d4eb/src/NuGet.Core/NuGet.Packaging/Signing/Utility/VerificationUtility.cs#L28-L34

Сonverts `SignatureVerificationStatusFlags.ChainBuildingFailure` into `SignatureVerificationStatus.Disallowed`

And then this leads to `NuGet.Packaging.Signing.SignatureException` here (`verifyResult.IsValid is false`)

https://github.com/NuGet/NuGet.Client/blob/46f80a3f1a83f3c5f33a20fa9fb72871e1e2d4eb/src/NuGet.Core/NuGet.Packaging/PackageExtractor.cs#L1034-L1072

And remove downloaded files.

nuget.exe install litedb:

```console
Error downloading 'LiteDB.5.0.21 : System.Buffers [4.5.1, )' from 'xxx'.
NuGet.Protocol.Core.Types.FatalProtocolException: Error downloading 'LiteDB.5.0.21 : System.Buffers [4.5.1, )' from 'xxx'. ---> NuGet.Packaging.Signing.SignatureException
   at NuGet.Packaging.PackageExtractor.<VerifyPackageSignatureAsync>d__9.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.Packaging\PackageExtractor.cs:line 1073
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.Packaging.PackageExtractor.<>c__DisplayClass3_2.<<InstallFromSourceAsync>b__0>d.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.Packaging\PackageExtractor.cs:line 520
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__5`1.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.Common\ConcurrencyUtilities.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__5`1.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.Common\ConcurrencyUtilities.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Packaging.PackageExtractor.<InstallFromSourceAsync>d__3.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.Packaging\PackageExtractor.cs:line 390
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.GlobalPackagesFolderUtility.<AddPackageAsync>d__3.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.Protocol\Utility\GlobalPackagesFolderUtility.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.GetDownloadResultUtility.<>c__DisplayClass3_0.<<GetDownloadResultAsync>b__0>d.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.Protocol\Utility\GetDownloadResultUtility.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass18_0`1.<<ProcessStreamAsync>b__0>d.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.Protocol\HttpSource\HttpSource.cs:line 252
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__20`1.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.Protocol\HttpSource\HttpSource.cs:line 291
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.HttpSource.<ProcessStreamAsync>d__18`1.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.Protocol\HttpSource\HttpSource.cs:line 239
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.GetDownloadResultUtility.<GetDownloadResultAsync>d__3.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.Protocol\Utility\GetDownloadResultUtility.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.V2FeedParser.<DownloadFromUrl>d__44.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.Protocol\LegacyFeed\V2FeedParser.cs:line 275
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.DownloadResourceV2Feed.<GetDownloadResourceResultAsync>d__4.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.Protocol\LegacyFeed\DownloadResourceV2Feed.cs:line 76
   --- End of inner exception stack trace ---
   at NuGet.Protocol.DownloadResourceV2Feed.<GetDownloadResourceResultAsync>d__4.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.Protocol\LegacyFeed\DownloadResourceV2Feed.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.PackageManagement\PackageDownloader.cs:line 302
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.PackageManagement.PackagePreFetcher.<>c__DisplayClass0_1.<<GetPackagesAsync>b__4>d.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.PackageManagement\PackagePreFetcher.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.PackageManagement.PackagePreFetcherResult.<EnsureResultAsync>d__24.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.PackageManagement\PackagePreFetcherResult.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.PackagePreFetcherResult.<GetResultAsync>d__25.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.PackageManagement\PackagePreFetcherResult.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__87.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.PackageManagement\NuGetPackageManager.cs:line 2655
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__87.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.PackageManagement\NuGetPackageManager.cs:line 2691
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__87.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.PackageManagement\NuGetPackageManager.cs:line 2823
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__53.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Core\NuGet.PackageManagement\NuGetPackageManager.cs:line 449
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.CommandLine.InstallCommand.<InstallPackageAsync>d__38.MoveNext() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Clients\NuGet.CommandLine\Commands\InstallCommand.cs:line 403
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.CommandLine.Command.Execute() in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Clients\NuGet.CommandLine\Commands\Command.cs:line 182
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args) in C:\Temp\nuget\NuGet.Client-dev\src\NuGet.Clients\NuGet.CommandLine\Program.cs:line 166
```
dotnet restore

```console
                   "C:\Temp\Temp.csproj" (Restore target) (1) ->
                   (Restore target) ->
                     C:\Temp\Temp.csproj : warning NU3012: Package 'LiteDB 5.0.21' from source 'xxx': The author primary signature found a chain building issue: CtlNotValidForUsage: The certificate is not valid for the requested usage.
                     C:\Temp\Temp.csproj : warning NU3012: Package 'LiteDB 5.0.21' from source 'xxxx': The author primary signature found a chain building issue: NotValidForUsage: The certificate is not valid for the requested usage.


                   "C:\Temp\Temp.csproj" (Restore target) (1) ->
                   (Restore target) ->
                     C:\Program Files\dotnet\sdk\8.0.303\NuGet.targets(169,5): error MSB4181: The "RestoreTask" task returned false but did not log an error. [C:\Temp\Temp.cspr
                   oj]

    2 Warning(s)
    1 Error(s)
```

dotnet add package litedb

```console
info : Package 'LiteDB 5.0.21' from source 'xxx': Verifying author primary signature's timestamp with timestamping service certificate:
info :   Subject Name: CN=DigiCert Timestamp 2023, O="DigiCert, Inc.", C=US
info :   SHA1 hash: 66F02B32C2C2C90F825DCEAA8AC9C64F199CCF40
info :   SHA256 hash: D2F6E46DED7422CCD1D440576841366F828ADA559AAE3316AF4D1A9AD40C7828
info :   Issued by: CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA, O="DigiCert, Inc.", C=US
info :   Valid from: 7/14/2023 12:00:00 AM to 10/13/2034 11:59:59 PM
info : Package 'litedb' is compatible with all the specified frameworks in project 'C:\Temp\Temp.csproj'.
error: Value cannot be null. (Parameter 'path1')
```

**Comment by Nigusu-Allehu** [comment]
Thank you for taking the time to report this and for providing detailed information. Unfortunately, accept mode does not permit bypassing invalid or incomplete certificate chains. As you described, it ensures that all signatures and certificates are valid. Due to the certificate chain issues in your Windows Server environment, the signature validation process fails. [More on SignatureValidationMode](https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-Package-Signing-Client-Policy#accept-mode--) And [more](https://github.com/NuGet/Home/wiki/Repository-Signatures#client-policies)

**Comment by Ilchert** [comment]
Hello @Nigusu-Allehu 
A Certificate Trust List is a collection of trusted certificates distributed by Microsoft, typically utilized in closed environments with stringent policies. Although Microsoft signs this list and it should function correctly, issues arise. To resolve such problems, one must manually install the trusted root certificates package from all available packages. 

Can we convert this issue to feature request or somehow ignore key usage errors? Technically certificate is valid, just has issue with  detecting usage.


![image](https://github.com/user-attachments/assets/60ea6b6c-9c35-4445-aa8d-fec567a88697)

**Comment by nkolev92** [comment]
Closing per the previous comment. More information: https://learn.microsoft.com/en-us/nuget/consume-packages/installing-signed-packages.
