### ISSUE TITLE
Nuget: Central Directory corrupt

### ISSUE THREAD

**Issue by jeffschwMSFT** [NuGet/Home#13711]
### NuGet Product Used

dotnet.exe

### Product Version

.NET 9 Preview

### Worked before?

yes

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Full details can be found here https://github.com/dotnet/dnceng/issues/3099

```
  Restored D:\a\_work\1\s\src\libraries\externals.csproj (in 1.01 sec).
D:\a\_work\1\s\.dotnet\sdk\9.0.100-preview.5.24307.3\NuGet.RestoreEx.targets(19,5): error : Central Directory corrupt. [D:\a\_work\1\s\Build.proj]
D:\a\_work\1\s\.dotnet\sdk\9.0.100-preview.5.24307.3\NuGet.RestoreEx.targets(19,5): error :    at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory() [D:\a\_work\1\s\Build.proj]
D:\a\_work\1\s\.dotnet\sdk\9.0.100-preview.5.24307.3\NuGet.RestoreEx.targets(19,5): error :    at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding) [D:\a\_work\1\s\Build.proj]
D:\a\_work\1\s\.dotnet\sdk\9.0.100-preview.5.24307.3\NuGet.RestoreEx.targets(19,5): error :    at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding) [D:\a\_work\1\s\Build.proj]
D:\a\_work\1\s\.dotnet\sdk\9.0.100-preview.5.24307.3\NuGet.RestoreEx.targets(19,5): error :    at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen) [D:\a\_work\1\s\Build.proj]
D:\a\_work\1\s\.dotnet\sdk\9.0.100-preview.5.24307.3\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Packaging.PackageArchiveReader..ctor(Stream stream, Boolean leaveStreamOpen, IFrameworkNameProvider frameworkProvider, IFrameworkCompatibilityProvider compatibilityProvider) [D:\a\_work\1\s\Build.proj]
D:\a\_work\1\s\.dotnet\sdk\9.0.100-preview.5.24307.3\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Packaging.PackageArchiveReader..ctor(Stream stream) [D:\a\_work\1\s\Build.proj]
D:\a\_work\1\s\.dotnet\sdk\9.0.100-preview.5.24307.3\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Protocol.RemotePackageArchiveDownloader.GetPackageReader() [D:\a\_work\1\s\Build.proj]
D:\a\_work\1\s\.dotnet\sdk\9.0.100-preview.5.24307.3\NuGet.RestoreEx.targets(19,5): error :    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode) [D:\a\_work\1\s\Build.proj]
D:\a\_work\1\s\.dotnet\sdk\9.0.100-preview.5.24307.3\NuGet.RestoreEx.targets(19,5): error :    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode) [D:\a\_work\1\s\Build.proj]

```

**Comment by Nigusu-Allehu** [comment]
Thank for reaching out! 
You have a link to a build in the referenced dceng issue. However, I am not able to access it (it doesn't exist anymore). 

Just by looking at the error, my guess is, maybe there is a corrupt nupkg being used by your project.

Is it possible to provide some sort of repro step or a build we could look into?

**Comment by jeffschwMSFT** [comment]
this is part of the netcoreapp build (for .NET Core).  We see this issue ~daily in our build.  there are constant changes, but less likely that it is a corrupt package.  I do not have a standalone repro

**Comment by nkolev92** [comment]
Continuing some of this discussion via e-mail. 

Regardless of the root problem, I think there's an opportunity for improving the logging here, since the log message doesn't even tell us what package is corrupt.

**Comment by br-43** [comment]
I reproduce the same issue after upgrading from .NET 8 to .NET 10; my repo forces `<SelfConatined>true</SelfConatined>` and it seems to be causing this issue
```txt
C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(196,5): error : Central Directory corrupt. [X:\path\BuildPackages.proj]
C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(196,5): error :   An attempt was made to move the file pointer before the beginning of the file. [X:\path\BuildPackages.proj]
```
With this snippet from the .binlog
```txt
System.IO.InvalidDataException: Central Directory corrupt. ---> System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   --- End of inner exception stack trace ---
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at NuGet.Protocol.RemotePackageArchiveDownloader.GetPackageReader()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at NuGet.Protocol.RemotePackageArchiveDownloader.get_SignedPackageReader()
   at NuGet.Packaging.PackageExtractor.<>c__DisplayClass5_0.<<InstallFromSourceAsync>b__0>d.MoveNext()
```

In my global cache I see uncomplete download of packages `microsoft.windowsdesktop.app.runtime.win-x64\10.0.5` & `microsoft.aspnetcore.app.runtime.win-x64\10.0.5`. I don't think it is the size of these packages that fails my build since we have internal packages with 1GB.

**Environment**: 
In our CI/CD pipeline we install Visual Studio Build Tools 2026, and we invoke the restore & build through MSBuild (`C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\MSBuild\Current\Bin\amd64\MSBuild.exe`)

**Comment by br-43** [comment]
> I reproduce the same issue after upgrading from .NET 8 to .NET 10; my repo forces `<SelfConatined>true</SelfConatined>` and it seems to be causing this issue
[...]

I have fixed this by setting `<RestoreCleanupAssetsForUnsupportedProjects>false</RestoreCleanupAssetsForUnsupportedProjects>` as it seems my Traversal project files caused the failure with `SelfConatined` set to true.
Let me know if you need a reproduction repo for investigation.
