### ISSUE TITLE
Tests PushCommand_PushToServer_GetCredentialFromPlugin and NuGet.CommandLine.Test.NuGetPushCommandTest.PushCommand_PushToServerBasicAuth are flaky

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#13721]
Test: `NuGet.CommandLine.Test.NuGetPushCommandTest.PushCommand_PushToServer_GetCredentialFromPlugin`

# Error message
```
System.TimeoutException : D:\a_work\1\s\test\NuGet.Clients.Tests\NuGet.CommandLine.Test\bin\Debug\net472\NuGet\NuGet.exe push D:\a_work\1\s.test\work\069e972e\32b73562\testPackage1.1.1.0.nupkg -Source http://localhost:51787/177ea0de-4a2f-4569-895b-83147357bd3a/nuget timed out after 10.03 seconds
```

# Stack trace
```
   at NuGet.Test.Utility.RetryRunner.RunWithRetries[T,E](Func`1 func, Int32 maxRetries, ITestOutputHelper logger) in D:\a\_work\1\s\test\TestUtilities\Test.Utility\RetryRunner.cs:line 29
   at NuGet.Test.Utility.CommandRunner.Run(String filename, String workingDirectory, String arguments, Int32 timeOutInMilliseconds, Action`1 inputAction, IDictionary`2 environmentVariables, ITestOutputHelper testOutputHelper, Int32 timeoutRetryCount) in D:\a\_work\1\s\test\TestUtilities\Test.Utility\CommandRunner.cs:line 32
   at NuGet.CommandLine.Test.NuGetPushCommandTest.PushCommand_PushToServer_GetCredentialFromPlugin() in D:\a\_work\1\s\test\NuGet.Clients.Tests\NuGet.CommandLine.Test\NuGetPushCommandTest.cs:line 975
```

This test does not capture output 😢

**Comment by nkolev92** [comment]
Replacing https://github.com/NuGet/Client.Engineering/issues/2929 and https://github.com/NuGet/Client.Engineering/issues/2965
