### ISSUE TITLE
NRE retrieving package metadata from nuget.org feed

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#13804]
### NuGet Product Used

NuGet SDK

### Product Version

6.11.0

### Impact

I'm unable to use this version

### Repro Steps & Context

```csharp
#r "nuget: NuGet.Protocol, 6.11.0"

using NuGet.Configuration;
using NuGet.Protocol.Core.Types;

var repository = new SourceRepository(new PackageSource("https://api.nuget.org/v3/index.json"), Repository.Provider.GetCoreV3());
var resource = await repository.GetResourceAsync<PackageMetadataResource>();

var metadata = await resource.GetMetadataAsync("Uno.WinUI.Runtime.Skia.Wpf", false, false, 
    new SourceCacheContext(), NuGet.Common.NullLogger.Instance, CancellationToken.None);
```

Throws as follows:

```
   at NuGet.Protocol.PackageMetadataResourceV3.ProcessRegistrationPage(RegistrationPage registrationPage, List`1 results, VersionRange range, Boolean includePrerelease, Boolean includeUnlisted, MetadataReferenceCache metadataCache)
   at NuGet.Protocol.PackageMetadataResourceV3.GetMetadataAsync(String packageId, Boolean includePrerelease, Boolean includeUnlisted, VersionRange range, SourceCacheContext sourceCacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3.GetMetadataAsync(String packageId, Boolean includePrerelease, Boolean includeUnlisted, SourceCacheContext sourceCacheContext, ILogger log, CancellationToken token)
   at Program.<Main>$(String[] args) in C:\Users\dev\AppData\Local\Temp\roslynpad\build\f6b45e491fed44ce87ff7a925cf3aa27\Program.cs:line 9
   at Program.<Main>(String[] args)
```

NOTE: this fails regardless of where the code runs: unit test, console app, etc. I just used RoslynPad to verify outside of my scenario.

**Comment by kzu** [comment]
Seems like it was transient, but kinda weird for it to fail :/. I added Polly around that exception too now.
