### ISSUE TITLE
NuGet Fails in Containers When HOME Is Not Set

### ISSUE THREAD

**Issue by kasperk81** [NuGet/Home#13834]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK:  Version:           9.0.100-rc.2.24468.2  Commit:            c204043de1  Workload version:  9.0.100-manifests.47de87af  MSBuild version:   17.12.0-preview-24467-02+988196b1c

### Worked before?

No

### Impact

It bothers me. A fix would be nice

#### Problem

When running NuGet commands inside a container environment where the HOME environment variable is not set, NuGet fails with the following error, while other .NET SDK commands work as expected. The failure is caused by NuGet not having a fallback to SpecialFolder.UserProfile, unlike other SDK commands that already handle this scenario.

#### Proposed Solution

NuGet already uses the UserProfile fallback for the full .NET Framework. This issue proposes extending the same fallback logic for CoreCLR to align the behavior of NuGet commands with other SDK tools.

The proposed PR adds the fallback behavior to NuGetEnvironment.GetFolderPath, allowing it to retrieve the correct user profile path even when HOME is not set, preventing failures in containerized environments.
Example of Working Behavior (from .NET SDK):

Other SDK commands use the following fallback to handle the absence of HOME:

    [Link to SDK Code Reference](https://github.com/dotnet/sdk/blob/c3a8f72/src/Common/CliFolderPathCalculatorCore.cs#L38-L38)

#### Why This Change Is Important

    Consistency: Aligns the behavior of NuGet with other SDK tools.
    Usability: Improves the developer experience when working inside containerized environments, avoiding the need to manually set environment variables.

### Verbose Logs

```shell
The "WarnForInvalidProjectsTask" task failed unexpectedly.
  System.InvalidOperationException: Required environment variable 'HOME' is not set. Try setting 'DOTNET_CLI_HOME' or 'HOME' and running the operation
     at NuGet.Common.NuGetEnvironment.GetValueOrThrowMissingEnvVarsDotnet(Func`1 getValue, String home, String dotnetHome)
     at NuGet.Common.NuGetEnvironment.GetHome()
     at NuGet.Common.NuGetEnvironment.<>c.<.cctor>b__20_0()
     at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
     at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
     at System.Lazy`1.CreateValue()
     at NuGet.Common.NuGetEnvironment.GetFolderPath(SpecialFolder folder)
     at NuGet.Common.NuGetEnvironment.GetFolderPath(NuGetFolderPath folder)
     at NuGet.Common.PathUtility.CheckIfFileSystemIsCaseInsensitive()
     at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
     at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
     at System.Lazy`1.CreateValue()
     at NuGet.Common.PathUtility.get_IsFileSystemCaseInsensitive()
     at NuGet.Common.PathUtility.GetStringComparerBasedOnOS()
     at NuGet.Build.Tasks.WarnForInvalidProjectsTask.Execute()
     at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
     at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```
```

**Comment by zivkan** [comment]
Thanks for the contribution, @kasperk81!

This will be available starting from the .NET 9.0.200 SDK, if you use a [manual or scripted install](https://learn.microsoft.com/dotnet/core/install/linux-scripted-manual), or if you use the packages from packages.microsoft.com. If you use distro-built versions of the .NET SDK, then it won't be available until the .NET 10.0.100 SDK, since they only take `.1xx` branches of the .NET SDK.
