### ISSUE TITLE
Null ref exception in NuGet.DependencyResolver.RemoteDependencyWalker.IsGreaterThanOrEqualTo

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1384]
The below packages cause a null reference exception during project.json restores for UWP.
- Moon.Owin.Localization 1.3.1
- Moon.Owin.Localization 1.3.3
- Moon.Web.Localization 1.3.3
- IX.Framework.Engines.Embedding.Implementation.Autofac 1.1.3.1

```
System.NullReferenceException: Object reference not set to an instance of an object.
at NuGet.DependencyResolver.RemoteDependencyWalker.IsGreaterThanOrEqualTo(VersionRange nearVersion, VersionRange farVersion)
in C:\\src\\NuGet3\\src\\NuGet.DependencyResolver.Core\\Remote\\RemoteDependencyWalker.cs:line 171
at NuGet.DependencyResolver.GraphOperations.<>c__DisplayClass2_0`1.<CheckCycleAndNearestWins>b__0(GraphNode`1 node) in C:\\src\\NuGet3\\src\\NuGet.DependencyResolver.Core\\GraphModel\\GraphOperations.cs:line 83
at NuGet.DependencyResolver.GraphOperations.<>c__DisplayClass9_0`1.<ForEach>b__0(GraphNode`1 node, Int32 _) in C:\\src\\NuGet3\\src\\NuGet.DependencyResolver.Core\\GraphModel\\GraphOperations.cs:line 327
at NuGet.DependencyResolver.GraphOperations.ForEach[TItem,TState](GraphNode`1 root, TState state, Func`3 visitor) in C:\\src\\NuGet3\\src\\NuGet.DependencyResolver.Core\\GraphModel\\GraphOperations.cs:line 306
at NuGet.DependencyResolver.GraphOperations.ForEach[TItem](GraphNode`1 root, Action`1 visitor) in C:\\src\\NuGet3\\src\\NuGet.DependencyResolver.Core\\GraphModel\\GraphOperations.cs:line 325
at NuGet.DependencyResolver.GraphOperations.CheckCycleAndNearestWins[TItem](GraphNode`1 root, List`1 downgrades, List`1 cycles) in C:\\src\\NuGet3\\src\\NuGet.DependencyResolver.Core\\GraphModel\\GraphOperations.cs:line 57
at NuGet.DependencyResolver.GraphOperations.Analyze[TItem](GraphNode`1 root) in C:\\src\\NuGet3\\src\\NuGet.DependencyResolver.Core\\GraphModel\\GraphOperations.cs:line 26
at NuGet.Commands.RestoreTargetGraph.Create(Boolean writeToLockFile, RuntimeGraph runtimeGraph, IEnumerable`1 graphs, RemoteWalkContext context, ILogger log, NuGetFramework framework, String runtimeIdentifier) in C:\\src\\NuGet3\\src\\NuGet.Commands\\RestoreGraph.cs:line 106
```

**Comment by RanjiniM** [comment]
Fixed and added test - f4f5b33965d90a0cb4ef65c5086c6fff63db1df4
