### ISSUE TITLE
Test:  `NuGet.PackageManagement.VisualStudio.Test.TelemetryOnceEmitterTests.EmitIfNeeded_MultipleThreads_EmitsOnceAsync` fails

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#13920]
This test failed 3 times in a row in a CI build:

```
 NuGet.PackageManagement.VisualStudio.Test.TelemetryOnceEmitterTests.EmitIfNeeded_MultipleThreads_EmitsOnceAsync [FAIL]
    Failed NuGet.PackageManagement.VisualStudio.Test.TelemetryOnceEmitterTests.EmitIfNeeded_MultipleThreads_EmitsOnceAsync [261 ms]
    Error Message:
     Assert.Equal() Failure: Values differ
  Expected: 1
  Actual:   0
    Stack Trace:
       at NuGet.PackageManagement.VisualStudio.Test.TelemetryOnceEmitterTests.<EmitIfNeeded_MultipleThreads_EmitsOnceAsync>d__5.MoveNext() in D:\a\_work\1\s\test\NuGet.Clients.Tests\NuGet.PackageManagement.VisualStudio.Test\Telemetry\TelemetryOnceEmitterTests.cs:line 81
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Standard Output Messages:
   2919 Created
   2921 Created
   2922 Created
   2923 Created
   2924 Created
```

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/pull/6417
