### ISSUE TITLE
dotnet tool restore fails on Linux with System.ArgumentException: "" is invalid version string

### ISSUE THREAD

**Issue by forki** [NuGet/Home#13921]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet 9.0.100

### Worked before?

8.x.y

### Impact

I'm unable to use this version

### Repro Steps & Context

After upgrade to .NET 9 the dotnet tool command fails on Linux but still works on Windows. 

Here is a minimal repro and the stacktrace

[dotnet-tools.json](https://github.com/user-attachments/files/17731461/dotnet-tools.json)
[global.json](https://github.com/user-attachments/files/17731466/global.json)

```
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "fantomas": {
      "version": "6.2.3",
      "commands": [
        "fantomas"
      ],
      "rollForward": false
    }
  }
}

```

error:
```

Unhandled exception: System.ArgumentException: "" ist keine gültige Versionszeichenfolge.
   at NuGet.Versioning.VersionRange.Parse(String value, Boolean allowFloating)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at NuGet.Protocol.PackageMetadataResourceV3.DeserializeStreamDataAsync[T](Stream stream, CancellationToken token)
   at NuGet.Protocol.HttpSource.<>c__DisplayClass[15](https://gitlab/a-team/stream/-/jobs/1849400#L15)_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3.GetMetadataAsync(String packageId, Boolean includePrerelease, Boolean includeUnlisted, VersionRange range, SourceCacheContext sourceCacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3.GetMetadataAsync(String packageId, Boolean includePrerelease, Boolean includeUnlisted, SourceCacheContext sourceCacheContext, ILogger log, CancellationToken token)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetPackageMetadataAsync(PackageSource source, String packageIdentifier, Boolean includePrerelease, Boolean includeUnlisted, CancellationToken cancellationToken)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetPackageMetadataAsync(String packageIdentifier, NuGetVersion packageVersion, IEnumerable`1 sources, CancellationToken cancellationToken, Boolean includeUnlisted)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetPackageSourceAndVersion(PackageId packageId, NuGetVersion packageVersion, PackageSourceLocation packageSourceLocation, Boolean includePreview, Boolean includeUnlisted, PackageSourceMapping packageSourceMapping)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.DownloadPackageAsync(PackageId packageId, NuGetVersion packageVersion, PackageSourceLocation packageSourceLocation, Boolean includePreview, Nullable`1 includeUnlisted, Nullable`1 downloadFolder, PackageSourceMapping packageSourceMapping)
   at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.DownloadAndExtractPackage(PackageId packageId, INuGetPackageDownloader nugetPackageDownloader, String packagesRootPath, NuGetVersion packageVersion, PackageSourceLocation packageSourceLocation, Boolean includeUnlisted)
   at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.<>c__DisplayClass8_0.<InstallPackage>b__0()
   at Microsoft.DotNet.Cli.TransactionalAction.Run[T](Func`1 action, Action commit, Action rollback)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
   at System.Linq.Enumerable.ArraySelectIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.ArraySelectIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at System.CommandLine.ParseResult.Invoke()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

**Comment by aklefdal** [comment]
I found the bug as well. Fortunately just a hobby project. Tried different dotnet tools (Fantomas, Paket, outdated), all with same result.
Rolled back to net8.0.

**Comment by sailro** [comment]
You can repro the exact same issue using the `dotnet list` command:

`dotnet list full/path/to/solution package --vulnerable --include-transitive`

In my case (on Windows):

```
dotnet list full/path/to/solution package --vulnerable --include-transitive
warn : An invalid cache entry was found for URL 'https://api.nuget.org/v3/registration5-gz-semver2/yamldotnet/page/2.3.0-rc/3.9.0-pre239.json' and will be replaced.
warn : '' is not a valid version string.
error: '' is not a valid version string.
```

While when using net 8.0, absolutely no issue at all.

So I fear this bug is bigger than a simple dotnet tool issue, and not OS-specific.

**Comment by forki** [comment]
Yes I just had a dotnet build error with same issue. But couldn't reproduce. So I assume it was during restore phase

**Comment by Lanayx** [comment]
It fails for me with fantomas on windows as well, so it's not a linux-only issue

**Comment by SimonCropp** [comment]
i have the same for bogus. package url https://api.nuget.org/v3/registration5-gz-semver2/bogus/page/2.1.4/18.0.1.json

my suspicion is that the above has `"minClientVersion":""` and nuget is not checking for empty string

**Comment by SimonCropp** [comment]
@Bogus ☝🏻

**Comment by jebriede** [comment]
I'm able to reproduce the issue with `dotnet tool restore` on Windows. Marking as ready for triage.

I was not able to reproduce it with the `dotnet list` command mentioned [in this comment](https://github.com/NuGet/Home/issues/13921#issuecomment-2474753677). @sailro please let us know if there's something different about the `dotnet list` repro from what was reported.

**Comment by pcshrosbree** [comment]
This dotnet-tools.json fails with `Unhandled exception: System.ArgumentException: '' is not a valid version string.`:

```JSON
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "dotnet-fsharplint": {
      "version": "0.24.3--date20240609-0921.git-873d145",
      "commands": [
        "dotnet-fsharplint"
      ],
      "rollForward": false
    },
    "fable": {
      "version": "4.23.0",
      "commands": [
        "fable"
      ],
      "rollForward": false
    },
    "fantomas": {
      "version": "6.3.16",
      "commands": [
        "fantomas"
      ],
      "rollForward": false
    },
    "fsdocs-tool": {
      "version": "21.0.0-beta-003",
      "commands": [
        "fsdocs"
      ],
      "rollForward": false
    },
    "fsharp-analyzers": {
      "version": "0.25.0",
      "commands": [
        "fsharp-analyzers"
      ],
      "rollForward": false
    }
  }
}
```

But this one, which has only fantomas removed, succeeds:

```JSON
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "dotnet-fsharplint": {
      "version": "0.24.3--date20240609-0921.git-873d145",
      "commands": [
        "dotnet-fsharplint"
      ],
      "rollForward": false
    },
    "fable": {
      "version": "4.23.0",
      "commands": [
        "fable"
      ],
      "rollForward": false
    },
    "fsdocs-tool": {
      "version": "21.0.0-beta-003",
      "commands": [
        "fsdocs"
      ],
      "rollForward": false
    },
    "fsharp-analyzers": {
      "version": "0.25.0",
      "commands": [
        "fsharp-analyzers"
      ],
      "rollForward": false
    }
  }
}
```

So it works for several packages, but not fantomas.

**Comment by robindv** [comment]
Related to https://github.com/dotnet/sdk/issues/44838 ?

**Comment by sailro** [comment]
> I'm able to reproduce the issue with `dotnet tool restore` on Windows. Marking as ready for triage.
> 
> I was not able to reproduce it with the `dotnet list` command mentioned [in this comment](https://github.com/NuGet/Home/issues/13921#issuecomment-2474753677). @sailro please let us know if there's something different about the `dotnet list` repro from what was reported.

@jebriede: I created and attached a minimal repro for you:
[repro.zip](https://github.com/user-attachments/files/17744156/repro.zip)

run:

`dotnet restore .\ComponentGovernance.sln`

then

`dotnet list C:\full\path\to\ComponentGovernance.sln package --vulnerable --include-transitive`

You'll hit:

```
warn : An invalid cache entry was found for URL 'https://api.nuget.org/v3/registration5-gz-semver2/yamldotnet/page/2.3.0-rc/3.9.0-pre239.json' and will be replaced.
warn : '' is not a valid version string.
error: '' is not a valid version string.
```

**Comment by aetos382** [comment]
There is a method called `NuGet.Versioning.VersionRange.Parse(String value, Boolean allowFloating)` at the top of the stack trace, so I think it is probably failed to parse the version range of the dependent package.

YamlDotNet version 3.8 has the following dependencies.
This `"range": ""` cannot be parsed.

```json
"dependencyGroups": [
  {
    "@id": "https://api.nuget.org/v3/catalog0/data/2021.02.02.12.12.44/yamldotnet.3.8.0-pre143.json#dependencygroup/.netplatform5.0",
    "@type": "PackageDependencyGroup",
    "dependencies": [
      {
        "@id": "https://api.nuget.org/v3/catalog0/data/2021.02.02.12.12.44/yamldotnet.3.8.0-pre143.json#dependencygroup/.netplatform5.0/system.collections",
        "@type": "PackageDependency",
        "id": "System.Collections",
        "range": "",
        "registration": "https://api.nuget.org/v3/registration5-gz-semver2/system.collections/index.json"
      }
    ],
    "targetFramework": ".NETPlatform5.0"
  }
]
```

**Comment by Numpsy** [comment]
> There is a method called NuGet.Versioning.VersionRange.Parse(String value, Boolean allowFloating) at the top of the stack trace, so I think it is probably failed to parse the version range of the dependent package.

Is this the same as the already closed https://github.com/NuGet/Home/issues/13869 or something else in the same area?

**Comment by BlairLeduc** [comment]
> You can repro the exact same issue using the `dotnet list` command:
> 
> `dotnet list full/path/to/solution package --vulnerable --include-transitive`
> 
> In my case (on Windows):
> 
> ```
> dotnet list full/path/to/solution package --vulnerable --include-transitive
> warn : An invalid cache entry was found for URL 'https://api.nuget.org/v3/registration5-gz-semver2/yamldotnet/page/2.3.0-rc/3.9.0-pre239.json' and will be replaced.
> warn : '' is not a valid version string.
> error: '' is not a valid version string.
> ```
> 
> While when using net 8.0, absolutely no issue at all.
> 
> So I fear this bug is bigger than a simple dotnet tool issue, and not OS-specific.

Diagnostics of this failure that I too am also experiencing with YamlDotNet:
```
  OK https://api.nuget.org/v3/registration5-gz-semver2/yamldotnet/page/2.3.0-rc/3.9.0-pre239.json 26ms
error: '' is not a valid version string.
trace: System.AggregateException: One or more errors occurred. ('' is not a valid version string.)
trace:  ---> System.ArgumentException: '' is not a valid version string.
trace:    at NuGet.Versioning.VersionRange.Parse(String value, Boolean allowFloating)
trace:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
```

I also agree with @SimonCropp. This json file also contains lines with  `"minClientVersion":""`.

**Comment by pcshrosbree** [comment]
> There is a method called `NuGet.Versioning.VersionRange.Parse(String value, Boolean allowFloating)` at the top of the stack trace, so I think it is probably failed to parse the version range of the dependent package.

The [fantomas package](https://www.nuget.org/packages/fantomas/7.0.0-alpha-002) has no dependencies, but still triggers the issue, so while there may be a problem parsing dependents, it is not the only problem.

**Comment by nojaf** [comment]
Hi there! I'm the maintainer of Fantomas. At one point, Fantomas was a class library rather than a tool. The name `Fantomas` was reused for the tool, and the library was renamed to `Fantomas.Core`.

This change occurred years ago (in v4, it was a library, as seen here: https://www.nuget.org/packages/Fantomas/4.7.9). This may or may not be relevant.

If anyone notices a wrong configuration on our end, I’d appreciate the feedback. However, I believe we are following standard practices, and it was working well with the .NET 8 SDK.

**Comment by zivkan** [comment]
This is a duplicate of https://github.com/NuGet/Home/issues/13869 as @Numpsy asked about.

It's already in dotnet/sdk's release/9.0.1xx release, but we got the original bug report too late to make it into 9.0.100, so it will be released whenever 9.0.101 does.

fyi @baronfel and @marcpopMSFT regarding customer impact.

It affects `dotnet tool`, but also `dotnet package search --exact-match` and `dotnet list package`, when any version of a package id had at any point in time a dependency without a version. If there are any other scenarios that use nuget.org's "registration resource" (package metadata), it will be affected as well.  Restore does not use the registration resource, so restore is not affected.

**Comment by martinsuchan** [comment]
Just had the same issue in our project, repro is simple:
- add "castle.core" version "5.1.1" to your project
- try running `dotnet list .\projectname.csproj package --vulnerable --include-transitive`
- warn : An invalid cache entry was found for URL 'https://api.nuget.org/v3/registration5-gz-semver2/castle.core/index.json' and will be replaced.

**Comment by aetos382** [comment]
When I run the command `dotnet tool update fantomas -v diag` in a project that has installed
 [fantomas](https://www.nuget.org/packages/fantomas), an exception is thrown while parsing the contents of [this file](https://api.nuget.org/v3/registration5-gz-semver2/fantomas/page/0.8.0/3.0.0-beta-005.json).

This includes information about [v1.0.5](https://www.nuget.org/packages/fantomas/1.0.5). This version has a dependency on `FSharp.Compiler.Service` without specifying a version range.

It seems that `dotnet` cli also retrieves historical information about installed packages. Therefore, it will occur even if there are no dependencies on the latest version.

If I run the `dotnet list package --vulnerable -v diag` command in a project that has [Newtonsoft.Json](https://www.nuget.org/packages/newtonsoft.json/) installed, this problem will not occur. [The file](https://api.nuget.org/v3/registration5-gz-semver2/newtonsoft.json/index.json) obtained at this time has `"minClientVersion": ""`, but does not have `"range": ""`.

**Comment by jeffkl** [comment]
Closing in favor of https://github.com/dotnet/sdk/issues/44838
