### ISSUE TITLE
VS 2015 update 5, Nuget fails to install

### ISSUE THREAD

**Issue by tombrown571** [NuGet/Home#1451]
I have been having problems with NuGet.  I am unable to uninstall it or update it. "The process cannot access the file because it is being used by another process." - same error in both cases

I have been blocked all day with this issue - Now just want to delete all traces of package manager from my system so I can load it properly.  Of course Ive tried rebooting etc.

I have tried: 
Admin command prompt VsixInstaller /u:NuGet2013 (fails)
Repairing VS 2013 - same problem still occurs.
Uninstalled and Reinstalling VS 2013:  VS reports Setup Completed, not all features installed - correctly "Microsoft NuGet - Visual Studio 2013 Package Failed"  - contact the package vendor.

From Visual Studio installation the log file:
[1298:1C20][2015-09-24T15:03:56]i000: MUX:  ExecutePackageBegin PackageId: nugetvs2013
[21F8:1E04][2015-09-24T15:03:56]i301: Applying execute package: nugetvs2013, action: Install, path: C:\ProgramData\Package Cache{060E4460-DD09-34A7-A3ED-7267EAA9920C}v2.8.60610.756\packages\WPT\NuGetVS2013.msi, arguments: ' ARPSYSTEMCOMPONENT="1" MSIFASTINSTALL="7"'
[1298:1C20][2015-09-24T15:04:11]i000: MUX:  ExecuteError: Package (nugetvs2013) failed: Error Message Id: 1722 ErrorMessage: There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  
[21F8:1E04][2015-09-24T15:04:11]e000: Error 0x80070643: Failed to install MSI package.
[21F8:1E04][2015-09-24T15:04:11]e000: Error 0x80070643: Failed to execute MSI package.
[1298:1C20][2015-09-24T15:04:11]e000: Error 0x80070643: Failed to configure per-machine MSI package.
[1298:1C20][2015-09-24T15:04:11]i000: MUX:  Installation size in bytes for package: nugetvs2013 MaxAppDrive: 0  MaxSysDrive: 242769920  AppDrive: 0  SysDrive: 239554560
[1298:1C20][2015-09-24T15:04:11]i000: MUX:  Return Code:0x80070643 Msi Messages:1722 Result Detail:0 Restart:None
[1298:1C20][2015-09-24T15:04:11]i000: MUX:  Set Result: Return Code=-2147023293 (0x80070643), Error Message=1722, Result Detail=, Vital=False, Package Action=Install, Package Id=nugetvs2013
[1298:1C20][2015-09-24T15:04:11]w350: Applied non-vital package: nugetvs2013, encountered error: 0x80070643. Continuing...

Other Symtoms:
Tools-> NuGet Package Manager menu item is not present
Extensions and updates reports NuGet as installed (V 2.8.60723.765) but it cannot be uninstalled or updated ("The process cannot access the file because it is being used by another process.")
When compiling a solution - packages are not autmatically downloaded
Right-click on references - there is no link to add package to project
Tools-> Options -> NuGet Package Manager Tab "An error occurred loading this property page"

Is there any way to clear this error?

**Comment by tombrown571** [comment]
Additional Data:  VSIXInstaller Log - attempt to install.

24/09/2015 16:25:47 - Microsoft VSIX Installer
24/09/2015 16:25:47 - -------------------------------------------
24/09/2015 16:25:47 - Initializing Install...
24/09/2015 16:25:47 - Extension Details...
24/09/2015 16:25:47 -   Identifier      : NuGet.67e54e40-0ae3-42c5-a949-fddf5739e6a5
24/09/2015 16:25:47 -   Name            : NuGet Package Manager for Visual Studio 2013
24/09/2015 16:25:47 -   Author          : Microsoft Corporation
24/09/2015 16:25:47 -   Version         : 2.8.60723.765
24/09/2015 16:25:47 -   Description     : A collection of tools to automate the process of downloading, installing, upgrading, configuring, and removing packages from a VS Project.
24/09/2015 16:25:47 -   Locale          : en-US
24/09/2015 16:25:47 -   MoreInfoURL     : http://docs.nuget.org/
24/09/2015 16:25:47 -   InstalledByMSI  : False
24/09/2015 16:25:47 -   SupportedFrameworkVersionRange : [4.0,4.5]
24/09/2015 16:25:47 - 
24/09/2015 16:25:48 -   SignedBy        : Microsoft Corporation
24/09/2015 16:25:48 -   Certificate Info : [Subject]
  CN=Microsoft Corporation, OU=MOPR, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

[Issuer]
  CN=Microsoft Code Signing PCA, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

[Serial Number]
  33000000FEEB02CCACAAEB9F780001000000FE

[Not Before]
  20/05/2015 18:30:50

[Not After]
  20/08/2016 18:30:50

[Thumbprint]
  3FF2B5272DA04778A97B10E39F2AE1774ABF0E25

24/09/2015 16:25:48 -   Supported Products : 
24/09/2015 16:25:48 -       Microsoft.VisualStudio.Pro
24/09/2015 16:25:48 -           Version : [12.0]
24/09/2015 16:25:48 -       Microsoft.VisualStudio.IntegratedShell
24/09/2015 16:25:48 -           Version : [12.0]
24/09/2015 16:25:48 -       Microsoft.VisualStudio.VWDExpress
24/09/2015 16:25:48 -           Version : [12.0]
24/09/2015 16:25:48 -       Microsoft.VisualStudio.VPDExpress
24/09/2015 16:25:48 -           Version : [12.0]
24/09/2015 16:25:48 -       Microsoft.VisualStudio.VSWinExpress
24/09/2015 16:25:48 -           Version : [12.0]
24/09/2015 16:25:48 -       Microsoft.VisualStudio.VSWinDesktopExpress
24/09/2015 16:25:48 -           Version : [12.0]
24/09/2015 16:25:48 - 
24/09/2015 16:25:48 -   References      : 
24/09/2015 16:25:48 - 
24/09/2015 16:25:48 - Searching for applicable products...
24/09/2015 16:25:48 - Found installed product - Microsoft Visual Studio Premium 2013
24/09/2015 16:25:49 - The extension will be upgraded from version 2.8.50313.46.
24/09/2015 16:25:49 - Found installed product - Microsoft Visual Studio Professional 2013
24/09/2015 16:25:49 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
24/09/2015 16:25:49 - Found installed product - Global Location
24/09/2015 16:25:49 - Found installed product - ssms
24/09/2015 16:25:53 - The following target products have been selected...
24/09/2015 16:25:53 -   Microsoft Visual Studio Premium 2013
24/09/2015 16:25:53 - 
24/09/2015 16:25:53 - Beginning to install extension to Microsoft Visual Studio Premium 2013...
24/09/2015 16:25:53 - Upgrading 'NuGet Package Manager for Visual Studio 2013', version 2.8.50313.46 to version 2.8.60723.765.
24/09/2015 16:25:54 - Install Error : System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.AtomicallyDeleteFiles(IEnumerable`1 filePaths, Boolean justMarkForDeletion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.DeleteDiscoverableFiles(IInstalledExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.UninstallInternal(IInstalledExtension extension, Boolean forceDelete)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CommitInstalledAndUninstalledExtensions(IEnumerable`1 installedExtensions, IEnumerable`1 uninstalledExtensions, IEnumerable`1 packComponentChanges)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)

**Comment by yishaigalatzer** [comment]
@tombrown571 I assume you mean Visual Studio 2013?

We plan to update NuGet to 2.9 later this week, I hope this will resolve your issue. If not please re-open and we can try and figure out what to do.

Alternatively can you please try the following?
Download the vsix, and close all instances of visual studio (devenv, vshost, etc).

Then double click on the vsix.

**Comment by yishaigalatzer** [comment]
This was identified as a visual studio issue, we have communicated it to the extensions team, and there is not much we can do in NuGet to fix it.

The bug was fixed in 2015 Update II, and I don't know of plans to fix it in 2013

**Comment by rwgbryant** [comment]
it's back in VS2015 Update 3.

**Comment by yishaigalatzer** [comment]
Thanks I'll share with the vs extensibility team

**Comment by Michael-Eng** [comment]
@rwgbryant  I work on the Visual Studio Extensibility team and would like to investigate your issue further. Can you please email me meng at microsoft.com? I'd like to find out more about the current state of your machine. Thanks!

**Comment by AdrianBathurst** [comment]
I have similar issue trying to install DotNetCore.1.0.0-VS2015Tools.Preview2.exe. I have VS2015 Update 3 installed.

Seems to fail on `NuGetVisualStudio14_rc2_39.msi`, see near the end of log below...

```
[1474:05B8][2016-07-14T12:07:39]i361: Created a system restore point.
[1474:05B8][2016-07-14T12:07:39]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{9b3936b0-e973-47b9-afb2-de7cd6501203}, resume: Active, restart initiated: No, disable resume: No
[1474:1950][2016-07-14T12:07:40]i304: Verified existing payload: SetupBlocked_Install at path: C:\ProgramData\Package Cache\7ec72441-2fd4-3ea7-b1a6-cf38c6ae4585\SetupBlocked_rc2_39.exe.
[1474:05B8][2016-07-14T12:07:40]i301: Applying execute package: SetupBlocked_Install, action: Install, path: C:\ProgramData\Package Cache\7ec72441-2fd4-3ea7-b1a6-cf38c6ae4585\SetupBlocked_rc2_39.exe, arguments: '"C:\ProgramData\Package Cache\7ec72441-2fd4-3ea7-b1a6-cf38c6ae4585\SetupBlocked_rc2_39.exe"'
[1474:1950][2016-07-14T12:07:40]i304: Verified existing payload: Preparation_Uninstall_ASPNET at path: C:\ProgramData\Package Cache\5509473c-af3f-3169-b338-51c82cc2f554\Preparation_rc2_39.exe.
[1474:1950][2016-07-14T12:07:40]i304: Verified existing payload: ANCM_IISExpress_x64 at path: C:\ProgramData\Package Cache\{C2BB4C41-59DC-487E-9CCF-1E21C3AC9139}v1.0.1967\packages\ancm_iis_express_x64_en_rc2_39.msi.
[1474:1950][2016-07-14T12:07:40]i304: Verified existing payload: DotNetVersionManager_x64 at path: C:\ProgramData\Package Cache\{4EC36977-42B9-3C18-A692-B9DEE7404484}v1.0.11123.0\packages\DotNetVersionManager-x64_rc1.msi.
[1C6C:1280][2016-07-14T12:07:40]i319: Applied execute package: SetupBlocked_Install, result: 0x0, restart: None
[1474:05B8][2016-07-14T12:07:40]i301: Applying execute package: Preparation_Uninstall_ASPNET, action: Install, path: C:\ProgramData\Package Cache\5509473c-af3f-3169-b338-51c82cc2f554\Preparation_rc2_39.exe, arguments: '"C:\ProgramData\Package Cache\5509473c-af3f-3169-b338-51c82cc2f554\Preparation_rc2_39.exe" /d'
[1C6C:1280][2016-07-14T12:07:40]i319: Applied execute package: Preparation_Uninstall_ASPNET, result: 0x0, restart: None
[1474:05B8][2016-07-14T12:07:40]i301: Applying execute package: ANCM_IISExpress_x64, action: Repair, path: C:\ProgramData\Package Cache\{C2BB4C41-59DC-487E-9CCF-1E21C3AC9139}v1.0.1967\packages\ancm_iis_express_x64_en_rc2_39.msi, arguments: ' ARPSYSTEMCOMPONENT="1" MSIFASTINSTALL="7"'
[1474:1950][2016-07-14T12:07:40]i304: Verified existing payload: AspNetCoreLocalFeed at path: C:\ProgramData\Package Cache\{4C42E682-080B-305F-B2D6-AC2DAB8F0853}v1.0.20624.0\packages\AspNetCoreLocalFeed_rc2_39.msi.
[1C6C:10F8][2016-07-14T12:07:40]w343: Prompt for source of package: NuGetVS14, payload: NuGetVS14, path: C:\Users\Adrian\Downloads\packages\NuGetVisualStudio14_rc2_39.msi
[1C6C:10F8][2016-07-14T12:07:40]i338: Acquiring package: NuGetVS14, payload: NuGetVS14, download from: https://download.microsoft.com/download/A/3/8/A38489F3-9777-41DD-83F8-2CBDFAB2520C/packages/NuGetVisualStudio14_rc2_39.msi
[1474:1950][2016-07-14T12:07:40]i305: Verified acquired payload: NuGetVS14 at path: C:\ProgramData\Package Cache\.unverified\NuGetVS14, moving to: C:\ProgramData\Package Cache\{08D9540E-77B1-37B3-909A-813DAA5523D0}v3.5.0.1484\packages\NuGetVisualStudio14_rc2_39.msi.
[1C6C:10F8][2016-07-14T12:07:40]w343: Prompt for source of package: NuGetVS14, payload: cabFB5D09005B6CCD7291B309F84DC6E0E2, path: C:\Users\Adrian\Downloads\packages\nuget14_VisualStudio.cab
[1C6C:10F8][2016-07-14T12:07:40]i338: Acquiring package: NuGetVS14, payload: cabFB5D09005B6CCD7291B309F84DC6E0E2, download from: https://download.microsoft.com/download/A/3/8/A38489F3-9777-41DD-83F8-2CBDFAB2520C/packages/nuget14_VisualStudio.cab
[1474:1950][2016-07-14T12:07:41]i305: Verified acquired payload: cabFB5D09005B6CCD7291B309F84DC6E0E2 at path: C:\ProgramData\Package Cache\.unverified\cabFB5D09005B6CCD7291B309F84DC6E0E2, moving to: C:\ProgramData\Package Cache\{08D9540E-77B1-37B3-909A-813DAA5523D0}v3.5.0.1484\packages\nuget14_VisualStudio.cab.
[1C6C:1280][2016-07-14T12:07:42]i319: Applied execute package: ANCM_IISExpress_x64, result: 0x0, restart: None
[1474:05B8][2016-07-14T12:07:42]i325: Registering dependency: {9b3936b0-e973-47b9-afb2-de7cd6501203} on package provider: IISExpress_AspNetCore_Module,x64, package: ANCM_IISExpress_x64
[1474:05B8][2016-07-14T12:07:42]i301: Applying execute package: DotNetVersionManager_x64, action: Repair, path: C:\ProgramData\Package Cache\{4EC36977-42B9-3C18-A692-B9DEE7404484}v1.0.11123.0\packages\DotNetVersionManager-x64_rc1.msi, arguments: ' MSIFASTINSTALL="7"'
[1474:1950][2016-07-14T12:07:42]i304: Verified existing payload: WebToolsExtensionsVS14 at path: C:\ProgramData\Package Cache\{7F0C6393-B732-3AFC-8633-7313EC76E4A9}v14.1.20624.0\packages\WebToolsExtensionsVS14_rc2_39.msi.
[1474:1950][2016-07-14T12:07:42]i304: Verified existing payload: DotNetToolsVS14 at path: C:\ProgramData\Package Cache\{E173E253-D82C-34A2-ABE2-5A55017B53B5}v14.1.20624.0\packages\DotNetToolsVS14_rc2_39.msi.
[1474:1950][2016-07-14T12:07:42]i304: Verified existing payload: Preparation_ASPNET at path: C:\ProgramData\Package Cache\c691a447-d7f4-34ee-ac0e-e7bec4bcdd78\Preparation_rc2_39.exe.
[1C6C:1280][2016-07-14T12:07:42]i319: Applied execute package: DotNetVersionManager_x64, result: 0x0, restart: None
[1474:05B8][2016-07-14T12:07:42]i325: Registering dependency: {9b3936b0-e973-47b9-afb2-de7cd6501203} on package provider: Microsoft.AspNet.DNVM_x64_ENU,v1, package: DotNetVersionManager_x64
[1474:05B8][2016-07-14T12:07:42]i301: Applying execute package: AspNetCoreLocalFeed, action: Repair, path: C:\ProgramData\Package Cache\{4C42E682-080B-305F-B2D6-AC2DAB8F0853}v1.0.20624.0\packages\AspNetCoreLocalFeed_rc2_39.msi, arguments: ' ARPSYSTEMCOMPONENT="1" MSIFASTINSTALL="7"'
[1C6C:1280][2016-07-14T12:08:03]i319: Applied execute package: AspNetCoreLocalFeed, result: 0x0, restart: None
[1474:05B8][2016-07-14T12:08:03]i325: Registering dependency: {9b3936b0-e973-47b9-afb2-de7cd6501203} on package provider: Microsoft.AspNet.ASPNETCORELOCALFEED_x86_ENU,v1.0.0-rc2-15775, package: AspNetCoreLocalFeed
[1474:05B8][2016-07-14T12:08:03]i323: Registering package dependency provider: {08D9540E-77B1-37B3-909A-813DAA5523D0}, version: 3.5.0.1484, package: NuGetVS14
[1474:05B8][2016-07-14T12:08:03]i301: Applying execute package: NuGetVS14, action: Install, path: C:\ProgramData\Package Cache\{08D9540E-77B1-37B3-909A-813DAA5523D0}v3.5.0.1484\packages\NuGetVisualStudio14_rc2_39.msi, arguments: ' ARPSYSTEMCOMPONENT="1" MSIFASTINSTALL="7" SKIP_SETUP="1"'
[1474:05B8][2016-07-14T12:08:08]e000: Error 0x80070643: Failed to install MSI package.
[1474:05B8][2016-07-14T12:08:08]e000: Error 0x80070643: Failed to execute MSI package.
[1C6C:1280][2016-07-14T12:08:08]e000: Error 0x80070643: Failed to configure per-machine MSI package.
[1C6C:1280][2016-07-14T12:08:08]i319: Applied execute package: NuGetVS14, result: 0x80070643, restart: None
[1C6C:1280][2016-07-14T12:08:08]e000: Error 0x80070643: Failed to execute MSI package.
[1474:05B8][2016-07-14T12:08:08]i329: Removed package dependency provider: {08D9540E-77B1-37B3-909A-813DAA5523D0}, package: NuGetVS14
[1474:05B8][2016-07-14T12:08:08]i351: Removing cached package: NuGetVS14, from path: C:\ProgramData\Package Cache\{08D9540E-77B1-37B3-909A-813DAA5523D0}v3.5.0.1484\
[1474:05B8][2016-07-14T12:08:08]i372: Session end, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{9b3936b0-e973-47b9-afb2-de7cd6501203}, resume: ARP, restart: None, disable resume: No
[1474:05B8][2016-07-14T12:08:08]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{9b3936b0-e973-47b9-afb2-de7cd6501203}, resume: ARP, restart initiated: No, disable resume: No
[1C6C:1280][2016-07-14T12:08:08]i399: Apply complete, result: 0x80070643, restart: None, ba requested restart:  No
```

**Comment by joeloff** [comment]
There will be separate log file for the NuGet MSI in %temp%, the file should be prefixed with dd_NetCoreTools that will shed more light on the failure

There should also be a corresponding vsixinstaller log in %temp%. Unfortunately, you'll need to find the correct one based on the timestamp/contents as the VSIX logs usually just get a GUID appended to the filename.

Could you please attach both the VSIX and MSI log for NuGet.

**Comment by AdrianBathurst** [comment]
Here are the logs.

I notice there is a reference to `C:\Program Files (x86)\NuGet\Visual Studio 2015\NuGet.Tools.vsix`, this does not exist, there is no NuGet directory at all.

I have NuGet v3.5.0.1484 already installed.

[logs.zip](https://github.com/NuGet/Home/files/364245/logs.zip)

**Comment by joeloff** [comment]
Thanks @AdrianBathurst The MSI usually drops the VSIX there before running the VSIXInstaller on it to install NuGet.

I'll take a look at the logs.

**Comment by joeloff** [comment]
From what I can tell, the MSI is trying to install it, however, the VSIXInstaller seems to think that the VSIX doesn't apply to any VS SKU you have:

_14/07/2016 17:00:59 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.OnStartup(StartupEventArgs e)_

When the VSIXInstaller returns an error the MSI is rolled back so that's why you won't see the VSIX on disk.

One thing you can try:
1. Launch VS
2. Go to Tools, Extensions and Updates
3. Uninstall NuGet (you might need to launch VS as admin)
4. Close VS, restart it and close it again. VS usually cleans out the temporary files for VSIX installs that were removed after you restart it.
5. Install .NET Core Tools again

**Comment by AdrianBathurst** [comment]
Followed your steps. Same error. Yes I did notice that vs version message which I thought was strange.

When the error was thrown, I checked if the NuGet directory & vsix file existed, they did, so the installer is getting it there.

**Comment by AdrianBathurst** [comment]
I also tried running the NuGet installer standalone, same error...

![28d7da34-49c9-11e6-99b8-b4ac35e5bfe5](https://cloud.githubusercontent.com/assets/9006517/16848195/7b76eb86-49ec-11e6-985b-82480b80f481.jpg)

**Comment by Michael-Eng** [comment]
What version of Visual Studio do you have installed? Can you send us a screenshot of the window from Help | About? Thanks

**Comment by AdrianBathurst** [comment]
![2016-07-14_180751](https://cloud.githubusercontent.com/assets/9006517/16848493/f039bff6-49ed-11e6-85e3-ff88f08460bc.jpg)

**Comment by AdrianBathurst** [comment]
There is a similar issue raised on aspnet/Tooling by someone else...
https://github.com/aspnet/Tooling/issues/655

**Comment by Michael-Eng** [comment]
Does the vsix_\* log file for your last install attempt match the one in the zip file you sent? From the log, it looks like the vsix installer doesn't see any installed VS SKUs.

In the vsix_\* log file, we should see lines like this:
6/17/2016 11:29:00 AM - Found installed product - Microsoft Visual Studio Enterprise 2015

but in yours it's not there.

**Comment by Michael-Eng** [comment]
From your screenshot you have VS Community installed, however it does not appear that way to the vsix installer. 

To verify:
1. in your registry, you should have HKLM\Software\Wow6432Node\Microsoft\VisualStudio\14.0\Setup\VS\Community[ProductDir] and it should be set correctly
2. You should also have HKLM\Software\Wow6432Node\Microsoft\VisualStudio\14.0[InstallDir] set and when you look at the path set, there should be a devenv.exe in that path.

I believe that's how the vsixinstaller determines if the Community sku is installed. For some reason we don't think it's installed.

If you're missing these registry keys, one way to restore them is to run repair of VS from Control Panel | Add/Remove Programs

**Comment by AdrianBathurst** [comment]
Here are the screen shots...

![2016-07-14_192252](https://cloud.githubusercontent.com/assets/9006517/16850868/da428380-49f8-11e6-8b14-af36c6a6663a.jpg)

![2016-07-14_192432](https://cloud.githubusercontent.com/assets/9006517/16850875/e1e78400-49f8-11e6-8093-7f8eecf8e162.jpg)

![2016-07-14_192542](https://cloud.githubusercontent.com/assets/9006517/16850884/e5208040-49f8-11e6-84f7-db4f8cf82fd9.jpg)

**Comment by AdrianBathurst** [comment]
Not quite sure what you meant in your previous post, so here are all the logs...

[DotNetCore.1.0.0-VS2015Tools.Preview2.exe - Install logs.zip](https://github.com/NuGet/Home/files/364526/DotNetCore.1.0.0-VS2015Tools.Preview2.exe.-.Install.logs.zip)

[DotNetCore.1.0.0-VS2015Tools.Preview2.exe - Uninstall logs.zip](https://github.com/NuGet/Home/files/364527/DotNetCore.1.0.0-VS2015Tools.Preview2.exe.-.Uninstall.logs.zip)

[NuGetVisualStudio14_rc2_39.msi - Install logs.zip](https://github.com/NuGet/Home/files/364529/NuGetVisualStudio14_rc2_39.msi.-.Install.logs.zip)

**Comment by joeloff** [comment]
@AdrianBathurst which keys do you see under HKLM\Wow6432Node\SOFTWARE\Microsoft\DevDiv\vs\Servicing\14.0\

Is there anything for professional? That's how the NuGet MSI detects the SKU.

**Comment by joeloff** [comment]
If you see this key: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\DevDiv\vs\Servicing\14.0\professional

You can try to temporarily rename it to something other than professional and then run the .NET Core tool install.

If you only have Community installed, then you shouldn't have this key, but if you do have it, this should get you around the install issue you're facing

**Comment by AdrianBathurst** [comment]
@joeloff  Am away till tonight, will check then. I only have Community installed though.

**Comment by AdrianBathurst** [comment]
@joeloff Hooorayyy! Yes, that key was present. I renamed it & it worked!! Thank you!!! Odd, as I've not installed Professional. Question is, should I keep it renamed, or return it to it's original state?

Thanks again!

**Comment by joeloff** [comment]
Awesome!. For now, rename it back to professional. I'll follow up with VS to find out why the professional key was created

**Comment by AdrianBathurst** [comment]
Here is the screen shot for reference...

![2016-07-15_191820](https://cloud.githubusercontent.com/assets/9006517/16884389/0104c9ce-4ac1-11e6-8f46-4f023e83d63b.jpg)
