### ISSUE TITLE
A Task was Cancelled

### ISSUE THREAD

**Issue by gravidThoughts** [NuGet/Home#1475]
VS 2015 
Nuget Package Manager for VS 3.2.60914.10516
verbosity = Detailed
source = https://www.nuget.org/api/v2   (V3 source just plain does not work)

Brand new HTML Typescript application project. Attempting to install package. Here is the "detailed" output.

```
Attempting to gather dependencies information for package 'moment.TypeScript.DefinitelyTyped.1.1.1' with respect to project 'TypeScriptHTMLApp1', targeting '.NETFramework,Version=v4.5.2'
A task was canceled.
========== Finished ==========
```

Zero help. Anywhere else I can look to attempt to troubleshoot this issue?

**Comment by emgarten** [comment]
What happens when you install from a V3 source?

Does the task canceled message show up right away, or does it take a couple minutes?

**Comment by gravidThoughts** [comment]
@emgarten

https://api.nuget.org/v3/index.json 

I cannot get V3 source to work at all. It just sits on loading animation whenever I switch to that source.

It takes a couple of minutes.

Does a v3 source work with package manager from VS 2013?

**Comment by emgarten** [comment]
VS 2013 does not have v3 source support.

From what you have described it sounds like the network calls are not making it to the server. V2 and V3 sources could be timing out in different ways due to the same issue.

Would you be able to run fiddler or another tool to view the network calls and see what is happening on your network?

**Comment by yishaigalatzer** [comment]
Regardless of if we can help this user, this error message should be improved and provide some more input as to what timed out while making what request.

**Comment by RanjiniM** [comment]
@gravidThoughts, do you have a fiddler trace that you can share for this issue? Thanks!

**Comment by gravidThoughts** [comment]
@RanjiniM I don't and (un)fortunately it resolved itself. I came to find out our proxy server was having issues that day. If it happens again I will run a trace on fiddler.

**Comment by RanjiniM** [comment]
Better error messages have been added for network issue scenarios now.

**Comment by bilal-fazlani** [comment]
```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.v3.DependencyInfo.Utils.<LoadResource>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.v3.DependencyInfo.Utils.<LoadRanges>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.v3.RegistrationResourceV3.<GetPackageMetadata>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.v3.RegistrationResourceV3.<GetPackageMetadata>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.VisualStudio.UIMetadataResourceV3.<GetMetadata>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<GetPackageMetadataAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<GetPackageMetadataAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<CheckLicenseAcceptanceAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()
========== Finished ==========

```

**Comment by yishaigalatzer** [comment]
@bilal-fazlani this is a closed bug, and your comment is a bit out of context. Would you mind expanding a bit? What version of nuget are you using, where exactly do you see this?
