### ISSUE TITLE
hexadecimal value 0x00, is an invalid character. Line 1, position 1.

### ISSUE THREAD

**Issue by MatzeG** [NuGet/Home#1550]
Hello 

I get on some Projects the following error and i don´t know how to find it. Any hints? I use VS 2015 and Nuget 3.2.60914.10516

regards Matthias

System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.ProjectManagement.XmlUtility.LoadSafe(Stream input, LoadOptions options)
   at NuGet.ProjectManagement.XmlUtility.GetDocument(String root, String path)
   at NuGet.ProjectManagement.XmlUtility.GetOrCreateDocument(XName rootName, String root, String path, INuGetProjectContext nuGetProjectContext)
   at NuGet.PackageManagement.VisualStudio.BindingRedirectManager.GetConfiguration(String configFileFullPath)
   at NuGet.PackageManagement.VisualStudio.BindingRedirectManager.AddBindingRedirects(IEnumerable`1 bindingRedirects)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.<<AddBindingRedirects>b__59_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddBindingRedirects()
   at NuGet.ProjectManagement.MSBuildNuGetProject.PostProcessAsync(INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()

**Comment by yishaigalatzer** [comment]
Can you look at your app.config or web.config across your solution?
Can you share the project?

Our error handling should probably call out the file name that is causing this to happen.

**Comment by yishaigalatzer** [comment]
Fix through - https://github.com/NuGet/NuGet.Client/pull/17/files

**Comment by Seeker1437** [comment]
Hi there, hate to bring back things from the dead, I am encountering this issue on Nuget 3.4.4 under VIsual Studio 2015.3 I can't figure out what it's looking at.

**Comment by yishaigalatzer** [comment]
Can you open a new bug and share a repro? This might be unrelated.

Please share the full error output as well

**Comment by db-007** [comment]
Seeing same issue when I tried installing Xamarin.FFImageLoading.Forms v 2.2.10 package from Package Manager in VS2015
"An error occurred while reading file 'C:\source\SolutionName\ProjectName\ProjectName\packages.config': '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1."

**Comment by Seeker1437** [comment]
See #3078 maybe?

**Comment by lennybacon** [comment]
#3078 Had the solution for me

```powershell
& nuget.exe locals -clear temp
& nuget.exe locals -clear global-packages
& nuget.exe locals -clear http-cache
```

**Comment by Himura2la** [comment]
For dotnet core, use `dotnet nuget locals  --clear global-packages`

**Comment by aalau** [comment]
> For dotnet core, use `dotnet nuget locals --clear global-packages`

Had the same error and ran the above in developer powershell, then[ Build > Clean Solution, Rebuild solution](https://stackoverflow.com/questions/42153798/getting-getprimarycpuabi-task-failed-unexpectedly-every-time-even-if-i-try-to).

**Comment by Murad-88** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project Property: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.. Please see Error List window for detailed warnings and errors.				


why do I get this error and the file web.config contains nothing of that value, it all started when my collage pushed the project with the new tool used (reportViewer). now I cant restore all the packages and it shows this ! symbol to all references in the project
