### ISSUE TITLE
nuget.exe pack of folder with [Content_Types].xml folder in it crashes

### ISSUE THREAD

**Issue by jasonmalinowski** [NuGet/Home#1641]
1. Take some functioning .nuspec that you use to make content packages.
2. Include a [Content_Types].xml file into the folder that contains the .nuspec
3. Remove your input `<files>` element so that file will try to be included into the .nupkg
4. Run nuget.exe pack

_Expected:_ it fails in a debuggable way
_Actual:_ it fails with:

```
Cannot create file because the specified file name is already in use.
```

This fails because NuGet has already tried adding the [Content_Types].xml, and then when it's finalizing the .nupkg the OPC packager tries adding that file again. As a result, it conflicts.

This isn't a terribly easy to hit bug, but it required me attaching a debugger to nuget.exe to figure out.

**Comment by emgarten** [comment]
The exception/message is coming from ZipArchive. NuGet should handle this better.

Full stack:

```
System.InvalidOperationException: Cannot create file because the specified file name is already in use.
   at MS.Internal.IO.Zip.ZipArchive.AddFile(String zipFileName, CompressionMethodEnum compressionMethod, DeflateOptionEn
um deflateOption)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.SaveToFile()
   at System.IO.Packaging.ZipPackage.Dispose(Boolean disposing)
   at System.IO.Packaging.Package.System.IDisposable.Dispose()
   at NuGet.PackageBuilder.Save(Stream stream)
   at NuGet.CommandLine.PackCommand.BuildPackage(PackageBuilder builder, String outputPath)
   at NuGet.CommandLine.PackCommand.BuildFromNuspec(String path)
   at NuGet.CommandLine.PackCommand.BuildPackage(String path)
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by yishaigalatzer** [comment]
We should probably ignore the file (like we do many others) and not fail

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
