### ISSUE TITLE
"sources add" fails on remote box because it needs to have encryption rights

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#1647]
Hey,

Im trying the following (Nuget version: 2.8.60717.93):

```
PS D:\> nuget sources add -name some -user lala -pass mmm -configfile D:\nuget.config -source https://some -verbosity detailed
System.Security.Cryptography.CryptographicException: The requested operation cannot be completed. The computer must be trusted for delegation and the current user account must be configured to allow delegation.
   at System.Security.Cryptography.ProtectedData.Protect(Byte[] userData, Byte[] optionalEntropy, DataProtectionScope scope)
   at NuGet.EncryptionUtility.EncryptString(String value)
   at NuGet.PackageSourceProvider.ReadPasswordValues(PackageSource source)
   at NuGet.PackageSourceProvider.SavePackageSources(IEnumerable`1 sources)
   at NuGet.Commands.SourcesCommand.AddNewSource()
   at NuGet.Commands.SourcesCommand.ExecuteCommand()
   at NuGet.Commands.Command.Execute()
   at NuGet.Program.Main(String[] args)
```

I understand that I can this fix by giving encryption permissions for this user in this machine through AD but this seems like a lot of work for something "simple". Is there any chance that the encryption algorithm could be changed for something else that doesn't require some much AD config? I'd be happy if I could choose a different encryption algorithm that is weaker but easier to run. 

Thanks,

Duda.

**Comment by yishaigalatzer** [comment]
We are not planning on changing this, if anything we will make encryption stronger rather than weaker.
