### ISSUE TITLE
MsBuildUtility should ignore invalid msbuild versions instead of throwing

### ISSUE THREAD

**Issue by zjrunner** [NuGet/Home#1681]
[GetMsBuildDirectory](https://github.com/NuGet/NuGet.Client/blob/81717f6de319290fba103b4b5202ed5d13812397/src/NuGet.Clients/NuGet.CommandLine/MsBuildUtility.cs#L232) does a Version.Parse of the toolsets.  These toolsets don't always have parseable versions (usually because a user messes around there), so a conditional TryParse should be used in here instead to filter out bad values.

[update 2015.11.4 - add repro]
Copy registry key HKLM\SOFTWARE\Wow6432Node\Microsoft\MSBuild\ToolsVersions\4.0 to HKLM\SOFTWARE\Wow6432Node\Microsoft\MSBuild\ToolsVersions\Foo4.0, then launch nuget.
[end]

From a user:
System.FormatException: Input string was not in a correct format.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at NuGet.CommandLine.MsBuildUtility.<>c.<GetMsbuildDirectory>b__7_0(Toolset toolset)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.CommandLine.MsBuildUtility.GetMsbuildDirectory(String version, IConsole console)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__18.MoveNext()

**Comment by yishaigalatzer** [comment]
The reason this is moved to a much higher priority is that even when using -msbuildversion the operation still fails. We should fix this right away.

**Comment by feiling** [comment]
Fixed. See https://github.com/NuGet/NuGet.Client/commit/908fb249cbced8526902b9c93d28f564f3b2e1d8
