### ISSUE TITLE
If NUGET_PACKAGES plus the package name and version is close to MAXPATH, nuget crashes with a Mutex creation arg exception

### ISSUE THREAD

**Issue by zjrunner** [NuGet/Home#1728]
_nuget 3.2.1_
I found this while trying to get a repro for https://github.com/NuGet/Home/issues/1727.  I agree it is a corner case and may not be worth fixing, but at minimum it should not lead to a crash of the exe as an unhandled exception (with a debugger pop and a '0' exitcode which is bad news for lab scenarios)

1) set NUGET_PACKAGES to a path close to 248 characters long.
2) restore a package with a decent sized name and version (I think the mutex name chosen internally has other padding so anything may fail here)

Unhandled Exception: System.ArgumentException: The name can be no more than 260 characters
 in length.
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name, Boolean& createdNe
w, MutexSecurity mutexSecurity)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at NuGet.Common.NuGet.Packaging673149.ConcurrencyUtilities.HandleMutex(String name, Sem
aphoreSlim lockStart, SemaphoreSlim lockEnd, SemaphoreSlim lockOperation, CancellationToke
n token)
   at NuGet.Common.NuGet.Packaging673149.ConcurrencyUtilities.<>c__DisplayClass0_3`1.<Exec
uteWithFileLocked>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, Con
textCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCall
back callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCall
back callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by yishaigalatzer** [comment]
We plan to get rid of the mutex in the next release anyways because it does not work on coreCLR. So i'm closing as duplicate (although it is not really one) to https://github.com/NuGet/Home/issues/1230, because resolving 1230 will resolve it.
