### ISSUE TITLE
InvalidOperationException thrown when calling IPackageRepository.GetPackages()

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#1730]
When IPackageRepository.GetPackages() is called against the https://packages.nuget.org/api/v2 repository, an InvalidOperationException is thrown. 

This was using Nuget.Core 2.9.0 for .NET 4.5. (package id="NuGet.Core" version="2.9.0" targetFramework="net45" )

System.InvalidOperationException: The current value 'String' type is not compatible with the expected 'System.Uri' type. ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Data.Services.Client.ClientConvert.ChangeType(String propertyValue, Type propertyType)
   --- End of inner exception stack trace ---
   at System.Data.Services.Client.ClientConvert.ChangeType(String propertyValue, Type propertyType)
   at System.Data.Services.Client.AtomMaterializer.MaterializeDataValue(Type type, AtomContentProperty atomProperty, DataServiceContext context)
   at System.Data.Services.Client.AtomMaterializer.MaterializeDataValues(ClientType actualType, List`1 values, Boolean ignoreMissingProperties, DataServiceContext context)
   at System.Data.Services.Client.AtomMaterializer.MaterializeResolvedEntry(AtomEntry entry, Boolean includeLinks)
   at System.Data.Services.Client.AtomMaterializer.DirectMaterializePlan(AtomMaterializer materializer, AtomEntry entry, Type expectedEntryType)
   at System.Data.Services.Client.AtomMaterializer.Read()
   at System.Data.Services.Client.MaterializeAtom.MoveNextInternal()
   at System.Data.Services.Client.MaterializeAtom.MoveNext()
   at NuGet.DataServiceQueryWrapper`1.<GetAll>d__7.MoveNext()

**Comment by yishaigalatzer** [comment]
We are deprecating nuget.core and do not plan to fix any bugs in it.

You should use - https://www.nuget.org/api/v2/ as your feed.

**Comment by daveaglick** [comment]
> We are deprecating nuget.core and do not plan to fix any bugs in it.

What does this mean? `NuGet.Core` is a library whereas the URL you provided is an endpoint. Does this mean that there are no other public programmatic APIs for accessing the NuGet feed and it needs to be consumed over the wire, or should we be be using a different library that isn't `NuGet.Core`?

**Comment by yishaigalatzer** [comment]
Yes, we are creating a new API for nuget as a set of packages (starting with nuget.packagemanagement package). nuget.core does not support V3 feeds for example, and none of the new project.json scenarios.

Our plans are to completely remove dependency on nuget.core by one of the next few releases. We already shed most of it in 3.3.

I'm also suggesting that you should probably be able to use nuget.core with www.nuget.org/api/v2 without any issues., and its your choice when you want to move to the next version. Its probably another release or two before we will have it full featured and documented,

**Comment by daveaglick** [comment]
That makes sense, thanks. I'm currently using NuGet.Core and was worried there would be no v3 replacement. Looking forward to the new API.
