### ISSUE TITLE
MsBuildUtility does not account for unparseable toolset versions

### ISSUE THREAD

**Issue by dagood** [NuGet/Home#1737]
When trying to perform a restore command inside a build process, I get the following error and stack trace:

```
System.ArgumentException: Version string portion was too short or too long.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at NuGet.CommandLine.MsBuildUtility.<>c.<GetMsbuildDirectory>b__7_0(Toolset toolset)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.CommandLine.MsBuildUtility.GetMsbuildDirectory(String version, IConsole console)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__18.MoveNext()
```

In the same context, the MSBuild toolsets are:

```
dogfood
14.0
12.0
4.0
3.5
2.0
```

I believe this happens because `dogfood` isn't a version, yet `MsBuildUtility` treats it like one here: [MsBuildUtility.cs:232](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/MsBuildUtility.cs#L232) and elsewhere in the utility.

**Comment by dagood** [comment]
I didn't see issue #1681 in my earlier searches, but it's another symptom of the same assumption.

**Comment by yishaigalatzer** [comment]
We are going to check in a fix shortly, you should be able to pick it up from myget
