### ISSUE TITLE
Cannot install Aspose.Email 6.1.0 (Install-Package : Found invalid data while decoding.)

### ISSUE THREAD

**Issue by nambrose** [NuGet/Home#1881]
I get the above error on:

Install-Package Aspose.Email

I am able to download the .nupkg and unzip it just fine.

Nuget version 3.3.0.167
VS 2015 Update 1

I've logged an incident with Aspose.
Same thing happened to two people here so far.

Stack:

Attempting to gather dependencies information for package 'Aspose.Email.6.1.0' with respect to project 'AsposeAttach', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'Aspose.Email.6.1.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Aspose.Email.6.1.0'
Resolved actions to install package 'Aspose.Email.6.1.0'
Install failed. Rolling back...
Package 'Aspose.Email.6.1.0 : ' does not exist in project 'AsposeAttach'
Package 'Aspose.Email.6.1.0 : ' does not exist in folder 'C:\Users\NicholasA\Documents\Visual Studio 2015\Projects\AsposeAttach\packages'
System.IO.InvalidDataException: Found invalid data while decoding.
   at System.IO.Compression.Inflater.DecodeDynamicBlockHeader()
   at System.IO.Compression.Inflater.Decode()
   at System.IO.Compression.Inflater.Inflate(Byte[] bytes, Int32 offset, Int32 length)
   at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at NuGet.Packaging.NuGetPackageUtils.ExtractFiles(ZipArchive archive, String targetPath, String nupkgFileName, String hashFileName)
   at NuGet.Packaging.NuGetPackageUtils.<>c__DisplayClass1_0.<<InstallFromSourceAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLocked>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLocked>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Packaging.NuGetPackageUtils.<InstallFromSourceAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.v3.GlobalPackagesFolderUtility.<AddPackageAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.v3.DownloadResourceV3.<GetDownloadResultAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.v3.DownloadResourceV3.<GetDownloadResourceResultAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()
========== Finished ==========

**Comment by yishaigalatzer** [comment]
I'm guessing that that you have some sort of corrupted cache on the machines. Can try downloading nuget.exe 3.3 (from here - https://dist.nuget.org/index.html) and run nuget locals -Clear all.

If it still persists after that, please share your nuget source configuration (nuget.config)

**Comment by yishaigalatzer** [comment]
Actually - I see the same on my machine, This might be a server issue @joyhui @maartenba

**Comment by nambrose** [comment]
OK, thanks for checking. Is this a Nuget server issue or an issue with the provider of the libs ?

**Comment by yishaigalatzer** [comment]
This does look like a server issue, I can download the package and then install it from a local folder.

**Comment by joyhui** [comment]
Here is what I tried:
1. Download the package through link: 
https://api.nuget.org/packages/aspose.email.6.1.0.nupkg  (API nugetclient is using.)
https://www.nuget.org/api/v2/package/Aspose.Email/6.1.0 (Links in nuget.org)
The downloaded package are the same size.
1. Change extension from .nupkg to .zip
2. Try "extract all..." in right-click manu to Unzip it...

I got exception: 
![untitled](https://cloud.githubusercontent.com/assets/4565352/12101945/92c19fc6-b2ec-11e5-995f-dfee7ec1a3db.png)

It seems the dll in lib\net40-client is corrupted. If I delete this file from zip, unzip is ok.

**Comment by nambrose** [comment]
OK I have logged an issue with Aspose and will point them to this link.
Will let you know what they say !!!

**Comment by maartenba** [comment]
Package binary has been fixed on our side, can you retry installing it?

**Comment by yishaigalatzer** [comment]
@nambrose closing as we verified this work, feel free to ping if this is not the case.

Note - This does seem like a package issue. Well NuGet.org should have kicked out the package, but our validation doesn't try to unzip it 3 different ways. We will look at adding that validation separately.

**Comment by nambrose** [comment]
Cool, seems to work! Thanks !
