### ISSUE TITLE
NuGet doesn't restore for child folders

### ISSUE THREAD

**Issue by victorhurdugaci** [NuGet/Home#1925]
In dnu it was possible to run restore from the root of a solution and it would restore for all projects (subfolders). The XPlat nuget doesn't seem to do the same.

Repro:
1. Clone MVC
2. Run `NuGet.CommandLine.XPlat restore` in the solution root

Result:

```
D:\aspnet\mvc>c:\Users\victorhu\.dnx\bin\NuGet.CommandLine.XPlat.cmd restore
System.IO.FileNotFoundException: Could not find file 'D:\aspnet\mvc\project.json'.
File name: 'D:\aspnet\mvc\project.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions o
ptions, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean
bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at NuGet.CommandLine.XPlat.Program.<>c__DisplayClass1_0.<<Main>b__1>d.MoveNext()
```

**Comment by victorhurdugaci** [comment]
cc @emgarten

**Comment by emgarten** [comment]
I'll get this fixed today

**Comment by emgarten** [comment]
I'm not able to repro this using the latest build. Restoring without passing in a directory restores all project.json files in the directory.

**Comment by yishaigalatzer** [comment]
@victorhurdugaci what is the status of this? Can it be closed?

**Comment by yishaigalatzer** [comment]
@victorhurdugaci I'm closing this, please re-open if you have a repro
