### ISSUE TITLE
Restore NullRefs on TryResolveConflicts

### ISSUE THREAD

**Issue by BrennanConroy** [NuGet/Home#1959]
When restoring https://github.com/aspnet/Razor/tree/dev/test/Microsoft.AspNet.Razor.Runtime.Test
The below exception is thrown

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object
reference not set to an instance of an object.
   at NuGet.DependencyResolver.GraphOperations.<>c__DisplayClass6_1`1.<TryResolveConflicts>b__4(GraphNode`1 node)
   at NuGet.DependencyResolver.GraphOperations.<>c__DisplayClass9_0`1.<ForEach>b__0(GraphNode`1 node, Int32 _)
   at NuGet.DependencyResolver.GraphOperations.ForEach[TItem,TState](GraphNode`1 root, TState state, Func`3 visitor)
   at NuGet.DependencyResolver.GraphOperations.TryResolveConflicts[TItem](GraphNode`1 root, List`1 versionConflicts)
   at NuGet.DependencyResolver.GraphOperations.Analyze[TItem](GraphNode`1 root)
   at NuGet.Commands.RestoreTargetGraph.Create(Boolean writeToLockFile, RuntimeGraph runtimeGraph, IEnumerable`1 graphs,
 RemoteWalkContext context, ILogger log, NuGetFramework framework, String runtimeIdentifier)
   at NuGet.Commands.RestoreCommand.<WalkDependenciesAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreCommand.<TryRestore>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.XPlat.Program.<ExecuteRestore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.XPlat.Program.<>c__DisplayClass1_0.<<Main>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
```

**Comment by BrennanConroy** [comment]
Just tried with build 517 and it looks to be fixed

**Comment by emgarten** [comment]
I am no longer able to repro the crash with the latest bits.

**Comment by natemcmaster** [comment]
I am still seeing this issue on Linux when attempting to restore on EntityFramework on "src/Microsoft.EntityFrameworkCore.Sqlite"

dotnet cli  1.0.1.001022

**Comment by emgarten** [comment]
NuGet/NuGet.Client@aae23452ba3689bb453a9f95926d765c5aa8bfe4

I've checked in a fix for this. System.Linq 4.0.0 was conflicting with the framework reference to System.Linq 4.0.0. The fix adds additional type checking for this scenario.
