### ISSUE TITLE
Restore has duplicate key when creating lock file

### ISSUE THREAD

**Issue by BrennanConroy** [NuGet/Home#1960]
When restoring https://github.com/aspnet/EntityFramework/tree/dev/src/EntityFramework.Commands
You get the below exception

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentException: An item with
 the same key has already been added. Key: (System.Reflection.Extensions, 4.0.0)
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](List`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)

   at NuGet.Commands.RestoreCommand.CreateLockFile(LockFile previousLockFile, PackageSpec project, IEnumerable`1 targetG
raphs, NuGetv3LocalRepository repository, RemoteWalkContext context)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.XPlat.Program.<ExecuteRestore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.XPlat.Program.<>c__DisplayClass1_0.<<Main>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)
```

**Comment by natemcmaster** [comment]
+1 this is completely blocking Entity Framework.

https://ci.appveyor.com/project/aspnetci/entityframework/build/1.0.760#L161

**Comment by BrennanConroy** [comment]
Just tried with build 517 and it looks to be fixed
