### ISSUE TITLE
JSON error with lock file

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#1964]
Restoring this project file: https://github.com/dotnet/cli/blob/master/src/dotnet-restore/project.json causes an exception message:

```
System.ArgumentException: Can not add property System.Reflection.Emit.ILGeneration to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.Add(Object content)
   at NuGet.ProjectModel.LockFileFormat.WriteObject[TItem](IEnumerable`1 items, Func`2 writeItem) in C:\Users\anurse\Code\NuGet\NuGet.Client\src\NuGet.Core\NuGet.ProjectModel\LockFileFormat.cs:line 520
   at NuGet.ProjectModel.LockFileFormat.WriteTargetLibrary(LockFileTargetLibrary library) in C:\Users\anurse\Code\NuGet\NuGet.Client\src\NuGet.Core\NuGet.ProjectModel\LockFileFormat.cs:line 304
   at NuGet.ProjectModel.LockFileFormat.WriteObject[TItem](IEnumerable`1 items, Func`2 writeItem) in C:\Users\anurse\Code\NuGet\NuGet.Client\src\NuGet.Core\NuGet.ProjectModel\LockFileFormat.cs:line 520
   at NuGet.ProjectModel.LockFileFormat.WriteTarget(LockFileTarget target) in C:\Users\anurse\Code\NuGet\NuGet.Client\src\NuGet.Core\NuGet.ProjectModel\LockFileFormat.cs:line 238
   at NuGet.ProjectModel.LockFileFormat.WriteObject[TItem](IEnumerable`1 items, Func`2 writeItem) in C:\Users\anurse\Code\NuGet\NuGet.Client\src\NuGet.Core\NuGet.ProjectModel\LockFileFormat.cs:line 520
   at NuGet.ProjectModel.LockFileFormat.WriteLockFile(LockFile lockFile) in C:\Users\anurse\Code\NuGet\NuGet.Client\src\NuGet.Core\NuGet.ProjectModel\LockFileFormat.cs:line 175
   at NuGet.ProjectModel.LockFileFormat.Write(TextWriter textWriter, LockFile lockFile) in C:\Users\anurse\Code\NuGet\NuGet.Client\src\NuGet.Core\NuGet.ProjectModel\LockFileFormat.cs:line 145
   at NuGet.ProjectModel.LockFileFormat.Write(Stream stream, LockFile lockFile) in C:\Users\anurse\Code\NuGet\NuGet.Client\src\NuGet.Core\NuGet.ProjectModel\LockFileFormat.cs:line 135
   at NuGet.ProjectModel.LockFileFormat.Write(String filePath, LockFile lockFile) in C:\Users\anurse\Code\NuGet\NuGet.Client\src\NuGet.Core\NuGet.ProjectModel\LockFileFormat.cs:line 127
   at NuGet.Commands.RestoreResult.Commit(ILogger log, Boolean forceWrite) in C:\Users\anurse\Code\NuGet\NuGet.Client\src\NuGet.Core\NuGet.Commands\RestoreResult.cs:line 122
   at NuGet.Commands.RestoreResult.Commit(ILogger log) in C:\Users\anurse\Code\NuGet\NuGet.Client\src\NuGet.Core\NuGet.Commands\RestoreResult.cs:line 98
   at NuGet.CommandLine.XPlat.Program.<ExecuteRestore>d__3.MoveNext() in C:\Users\anurse\Code\NuGet\NuGet.Client\src\NuGet.Core\NuGet.CommandLine.XPlat\Program.cs:line 321
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.CommandLine.XPlat.Program.<>c__DisplayClass1_0.<<Main>b__1>d.MoveNext() in C:\Users\anurse\Code\NuGet\NuGet.Client\src\NuGet.Core\NuGet.CommandLine.XPlat\Program.cs:line 136
```

(There are also restore errors but they are unrelated, I think)

This seems to be caused by the fact that we simply concat the dependencies that come from runtime.json to the dependencies specified in the nuspec, meaning duplicates can occur. I have a fix and will submit a PR shortly.

**Comment by emgarten** [comment]
NuGet/NuGet.Client@36e3183f676ce46dbaa7ba3b4c7cde69f6ae210d
