### ISSUE TITLE
NuGet.Server crashing with null reference exception on startup

### ISSUE THREAD

**Issue by sandersaares** [NuGet/Home#2005]
I tried setting up an install of the NuGet.Server package but after initially working, I find that after a few days it started crashing on every request. Unknown what the cause of this might be but below is the exception that I see in the logs (slightly censored).

Using NuGet.Server 2.10.0-master-0002. Hosting as an Azure Web App.

I have verified that the packages directory exists and contains data. There were no packages added between the moment when it worked and when it did not - only read operations were performed. Restarting the web app does not fix it.

There is a 0-byte file rd000d3a230d21.cache.bin in the packages directory. Deleting this file fixes the problem.

```
<Event><System><Provider Name="ASP.NET 4.0.30319.0"/><EventID>1309</EventID><Level>2</Level><Task>0</Task><Keywords>Keywords</Keywords><TimeCreated SystemTime="2016-01-28T08:26:19Z"/><EventRecordID>589336296</EventRecordID><Channel>Application</Channel><Computer>RD000D3A230D21</Computer><Security/></System><EventData><Data>3005</Data><Data>An unhandled exception has occurred.</Data><Data>1/28/2016 8:26:18 AM</Data><Data>1/28/2016 8:26:18 AM</Data><Data>e0048bb111fe4ecebf3f73064e24d16b</Data><Data>1</Data><Data>1</Data><Data>0</Data><Data>/LM/W3SVC/840757483/ROOT-2-130984431777268075</Data><Data>Full</Data><Data>/</Data><Data>D:\home\site\wwwroot\</Data><Data>RD000D3A230D21</Data><Data></Data><Data>3604</Data><Data>w3wp.exe</Data><Data>IIS APPPOOL\xxx</Data><Data>InvalidOperationException</Data><Data>The pre-application start initialization method Run on type WebActivatorEx.ActivationManager threw an exception with the following error message: Exception has been thrown by the target of an invocation..
   at System.Web.Compilation.BuildManager.InvokePreStartInitMethodsCore(ICollection`1 methods, Func`1 setHostingEnvironmentCultures)
   at System.Web.Compilation.BuildManager.InvokePreStartInitMethods(ICollection`1 methods)
   at System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean&amp; isRefAssemblyLoaded)
   at System.Web.Compilation.BuildManager.ExecutePreAppStart()
   at System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException)

Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at WebActivatorEx.BaseActivationMethodAttribute.InvokeMethod()
   at WebActivatorEx.ActivationManager.RunActivationMethods[T](Boolean designerMode)
   at WebActivatorEx.ActivationManager.Run()

Object reference not set to an instance of an object.
   at NuGet.CollectionExtensions.AddRange[T](ICollection`1 collection, IEnumerable`1 items)
   at NuGet.Server.Infrastructure.ServerPackageStore.Load()
   at NuGet.Server.Infrastructure.ServerPackageStore..ctor(IFileSystem fileSystem, String fileName)
   at NuGet.Server.Infrastructure.ServerPackageRepository..ctor(String path, IHashProvider hashProvider, ILogger logger)
   at NuGet.Server.DefaultServiceResolver..ctor()
   at xxx.NuGetRoutes.Start()

</Data><Data>https://xxx/Packages</Data><Data>/xxx/Packages</Data><Data>123.123.123.123</Data><Data></Data><Data>False</Data><Data></Data><Data>IIS APPPOOL\axnuget</Data><Data>7</Data><Data>IIS APPPOOL\xxx</Data><Data>False</Data><Data>   at System.Web.Compilation.BuildManager.InvokePreStartInitMethodsCore(ICollection`1 methods, Func`1 setHostingEnvironmentCultures)
   at System.Web.Compilation.BuildManager.InvokePreStartInitMethods(ICollection`1 methods)
   at System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean&amp; isRefAssemblyLoaded)
   at System.Web.Compilation.BuildManager.ExecutePreAppStart()
   at System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException)
</Data></EventData></Event></Events>
```

**Comment by maartenba** [comment]
@sandersaares Can you try uninstalling NuGet.Server 2.10.0-master-0002 and then install the following package and see if this resolves the issue?

`Install-Package NuGet.Server -Version 2.10.0-dev-0003 -Source https://www.myget.org/F/nugetbuild/api/v2`

**Comment by sandersaares** [comment]
Alright, will give it a shot. It took some days for the error to occur, so I'll report back next week.

**Comment by maartenba** [comment]
Thanks @sandersaares !

**Comment by sandersaares** [comment]
Issue has not reoccurred - I assume it is fixed. Will speak up again if I notice it reappear.

**Comment by maartenba** [comment]
We pushed this version (well, actually `2.10.0-master-0004`) to NuGet.org. Thanks for your feedback!
