### ISSUE TITLE
XPlat client timeout behavior inconsistent

### ISSUE THREAD

**Issue by pakrym** [NuGet/Home#2017]
Sometimes nuget restore tries to retry after timeout, other times it throws and aborts. Also it's hard for user to interpret `A task was canceled.` as timeout.

Both outputs of `dotnet restore` are on same repo (`dotnet\cli\src\dotnet-pack`) with interval of 1 minute.

```
info : Running restore with 16 concurrent jobs.
info : Restoring packages for D:\github\dotnet\cli\src\dotnet-pack\project.json...
info :   NotFound https://www.myget.org/F/nugetbuild/api/v3/flatcontainer/microsoft.extensions.filesystemglobbing/index.json 723ms
info :   NotFound https://www.myget.org/F/dotnet-corefxlab/api/v3/flatcontainer/microsoft.extensions.filesystemglobbing/index.json 761ms
info :   NotFound https://www.myget.org/F/dotnet-buildtools/api/v3/flatcontainer/microsoft.extensions.filesystemglobbing/index.json 723ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.extensions.jsonparser.sources/index.json 268ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.extensions.hashcodecombiner.sources/index.json 258ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.extensions.commandlineutils.sources/index.json 261ms
info :   NotFound https://www.myget.org/F/netcore-package-prototyping/api/v3/flatcontainer/microsoft.extensions.jsonparser.sources/index.json 721ms
info :   NotFound https://www.myget.org/F/dotnet-corefxlab/api/v3/flatcontainer/microsoft.extensions.jsonparser.sources/index.json 721ms
info :   NotFound https://www.myget.org/F/fsharp-daily/api/v3/flatcontainer/microsoft.extensions.jsonparser.sources/index.json 751ms
info :   NotFound https://www.myget.org/F/roslyn-nightly/api/v3/flatcontainer/microsoft.extensions.hashcodecombiner.sources/index.json 745ms
info :   NotFound https://www.myget.org/F/fsharp-daily/api/v3/flatcontainer/microsoft.extensions.hashcodecombiner.sources/index.json 744ms
info :   NotFound https://www.myget.org/F/netcore-package-prototyping/api/v3/flatcontainer/microsoft.extensions.commandlineutils.sources/index.json 747ms
info :   NotFound https://www.myget.org/F/nugetbuild/api/v3/flatcontainer/microsoft.extensions.commandlineutils.sources/index.json 761ms
info :   NotFound https://www.myget.org/F/dotnet-corefxlab/api/v3/flatcontainer/microsoft.extensions.commandlineutils.sources/index.json 759ms
info :   NotFound https://www.myget.org/F/fsharp-daily/api/v3/flatcontainer/microsoft.extensions.commandlineutils.sources/index.json 767ms
info :   NotFound https://www.myget.org/F/nugetbuild/api/v3/flatcontainer/microsoft.extensions.hashcodecombiner.sources/index.json 789ms
info :   NotFound https://www.myget.org/F/dotnet-buildtools/api/v3/flatcontainer/microsoft.extensions.jsonparser.sources/index.json 798ms
info :   NotFound https://www.myget.org/F/nugetbuild/api/v3/flatcontainer/microsoft.extensions.jsonparser.sources/index.json 805ms
info :   NotFound https://www.myget.org/F/dotnet-core-rel/api/v3/flatcontainer/microsoft.extensions.jsonparser.sources/index.json 819ms
info :   NotFound https://www.myget.org/F/dotnet-corefxlab/api/v3/flatcontainer/microsoft.extensions.hashcodecombiner.sources/index.json 814ms
info :   NotFound https://www.myget.org/F/dotnet-buildtools/api/v3/flatcontainer/microsoft.extensions.commandlineutils.sources/index.json 823ms
info :   NotFound https://www.myget.org/F/dotnet-buildtools/api/v3/flatcontainer/microsoft.extensions.hashcodecombiner.sources/index.json 838ms
info :   NotFound https://www.myget.org/F/dotnet-core-rel/api/v3/flatcontainer/microsoft.extensions.commandlineutils.sources/index.json 957ms
info :   NotFound https://www.myget.org/F/fsharp-daily/api/v3/flatcontainer/microsoft.extensions.filesystemglobbing/index.json 1091ms
info :   NotFound https://www.myget.org/F/roslyn-nightly/api/v3/flatcontainer/microsoft.extensions.commandlineutils.sources/index.json 1132ms
info :   NotFound https://www.myget.org/F/dotnet-core-rel/api/v3/flatcontainer/microsoft.extensions.hashcodecombiner.sources/index.json 1205ms
info : Retrying 'FindPackagesByIdAsync' for source https://www.myget.org/F/dotnet-core-rel/api/v3/flatcontainer/.
A task was canceled.
info : Retrying 'FindPackagesByIdAsync' for source https://www.myget.org/F/roslyn-nightly/api/v3/flatcontainer/.
A task was canceled.
info :   NotFound https://www.myget.org/F/roslyn-nightly/api/v3/flatcontainer/microsoft.extensions.filesystemglobbing/index.json 723ms
info : Retrying 'FindPackagesByIdAsync' for source https://www.myget.org/F/netcore-package-prototyping/api/v3/flatcontainer/.
A task was canceled.
info :   NotFound https://www.myget.org/F/netcore-package-prototyping/api/v3/flatcontainer/microsoft.extensions.filesystemglobbing/index.json 1030ms
info : Retrying 'FindPackagesByIdAsync' for source https://www.myget.org/F/roslyn-nightly/api/v3/flatcontainer/.
A task was canceled.
info : Retrying 'FindPackagesByIdAsync' for source https://www.myget.org/F/netcore-package-prototyping/api/v3/flatcontainer/.
A task was canceled.
info :   NotFound https://www.myget.org/F/netcore-package-prototyping/api/v3/flatcontainer/microsoft.extensions.hashcodecombiner.sources/index.json 952ms
info :   NotFound https://www.myget.org/F/roslyn-nightly/api/v3/flatcontainer/microsoft.extensions.jsonparser.sources/index.json 1170ms
info : Retrying 'FindPackagesByIdAsync' for source https://www.myget.org/F/dotnet-core-rel/api/v3/flatcontainer/.
A task was canceled.
info :   NotFound https://www.myget.org/F/dotnet-core-rel/api/v3/flatcontainer/microsoft.extensions.filesystemglobbing/index.json 790ms
info : All packages are compatible with DNXCore,Version=v5.0.
info : All packages are compatible with DNXCore,Version=v5.0 (win7-x64).
info : All packages are compatible with DNXCore,Version=v5.0 (win7-x86).
info : Committing restore...
info : Restore completed in 204241ms.
```

```
 dotnet restore
info : Running restore with 16 concurrent jobs.
info : Restoring packages for D:\github\dotnet\cli\src\dotnet-pack\project.json...
info :   NotFound https://www.myget.org/F/dotnet-core-rel/api/v3/flatcontainer/microsoft.extensions.filesystemglobbing/index.json 857ms
info :   NotFound https://www.myget.org/F/nugetbuild/api/v3/flatcontainer/microsoft.extensions.filesystemglobbing/index.json 808ms
info :   NotFound https://www.myget.org/F/roslyn-nightly/api/v3/flatcontainer/microsoft.extensions.filesystemglobbing/index.json 747ms
info : Warning: FindPackagesById: Microsoft.Extensions.CommandLineUtils.Sources
  A task was canceled.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)
```

**Comment by yishaigalatzer** [comment]
We also want to address other errors and retry scenarios. Lets start by coming up with a retry behavior expectation table, review then implement the fix

**Comment by joelverhagen** [comment]
Closed with https://github.com/NuGet/NuGet.Client/pull/254.
