### ISSUE TITLE
NullReference when trying to download a package with NuGet.Client

### ISSUE THREAD

**Issue by twsouthwick** [NuGet/Home#2043]
I'm using NuGet.Client libraries 3.3 to get the latest version of a library and download it. I'm using the following code:

``` csharp
using NuGet.Protocol.Core.Types;
using NuGet.Protocol.Core.v3;
using NuGet.Protocol.Core.v3.RemoteRepositories;
using NuGet.Versioning;
using System.Linq;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace nuget_core_null_ref
{
    class Program
    {
        static void Main(string[] args)
        {
            RunAsync("https://api.nuget.org/v3/index.json", "NuGet.Client").Wait();
        }

        private static async Task RunAsync(string feed, string name)
        {
            var handler = new HttpClientHandler();
            var httpResource = new HttpHandlerResourceV3(handler, handler);

            var repo = Repository.Factory.GetCoreV3(feed);
            var finder = new RemoteV3FindPackageByIdResource(repo, () =>
            {
                return Task.FromResult<HttpHandlerResource>(httpResource);
            });

            var versions = await finder.GetAllVersionsAsync(name, CancellationToken.None);
            var latest = versions.OrderByDescending(v => v.Version).First();

            await GetPackageSizeAsync(finder, latest, name);
        }

        private static async Task GetPackageSizeAsync(FindPackageByIdResource finder, NuGetVersion latest, string name)
        {
            // Exception thrown on the following line
            using (var stream = await finder.GetNupkgStreamAsync(name, latest, CancellationToken.None))
            {
            }
        }
    }
}
```

I keep getting a NullReferenceException on the line that calls `finder.GetNupkgStreamAsync` with the following stack trace:

``` csharp
   at NuGet.Protocol.Core.v3.RemoteRepositories.RemoteV3FindPackageByIdResource.<OpenNupkgStreamAsyncCore>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.v3.RemoteRepositories.RemoteV3FindPackageByIdResource.<OpenNupkgStreamAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.v3.RemoteRepositories.RemoteV3FindPackageByIdResource.<GetNupkgStreamAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at nuget_core_null_ref.Program.<GetPackageSizeAsync>d__2.MoveNext() in Program.cs:line 42
```

**Comment by emgarten** [comment]
Take a look at: http://pastebin.com/ZhKe7Rdi

**Comment by twsouthwick** [comment]
Thanks! That got it working :)

Are there plans to throw an ArgumentNullException at these points instead of NullReferenceException? That way, a useful message could be shared. For this in particular, couldn't the context and logger be set to these defaults automatically?

**Comment by emgarten** [comment]
I believe @yishaigalatzer fixed this for 3.4

**Comment by yishaigalatzer** [comment]
Yup. Thanks for the report, closing it

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/NuGet.Client/commit/db49e0b84d096d4807c4a065f1f832be75672546
