### ISSUE TITLE
nuget pack fails to recreate a package

### ISSUE THREAD

**Issue by duduamar** [NuGet/Home#2169]
I have a simple nuget package that I am creating. When I create it using "nuget pack", it works and creates the .nupkg file, but when I rerun the same command I get this error:

`The process cannot access the file '<my .nupkg file>' because it is being used by another process.`

But - no one is using this file (I checked through Process Explorer, and also I am able to simply delete it). When I delete this file and run the command again - it succeeds.

I didn't find anything useful googling for this, maybe someone here knows what to do?

**Comment by duduamar** [comment]
More details about this, this is the output with verbose:

```
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Attempting to build package from '<my nuget package>.nuspec'.
System.IO.IOException: The process cannot access the file '<the existing nupkg file>' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.PhysicalPackageFile.GetStream()
   at NuGet.PackageBuilder.WriteFiles(Package package)
   at NuGet.PackageBuilder.Save(Stream stream)
   at NuGet.CommandLine.PackCommand.BuildPackage(PackageBuilder builder, String outputPath)
   at NuGet.CommandLine.PackCommand.BuildFromNuspec(String path)
   at NuGet.CommandLine.PackCommand.BuildPackage(String path)
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

I have created a very simple C# file calling the FileStream ctor:

```
var path = "<the existing nupkg file>";
var fs = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
Console.WriteLine("FileStrem opened " + fs.CanRead + " " + fs.Name);
```

And the program works as expected:
`FileStrem opened True <the existing nupkg file>`

So, to sum up - seems like two exact calls to FileStream ctor produce different results, this is where I am right now, will appreciate any help.

**Comment by emgarten** [comment]
This may be caused by the nupkg being added to the new nupkg you are creating. When it tries to write out the new nupkg it finds that it is already in use. Remove the old nupkg first.

**Comment by duduamar** [comment]
But I am running nuget pack with "-Exclude *.nupkg", shouldn't that take care of that?

**Comment by duduamar** [comment]
Indeed, seems like you are right - when I use a different output path (meaning the contents of the package and the package files are now separated) - this works as expected. I still think the exclusion of nupkg files should've helped here.

**Comment by yishaigalatzer** [comment]
Thanks for reporting this.

I tend to agree that -Exclude should have helped, but given that you don't want to pack over the same object.

We have seen quite a few packages that include an older version of themselves in, and bloating up the size because sometimes you get an inception scenario where it is actually recursively including older versions as you repack again and again.

Best suggestion - your output path should be elsewhere from where your files are.

We could look at why this happens at some point in the future when this rises to a high enough interest level. For now I'm moving over to our backlog
