### ISSUE TITLE
Nuget restore in parallel fails due to access denied errors in file semaphores

### ISSUE THREAD

**Issue by MattGal** [NuGet/Home#2217]
I don't think this is the same issue as #2102 but in the same category of issue.

We have an msbuild process that does nuget restore over thousands of projects, with default parallelism (i.e. one msbuild instance per logical processor).  Previously we had used dnx.exe but there were breaking changes that necessitated moving away from that.  Our scenario is not blocked because we can get the same effective behavior out of other tools, but this ought to work.

When building in this format with multiple nuget restores going on, nuget.exe ( I tried v3.4.0-beta-669 from the feed) throws with errors like this:

Access to the path 'C:\Users\username\AppData\Local\Temp\NuGetScratch\lock\fd29456801011cc2f0cd4876524c40837286c177' is denied.

for commands like:
nuget.exe restore -PackagesDirectory "D:\foo" -Source ...

Feel free to ping me directly for repro help or to try out this scenario with updated nuget.exe.

**Comment by yishaigalatzer** [comment]
@MattGal any chance to get a better callstack in this case? Can you also tell me what build started failing here?

**Comment by yishaigalatzer** [comment]
@emgarten could this be related to the delete changes?

**Comment by MattGal** [comment]
@yishaigalatzer it's tricky because this happens in an environment where a bunch of these are starting at once... attaching a debugger may be tough.  I'll take a quick stab at it.

**Comment by emgarten** [comment]
I just hit this error message also while restoring with the latest version. I'll take a look at what is going on, it could be related to the recent change to pass the DeleteOnClose flag to the file lock, this may throw on dispose which is outside of the current try/catch.

**Comment by MattGal** [comment]
```
 9>RestorePackages:
     System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\mattgal\AppData\
     Local\Temp\NuGetScratch\lock\965fc7cdd404fce7047d30f6610ab92a84a18fa3' is denied.
        at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
        at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, Strin
     g msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
        at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
        at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__0`1.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at NuGet.Packaging.PackageExtractor.<InstallFromSourceAsync>d__2.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at NuGet.Commands.RestoreCommand.<InstallPackageAsync>d__25.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at NuGet.Commands.RestoreCommand.<>c__DisplayClass24_1.<<InstallPackagesAsync>b__2>d.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:
     line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at NuGet.Commands.RestoreCommand.<InstallPackagesAsync>d__24.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        at NuGet.Commands.RestoreCommand.<TryRestore>d__9.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d__8.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__7.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        at NuGet.CommandLine.RestoreCommand.<PerformNuGetV3RestoreAsync>d__25.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\RestoreCommand.cs:line 325
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at NuGet.CommandLine.RestoreCommand.<>c__DisplayClass23_1.<<ExecuteCommandAsync>b__1>d.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\RestoreCommand.cs:
     line 144
        --- End of inner exception stack trace ---
        at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
        at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
        at System.Threading.Tasks.Task`1.get_Result()
        at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__23.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\RestoreCommand.cs:line 156
        --- End of inner exception stack trace ---
        at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
        at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
        at NuGet.CommandLine.Command.Execute() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\Command.cs:line 123
        at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args) in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Program.cs:line 118
     ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\mattgal\AppData\Local\Temp\NuGetScratch\lock\965fc7
     cdd404fce7047d30f6610ab92a84a18fa3' is denied.
        at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
        at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, Strin
     g msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
        at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
        at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__0`1.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at NuGet.Packaging.PackageExtractor.<InstallFromSourceAsync>d__2.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at NuGet.Commands.RestoreCommand.<InstallPackageAsync>d__25.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at NuGet.Commands.RestoreCommand.<>c__DisplayClass24_1.<<InstallPackagesAsync>b__2>d.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:
     line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at NuGet.Commands.RestoreCommand.<InstallPackagesAsync>d__24.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        at NuGet.Commands.RestoreCommand.<TryRestore>d__9.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d__8.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__7.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        at NuGet.CommandLine.RestoreCommand.<PerformNuGetV3RestoreAsync>d__25.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\RestoreCommand.cs:line 325
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at NuGet.CommandLine.RestoreCommand.<>c__DisplayClass23_1.<<ExecuteCommandAsync>b__1>d.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\RestoreCommand.cs:
     line 144
        --- End of inner exception stack trace ---
        at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
        at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
        at System.Threading.Tasks.Task`1.get_Result()
        at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__23.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\RestoreCommand.cs:line 156
     ---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\mattgal\AppData\Local\Temp\NuGetScratch\lock\965fc7cdd404fce7047d30f6610ab92a84a18fa3' is denied.
        at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
        at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, Strin
     g msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
        at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
        at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__0`1.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at NuGet.Packaging.PackageExtractor.<InstallFromSourceAsync>d__2.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at NuGet.Commands.RestoreCommand.<InstallPackageAsync>d__25.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at NuGet.Commands.RestoreCommand.<>c__DisplayClass24_1.<<InstallPackagesAsync>b__2>d.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:
     line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at NuGet.Commands.RestoreCommand.<InstallPackagesAsync>d__24.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        at NuGet.Commands.RestoreCommand.<TryRestore>d__9.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d__8.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__7.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\CommandAttribute.cs:line 0
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        at NuGet.CommandLine.RestoreCommand.<PerformNuGetV3RestoreAsync>d__25.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\RestoreCommand.cs:line 325
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at NuGet.CommandLine.RestoreCommand.<>c__DisplayClass23_1.<<ExecuteCommandAsync>b__1>d.MoveNext() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\NuGet.CommandLine\Commands\RestoreCommand.cs:
     line 144<---
     <---
```

**Comment by emgarten** [comment]
NuGet/NuGet.Client@f91624e099fdc1bac8aaf69eba4bbf5b8f99dc5f
