### ISSUE TITLE
IVsPackageInstallerServices InstallPackage  401 authenticated feed

### ISSUE THREAD

**Issue by WimBoom** [NuGet/Home#2241]
IVsPackageInstaller.InstallPackage fails on getting a package on a authenticated feed
With this code:

```
class ChildWizard : IWizard
{
    [Import]
    internal IVsPackageInstaller Installer { get; set; }

    private const string feedUrl = "https://feedurl.pkgs.visualstudio.com/DefaultCollection/_packaging/projectname/nuget/v2";
    public void ProjectFinishedGenerating(Project project)
    {
           AddNuGetDependencyIfMissing(...)
    }
    private void AddNuGetDependencyIfMissing(Project project, string packageId, string version = null, string feed = null)
    {
           ** Installer.InstallPackage**(feedurl,
                     project,
                     packageId,
                     version, //Null is latest version of packageId
                     ignoreDependencies: false);
    }
```

}
**Exception on  Installer.InstallPackage**
An exception of type 'System.Net.WebException' occurred in NugetFeedWizard.dll but was not handled in user code

Additional information: The remote server returned an error: (401) Unauthorized.

**With fiddler see we this:**
GET https://feedurl.pkgs.visualstudio.com/DefaultCollection/_packaging/projectname/nuget/v2 HTTP/1.0
User-Agent: NuGet/2.10.0.755 (Microsoft Windows NT 10.0.10586.0)
Host: feedurl.pkgs.visualstudio.com
Message:
TF400813: Resource not available for anonymous access. Client authentication required.

**Stacktrace:**
  at System.Net.HttpWebRequest.GetResponse()
   at NuGet.RequestHelper.GetResponse()
   at NuGet.HttpClient.GetResponse()
   at NuGet.RedirectedHttpClient.GetResponseUri(HttpClient client)
   at NuGet.RedirectedHttpClient.EnsureClient()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at NuGet.MemoryCache.GetOrAdd[T](Object cacheKey, Func`1 factory, TimeSpan expiration, Boolean absoluteExpiration)
   at NuGet.RedirectedHttpClient.get_CachedClient()
   at NuGet.RedirectedHttpClient.get_Uri()
   at NuGet.DataServicePackageRepository.get_Source()
   at NuGet.Protocol.Core.v2.DependencyInfoResourceV2.ResolvePackages(String packageId, NuGetFramework projectFramework, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.<GetLatestVersionCoreAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<>c__DisplayClass62_1.<<GetLatestVersionAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<GetLatestVersionAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<GetLatestVersionAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   at NugetFeedTemplateWizard.ChildWizard.AddNuGetDependencyIfMissing(Project project, String packageId, String version, String feed)

**The feed is registered** in the %appdata%\Nuget\Nuget.config with this command:
nuget sources add -name "FEED" -source https://feedurl.pkgs.visualstudio.com/DefaultCollection/_packaging/projectname/nuget/v2 -username "username" -password "hidden"

**Comment by yishaigalatzer** [comment]
Please upgrade to NuGet 3.3 or 3.4RC released today with Update 2 RC (Visual Studio 2015). I believe the problem should be resolved there (didn't test, but we have a single install/restore path including authentication).

We no longer support this level of bugs for NuGet on 2013.

Please let us know if that resolves your problem

**Comment by WimBoom** [comment]
I install Update 2 RC (Visual Studio 2015). And it works! Thank you!
