### ISSUE TITLE
First-timer having trouble building nuget

### ISSUE THREAD

**Issue by wbradney** [NuGet/Home#2250]
I followed the instructions [here](http://docs.nuget.org/Contribute/Setting-up-the-NuGet-Development-Environment).

And got:

```
PS>Home\build-nuget.ps1 -Configuration debug -clean .
Home\build-nuget.ps1 : The module 'Home' could not be loaded. For more information, run 'Import-Module Home'.
At line:1 char:1
+ Home\build-nuget.ps1 -Configuration debug -clean .
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Home\build-nuget.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule

```

So then I tried:

```
PS>Home\build-nuget.ps1 -Configuration debug
======== Building in C:\Users\wbradney\nuget\NuGet3 ======
Unable to find package 'KoreBuild'.
Package "Sake" is already installed.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
warn: Dynamic view compilation failed.
c:\Users\wbradney\nuget\NuGet3\makefile.shade(10,69): error CS0103: The name 'IsMono' does not exist in the current context
c:\Users\wbradney\AppData\Local\Temp\edaed8b6c4b641709e89c7866a7d5ada-1.cs(526,19): error CS0246: The type or namespace name 'Exception' could not be
found (are you missing a using directive or an assembly reference?)
c:\Users\wbradney\nuget\NuGet3\makefile.shade(11,50): error CS0103: The name 'IsMono' does not exist in the current context
c:\Users\wbradney\AppData\Local\Temp\edaed8b6c4b641709e89c7866a7d5ada-1.cs(640,19): error CS0246: The type or namespace name 'Exception' could not be
found (are you missing a using directive or an assembly reference?)
c:\Users\wbradney\nuget\NuGet3\makefile.shade(13,69): error CS0103: The name 'IsMono' does not exist in the current context
c:\Users\wbradney\AppData\Local\Temp\edaed8b6c4b641709e89c7866a7d5ada-1.cs(754,19): error CS0246: The type or namespace name 'Exception' could not be
found (are you missing a using directive or an assembly reference?)
c:\Users\wbradney\nuget\NuGet3\makefile.shade(14,50): error CS0103: The name 'IsMono' does not exist in the current context
c:\Users\wbradney\AppData\Local\Temp\edaed8b6c4b641709e89c7866a7d5ada-1.cs(868,19): error CS0246: The type or namespace name 'Exception' could not be
found (are you missing a using directive or an assembly reference?)

1 using System.Diagnostics;
2 using System.IO;
3
4 [global::Spark.SparkViewAttribute(
5     Templates = new string[] {
6       "makefile.shade"
7     })]
8 public class View8905ce7c65094695971f0a8d788130f5 : Sake.Engine.Builder.BuilderBase
9 {
10

... snip ...

883     [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
884     public override void Render()
885     {
886                 RenderViewLevel0();
887     }
888 }

verbose: Stack trace:
   at Spark.Compiler.BatchCompiler.Compile(Boolean debug, String languageOrExtension, String[] sourceCode)
   at Spark.Compiler.CSharp.CSharpViewCompiler.CompileView(IEnumerable`1 viewTemplates, IEnumerable`1 allResources)
   at Spark.SparkViewEngine.CreateEntryInternal(SparkViewDescriptor descriptor, Boolean compile)
   at Spark.SparkViewEngine.CreateEntry(SparkViewDescriptor descriptor)
   at Sake.Engine.Loader.DefaultLoader.Load(Options options)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
last exit code 1
Build failed. Project directory is C:\Users\wbradney\nuget\NuGet3
At C:\Users\wbradney\nuget\Home\build-nuget.ps1:49 char:9
+         throw $errorMessage
+         ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Build failed. P...ey\nuget\NuGet3:String) [], RuntimeException
    + FullyQualifiedErrorId : Build failed. Project directory is C:\Users\wbradney\nuget\NuGet3

```

**Comment by yishaigalatzer** [comment]
I've seen 3 people do it in the last couple of days without issues, so possibly you are missing steps from the startup?

Can you start with a fresh clone, make sure all the dependencies are installed (and all the feeds required to build are accessible). and run the plain build.ps1 -CleanCache ?

**Comment by wbradney** [comment]
Sorry if I'm being dense, but I just tried again on my clean home laptop and I get the exact same error.
What is the "plain build.ps1"? I don't see any build.ps1 file anywhere in the directories cloned.

**Comment by wbradney** [comment]
Also, where do I find the list of "feeds required to build"?

**Comment by wbradney** [comment]
The script is trying to install a package called KoreBuild from source `https://www.myget.org/F/nugetbuild/api/v2`. When I list the packages there the KoreBuild package doesn't seem to exist (even in a prerelease form):

```
PS C:\users\wayne\nugetrepo\NuGet3> nuget list -Source https://www.myget.org/F/nugetbuild/api/v2 -pre
Microsoft.VisualStudio.ProjectSystem.Interop 1.0.0-beta-607
NuGet.Client 3.4.0-rtm-beta-721
NuGet.CommandLine 3.4.0-rtm-721
NuGet.CommandLine.Cmd 3.1.0-beta-10371
NuGet.CommandLine.XPlat 3.4.0-rtm-beta-721
NuGet.Commands 3.4.0-rtm-beta-721
NuGet.Common 3.4.0-rtm-beta-721
NuGet.Configuration 3.4.0-rtm-beta-721
NuGet.ContentModel 3.4.0-rtm-beta-721
NuGet.DependencyResolver 3.4.0-rtm-beta-721
NuGet.DependencyResolver.Core 3.4.0-rtm-beta-721
NuGet.Frameworks 3.4.0-rtm-beta-721
NuGet.Indexing 3.4.0-rtm-beta-721
NuGet.LibraryModel 3.4.0-rtm-beta-721
NuGet.Logging 3.4.0-rtm-beta-721
NuGet.MsBuild.Integration 3.1.0-beta-001
NuGet.PackageManagement 3.4.0-rtm-beta-721
NuGet.Packaging 3.4.0-rtm-beta-721
NuGet.Packaging.Build 3.4.0-beta-693
NuGet.Packaging.Core 3.4.0-rtm-beta-721
NuGet.Packaging.Core.Types 3.4.0-rtm-beta-721
NuGet.ProjectManagement 3.4.0-rtm-beta-721
NuGet.ProjectModel 3.4.0-rtm-beta-721
NuGet.Protocol.Core.Types 3.4.0-rtm-beta-721
NuGet.Protocol.Core.v2 3.4.0-rtm-beta-721
NuGet.Protocol.Core.v3 3.4.0-rtm-beta-721
NuGet.Protocol.Test.Utility 1.0.0-beta-607
NuGet.Protocol.VisualStudio 3.4.0-rtm-beta-721
NuGet.Repositories 3.4.0-rtm-beta-721
NuGet.Resolver 3.4.0-rtm-beta-721
NuGet.RuntimeModel 3.4.0-rtm-beta-721
NuGet.Server 2.10.0-master-0008
NuGet.Services.Metadata.Catalog 3.0.1951-r-searchcloud
NuGet.Services.Search.Client 3.0.428-r-master
NuGet.Shared 3.4.0-rtm-beta-721
NuGet.Test.Utility 3.4.0-beta-607
NuGet.Versioning 3.4.0-rtm-beta-721
SynchronizationTestApp 1.0.0-beta-607
Test.Utility 3.4.0-beta-607
PS C:\users\wayne\nugetrepo\NuGet3>
```

**Comment by yishaigalatzer** [comment]
Sorry this doc is out of date, I'll fix it, I now understand the confusion (sorry for not following you link earlier). 

The steps are described better on the home page of this repo, in short clone nuget.client and run build.ps1

**Comment by wbradney** [comment]
OK, thanks. I was able to build, but there are errors in the tests. I'm proceeding with debugging my issue.
