### ISSUE TITLE
Exception adding a package: VS2015 Update 2 CTP, Nuget extension 3.4.0.653 (RC)

### ISSUE THREAD

**Issue by kkm000** [NuGet/Home#2270]
Trying to install a package FSharpx.Extras.1.10.3. Not sure if this is a packaging problem, or a bug in NuGet package manager. 

VS2015 Update 2 CTP with Nuget extension 3.4.0.653 (this is the latest RC. Installation attempt fails after resolving dependencies with the following exception logged in the Output window:

```
Attempting to gather dependency information for package 'FSharpx.Extras.1.10.3' with respect to project 'forthright', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'FSharpx.Extras.1.10.3' with DependencyBehavior 'Lowest'
Resolving actions to install package 'FSharpx.Extras.1.10.3'
Resolved actions to install package 'FSharpx.Extras.1.10.3'
Newtonsoft.Json.JsonSerializationException: Error converting value "" to type 'System.Boolean'. Path 'requireLicenseAcceptance', line 38, position 43. ---> System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at System.String.System.IConvertible.ToBoolean(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at NuGet.Protocol.PackageMetadataResourceV3.ParseMetadata(JObject metadata)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGet.PackageManagement.UI.UIActionEngine.<GetPackageMetadataAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<GetPackageMetadataAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<CheckLicenseAcceptanceAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()
========== Finished ==========
```

The same package installs in VS2015 Update 1 with stock NuGet extension.

**Comment by yishaigalatzer** [comment]
We haven't started looking into it, but it is always a good idea to share more details, about the project type, other packages (pre install packages.config), nuget.config

**Comment by kkm000** [comment]
The project type is a very normal F# library without any manual project modifications, recently created with the same VS version (Up2 CTP), targeting .NET 4.5.2. The problem does not reproduce on another machine with VS 2015 Update 1 RTM.

I think I have an idea. The package FSharpx.Extras that I tried to install has a few dependencies, and I started installing them one by one in reverse topological order (starting from those having no dependencies). `FSharp.Core.3.1.2.1` installs fine, but `FSharp.Control.AsyncSeq.1.13` failled to install. The error message was again the same: _Error converting value "" to type 'System.Boolean'. Path 'requireLicenseAcceptance', line 38, position 43. ---> System.FormatException: String was not recognized as a valid Boolean._

Now, I see that he `nuspec` in package `FSharp.Control.AsyncSeq.1.13` has no `requireLicenseAcceptance` element:

``` xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/10/nuspec.xsd">
  <metadata>
    <id>FSharp.Control.AsyncSeq</id>
    <version>1.13</version>
    <authors>Tomasz Petricek, David Thomas, Ryan Riley, Steffen Forkmann</authors>
    <owners>Tomasz Petricek, David Thomas, Ryan Riley, Steffen Forkmann</owners>
    <licenseUrl>http://fsprojects.github.io/FSharp.Control.AsyncSeq/license.html</licenseUrl>
    <projectUrl>http://fsprojects.github.io/FSharp.Control.AsyncSeq/</projectUrl>
    <iconUrl>http://fsprojects.github.io/FSharp.Control.AsyncSeq/img/logo.png</iconUrl>
    <description>Asynchronous sequences for F#</description>
    <summary>Asynchronous sequences for F#</summary>
    <releaseNotes>Renamed to FSharp.Control.AsyncSeq
Remove surface area
Hide Nil/Cons from representation of AsyncSeq</releaseNotes>
    <copyright>Copyright 2015</copyright>
    <tags>F# async fsharpx</tags>
  </metadata>
</package>
```

The `nuspec` in the successfully installed package `FSharp.Core.3.1.2.1` does:

``` xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>FSharp.Core</id>
    <version>3.1.2.1</version>
. . . . . 
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
. . . . .
  </metadata>
</package>
```

It's hard to guess what the position in the error message means (it is outside the nuspec file), but hope you might have some ideas.

**Comment by johnataylor** [comment]
problem in json deserialization - fixed

**Comment by kkm000** [comment]
Is there a version of the extension I can use to confirm the fix?
