### ISSUE TITLE
ApplicationInsights 2.0 package is listed but doesn't exist yet

### ISSUE THREAD

**Issue by abatishchev** [NuGet/Home#2317]
Hi,
I understand this is likely an issue of the propagation a recently added package around the system/storage. But still would be nice if it could be addressed. For instance, fail for gracefully.

Here's the scenario: NuGet says for project 'Api' referencing Microsoft.ApplicationInsights version 1.2.3 there is an update to [2.0.0](https://www.nuget.org/packages/Microsoft.ApplicationInsights/2.0.0).

The most annoying here that NuGet uninstalls  the existing version first, then tries to download the new version where here it fails. Ending up with leaving the project in bad state.

The output:

```
Successfully uninstalled 'Microsoft.ApplicationInsights 1.2.3' from Api
GET https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights/2.0.0/microsoft.applicationinsights.2.0.0.nupkg
Error downloading 'Microsoft.ApplicationInsights 2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights/2.0.0/microsoft.applicationinsights.2.0.0.nupkg'.
Response status code does not indicate success: 404 (Not Found).
Install failed. Rolling back...
Package 'Microsoft.ApplicationInsights 2.0.0' does not exist in project 'Api'
NuGet.Protocol.Core.Types.FatalProtocolException: Error downloading 'Microsoft.ApplicationInsights 2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights/2.0.0/microsoft.applicationinsights.2.0.0.nupkg'. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<GetStreamAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.GetDownloadResultUtility.<GetDownloadResultAsync>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at NuGet.Protocol.GetDownloadResultUtility.<GetDownloadResultAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.v3.DownloadResourceV3.<GetDownloadResourceResultAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<>c__DisplayClass4_0.<<PerformUpdateAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()
========== Finished ==========
```

Thanks.

**Comment by yishaigalatzer** [comment]
@abatishchev - There are two issues here
1. That the package is missing from one of the sources that's a server issue and I opened an immediate bug to fix it https://github.com/NuGet/NuGetGallery/issues/2939 (CC @maartenba)
2. When it comes to not rolling back, I agree that's a good idea. It would be helpful to add clear repro steps.
   2.1 Version of visual studio and nuget
   2.2 Exact project type (mostly is it packages.config, xproj or csproj + project.json)
   2.3 What exactly did you do, if in the UI, what did you click and if in the powershell console what command did you type.

**Comment by abatishchev** [comment]
2.1 Microsoft Visual Studio Enterprise 2015 Version 14.0.25029.00 Update 2 RC (dogfooding), Microsoft .NET Framework Version 4.6.01055.
2.2 Regular ASP.NET Web API with packages.config
2.3 Using UI, clicked Managed Packages on the solution node, opened the Updates tabs, clicked Select All then Update (love this button btw).

**Comment by maartenba** [comment]
Package indeed did not exist - it has been added to the V3 flat container.

**Comment by abatishchev** [comment]
Should this be closed?
