### ISSUE TITLE
Removed package 'x' is followed by System.FormatException

### ISSUE THREAD

**Issue by abatishchev** [NuGet/Home#2328]
I'm continuously trying to update App Insights in my Web API project from 1.2.3 to 2.0.0 using VS 2015 Update 2 RC and NuGet 3.4.0.768 (both dogfooding) but getting the following exception:

```
Attempting to gather dependency information for multiple packages with respect to project 'Api', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for multiple packages.
Resolving actions install multiple packages
Removed package 'Microsoft.ApplicationInsights.Web 1.2.3' from 'packages.config'
Successfully uninstalled 'Microsoft.ApplicationInsights.Web 1.2.3' from Api
Removed package 'Microsoft.ApplicationInsights.WindowsServer 1.2.3' from 'packages.config'
Successfully uninstalled 'Microsoft.ApplicationInsights.WindowsServer 1.2.3' from Api
Removed package 'Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel 1.2.3' from 'packages.config'
Successfully uninstalled 'Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel 1.2.3' from Api
Removed package 'Microsoft.ApplicationInsights.PerfCounterCollector 1.2.3' from 'packages.config'
Successfully uninstalled 'Microsoft.ApplicationInsights.PerfCounterCollector 1.2.3' from Api
Removed package 'Microsoft.ApplicationInsights.DependencyCollector 1.2.3' from 'packages.config'
Successfully uninstalled 'Microsoft.ApplicationInsights.DependencyCollector 1.2.3' from Api
Removed package 'Microsoft.ApplicationInsights 1.2.3' from 'packages.config'
Successfully uninstalled 'Microsoft.ApplicationInsights 1.2.3' from Api
  GET https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights/2.0.0/microsoft.applicationinsights.2.0.0.nupkg
Installing Microsoft.ApplicationInsights 2.0.0.
Adding package 'Microsoft.ApplicationInsights.2.0.0' to folder 'D:\Projects\PaymentRequest\packages'
Added package 'Microsoft.ApplicationInsights.2.0.0' to folder 'D:\Projects\PaymentRequest\packages'
Install failed. Rolling back...
Package 'Microsoft.ApplicationInsights 2.0.0' does not exist in project 'Api'
Package 'Microsoft.ApplicationInsights 1.2.3' already exists in folder 'D:\Projects\PaymentRequest\packages'
Added package 'Microsoft.ApplicationInsights 1.2.3' to 'packages.config'
Package 'Microsoft.ApplicationInsights.DependencyCollector 1.2.3' already exists in folder 'D:\Projects\PaymentRequest\packages'
Added package 'Microsoft.ApplicationInsights.DependencyCollector 1.2.3' to 'packages.config'
Package 'Microsoft.ApplicationInsights.PerfCounterCollector 1.2.3' already exists in folder 'D:\Projects\PaymentRequest\packages'
Added package 'Microsoft.ApplicationInsights.PerfCounterCollector 1.2.3' to 'packages.config'
Package 'Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel 1.2.3' already exists in folder 'D:\Projects\PaymentRequest\packages'
Added package 'Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel 1.2.3' to 'packages.config'
Package 'Microsoft.ApplicationInsights.WindowsServer 1.2.3' already exists in folder 'D:\Projects\PaymentRequest\packages'
Added package 'Microsoft.ApplicationInsights.WindowsServer 1.2.3' to 'packages.config'
Executing script file 'D:\Projects\PaymentRequest\packages\Microsoft.ApplicationInsights.WindowsServer.1.2.3\Tools\install.ps1'...
Package 'Microsoft.ApplicationInsights.Web 1.2.3' already exists in folder 'D:\Projects\PaymentRequest\packages'
Added package 'Microsoft.ApplicationInsights.Web 1.2.3' to 'packages.config'
Removing package 'Microsoft.ApplicationInsights 2.0.0' from folder 'D:\Projects\PaymentRequest\packages'
Removed package 'Microsoft.ApplicationInsights 2.0.0' from folder 'D:\Projects\PaymentRequest\packages'
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at NuGet.Packaging.PackagesConfigWriter.WriteFile(String fullPath)
   at NuGet.Packaging.PackagesConfigWriter.Dispose()
   at NuGet.ProjectManagement.PackagesConfigNuGetProject.InstallPackageAsync(PackageIdentity packageIdentity, DownloadResourceResult downloadResourceResult, INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.ProjectManagement.MSBuildNuGetProject.<InstallPackageAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<>c__DisplayClass4_0.<<PerformUpdateAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()
========== Finished ==========
```

**Comment by alpaix** [comment]
From a brief code path observation it looks like operation failed while trying to write packages.config file to disk. It's not clear what was the actual error since exception was thrown in catch-all clause. Will proceed with fixing error message format first.
