### ISSUE TITLE
NuGet pack couldn't extract metadata.

### ISSUE THREAD

**Issue by Razenpok** [NuGet/Home#2360]
Nuget pack cannot extract metadata from assemblies with Bridge reference.

Steps to reproduce:
1. Create class library project.
2. Remove all references.
3. Install Bridge NuGet package (https://www.nuget.org/packages/Bridge/).
4. Add this method in Class1:

``` csharp
[Ready]
public static void Test() { }
```
1. Build project.
2. Run "nuget spec".
3. Run "nuget pack ClassLibrary1.csproj"
4. Observe "WARNING: Unable to extract metadata from 'ClassLibrary1.dll'" error.

**Comment by yishaigalatzer** [comment]
@toddm if this is limited to a quirk in brige, lets move it out, but if it is a more inherent issue, lets figure out what the fix should be

**Comment by toddm** [comment]
The internal exception is this:
System.TypeLoadException occurred
  HResult=-2146233054
  Message=Could not load type 'System.Object' from assembly 'Bridge, Version=1.11.0.0, Culture=neutral, PublicKeyToken=null' because the parent does not exist.
  Source=mscorlib
  TypeName=System.Object
  StackTrace:
       at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr\* typeInstArgs, Int32 typeInstCount, IntPtr\* methodInstArgs, Int32 methodInstCount)
       at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
       at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
       at System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttributeRecord caRecord)
       at System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
       at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeAssembly target)
       at System.Reflection.RuntimeAssembly.GetCustomAttributesData()
       at System.Reflection.CustomAttributeData.GetCustomAttributes(Assembly target)
       at NuGet.CommandLine.AssemblyMetadataExtractor.MetadataExtractor.GetMetadata(String path) in E:\NuGet.Client\src\NuGet.Clients\NuGet.CommandLine\Commands\Pack\AssemblyMetadataExtractor.cs:line 83
  InnerException:

**Comment by emgarten** [comment]
Closing due to lack of feedback on this.
