### ISSUE TITLE
Can't load Microsoft.TeamFoundation.Client on dev15, need to update Microsoft.TeamFoundation.Client version to 15.0 for VS "15" Preview

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#2392]
Repro step:
1.create console app, bind it to TFS.
2.install any package from nuget UI.

expect: install well
actual: got error could not load file or assembly "Microsoft.TeamFoundation.Client"

the issue here is in dev15, Microsoft.TeamFoundation.Client version is 15.0, nuget is referencing 14.0.
need to update it for dev15

**Comment by rrelyea** [comment]
Dev 15 Preview build 25122 (one day before final)
Using NuGet 3.4.0.798 (hand installed on top of the one in 25122).

**Comment by pspill** [comment]
Attempting to gather dependency information for package 'bootstrap.3.3.6' with respect to project 'ConsoleApplication5', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for package 'bootstrap.3.3.6' with DependencyBehavior 'Lowest'
Resolving actions to install package 'bootstrap.3.3.6'
Resolved actions to install package 'bootstrap.3.3.6'
Adding package 'jQuery.1.9.1' to folder 'C:\school\ConsoleApplication5\packages'
Install failed. Rolling back...
Package 'jQuery.1.9.1' does not exist in project 'ConsoleApplication5'
Removing package 'jQuery.1.9.1' from folder 'C:\school\ConsoleApplication5\packages'
Could not load file or assembly 'Microsoft.TeamFoundation.Client, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Removed package 'jQuery.1.9.1' from folder 'C:\school\ConsoleApplication5\packages'
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.TeamFoundation.Client, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.TeamFoundation.Client, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at NuGet.TeamFoundationServer.DefaultTFSSourceControlManager..ctor(ISettings settings, SourceControlBindings sourceControlBindings)
   at NuGet.TeamFoundationServer.TFSSourceControlManagerProvider.GetTFSSourceControlManager(SourceControlBindings sourceControlBindings)
   at NuGet.PackageManagement.VisualStudio.TFSSourceControlManagerProviderPicker.GetTFSSourceControlManager(SourceControlBindings sourceControlBindings)
   at NuGet.PackageManagement.VisualStudio.VSSourceControlManagerProvider.<>c__DisplayClass5_0.<GetSourceControlManager>b__1(ITFSSourceControlManagerProvider provider)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGet.PackageManagement.VisualStudio.VSSourceControlManagerProvider.<<GetSourceControlManager>b__5_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at NuGet.PackageManagement.VisualStudio.VSSourceControlManagerProvider.GetSourceControlManager()
   at NuGet.ProjectManagement.SourceControlUtility.GetSourceControlManager(INuGetProjectContext nuGetProjectContext)
   at NuGet.ProjectManagement.FolderNuGetProject.InstallPackageAsync(PackageIdentity packageIdentity, DownloadResourceResult downloadResourceResult, INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.ProjectManagement.MSBuildNuGetProject.<InstallPackageAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()

**Comment by drewgillies** [comment]
Note: this is fixed by https://github.com/NuGet/NuGet.Client/commit/e117ed7ebad25f440115b42bcac147767e68a4e3
but I would like to keep the issue open for now as we don't have full CI in place for Dev15.

**Comment by drewgillies** [comment]
Closing, as this change now flows through to Dev15 consumables (VSIXes, signed VSIXes, packaging etc).

**Comment by SvenAelterman** [comment]
I am unclear, using 15 Preview 2, how to avoid this problem?
