### ISSUE TITLE
NuGet.NetPortableProfile is not thread-safe

### ISSUE THREAD

**Issue by hickford** [NuGet/Home#2464]
I innocently assumed the method `NuGet.VersionUtility.TryGetCompatibleItems` (in NuGet.Core.dll) would be thread-safe. It turns out not to be (example stack trace below). Reading the source code, this looks to be due to [naive lazy initialisation of NetPortableProfileTable.Profile](https://github.com/NuGet/NuGet2/blob/2.11/src/Core/NETPortable/NetPortableProfileTable.cs#L50)

I expect it would be easy to make thread safe with a lock statement or the System.Lazy type.

```
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.NetPortableProfileTable.GetProfile(String profileName)
   at NuGet.NetPortableProfile.Parse(String profileValue, Boolean treatOptionalFrameworksAsSupportedFrameworks)
   at NuGet.VersionUtility.IsPortableLibraryCompatible(FrameworkName projectFrameworkName, FrameworkName packageTargetFrameworkName)
   at NuGet.VersionUtility.IsCompatible(FrameworkName projectFrameworkName, FrameworkName packageTargetFrameworkName)
   at NuGet.VersionUtility.<>c__DisplayClass19`1.<TryGetCompatibleItems>b__13(IGrouping`2 g)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NuGet.VersionUtility.TryGetCompatibleItems[T](FrameworkName projectFramework, IEnumerable`1 items, IEnumerable`1& compatibleItems)
```

**Comment by hickford** [comment]
It looks like other people have suffered the same bug too:
1. https://github.com/NuGet/Home/issues/778
2. https://gitcandy.com/Repository/Commit/KRuntime/df5e113c14429708b901f3cce69b1279865618b1/src/Microsoft.Framework.Runtime/NuGet
3. http://stackoverflow.com/q/24429838/284795

**Comment by emgarten** [comment]
Use the `NuGet.Frameworks` library

**Comment by emgarten** [comment]
@joelverhagen would you merge this as part of your 2.12 target framework changes?

**Comment by joelverhagen** [comment]
Fixed with https://github.com/NuGet/NuGet2/pull/50.
