### ISSUE TITLE
Convert_WithValidImageUrl_DownloadsImage fails on CI

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#2474]
`NuGet.PackageManagement.UI.Test.IconUrlToImageCacheConverterTests.Convert_WithValidImageUrl_DownloadsImage` fails on CI out of some unclear reason. In order to unblock the 3.4.2 release it's been disabled for now.

**Comment by alpaix** [comment]
Disabled catch-all statement to reveal the actual exception.

```
System.Runtime.InteropServices.COMException : This function is not supported on this system. (Exception from HRESULT: 0x80070078)
    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
    at MS.Win32.WinInet.get_InternetCacheFolder()
    at System.Windows.Media.Imaging.BitmapDownload.BeginDownload(BitmapDecoder decoder, Uri uri, RequestCachePolicy uriCachePolicy, Stream stream)
    at System.Windows.Media.Imaging.LateBoundBitmapDecoder..ctor(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy requestCachePolicy)
    at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
    at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
    at System.Windows.Media.Imaging.BitmapImage.EndInit()
    at NuGet.PackageManagement.UI.IconUrlToImageCacheConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture) in C:\BuildAgent\work\6146812267711dd9\src\NuGet.Clients\PackageManagement.UI\Converters\IconUrlToImageCacheConverter.cs:line 74
    at NuGet.PackageManagement.UI.Test.IconUrlToImageCacheConverterTests.Convert_WithValidImageUrl_DownloadsImage() in C:\BuildAgent\work\6146812267711dd9\test\NuGet.Clients.Tests\NuGet.PackageManagement.UI.Test\Converters\IconUrlToImageCacheConverterTests.cs:line 76
```

Most likely error occurs due to certain TeamCity build agent settings.

**Comment by yishaigalatzer** [comment]
Thanks @alpaix lets be 100% sure today before we ship :)

**Comment by alpaix** [comment]
Verified build agent running on the same vm (w2012r2) but not as a service completes build with no issues. That confirms my theory WPF code is not designed to run with windows service. So that's definitely not a bug.

**Comment by alpaix** [comment]
Quote from [msdn](https://msdn.microsoft.com/en-us/library/windows/desktop/cc817578%28v=vs.85%29.aspx):

> Note  WinINet does not support server implementations. In addition, it should not be used from a service. For server implementations or services use Microsoft Windows HTTP Services (WinHTTP).
