### ISSUE TITLE
Unable to load the service index for source https://www.myget.org/F/<id> ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden)

### ISSUE THREAD

**Issue by abatishchev** [NuGet/Home#2530]
Hi,
I'm using NuGet 3.5.0.1164 (dogfooding) in VS 2015.2 and get this exception when try to install an update:

```
Attempting to gather dependency information for multiple packages with respect to project 'Api', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for multiple packages.
Resolving actions install multiple packages
System.AggregateException: One or more errors occurred. ---> NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://www.myget.org/F/mpsit/auth/<id>/. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass21_0.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<GetAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.v3.ODataServiceDocumentResourceV2Provider.<CreateODataServiceDocumentResourceV2>d__9.MoveNext()
   --- End of inner exception stack trace ---
   at NuGet.Protocol.Core.v3.ODataServiceDocumentResourceV2Provider.<CreateODataServiceDocumentResourceV2>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.v3.ODataServiceDocumentResourceV2Provider.<TryCreate>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.PackageMetadataResourceV2FeedProvider.<TryCreate>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__11`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResource[T](CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResource[T]()
   at NuGet.PackageManagement.UI.UIActionEngine.<GetPackageMetadataAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<GetPackageMetadataAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<CheckLicenseAcceptanceAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()
---> (Inner Exception #0) NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://www.myget.org/F/mpsit/auth/b7f5804d-ed03-4d6d-858b-2942d4436c31/. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass21_0.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<GetAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.v3.ODataServiceDocumentResourceV2Provider.<CreateODataServiceDocumentResourceV2>d__9.MoveNext()
   --- End of inner exception stack trace ---
   at NuGet.Protocol.Core.v3.ODataServiceDocumentResourceV2Provider.<CreateODataServiceDocumentResourceV2>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.v3.ODataServiceDocumentResourceV2Provider.<TryCreate>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.PackageMetadataResourceV2FeedProvider.<TryCreate>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__11`1.MoveNext()<---
```

I think NuGet client should swallow such exception.

**Comment by yishaigalatzer** [comment]
@abatishchev can you explain the full scenario? Is it that you used credentials that are forbidden on the server, or is there something else going on?

**Comment by emgarten** [comment]
Gather here should throw if this is coming from the primary source. The stack trace should not be displayed here, this isn't a crash, just a normal protocol failure. 

@abatishchev was this from the UI or powershell?

**Comment by abatishchev** [comment]
@yishaigalatzer As I understand, MyGet has adopted v3 url format so in VS 2015 it should be now `https://www.myget.org/F/mpsit/auth/<id>/nuget/v3/index.json` rather than old, v2 one `https://www.myget.org/F/mpsit/auth/<id>`

The scenario is simple: Manage packages on the solution level, select Updates tab, select some packages (all except ApplicationInsights 2.0.1), press Update.

@emgarten: UI. Selected source is nuget.org, have MyGet enabled in MyGet.config next to the solution file, also few disabled sources in VS settings.

**Comment by emgarten** [comment]
This may be coming from the _ignore failing sources_ change in 3.5.0.

**Comment by yishaigalatzer** [comment]
@abatishchev can you explain why are you getting a 403? Are you providing invalid credentials?

**Comment by abatishchev** [comment]
This is how MyGet.com now behaves (at least for me, per my understanding): throws 403 for v3 client accessing v2 url.

**Comment by yishaigalatzer** [comment]
That's weird, can you share a fiddler feed?

**Comment by maartenba** [comment]
Also can you check the feed URL? It's  `https://www.myget.org/F/mpsit/auth/<id>/api/v3/index.json` - not `https://www.myget.org/F/mpsit/auth/<id>/nuget/v3/index.json`

**Comment by alpaix** [comment]
@abatishchev Thanks for reporting this issue.

**Current status.** @joelverhagen and I tried to reproduce the customer scenario but couldn't get exactly the same output with exception stack trace. We discovered many others where vague unclear error message was printed. My theory is that user's permissions were changed during open VisualStudio session.

**Action item.** Inspect all code paths where 403 can be returned and make sure actionable user error is shown.

**Comment by abatishchev** [comment]
Was it addressed, can the issue be closed?

**Comment by abatishchev** [comment]
Was it addressed, can the issue be closed?

**Comment by abatishchev** [comment]
@alpaix hi, was this addressed, can the issue be closed?

**Comment by alpaix** [comment]
We didn't address this particular issue but we made number of improvements in this area in v4.0+ and VS2017. VS2015 client will get a minor update only. Given the fact we couldn't repro your scenario locally we're going to need your help in re-validating this issue. Will you be able to install and run VS2017?

**Comment by abatishchev** [comment]
hi, i'm sorry, got missed your response! sure, i'm willing to help.

**Comment by zhili1208** [comment]
@abatishchev does this issue still repro in VS2017?

**Comment by abatishchev** [comment]
@zhili1208 I haven't see this for a while, I think it's safe to close the issues
