### ISSUE TITLE
[Watson] clr20r3: CLR_EXCEPTION_System.NullReferenceException_80004003_NuGet.PackageManagement.VisualStudio.dll!UNKNOWN

### ISSUE THREAD

**Issue by spadapet** [NuGet/Home#2539]
Cloned from:
https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=209288

When a user nuget.config or solution specific nuget.config file is invalid/corrupt, the NuGet Visual Studio package and extensions fail to load. Our VSSettings class ends up with a null SolutionSettings and throws a null exception when trying to use the settings.

The null exceptoin callstack is:

```
   at NuGet.PackageManagement.VisualStudio.VSSettings.GetSettingValues(String section, Boolean isPath) in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Clients\PackageManagement.VisualStudio\VSSettings.cs:line 92
   at NuGet.Configuration.PackageSourceProvider.LoadPackageSources() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Core\NuGet.Configuration\PackageSource\PackageSourceProvider.cs:line 80
   at NuGet.Protocol.VisualStudio.ExtensibleSourceRepositoryProvider.Init() in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Core\NuGet.Protocol.VisualStudio\VSSourceRepositoryProvider.cs:line 82
   at NuGet.Protocol.VisualStudio.ExtensibleSourceRepositoryProvider..ctor(IPackageSourceProvider packageSourceProvider, IEnumerable`1 resourceProviders) in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Core\NuGet.Protocol.VisualStudio\VSSourceRepositoryProvider.cs:line 51
   at NuGet.Protocol.VisualStudio.ExtensibleSourceRepositoryProvider..ctor(IEnumerable`1 resourceProviders, ISettings settings) in C:\BuildAgent\work\c0d8eb4bb9a1fa12\src\NuGet.Core\NuGet.Protocol.VisualStudio\VSSourceRepositoryProvider.cs:line 37
```

**Comment by spadapet** [comment]
I'm going to use the NullSettings.Instance object when failing to read any user nuget.config file. The error message probably needs to be updated to be more clear on what to do.

**Comment by spadapet** [comment]
Cherry picked into 3.4.3 release branches
