### ISSUE TITLE
Restore crashes with a null ref when attempting to restore "xunit"

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#2549]
Version: 3.4.0.785

Given the following an msbuild project with the following project.json:

```
{
  "dependencies": {
    "xunit": "2.1.0"
  },
  "frameworks": {
    ".NETPortable, Version=v4.5, Profile=Profile7": { }
  }
}
```

NuGet restore of this project crashes with the following:

```
Running restore with 8 concurrent jobs.
Reading project file C:\Analyzers\roslyn-analyzers\src\Dependencies\xUnit\project.json.
Restoring packages for C:\Analyzers\roslyn-analyzers\src\Dependencies\xUnit\project.json...
Restoring packages for .NETPortable,Version=v4.5,Profile=Profile7...
Resolving conflicts for .NETPortable,Version=v4.5,Profile=Profile7...
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Commands.RestoreTargetGraph.<>c__DisplayClass43_0.<Create>b__0(GraphNode`1 node)
   at NuGet.DependencyResolver.GraphOperations.<>c__DisplayClass9_0`1.<ForEach>b__0(GraphNode`1 node, Int32 _)
   at NuGet.DependencyResolver.GraphOperations.ForEach[TItem,TState](GraphNode`1 root, TState state, Func`3 visitor)
   at NuGet.DependencyResolver.GraphOperations.ForEach[TItem](GraphNode`1 root, Action`1 visitor)
   at NuGet.DependencyResolver.GraphOperations.ForEach[TItem](IEnumerable`1 roots, Action`1 visitor)
   at NuGet.Commands.RestoreTargetGraph.Create(Boolean writeToLockFile, RuntimeGraph runtimeGraph, IEnumerable`1 graphs, RemoteWalkContext context, ILogger log, NuGetFramework framework, String runtimeIdentifier)
   at NuGet.Commands.RestoreCommand.<WalkDependenciesAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.Commands.RestoreCommand.<TryRestore>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<>c__DisplayClass0_0.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.Commands.RestoreRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__23.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Commands.RestoreTargetGraph.<>c__DisplayClass43_0.<Create>b__0(GraphNode`1 node)
   at NuGet.DependencyResolver.GraphOperations.<>c__DisplayClass9_0`1.<ForEach>b__0(GraphNode`1 node, Int32 _)
   at NuGet.DependencyResolver.GraphOperations.ForEach[TItem,TState](GraphNode`1 root, TState state, Func`3 visitor)
   at NuGet.DependencyResolver.GraphOperations.ForEach[TItem](GraphNode`1 root, Action`1 visitor)
   at NuGet.DependencyResolver.GraphOperations.ForEach[TItem](IEnumerable`1 roots, Action`1 visitor)
   at NuGet.Commands.RestoreTargetGraph.Create(Boolean writeToLockFile, RuntimeGraph runtimeGraph, IEnumerable`1 graphs, RemoteWalkContext context, ILogger log, NuGetFramework framework, String runtimeIdentifier)
   at NuGet.Commands.RestoreCommand.<WalkDependenciesAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.Commands.RestoreCommand.<TryRestore>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<>c__DisplayClass0_0.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.Commands.RestoreRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__23.MoveNext()<---
```

If I replace xunit with "xunit.core", then everything succeeds.

**Comment by rrelyea** [comment]
@emgarten  - let's discuss

**Comment by davkean** [comment]
This project may have been called "xunit" - and might be related to: https://github.com/NuGet/Home/issues/2558

**Comment by emgarten** [comment]
project.json restore use to respect package id casing but we've since moved to case-insensitive. it looks like the circular dependency check was stuck in the middle of that. I've made it case-insensitive now.

NuGet/NuGet.Client@e4f6732d935c873d9feac7e146990a4e69c8ac47
