### ISSUE TITLE
Installation failures due to package not existing, but it does

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2559]
From email thread:
Sometimes, I’m getting installation failures that says a package doesn’t exist, but I know the package exist.
Every time it is a different package.

Example:
Adding package 'Fooservice.Tomsignal.library.1.0.0' to folder 'c:\temp\tests\SpeedBar_1\packages'
Added package 'Fooservice.Tomsignal.library.1.0.0' to folder 'c:\temp\tests\SpeedBar_1\packages'
Install failed. Rolling back...
Package 'Fooservice.Tomsignal.library.1.0.0 : createaqrplugin.product [1.0.0, 2.0.0), DataSchemas (, ), Platform.LegacyQueryResponseData [1.0.0, 2.0.0), Fooplatform.asyncplugins.product [1.0.0, 2.0.0), FooSdk (, ), Fooservice.cnavsignal.product [1.0.0, 2.0.0), Fooservice.ctex.product [1.0.0, 2.0.0), Fooservice.userannotation.product [1.0.0, 2.0.0)' does not exist in project 'entity_packages'

I’m installing from Visual Studio (using the Nuget Package manager UI)
I tried in 2 machines, one with VS 2015 Update 1 (with nuget 3.3), the other with VS 2015 Update 2 RC (with nuget 3.4). This happened on both machines, but it seems to happen more frequently on machine with nuget 3.3

Packages are in a VSO nuget feed.

Here is my latest repro call stack – I attached full output.
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at NuGet.Packaging.PackagesConfigWriter.WriteFile(String fullPath)
   at NuGet.Packaging.PackagesConfigWriter.Dispose()
   at NuGet.ProjectManagement.PackagesConfigNuGetProject.InstallPackageAsync(PackageIdentity packageIdentity, DownloadResourceResult downloadResourceResult, INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.ProjectManagement.MSBuildNuGetProject.<InstallPackageAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()
========== Finished ==========

Installing this package did succeed a few times, but it is failing quite frequently too.

(and, yes, it is a package with many dependencies and this is for a test – I did reduce # of packages by a lot by grouping but we will have a few projects using many packages and I need to understand when / what will break)

(and, yes, I’m using packages.config because I need to build these projects on an internal build system)

Installed 3.4.2
Error doesn’t have extra information

System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at NuGet.Packaging.PackagesConfigWriter.WriteFile(String fullPath)
   at NuGet.Packaging.PackagesConfigWriter.Dispose()
   at NuGet.ProjectManagement.PackagesConfigNuGetProject.InstallPackageAsync(PackageIdentity packageIdentity, DownloadResourceResult downloadResourceResult, INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.ProjectManagement.MSBuildNuGetProject.<InstallPackageAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()
========== Finished ==========

**Comment by emgarten** [comment]
NuGet/NuGet.Client@078a8589a43357dd38d427a8764e85fa2bf18de8
