### ISSUE TITLE
Nuget.exe fails when it is denied access to %APPDATA%\Nuget\NuGet.config

### ISSUE THREAD

**Issue by dannyvv** [NuGet/Home#2676]
I'm trying to run nuget in a restricted environment i.e. where nuget cannot be influenced by any installed state on the machine.
When I deny access to %APPDATA%\Nuget\NuGet.config
I get a crash of Nuget:

```
System.UnauthorizedAccessException: Access to the path 'C:\Users\dannyvv\AppData\Roaming\NuGet\NuGet.Config' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at NuGet.PhysicalFileSystem.AddFileCore(String path, Action`1 writeToStream)
   at NuGet.PhysicalFileSystem.AddFile(String path, Action`1 writeToStream)
   at NuGet.XmlUtility.CreateDocument(XName rootName, IFileSystem fileSystem, String path)
   at NuGet.XmlUtility.GetOrCreateDocument(XName rootName, IFileSystem fileSystem, String path)
   at NuGet.Settings.<>c__DisplayClass1.<.ctor>b__0()
   at NuGet.Settings.ExecuteSynchronized(Action ioOperation)
   at NuGet.Settings..ctor(IFileSystem fileSystem, String fileName, Boolean isMachineWideSettings)
   at NuGet.Settings.ReadSettings(IFileSystem fileSystem, String settingsPath, Boolean isMachineWideSettings)
   at NuGet.Settings.LoadUserSpecificSettings(List`1 validSettingFiles, IFileSystem fileSystem, String configFileName)
   at NuGet.Settings.LoadDefaultSettings(IFileSystem fileSystem, String configFileName, IMachineWideSettings machineWideSettings)
   at NuGet.ProxyCache.<.cctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at NuGet.CommandLine.Command.SetDefaultCredentialProvider()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

For file operations nuget should protected against IOException and UnauthorizedAccessException.
In this case I'd like nuget to just ignore the file and treat it like empty. 
But the bare bare minium should be a better user error message rather than a crash.

**Comment by zhili1208** [comment]
@dannyvv what's the nuget.exe version you are using?

**Comment by dannyvv** [comment]
D:\temp\nugettest>nuget.exe
NuGet Version: 3.4.0.653

**Comment by zhili1208** [comment]
Can you try 3.4.3 from here: https://dist.nuget.org/index.html?

**Comment by rrelyea** [comment]
@yishaigalatzer will reach out to discuss the scenario.

Our plan for a fix: don't throw...but do give real error message.

**Comment by jainaashish** [comment]
Please try with latest NuGet, and let us know if this is still an issue.
