### ISSUE TITLE
Portable frameworks with hyphenated profiles are rejected.

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2734]
Prompted by https://github.com/NuGet/Home/issues/2711.

This change was made with #1869. It broke some existing packages (e.g. [ReadOnlySourceTree 0.1.24-beta](https://www.nuget.org/packages/ReadOnlySourceTree/0.1.24-beta)). 

If we are okay with this breaking change, we should clearly communicate this to the user by a) improving the error message and b) mentioning this in our docs.

@rrelyea @yishaigalatzer

**Comment by joelverhagen** [comment]
Some scenarios to consider:
1. What happens if a feed (local v2? local v3? remote v2? remote v3?) has an invalid portable framework in an older version of the package? can the user still use the UI to upgrade out of the bad version?
2. If there is no fixed version of the package, what else can the user do? Is the only option contacting the package owner about fixing the package in a newer version?

**Comment by joelverhagen** [comment]
Tested some different cases in current `dev`.
- Works
  - Browsing V2 remote
  - Browsing V3 remote
  - Browsing V2 local
  - Browsing V3 local
  - Installing, updating, and uninstalling a "good" version of a package that has a "bad" version.
  - Restoring a "bad" version
- Broken
  - If the user already has a version with `net-cf` installed, they cannot uninstall or update.

**Comment by joelverhagen** [comment]
Uninstall has this stack trace when failing:

```
Attempting to gather dependency information for package 'ReadOnlySourceTree.0.1.24-beta' with respect to project 'ConsoleApplication6', targeting '.NETFramework,Version=v4.6.1'
Resolving actions to uninstall package 'ReadOnlySourceTree.0.1.24-beta'
Resolved actions to uninstall package 'ReadOnlySourceTree.0.1.24-beta'
Install failed. Rolling back...
Package 'ReadOnlySourceTree.0.1.24-beta' already exists in project 'ConsoleApplication6'
Executing nuget actions took 25.56 ms
System.ArgumentException: Invalid portable frameworks.
   at NuGet.Frameworks.FrameworkNameProvider.TryGetPortableFrameworks(String shortPortableProfiles, IEnumerable`1& frameworks)
   at NuGet.Frameworks.NuGetFramework.ParseFolder(String folderName, IFrameworkNameProvider mappings)
   at NuGet.Packaging.PackageReaderBase.GetFrameworkFromPath(String path, Boolean allowSubFolders)
   at NuGet.Packaging.PackageReaderBase.<GetFileGroups>d__29.MoveNext()
   at NuGet.Packaging.PackageReaderBase.GetBuildItems()
   at NuGet.ProjectManagement.MSBuildNuGetProject.<UninstallPackageAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteUninstallAsync>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()
========== Finished ==========
```

**Comment by joelverhagen** [comment]
The fix we applied here is to improve the error message that appears to the user when a package contains this invalid framework. More details on the PR:
https://github.com/NuGet/NuGet.Client/issues/715
