### ISSUE TITLE
Passing -IncludeReferencedProjects does not honor Configuration property

### ISSUE THREAD

**Issue by heaths** [NuGet/Home#2824]
We build a couple nupkgs during project build that result in a command line like:

```
"C:\src\.nuget\NuGet.exe" pack "C:\src\Foo\Foo.csproj" -Properties "Configuration=Release;Platform=AnyCPU" -NonInteractive -IncludeReferencedProjects -OutputDirectory "C:\src\Foo\bin\Release" -symbols
```

This should be picking up project references - some of which also have corresponding _.nuspec_ files, but despite passing `Configuration` we get the following error in a clean build:

```
Unable to find 'C:\src\Bar\bin\Debug\Bar.dll'. Make sure the project has been built.
```

Seems that Configuration isn't considered when processing referenced projects. If I define an environment variable like `set Configuration=Release` the command works.

**Comment by heaths** [comment]
Forgot to add that I'm using 3.4.3.855 and the stack trace follows:

```
NuGet.CommandLineException: Unable to find 'C:\src\Bar\bin\Debug\Bar.dll'. Make sure the project has been built.
   at NuGet.CommandLine.ProjectFactory.BuildProject()
   at NuGet.CommandLine.ProjectFactory.RecursivelyApply(Action`1 action, Object alreadyAppliedProjects)
   at NuGet.CommandLine.ProjectFactory.RecursivelyApply(Action`1 action)
   at NuGet.CommandLine.ProjectFactory.ApplyAction(Action`1 action)
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath)
   at NuGet.CommandLine.PackCommand.BuildFromProjectFile(String path)
   at NuGet.CommandLine.PackCommand.BuildPackage(String path)
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

A bit more information: we have common _props_ and _targets_ files that default `Configuration` (like the default _csproj_) but I also tried adding them seeing in code (albeit based on HEAD) how properties are being read, but that made no difference to the outcome.

**Comment by EamonHetherton** [comment]
I have encountered this too. Given the age of the bug I'm not holding my breath for a fix.

My workaround at the moment is to force my dependent projects to build as Release in their csproj file as so far I only ever pack release builds.

**Comment by i-am-shodan** [comment]
Just wanted to say that this is an issue for me and your workaround does work. Thanks so much!
