### ISSUE TITLE
Possible race condition in ConcurrencyUtilities.ExecuteWithFileLockedAsync

### ISSUE THREAD

**Issue by pranavkm** [NuGet/Home#2829]
Saw this on our build agent:

```
System.AggregateException: One or more errors occurred. (The process cannot access the file because another process has locked a portion of the file) ---> System.IO.IOException: The process cannot access the file because another process has locked a portion of the file
error:    at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
error:    at NuGet.DependencyResolver.SourceRepositoryDependencyProvider.<CopyToAsync>d__16.MoveNext()
error:    at NuGet.Packaging.PackageExtractor.<>c__DisplayClass2_0.<<InstallFromSourceAsync>b__0>d.MoveNext()
error:    at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__0`1.MoveNext()
error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
error:    at NuGet.Packaging.PackageExtractor.<InstallFromSourceAsync>d__2.MoveNext()
error:    at NuGet.Commands.ProjectRestoreCommand.<InstallPackageAsync>d__8.MoveNext()
error:    at NuGet.Commands.ProjectRestoreCommand.<>c__DisplayClass7_1.<<InstallPackagesAsync>b__2>d.MoveNext()
error:    at NuGet.Commands.ProjectRestoreCommand.<InstallPackagesAsync>d__7.MoveNext()
error:    at NuGet.Commands.ProjectRestoreCommand.<TryRestore>d__3.MoveNext()
error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
error:    at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d__14.MoveNext()
error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
error:    at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__8.MoveNext()
error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
error:    at NuGet.Commands.RestoreRunner.<Execute>d__1.MoveNext()
error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
error:    at NuGet.Commands.RestoreRunner.<>c__DisplayClass0_0.<<Run>b__0>d.MoveNext()
error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
error:    at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__2.MoveNext()
error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
error:    at NuGet.Commands.RestoreRunner.<Run>d__0.MoveNext()
error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
error:    at NuGet.CommandLine.XPlat.RestoreCommand.<>c__DisplayClass0_1.<<Register>b__1>d.MoveNext()
```

**Comment by rrelyea** [comment]
What OS did this build agent run on?
Have you seen it more than once?

**Comment by pranavkm** [comment]
This was a Win2012 machine. It might've been one off since we haven't seen too many restore failures.

**Comment by emgarten** [comment]
This hasn't come up again. At this point I think it has been fixed.
