### ISSUE TITLE
API Key in config does not correctly transfer from v3 to v2 for push

### ISSUE THREAD

**Issue by jmyersmsft** [NuGet/Home#2975]
It appears that when you try to push a package using the v3 protocol, an API key set for that URL isn't used. Instead, it looks for an API key for the v2 URL from the PackagePublish resource in index.json.

NuGet Version: 3.4.4.1321

```
PS>.\nuget344.exe push MyPackage.1.0.0.nupkg -source https://my-vsts-account.pkgs.visualstudio.com/DefaultCollection/_packaging/jmyers-test6/nuget/v3/index.json -verbosity detailed
WARNING: No API Key was provided and no API Key could be found for 'https://my-vsts-account.pkgs.visualstudio.com/DefaultCollection/_packaging/d2370e04-786b-4806-ab18-976aeaa518da/nuget/v2/'. To save an API Key for a source use the 'setApiKey' command.
Pushing MyPackage.1.0.0.nupkg to 'https://my-vsts-account.pkgs.visualstudio.com/DefaultCollection/_packaging/d2370e04-786b-4806-ab18-976aeaa518da/nuget/v2/'...
  PUT https://my-vsts-account.pkgs.visualstudio.com/DefaultCollection/_packaging/d2370e04-786b-4806-ab18-976aeaa518da/nuget/v2/
  Unauthorized https://my-vsts-account.pkgs.visualstudio.com/DefaultCollection/_packaging/d2370e04-786b-4806-ab18-976aeaa518da/nuget/v2/ 642ms
  PUT https://my-vsts-account.pkgs.visualstudio.com/DefaultCollection/_packaging/d2370e04-786b-4806-ab18-976aeaa518da/nuget/v2/
  BadRequest https://my-vsts-account.pkgs.visualstudio.com/DefaultCollection/_packaging/d2370e04-786b-4806-ab18-976aeaa518da/nuget/v2/ 978ms
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__16.MoveNext()<---
```

```
PS>.\nuget344.exe setapikey VSTS -source https://my-vsts-account.pkgs.visualstudio.com/DefaultCollection/_packaging/jmyers-test6/nuget/v3/index.json
The API Key 'VSTS' was saved for 'https://my-vsts-account.pkgs.visualstudio.com/DefaultCollection/_packaging/jmyers-test6/nuget/v3/index.json'.
```

```
PS>.\nuget344.exe push MyPackage.1.0.0.nupkg -source https://my-vsts-account.pkgs.visualstudio.com/DefaultCollection/_packaging/jmyers-test6/nuget/v3/index.json -verbosity detailed
WARNING: No API Key was provided and no API Key could be found for 'https://my-vsts-account.pkgs.visualstudio.com/DefaultCollection/_packaging/d2370e04-786b-4806-ab18-976aeaa518da/nuget/v2/'. To save an API Key for a source use the 'setApiKey' command.
Pushing MyPackage.1.0.0.nupkg to 'https://my-vsts-account.pkgs.visualstudio.com/DefaultCollection/_packaging/d2370e04-786b-4806-ab18-976aeaa518da/nuget/v2/'...
  PUT https://my-vsts-account.pkgs.visualstudio.com/DefaultCollection/_packaging/d2370e04-786b-4806-ab18-976aeaa518da/nuget/v2/
  Unauthorized https://my-vsts-account.pkgs.visualstudio.com/DefaultCollection/_packaging/d2370e04-786b-4806-ab18-976aeaa518da/nuget/v2/ 738ms
  PUT https://my-vsts-account.pkgs.visualstudio.com/DefaultCollection/_packaging/d2370e04-786b-4806-ab18-976aeaa518da/nuget/v2/
  BadRequest https://my-vsts-account.pkgs.visualstudio.com/DefaultCollection/_packaging/d2370e04-786b-4806-ab18-976aeaa518da/nuget/v2/ 750ms
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__16.MoveNext()<---
```

**Comment by zhili1208** [comment]
I think this is same issue as https://github.com/NuGet/Home/issues/2627
