### ISSUE TITLE
Errors in VS 15 Preview 3

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#3073]
Filing on behalf of @zooba

Not sure this is the right place, but it was easiest to find.

I'm seeing this error in the ActivityLog.xml and a "failed to load extension" dialog box occasionally in VS 15 Preview 3:

CreateInstance failed for package [NuGetPackage]Source: 'mscorlib' Description: Exception has been thrown by the target of an invocation. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: InitializePackageServiceProvider must be called on the UI thread.
 at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)
 at NuGet.PackageManagement.VisualStudio.ServiceLocator.InitializePackageServiceProvider(IServiceProvider provider)
 at NuGetVSExtension.NuGetPackage..ctor() --- End of inner exception stack trace ---
 at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
 at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
 at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
 at System.Activator.CreateInstance(Type type, Boolean nonPublic)
 at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
 at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
 at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
 at System.Activator.CreateInstance(String assemblyName, String typeName)
 at System.AppDomain.CreateInstance(String assemblyName, String typeName)System.Runtime.InteropServices.COMException (0x8001010E): InitializePackageServiceProvider must be called on the UI thread.
 at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)
 at NuGet.PackageManagement.VisualStudio.ServiceLocator.InitializePackageServiceProvider(IServiceProvider provider)
 at NuGetVSExtension.NuGetPackage..ctor()
It's seemingly random, but I wasn't deliberately trying to use Nuget at all - it just appeared.

**Comment by drewgillies** [comment]
@zooba --any details you can give us about the steps that led to this failure would be very helpful in reproducing it ourselves (and fixing), including:
Was preview 3 installed over the top of another VS 15 preview?
If so, had you installed any other versions of the NuGet extension to Vs prior to installing preview 3?
Essentially, anything you can think of that might make your scenario unique or rare.

**Comment by zooba** [comment]
No shortage of things that make me unique here :) But it was a clean install using the classic installer on a clean VM and I didn't touch Nuget at all, so it shouldn't have had any other versions unless it updated automatically. (Very slight chance I may not have had the actual Preview 3 - build number is 25424.00 from Preview, but it should be essentially Preview 3 at this stage :) )

I was running our automated tests for https://github.com/Microsoft/PTVS, which restart VS a lot (since it currently crashes a lot...). None of our tests exercise Nuget directly (since last time we tried to get support it was rejected), but presumably there is some autoloading going on when we open various projects (we do open C# and C++ projects in a few tests, which may have triggered it - I wasn't watching when this happened).

Judging from the error and the fact that I've only seen it once or twice in a few days of testing, it's a fairly rare race condition. But since VS is the only one that constructs packages, you've either got an explicit instantiation somewhere or there's a VS bug. Alternatively, you may just want to avoid functionality in the package constructor that relies on VS - that's what the `Initialize` method is for. I couldn't find the actual source for the package so I can't be more specific I'm afraid :)

The best repro I can suggest involves repeatedly restarting VS and doing anything that may directly or indirectly load your package. As I'm sure you're aware, race conditions are notoriously hard to reproduce on demand.

**Comment by drewgillies** [comment]
I see. One thing that springs to mind with this release is that there is an issue (this one: https://github.com/NuGet/Home/issues/2369) relating to creating/restoring anything that utilizes the common project system (in this case, C++). We get a pretty large failure in these cases--it is fixed, but the fix isn't in preview 3. I can see this throwing VS into a state which could precipitate bizarre errors like this.

So, 2 thoughts occur to me:
- I can get you a private build with the fix in to see if this addresses the problem. Please reach out to me (alias drewgil) and we can set this up
- I'm concerned by this: "last time we tried to get support it was rejected" --can we also talk about this offline and see if there's anything outstanding there?

**Comment by drewgillies** [comment]
Discussed offline. Filer is happy to close this for now. If Dev15 VSIX doesn't fix the problem we can re-investigate.

**Comment by davkean** [comment]
This caused by https://github.com/NuGet/Home/issues/3073.
