### ISSUE TITLE
nuget.exe fails to restore from the home directory

### ISSUE THREAD

**Issue by AndreyAkinshin** [NuGet/Home#3093]
Repro:

```
C:\Users\jetbrains> nuget restore -Verbosity detailed
System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\jetbrains\AppData\Local\Application Data' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at NuGet.CommandLine.RestoreCommand.GetInputsFromDirectory(String directory, PackageRestoreInputs packageRestoreInputs)
   at NuGet.CommandLine.RestoreCommand.DetermineRestoreInputs()
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__23.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\jetbrains\AppData\Local\Application Data' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at NuGet.CommandLine.RestoreCommand.GetInputsFromDirectory(String directory, PackageRestoreInputs packageRestoreInputs)
   at NuGet.CommandLine.RestoreCommand.DetermineRestoreInputs()
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__23.MoveNext()<---
```

**Comment by AndreyAkinshin** [comment]
Here is the exception origin: https://github.com/NuGet/NuGet.Client/blob/90d885f025ede1be661dbd60c182f23862a070ca/src/NuGet.Clients/NuGet.CommandLine/Commands/RestoreCommand.cs#L565:

``` cs
// Project.json is any directory
if (Directory.GetFiles(
    directory,
    $"*{ProjectJsonPathUtilities.ProjectConfigFileName}",
    SearchOption.AllDirectories).Length > 0)
{
    // V3 recursive project.json search
    packageRestoreInputs.RestoreV3Context.Inputs.Add(directory);

    return;
}
```

**Comment by AndreyAkinshin** [comment]
Even the code

``` cs
Directory.GetFiles(Environment.GetFolderPath(
    Environment.SpecialFolder.UserProfile), "*", SearchOption.AllDirectories)
```

throws the same exception. Also, `Directory.GetFiles` with `SearchOption.AllDirectories` can be a **very** expensive call and take a lot of time. I suggest the following solution: we can implement the recursion manually (with try-catch blocks) + check that if there is at least one file which matches the given `searchPattern`. The implementation:

``` cs
private static bool HasFilesInAllDirectories(string path, string searchPattern)
{
  try
  {
    if (Directory.GetFiles(path, searchPattern, SearchOption.TopDirectoryOnly).Any())
      return true;
  }
  catch (UnauthorizedAccessException)
  {
  }
  try
  {
    return Directory.GetDirectories(path)
                    .Any(subDir => HasFilesInAllDirectories(subDir, searchPattern));
  }
  catch (UnauthorizedAccessException)
  {
  }
  return false;
}
```

Profit:
1. We don't have UnauthorizedAccessExceptions anymore.
2. It works much faster than `Directory.GetFiles(...).Length > 0` (milliseconds instead of minutes for a folder with big amount of files).

**Comment by emgarten** [comment]
Typically restore is run against the root of a repository to restore all projects. Can you share some details on why you would want to run a restore on your home directory like this?

Failing silently and ignoring directories that cannot be accessed could be confusing later when projects in those directories aren't restored.

Longer term once .NET Core moves to using MSBuild dotnet restore will likely use solutions to discover projects instead of recursively searching the directory.

Related: https://github.com/NuGet/Home/issues/3038

**Comment by AndreyAkinshin** [comment]
@emgarten, I did it accidentally. Other users also can run `nuget.exe` from the wrong place accidentally. In this case, `nuget.exe` shouldn't throw an incomprehensible exception with a strange stacktrace. Also, `nuget.exe` shouldn't spend minutes browsing all the files in the directory (a case with a directory without `project.json` in the root and with a lot of files in subfolders).

**Comment by rrelyea** [comment]
I ran "nuget restore" on my C:\ and c:\users\rob -- both failed within 1-3 seconds with a good error message. I agree that the stack trace is a bit much, but verbosity detailed appears to have added it.

Will make some comments in your PR.

**Comment by emgarten** [comment]
Fixed with @AndreyAkinshin's PR 
NuGet/nuget.client@895c82b366d72d2484f49559801d41e004d1d7f1
