### ISSUE TITLE
Exception in Test output window

### ISSUE THREAD

**Issue by mlorbetske** [NuGet/Home#3095]
Created on behalf of @rynowak

I'm getting this exception stack trace during test discovery on the aspnet/Routing repo

```
System.ArgumentException: '1.0.0-*' is not a valid version string.
Parameter name: value
   at NuGet.Versioning.NuGetVersion.Parse(String value)
   at NuGet.PackageManagement.VisualStudio.ProjectKNuGetProject.<GetInstalledPackagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstallerServices.<>c__DisplayClass7_0.<<GetInstalledPackages>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages()
   at Microsoft.VisualStudio.TestWindow.VsAdapters.UnitTestExtensionDiscoverer.GetAllEnabledExtensions(ILogger log)
```

As far as I can tell, testing is still working as expected

Repro:
- clone routing
- run build.cmd at the command line
- open routing.sln
- open test window
- do a build in VS to trigger test discovery

**Comment by yishaigalatzer** [comment]
@joelverhagen this does look like a dup of #3070 .

Workaround use tooling without \* notation for now
