### ISSUE TITLE
Linux build.sh nuget location?

### ISSUE THREAD

**Issue by vindicatorr** [NuGet/Home#3120]
Branch dev
Archlinux

I see the script:
1) downloads dotnet (if the distribution is included in the list (archlinux is not))
2) installs dotnet
3) echos the dotnet version
4) does some git stuff for submodules (that don't seem to do anything)
5) clears out the packages "cache" in ~/.nuget (if specified)
6) restores nuget packages using "dotnet"
7) finally runs tests using the "dotnet" command.

I don't see where the nuget executable is being built

Looking at the build script in the "common" submodule, I see reference to the old dnvm/dnx.
Seeing this, I would have asked if linux was still being supported (I'd expect so), but when I saw toddm had done some updates 18 days ago, I'd have to say that it is.
I just don't know where nuget actually gets built.

When the tests are run, I only see 1 Failure with Nuget.Commands.Test

```
$ grep "Failed: " build1.log 
   NuGet.Client.Test  Total: 31, Errors: 0, Failed: 0, Skipped: 0, Time: 0.389s
   NuGet.Commands.Test  Total: 161, Errors: 0, Failed: 1, Skipped: 0, Time: 2.266s
   NuGet.Common.Test  Total: 132, Errors: 0, Failed: 0, Skipped: 0, Time: 5.072s
   NuGet.Configuration.Test  Total: 182, Errors: 0, Failed: 0, Skipped: 0, Time: 0.783s
   NuGet.DependencyResolver.Core.Tests  Total: 2, Errors: 0, Failed: 0, Skipped: 0, Time: 2.269s
   NuGet.DependencyResolver.Tests  Total: 64, Errors: 0, Failed: 0, Skipped: 0, Time: 0.401s
   NuGet.Frameworks.Test  Total: 1242, Errors: 0, Failed: 0, Skipped: 0, Time: 0.653s
   NuGet.LibraryModel.Tests  Total: 28, Errors: 0, Failed: 0, Skipped: 0, Time: 0.178s
   NuGet.Packaging.Core.Test  Total: 22, Errors: 0, Failed: 0, Skipped: 0, Time: 0.165s
   NuGet.Packaging.Test  Total: 320, Errors: 0, Failed: 0, Skipped: 0, Time: 0.954s
   NuGet.ProjectModel.Test  Total: 101, Errors: 0, Failed: 0, Skipped: 0, Time: 0.359s
   NuGet.Protocol.Core.v3.Tests  Total: 435, Errors: 0, Failed: 0, Skipped: 0, Time: 3.773s
   NuGet.Resolver.Test  Total: 73, Errors: 0, Failed: 0, Skipped: 0, Time: 16.167s
   NuGet.RuntimeModel.Test  Total: 15, Errors: 0, Failed: 0, Skipped: 0, Time: 0.276s
   NuGet.Synchronization.Test  Total: 6, Errors: 0, Failed: 0, Skipped: 2, Time: 0.206s
   NuGet.Versioning.Test  Total: 607, Errors: 0, Failed: 0, Skipped: 0, Time: 0.351s
```

```
xUnit.net Runner (64-bit arch.-x64)
  Discovering: NuGet.Commands.Test
  Discovered:  NuGet.Commands.Test
  Starting:    NuGet.Commands.Test
    NuGet.Commands.Test.ContentFilesTests.ContentFiles_VerifyNearestTFMPerLanguage [FAIL]
      Assert.Equal() Failure
                                       ↓ (pos 28)
      Expected: ···iles/any/net40/image.jpg|contentFiles/any/net40/image2.jpg
      Actual:   ···iles/any/net40/image2.jpg|contentFiles/any/net40/image.jpg
                                       ↑ (pos 28)
      Stack Trace:
        /home/username/Desktop/tmp/source/NuGet.Client/test/NuGet.Core.Tests/NuGet.Commands.Test/ContentFilesTests.cs(540,0): at NuGet.Commands.Test.ContentFilesTests.<ContentFiles_VerifyNearestTFMPerLanguage>d__5.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Finished:    NuGet.Commands.Test
```

The prebuilt nuget.exe (v3.5.0) runs with mono, but not with dotnet:

```
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/username/Desktop'.
```

**Comment by PatoBeltran** [comment]
Closing this issue. The latest nuget can be build on linux by running the ./build.sh script. You'll need to have dotnet installed.
