### ISSUE TITLE
nuget pack does not work if you change the name of the exe

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#3146]
Repros in 3.5.0-beta2 and nightly builds. 

Throws the error:
Could not load file or assembly 'NuGet, Version=3.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by emgarten** [comment]
Would you paste the stack trace by running with `-verbosity detailed`

**Comment by rohit21agrawal** [comment]
@emgarten 

```
System.IO.FileNotFoundException: Could not load file or assembly 'NuGet, Version=3.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'NuGet, Version=3.5.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName)
   at NuGet.Runtime.AppDomainExtensions.CreateInstance[T](AppDomain domain) in D:\forks\nuget\src\CommandLine\Commands\HelpCommandMarkdownTemplate.cshtml:line 0
   at NuGet.CommandLine.AssemblyMetadataExtractor.GetMetadata(String assemblyPath) in D:\nuget\NuGet.Client\src\NuGet.Clients\NuGet.CommandLine\Commands\Pack\AssemblyMetadataExtractor.cs:line 27
   at NuGet.CommandLine.AssemblyMetadataExtractor.ExtractMetadata(PackageBuilder builder, String assemblyPath) in D:\nuget\NuGet.Client\src\NuGet.Clients\NuGet.CommandLine\Commands\Pack\AssemblyMetadataExtractor.cs:line 38
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded) in D:\nuget\NuGet.Client\src\NuGet.Clients\NuGet.CommandLine\Commands\ProjectFactory.cs:line 210

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

System.Exception: Failed to build package. D:\temp\projects\NuGetPackDependencyBug\ProjectA\ProjectA.csproj
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path) in D:\forks\nuget\src\CommandLine\Commands\HelpCommandMarkdownTemplate.cshtml:line 0
   at NuGet.Commands.PackCommandRunner.BuildPackage(String path) in D:\forks\nuget\src\CommandLine\Commands\HelpCommandMarkdownTemplate.cshtml:line 0
   at NuGet.Commands.PackCommandRunner.BuildPackage() in D:\forks\nuget\src\CommandLine\Commands\HelpCommandMarkdownTemplate.cshtml:line 0
   at NuGet.CommandLine.PackCommand.ExecuteCommand() in D:\nuget\NuGet.Client\src\NuGet.Clients\NuGet.CommandLine\Commands\PackCommand.cs:line 153
   at NuGet.CommandLine.Command.ExecuteCommandAsync() in D:\nuget\NuGet.Client\src\NuGet.Clients\NuGet.CommandLine\Commands\Command.cs:line 189
   at NuGet.CommandLine.Command.Execute() in D:\nuget\NuGet.Client\src\NuGet.Clients\NuGet.CommandLine\Commands\Command.cs:line 129
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args) in D:\nuget\NuGet.Client\src\NuGet.Clients\NuGet.CommandLine\Program.cs:line 130
```

**Comment by rohit21agrawal** [comment]
getting different stack trace now : 
[NugetBug.zip](https://github.com/NuGet/Home/files/719751/NugetBug.zip)



```D:\temp\issue4234\NugetBug>nuget-3.5.exe pack "NugetBug.csproj" -Properties Configuration=Release -Verbosity detailed -Symbols -Version "2.0.0"
NuGet Version: 3.5.0.1938
Attempting to build package from 'NugetBug.csproj'.
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from 'D:\temp\issue4234\NugetBug\bin\Release'.
Using 'NugetBug.nuspec' for metadata.
System.Exception: Authors is required.
Description is required.
   at NuGet.Packaging.Manifest.Validate(Manifest manifest)
   at NuGet.Packaging.Manifest.ReadFrom(Stream stream, Func`2 propertyProvider, Boolean validateSchema)
   at NuGet.CommandLine.ProjectFactory.ProcessNuspec(PackageBuilder builder, String basePath)
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage()
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)```

**Comment by nkolev92** [comment]
Closing as dup of https://github.com/NuGet/Home/issues/4234 as it's more popular.
