### ISSUE TITLE
NuGet.PackageManagement: Fail to install package with "an error occurred while sending the request" error

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#322]
Repro steps:
1. create a new class library project
2. start PMC, type install-package Microsoft.aspnet.mvc -version 5.0.0

Expected: works fine

Actual:

System.InvalidOperationException occurred
  HResult=-2146233079
  Message=An error occurred while sending the request.
  Source=NuGet.PackageManagement
  StackTrace:
       at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__97.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__79.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at NuGet.PackageManagement.PowerShellCmdlets.PackageActionBaseCommand.<InstallPackageByIdentityAsync>d__4.MoveNext() in f:\dd\git\NuGet.VisualStudioExtension\src\PackageManagement.PowerShellCmdlets\PackageActionBaseCommand.cs:line 94
  InnerException: System.Net.Http.HttpRequestException
       HResult=-2146233088
       Message=An error occurred while sending the request.
       Source=mscorlib
       StackTrace:
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.Protocol.Core.v3.DependencyInfo.ResolverMetadataClient.<LoadResource>d__2.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.Protocol.Core.v3.DependencyInfo.ResolverMetadataClient.<GetRegistrationInfo>d__3.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.Protocol.Core.v3.DependencyInfo.ResolverMetadataClient.<InlineDependencies>d__1.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
            at NuGet.Protocol.Core.v3.DependencyInfo.ResolverMetadataClient.<GetTree>d__0.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.Protocol.Core.v3.DependencyInfoResourceV3.<GetPackagesFromRegistration>d__7.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.Protocol.Core.v3.DependencyInfoResourceV3.<ResolvePackages>d__5.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.PackageManagement.ResolverGather.<>c__DisplayClass31.<<ProcessMissingPackageIdentities>b__2a>d__33.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.PackageManagement.ResolverGather.<ProcessMissingPackageIdentities>d__36.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
            at NuGet.PackageManagement.ResolverGather.<GatherPackageDependencyInfo>d__14.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.PackageManagement.ResolverGather.<GatherPackageDependencyInfo>d__3.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__97.MoveNext()
       InnerException: System.Net.WebException
            HResult=-2146233079
            Message=*The remote name could not be resolved: 'api.nuget'*
            Source=System
            StackTrace:
                 at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                 at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
            InnerException:

**Comment by danliu** [comment]
Note the message says "The remote name could not be resolved: 'api.nuget'

Looks like we are passing the wrong name here.

**Comment by deepakaravindr** [comment]
No repro now. Closing the issue
