### ISSUE TITLE
NullReferenceException in VS 2015 CTP6 in InstallPackages against local NuGet repo

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#326]
moved from https://github.com/NuGet/NuGetGallery/issues/2374
This is the error I see (below). Our ASP.NET MVC web site is hosting NuGet.Server 2.8.3. I do not see an update for this package. Perhaps this is a mismatch between the 3.0 client and the server that will get fixed when someone drops an update for NuGet.Server?
Error occured:\nSystem.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.PackageManagement.UI.PackageLoader.<>c__DisplayClass1a.<<SearchInstalled>b__10>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.UI.PackageLoader.<SearchInstalled>d__2a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.PackageLoader.<Search>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.PackageLoader.<LoadItems>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.InfiniteScrollList.<<LoadWork>b__7>d__9.Move

**Comment by zhili1208** [comment]
@rkeithhill  I moved this issue here

**Comment by feiling** [comment]
@rkeithhill, could you tell us what are the repro steps?

**Comment by rkeithhill** [comment]
Hmm, I don't get the NullReferenceException anymore.  However, CTP6 is not showing *any* of the NuGet packages that are hosted on our internal NuGet server.  The packages do show up just fine in Visual Studio 2013.

Will we need an updated version of the NuGet.Server package for our ASP.NET MVC website, in order to work with Visual Studio 2015?

**Comment by yishaigalatzer** [comment]
We don't think so. Your VS 2015 should work fine against your server. Can you give us access to your server? Or at least share some more information on your setup.

(Cool bike btw :) )

**Comment by rkeithhill** [comment]
I'm simply running an ASP.NET MVC4 (on .NET 4.0) on Windows Server 2008 SP2 that has the NuGet.Server 2.8.3 nuget pkg installed. The NuGet server setup points to a network share where we drop NuGet pkgs.  As I said, this works fine from VS 2013 U4 but I get bupkis on VS 2015 CTP6.

**Comment by yishaigalatzer** [comment]
Ctp6 was hmm buggy. This should work fine for rc. If not let us know. If we can get access to your packages we can also verify it for you (please reopen if you can help with the scenario or this fails in rc). 

350xcf here :)
