### ISSUE TITLE
IVsPackageInstaller InstallPacakge API with source as null throwing exception

### ISSUE THREAD

**Issue by navin22** [NuGet/Home#3368]
We are using the Nuget Visual Studio extension service IVsPackageInstaller service to install the package dynamically. We are using the following method particularly.

`VsPackageInstaller installer = (IVsPackageInstaller)componentModel.GetService<IVsPackageInstaller>();   installer.InstallPackage(null, project, packageId, packageVersion, false);`

This was working fine with package source as null. But suddenly it started breaking with the below exception. Is this regression ?

```
Initialization method InitializeTests threw exception. System.ArgumentException: System.ArgumentException: primarySources.

Stack Trace : 
Server stack trace: 
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalCoreAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   at Microsoft.Test.Apex.VisualStudio.NuGet.NuGetPackageManagerTestService.InstallPackage(String source, ProjectTestExtension project, String packageName, String packageVersion) in NuGetPackageManagerTestService.cs:line 90
   at Microsoft.Test.Apex.VisualStudio.NuGet.NuGetPackageManagerTestService.InstallPackage(ProjectTestExtension project, String packageName, String packageVersion) in NuGetPackageManagerTestService.cs:line 74
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Test.Apex.VisualStudio.NuGet.NuGetPackageManagerTestService.InstallPackage(ProjectTestExtension project, String packageName, String packageVersion)
   at MS.TLM.Test.UnitTesting.SmokeTests.DesktopCSharpTests.InitializeTests() in DesktopCSharpTests.cs:line 51
```

**Comment by emgarten** [comment]
> This was working fine with package source as null. But suddenly it started breaking with the below exception

What changed around the time this started?

What version of NuGet and what version of Visual Studio are you using?

**Comment by navin22** [comment]
We are using Visual Studio Enterprise 15 Preview.
And NuGet Package Manager for Visual Studio 15 Extension.

**Comment by emgarten** [comment]
Which version of NuGet?

**Comment by navin22** [comment]
NuGet Package Manager 3.5.0

**Comment by navin22** [comment]
@emgarten : Any update on this ?

**Comment by drewgillies** [comment]
@navin22 Are you running Visual Studio 15 Preview 1, 2, 3 or 4?

**Comment by navin22** [comment]
Preview 5

**Comment by drewgil** [comment]
@navin22 - can you please send a hello mail to support@nuget.org? I want to get some details from you directly and need your name.

**Comment by rrelyea** [comment]
Closing per email communication with the team. They were able to resolve the issue. Will ask them to add more info to this issue, to help other folks who may run into this in the future.
