### ISSUE TITLE
CTP6 bug (ported from CodePlex)

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#340]
https://nuget.codeplex.com/workitem/4475

To reproduce the error: 

 Create a portable DLL class Profile 259 

 Try to install json.net 6.0.8 

 Package Manager Output:
```
Attempting to gather dependencies information for package 'Newtonsoft.Json.6.0.8' with respect to project targeting '.NETPortable, Version=v4.5, Profile=Profile259'
Preview Window pops up and then the exception is thrown
System.InvalidOperationException: Sequence contains more than one element
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__d2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActions>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformAction>d__0.MoveNext()
```

**Comment by benpye** [comment]
I also get this bug with a Profile111 PCL.

**Comment by piotrek1231** [comment]
I also have the same problem

**Comment by emgarten** [comment]
This has been fixed and it will be in the next release.
