### ISSUE TITLE
VersionUtility.TryGetCompatibleItems throws exception "An item with the same key has already been added."

### ISSUE THREAD

**Issue by gawie-yssel** [NuGet/Home#3410]
To replicate this issue:
1. Install Xamarin (4.1 in my environment).
2. Execute NuGet.VersionUtility.TryGetCompatibleItems on files in the NJsonSchema package.

[This](https://github.com/NuGet/Home/files/456493/TestNuget.zip) solution illustrates the problem. Install Xamarin and change the const pathToPackagesContainingJsonSchema in Program to point to the packages directory. Run the app.

Stack trace

```
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at NuGet.VersionUtility.TryGetCompatibleItems[T](FrameworkName projectFramework, IEnumerable`1 items, IEnumerable`1& compatibleItems) in D:\dev\NuGet2\src\Core\Utility\VersionUtility.cs:line 887
```

**Comment by emgarten** [comment]
This looks like a problem with NJsonSchema that is being handled poorly by the nuget.core.dll (legacy) used by Xamarin.

NJsonSchema contains these frameworks:

```
portable-net45+win+wpa81+wp80+MonoAndroid10+MonoTouch10
portable45-net45+win8+wp8+wpa81
```

Both of them are the same portable profile, just written in different ways.

**Comment by yishaigalatzer** [comment]
We don't plan to make any more fixes in nuget.core. Xamarin is moving over to nuget.frameworks going forward.

I'm suggesting a won't fix here on our side, and not try to fix nuget.core as we don't plan on supporting it going forward.

**Comment by gawie-yssel** [comment]
The bug was introduced in release 2.12. It worked in 2.12.0-rtm-815. We fixed our code by rolling back to the rtm.

**Comment by yishaigalatzer** [comment]
Re-opened and moved to Joel

**Comment by joelverhagen** [comment]
Fixed with https://github.com/NuGet/NuGet2/pull/60. Spoke offline with @rrelyea. This will be shipping with 2.14.
