### ISSUE TITLE
VS 2015 CTP 6 - Central Directory corrupt

### ISSUE THREAD

**Issue by jcapellman** [NuGet/Home#360]
Upon updating any NuGet Package I received the following exception (tried running as admin, same error):

System.IO.InvalidDataException: Central Directory corrupt. ---> System.IO.IOException: An attempt was made to move the position before the beginning of the stream.
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   --- End of inner exception stack trace ---
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__d2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActions>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformAction>d__0.MoveNext()

**Comment by jcapellman** [comment]
If I manually update the project.json file with the new version for EntityFramework for instance, it seems to work ok, but then I get other errors in VS.

Installing a new package I get a different error.

**Comment by yishaigalatzer** [comment]
@jcapellman what project type are you using. and what exact steps are you going through?

// CC @davidfowl @anurse

**Comment by jcapellman** [comment]
@yishaigalatzer here are my exact steps:

Open VS 2015 CTP 6
Open my solution (which contains an ASP.NET 5 project and 2 ASP.NET 5 Class Library projects)
Right clicking on the solution and clicking on Manage NuGet Packages for Solution or right clicking on a specific project and clicking on Manage NuGet Packages
I'll filter to "Upgrade Available" in the filter dropdown
Select EntityFramework, it currently has an upgrade available to 7.0.0-beta5-12831, click the Upgrade button
The Review Changes dialog appears, I click Ok
A few seconds later, the License Acceptance pops up, I click "I Accept"

And then the "Error" popup appears with "Central Directory corrupt." and the exception I noted above.

**Comment by yishaigalatzer** [comment]
Ctp6 does not yet support dnxXXX target frameworks. Which is why you have to either stick to the shipped version or do the upgrades/restores by editing project.json and restoring from command line. The updates comes out in RC.

**Comment by yishaigalatzer** [comment]
Cc @davidfowl
