### ISSUE TITLE
Batch update fails from UI when source without the package is first and All source is selected

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3696]
## Steps
1. Open Visual Studio 2015 with .NET Core SDK (preview 2 tooling).
2. Create a new .NET Core console app (.xproj).
3. Add a package source that has a package not on NuGet.org (e.g. https://dotnet.myget.org/F/nuget-build/api/v3/index.json).
4. Make sure nuget.org is the first source in the list.
5. Install an older version of that package (e.g. NuGet.Versioning).
6. Switch to the Updates tab.
7. Select the All source.
8. Check the package then hit the Update button.
## Expected

The package should update.
## Actual

The package update fails:

```
Retrieving package 'NuGet.Versioning 3.6.0-rc-1995' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/nuget.versioning/3.6.0-rc-1995/nuget.versioning.3.6.0-rc-1995.nupkg
Uninstalling NuGet package NuGet.Versioning.3.6.0-rc-1991.
Successfully uninstalled 'NuGet.Versioning.3.6.0-rc-1991' from ConsoleApp4
  NotFound https://api.nuget.org/v3-flatcontainer/nuget.versioning/3.6.0-rc-1995/nuget.versioning.3.6.0-rc-1995.nupkg 230ms
Install failed. Rolling back...
Uninstalling NuGet package NuGet.Versioning.3.6.0-rc-1995.
Executing nuget actions took 240.37 ms
NuGet.Protocol.Core.Types.FatalProtocolException: Package 'NuGet.Versioning.3.6.0-rc-1995' is not found on source 'https://api.nuget.org/v3/index.json'.
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackagePreFetcher.<>c__DisplayClass0_0.<<GetPackagesAsync>b__4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackagePreFetcherResult.<EnsureResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.PackageManagement.PackagePreFetcherResult.<GetResultAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<>c__DisplayClass4_0.<<PerformUpdateAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()
```

**Comment by joelverhagen** [comment]
## Workarounds:
1. Make sure the source is first in the list of sources.
2. Update each package individually from the Installed tab.
3. Select the specific package source when on the Updates package

**Comment by joelverhagen** [comment]
## Other project types

| project type | status |
| --- | --- |
| packages.config | unaffected |
| UWP project.json | unaffected |
| PackageReference | unaffected (validated on 2016-10-27) |

**Comment by rrelyea** [comment]
Rohit is oof. Is this really a validation task? Or is there work here?
If there is work, how important is it for RC?

**Comment by joelverhagen** [comment]
We can choose to not fix this for .xproj. If so, then this is a validation task for PackageReference (which I have already verified as not effected). If not, then we should leave this open for the .xproj scenarion. Your call, @rrelyea @yishaigalatzer

**Comment by rrelyea** [comment]
yes, won't fix for xproj/p.j.
thx!
