### ISSUE TITLE
Debug build:  assertion failed while restoring multiple TFMS for .NET Core project in VS

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3798]
It looks like restores inside of VS are not setting the `PackageSpec.RestoreMetadata.CrossTargeting` boolean.

The assertion that is failing is:
https://github.com/NuGet/NuGet.Client/blob/c1fb5ed9df932ff2d5240ae2e560732085899a69/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/BuildAssetsUtils.cs#L87-L89

Line 88 could use the `isCrossTargeting` local since it looks we consider TFM.Count > 2 cases as cross targeting, but then why do we have the property?
## Steps
1. Install a debug version of the VSIX to d15.
2. Create .NET Core library project.
3. Edit the .csproj to target two frameworks, changing `<TargetFramework>` to `<TargetFrameworks>`.
4. Move the the `NETStandard.Library` dependency to a condition if necessary.
5. Reload the .csproj and restore.
## Expected

The restore completes successfully.
## Actual

Debug assertion fails:

```
Invalid crosstargeting and framework count combination
   at NuGet.Commands.BuildAssetsUtils.RestoreMSBuildFiles(PackageSpec project, IEnumerable`1 targetGraphs, IReadOnlyList`1 repositories, RemoteWalkContext context, RestoreRequest request, Dictionary`2 includeFlagGraphs)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
   at NuGet.Commands.RestoreCommand.ExecuteAsync()
   at NuGet.Commands.RestoreRunner.<Execute>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at NuGet.Commands.RestoreRunner.Execute(RestoreSummaryRequest summaryRequest)
   at NuGet.Commands.RestoreRunner.<ExecuteAndCommit>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at NuGet.Commands.RestoreRunner.ExecuteAndCommit(RestoreSummaryRequest summaryRequest)
   at NuGet.Commands.RestoreRunner.<>c__DisplayClass1_0.<<Run>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at NuGet.Commands.RestoreRunner.<>c__DisplayClass1_0.<Run>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by joelverhagen** [comment]
Note that using the debugger to skip over the assertion yields a good restore (from what I can tell)

**Comment by rrelyea** [comment]
dupe of #3739 ??

**Comment by joelverhagen** [comment]
> CrossTargeting - true when $(TargetFrameworks) is used, false otherwise. This enables writing buildCrossTargeting imports to the generated targets/props.

Yes
