### ISSUE TITLE
IVSPackageInstaller.InstallPackage throws null ref exception

### ISSUE THREAD

**Issue by ejizba** [NuGet/Home#3832]
VS version: d15prerel/25830.04

I created a small sample project that illustrates the issue. It's a VSIX extension project, so you'll need Dev15 with the extensibility tools to run it.
[VSIXProject1.zip](https://github.com/NuGet/Home/files/562548/VSIXProject1.zip)

### Repro Steps:
1. F5 the sample project (you might have to update the path to "Nuget.VisualStudio" reference on your machine in order to build)
2.  File -> New Project -> ASP.NET Core (.NET Framework) -> Empty
3. Tools -> Invoke Command1

Expected: A Nuget package gets installed to the project
Actual: A null ref exception is thrown (line 121 in Command1.cs of the sample project)

### Verbose Logs
   at NuGet.VisualStudio.VsPackageInstallerServices.<GetInstalledPackageReferencesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstallerServices.<>c__DisplayClass14_0.<<IsPackageInstalled>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at NuGet.VisualStudio.VsPackageInstallerServices.IsPackageInstalled(Project project, String packageId, NuGetVersion nugetVersion)
   at NuGet.VisualStudio.VsPackageInstallerServices.IsPackageInstalledEx(Project project, String packageId, String versionString)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   at VSIXProject1.Command1.MenuItemCallback(Object sender, EventArgs e) in C:\Users\erijiz\documents\visual studio 2017\Projects\VSIXProject1\VSIXProject1\Command1.cs:line 121
   at System.ComponentModel.Design.MenuCommand.Invoke()
   at System.ComponentModel.Design.MenuCommand.Invoke(Object arg)
   at Microsoft.VisualStudio.Shell.OleMenuCommandService.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid& commandGroup, UInt32 nCmdId, UInt32 nCmdExcept, IntPtr pIn, IntPtr vOut)
   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid& guidGroup, UInt32 nCmdId, UInt32 nCmdExcept, IntPtr pIn, IntPtr vOut)

**Comment by emgarten** [comment]
I am able to get a repro of this.

**Comment by emgarten** [comment]
The CustomUnique name being returned here for a new .NETCore web app is `src` which is the solution folder the project is in, not the project name.

VSSolutionManager.GetOrCreateProjectAsync returns null here when it tries to retrieve a project with that name.

**Comment by emgarten** [comment]
The error does not repro after removing the `src` folder. It looks like VSIXProject may have the bug here. 
`var project = dte.Solution.Projects.Cast<Project>().First();` this line returns the folder isn't of the actual project.

This is assuming that this issue is for a .NETCore project, this step is unclear `File -> New Project -> ASP.NET Core (.NET Framework) -> Empty` is this referring to .NETCore or Desktop? There is no project type with this name that I can find.

**Comment by emgarten** [comment]
I worked @EricJizbaMSFT on this a bit more. 

His repro still gets a null ref when running on a solution that has not yet been saved. 

@jainaashish thinks this may be fixed with https://github.com/NuGet/Home/issues/3818 (which is in dev build 2040 and later)

The project does exist in the nuget project cache, but it cannot be found due to the name.

**Comment by rrelyea** [comment]
@EricJizbaMSFT  - Is this fixed in current VS builds? 25901.02 has NuGet 2044 instered.

**Comment by ejizba** [comment]
It still repros for me in d15rel/25901.02

**Comment by ejizba** [comment]
Attaching the updated sample project here, since outlook thinks it's malware
[VSIXProject1.zip](https://github.com/NuGet/Home/files/567883/VSIXProject1.zip)

Also including the updated repro steps:
1.  F5 the sample project
2.  Tools -> Invoke Command1
3.  Select ‘Empty’ in the ASP.NET project dialog that pops up

Expected: a project is created with the nuget package added
Actual: The project is created, but the nuget package fails to install

**Comment by jainaashish** [comment]
This scenario is broken with .net core projects in Dev15 and require good discussion among different teams to finalize the right behavior. Since .Net core projects are CPS based project system in Dev15 where every time you create a new project from existing templates, CPS nominate that project to NuGet and pass along project restore data which is used to install/ update/ restore packages to this project. 

But there are several ways we can encounter this problem and workarounds, One of these is if you directly add package reference in your template csproj file and load it from there instead of calling wizard PackageInstaller InstallPackage api. With this approach, you will also need to make sure that the new package is provided with template packages cache. Let us know if this can work for you now? else we'll see what can be done at this point in time.

About the null ref then we've a PR (https://github.com/NuGet/NuGet.Client/pull/993 ) out for this so it will fail gracefully.

**Comment by ejizba** [comment]
"CPS nominate that project to NuGet and pass along project restore data"

> How does this work? Is there an event we could just wait for before calling InstallPackage api?

"you will also need to make sure that the new package is provided with template packages cache"

> Can you expand on this? I'm not sure I understand what to do here.

**Comment by jainaashish** [comment]
`"you will also need to make sure that the new package is provided with template packages cache"

Can you expand on this? I'm not sure I understand what to do here.`

Leave it for now, just try adding that package reference directly into template csproj, instead of calling into installpackage api. and see if it works for you.

**Comment by rrelyea** [comment]
Eric is running with a workaround. Ok for RC.

**Comment by rrelyea** [comment]
brainstorming with Ashish:
1) create queue, drain queue on nominate
2) have cps provide a nominatenow() api
3) don't support rollback (don't do preview install), do install, tell cps via unconfigured project to add ref.

our guess is number 2, let's meet with Roslyn-project-system folks to discuss options.

**Comment by rrelyea** [comment]
Refresh my memory...why in validating column again?

**Comment by jainaashish** [comment]
This specific scenario is already fixed. There is another similar open item but with different repro steps which Roslyn team is looking into - https://github.com/dotnet/roslyn-project-system/issues/1332 

So there is nothing needed from our end as of now.

**Comment by jainaashish** [comment]
External issue is already closed. So closing this as well.

**Comment by rrelyea** [comment]
LEaving in backlog, to help track: https://github.com/dotnet/project-system/issues/1600
