### ISSUE TITLE
"Is not a valid version string" in client when downloading SemVer 2.0 package from Nexus

### ISSUE THREAD

**Issue by MartinSGill** [NuGet/Home#3857]
## Details about Problem

**NuGet product used**: NuGet.exe
**NuGet version**: 3.5.0.1938
**OS version**:  win10 v1607

Nexus seems happy with the SemVer 2.0 package, but the nuget client throws an error when Nexus gives it the correct package with the SemVer 2.0 version.

## Detailed repro steps so we can see the same problem

1. Create simple nuspec

```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>Semver2.test</id>
    <version>1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1</version>
    <authors>Example</authors>
    <owners>Example</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package to Test SemVer2 capabilities</description>
    <tags>test</tags>
  </metadata>
</package>
```

2. Pack it

```
./nuget pack
Attempting to build package from 'semver2.test.nuspec'.
Successfully created package 'E:\projects\semver2-test\Semver2.test.1.2.3-prerelease.1.2.3.nupkg'.
WARNING: Issue found with package 'Semver2.test'.

WARNING: Issue: Package version not supported on legacy clients.
WARNING: Description: The package version '1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1' uses SemVer 2.0.0 or components of SemVer 1.0.0 that are notsupported on legacy clients. This message can be ignored if the package is not intended for older clients.
WARNING: Solution: Change the package version to a SemVer 1.0.0 string. If the version contains a release label it must start with a letter.
```

Success with warning, sees it correctly as SemVer 2.0
Package name seems to be missing SemVer 2.0 parts

3. Push it to Nexus

```
Pushing Semver2.test.1.2.3-prerelease.1.2.3.nupkg to 'https://*******.com/service/local/nuget/releases_dotnet/'...
  PUT https://*******.com/service/local/nuget/releases_dotnet/
  Created https://*******.com/service/local/nuget/releases_dotnet/ 440ms
Your package was pushed.
```

4. Look for it

```
./nuget list Semver2 -prerelease -verbosity detailed
NuGet Version: 3.5.0.1938
GET https://*******.com/service/local/nuget/releases_dotnet/Search()?$filter=IsAbsoluteLatestVersion&$orderby=Id&$skip=0&$top=30&searchTerm='Semver2'&targetFramework=''&includePrerelease=true

System.AggregateException: One or more errors occurred. ---> System.ArgumentException: '1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1' is not a valid version string.
Parameter name: version
   at NuGet.SemanticVersion.Parse(String version)
   at NuGet.DataServicePackage.NuGet.IPackageName.get_Version()
   at NuGet.PackageEqualityComparer.<.cctor>b__1(IPackageName x)
   at NuGet.PackageEqualityComparer.GetHashCode(IPackageName obj)
   at System.Collections.Generic.HashSet`1.InternalGetHashCode(T item)
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at NuGet.AggregateQuery`1.<ReadOrderedQueues>d__c.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at NuGet.EnumerableExtensions.<DistinctLast>d__0`1.MoveNext()
   at NuGet.Commands.ListCommand.<ExecuteCommandAsync>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.ArgumentException: '1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1' is not a valid version string.
Parameter name: version
   at NuGet.SemanticVersion.Parse(String version)
   at NuGet.DataServicePackage.NuGet.IPackageName.get_Version()
   at NuGet.PackageEqualityComparer.<.cctor>b__1(IPackageName x)
   at NuGet.PackageEqualityComparer.GetHashCode(IPackageName obj)
   at System.Collections.Generic.HashSet`1.InternalGetHashCode(T item)
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at NuGet.AggregateQuery`1.<ReadOrderedQueues>d__c.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at NuGet.EnumerableExtensions.<DistinctLast>d__0`1.MoveNext()
   at NuGet.Commands.ListCommand.<ExecuteCommandAsync>d__22.MoveNext()<---
```

The Server itself returned (as far as I can tell) a correct response, and the package was correctly found.

```xml
<feed xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"
    xmlns="http://www.w3.org/2005/Atom" xml:base="https://*******.com/service/local/nuget/releases_dotnet/">
    <title type="text">Search</title>
    <id>
        https://*******.com/service/local/nuget/releases_dotnet/Search
    </id>
    <updated>2016-11-02T11:15:16.171Z</updated>
    <link rel="self" title="Search" href="Search" />
    <entry>
        <id>
            https://*******.com/service/local/nuget/releases_dotnet/Packages(Id='Semver2.test',Version='1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1')
        </id>
        <title type="text">Semver2.test</title>
        <summary type="text">Package to Test SemVer2 capabilities</summary>
        <updated>2016-11-02T11:02:40.068Z</updated>
        <author>
            <name>Example</name>
        </author>
        <link rel="edit-media" title="V2FeedPackage" href="Packages(Id='Semver2.test',Version='1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1')/$value"
        />
        <link rel="edit" title="V2FeedPackage" href="Packages(Id='Semver2.test',Version='1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1')"
        />
        <category term="NuGetGallery.V2FeedPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
        <content type="application/zip" src="https://*******.com/service/local/nuget/releases_dotnet/Semver2.test/1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1"
        />
        <m:properties>
            <d:Version>1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1</d:Version>
            <d:Copyright m:null="true" />
            <d:Created m:type="Edm.DateTime">2016-11-02T11:02:40.068Z</d:Created>
            <d:Dependencies m:null="true" />
            <d:Description>Package to Test SemVer2 capabilities</d:Description>
            <d:DownloadCount m:type="Edm.Int32">0</d:DownloadCount>
            <d:GalleryDetailsUrl m:null="true" />
            <d:IconUrl m:null="true" />
            <d:IsLatestVersion m:type="Edm.Boolean">false</d:IsLatestVersion>
            <d:IsAbsoluteLatestVersion m:type="Edm.Boolean">true</d:IsAbsoluteLatestVersion>
            <d:IsPrerelease m:type="Edm.Boolean">true</d:IsPrerelease>
            <d:Published m:type="Edm.DateTime">2016-11-02T11:02:40.068Z</d:Published>
            <d:Language m:null="true" />
            <d:LicenseUrl m:null="true" />
            <d:PackageHash>
                HPFuPewh93r77SMqo54n/URCBy/4xt1cjoqehIps0Pv7KaR0kzMiUq4DCpbdWmPcWIq3girQJPYNSgsivQzalg==
            </d:PackageHash>
            <d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm>
            <d:PackageSize m:type="Edm.Int64">1318724</d:PackageSize>
            <d:ProjectUrl m:null="true" />
            <d:ReportAbuseUrl m:null="true" />
            <d:ReleaseNotes m:null="true" />
            <d:RequireLicenseAcceptance m:type="Edm.Boolean">false</d:RequireLicenseAcceptance>
            <d:Tags>test</d:Tags>
            <d:Title>Semver2.test</d:Title>
            <d:VersionDownloadCount m:type="Edm.Int32">0</d:VersionDownloadCount>
        </m:properties>
    </entry>
</feed>
```

**Comment by yishaigalatzer** [comment]
@MartinSGill thanks for the report. 

Edit: Just noticed the other issue...

> Can you install it, but just fail to list it? Or install is failing for you as well?

So is restore is failing as well?

**Comment by yishaigalatzer** [comment]
CC @emgarten @joelverhagen

**Comment by emgarten** [comment]
NuGet.exe 3.5.0 doesn't support SemVer 2.0.0 in the list command, that part still uses NuGet.Core.dll.

**Comment by jainaashish** [comment]
Fixed with latest version of NuGet.exe
