### ISSUE TITLE
"Unable to Find Package" in NuGet install, despite package reported correctly by Nexus

### ISSUE THREAD

**Issue by MartinSGill** [NuGet/Home#3858]
## Details about Problem

**NuGet product used**: NuGet.exe
**NuGet version**: 3.5.0.1938
**OS version**:  win10 v1607

Possibly related to #3857 

Nexus seems happy with the SemVer 2.0 package, but the nuget client claims it cannot find the package, despite the server providing the link.

## Detailed repro steps so we can see the same problem

1. Create simple nuspec

```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>Semver2.test</id>
    <version>1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1</version>
    <authors>Example</authors>
    <owners>Example</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package to Test SemVer2 capabilities</description>
    <tags>test</tags>
  </metadata>
</package>
```

2. Pack it

```
./nuget pack
Attempting to build package from 'semver2.test.nuspec'.
Successfully created package 'E:\projects\semver2-test\Semver2.test.1.2.3-prerelease.1.2.3.nupkg'.
WARNING: Issue found with package 'Semver2.test'.

WARNING: Issue: Package version not supported on legacy clients.
WARNING: Description: The package version '1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1' uses SemVer 2.0.0 or components of SemVer 1.0.0 that are notsupported on legacy clients. This message can be ignored if the package is not intended for older clients.
WARNING: Solution: Change the package version to a SemVer 1.0.0 string. If the version contains a release label it must start with a letter.
```

Success with warning, sees it correctly as SemVer 2.0
Package name seems to be missing SemVer 2.0 parts

3. Push it to Nexus

```
Pushing Semver2.test.1.2.3-prerelease.1.2.3.nupkg to 'https://*******.com/service/local/nuget/releases_dotnet/'...
  PUT https://*******.com/service/local/nuget/releases_dotnet/
  Created https://*******.com/service/local/nuget/releases_dotnet/ 440ms
Your package was pushed.
```

4. Try to install it

```
./nuget install Semver2.test -verbosity detail -source https://*******.com/service/local/nuget/releases_dotnet
NuGet Version: 3.5.0.1938
Feeds used:
  https://*******.com/service/local/nuget/releases_dotnet

  GET https://*******.com/service/local/nuget/releases_dotnet/FindPackagesById()?id='Semver2.test'
  OK https://*******.com/service/local/nuget/releases_dotnet/FindPackagesById()?id='Semver2.test' 32ms
System.AggregateException: One or more errors occurred. ---> NuGet.CommandLine.CommandLineException: Unable to find package 'Semver2.test'
   at NuGet.CommandLine.InstallCommand.<InstallPackage>d__31.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) NuGet.CommandLine.CommandLineException: Unable to find package 'Semver2.test'
   at NuGet.CommandLine.InstallCommand.<InstallPackage>d__31.MoveNext()<---
   
```

The Server itself returned (as far as I can tell) a correct response, and the package was correctly found.

```xml
<feed xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"
    xmlns="http://www.w3.org/2005/Atom" xml:base="https://*******.com/service/local/nuget/releases_dotnet/">
    <title type="text">FindPackagesById</title>
    <id>
        https://*******.com/service/local/nuget/releases_dotnet/FindPackagesById
    </id>
    <updated>2016-11-02T11:46:19.906Z</updated>
    <link rel="self" title="FindPackagesById" href="FindPackagesById" />
    <entry>
        <id>
            https://*******.com/service/local/nuget/releases_dotnet/Packages(Id='Semver2.test',Version='1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1')
        </id>
        <title type="text">Semver2.test</title>
        <summary type="text">Package to Test SemVer2 capabilities</summary>
        <updated>2016-11-02T11:02:40.068Z</updated>
        <author>
            <name>Example</name>
        </author>
        <link rel="edit-media" title="V2FeedPackage" href="Packages(Id='Semver2.test',Version='1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1')/$value"
        />
        <link rel="edit" title="V2FeedPackage" href="Packages(Id='Semver2.test',Version='1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1')"
        />
        <category term="NuGetGallery.V2FeedPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
        <content type="application/zip" src="https://*******.com/service/local/nuget/releases_dotnet/Semver2.test/1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1"
        />
        <m:properties>
            <d:Version>1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1</d:Version>
            <d:Copyright m:null="true" />
            <d:Created m:type="Edm.DateTime">2016-11-02T11:02:40.068Z</d:Created>
            <d:Dependencies m:null="true" />
            <d:Description>Package to Test SemVer2 capabilities</d:Description>
            <d:DownloadCount m:type="Edm.Int32">0</d:DownloadCount>
            <d:GalleryDetailsUrl m:null="true" />
            <d:IconUrl m:null="true" />
            <d:IsLatestVersion m:type="Edm.Boolean">false</d:IsLatestVersion>
            <d:IsAbsoluteLatestVersion m:type="Edm.Boolean">true</d:IsAbsoluteLatestVersion>
            <d:IsPrerelease m:type="Edm.Boolean">true</d:IsPrerelease>
            <d:Published m:type="Edm.DateTime">2016-11-02T11:02:40.068Z</d:Published>
            <d:Language m:null="true" />
            <d:LicenseUrl m:null="true" />
            <d:PackageHash>
                HPFuPewh93r77SMqo54n/URCBy/4xt1cjoqehIps0Pv7KaR0kzMiUq4DCpbdWmPcWIq3girQJPYNSgsivQzalg==
            </d:PackageHash>
            <d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm>
            <d:PackageSize m:type="Edm.Int64">1318724</d:PackageSize>
            <d:ProjectUrl m:null="true" />
            <d:ReportAbuseUrl m:null="true" />
            <d:ReleaseNotes m:null="true" />
            <d:RequireLicenseAcceptance m:type="Edm.Boolean">false</d:RequireLicenseAcceptance>
            <d:Tags>test</d:Tags>
            <d:Title>Semver2.test</d:Title>
            <d:VersionDownloadCount m:type="Edm.Int32">0</d:VersionDownloadCount>
        </m:properties>
    </entry>
</feed>
```

**Comment by emgarten** [comment]
You are missing the `-pre` flag

I created a package with the same id/version on a myget feed and was able to install it without any issues, it should work from nexus also. Let me know if it doesn't!

`NuGet.3.5.0.exe install semver2.test -Source https://www.myget.org/F/semver2/api/v2 -pre`

**Comment by yishaigalatzer** [comment]
@emgarten thanks for the update, I would think we should make the error a bit nicer than

> System.AggregateException: One or more errors occurred. ---> NuGet.CommandLine.CommandLineException: Unable to find package 'Semver2.test'

Or does that happen only in detailed mode?

**Comment by MartinSGill** [comment]
@yishaigalatzer Non-Detailed is nicer: "Unable to find package 'Semver2.test'". A hint "(a pre-release package was found, use -prerelease to install it)" might be nice though.

@emgarten I also have problems when using -pre (my bad for missing that initially)

Not sure if this is a Nexus bug or a NuGet bug though.

The link `https://*******.com/service/local/repositories/releases_dotnet/content/Semver2.test/1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1` fails to download.

The actual package is there though at `https://*******.com/service/local/repositories/releases_dotnet/content/Semver2.test/1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1/Semver2.test-1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1.nupkg` and I can manually download it through the Nexus UI.

Could this be because NuGet (at Step 2) renames the package and no longer includes the full version string (i.e. stripping off the metadata)?

```
 ./nuget install Semver2.test -verbosity detail -source https://*******.com/service/local/nuget/releases_dotnet -pre
NuGet Version: 3.5.0.1938
Feeds used:
  https://*******.com/service/local/nuget/releases_dotnet

  GET https://*******.com/service/local/nuget/releases_dotnet/FindPackagesById()?id='Semver2.test'
  OK https://*******.com/service/local/nuget/releases_dotnet/FindPackagesById()?id='Semver2.test' 31ms


Attempting to gather dependency information for package 'Semver2.test.1.2.3-prerelease.1.2.3' with respect to project 'E:\projects\semver2-test', targeting 'Any,Version=v0.0'
Package Semver2.test from source https://*******.com/service/local/nuget/releases_dotnet gathered from cache.
Total number of results gathered : 1
Gathering dependency information took 26.5 ms
Summary of time taken to gather dependencies per source :
Attempting to resolve dependencies for package 'Semver2.test.1.2.3-prerelease.1.2.3' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Semver2.test.1.2.3-prerelease.1.2.3'
Resolved actions to install package 'Semver2.test.1.2.3-prerelease.1.2.3'
Retrieving package 'Semver2.test 1.2.3-prerelease.1.2.3' from 'https://*******.com/service/local/nuget/releases_dotnet'.
  GET https://*******.com/service/local/nuget/releases_dotnet/Semver2.test/1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1
  NotFound https://*******.com/service/local/nuget/releases_dotnet/Semver2.test/1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1 32ms
WARNING: Install failed. Rolling back...
Executing nuget actions took 68.68 ms
System.AggregateException: One or more errors occurred. ---> NuGet.Protocol.Core.Types.FatalProtocolException: Package 'Semver2.test.1.2.3-prerelease.1.2.3' is not found on source 'https://*******.com/service/local/nuget/releases_dotnet'.
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackagePreFetcher.<>c__DisplayClass0_0.<<GetPackagesAsync>b__4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackagePreFetcherResult.<EnsureResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.PackageManagement.PackagePreFetcherResult.<GetResultAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.CommandLine.InstallCommand.<InstallPackage>d__31.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) NuGet.Protocol.Core.Types.FatalProtocolException: Package 'Semver2.test.1.2.3-prerelease.1.2.3' is not found on source 'https://*******.com/service/local/nuget/releases_dotnet'.
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackagePreFetcher.<>c__DisplayClass0_0.<<GetPackagesAsync>b__4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackagePreFetcherResult.<EnsureResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.PackageManagement.PackagePreFetcherResult.<GetResultAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.CommandLine.InstallCommand.<InstallPackage>d__31.MoveNext()<---
```

**Comment by emgarten** [comment]
@MartinSGill can you manually download the nupkg from the url using the browser? 
`https://*******.com/service/local/repositories/releases_dotnet/content/Semver2.test/1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1/Semver2.test-1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1.nupkg`

I'm wondering if Nexus has an issue with the url since it contains an unescaped `+`. It is a known issue that SemVer 2.0.0 itself is not url friendly.

MyGet also puts the `+` in the download url, but there it appears to be working, so I don't think this is a client issue.

> Could this be because NuGet (at Step 2) renames the package and no longer includes the full version string (i.e. stripping off the metadata)?

The feed gives a download url, and the client downloads that url directly, it doesn't try to parse it. Metadata is left off the name on disk just to shorten the file name, and to avoid having two copies of the same package with different metadata (since metadata doesn't count as part of the package identity)

**Comment by MartinSGill** [comment]
@emgarten

Yes, I can download from that URL manually, i.e. directly in Chrome and I get the package.

That's not the URL in the XML though... that URL is:

```
<content type="application/zip" src="https://*******.com/service/local/nuget/releases_dotnet/Semver2.test/1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1"/>
```

That URL doesn't work. And I don't know enough about the API to tell if the actual package URL should be retrieved using a redirect (in Nexus) or if the client is supposed to calculate the URL from that link.

**Comment by MartinSGill** [comment]
@emgarten

Yes, I can download from that URL manually, i.e. directly in Chrome and I get the package.

That's not the URL in the XML though... that URL is:
```
<content type="application/zip" src="https://*******.com/service/local/nuget/releases_dotnet/Semver2.test/1.2.3-prerelease.1.2.3+SHA-ABCDEF-20161111-slave1"/>
```

That URL doesn't work. And I don't know enough about the API to tell if the actual package URL should be retrieved using a redirect (in Nexus) or if the client is supposed to calculate the URL from that link.

**Comment by emgarten** [comment]
> the API to tell if the actual package URL should be retrieved using a redirect (in Nexus) or if the client is supposed to calculate the URL from that link.

The feed is allowed to put the nupkg at any url, NuGet just follows the link provided. There is no url construction happening in the client.

So far this seems like an issue with Nexus, can you open a bug with them with what you are seeing? I'd be happy to help also to get Nexus and NuGet working together for SemVer 2.0.0.

**Comment by jainaashish** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.

**Comment by lukas-lansky** [comment]
Just for others seeing this: I have the same issue against Nexus. A package with a simple version like `1.2.3+09d6b7c` is succesfully stored, it's listed, but fails to be downloaded by NuGet client.

What I see when I look into URLs confirms your suspicion about escaping characters.

```
> http://***.com/nexus/service/local/nuget/repo-name/Nuget.Name/1.2.3+09d6b7c
404 Path /Nuget.Name/1.2.3 09d6b7c/Nuget.Name-1.2.3 09d6b7c.nupkg not found in local storage of repository "Repository" [id=repo-name] 
```

Note the `+` sign missing in the response. Now when I escape manually:

```
> http://***.com/nexus/service/local/nuget/repo-name/Nuget.Name/1.2.3%2B09d6b7c
[download offered]
```

This is clearly problem of Nexus as + [should not mean "space" in the path component of URL](https://stackoverflow.com/a/2678602/577067). I sent a support ticket to them.
