### ISSUE TITLE
LockRecursionException in ProjectSystemCache.TryGetProjectNameByShortName

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#3861]
Throw below exception at solution build with DPL :
```
System.Threading.LockRecursionException: Recursive read lock acquisitions not allowed in this mode.
   at System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(TimeoutTracker timeout)
   at System.Threading.ReaderWriterLockSlim.TryEnterReadLock(TimeoutTracker timeout)
   at NuGet.PackageManagement.VisualStudio.ProjectSystemCache.TryGetProjectNameByShortName(String name, ProjectNames& projectNames)
   at NuGet.PackageManagement.VisualStudio.ProjectSystemCache.TryGetProjectNames(String name, ProjectNames& projectNames)
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.SetDefaultProjectName()
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.EnsureNuGetAndEnvDTEProjectCache()
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.<<Init>b__81_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.Init()
```

**Comment by rrelyea** [comment]
From Rodrigo:
No RC bug.
-   I only see this in DPL mode
-   Apparently only manifest for solution build not for project build
-   I tried Roslyn.sln but haven’t tried in simple projects
-   When I tried no projects were loaded (the whole purpose of DPL)
