### ISSUE TITLE
Nuget.exe throws System.ArgumentException

### ISSUE THREAD

**Issue by mynkow** [NuGet/Home#4085]
## Details about Problem

NuGet product used (NuGet.exe):

NuGet version (3.5.0.1938):

OS version (i.e. win10 v1607 (14393.321)):

## Detailed repro steps so we can see the same problem

1. Add two package sources like this:
```
<packageSources>
    <add key="v2.nuget.org" value="https://nuget.org/api/v2" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
```

2. Execute a command like this:
`NuGet.exe list Cronus -verbosity detailed`

### Verbose Logs

```
C:\Users\mynkow\AppData\Local\NuGet>C:\Users\mynkow\AppData\Local\NuGet\NuGet.exe list Cronus -verbosity detailed
NuGet Version: 3.5.0.1938
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at NuGet.Credentials.CredentialServiceAdapter.SetEndpoints(IEnumerable`1 endpoints)
   at NuGet.Commands.ListCommand.<ExecuteCommandAsync>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at NuGet.Credentials.CredentialServiceAdapter.SetEndpoints(IEnumerable`1 endpoints)
   at NuGet.Commands.ListCommand.<ExecuteCommandAsync>d__22.MoveNext()<---
```

Full config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="v2.nuget.org" value="https://nuget.org/api/v2" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

**Comment by kzu** [comment]
I can verify this too, exact same error. My config:

```
	<packageSources>
		<add key="v3" value="https://www.myget.org/F/xvs/api/v3/index.json" />
		<add key="v2" value="https://www.myget.org/F/xvs/api/v2" />
	</packageSources>
```

Command:
```
nuget.exe list List Xamarin.Messaging.99 -pre
```

**Comment by SayliS** [comment]
I spent 2 hours trying to understand what is going on. Can you please fix it or throw some reasonable error/exception please.

**Comment by mynkow** [comment]
Any update?

**Comment by zhili1208** [comment]
Please try nuget.exe 4.3 from https://www.nuget.org/downloads. I can't repro with Nuget.exe 4.3
