### ISSUE TITLE
[VSFeedback] Error occurred while restoring NuGet packages for website project: Value cannot be null.

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4092]
[Feedback] Error occurred while restoring NuGet packages: Value cannot be null.
Internal Bug 293947

Perhaps MsBuildNuGetProject.cs ~ line 609

        public async Task<IReadOnlyList<PackageSpec>> GetPackageSpecsAsync(DependencyGraphCacheContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }
            PackageSpec packageSpec = null;
            if (!context.PackageSpecCache.TryGetValue(MSBuildNuGetProjectSystem.ProjectFileFullPath, out packageSpec))

ProjectFileFullPath may be null? Not sure what would cause that.
One clue...the project file guid is the one for solution folders...???
---
Stack trace from the vsfeedback item:
Error occurred while restoring NuGet packages: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at NuGet.ProjectManagement.MSBuildNuGetProject.<GetPackageSpecsAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<GetSolutionRestoreSpec>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<IsRestoreRequiredAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.SolutionRestoreJob.<RestorePackageSpecProjectsAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.SolutionRestoreJob.<RestoreAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.SolutionRestoreJob.<ExecuteAsync>d__19.MoveNext()

**Comment by rrelyea** [comment]
Likely repro steps (via an email thread):
1)	File New Web Site (C#, Empty)
2)	Add New Project (C#, Asp.Net Core, WebApp)

At this point, 
1)	try opening a .cshtml file  lots of errors
2)	try solution level restore  following error in output window:  “Error occurred while restoring NuGet packages: Value cannot be null. Parameter name: key”
