### ISSUE TITLE
The given path's format is not supported with local package sources

### ISSUE THREAD

**Issue by kentcb** [NuGet/Home#4094]
## Details about Problem

* NuGet via VS 2015 14.0.25431.01 U3 PMC
* Version 3.5.0.1484
* `dotnet --version` is `1.0.0-preview2-003133`
* Windows Version 10.0.14393 Build 14393

## Detailed repro steps so we can see the same problem

1. Make sure you have a local source configured in VS Package Sources. e.g. `file://:C:\Users\Me\LocalNuGet\`
2. `git clone https://github.com/kentcb/Contented.git`
3. `cd Contented\Src\`
4. `dotnet restore`

### Verbose Logs

```
dotnet restore -v Detailed
log  : Restoring packages for C:\Users\Kent\Repository\contented\Src\Contented.Core\project.json...
log  : Restoring packages for C:\Users\Kent\Repository\contented\Src\Contented.PowerShell\project.json...
info :   GET https://powershell.myget.org/F/powershell-core/FindPackagesById()?id='Microsoft.NETCore'
info :   GET https://www.myget.org/F/reactiveui/api/v2/FindPackagesById()?id='Microsoft.NETCore'
info :   GET https://powershell.myget.org/F/powershell-core/FindPackagesById()?id='Microsoft.NETCore.Portable.Compatibility'
info :   GET https://www.myget.org/F/reactiveui/api/v2/FindPackagesById()?id='Microsoft.NETCore.Portable.Compatibility'
error: The given path's format is not supported.
```

### Sample Project

https://github.com/kentcb/Contented

**Comment by rrelyea** [comment]
This works fine with nuget.org as the only source.
From your log, it looks like you are using 2 different myget sources.
??

**Comment by kentcb** [comment]
@rrelyea aha! OK, this is the source that was causing the issue:

![image](https://cloud.githubusercontent.com/assets/1901832/21163643/393e5874-c1e4-11e6-9423-53e314de9f72.png)

Once I disabled that, the restore worked. I will edit the repro steps accordingly. Also, it would be nice if the output included the details of the source whose path is not supported. That would have made the workaround super obvious.

**Comment by weshaggard** [comment]
I'm hitting this exact issue with the latest CLI (2.0.2-vspre-006949, although it repros on other 2.0.0 preview builds as well), with a base `dotnet new console` application.

From some experimenting it seems there is an issue with the order in which the local file source is used:

Here is the output of a few different restore commands:
```
> dotnet restore
  Restoring packages for D:\git\tests\samples\test\test.csproj...
  Restore completed in 142.2 ms for D:\git\tests\samples\test\test.csproj.

> dotnet restore --source D:\git\source-build\bin/obj/x64/Release/source-built/
  Restore completed in 19.2 ms for D:\git\tests\samples\test\test.csproj.

> dotnet restore --source D:\git\source-build\bin/obj/x64/Release/source-built/ --source https://api.nuget.org/v3/index.json
c:\program files\dotnet\sdk\2.0.2-vspre-006949\NuGet.targets(466,5): error : The given path's format is not supported. [D:\git\tests\samples\test\test.csproj]

> dotnet restore --source https://api.nuget.org/v3/index.json --source D:\git\source-build\bin/obj/x64/Release/source-built/
  Restoring packages for D:\git\tests\samples\test\test.csproj...
  Restore completed in 146.54 ms for D:\git\tests\samples\test\test.csproj.
```

So it appears to only fail if the first source is a file path. Here are some details from the detailed msbuild log:

```
                   Using "GetRestoreSettingsTask" task from assembly "c:\program files\dotnet\sdk\2.0.2-vspre-006949\NuGet.Build.Tasks.dll".
                   Task "GetRestoreSettingsTask" (TaskId:20)
                     Task Parameter:ProjectUniqueName=D:\git\tests\samples\test\test.csproj (TaskId:20)
                     Task Parameter:RestoreSources=D:\git\source-build\bin/obj/x64/Release/source-built/;https://api.nuget.org/v3/index.json (TaskId:20)
                     Task Parameter:
                         RestoreSettingsPerFramework=
                             77431c89-cc8d-4ee6-bc09-fc81f4dfad7d
                                     MSBuildSourceProjectFile=D:\git\tests\samples\test\test.csproj
                                     MSBuildSourceTargetName=_GetRestoreSettingsPerFramework
                                     OriginalItemSpec=D:\git\tests\samples\test\test.csproj
                                     RestoreAdditionalProjectFallbackFolders=;c:\program files\dotnet\sdk\2.0.2-vspre-006949\Sdks\Microsoft.NET.Sdk\build\..\..\..\..\NuGetFallbackFolder
                                     RestoreAdditionalProjectFallbackFoldersExcludes=
                                     RestoreAdditionalProjectSources= (TaskId:20)
                     Task Parameter:RestoreSourcesOverride=D:\git\source-build\bin/obj/x64/Release/source-built/;https://api.nuget.org/v3/index.json (TaskId:20)
                     Task Parameter:MSBuildStartupDirectory=D:\git\tests\samples\test (TaskId:20)
                     (in) ProjectUniqueName 'D:\git\tests\samples\test\test.csproj' (TaskId:20)
                     (in) RestoreSources 'D:\git\source-build\bin/obj/x64/Release/source-built/;https://api.nuget.org/v3/index.json' (TaskId:20)
                     (in) RestorePackagesPath '' (TaskId:20)
                     (in) RestoreFallbackFolders '' (TaskId:20)
                     (in) RestoreConfigFile '' (TaskId:20)
                     (in) RestoreSolutionDirectory '' (TaskId:20)
                     (in) RestorePackagesPathOverride '' (TaskId:20)
                     (in) RestoreSourcesOverride 'D:\git\source-build\bin/obj/x64/Release/source-built/;https://api.nuget.org/v3/index.json' (TaskId:20)
                     (in) RestoreFallbackFoldersOverride '' (TaskId:20)
16:07:18.229   1:6>c:\program files\dotnet\sdk\2.0.2-vspre-006949\NuGet.targets(466,5): error : The given path's format is not supported. [D:\git\tests\samples\test\test.csproj]
                     System.NotSupportedException: The given path's format is not supported.
                        at System.IO.Path.GetFullPath(String path)
                        at NuGet.Common.UriUtility.GetAbsolutePath(String rootDirectory, String path)
                        at NuGet.Build.Tasks.GetRestoreSettingsTask.<Execute>b__61_4(String e)
                        at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
                        at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
                        at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
                        at NuGet.Build.Tasks.GetRestoreSettingsTask.<Execute>b__61_3()
                        at NuGet.Build.Tasks.RestoreSettingsUtils.GetValue[T](Func`1[] funcs)
                        at NuGet.Build.Tasks.GetRestoreSettingsTask.Execute() (TaskId:20)
                     Output Property: _OutputPackagesPath=C:\Users\wesh\.nuget\packages\ (TaskId:20)
                     Output Property: _OutputConfigFilePaths=C:\Users\wesh\AppData\Roaming\NuGet\NuGet.Config;C:\Program Files %28x86%29\NuGet\Config\Microsoft.VisualStudio.Offline.config (TaskId:20)
                   Done executing task "GetRestoreSettingsTask" -- FAILED. (TaskId:20)

```

cc @eerhardt
