### ISSUE TITLE
Nuget List with two VSTS feeds as source fails with auth error

### ISSUE THREAD

**Issue by shubham90** [NuGet/Home#4118]
**NuGet product used:** Nuget.exe 

**NuGet version** : 3.5.0.1938 , 4.0.0.2135

**OS version**: Win10

**Worked before? If so, with which NuGet version:** Yes, Nuget 3.3

**## Detailed repro steps so we can see the same problem**

1. We are using vsts credential provider for auth. On a command line, do a "nuget list -source foo -source bar -allversions -noninterative"
where foo and bar are different feeds from the same account.

2. Interestingly, Nuget returns **status code 0** even on failure.

**### Verbose Logs**
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> NuGet.Credentials.PluginException: Credential plugin C:\Users\shbhawsi\Downloads\CredentialProviderBundle\CredentialProvider.VSS.exe handles this request, but is unable to provide credentials. Auth tokens could not be retrieved. Remove the -NonInteractive flag and try again
   at NuGet.Credentials.PluginCredentialProvider.GetPluginResponse(PluginCredentialRequest request, CancellationToken cancellationToken)
   at NuGet.Credentials.PluginCredentialProvider.GetAsync(Uri uri, IWebProxy proxy, CredentialRequestType type, String message, Boolean isRetry, Boolean nonInteractive, CancellationToken cancellationToken)
   at NuGet.Credentials.CredentialService.<GetCredentialsAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at NuGet.Credentials.CredentialServiceAdapter.GetCredentials(Uri uri, IWebProxy proxy, CredentialType credentialType, Boolean retrying)
   at NuGet.RequestHelper.SetCredentialsOnAuthorizationError(HttpWebRequest request)
   at NuGet.RequestHelper.ConfigureRequest(HttpWebRequest request)
   at NuGet.RequestHelper.GetResponse()
   at NuGet.RedirectedHttpClient.GetResponseUri(HttpClient client)
   at NuGet.RedirectedHttpClient.EnsureClient()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at NuGet.MemoryCache.GetOrAdd[T](Object cacheKey, Func`1 factory, TimeSpan expiration, Boolean absoluteExpiration)
   at NuGet.RedirectedHttpClient.get_CachedClient()
   at NuGet.RedirectedHttpClient.get_Uri()
   at NuGet.DataServicePackageRepository.get_Context()
   at NuGet.DataServicePackageRepository.Search(String searchTerm, IEnumerable`1 targetFrameworks, Boolean allowPrereleaseVersions)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.AggregateQuery`1..ctor(IEnumerable`1 queryables, IEqualityComparer`1 equalityComparer, ILogger logger, Boolean ignoreFailures)
   at NuGet.AggregateRepository.CreateAggregateQuery(IEnumerable`1 queries)
   at NuGet.Commands.ListCommand.GetPackages(IEnumerable`1 listEndpoints)
   at NuGet.Commands.ListCommand.<ExecuteCommandAsync>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)

**Comment by zjrunner** [comment]
confirmation this is a bug/regression?  Sounds like (1) incorrect return code and (2) double auth attempts with second improperly sending in the IsRetry flag?

**Comment by shubham90** [comment]
I can still repro this issue. This happens only in List with two sources in one command. @rrelyea Any confirmation for the bug ?

**Comment by nkolev92** [comment]
Hey @shubham90 Thanks for this issue. 

At this point with the new credential provider I was not able to repro this scenario. 

Apologies for the long turnaround.
