### ISSUE TITLE
nuget delete does not work with V2-feedsnuget

### ISSUE THREAD

**Issue by Tasteful** [NuGet/Home#4169]
NuGet CLI Version: 3.5.0.1996

I'm using the NuGet.Server 2.11.3 that is working with V2 feeds. When trying to delete a package with `nuget delete` command with what I think is V3 feed url.

In my local test feed I added one package 
```
nuget list -source NugetServerTest -verbosity detailed
NuGet Version: 3.5.0.1996
Using credentials from config. UserName: patric.forsgard
GET http://localhost:41851/NuGet/Search()?$filter=IsLatestVersion&$orderby=Id&$skip=0&$top=30&searchTerm=''&targetFramework=''&includePrerelease=false
Microsoft.Web.Xdt
 2.1.1
 Microsoft Xml Document Transformation (XDT) library. For more info on XDT please visit http://msdn.microsoft.com/en-us
 /library/dd465326.aspx.
 License url: http://go.microsoft.com/fwlink/?LinkId=273778
```

and when I tried to delete the package it looks like the following
```
nuget delete Microsoft.Web.Xdt 2.1.1 -source NugetServerTest -verbosity detai
led
NuGet Version: 3.5.0.1996
WARNING: No API Key was provided and no API Key could be found for 'http://localhost:41851/NuGet/'. To save an API Key for a source use the 'setApiKey' command.
Microsoft.Web.Xdt 2.1.1 will be deleted from the 'http://localhost:41851/NuGet/'. Would you like to continue? (y/N) y
WARNING: Deleting Microsoft.Web.Xdt 2.1.1 from the 'http://localhost:41851/NuGet/'.
  DELETE http://localhost:41851/NuGet/Microsoft.Web.Xdt/2.1.1
  NotFound http://localhost:41851/NuGet/Microsoft.Web.Xdt/2.1.1 123ms
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c.<DeletePackageFromServer>b__23_1(HttpResponseMessage response)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<DeletePackageFromServer>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<DeletePackage>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Delete>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.DeleteRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.DeleteCommand.<ExecuteCommandAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c.<DeletePackageFromServer>b__23_1(HttpResponseMessage response)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<DeletePackageFromServer>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<DeletePackage>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Delete>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.DeleteRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.DeleteCommand.<ExecuteCommandAsync>d__12.MoveNext()<---
```

When I check the XML for the path to the package it is showing `http://localhost:41851/api/v2/package/microsoft.web.xdt/2.1.1`.

Is the delete command using wrong path for removing packages?

(same issue with nuget cli 3.4.4)

**Comment by joelverhagen** [comment]
This is a NuGet.Server issue, not client (nuget.exe). Moving to the server-side repo.

**Comment by joelverhagen** [comment]
Issue moved to [NuGet/NuGetGallery #3440](https://github.com/NuGet/NuGetGallery/issues/3440) via [**ZenHub**](https://www.zenhub.com/)
