### ISSUE TITLE
strange error during restore - method not found

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4272]
Error occurred while restoring NuGet packages: Method not found: 'NuGet.RuntimeModel.RuntimeGraph NuGet.RuntimeModel.JsonRuntimeFormat.ReadRuntimeGraph(Newtonsoft.Json.Linq.JToken)'.

per mail thread.

**Comment by rrelyea** [comment]
[Update - Did not turn out to be this] May be related to Out of Process analyzers. Sounds like a fix may be in today's build, per email.

**Comment by rrelyea** [comment]
believe it will be fixed by this work: https://github.com/dotnet/roslyn-project-system/issues/1211 (should we move to sdk repo)

**Comment by AArnott** [comment]
This repro'd for me on today's e2e testing build: d15prerel 26120.4. Running scenario 31., after creating the 3 projects, VS crashed due to dotnet/roslyn#16410. And after reloading VS and reloading the solution this error appears twice in the error list.

**Comment by rrelyea** [comment]
SDK fix is being validated. PR is here: https://github.com/dotnet/sdk/pull/699 (don't know what the tracking issue is. going to mark this one as external.)

**Comment by clairernovotny** [comment]
I'm still seeing this in RC3

**Comment by rrelyea** [comment]
Let's discuss this one over here: https://github.com/dotnet/sdk/issues/745
Should have been fixed in RC3

**Comment by iskiselev** [comment]
It this error expected in RC.3+26127.3?
I get it on one of my solutions, and package restore doesn't work after it. If it helps, here is my stack trace:
```
Error occurred while restoring NuGet packages: System.MissingMethodException: Method not found: 'NuGet.RuntimeModel.RuntimeGraph NuGet.RuntimeModel.JsonRuntimeFormat.ReadRuntimeGraph(Newtonsoft.Json.Linq.JToken)'.
   at NuGet.ProjectModel.JsonPackageSpecReader.GetPackageSpec(JObject rawPackageSpec, String name, String packageSpecPath, String snapshotValue)
   at NuGet.ProjectModel.JsonPackageSpecReader.GetPackageSpec(Stream stream, String name, String packageSpecPath, String snapshotValue)
   at NuGet.ProjectModel.JsonPackageSpecReader.GetPackageSpec(String name, String packageSpecPath)
   at NuGet.ProjectManagement.Projects.ProjectJsonBuildIntegratedNuGetProject.get_JsonPackageSpec()
   at NuGet.ProjectManagement.Projects.ProjectJsonBuildIntegratedNuGetProject.<GetPackageSpecsAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<GetSolutionRestoreSpec>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<IsRestoreRequiredAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestorePackageSpecProjectsAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<ExecuteAsync>d__14.MoveNext()
```

**Comment by rrelyea** [comment]
SDK team fixed partway for RC3, but seems like they didn't fix all the way
SDK team believes they have fixed it all the way now, next update will have it.
Tracked here: https://github.com/dotnet/sdk/issues/745
