### ISSUE TITLE
Can't add a packagereference to a project with a reference to a .Net Standard project

### ISSUE THREAD

**Issue by ridomin** [NuGet/Home#4384]
## Details about Problem
Using VS 2017 RC (D15rel 26119.0)
Package Manager Console Host Version 4.0.0.2215

## Detailed repro steps so we can see the same problem

1. Create a Console App (.NET Desktop)

2. Create a Class Library (Net Standard)

3. Reference the Class Library from the Console App

4. Add a NuGet to the console app (and select package references)

Package Manager fails with 
System.Runtime.InteropServices.COMException (0x8004C738): Exception from HRESULT: 0x8004C738

### Verbose Logs
```
System.Runtime.InteropServices.COMException (0x8004C738): Exception from HRESULT: 0x8004C738
   at VSLangProj150.Reference6.GetMetadata(Array parrbstrDesiredMetadata, Array& pparrbstrMetadataElements, Array& pparrbstrMetadataValues)
   at NuGet.PackageManagement.VisualStudio.EnvDTEProjectAdapter.<GetLegacyCSProjProjectReferences>d__37.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.GetPackageSpec()
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.<>c__DisplayClass36_0`1.<<RunOnUIThread>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.<RunOnUIThread>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.<GetPackageSpecAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.<GetInstalledPackagesAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.DetailControlModel.<GetDependencies>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.DetailControlModel.<<get_InstalledPackageDependencies>b__16_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at NuGet.PackageManagement.UI.DetailControlModel.get_InstalledPackageDependencies()
   at NuGet.PackageManagement.UI.PackageDetailControlModel.UpdateInstalledVersion()
   at NuGet.PackageManagement.UI.PackageDetailControlModel.NuGetProjectChanged(Object sender, NuGetProjectEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.<UpdateNuGetProjectToPackageRef>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.NuGetUI.<UpdateNuGetProjectToPackageRef>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<CheckPackageManagementFormat>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__7.MoveNext()
Time Elapsed: 00:00:00
========== Finished ==========


```

**Comment by jainaashish** [comment]
dup# https://github.com/NuGet/Home/issues/4326
