### ISSUE TITLE
Nuget pack allows multiple files with the same path to be added to a package

### ISSUE THREAD

**Issue by Kieranties** [NuGet/Home#4388]
## Details about Problem
NuGet version: `3.5.0.1938`
Worked in: `2.8.60717.93`

## Detailed repro steps so we can see the same problem

1. Create the following folder structure
```
Root
| - Folder1
| | - SomeFile.txt
| - Folder2
| | - SomeFile.txt
| - Folder3
  | SomeFile.txt
```

2. In the root, add the following nuspec as `root.nuspec'
```
<?xml version="1.0"?>
<package>
  <metadata>
    <id>Root.Error</id>
    <version>0.0.0</version>
    <authors>Kieranties</authors>
    <owners>Kieranties</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Shows Error</description>
    <copyright>Kieranties</copyright>
  </metadata>
  <files>    
    <file  src="Folder*\SomeFile.*"  target="lib\net462"  />
  </files>
</package>
```

3. Run `nuget pack` in the root folder.

## Expected Result
I expected the pack to fail, due to having the same file packed multiple times.  I expected the same error output as version 2.8.60717.93

```
C:\root
> nuget pack
Attempting to build package from 'root.nuspec'.
lib\net462\SomeFile.txt
Cannot add part for the specified URI because it is already in the package.
```
## Actual Result
The pack succeeds and results in a nuget package that cannot be installed or extracted via zip utilities (see image for package contents)
![errorpackage](https://cloud.githubusercontent.com/assets/351423/22251857/300acb22-e244-11e6-8162-a23e3afba0cd.PNG)

### Verbose Logs

```
NuGet Version: 3.5.0.1938
Attempting to build package from 'root.nuspec'.

Id: Root.Error
Version: 0.0.0
Authors: Kieranties
Description: Shows Error
Dependencies: None

Added file '[Content_Types].xml'.
Added file '_rels/.rels'.
Added file 'lib/net462/SomeFile.txt'.
Added file 'lib/net462/SomeFile.txt'.
Added file 'lib/net462/SomeFile.txt'.
Added file 'package/services/metadata/core-properties/c3408a9ca1e2478da98d9856766d0e69.psmdcp'.
Added file 'Root.Error.nuspec'.

Successfully created package 'C:\root\Root.Error.0.0.0.nupkg'.
```

### Sample Project

[repro.zip](https://github.com/NuGet/Home/files/726971/repro.zip)

**Comment by unclev** [comment]
The following piece of code

```cs
using System.IO;
using NuGet;

namespace repack
{
    public class Class1
    {
        public void Repack()
        {
            var nupkg = File.ReadAllBytes("root.nupkg");
            Stream stream = new MemoryStream(nupkg);
            IPackage pack = new ZipPackage(stream);
            // ...
        }
    }
}
```
causes exception like this
```
System.ArgumentException: Item has already been added. Key in dictionary: 'SomeFile.txt'  Key being added: 'SomeFile.txt'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.Add(Object key, Object value)
   at System.Collections.Specialized.OrderedDictionary.Add(Object key, Object value)
   at MS.Internal.IO.Zip.ZipIOCentralDirectoryBlock.ParseRecord(BinaryReader reader, Int64 centralDirectoryOffset, Int32 centralDirectoryCount, Int64 expectedCentralDirectorySize)
   at MS.Internal.IO.Zip.ZipIOCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
   at MS.Internal.IO.Zip.ZipIOBlockManager.get_CentralDirectoryBlock()
   at MS.Internal.IO.Zip.ZipArchive.GetFiles()
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(Stream stream)
   at repack.Class1.Repack() in D:\git.unclev.ru\misc\PackagingTest01\repack\Class1.cs:line 12
```
(This is just for example. My actual filenames, code, and exception details slightly differ).

**Comment by abatishchev** [comment]
Got the same error between upgrading from 5.8.1.7021 to 5.11.0.10.

Working build:

```
[INFO] [14] NuGet Version: 5.8.1.7021
[INFO] [15] Attempting to build package from 'MyApp.nuspec'.
[INFO] [16] Id: MyApp
[INFO] [17] Version: 0.0.1804.3804
[INFO] [21] Dependencies: None
[INFO] [22] Added file '[Content_Types].xml'.
[INFO] [23] Added file '_rels/.rels'.
```

Failing build:

```
[INFO] [8495] NuGet Version: 5.11.0.10
[INFO] [8496] Attempting to build package from 'MyApp.nuspec'.
##[error][Package] [Package NuGet] [8497] Error NU5050: Attempted to pack multiple files into the same location(s). The following destinations were used multiple times: content\ApplicationManifest.xml
[ERROR] [8497] Error NU5050: Attempted to pack multiple files into the same location(s). The following destinations were used multiple times: content\ApplicationManifest.xml
##[error][Package] [Package NuGet] [8498] NuGet.Packaging.Core.PackagingException: Attempted to pack multiple files into the same location(s). The following destinations were used multiple times: content\ApplicationManifest.xml
[ERROR] [8498] NuGet.Packaging.Core.PackagingException: Attempted to pack multiple files into the same location(s). The following destinations were used multiple times: content\ApplicationManifest.xml
[ERROR] [8499]    at NuGet.Packaging.PackageBuilder.ValidateFilesUnique(IEnumerable`1 files)
##[error][Package] [Package NuGet] [8499]    at NuGet.Packaging.PackageBuilder.ValidateFilesUnique(IEnumerable`1 files)
[ERROR] [8500]    at NuGet.Packaging.PackageBuilder.Save(Stream stream)
##[error][Package] [Package NuGet] [8500]    at NuGet.Packaging.PackageBuilder.Save(Stream stream)
[ERROR] [8501]    at NuGet.Commands.PackCommandRunner.BuildPackage(PackageBuilder builder, String outputPath, Boolean symbolsPackage)
##[error][Package] [Package NuGet] [8501]    at NuGet.Commands.PackCommandRunner.BuildPackage(PackageBuilder builder, String outputPath, Boolean symbolsPackage)
[ERROR] [8502]    at NuGet.Commands.PackCommandRunner.BuildFromNuspec(String path)
##[error][Package] [Package NuGet] [8502]    at NuGet.Commands.PackCommandRunner.BuildFromNuspec(String path)
##[error][Package] [Package NuGet] [8503]    at NuGet.CommandLine.PackCommand.ExecuteCommand()
[ERROR] [8503]    at NuGet.CommandLine.PackCommand.ExecuteCommand()
##[error][Package] [Package NuGet] [8504]    at NuGet.CommandLine.Command.ExecuteCommandAsync()
[ERROR] [8504]    at NuGet.CommandLine.Command.ExecuteCommandAsync()
##[error][Package] [Package NuGet] [8505]    at NuGet.CommandLine.Command.Execute()
[ERROR] [8505]    at NuGet.CommandLine.Command.Execute()
##[error][Package] [Package NuGet] [8506]    at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
[ERROR] [8506]    at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by BrianMouncer** [comment]
Why does adding Nuget.exe pack -Properties "NoWarn=NU5050" not suppress this error?
Is there another form like NoError=NU5050 property that I have not been able to track down?
Or should NoWarn=NU505 work but also has a bug?

**Comment by nkolev92** [comment]
`NU5050` is an error, that's now being raised when duplicates are attempted to be packed. 

Unfortunately, there's an issue that it can sometimes error out too aggressively. 
That is being tracked in https://github.com/NuGet/Home/issues/11052.
