### ISSUE TITLE
PackageRef migration for PCL project: Adding a package to a Portable Class Library that does not contain project.json fails.

### ISSUE THREAD

**Issue by unniravindranathan-okta** [NuGet/Home#4418]
1. Create PCL project targeting 4.6 and Win10 (this template uses Microsoft.NETCore and Microsoft.NETCore.Portable.Compatibility packages)
2. Remove project.json 
3. Reload the project
4. Try to add add Microsoft.NETCore.

**Observed:** Exception message below.

System.ArgumentException: Invalid framework version '.0'.
   at NuGet.Frameworks.NuGetFramework.ParseFrameworkName(String frameworkName, IFrameworkNameProvider mappings)
   at NuGet.PackageManagement.VisualStudio.EnvDTEProjectAdapter.get_TargetNuGetFramework()
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.GetPackageSpec()
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.<>c__DisplayClass36_0`1.<<RunOnUIThread>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.<RunOnUIThread>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.<GetPackageSpecAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.<GetInstalledPackagesAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at NuGet.PackageManagement.UI.DetailControlModel.<GetDependencies>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.DetailControlModel.<<get_InstalledPackageDependencies>b__16_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at NuGet.PackageManagement.UI.DetailControlModel.get_InstalledPackageDependencies()
   at NuGet.PackageManagement.UI.PackageDetailControlModel.UpdateInstalledVersion()
   at NuGet.PackageManagement.UI.PackageDetailControlModel.NuGetProjectChanged(Object sender, NuGetProjectEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.<UpdateNuGetProjectToPackageRef>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.NuGetUI.<UpdateNuGetProjectToPackageRef>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<CheckPackageManagementFormat>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__7.MoveNext()
Time Elapsed: 00:00:00
========== Finished ==========

**Comment by cni13** [comment]
What is the workaround for this issue? I use VS 2017 RC and it's VS that changed the reference setting to ProjectReference in csproj.

**Comment by jainaashish** [comment]
@zuckerthoben Current workaround for this issue is to add `NuGetTargetFramework` property with right target framework value explicitly in csproj file. So add below PropertyGroup section in your csproj file and it will work.

  ```
<PropertyGroup>
    <NuGetTargetFramework>dotnet</NuGetTargetFramework>
  </PropertyGroup>
```

**Comment by cni13** [comment]
@jainaashish What values can I use for the NugetTargetFramework attribute? Do I enter dotnet on all my projects? (Xamarin.Android, iOS, PCL, UWP, WPF, ASP.NET Web API) ?

**Comment by jainaashish** [comment]
@zuckerthoben not for all projects, basically try to relate it with framework value defined in project.json file. And please keep in mind, it's a temp workaround, we'll anyway fix it properly in next visual studio update.

**Comment by cni13** [comment]
@jainaashish Ok. I guess I will stick with my rebuilt packages.config. When VS 2017 releases I will evaluate switch to .NET standard and the csproj format.

**Comment by jainaashish** [comment]
Need to discuss and finalize behavior for PCL projects to support PackageReference with .Net core team

**Comment by jainaashish** [comment]
So the right guidance here is to move from PCL library to .net standard library. We'll well document this and what customer is expected to do here. But there is no engineering effort required for now. So closing this bug.
