### ISSUE TITLE
NuGet client 3.5.0 restore ignores -MSBuild command-line argument

### ISSUE THREAD

**Issue by Gudahtt** [NuGet/Home#4429]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version (x.x.x.xxx): 3.5.0.1938

VS version: 2013

OS version (i.e. win10 v1607 (14393.321)): Windows 10 Pro v1607 build 14393.693

Worked before? If so, with which NuGet version: 3.4.4, and latest dev

## Detailed repro steps so we can see the same problem

1. Ensure that only MSBuild 12 is installed

2. Call `nuget restore -MSBuild 12`

3. It will fail, claiming that it cannot find MSBuild version 14

### Verbose Logs

```
System.AggregateException: One or more errors occurred. ---> NuGet.CommandLine.CommandLineException: Failed to load msbuild Toolset ---> System.IO.FileNotFoundException: Could not load
 file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivH
ostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHo
stBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPr
ivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at NuGet.CommandLine.MsBuildUtility.GetMsbuildDirectory(String userVersion, IConsole console)
   --- End of inner exception stack trace ---
   at NuGet.CommandLine.MsBuildUtility.GetMsbuildDirectory(String userVersion, IConsole console)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>b__22_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at NuGet.CommandLine.RestoreCommand.ProcessSolutionFile(String solutionFileFullPath, PackageRestoreInputs restoreInputs)
   at NuGet.CommandLine.RestoreCommand.GetInputsFromDirectory(String directory, PackageRestoreInputs packageRestoreInputs)
   at NuGet.CommandLine.RestoreCommand.DetermineRestoreInputs()
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) NuGet.CommandLine.CommandLineException: Failed to load msbuild Toolset ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build,
 Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivH
ostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHo
stBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPr
ivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at NuGet.CommandLine.MsBuildUtility.GetMsbuildDirectory(String userVersion, IConsole console)
   --- End of inner exception stack trace ---
   at NuGet.CommandLine.MsBuildUtility.GetMsbuildDirectory(String userVersion, IConsole console)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>b__22_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at NuGet.CommandLine.RestoreCommand.ProcessSolutionFile(String solutionFileFullPath, PackageRestoreInputs restoreInputs)
   at NuGet.CommandLine.RestoreCommand.GetInputsFromDirectory(String directory, PackageRestoreInputs packageRestoreInputs)
   at NuGet.CommandLine.RestoreCommand.DetermineRestoreInputs()
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__22.MoveNext()<---
```

I've testing this with the latest dev branch, and I couldn't reproduce the problem. It consistently happens with version 3.5.0 though.

I discovered this via the issue https://github.com/cake-build/cake/issues/1449 , which led to me attempting to call nuget directly from the command-line.

**Comment by rrelyea** [comment]
NuGet.exe 3.5.0 needs to have msbuild 14 to find other versions of msbuild.
NuGet.exe 4.0.0 has improved the technique, and should no longer have this problem.
Marking as fixed.

**Comment by Gudahtt** [comment]
Good to know; thanks.

**Comment by Kittyfisto** [comment]
So I need to install Visual Studio 2017 in order to run nuget (4) against Visual Studio 12?

**Comment by Gudahtt** [comment]
@Kittyfisto Nuget 4 shouldn't have this problem - at least as far as I know. But even with Nuget 3, you don't need full Visual Studio 2015 or 2017; the build tools for either will suffice.

Visual Studio 2015: https://www.microsoft.com/en-us/download/details.aspx?id=48159

Or

Visual Studio 2017: https://www.visualstudio.com/downloads/
Go to 'Other Tools and Frameworks' and you should see 'Build Tools for Visual Studio 2017'.

**Comment by Kittyfisto** [comment]
@Gudahtt Thanks for the quick answer! That works for me.
