### ISSUE TITLE
Pack task should not be reading the project file

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4473]
I noticed that the Pack task is reading the project file - this is a no no for a task:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "PackTask" task failed unexpectedly.
System.Exception: Enabling license acceptance requires a license url.
   at NuGet.Packaging.Manifest.Validate(Manifest manifest)
   at NuGet.Packaging.Manifest.Save(Stream stream, Boolean validate, Int32 minimumManifestVersion)
   at NuGet.Commands.MSBuildProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage()
   at NuGet.Build.Tasks.Pack.PackTaskLogic.BuildPackage(PackCommandRunner runner)
   at NuGet.Build.Tasks.Pack.PackTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ClassLibrary23	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets	92	
```

Builds can occur on unsaved in-memory projects - reading the project file is not the right thing. You should be passing all the build properties in to the task.

**Comment by rohit21agrawal** [comment]
The pack task does not read the project file.. what made you think that is so?

**Comment by davkean** [comment]
What does this line do? https://github.com/NuGet/NuGet.Client/blob/77f879be85b3bad14d8d18b6e31c5c1fc19446da/src/NuGet.Core/NuGet.Commands/CommandRunners/PackCommandRunner.cs#L722

**Comment by rohit21agrawal** [comment]
If Pack has been executed as a msbuild task, all it does is create an object of MSBuildProjectFactory from the packArgs object . PackArgs contains all the inputs that it needs from the csproj file.

If pack has been invoked via nuget.exe pack, then we create a Microsoft.Build.Project object from the project file

**Comment by rohit21agrawal** [comment]
Essentially the difference in code path is in the following two different ProjectFactory delegates being passed around : 
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/PackTaskLogic.cs#L189

vs

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/PackCommand.cs#L154

**Comment by davkean** [comment]
👍
