### ISSUE TITLE
[Watson] dev11nonfatalerror: DEV11NONFATAL_CLR_EXCEPTION_System.NullReferenceException_80004003_NuGet.PackageManagement.VisualStudio.dll!Unknown

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#4485]
Internal bug: 378900

```
NuGet.PackageManagement.VisualStudio!Unknown
2. at mscorlib.ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess in TaskAwaiter.cs
3. at mscorlib.ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification in TaskAwaiter.cs
4. at Microsoft.VisualStudio.Threading.ni!Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread in JoinableTask.cs
5. at Microsoft.VisualStudio.Threading.ni!Microsoft.VisualStudio.Threading.JoinableTask_1[[System.Boolean,_mscorlib]].CompleteOnCurrentThread
6. at Microsoft.VisualStudio.Threading.ni!Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[[System.Boolean,_mscorlib]]
7. at NuGet.PackageManagement.VisualStudio!Unknown
8. at NuGet.SolutionRestoreManager!Unknown
9. at mscorlib.ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess in TaskAwaiter.cs
10. at mscorlib.ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification in TaskAwaiter.cs
11. at Microsoft.VisualStudio.ProjectSystem.Managed.VS!Unknown
12. at mscorlib.ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw in exceptionservicescommon.cs
13. at Microsoft.VisualStudio.ProjectSystem.ni!Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow in CommonProjectSystemTools.cs
14. at Microsoft.VisualStudio.ProjectSystem.Implementation.ni!Unknown in ProjectErrorReporting.cs
15. at Microsoft.VisualStudio.ProjectSystem.Implementation.ni!Unknown in ExceptionFilter.cs
16. at UNKNOWN!UNKNOWN
```

**Comment by emgarten** [comment]
55 hits so far in VS 2017 RTW, this is currently the top issue

**Comment by rrelyea** [comment]
Let's figure out issue. Depending on timing of fix availability, we'll take for 4.1 or 4.3.

**Comment by zhili1208** [comment]
vsSolution might be null in this method, this is the only place which can throw null ref exception: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSSolutionManager.cs#L580
attached debugger to the dump file, got following stack:
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.<<get_IsSolutionFullyLoaded>b__77_0>d.MoveNext() in C:\BuildAgent\work\b5d8a6f41378b0dd\NuGet.Client\src\NuGet.Clients\PackageManagement.VisualStudio\IDE\VSSolutionManager.cs:line 477
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.get_IsSolutionFullyLoaded() in C:\BuildAgent\work\b5d8a6f41378b0dd\NuGet.Client\src\NuGet.Clients\PackageManagement.VisualStudio\IDE\VSSolutionManager.cs:line 472
   at NuGet.SolutionRestoreManager.SolutionRestoreWorker.<InitializeAsync>d__31.MoveNext() in C:\BuildAgent\work\b5d8a6f41378b0dd\NuGet.Client\src\NuGet.Clients\NuGet.SolutionRestoreManager\SolutionRestoreWorker.cs:line 142
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreWorker.<ScheduleRestoreAsync>d__36.MoveNext() in C:\BuildAgent\work\b5d8a6f41378b0dd\NuGet.Client\src\NuGet.Clients\NuGet.SolutionRestoreManager\SolutionRestoreWorker.cs:line 234
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.NuGetRestorer.<>c__DisplayClass17_0.<<ProjectPropertyChangedAsync>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )

**Comment by emgarten** [comment]
@rrelyea @zhili1208 this has 56 hits in 15.1. Can we get this merged for 15.3?

**Comment by jviau** [comment]
Ran into this creating a new .netcore project on 26507.0-Preview d15rel

**Comment by alpaix** [comment]
@rrelyea Not for preview 3?

**Comment by jeremymeng** [comment]
Running into this when open project via `devenv LazyPerf.csproj` cloned from https://github.com/jeremymeng/LazyPerf

**Comment by zhili1208** [comment]
@jeremymeng what's the VS version you are using?

**Comment by jeremymeng** [comment]
@zhili1208 VS 2017 15.2.  I think the project is targeting netcoreapp2.0, which isn't supported in this version.  The latest VS preview does not have this issue.

**Comment by zhili1208** [comment]
thanks @jeremymeng unfortunately I didn't repro this on 15.2(26430.16). still need a repro to understand which variable is null.

**Comment by jeremymeng** [comment]
@zhili1208 I tried again but couldn't repro it either...

**Comment by jainaashish** [comment]
this failure isnt there in recent visual studio releases so closing it for now.
