### ISSUE TITLE
NuGet.CommandLine.CommandLineException: Failed to load msbuild Toolset

### ISSUE THREAD

**Issue by takinosaji** [NuGet/Home#4507]
NuGet product used (NuGet.exe):

NuGet version (3.5.0 / 4.0.0-rc2):

OS version (win10):

Problem appeared for restoring of packages with nuget in Teamcity after uninstalling of Visual Studio 2015 and installing of VS2017 RC with new MSBuild. The problem is that nuget is intended to use MSbuild 14 even if i set version 15 via **-msbuildversion** parameter.

Error log:
ystem.AggregateException: One or more errors occurred. ---> NuGet.CommandLine.CommandLineException: Failed to load msbuild Toolset ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
[04:12:10]	   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[04:12:10]	   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[04:12:10]	   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[04:12:10]	   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
[04:12:10]	   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
[04:12:10]	   at System.Reflection.Assembly.Load(String assemblyString)
[04:12:10]	   at NuGet.CommandLine.MsBuildUtility.GetMsbuildDirectory(String userVersion, IConsole console)
[04:12:10]	   --- End of inner exception stack trace ---
[04:12:10]	   at NuGet.CommandLine.MsBuildUtility.GetMsbuildDirectory(String userVersion, IConsole console)
[04:12:10]	   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>b__22_0()
[04:12:10]	   at System.Lazy`1.CreateValue()
[04:12:10]	   at System.Lazy`1.LazyInitValue()
[04:12:10]	   at System.Lazy`1.get_Value()
[04:12:10]	   at NuGet.CommandLine.RestoreCommand.ProcessSolutionFile(String solutionFileFullPath, PackageRestoreInputs restoreInputs)
[04:12:10]	   at NuGet.CommandLine.RestoreCommand.GetInputsFromFile(String projectFilePath, PackageRestoreInputs packageRestoreInputs)
[04:12:10]	   at NuGet.CommandLine.RestoreCommand.DetermineRestoreInputs()
[04:12:10]	   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__22.MoveNext()
[04:12:10]	   --- End of inner exception stack trace ---
[04:12:10]	   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[04:12:10]	   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[04:12:10]	   at NuGet.CommandLine.Command.Execute()
[04:12:10]	   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
[04:12:10]	---> (Inner Exception #0) NuGet.CommandLine.CommandLineException: Failed to load msbuild Toolset ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
[04:12:10]	   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[04:12:10]	   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[04:12:10]	   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[04:12:10]	   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
[04:12:10]	   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
[04:12:10]	   at System.Reflection.Assembly.Load(String assemblyString)
[04:12:10]	   at NuGet.CommandLine.MsBuildUtility.GetMsbuildDirectory(String userVersion, IConsole console)
[04:12:10]	   --- End of inner exception stack trace ---
[04:12:10]	   at NuGet.CommandLine.MsBuildUtility.GetMsbuildDirectory(String userVersion, IConsole console)
[04:12:10]	   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>b__22_0()
[04:12:10]	   at System.Lazy`1.CreateValue()
[04:12:10]	   at System.Lazy`1.LazyInitValue()
[04:12:10]	   at System.Lazy`1.get_Value()
[04:12:10]	   at NuGet.CommandLine.RestoreCommand.ProcessSolutionFile(String solutionFileFullPath, PackageRestoreInputs restoreInputs)
[04:12:10]	   at NuGet.CommandLine.RestoreCommand.GetInputsFromFile(String projectFilePath, PackageRestoreInputs packageRestoreInputs)
[04:12:10]	   at NuGet.CommandLine.RestoreCommand.DetermineRestoreInputs()
[04:12:10]	   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__22.MoveNext()<---
[04:12:10]	
[04:12:10]	Process exited with code 1

**Comment by rrelyea** [comment]
3.5.0 had this problem.
4.0.0-rc4 and later should be fine. See http://nuget.org/downloads
Please confirm this works for you.

**Comment by zhili1208** [comment]
BTW, specifing 15 for msbuildVersion won't work for VS2017, because the msbuild version is 15.1, and nuget will automatically find msbuild 15, you don't need to use msbuildversion for msbuild 15
