### ISSUE TITLE
Pack throws exception if IncludeSource is used in a project with multiple TFMs

### ISSUE THREAD

**Issue by srivatsn** [NuGet/Home#4536]
_From @niemyjski on February 8, 2017 15:41_

I'm running VS2017 RC3 (Latest) and I'm seeing this randomly when I build my solution or the `Foundatio.Redis` package.

Just clone (https://github.com/exceptionless/foundatio) and try building different projects / run the tests

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "PackTask" task failed unexpectedly.
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NuGet.Build.Tasks.Pack.PackTaskLogic.GetSourceFiles(IPackTaskRequest`1 request, String currentProjectDirectory)
   at NuGet.Build.Tasks.Pack.PackTaskLogic.GetPackArgs(IPackTaskRequest`1 request)
   at NuGet.Build.Tasks.Pack.PackTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Foundatio	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets	104	
```

_Copied from original issue: dotnet/sdk#838_

**Comment by srivatsn** [comment]
_From @niemyjski on February 8, 2017 15:54_

Also, is there a good place to log an issue with the VS Test runner? I can't seem to be able to profile any unit tests either. And My redis unit tests aren't discoverable now either :\

**Comment by niemyjski** [comment]
This issue is so annoying I wish I could go back to the previous RC

**Comment by rohit21agrawal** [comment]
@niemyjski  what arguments are you passing to pack foundation.redis ?

**Comment by niemyjski** [comment]
@rohit21agrawal  I have the new feature to package on build defined in the csproj... But this is just from within Visual Studio when I right click a project and select build or click run all unit tests (which does a build). It's super annoying

**Comment by rohit21agrawal** [comment]
@niemyjski  figured out..this is a bug in the Pack code when ```IncludeSource``` is set to true. while i am figuring out the exact cause, you can work around by setting this to false in your project.

**Comment by rohit21agrawal** [comment]
https://github.com/exceptionless/Foundatio/blob/master/build/common.props#L15 - set this to false for now.

**Comment by niemyjski** [comment]
Thanks, seems kinda odd that building of packages would happen so often even if nothing changed. Especially when I want to just run tests.

**Comment by rohit21agrawal** [comment]
@niemyjski i agree. we plan to fix this soon : https://github.com/NuGet/Home/issues/4363
