### ISSUE TITLE
NuGet ProjectSystemCache error when adding package in vsix package

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4545]
vsfeedback 784047 filed with RC3.1 | https://developercommunity.visualstudio.com/content/problem/16659/nuget-projectsystemcache-error-when-adding-package.html

(please consider that the user may had added the package via PackageRef or Packages.config)

I have an existing solution that builds in VS2017RC. It is a VSIX project and I'm trying to add the Microsoft.VSSDK.BuildTools package to it. When I add the package NuGet throws an exception saying value cannot be null or an empty string.

System.ArgumentException: Value cannot be null or an empty string.
Parameter name: name
   at NuGet.PackageManagement.VisualStudio.ProjectSystemCache.ContainsKey(String name)
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.RemoveEnvDTEProjectFromCache(String name)
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.<UpdateNuGetProjectToPackageRef>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.NuGetUI.<UpdateNuGetProjectToPackageRef>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<CheckPackageManagementFormat>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__7.MoveNext()

**Comment by rrelyea** [comment]
Likely #4433 -- currently in 4.0.1
Please take a peek to confirm. Want to think more if we should be taking 4433 in RTM.

**Comment by CoolDadTx** [comment]
I'm no longer having this issue in RC4-26206.0. The packages are being stored in packages.config.

**Comment by rohit21agrawal** [comment]
@rrelyea  @CoolDadTx  good to close this out then?

**Comment by CoolDadTx** [comment]
Fine with me.
