### ISSUE TITLE
TelemetryEvent crashes restore if project entry is null

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#4678]
Observed locally on NuGet.Sln

Call [here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionRestoreJob.cs#L248) seems to be failing because the entries inside the primaryCache are not correctly populated. 

I am investing the cache issue. But the telemetry call should not block restore.

Stack - 

```
All packages are already installed and there is nothing to restore.
Time Elapsed: 00:00:19.5534858
========== Finished ==========

Error occurred while restoring NuGet packages: System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<>c.<EmitRestoreTelemetryEvent>b__17_0(NuGetProject project)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.EmitRestoreTelemetryEvent(IEnumerable`1 projects, RestoreOperationSource source, DateTimeOffset startTime, NuGetOperationStatus status, Int32 packageCount, Double duration)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<ExecuteAsync>d__15.MoveNext()
```

**Comment by AArnott** [comment]
I am seeing this consistently in at least one of my solutions when I try to build to run tests. The callstack for the NRE is slightly different.

```
NuGet.SolutionRestoreManager.dll!NuGet.SolutionRestoreManager.SolutionRestoreJob.EmitRestoreTelemetryEvent.AnonymousMethod__17_0(NuGet.ProjectManagement.NuGetProject project)	Unknown
System.Core.dll!System.Linq.EnumerableSorter<NuGet.ProjectManagement.NuGetProject, string>.ComputeKeys(NuGet.ProjectManagement.NuGetProject[] elements, int count)	Unknown
System.Core.dll!System.Linq.EnumerableSorter<NuGet.ProjectManagement.NuGetProject>.Sort(NuGet.ProjectManagement.NuGetProject[] elements, int count)	Unknown
System.Core.dll!System.Linq.OrderedEnumerable<NuGet.ProjectManagement.NuGetProject>.GetEnumerator()	Unknown
System.Core.dll!System.Linq.Enumerable.WhereSelectEnumerableIterator<NuGet.ProjectManagement.NuGetProject, string>.MoveNext()	Unknown
System.Core.dll!System.Linq.Buffer<string>.Buffer(System.Collections.Generic.IEnumerable<string> source)	Unknown
System.Core.dll!System.Linq.Enumerable.ToArray<string>(System.Collections.Generic.IEnumerable<string> source)	Unknown
NuGet.SolutionRestoreManager.dll!NuGet.SolutionRestoreManager.SolutionRestoreJob.EmitRestoreTelemetryEvent(System.Collections.Generic.IEnumerable<NuGet.ProjectManagement.NuGetProject> projects, NuGet.PackageManagement.UI.RestoreOperationSource source, System.DateTimeOffset startTime, NuGet.PackageManagement.UI.NuGetOperationStatus status, int packageCount, double duration)	Unknown
NuGet.SolutionRestoreManager.dll!NuGet.SolutionRestoreManager.SolutionRestoreJob.RestoreAsync(bool forceRestore, NuGet.PackageManagement.UI.RestoreOperationSource restoreSource, System.Threading.CancellationToken token)	Unknown
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine) Line 1090	C#
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0() Line 977	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123	C#
mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0() Line 288	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123	C#
mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask) Line 810	C#
mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3617	C#
mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree() Line 2363	C#
mscorlib.dll!System.Threading.Tasks.Task<bool>.TrySetResult(bool result) Line 490	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<bool>.SetResult(bool result) Line 608	C#
NuGet.PackageManagement.VisualStudio.dll!NuGet.PackageManagement.VisualStudio.VSSolutionManager.SolutionHasDeferredProjectsAsync()	Unknown
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine) Line 1090	C#
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0() Line 977	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123	C#
mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0() Line 288	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123	C#
mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask) Line 810	C#
mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3617	C#
mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree() Line 2363	C#
mscorlib.dll!System.Threading.Tasks.Task<bool>.TrySetResult(bool result) Line 490	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<bool>.SetResult(bool result) Line 608	C#
Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTask<bool>.JoinAsync(System.Threading.CancellationToken cancellationToken)	Unknown
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine) Line 1090	C#
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0() Line 977	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123	C#
mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0() Line 288	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123	C#
mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask) Line 810	C#
mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3617	C#
mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree() Line 2363	C#
mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult(System.Threading.Tasks.VoidTaskResult result) Line 490	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.VoidTaskResult result) Line 608	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult> completedTask) Line 638	C#
Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTask.JoinAsync(System.Threading.CancellationToken cancellationToken)	Unknown
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine) Line 1090	C#
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0() Line 977	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123	C#
mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0() Line 288	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123	C#
mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.ExecuteWorkItemHelper() Line 681	C#
mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() Line 715	C#
mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820	C#
mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Line 1161	C#
```

**Comment by mishra14** [comment]
@emgarten

**Comment by emgarten** [comment]
@AArnott can you share your solution and steps?

**Comment by AArnott** [comment]
I'm afraid I've lost the repro. ☹️

**Comment by mishra14** [comment]
Issue moved to [NuGet/Client.Engineering #54](https://github.com/NuGet/Client.Engineering/issues/54) via [**ZenHub**](https://www.zenhub.com/)
