### ISSUE TITLE
command line nuget restore fails with: error MSB4023:  Illegal characters in path.

### ISSUE THREAD

**Issue by philipogorman** [NuGet/Home#4705]
I get an error when trying to restore nuget package for a solution on our build server. Before a build we restore the packages with a command like this:

nuget.exe restore AutonomousApp.sln

But for this solution I get:

MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(353,30): error MSB4023: Cannot evaluate the item metadata "%(Filename)". The it
em metadata "%(Filename)" cannot be applied to the path "obj\"x86"\Debug\AutonomousApp.pdb". Illegal characters in path. [D:\Repos\git\aut
onomousapp\AutonomousApp\AutonomousApp.csproj]
    System.AggregateException: One or more errors occurred. ---> NuGet.CommandLine.CommandLineException
       at NuGet.CommandLine.MsBuildUtility.GetProjectReferences(String msbuildDirectory, String[] projectPaths, Int32 timeOut)
       at NuGet.CommandLine.RestoreCommand.DetermineRestoreInputs()
       at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__22.MoveNext()
       --- End of inner exception stack trace ---
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at NuGet.CommandLine.Command.Execute()
       at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
    ---> (Inner Exception #0) NuGet.CommandLine.CommandLineException
       at NuGet.CommandLine.MsBuildUtility.GetProjectReferences(String msbuildDirectory, String[] projectPaths, Int32 timeOut)
       at NuGet.CommandLine.RestoreCommand.DetermineRestoreInputs()
       at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__22.MoveNext()<---

We can do this successfully on many other solutions. This one is slightly different because it uses the project.json system (there is no packages.config)

There are no problems restoring in VS.

**Comment by emgarten** [comment]
@philipogorman This looks like a problem with the project file or the properties it uses, not an issue specific to restore. Does changing the properties used to build the filename solve the issue?

**Comment by emgarten** [comment]
No response.
