### ISSUE TITLE
Latest Nugetizer VSIX fails to install due to Merq dependency on Xamarin

### ISSUE THREAD

**Issue by bbowman** [NuGet/Home#5026]
@kzu We are seeing this for our customers. Interesting details in bold. I don't think Nugetizer should have a dependency on Xamarin as it is intended to be the generic solution for nuget package authoring.

4/13/17 1:38:14 PM - Microsoft VSIX Installer
4/13/17 1:38:14 PM - -------------------------------------------
4/13/17 1:38:14 PM - vsixinstaller.exe version:
4/13/17 1:38:14 PM - 15.0.26228.9 built by: D15RTWSVC
4/13/17 1:38:14 PM - -------------------------------------------
4/13/17 1:38:14 PM - Command line parameters:
4/13/17 1:38:14 PM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VSIXInstaller.exe,.\blah.vsix
4/13/17 1:38:14 PM - -------------------------------------------
4/13/17 1:38:14 PM - Microsoft VSIX Installer
4/13/17 1:38:14 PM - -------------------------------------------
4/13/17 1:38:15 PM - Initializing Install...
4/13/17 1:38:15 PM - Extension Details...
4/13/17 1:38:15 PM -     Identifier         : NuGet.Packaging
4/13/17 1:38:15 PM -     Name               : NuGetizer-3000
4/13/17 1:38:15 PM -     Author             : Microsoft
4/13/17 1:38:15 PM -     Version            : 0.1.244
4/13/17 1:38:15 PM -     Description        : NuGet Package Authoring Tools
4/13/17 1:38:15 PM -     Locale             : en-US
4/13/17 1:38:15 PM -     MoreInfoURL        : 
4/13/17 1:38:15 PM -     InstalledByMSI     : False
4/13/17 1:38:15 PM -     SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
4/13/17 1:38:15 PM - 
4/13/17 1:38:15 PM -     SignatureState     : Unsigned
4/13/17 1:38:15 PM -     Supported Products : 
4/13/17 1:38:15 PM -                     Microsoft.VisualStudio.Pro
4/13/17 1:38:15 PM -                                     Version : [15.0]
4/13/17 1:38:15 PM - 
4/13/17 1:38:15 PM -     References         : 
4/13/17 1:38:15 PM -                     -------------------------------------------------------
4/13/17 1:38:15 PM -                     Identifier   : Merq
4/13/17 1:38:15 PM -                     Name         : Extensibility Message Bus
4/13/17 1:38:15 PM -                     Version      : [1.1.17,)
4/13/17 1:38:15 PM -                     MoreInfoURL  : 
4/13/17 1:38:15 PM -                     Nested       : Yes
4/13/17 1:38:15 PM - 
4/13/17 1:38:15 PM -     Prerequisites      : 
4/13/17 1:38:15 PM -                     -------------------------------------------------------
4/13/17 1:38:15 PM -                     Identifier   : Microsoft.VisualStudio.Component.CoreEditor
4/13/17 1:38:15 PM -                     Name         : Visual Studio core editor
4/13/17 1:38:15 PM -                     Version      : [15.0,16.0)
4/13/17 1:38:15 PM - 
4/13/17 1:38:15 PM - Signature Details...
4/13/17 1:38:15 PM -     Extension is not signed.
4/13/17 1:38:15 PM - 
4/13/17 1:38:15 PM - Searching for applicable products...
4/13/17 1:38:15 PM - Found installed product - Microsoft Visual Studio Enterprise 2015
4/13/17 1:38:15 PM - Found installed product - Microsoft Visual Studio Professional 2015
4/13/17 1:38:15 PM - Found installed product - Microsoft Visual Studio Community 2015
4/13/17 1:38:15 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
4/13/17 1:38:15 PM - Found installed product - Global Location
4/13/17 1:38:15 PM - Found installed product - Visual Studio Enterprise 2017
4/13/17 1:38:15 PM - PKGDEF Information: Looking for master PkgDef file, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\master.pkgdef

4/13/17 1:38:15 PM - PKGDEF Information: Creating PkgDefCacheNonVolatile
4/13/17 1:38:15 PM - PKGDEF Information: Double-checking master pkgdef file
4/13/17 1:38:15 PM - PKGDEF Information: PkgDefManagement initialized
4/13/17 1:38:15 PM - PKGDEF Information: RootFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\

4/13/17 1:38:15 PM - PKGDEF Information: ShellFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\

4/13/17 1:38:15 PM - PKGDEF Information: PkgDefSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.admin.pkgdef

4/13/17 1:38:15 PM - PKGDEF Information: ImageManifestSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions;C:\Users\duhowett\AppData\Local\Microsoft\VisualStudio\15.0_420efee4\Extensions

4/13/17 1:38:15 PM - PKGDEF Information: ApplicationExtensionsFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions

4/13/17 1:38:15 PM - PKGDEF Information: "ZeroImpact" = dword:0, "MergeRegistry" = dword:3
4/13/17 1:38:15 PM - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
4/13/17 1:38:15 PM - PKGDEF Information: User extensions enabled by setting, Path: HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\15.0_420efee4\ExtensionManager\EnableAdminExtensions

4/13/17 1:38:15 PM - PKGDEF Information: PkgDefCache flags, PKGDEF: 7001
4/13/17 1:38:15 PM - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
4/13/17 1:38:15 PM - PKGDEF Information: PkgDefManagement startup complete
4/13/17 1:38:16 PM - The extension with ID 'NuGet.Packaging' is not installed to Visual Studio Enterprise 2017.
4/13/17 1:38:21 PM - The following target products have been selected...
4/13/17 1:38:21 PM -     Visual Studio Enterprise 2017
4/13/17 1:38:21 PM - 
4/13/17 1:38:22 PM - Beginning to install extension to Visual Studio Enterprise 2017...
4/13/17 1:38:27 PM - **Install Error : Microsoft.VisualStudio.ExtensionManager.NestedExtensionInstallException: The extension 'Merq' nested within 'NuGet.Packaging' failed to install.
Installation of Extensibility Message Bus failed. To install this extension please install at least one of the following components: Xamarin ---> System.InvalidOperationException: Installation of Extensibility Message Bus failed. To install this extension please install at least one of the following components: Xamarin**
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallNestedExtensions(InstallableExtensionImpl parentExtension, IInstalledExtension installedParentExtension, ZipPackage parentVSIX, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallNestedExtensions(InstallableExtensionImpl parentExtension, IInstalledExtension installedParentExtension, ZipPackage parentVSIX, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformLegacyInstall(InstallableExtensionImpl extension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Boolean isPackComponent, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by kzu** [comment]
Fixed with https://github.com/NuGet/NuGet.Build.Packaging/issues/121
