### ISSUE TITLE
Nuget.exe 4.3 silently ignores invalid project.json file

### ISSUE THREAD

**Issue by agr** [NuGet/Home#5253]
Tested with nuget.exe 4.3 (4045) on [this](https://github.com/agr/NugetUnparseableProjectJsonDemo) project.

When project.json cannot be parsed, running `nuget restore` does nothing and produces no indication in the output that it did nothing.

Repro steps:
1. Check out the project
2. Run the `nuget.exe restore -source http://api.dev.nugettest.org/v3-index/index.json` command 
3. Observe no errors

The output is:

```
e:\dev\misc\SemVer2Test>nuget restore -source http://api.dev.nugettest.org/v3-index/index.json
MSBuild auto-detection: using msbuild version '15.3.118.39484' from 'C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin'.
```
Adding the `-verbosity detailed` argument produces the stack trace (included in `runme.cmd`):

```
e:\dev\misc\SemVer2Test>nuget restore -source http://api.dev.nugettest.org/v3-index/index.json -verbosity detailed
NuGet Version: 4.3.0.0
Restoring NuGet packages for solution e:\dev\misc\SemVer2Test\SemVer2Test.sln.
MSBuild auto-detection: using msbuild version '15.3.118.39484' from 'C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
MSBuild P2P timeout [ms]: 120000
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin\msbuild.exe /t:GenerateRestoreGraphFile /nologo /nr:false /p:RestoreUseCustomAfterTargets=true /p:BuildProjectReferences=false /v:q  /p:NuGetRestoreTargets="C:\Users\angrigor\AppData\Local\Temp\NuGet-Scratch\dwcu5qrb.02e.targets" /p:RestoreTaskAssemblyFile="C:\Users\angrigor\NuGet.exe" /p:RestoreGraphOutputPath="C:\Users\angrigor\AppData\Local\Temp\NuGet-Scratch\ourtigz0.v0e.result" /p:ExcludeRestorePackageImports=true  /p:RestoreRecursive=False  /p:RestoreProjectFilterMode=exclusionlist /p:RestoreContinueOnError=WarnAndContinue  /p:RestoreGraphProjectInput="e:\dev\misc\SemVer2Test\SemVer2Test\SemVer2Test.csproj;" "C:\Users\angrigor\AppData\Local\Temp\NuGet-Scratch\dwcu5qrb.02e.targets"
NuGet.CommandLine.CommandLineException
   at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__38.MoveNext()
System.AggregateException: One or more errors occurred. ---> NuGet.CommandLine.CommandLineException
   at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<DetermineRestoreInputsAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) NuGet.CommandLine.CommandLineException
   at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<DetermineRestoreInputsAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__30.MoveNext()<---
```

**Comment by emgarten** [comment]
This experience looks pretty awful, I'll take a look at fixing this as part of moving nuget.exe to use ``/t:restore``

**Comment by emgarten** [comment]
This is due to msbuild logging errors to the output stream instead of the error stream. Restore is currently throwing the result of the error stream in the exception message, but it is empty.
