### ISSUE TITLE
NuGet restore fails with "invalid" version string

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#5295]
With VS 2017 Update 3 Preview 1, NuGet restore is failing with a valid version string, saying it's invalid:

``` xml
  <PropertyGroup>
    <NerdbankGitVersioningVersion>2.0.3-beta-g4d80666c50</NerdbankGitVersioningVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version=" '$(NerdbankGitVersioningVersion)' " PrivateAssets="all" />
  </ItemGroup>

```
Repro here: https://github.com/Reactive-Extensions/Rx.NET/tree/d5abbe04b50136b1a83bc90eaa02ab64cddae1b8/Ix.NET/Source

Go to the Ix.Net sln and open in VS. Package Manager Output fails.

```
Error occurred while restoring NuGet packages: System.ArgumentException: '$(NerdbankGitVersioningVersion)' is not a valid version string.
   at NuGet.Versioning.VersionRange.Parse(String value, Boolean allowFloating)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.ToPackageLibraryDependency(LegacyCSProjPackageReference item)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.GetPackageSpec()
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.<>c__DisplayClass39_0`1.<<RunOnUIThread>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.<RunOnUIThread>d__39`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.<GetPackageSpecAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.<GetPackageSpecsAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<GetSolutionRestoreSpec>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<IsRestoreRequiredAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestorePackageSpecProjectsAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<ExecuteAsync>d__15.MoveNext()

```

/cc @AArnott

**Comment by clairernovotny** [comment]
If I replace the variable with a string, it appears to work:
```xml
<PackageReference Include="Nerdbank.GitVersioning" Version="2.0.3-beta-g4d80666c50" PrivateAssets="all" />
```

**Comment by AArnott** [comment]
This is not unique to 15.3 Preview 1. I've seen this for all versions of VS 2017. I _think_ I filed a bug on it months ago but I can't find it. now.

**Comment by rrelyea** [comment]
This is being tracked in the project system repo. https://github.com/dotnet/project-system/issues/2129

**Comment by davkean** [comment]
Note, only the legacy project system cannot handle variables. The new project system does not suffer from this problem.

@onovotny That PackageReference though, is invalid. It's has extraneous single quotes.

Note, on latest bits - looks like we don't get any errors or warnings: https://github.com/NuGet/Home/issues/5531.
