### ISSUE TITLE
NuGet.exe 2.8 fails to push the package, while NuGet.exe 2.7 succeeds

### ISSUE THREAD

**Issue by bhuvak** [NuGet/Home#535]
Ported from https://github.com/NuGet/NuGetGallery/issues/2447

**Comment by bhuvak** [comment]
Closing the issue as it doesn't repro. More details @ https://github.com/NuGet/NuGetGallery/issues/2447

**Comment by larsbrinkhoff** [comment]
I guess I have the same issue.  Using NuGet 2.8.6, pushing a 79 Mbyte file.  Is the file size a problem?

```
$ nuget push PortableGit.2.5.1.01.nupkg  -Verbosity detailed -Timeout 901
Pushing PortableGit 2.5.1.01 to the NuGet gallery (https://www.nuget.org)...
PUT https://www.nuget.org/api/v2/package/
System.Net.WebException: The request was aborted: The request was canceled. ---> System.IO.IOException: Cannot close stream until all bytes are written.
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   at System.Net.ConnectStream.System.Net.ICloseEx.CloseEx(CloseExState closeState)
   at System.Net.ConnectStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at NuGet.MultipartWebRequest.CreateMultipartRequest(WebRequest request)
   at NuGet.PackageServer.<>c__DisplayClass4.<PushPackageToServer>b__2(Object sender, WebRequestEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at NuGet.HttpClient.RaiseSendingRequest(WebRequest webRequest)
   at NuGet.RequestHelper.GetResponse()
   at NuGet.HttpClient.GetResponse()
   at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
   at NuGet.PackageServer.PushPackageToServer(String apiKey, Func`1 packageStreamFactory, Int64 packageSize, Int32 timeout, Boolean disableBuffering)
   at NuGet.PackageServer.PushPackage(String apiKey, IPackage package, Int64 packageSize, Int32 timeout, Boolean disableBuffering)
   at NuGet.Commands.PushCommand.PushPackageCore(String source, String apiKey, PackageServer packageServer, String packageToPush, TimeSpan timeout)
   at NuGet.Commands.PushCommand.PushPackage(String packagePath, String source, String apiKey, TimeSpan timeout)
   at NuGet.Commands.PushCommand.ExecuteCommand()
   at NuGet.Commands.Command.Execute()
   at NuGet.Program.Main(String[] args)
```

**Comment by larsbrinkhoff** [comment]
It got pushed successfully with NuGet 2.7.3.
