### ISSUE TITLE
Nuget.exe - exception when finding dependencies during pack

### ISSUE THREAD

**Issue by ttvrdon** [NuGet/Home#5406]
## Details about Problem
NuGet product used: NuGet.exe
NuGet version: 4.1.0.2450
VS version: 15.2
OS version: win10 v1511 (10586.916)

## Detailed repro steps so we can see the same problem
Used command: NuGet.exe pack example.scproj -Verbosity detailed

Example Project dependencies (packages.config):
`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Api.Client.Core" version="2.0.3" targetFramework="net461" />
</packages>
`

Api.Client.Core.nuspec:
`<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>api.client.core</id>
    <version>2.0.3</version>
  </metadata>
</package>
`

## Received error (verbose output):
Found packages.config. Using packages listed as dependencies
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NuGet.CommandLine.ProjectFactory.ProcessDependencies(PackageBuilder builder)
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)

Package's name is lower-case, but reference packages.config is Camel-case.
This difference is not an issue for build, but packing package fails.

**Comment by mishra14** [comment]
@ttvrdon can you please retry with [latest NuGet.exe](https://dist.nuget.org/win-x86-commandline/v4.4.1/nuget.exe) and let us know if you are still running into this issue?

**Comment by mishra14** [comment]
tagging @rohit21agrawal  for visibility.

**Comment by ghost** [comment]
@mishra14 using later nuget.exe fixed this particular issue for me.
