### ISSUE TITLE
ConfiguredProjectVersion has decremented error

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#5407]
End to end tests cause the following prompt in recent builds:

`
The ConfiguredProjectVersion has decremented, outside the context of an active project config change.  This is likely an error, and can lead to hangs.
`

```
=====================
6/14/2017 6:22:31 AM
Recoverable
System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.ProjectSystem.ProjectDataSources+DataSourceRegressionException: The ConfiguredProjectVersion has decremented, outside the context of an active project config change.  This is likely an error, and can lead to hangs.
   at Microsoft.VisualStudio.ProjectSystem.ProjectDataSources.CheckValidVersionProgression(IImmutableDictionary`2 oldDataSourceVersions, IImmutableDictionary`2 dataSourceVersions, Boolean unconfiguredProjectLevel)
   at Microsoft.VisualStudio.ProjectSystem.SyncLinkToLink`1.ProcessData(Boolean inline)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.VisualStudio.ProjectSystem.ProjectDataSources+DataSourceRegressionException: The ConfiguredProjectVersion has decremented, outside the context of an active project config change.  This is likely an error, and can lead to hangs.
   at Microsoft.VisualStudio.ProjectSystem.ProjectDataSources.CheckValidVersionProgression(IImmutableDictionary`2 oldDataSourceVersions, IImmutableDictionary`2 dataSourceVersions, Boolean unconfiguredProjectLevel)
   at Microsoft.VisualStudio.ProjectSystem.SyncLinkToLink`1.ProcessData(Boolean inline)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---

===================
```

**Comment by mishra14** [comment]
Working with Lifeng to improve the logging on the machine and get more details about the issue.

**Comment by rrelyea** [comment]
updated VS on the e2e test machine, and all is golden. learn from this. newer is always better.
