### ISSUE TITLE
NuGet error in VS when using paket in dotnet projects.

### ISSUE THREAD

**Issue by hvidgaard** [NuGet/Home#5536]
I'm running Windows 10 v1703 (15063.413), VS2017 15.2 (26430.6 and NuGet package manager 4.2.0.2457) and VS2017 15.3 (preview 2.1 and nuget package manager 4.3.0.4113) both get the error.

When using paket to handle dependencies, I get a NuGet error upon opening the solution. [Here](https://1drv.ms/u/s!AhhMMYIXfwvmgcNnccaWmsXp3CDIzw) is a sample solution that exhibit this error. Having a solution with more projects and more dependencies, it will be more likely to produce the error, but this consistently produce multiple errors on a few of my coworkers machines as well.

I'm unsure where exactly to report this, but I'm doing it here, since it seems the error is thrown in NuGet. Everything resolves correctly in the end, but it take quite a while for it to do so, and makes VS take a long time to resolve dependencies, which for large solutions render VS more or less unusable.

The error has the form

```
Error occurred while restoring NuGet packages: System.InvalidOperationException: The operation failed as details for project Ims.Model could not be loaded.
   at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.GetPackageSpecsAsync(DependencyGraphCacheContext context)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<GetSolutionRestoreSpec>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<IsRestoreRequiredAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestorePackageSpecProjectsAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<ExecuteAsync>d__15.MoveNext()
```

**Comment by nkolev92** [comment]
@hvidgaard Are you still hitting this issue with 15.4?
