### ISSUE TITLE
nuget restore fails when VS Test Agent is installed with a SxS SKU

### ISSUE THREAD

**Issue by blitzxion** [NuGet/Home#5840]
## Details about Problem

NuGet product used:
**nuget.exe**

NuGet version (x.x.x.xxx):
**4.3.0.4406**

dotnet.exe --version (if appropriate):
**2.0.0**

VS version (if appropriate):
**VS Test Agent 2017 15.3.3**
**VS Build Tools 2017 15.3.3**

OS version (i.e. win10 v1607 (14393.321)):
**Windows Server 2016 v1607 (14393.1593)**

Worked before? If so, with which NuGet version:
**4.3.0.4406**

## Detailed repro steps so we can see the same problem
1. Obtain copy of latest nuget.exe
2. Install VS Build Tools 2017 15.3.3
3. Verify `nuget restore` works (uses MSBuild 15.3.x)
4. Install VS Test Agent 2017 15.3.3
5. Verify `nuget restore` fails
6. Uninstall VS Build Tools 2017
7. Verify `nuget restore` works (uses MSBuild 14.x)
8. Install VS Build Tools 2017 15.3.3
9. Verify `nuget restore` fails
10. Uninstall VS Test Agent 2017
11. Verify `nuget restore` works (uses MSBuild 15.3.x)

## Other suggested things
If you supply the MSBuildVersion flag: `nuget restore -MSBuildVersion 15.3` the restore works. But then the flag becomes required.

### Verbose Logs
```cmd
> nuget restore -verbosity detailed
NuGet Version: 4.3.0.4406
Restoring NuGet packages for solution C:\projects\MyExampleProject\MyExampleProject.sln.
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.CommandLine.MsBuildUtility.<>c__DisplayClass22_0.<GetToolsetFromPath>b__0(MsBuildToolset t)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGet.CommandLine.MsBuildUtility.GetToolsetFromPath(String msBuildPath, IEnumerable`1 installedToolsets)
   at NuGet.CommandLine.MsBuildUtility.GetMsBuildDirectoryInternal(String userVersion, IConsole console, IEnumerable`1 installedToolsets, Func`1 getMsBuildPathInPathVar)
   at NuGet.CommandLine.MsBuildUtility.GetMsBuildDirectory(String userVersion, IConsole console)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at NuGet.CommandLine.RestoreCommand.ProcessSolutionFile(String solutionFileFullPath, PackageRestoreInputs restoreInputs)
   at NuGet.CommandLine.RestoreCommand.<DetermineRestoreInputsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__34.MoveNext()

>
```
### Sample Project
[Download the sample app](https://www.dropbox.com/s/161dposz9v4dm2v/WebApplication1.zip?dl=0) or just create a simple MVC Web Application in VS (or any project that happens to have a `*.sln` file. This might have something to do with it? I created a MVC app from scratch using Visual Studio on a different computer, copied it over to the server in question and attempted the nuget restore on it... it failed.

Simply, having both the VS Test Agent and the VS Build Tools installed on the same machine renders the `nuget restore` command faulty. Uninstall one or the other (preferably VS Test Agent) will allow the `nuget restore` command to run as expected. I do not have any full edition of VS installed (this is a BuildServer running TeamCity 10.x). 

It isn't favorable or entirely possible to inject the `-MSBuildVersion 15.3` value wherever I'm using `nuget restore`.

**Comment by emgarten** [comment]
This looks like a bug in the way nuget discovers msbuild.

**Comment by nkolev92** [comment]
The root cause of the issue is that we don't deal well with SKUs that don't come with MsBuild such as VS Test Agent.
15.1 is where this issue was introduced, as that's when the concept of SxS SKUs was added. 

I'll rename the issue to reflect the findings.

**Comment by nkolev92** [comment]
@blitzxion I have addressed this issue in the linked PR. 
It will come in the next release, 4.4. 

We can provide you a build so you can validate it on your side as well.

**Comment by blitzxion** [comment]
@nkolev92 Awesome! At your leisure, I would like to get that build you spoke of and test it out.
