### ISSUE TITLE
NuGet.CommandLine restore fails with "Unable to find property definition for {locale}"

### ISSUE THREAD

**Issue by pranavkm** [NuGet/Home#590]
Calling the restore command for any project seems to be broken:
```C#
System.Exception: Unable to find property definition for {locale}
   at NuGet.ContentModel.Infrastructure.PatternExpression.TokenSegment.TryMatch(ContentItem item, IReadOnlyDictionary`2
propertyDefinitions, Int32 startIndex, Int32& endIndex) in D:\work\nuget3\src\NuGet.ContentModel\Infrastructure\Parser.c
s:line 129
   at NuGet.ContentModel.Infrastructure.PatternExpression.Match(String path, IReadOnlyDictionary`2 propertyDefinitions)
in D:\work\nuget3\src\NuGet.ContentModel\Infrastructure\Parser.cs:line 56
   at NuGet.ContentModel.ContentItemCollection.<FindItemGroups>d__5.MoveNext() in D:\work\nuget3\src\NuGet.ContentModel\
ContentItemCollection.cs:line 54
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.ContentModel.ContentItemCollection.FindBestItemGroup(SelectionCriteria criteria, PatternSet[] definitions) i
n D:\work\nuget3\src\NuGet.ContentModel\ContentItemCollection.cs:line 84
   at NuGet.Commands.RestoreCommand.CreateLockFileTargetLibrary(LocalPackageInfo package, RestoreTargetGraph targetGraph
, DefaultPackagePathResolver defaultPackagePathResolver, String correctedPackageName) in D:\work\nuget3\src\NuGet.Comman
ds\RestoreCommand.cs:line 317
```

**Comment by pranavkm** [comment]
cc @anurse

**Comment by anurse** [comment]
FYI, @yishaigalatzer This is a 3.0.0-rtm issue, not a commandline issue. The same exception would be thrown in VS.
