### ISSUE TITLE
FatalProtocolException during restore

### ISSUE THREAD

**Issue by shishirx34** [NuGet/Home#6023]
This morning there was an incident created on VSTS with the following exception. 

It seems that the client failed to download the package - `Humanizer.Core.zh-CN.2.2.0`

The package is available in the NuGet.org v3 feed: `https://api.nuget.org/v3-flatcontainer/humanizer.core.zh-cn/2.0.0/humanizer.core.zh-cn.2.0.0.nupkg`
And is not available in the vsts feed: `https://swissre.pkgs.visualstudio.com/_packaging/xxxxx/nuget/v3/flat2/humanizer.core.zh-cn/index.json`
But I'd assume the client should handle such 404s graciously?

Note this was an intermittent exception and went away afterwards. During the same time there were some 504(Gateway timeout) issues due to CDN connectivity problems likely. 

This leads me to believe, not sure correct me if I am wrong, that the client failed to download the package due to gateway timeout problem which led to the exception below?

Questions:
- Is that assumption right? If so, shouldn't the client handle/catch such exceptions and show 504 error in the output logs?
- if not, what could be the possible reason for the exception below?

```
The feed 'NuGetOrg [The feed 'NuGetOrg [https://api.nuget.org/v3/index.json]' lists package 'Humanizer.Core.zh-CN.2.2.0' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again.
2017-10-12T12:32:00.3344246Z   Unable to find package 'Humanizer.Core.zh-CN.2.2.0'.
2017-10-12T12:32:00.5290346Z   NotFoundhttps://swissre.pkgs.visualstudio.com/_packaging/xxxxx/nuget/v3/flat2/humanizer.core.zh-cn/index.json 202ms
2017-10-12T12:32:00.5595847Z   GEThttps://api.nuget.org/v3-flatcontainer/system.spatial/5.8.2/system.spatial.5.8.2.nupkg
2017-10-12T12:32:00.5605758Z   GEThttps://api.nuget.org/v3-flatcontainer/microsoft.data.edm/5.8.2/microsoft.data.edm.5.8.2.nupkg
2017-10-12T12:32:00.5665737Z   OKhttps://api.nuget.org/v3-flatcontainer/system.spatial/5.8.2/system.spatial.5.8.2.nupkg 6ms
2017-10-12T12:32:00.5745743Z   OKhttps://api.nuget.org/v3-flatcontainer/microsoft.data.edm/5.8.2/microsoft.data.edm.5.8.2.nupkg 11ms
2017-10-12T12:32:00.6155721Z   OKhttps://api.nuget.org/v3-flatcontainer/humanizer.core.zh-cn/index.json 435ms
2017-10-12T12:32:00.6175736Z   CACHEhttps://api.nuget.org/v3-flatcontainer/humanizer.core.zh-cn/index.json
2017-10-12T12:32:00.6185733Z   GEThttps://swissre.pkgs.visualstudio.com/_packaging/xxxxx/nuget/v3/flat2/humanizer.core.zh-cn/index.json
2017-10-12T12:32:00.6185733Z   CACHEhttps://api.nuget.org/v3-flatcontainer/humanizer.core.zh-cn/index.json
2017-10-12T12:32:00.6745732Z   NotFoundhttps://swissre.pkgs.visualstudio.com/_packaging/xxxxxx/nuget/v3/flat2/humanizer.core.zh-cn/index.json 56ms
2017-10-12T12:32:00.7218777Z NuGet.Protocol.Core.Types.FatalProtocolException: The feed 'NuGetOrg [https://api.nuget.org/v3/index.json]' lists package 'Humanizer.Core.zh-CN.2.2.0' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again. ---> NuGet.Protocol.PackageNotFoundProtocolException: Unable to find package 'Humanizer.Core.zh-CN.2.2.0'.
2017-10-12T12:32:00.7218777Z    at NuGet.Protocol.FindPackagesByIdNupkgDownloader.<GetNuspecReaderFromNupkgAsync>d__6.MoveNext()
2017-10-12T12:32:00.7218777Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7218777Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7218777Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7218777Z    at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResource.<GetDependencyInfoAsync>d__7.MoveNext()
2017-10-12T12:32:00.7218777Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7218777Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7218777Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7228783Z    at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesCoreAsync>d__19.MoveNext()
2017-10-12T12:32:00.7228783Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7228783Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7228783Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7228783Z    at NuGet.Commands.SourceRepositoryDependencyProvider.<>c__DisplayClass18_0.<<GetDependenciesAsync>b__0>d.MoveNext()
2017-10-12T12:32:00.7228783Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7228783Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7228783Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7228783Z    at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesAsync>d__18.MoveNext()
2017-10-12T12:32:00.7228783Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7228783Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7228783Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7228783Z    at NuGet.DependencyResolver.ResolverUtility.<CreateGraphItemAsync>d__2.MoveNext()
2017-10-12T12:32:00.7228783Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7228783Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7228783Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7228783Z    at NuGet.DependencyResolver.ResolverUtility.<FindLibraryEntryAsync>d__1.MoveNext()
2017-10-12T12:32:00.7228783Z    --- End of inner exception stack trace ---
2017-10-12T12:32:00.7228783Z    at NuGet.DependencyResolver.ResolverUtility.<FindLibraryEntryAsync>d__1.MoveNext()
2017-10-12T12:32:00.7228783Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7228783Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7228783Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7228783Z    at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
2017-10-12T12:32:00.7228783Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7228783Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7228783Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7228783Z    at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
2017-10-12T12:32:00.7228783Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7238778Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7238778Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7238778Z    at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
2017-10-12T12:32:00.7238778Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7238778Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7238778Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7238778Z    at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
2017-10-12T12:32:00.7238778Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7238778Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7238778Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7238778Z    at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
2017-10-12T12:32:00.7238778Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7238778Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7238778Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7238778Z    at NuGet.Commands.ProjectRestoreCommand.<WalkDependenciesAsync>d__5.MoveNext()
2017-10-12T12:32:00.7238778Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7238778Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7238778Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7238778Z    at NuGet.Commands.ProjectRestoreCommand.<TryRestore>d__3.MoveNext()
2017-10-12T12:32:00.7238778Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7238778Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7238778Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7238778Z    at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d__19.MoveNext()
2017-10-12T12:32:00.7238778Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7238778Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7238778Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7248821Z    at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__8.MoveNext()
2017-10-12T12:32:00.7248821Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7248821Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7248821Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7248821Z    at NuGet.Commands.RestoreRunner.<ExecuteAsync>d__7.MoveNext()
2017-10-12T12:32:00.7248821Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7248821Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7248821Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7248821Z    at NuGet.Commands.RestoreRunner.<ExecuteAndCommitAsync>d__6.MoveNext()
2017-10-12T12:32:00.7248821Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7248821Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7248821Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7248821Z    at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__9.MoveNext()
2017-10-12T12:32:00.7248821Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7248821Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7248821Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7248821Z    at NuGet.Commands.RestoreRunner.<RunAsync>d__2.MoveNext()
2017-10-12T12:32:00.7248821Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7248821Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7248821Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7248821Z    at NuGet.Commands.RestoreRunner.<RunAsync>d__0.MoveNext()
2017-10-12T12:32:00.7248821Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7248821Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7248821Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7248821Z    at NuGet.Commands.RestoreRunner.<RunAsync>d__1.MoveNext()
2017-10-12T12:32:00.7248821Z --- End of stack trace from previous location where exception was thrown ---
2017-10-12T12:32:00.7248821Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-10-12T12:32:00.7248821Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-10-12T12:32:00.7248821Z    at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__34.MoveNext()
2017-10-12T12:32:00.8489896Z ##[error]Error: d:\a\_tool\NuGet\4.3.0\x64\nuget.exe failed with return code: 1
2017-10-12T12:32:00.8489896Z ##[error]Packages failed to restore
2017-10-12T12:32:00.8559874Z ##[section]Finishing: Restore Platform NuGet Packages

```

**Comment by emgarten** [comment]
Related: https://github.com/NuGet/Home/issues/6039
