### ISSUE TITLE
new PackageArchiveReader(string) does not release file handle of invalid .nupkg

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#6028]
```csharp
var path = Path.GetFullPath("a.nupkg");
File.WriteAllText(path, "bad!");
/*
File.Copy(
    Environment.GetEnvironmentVariable("userprofile") +
    @"\.nuget\packages\newtonsoft.json\9.0.1\newtonsoft.json.9.0.1.nupkg",
    path,
    overwrite: true);
*/

try
{
    using (var reader = new PackageArchiveReader(path))
    {
        Console.WriteLine(reader.NuspecReader.GetIdentity());
    }
}
catch
{
    Console.WriteLine("Invalid .nupkg :(");
}

File.Delete(path);
```

Exception thrown:

```
Invalid .nupkg :(

Unhandled Exception: System.IO.IOException: The process cannot access the file 'C:\Users\jver\Desktop\ConsoleApp1\ConsoleApp2\a.nupkg' because it is being used by another process.
   at System.IO.Win32FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\jver\Desktop\ConsoleApp1\ConsoleApp2\Program.cs:line 33
```

Tried on NuGet.Packaging 4.4.0.

**Comment by joelverhagen** [comment]
Workaround is opening the file yourself and passing the stream to `PackageArchiveReader`.
