### ISSUE TITLE
Microsoft and .NET feed cannot be unchecked/disabled

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#612]
Repro steps:
1. start package manager settings dialog
2. uncheck Microsoft and .NET feed, click OK button
3. go back to package manager settings dialog again and check

Expected: Microsoft and .net feed is unchecked

Actual: it's still checked.

While debugging, found that below is exception is thrown for Microsoft and .net feed, which will keep its state being updated correctly.

>	NuGet.PackageManagement.VisualStudio.dll!NuGet.PackageManagement.VisualStudio.PathValidator.IsValidUncPath(string path) Line 73	C#
 	NuGet.Options.dll!NuGet.Options.PackageSourcesOptionsControl.TryUpdateSource() Line 336	C#
 	NuGet.Options.dll!NuGet.Options.PackageSourcesOptionsControl.ApplyChangedSettings() Line 211	C#
 	NuGet.Options.dll!NuGet.Options.PackageSourceOptionsPage.OnApply(Microsoft.VisualStudio.Shell.DialogPage.PageApplyEventArgs e) Line 34	C#
 

System.NotSupportedException occurred
  HResult=-2146233067
  Message=The given path's format is not supported.
  Source=mscorlib
  StackTrace:
       at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
       at System.IO.Path.GetFullPath(String path)
       at NuGet.PackageManagement.VisualStudio.PathValidator.IsValidUncPath(String path) in F:\dd\git\src\Home\NuGet.VisualStudioExtension\src\PackageManagement.VisualStudio\Utility\PathValidator.cs:line 73
  InnerException:

**Comment by danliu** [comment]
duplicate of https://github.com/NuGet/Home/issues/662. Looks like Zhi already have a fix.
