### ISSUE TITLE
VersionRange.TryParse should not throw when provided with null

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#6247]
```csharp
using System;
using System.Net;
using NuGet.Versioning;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // value types
            Console.WriteLine(bool.TryParse(null, out var boolean) + " " + boolean);
            Console.WriteLine(int.TryParse(null, out var number) + " " + number);
            Console.WriteLine(Guid.TryParse(null, out var guid) + " " + guid);
            Console.WriteLine(Enum.TryParse<HttpStatusCode>(null, out var statusCode) + " " + statusCode);
            Console.WriteLine(DateTime.TryParse(null, out var dateTime) + " " + dateTime);
            Console.WriteLine(DateTimeOffset.TryParse(null, out var dateTimeOffset) + " " + dateTimeOffset);

            // reference types
            Console.WriteLine(IPAddress.TryParse(null, out var ip) + " " + ip);
            Console.WriteLine(NuGetVersion.TryParse(null, out var version) + " " + version);
            Console.WriteLine(VersionRange.TryParse(null, out var versionRange) + " " + versionRange);
        }
    }
}
```

**Expected:** The method should return `false` and set the `out` parameter to `null`.
**Actual:**
```
False False
False 0
False 00000000-0000-0000-0000-000000000000
False 0
False 1/1/0001 12:00:00 AM
False 1/1/0001 12:00:00 AM +00:00
False
False

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at NuGet.Versioning.VersionRange.TryParse(String value, Boolean allowFloating, VersionRange& versionRange)
   at NuGet.Versioning.VersionRange.TryParse(String value, VersionRange& versionRange)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\joelv\Desktop\ConsoleApp1\ConsoleApp1\Program.cs:line 22
```

**Comment by jainaashish** [comment]
I understand the consistency but is there any other failure or something because of this gap? Will help us understand the priority.

**Comment by joelverhagen** [comment]
I am building some custom tools around NuGet and ran into this issue when parsing .nuspecs on my own. 

`XElement.Attribute` returns null when an attribute does not exist, i.e. if the `version` attribute on a dependency is not found. I ran into this because I was passing this `XAttribute?.Value` to the parse method.

Easy to work around but feels clunky for a Try method.
