### ISSUE TITLE
Running `dotnet restore --verbosity` (verbosity w/o value) throws an exception

### ISSUE THREAD

**Issue by evil-shrike** [NuGet/Home#6248]
Running `dotnet restore --verbosity` crashes with `ArgumentOutOfRangeException`.
Yes, `--verbosity` should have a value, but nuget should not throw.
I'd expect something like 'verbosity value missing (q,m,d)' message.

```
 ---> Running in c970969c266e
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.LogVerbosityForAllTopLevelCommand(ICollection`1 result, ParseResult parseResult, String topLevelCommandName)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
   at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
The command '/bin/sh -c dotnet restore --verbosity' returned a non-zero code: 1
```

**Comment by jainaashish** [comment]
It's inside dotnet cli and not NuGet. moving there - https://github.com/dotnet/cli/issues/8160
