### ISSUE TITLE
T4/TT file in a nuget package seems to be executed early

### ISSUE THREAD

**Issue by StingyJack** [NuGet/Home#6283]
NuGet product used: VS UI

NuGet version (x.x.x.xxx): whatever is in VS 2017

OS version (i.e. win10 v1607 (14393.321)): doesnt matter

Worked before? If so, with which NuGet version:
no idea

--------

I have a nuget package that includes a reference dll as well as a TT file and a .config file used by the TT. When I install the package, the I get an error about the config file not being found. 

When I look in the project, both content files appear to have been copied properly and the file exists. I think the error is happening because its executing the TT file before its finished copying the config file over. 

I would expect that any execution would be suppressed until the files are all copied, or suppressed entirely (in line with dropping support for install.ps1 - which i still maintain is a mistake).

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: System.IO.FileNotFoundException: Unable to locate file
File name: 'c:\tfs\projectName\CodeGen\SpecificCodeGen.config'

Server stack trace: 
   at Microsoft.VisualStudio.TextTemplating.VSHost.TextTemplatingService.ResolvePath(String path)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost.ResolvePath(String path)
   at Microsoft.VisualStudio.TextTemplating3B317D4AEDB728312E56C2201599D216A4334494666708257BAE9FE50639856A8CE7B9F4C656A97B41DE88144E1FF0DD5AFB07E75452561577CA4265BFB72E3B.GeneratedTextTransformation.TransformText()	projectName	c:\tfs\projectName\CodeGen\SpecificCodeGen.tt	1	
```

**Comment by jainaashish** [comment]
Are you using `packages.config` or `PackageReference` format to manage NuGet dependencies? And do you have any sample repro which depict this issue?

**Comment by StingyJack** [comment]
i wont touch packagereferences. they cost me  several days when they were the default, and left me with broken proj files.

**Comment by StingyJack** [comment]
is nuget going to trigger ivssinglefilegenerator before the entire package is installed?

**Comment by jainaashish** [comment]
NuGet doesn't trigger it, rather project system triggers it as part of design time build and it should happens after the package is installed. That's why I asked if you've any sample repro so that I can see what's going wrong in your case.

**Comment by StingyJack** [comment]
I'll try to post it when I get back into the office on Monday. Its an intermittent thing though, i think. It wasnt until I started adding the config transforms that the package started behaving like that.

**Comment by StingyJack** [comment]
@jainaashish - quite the different Monday in December than originally planned, but here is the repro as promised. https://github.com/StingyJack/nuget6283
