### ISSUE TITLE
Pack is looking for nupkg in wrong location

### ISSUE THREAD

**Issue by bronumski** [NuGet/Home#6300]
Possibly related to:
https://github.com/NuGet/Home/issues/5316
https://github.com/NuGet/Home/issues/3198
https://github.com/NuGet/Home/issues/3378

## Details about Problem
Had an existing project that packs up several packages via Fake and NuGet 2.8.
https://github.com/bronumski/HealthNet/tree/release/1.1.0.50

Project structure:
```
<root>
| - packages
| - src
|   |- (sln and projects)
|   |- nuget.config (repositorypath = ..\packages)
| - tools
|   | - nuget
| - (build and packaging scripts (Fake))
```
This had been working fine however I am attempting to add a dotnet core project and package that up. Because of this I have had to upgrade the embedded NuGet.exe in order to support the restores. Now when I package up the projects I get an error indicating that it cannot find the dependency package. 

The point to note here is that the dependent nuget package is being looked up in `<root>\packages\<package>\<version>\<package>.<version>.nupkg` not `<root>\packages\<package>.<version>\<package>.<version>.nupkg` which is what it used to do previously.

```
c:\Dev\HealthNet\src>..\tools\nuget\NuGet.exe pack -Version 1.1.0.0 -OutputDirectory "c:\Dev\HealthNet\bin" "c:\Dev\HealthNet\src\HealthNet.Core\HealthNet.Core.csproj" -IncludeReferencedProjects -Verbosity detailed -Properties configuration="release"
NuGet Version: 4.4.1.4656
Attempting to build package from 'HealthNet.Core.csproj'.
MSBuild auto-detection: using msbuild version '15.5.180.51428' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from 'c:\Dev\HealthNet\src\HealthNet.Core\bin\Release'.
Using 'HealthNet.Core.nuspec' for metadata.
Add file 'c:\Dev\HealthNet\src\HealthNet.Core\bin\Release\HealthNet.Core.dll' to package as 'lib\net45\HealthNet.Core.dll'
Found packages.config. Using packages listed as dependencies
Missing c:\Dev\HealthNet\packages\newtonsoft.json\7.0.1\newtonsoft.json.7.0.1.nupkg
Unable to find 'Newtonsoft.Json.7.0.1.nupkg'. Make sure the project has been built.
NuGet.CommandLine.CommandLineException: Unable to find 'Newtonsoft.Json.7.0.1.nupkg'. Make sure the project has been built.
   at NuGet.CommandLine.ProjectFactory.AddDependencies(Dictionary`2 packagesAndDependencies)
   at NuGet.CommandLine.ProjectFactory.RecursivelyApply(Action`1 action, Object alreadyAppliedProjects)
   at NuGet.CommandLine.ProjectFactory.RecursivelyApply(Action`1 action)
   at NuGet.CommandLine.ProjectFactory.ProcessDependencies(PackageBuilder builder)
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```
Prior to this it would produce the following:
```
c:\Dev\HealthNet\src>..\tools\nuget\NuGet.old.exe pack -Version 1.1.0.0 -OutputDirectory "c:\Dev\HealthNet\bin" "c:\Dev\HealthNet\src\HealthNet.Core\HealthNet.Core.csproj" -IncludeReferencedProjects -Verbosity detailed -Properties configuration="release"
Attempting to build package from 'HealthNet.Core.csproj'.
Packing files from 'c:\Dev\HealthNet\src\HealthNet.Core\bin\Release'.
Using 'HealthNet.Core.nuspec' for metadata.
Add file 'c:\Dev\HealthNet\src\HealthNet.Core\bin\Release\HealthNet.Core.dll' to package as 'lib\net45\HealthNet.Core.dll'
Found packages.config. Using packages listed as dependencies

Id: HealthNet.Core
Version: 1.1.0.0
Authors: bronumski
Description: Foo
License Url: https://github.com/bronumski/HealthNet/blob/master/LICENSE
Project Url: https://github.com/bronumski/HealthNet
Dependencies: Newtonsoft.Json (= 7.0.1)

Added file 'lib\net45\HealthNet.Core.dll'.

Successfully created package 'c:\Dev\HealthNet\bin\HealthNet.Core.1.1.0.0.nupkg'.
```
Given two major versions have been released since version 2.8.x do I need to change the way that I am using nuget within my project?

**Comment by bronumski** [comment]
i am happy to close this down, it is no longer relevant to anything I am working on.
