### ISSUE TITLE
Missing method exception for local repository

### ISSUE THREAD

**Issue by seesharper** [NuGet/Home#6372]
I am having trouble trying to use the SDK to search for local packages.

A simple console app shows the problem

```
        static void Main(string[] args)
        {            
            var root = Environment.CurrentDirectory;            
            var sourceRepositoryProvider = new SourceRepositoryProvider(Settings.LoadDefaultSettings(root), Repository.Provider.GetCoreV3());
                                   
            var repos = sourceRepositoryProvider.GetRepositories().ToArray();
            var localRepo = repos[1];

            var searchResource = localRepo.GetResource<PackageSearchResource>();

            var result = searchResource.SearchAsync("SomePackage", new SearchFilter(false), 0, 20, new Logger(), CancellationToken.None).Result;
            Console.WriteLine(result.Count());
        }  
```

This causes the following exception.

```
Method not found: 'NuGet.Packaging.Core.PackageIdentity NuGet.Packaging.Core.NuspecCoreReaderBase.GetIdentity()'.
```

Stack trace

```
   at NuGet.Protocol.LocalFolderUtility.GetPackageFromNupkg(FileInfo nupkgFile)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at NuGet.Protocol.LocalFolderUtility.<GetDistinctPackages>d__27.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at NuGet.Protocol.LocalPackageSearchResource.<CollapseToHighestVersion>d__8.MoveNext()
   at System.Linq.Enumerable.EnumerablePartition`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NuGet.Protocol.LocalPackageSearchResource.<>c__DisplayClass2_0.<SearchAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.LocalPackageSearchResource.<SearchAsync>d__2.MoveNext()
```

The csproj file containing package references

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
      <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="NuGet.Configuration" Version="4.5.0" />
      <PackageReference Include="NuGet.Packaging.Core.Types" Version="4.2.0" />
      <PackageReference Include="NuGet.Protocol.Core.v3" Version="4.2.0" />
      <PackageReference Include="NuGet.Packaging" Version="4.5.0" />
      <PackageReference Include="NuGet.Packaging.Core" Version="4.5.0" />
  </ItemGroup>

</Project>

```
 Am I missing any packages or did I mix up the wrong ones?

**Comment by seesharper** [comment]
Downgrading seems to work though

```
 <PackageReference Include="NuGet.Configuration" Version="4.5.0" />
 <PackageReference Include="NuGet.Packaging.Core.Types" Version="4.2.0" />
 <PackageReference Include="NuGet.Protocol.Core.v3" Version="4.2.0" />
 <PackageReference Include="NuGet.Packaging" Version="4.2.0" />
 <PackageReference Include="NuGet.Packaging.Core" Version="4.2.0" />
```

**Comment by emgarten** [comment]
@seesharper all NuGet.* packages need to be same version. Reference only NuGet.Protocol to bring in the rest of these using the correct version.

`<PackageReference Include="NuGet.Protocol" Version="4.5.0" />`
