### ISSUE TITLE
end to end tests are failing post the ngen change

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#6443]
For eg, build #9273 failed with :

``` 
2018-01-16T21:13:06.3846842Z Starting functional tests with command 'Run-Test -Exclude Silverlight.ps1 -Verbose *>&1 | Tee-Object E:\A\_work\2\s\artifacts\EndToEnd\FullLog_9273.txt'
2018-01-16T21:23:12.4863535Z RunFunctionalTests.ps1 threw an exception:  System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
2018-01-16T21:23:12.4865097Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2018-01-16T21:23:12.4866583Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2018-01-16T21:23:12.4867528Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-01-16T21:23:12.4868533Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-01-16T21:23:12.4869498Z    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2018-01-16T21:23:12.4870434Z    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2018-01-16T21:23:12.4871384Z    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2018-01-16T21:23:12.4872265Z    at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2018-01-16T21:23:12.4873116Z    at System.Management.Automation.CommandProcessorBase.Complete()
```

**Comment by jainaashish** [comment]
reverted the ngen change for now to fix these e2e or probably apex tests.
