### ISSUE TITLE
[Test Failure][Signing] The error doesn’t make sense when timestamp signing certificate does not satisfy certificate requirements

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#6451]
## Details about Problem
NuGet Version: Release-4.6.0-RTM 4825
VS Version: D15.6 27316.00
OS Version: RS3_Release 16299.15.170928-1534

## Detailed repro steps so we can see the same problem
1.	Create a new package.
2.	Create a new test certificate:  .\CreateTestCertificate.ps1 –AddAsTrustedRootAuthority.
3.	Sign the package:  NuGet.exe sign “PackageFilePath” -CertificatePath “PfxFilePath” -Timestamper http://freetsa.org/tsr.

## Expected Result:
Package signing should failed with an error saying "The timestamp service's certificate chain could not be built for the following certificate." 
## Actual Result:
Package signing failed with an error saying “Object reference not set to an instance of an object.” as below screenshot. This doesn’t make sense.
![inappropriateerror](https://user-images.githubusercontent.com/20632625/35079553-3acc79ee-fc00-11e7-9bef-e21725fac7ba.png)

**Comment by dtivel** [comment]
This appears to be a regression from @mishra14's PR [1934](https://github.com/NuGet/NuGet.Client/pull/1934/files#diff-0300598d24985bef7a3aaca743788176R181).

The first exception is a `TimestampException`.

```
Message:  The timestamp response is invalid.  Nonces did not match.
   at NuGet.Packaging.Signing.Rfc3161TimestampProvider.ValidateTimestampResponse(Byte[] nonce, Byte[] data, Rfc3161TimestampToken timestampToken) in C:\git\NuGet.Client\src\NuGet.Core\NuGet.Packaging\Signing\Timestamp\Rfc3161TimestampProvider.cs:line 184
   at NuGet.Packaging.Signing.Rfc3161TimestampProvider.TimestampData(TimestampRequest request, ILogger logger, CancellationToken token) in C:\git\NuGet.Client\src\NuGet.Core\NuGet.Packaging\Signing\Timestamp\Rfc3161TimestampProvider.cs:line 99
   at NuGet.Packaging.Signing.Rfc3161TimestampProvider.TimestampSignatureAsync(TimestampRequest request, ILogger logger, CancellationToken token) in C:\git\NuGet.Client\src\NuGet.Core\NuGet.Packaging\Signing\Timestamp\Rfc3161TimestampProvider.cs:line 56
   at NuGet.Packaging.Signing.X509SignatureProvider.TimestampSignature(SignPackageRequest request, ILogger logger, Signature signature, CancellationToken token) in C:\git\NuGet.Client\src\NuGet.Core\NuGet.Packaging\Signing\Authoring\X509SignatureProvider.cs:line 154
   at NuGet.Packaging.Signing.X509SignatureProvider.CreateSignatureAsync(SignPackageRequest request, SignatureContent signatureContent, ILogger logger, CancellationToken token) in C:\git\NuGet.Client\src\NuGet.Core\NuGet.Packaging\Signing\Authoring\X509SignatureProvider.cs:line 64
   at NuGet.Packaging.Signing.Signer.<SignAsync>d__4.MoveNext() in C:\git\NuGet.Client\src\NuGet.Core\NuGet.Packaging\Signing\Authoring\Signer.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.Commands.SignCommandRunner.<AddSignatureAndUpdatePackageAsync>d__4.MoveNext() in C:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\SignCommand\SignCommandRunner.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.Commands.SignCommandRunner.<SignPackageAsync>d__3.MoveNext() in C:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\SignCommand\SignCommandRunner.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Commands.SignCommandRunner.<ExecuteCommandAsync>d__1.MoveNext() in C:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\SignCommand\SignCommandRunner.cs:line 98
```

This exception bubbles up and subsequently causes a `NullReferenceException` exception because [`logMessage`](https://github.com/NuGet/NuGet.Client/blob/ecdf6fc5339ef19987449d84f3b09427df91bb62/src/NuGet.Core/NuGet.Common/ExceptionUtilities.cs#L40) is `null`:

```
   at NuGet.CommandLine.Console.Log(ILogMessage message) in C:\git\NuGet.Client\src\NuGet.Clients\NuGet.CommandLine\Common\Console.cs:line 386
```
