### ISSUE TITLE
Timestamping with Safe Creative TSA errors with null reference exception

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#6463]
Try signing with this TSA:
http://tsa.safecreative.org/

Options: `-timestamper http://tsa.safecreative.org -verbosity detailed`
Version: 4.7.0-preview1-4823

Output:
```
Signing package(s) with certificate:
Subject Name: CN=NUGET_DO_NOT_TRUST.leaf-1.test.test, OU=Test Organizational Unit Name, O=Test Organization Name, L=Redmond, S=WA, C=US
SHA1 hash: F507C424A6FCE6B4EB060546D41F049511289BD8
Issued by: CN=NUGET_DO_NOT_TRUST.intermediate.test.test, OU=Test Organizational Unit Name, O=Test Organization Name, L=Redmond, S=WA, C=US
Valid from: 1/3/2018 9:00:29 AM to 1/3/2028 9:00:29 AM

Timestamping package(s) with:
http://tsa.safecreative.org
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.CommandLine.Console.Log(ILogMessage message)
   at NuGet.Common.ExceptionUtilities.LogException(Exception ex, ILogger logger, Boolean logStackAsError)
   at NuGet.Commands.SignCommandRunner.<ExecuteCommandAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.SignCommandRunner.<ExecuteCommandAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.SignCommand.<ExecuteCommandAsync>d__45.MoveNext()
```

**Comment by joelverhagen** [comment]
Same with:
http://zeitstempel.dfn.de
http://timestamp.globalsign.com/scripts/timstamp.dll

**Comment by dtivel** [comment]
Looks like a dupe of https://github.com/NuGet/Home/issues/6451, which was fixed by https://github.com/NuGet/NuGet.Client/pull/1958.

Try the latest dev branch build.

**Comment by joelverhagen** [comment]
Thanks!
