### ISSUE TITLE
problem with install packages visual studio 2017

### ISSUE THREAD

**Issue by AlexeyShirshov** [NuGet/Home#6471]
I'm trying to install new package and get an error "URI formats are not supported". Here is package manager log (I use visual studio 2017 version 15.5.2):
Attempting to gather dependency information for package 'jQuery.3.2.1' with respect to project 'tengri-online-book', targeting '.NETFramework,Version=v4.5.1'
Gathering dependency information took 286,18 ms
Attempting to resolve dependencies for package 'jQuery.3.2.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'jQuery.3.2.1'
Resolved actions to install package 'jQuery.3.2.1'
Retrieving package 'jQuery 3.2.1' from 'nuget.org'.
Adding package 'jQuery.3.2.1' to folder 'F:\projects\tengri\sources\kx-web-tengri\packages'
Added package 'jQuery.3.2.1' to folder 'F:\projects\tengri\sources\kx-web-tengri\packages'
Overwriting existing file 'Scripts\jquery-3.2.1.slim.min.map'..
Install failed. Rolling back...
Package 'jQuery.3.2.1' does not exist in project 'tengri-online-book'
Removing package 'jQuery.3.2.1' from folder 'F:\projects\tengri\sources\kx-web-tengri\packages'
Removed package 'jQuery.3.2.1' from folder 'F:\projects\tengri\sources\kx-web-tengri\packages'
Executing nuget actions took 4,14 sec
System.ArgumentException: URI formats are not supported.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at NuGet.ProjectManagement.FileSystemUtility.AddFileCore(String root, String path, Action`1 writeToStream, INuGetProjectContext nuGetProjectContext)
   at NuGet.ProjectManagement.FileSystemUtility.AddFile(String root, String path, Stream stream, INuGetProjectContext nuGetProjectContext)
   at NuGet.PackageManagement.VisualStudio.VsMSBuildProjectSystem.<>c__DisplayClass29_0.<AddFile>b__1()
   at NuGet.PackageManagement.VisualStudio.VsMSBuildProjectSystem.AddFileCoreAsync(String path, Action addFile)
   at NuGet.PackageManagement.VisualStudio.VsMSBuildProjectSystem.<>c__DisplayClass29_0.<<AddFile>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.PackageManagement.VisualStudio.VsMSBuildProjectSystem.AddFile(String path, Stream stream)
   at NuGet.ProjectManagement.MSBuildNuGetProjectSystemUtility.<TryAddFileAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.ProjectManagement.MSBuildNuGetProjectSystemUtility.<AddFilesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.ProjectManagement.MSBuildNuGetProject.<InstallPackageAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteInstallAsync>d__83.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<>c__DisplayClass7_0.<<PerformActionImplAsync>b__0>d.MoveNext()
Time Elapsed: 00:00:04.6500166
========== Finished ==========

I have packages.config file in project and a lot of packages in it, but they does not apprear under installed packages tab. Get-Package cmd outputs "No packages installed."

But I'm able successfully install and upgrade packages if I open the solution in VS2015.

**Comment by jainaashish** [comment]
`Overwriting existing file 'Scripts\jquery-3.2.1.slim.min.map'..`
This line suggests that there were some Jquery files already exists in the project without having the package installed. It seems project is already in a bad state where some packages partially exists. Did you manually change anything with this project? What happens when you just create a new project in VS 2017 and try installing those packages? And last, Can you share a sample repro of the issue?

**Comment by nkolev92** [comment]
Thank you for reporting this issue.
We prioritize investigations based on community engagement such as comments and up-votes. 
We might not be able to investigate further in the foreseeable future.
