### ISSUE TITLE
nuget pack IncludeReferencedProjects does not work with projects that reference multiple Platforms

### ISSUE THREAD

**Issue by stryder199** [NuGet/Home#6485]
I have the following project layout:

ProjA - x64
ProjB - AnyCPU

ProjA references ProjB
Both have nuspec files.

If I run:
nuget.exe pack .\ProjA\ProjA.csproj -Prop Configuration=Release -Prop Platform=x64 -IncludeReferencedProjects -Symbols -Verbosity detailed

I get output:

```
NuGet Version: 4.5.0.4696
Attempting to build package from 'ProjA.csproj'.
MSBuild auto-detection: using msbuild version '15.5.180.51428' from 'X:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from '{{SLNROOT}}\ProjA\bin\x64\Release'.
Using 'ProjA.nuspec' for metadata.
Add file '{{SLNROOT}}\ProjA\bin\x64\Release\ProjA.dll' to package as 'lib\net461\ProjA.dll'
Error occurred when processing file '{{SLNROOT}}\ProjB\ProjB.csproj': Unable to find '{{SLNROOT}}\ProjB\bin\x64\Release\ProjB.dll'. Make sure the project has been built.
  Unable to find '{{SLNROOT}}\ProjB\bin\x64\Release\ProjB.dll'. Make sure the project has been built.
NuGet.CommandLine.CommandLineException: Error occurred when processing file '{{SLNROOT}}\ProjB\ProjB.csproj': Unable to find '{{SLNROOT}}\ProjB\bin\x64\Release\ProjB.dll'. Make sure the project has been built. ---> NuGet.CommandLine.CommandLineException: Unable to find '{{SLNROOT}}\ProjB\bin\x64\Release\ProjB.dll'. Make sure the project has been built.
   at NuGet.CommandLine.ProjectFactory.BuildProject()
   at NuGet.CommandLine.ProjectFactory.CreateDependencyFromProject(Object project, Dictionary`2 dependencies)
   --- End of inner exception stack trace ---
   at NuGet.CommandLine.ProjectFactory.CreateDependencyFromProject(Object project, Dictionary`2 dependencies)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NuGet.CommandLine.ProjectFactory.AddProjectReferenceDependencies(Dictionary`2 dependencies)
   at NuGet.CommandLine.ProjectFactory.ProcessDependencies(PackageBuilder builder)
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

######
Expected
ProjB gets ignored since a nuspec file exists for the project, meaning this dependency will be added as a nuget dependency to this package and will get resolved later.

######
Actual
Attempts to inspect ProjB's dlls, at a path it would never build to. Even if the dll's were there, it would resolve them as a nuget reference and not include them in this nuget package anyways.

NuGet Version: 4.5.0.4696

Sample VS project
[NugetTest.zip](https://github.com/NuGet/Home/files/1662376/NugetTest.zip)

**Comment by mishra14** [comment]
@rohit21agrawal any thoughts?

**Comment by mcblair** [comment]
This is a very real issue. 

Do you have a workaround @mishra14

**Comment by xJom** [comment]
I have somewhat the same issue.

If projB is built to an OutputPath that is [path to projB]\$(Configuration)\bin
and projA is built to an OutputPath that is [path to projA]\$(Configuration)\Plugins\Diagnostics
nuget pack will search for projB in [path to projB]\$(Configuration)\Plugins\Diagnostics.

Now projB.dll exists in both [path to projB]\$(Configuration)\bin and in [path to projA]\$(Configuration)\Plugins\Diagnostics,
but NOT in [path to projB]\$(Configuration)\Plugins\Diagnostics.

`NuGet Version: 5.8.0.6930
Attempting to build package from 'projA.csproj'.
MSBuild auto-detection: using msbuild version '16.8.2.56705' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from 'C:\Git\projA\Debug Local\Plugins\Diagnostics'.
Add file 'C:\Git\projB\Debug Local\Plugins\Diagnostics\projB.dll' to package as 'lib\netstandard2.0\projB.dll'
Error NU5012: Unable to find 'C:\Git\projA\Debug Local\Plugins\Diagnostics\projA.dll'. Make sure the project has been built.`

**Comment by xJom** [comment]
The workaround for me right now, is to add two more Configurations, "Debug Pack" and "Release Pack", which instead builds everything to [path to projX]\\..\\$(Configuration)\\bin, to be able to pack.
