### ISSUE TITLE
ankita

### ISSUE THREAD

**Issue by ankitaa123** [NuGet/Home#6544]
please help me with this

1   Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Linker.TypeReferenceExtensions.<GetMethods>d__4.MoveNext()
   at Mono.Linker.Steps.TypeMapStep.TryMatchMethod(TypeReference type, MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.GetBaseMethodInTypeHierarchy(TypeDefinition type, MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.MapVirtualMethods(TypeDefinition type)
   at Mono.Linker.Steps.TypeMapStep.MapType(TypeDefinition type)
   at Mono.Linker.Steps.TypeMapStep.ProcessAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	nagarnigammap.Android

2 

Severity Code Description Project File Line Suppression State Error The "LinkAssemblies" task failed unexpectedly. System.NullReferenceException: Object reference not set to an instance of an object. at Mono.Linker.TypeReferenceExtensions.<GetMethods>d__4.MoveNext() at Mono.Linker.Steps.TypeMapStep.TryMatchMethod(TypeReference type, MethodDefinition method) at Mono.Linker.Steps.TypeMapStep.GetBaseMethodInTypeHierarchy(TypeDefinition type, MethodDefinition method) at Mono.Linker.Steps.TypeMapStep.MapVirtualMethods(TypeDefinition type) at Mono.Linker.Steps.TypeMapStep.MapType(TypeDefinition type) at Mono.Linker.Steps.TypeMapStep.ProcessAssembly(AssemblyDefinition assembly) at Mono.Linker.Steps.BaseStep.Process(LinkContext context) at Mono.Linker.Pipeline.Process(LinkContext context) at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context) at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res) at Xamarin.Android.Tasks.LinkAssemblies.Execute() at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() nagarnigammap.Android

**Comment by rohit21agrawal** [comment]
@ankitaa123 please open a bug on the mono repository at  https://github.com/mono/mono
