### ISSUE TITLE
Error occurred while restoring NuGet packages: System.InvalidOperationException

### ISSUE THREAD

**Issue by pepone** [NuGet/Home#6558]
I getting this error with Visual Studio 15.5.5, I have a solution with several .NET Core projects, all the projects has a reference to [zeroc.icebuilder.msbuild](https://www.nuget.org/packages/zeroc.icebuilder.msbuild/) NuGet package I create.

I have[ Ice Builder](https://marketplace.visualstudio.com/items?itemName=ZeroCInc.IceBuilder) extension installed 

My NuGet package defines a new project [capability ](https://github.com/zeroc-ice/ice-builder-msbuild/blob/master/msbuild/zeroc.icebuilder.msbuild.csharp.targets#L37)`SliceCompile` and my extension register a [IVsProjectDesignerPageProvider ](https://github.com/zeroc-ice/ice-builder-visualstudio/blob/master/IceBuilder_Common/ProjectDesignerPageProvider.cs#L28)for this capability

So when the package is restore by NuGet package Manager, VS reloads the project because it see this new capability and this result in the `System.InvalidOperationException` from NuGet

## Detailed repro steps so we can see the same problem

1. Install [Ice Builder](https://marketplace.visualstudio.com/items?itemName=ZeroCInc.IceBuilder) extension

2. Clone the demo projects 

```
git clone https://github.com/zeroc-ice/ice-demos.git
cd ice-demos
git checkout v3.7.1-netcore-beta1
```

3. Open the solution file with Visual Studio 2017 `csharp/C# NET Core demos.sln`

### Verbose Logs

```
Error occurred while restoring NuGet packages: System.InvalidOperationException: The operation failed as details for project helloservice could not be loaded.
   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAsync(DependencyGraphCacheContext context)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<GetSolutionRestoreSpec>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestorePackageSpecProjectsAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<ExecuteAsync>d__15.MoveNext()
Error occurred while restoring NuGet packages: System.InvalidOperationException: The operation failed as details for project server could not be loaded.
   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAsync(DependencyGraphCacheContext context)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<GetSolutionRestoreSpec>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestorePackageSpecProjectsAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<ExecuteAsync>d__15.MoveNext()
Restoring NuGet packages...
```

**Comment by zhili1208** [comment]
Did this work in any version of VS 2017?

**Comment by emgarten** [comment]
The issue is that the project system hasn't yet sent the list of PackageReferences in the project to NuGet at the time restore begins.

Root cause is likely: https://github.com/NuGet/Home/issues/6575

**Comment by zkat** [comment]
We have done some work to improve working with unloaded projects. There's a dedicated error code now that has instructions on how to move forward. Please see https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1105
