### ISSUE TITLE
V3 RC - Exception trying to install packages with VS 2015 RC

### ISSUE THREAD

**Issue by onovotny** [NuGet/Home#659]
Opened my project, tried to add a nuget packge to some of my projects, got the following in the output window. Trying again unchecking the "show preview window" succeeded:

Attempting to gather dependencies information for package 'GitVersionTask.3.0.0-beta0002' with respect to project targeting '.NETPortable, Version=v4.5, Profile=Profile259'
Attempting to resolve dependencies for package 'GitVersionTask.3.0.0-beta0002' with DependencyBehavior 'Lowest'
Resolving actions to install package 'GitVersionTask.3.0.0-beta0002'
Resolved actions to install package 'GitVersionTask.3.0.0-beta0002'
Attempting to gather dependencies information for package 'GitVersionTask.3.0.0-beta0002' with respect to project targeting 'MonoAndroid, Version=v4.0.3'
Attempting to resolve dependencies for package 'GitVersionTask.3.0.0-beta0002' with DependencyBehavior 'Lowest'
Resolving actions to install package 'GitVersionTask.3.0.0-beta0002'
Resolved actions to install package 'GitVersionTask.3.0.0-beta0002'
Attempting to gather dependencies information for package 'GitVersionTask.3.0.0-beta0002' with respect to project targeting 'MonoTouch, Version=v1.0'
Attempting to resolve dependencies for package 'GitVersionTask.3.0.0-beta0002' with DependencyBehavior 'Lowest'
Resolving actions to install package 'GitVersionTask.3.0.0-beta0002'
Resolved actions to install package 'GitVersionTask.3.0.0-beta0002'
Attempting to gather dependencies information for package 'GitVersionTask.3.0.0-beta0002' with respect to project targeting 'Xamarin.iOS, Version=v1.0'
Attempting to resolve dependencies for package 'GitVersionTask.3.0.0-beta0002' with DependencyBehavior 'Lowest'
Resolving actions to install package 'GitVersionTask.3.0.0-beta0002'
Resolved actions to install package 'GitVersionTask.3.0.0-beta0002'
Attempting to gather dependencies information for package 'GitVersionTask.3.0.0-beta0002' with respect to project targeting 'Windows, Version=v8.1'
Attempting to resolve dependencies for package 'GitVersionTask.3.0.0-beta0002' with DependencyBehavior 'Lowest'
Resolving actions to install package 'GitVersionTask.3.0.0-beta0002'
Resolved actions to install package 'GitVersionTask.3.0.0-beta0002'
Attempting to gather dependencies information for package 'GitVersionTask.3.0.0-beta0002' with respect to project targeting 'Windows, Version=v8.1'
Attempting to resolve dependencies for package 'GitVersionTask.3.0.0-beta0002' with DependencyBehavior 'Lowest'
Resolving actions to install package 'GitVersionTask.3.0.0-beta0002'
Resolved actions to install package 'GitVersionTask.3.0.0-beta0002'
Attempting to gather dependencies information for package 'GitVersionTask.3.0.0-beta0002' with respect to project targeting '.NETFramework, Version=v4.5'
Attempting to resolve dependencies for package 'GitVersionTask.3.0.0-beta0002' with DependencyBehavior 'Lowest'
Resolving actions to install package 'GitVersionTask.3.0.0-beta0002'
Resolved actions to install package 'GitVersionTask.3.0.0-beta0002'
Attempting to gather dependencies information for package 'GitVersionTask.3.0.0-beta0002' with respect to project targeting 'Windows, Version=v8.1'
Attempting to resolve dependencies for package 'GitVersionTask.3.0.0-beta0002' with DependencyBehavior 'Lowest'
Resolving actions to install package 'GitVersionTask.3.0.0-beta0002'
Resolved actions to install package 'GitVersionTask.3.0.0-beta0002'
Attempting to gather dependencies information for package 'GitVersionTask.3.0.0-beta0002' with respect to project targeting 'WindowsPhone, Version=v8.0'
Attempting to resolve dependencies for package 'GitVersionTask.3.0.0-beta0002' with DependencyBehavior 'Lowest'
Resolving actions to install package 'GitVersionTask.3.0.0-beta0002'
Resolved actions to install package 'GitVersionTask.3.0.0-beta0002'
Attempting to gather dependencies information for package 'GitVersionTask.3.0.0-beta0002' with respect to project targeting 'WindowsPhoneApp, Version=v8.1'
Attempting to resolve dependencies for package 'GitVersionTask.3.0.0-beta0002' with DependencyBehavior 'Lowest'
Resolving actions to install package 'GitVersionTask.3.0.0-beta0002'
Resolved actions to install package 'GitVersionTask.3.0.0-beta0002'
System.Windows.Markup.XamlParseException: Set property 'System.Windows.Controls.ContentControl.Content' threw an exception. ---> System.InvalidOperationException: 'DialogWindowBase' TargetType does not match type of element 'PreviewWindow'.
   at System.Windows.Style.CheckTargetType(Object element)
   at System.Windows.StyleHelper.UpdateThemeStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldThemeStyle, Style newThemeStyle, Style& themeStyleCache)
   at System.Windows.FrameworkElement.OnThemeStyleChanged(DependencyObject d, Object oldValue, Object newValue)
   at System.Windows.StyleHelper.GetThemeStyle(FrameworkElement fe, FrameworkContentElement fce)
   at System.Windows.FrameworkElement.UpdateThemeStyleProperty()
   at System.Windows.FrameworkElement.OnThemeStyleKeyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at DevExpress.Xpf.Core.DependencyObjectWrapper.SetDefaultStyleKey(Object value)
   at DevExpress.Xpf.Core.ThemeManager.UpdateDefaultStyleKey(DependencyObjectWrapper wrapper, String themeName)
   at DevExpress.Xpf.Core.ThemeManager.TreeWalkerChanged(DependencyObject obj, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at DevExpress.Xpf.Core.ThemeManager.ChangeTheme(DependencyObject obj, String themeName, Boolean isTouch, String oldThemeName)
   at DevExpress.Xpf.Core.ThemeManager.ThemeNamePropertyChanged(DependencyObject obj, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at DevExpress.Xpf.Core.ThemeManager.SetThemeName(DependencyObject obj, String value)
   at DevExpress.Xpf.Core.ThemeManager.DevExpress.Xpf.Utils.Themes.IThemeManager.SetThemeName(DependencyObject d, String value)
   at DevExpress.Xpf.Utils.Themes.GlobalThemeHelper.SetGlobalTheme(FrameworkElement window)
   at DevExpress.Xpf.Utils.Themes.WindowTracker.DoWork(Object sender)
   at DevExpress.Xpf.Utils.Themes.WindowTracker.<.cctor>b__1(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.PropertyChangedCallback.Invoke(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at NuGet.PackageManagement.UI.PreviewWindow.InitializeComponent()
   at NuGet.PackageManagement.UI.NuGetUI.<>c__DisplayClass7.<PromptForPreviewAcceptance>b__6()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at NuGet.PackageManagement.UI.NuGetUI.PromptForPreviewAcceptance(IEnumerable`1 actions)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformAction>d__0.MoveNext()
========== Finished ==========

**Comment by yishaigalatzer** [comment]
Can we get some more info for reproducing the issue

What was in your packages.config before installing?
What is the project type?
What package(s) where you installing?

**Comment by feiling** [comment]
DevExpress.Xpf.Core.ThemeManager (https://documentation.devexpress.com/#wpf/clsDevExpressXpfCoreThemeManagertopic) shows up in the call stack. This leads me to believe there must be 3rd theme engine installed on your machine. There's no way for us to support such scenarios.

**Comment by onovotny** [comment]
See https://github.com/NuGet/Home/issues/649 for the root cause. It's the sci-tech memory profiler add-in that's loading the DevExpress controls into memory.
