### ISSUE TITLE
"nuget.exe restore" fails because it can't find Newtonsoft.Json 

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#6670]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): nuget.exe

NuGet version (x.x.x.xxx):  4.6.0.4971

This used to work. Not sure what happened here.

## Detailed repro steps so we can see the same problem

I just ran "nuget restore src" under my [VSSDKTestFx repo](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VSSDKTestFx).

```
MSBuild auto-detection: using msbuild version '15.7.66.2115' from 'C:\Program Files (x86)\Microsoft Visual Studio\d15.7stg\MSBuild\15.0\bin'.
Restoring packages for D:\git\VSSDKTestFx\src\Microsoft.VisualStudio.Sdk.TestFramework.Tests\Microsoft.VisualStudio.Sdk.TestFramework.Tests.csproj...
Restoring packages for D:\git\VSSDKTestFx\src\Microsoft.VisualStudio.Sdk.TestFramework\Microsoft.VisualStudio.Sdk.TestFramework.csproj...
  CACHE https://api.nuget.org/v3-flatcontainer/nerdbank.gitversioning/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/nerdbank.gitversioning/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.visualstudio.composition/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/nerdbank.gitversioning/2.0.41/nerdbank.gitversioning.2.0.41.nupkg
  GET https://www.myget.org/F/vs-devcore/api/v3/flatcontainer/nerdbank.gitversioning/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.visualstudio.composition/15.5.23/microsoft.visualstudio.composition.15.5.23.nupkg
  GET https://www.myget.org/F/vs-devcore/api/v3/flatcontainer/microsoft.visualstudio.composition/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.visualstudio.composition/15.5.23/microsoft.visualstudio.composition.15.5.23.nupkg 322ms
  NotFound https://www.myget.org/F/vs-devcore/api/v3/flatcontainer/microsoft.visualstudio.composition/index.json 683ms
  NotFound https://www.myget.org/F/vs-devcore/api/v3/flatcontainer/nerdbank.gitversioning/index.json 722ms
  GET https://www.myget.org/F/vs-devcore/api/v3/flatcontainer/nerdbank.gitversioning/index.json
  NotFound https://www.myget.org/F/vs-devcore/api/v3/flatcontainer/nerdbank.gitversioning/index.json 180ms
CredentialProvider.VSS: Getting new credentials for source:https://devdiv.pkgs.visualstudio.com/_packaging/VSIDE-RealSigned-Release/nuget/v3/index.json, scope:vso.packaging_write vso.drop_write
CredentialProvider.VSS: Caught exception: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
CredentialProvider.VSS: Caught exception: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
CredentialProvider.VSS: Caught exception: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
CredentialProvider.VSS: Caught exception: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
CredentialProvider.VSS: Couldn't get an authentication token for https://devdiv.pkgs.visualstudio.com/_packaging/VSIDE-RealSigned-Release/nuget/v3/index.json.
CredentialProvider.VSS: Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
CredentialProvider.VSS:    --- End of inner exception stack trace ---
CredentialProvider.VSS:    at Microsoft.VS.Services.NuGet.CredentialProvider.CredentialResponse.ToString()
CredentialProvider.VSS:    at System.IO.TextWriter.WriteLine(Object value)
CredentialProvider.VSS:    at System.IO.TextWriter.SyncTextWriter.WriteLine(Object value)
CredentialProvider.VSS:    at Microsoft.VS.Services.NuGet.CredentialProvider.Program.WriteResponse(CredentialResponse credentialResponse)
CredentialProvider.VSS:    at Microsoft.VS.Services.NuGet.CredentialProvider.Program.Main(String[] args)
CredentialProvider.VSS:    at Microsoft.VS.Services.NuGet.CredentialProvider.AssemblyLoader.Main(String[] args)
CredentialProvider.VSS: Getting new credentials for source:https://mseng.pkgs.visualstudio.com/_packaging/VS-PrivateAssemblies/nuget/v3/index.json, scope:vso.packaging_write vso.drop_write
CredentialProvider.VSS: Caught exception: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
CredentialProvider.VSS: Caught exception: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
CredentialProvider.VSS: Caught exception: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
CredentialProvider.VSS: Caught exception: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
CredentialProvider.VSS: Couldn't get an authentication token for https://mseng.pkgs.visualstudio.com/_packaging/VS-PrivateAssemblies/nuget/v3/index.json.
CredentialProvider.VSS: Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
CredentialProvider.VSS:    --- End of inner exception stack trace ---
CredentialProvider.VSS:    at Microsoft.VS.Services.NuGet.CredentialProvider.CredentialResponse.ToString()
CredentialProvider.VSS:    at System.IO.TextWriter.WriteLine(Object value)
CredentialProvider.VSS:    at System.IO.TextWriter.SyncTextWriter.WriteLine(Object value)
CredentialProvider.VSS:    at Microsoft.VS.Services.NuGet.CredentialProvider.Program.WriteResponse(CredentialResponse credentialResponse)
CredentialProvider.VSS:    at Microsoft.VS.Services.NuGet.CredentialProvider.Program.Main(String[] args)
CredentialProvider.VSS:    at Microsoft.VS.Services.NuGet.CredentialProvider.AssemblyLoader.Main(String[] args)
```

**Comment by rohit21agrawal** [comment]
@AArnott have you tried this with NuGet.exe 4.5?  Just want to make sure this is a regression on our end or not.

**Comment by AArnott** [comment]
This fails on 4.1 and 4.5.1 of nuget.exe as well. So I wonder if it's a machine configuration vulnerability of nuget.exe. I vaguely recall that (at least past versions of) nuget.exe is sensitive to GAC'd copies of some assemblies.

**Comment by AArnott** [comment]
BTW this isn't just the VSSDKTestFx repo. It's failing everywhere on this machine, which further makes me think it's nuget.exe vulnerability to some machine configuration.

**Comment by rohit21agrawal** [comment]
Looking at the call stack, this is owned by VSTS.

Cc: @jeffkl @zachrunner

**Comment by AArnott** [comment]
When I copy newtonsoft.json.dll,8.0.3 to the directory that contains nuget.exe and CredentialProvider.VSS.exe, it works.
I was using 0.25.0 of CredentialProvider.VSS.exe. When I copied 0.34.0 down of that .exe, and deleted the .config file I had next to it, it started working again.

**Comment by AArnott** [comment]
The CredentialProvider.VSS.exe.config file was a workaround for the newtonsoft.json.dll bug I remember hitting before. So with the newer version perhaps the workaround is no longer needed. Since I'm on the latest version of the tool now and it works, I'll close the issue.
