### ISSUE TITLE
Warn users of likely breaking changes when updating to new major versions

### ISSUE THREAD

**Issue by justcla** [NuGet/Home#6673]
Recently we’ve had lots of users complaining that their projects broke when they updated their Bootstrap NuGet package from v3 to v4.

The root problem is that there are breaking changes between the major versions of Bootstrap. However, there was no way for a user to know that when updating via the NuGet manager.

Ultimately, a user should be careful when updating NuGet packages, as any change in dependencies could break their existing code.
Our response to the users could be something like “This is your fault. In future, please be careful when updating NuGet packages.”
But given how easy we make it for users to see updated NuGet packages and to one-click update all, we might be leading our users into a trap.

My suggestion is that, when updating NuGet packages, we warn the user that updating their dependencies could have detrimental effects on their project – especially when an updated NuGet package has an increased Major version.

**Suggestion:**
Could we offer a confirmation dialog on Update that warns of potentially breaking changes?
-	It should include a “Don’t show this again”, for users who accept the risk and don’t want to be warned in future.
-	It could list all packages that have an increased major version and call them out as “High Risk” updates.

**Comment by bricelam** [comment]
Another very related issue: If there are two versions of a dependency in the restore graph that span major versions, NuGet should also generate a big fat warning.

* Project
  * DependencyA
    * TransitiveDependency v1.0.0
  * DependencyB
    * TransitiveDependency v2.0.0

> warning NUXXXX: TransitiveDependency version 2.0.0 is being used but DependencyA depends on version 1.0.0. DependencyA may encounter errors at runtime due to breaking changes between TransitiveDependency versions 1.0.0 and 2.0.0.

**Comment by airbreather** [comment]
> Another very related issue: If there are two versions of a dependency in the restore graph that span major versions, NuGet should also generate a big fat warning.
> 
> * Project
>   * DependencyA
>     * TransitiveDependency v1.0.0
>   * DependencyB
>     * TransitiveDependency v2.0.0

Current workaround is for every package that might be a DependencyA to specify explicit upper-bounds on `PackageReference` versions, e.g., aspnet/EntityFrameworkCore#18192 (with consideration for #6434).

This allows NU1608 to get raised in these situations, which doesn't quite have "big fat warning" status as things stand today, but I think it's an improvement over putting "obvious" values for `PackageReference` version numbers.

**Comment by airbreather** [comment]
> If there are two versions of a dependency in the restore graph that span major versions, NuGet should also generate a big fat warning.

I just hit something today that reminded me of this issue.

I've been called over to help migrate an ASP.NET Core web application from 2.1 to 5.0.  I wanted to first upgrade all the dependencies to the latest versions that `netcoreapp2.1` can reference (most notably, EF Core to 3.1) so that the final switchover from 2.1 to 5.0 will be a more manageable size for the reviewers.

Well, much to my surprise, EF Core 2.1 to 3.1 wasn't a hard blocker, but `Microsoft.Extensions.Options` to 5.0.0 was: because the newer version of that package depends on the newer version of the `Microsoft.Extensions.Primitives` package, I get the following stack trace related to dotnet/runtime#40743:
```
System.TypeLoadException: Could not load type 'Microsoft.Extensions.Primitives.InplaceStringBuilder' from assembly 'Microsoft.Extensions.Primitives, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.Net.Http.Headers.DateTimeFormatter.ToRfc1123String(DateTimeOffset dateTime, Boolean quoted)
   at Microsoft.Net.Http.Headers.HeaderUtilities.FormatDate(DateTimeOffset dateTime)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.DateHeaderValueManager.SetDateValues(DateTimeOffset value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory)
  --- SNIP ---
```
I know why this happens, and I'm not asking for this type to be added back (you probably won't ever see me complain about removing obsolete crap), especially now that .NET Core 2.1 is fully out-of-support.  What I'm mostly concerned about is the fact that there seems to be something missing in the .NET toolchain that would let me know about this issue in advance.
- Now, **fortunately** in this case, the issue happens reliably and fairly early in the application, but considering that we don't typically deprecate and remove APIs that are commonly used*, it seems very plausible that there may be some other different issues that would have escaped our testing.
    - \**I appreciate the irony of me saying this, given that I'm the guy who pushed for and implemented a breaking change that affected a ton of applications during a major version upgrade of a NuGet package that had had hundreds of thousands of downloads when I did so :wink:*.

You'd think that the `[Obsolete]` warning would satisfy this, but it really doesn't, since it wasn't actually obsolete in the package version that was used [here](https://github.com/dotnet/aspnetcore/blob/v2.1.30/src/Http/Headers/src/DateTimeFormatter.cs#L40), and I'm not calling that method directly; rather, [this](https://github.com/dotnet/aspnetcore/blob/v2.1.30/src/Servers/Kestrel/Core/src/Internal/Http/DateHeaderValueManager.cs#L54) is doing it on my behalf.

Ultimately, this seems to me like a major gap: I really don't see anything that the above-linked pull request **could** have done differently to get my attention onto this before I actually went to run the application, and I'm not really seeing a reasonable way that I could write a tool to statically discover these breaking changes, either.

**EDIT**
I'm also reminded about this post: https://codeblog.jonskeet.uk/2019/10/25/options-for-nets-versioning-issues
