### ISSUE TITLE
dotnet restore fails with NU1108 error ("Cycle detected") if csproj has the same name as a dependant PackageReference

### ISSUE THREAD

**Issue by evil-shrike** [NuGet/Home#6754]
A real case - you want to play with a library, let's take Autofac. You create a folder named "autofac" then run `dotnet new console` then `dotnet add package Autofac` and then run VSCode anticipating a fun.
Agree to install required assets for .net project and run restore to get intellisense.
Bump! Error - NU1108: Cycle detected.

```
D:\Work\Learn\autofac>dotnet restore
  Restoring packages for D:\Work\Learn\autofac\autofac.csproj...
D:\Work\Learn\autofac\autofac.csproj : error NU1108: Cycle detected.
D:\Work\Learn\autofac\autofac.csproj : error NU1108:   autofac -> Autofac (>= 1.0.0).
  Generating MSBuild file D:\Work\Learn\autofac\obj\autofac.csproj.nuget.g.props.
  Restore failed in 247,83 ms for D:\Work\Learn\autofac\autofac.csproj.
```
then you have to renam `autofac.csproj` to `autofac-sandbox.csproj` and restore starts working but not VSCode. you'll have to recreate project. it pains.
```
D:\Work\Learn\autofac>dotnet restore
  Restoring packages for D:\Work\Learn\autofac\autofac-sandbox.csproj...
  Installing Autofac 2.2.4.900.
D:\Work\Learn\autofac\autofac-sandbox.csproj : warning NU1603: autofac-sandbox depends on Autofac (>= 1.0.0) but Autofac 1.0.0 was not found. An approximate best match of Autofac 2.2.4.900 was resolved.
```

**Comment by nkolev92** [comment]
This is by design. 

Since project.json, NuGet has been moving towards project-package duality.

A project and a dependency cannot have the same name. 

I don't think NuGet needs to do anything different here.

**Comment by JohanLarsson** [comment]
Another case is if you have an analyzer library and want to use the published analyzer on the analyzer code.
I tried `<NoWarn>NU1108</NoWarn>` but it had no effect.

**Comment by tmat** [comment]
This is a general problem for toolset packages (DevelopmentDependency=true) that use previous versions of themselves during build. For example a Microsoft.SourceLink package.

> I don't think NuGet needs to do anything different here.

I  think NuGet needs to have a concept that allows it to distinguish between packages that are used in build and packages that are being built.

**Comment by tmat** [comment]
A workaround is to define PackageId to some unique value and then redefine it to the actual value in a target that runs just before Pack target.

```xml
  <PropertyGroup>
    <PackageId>*$(MSBuildProjectFullPath)*</PackageId>
  </PropertyGroup>

  <Target Name="_UpdatePackageId" BeforeTargets="$(PackDependsOn)" >
    <PropertyGroup>
      <PackageId>$(MSBuildProjectName)</PackageId>
    </PropertyGroup>
  </Target>
```

**Comment by nkolev92** [comment]
> I think NuGet needs to have a concept that allows it to distinguish between packages that are used in build and packages that are being built.

I agree with this, it's just that other design decisions such as Dev dependency itself kind of limit/kill some of the options. 
It'd be a significant undertaking, which we'd need to prioritize first. 
// cc @rrelyea

**Comment by TFTomSun** [comment]
Any progress on this issue? I ran into the same problem with a build package that is used by the project that builds the package.

**Comment by KirillOsenkov** [comment]
I just hit this and I think it's a problem that needs addressing.

There are two ways to interpret a name when a project has the same name as a package. One of them results in a cycle, the other doesn't. How about trying both combinations and only failing when no self-consistent combinations are possible?

It is really unexpected honestly to try to interpret the name inside PackageReference as a project first. Shouldn't it try to interpret it as a package first, and only when that fails, fall back to projects?

And what does it even mean to have a PackageReference to a project? Shouldn't it then include a path to the .csproj and not just a name?

This is very strange and counter-intuitive design honestly.

**Comment by TFTomSun** [comment]
@KirillOsenkov 
I use the approach of @tmat as a workaround and put it into the Directory.Build.targets of my repository. It could also be moved into a build package:

```xml
  <!--Begin: Avoid cycle error when package builds itself-->
  <Choose>
    <When Condition="$(AvoidCycleErrorOnSelfReference) == 'true'">
      <PropertyGroup>
        <PackageId Condition="'$(PackageId)' == ''">$(MSBuildProjectName)</PackageId>
        <PackageIdTemp>$(PackageId)</PackageIdTemp>
        <PackageId>$(PackageId)_temp</PackageId>
      </PropertyGroup>
    </When>
  </Choose>
  <Target Name="_UpdatePackageId" BeforeTargets="$(PackDependsOn)" Condition="$(AvoidCycleErrorOnSelfReference) == 'true'" >
    <PropertyGroup>
      <PackageId>$(PackageIdTemp)</PackageId>
    </PropertyGroup>
  </Target>
  <!--End: Avoid cycle error when package builds itself-->
```

In a project where you run into the issue simply add:

```xml
    <PropertyGroup>
      <AvoidCycleErrorOnSelfReference>true</AvoidCycleErrorOnSelfReference>
    </PropertyGroup>
```

**Comment by RachelDavids** [comment]
Came across this today. Created my standalone (not a package) csproj called "Validation"  several months ago. Today I tried to include "PInvoke.User32" - this has a dependency on a package called "Validation". How am I, as a developer, supposed to know that I should not have used "Validation" for my project name.

**Comment by RachelDavids** [comment]
@KirillOsenkov @tmat I tried the workaround mentioned earlier and it seems to have worked. BUT I'm not building a package so why should defining a PackageId change anything for me?

**Comment by pcgeek86** [comment]
Just ran into this problem. Hacked around it by renaming the project directory. At the very least, a useful error message would be appreciated.

**Comment by TFTomSun** [comment]
just discovered that the workaround from here https://github.com/NuGet/Home/issues/6754#issuecomment-592283619 just works as long as your development package has no other development package as dependency, for which you have to avoid the cyclic dependency error as well. 
If a dev package has a dependency on another dev package for which you workaround the cycle detection error you'd get the '_temp' package id as the dependency name in the referencing package. 

Does anyone have a workaround for that scenario?

@nkolev92 
Would it be difficult to add a flag that allows us to suppress the error? In case of dev package the error is a false positive, because if you add the dev package with 'PrivateAssets='all'' configured,  it doesn't become a dependency of itself -> no cyclic dependency in that scenario

**Comment by loic-sharma** [comment]
Here is another report: https://github.com/CompositionalIT/farmer/issues/595

Here is the output the customer received:

```
d:\code\mse\multiTenant\farmer>dotnet add package Farmer
  Determining projects to restore...
  Writing C:\Users\maxw\AppData\Local\Temp\tmpFE34.tmp
info : Adding PackageReference for package 'Farmer' into project 'd:\code\mse\multiTenant\farmer\farmer.fsproj'.
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/farmer/index.json
info : Restoring packages for d:\code\mse\multiTenant\farmer\farmer.fsproj...
error: NU1108: Cycle detected.
error:   farmer -> Farmer (>= 1.4.0).
info : Package 'Farmer' is compatible with all the specified frameworks in project 'd:\code\mse\multiTenant\farmer\farmer.fsproj'.
error: Value cannot be null. (Parameter 'path1')
```

While supporting this scenario may be too costly for NuGet, it certainly does seem like we could improve the user experience with a better error message. For example:

```diff
d:\code\mse\multiTenant\farmer>dotnet add package Farmer
  Determining projects to restore...
  Writing C:\Users\maxw\AppData\Local\Temp\tmpFE34.tmp
info : Adding PackageReference for package 'Farmer' into project 'd:\code\mse\multiTenant\farmer\farmer.fsproj'.
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/farmer/index.json
info : Restoring packages for d:\code\mse\multiTenant\farmer\farmer.fsproj...
-error: NU1108: Cycle detected
+error: NU1108: Cycle detected. The project 'farmer' cannot depend on a package named 'Farmer':
error:   farmer -> Farmer (>= 1.4.0).
+error: Please rename the project 'farmer' or remove the 'Farmer' dependency.
-info : Package 'Farmer' is compatible with all the specified frameworks in project 'd:\code\mse\multiTenant\farmer\farmer.fsproj'.
-error: Value cannot be null. (Parameter 'path1')
```

Also, it seems that we could add more information to NU1108's docs: https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1108

**Comment by isaacabraham** [comment]
@loic-sharma Agreed. There seems to be some resistance to fixing this issue / it being "by design". I think that that's an unfortunate attitude, but I don't want to get into any of that really: just fixing the error message would probably solve 90%+ of reports across projects and save lots of developers going down a wrong path, thinking e.g.

* "The package doesn't work!"
* "The package doesn't work with the version of .NET being used!"
* "NuGet is broken!"

An error that simply said something like this would probably suffice as a work around:

`You cannot create a .NET project with the same name as a NuGet package in that project. Please rename the project to something else`.

**Comment by scottkupec** [comment]
I've been using the work around above to run the published version of my code analyzer against the version currently being built.  Today, I decided to (finally) update all of my build pipelines to .NET SDK 3.1.x and see that I get this error:

```
2021-04-04T09:07:32.4982548Z ##[error]C:\hostedtoolcache\windows\dotnet\sdk\3.1.407\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): Error MSB4018: The "GenerateDepsFile" task failed unexpectedly.
System.ArgumentException: Can not add property My.Code.Analyzer/1.0.0 to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Microsoft.Extensions.DependencyModel.DependencyContextWriter.WriteTarget(IReadOnlyList`1 libraries)
   at Microsoft.Extensions.DependencyModel.DependencyContextWriter.WriteTargets(DependencyContext context)
   at Microsoft.Extensions.DependencyModel.DependencyContextWriter.Write(DependencyContext context)
   at Microsoft.Extensions.DependencyModel.DependencyContextWriter.Write(DependencyContext context, Stream stream)
   at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath)
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

Updating the assembly version is sufficient to mitigate.  I haven't looked into if something can be done about with an AssemblyVersion_temp or similar to provide a cleaner work around.

Adding this just in case it helps others get to this thread when searching for more information on the exception.

**Comment by Akash-Mair** [comment]
Ran into this problem yesterday, had no idea the project name was the problem from the error message.

**Comment by tg73** [comment]
I have a scenario where, at the end of a build, I want to compare the compiled binaries to the last published version of the current project. So before target `CollectPackageRefrences` , I add a `PackageReference` to the last published version, with `ExcludeAssets=all` (and `GeneratePathProperty=true`, so the binaries can be found for analysis). Surely there is no way that this should be construed as a cyclic dependency, as no assets are consumed?

**Comment by isaacabraham** [comment]
@loic-sharma any thoughts on this? I had another partner of ours fall foul of this recently.

**Comment by mathias-brandewinder** [comment]
Agree that a more explicit error message would go a long way. I just ran into the same case @loic-sharma is describing, and it took me a bit to figure out the source of the problem. 
After a while, `-error: NU1108: Cycle detected` finally put me on the right track, but this part lead me down the wrong path first:
```
-info : Package 'XYZ' is compatible with all the specified frameworks in project 'XYZ.fsproj'.
-error: Value cannot be null. (Parameter 'path1')
```

**Comment by loic-sharma** [comment]
@isaacabraham I like your error message, it would certainly help unblock customers! Sadly this is not my area of expertise, I'll ping the NuGet client team on this issue.

**Comment by LogoFun13-YT** [comment]
Trying to get a package ready for release on a personal repository, and it gives me the NU1108 error? If anyone has a good fix for this, please let me know as soon as possible.

**Comment by Isofteer** [comment]
After all that just make sure the solution name isnt similar with the nuget package you are installing

**Comment by kumkee** [comment]
> A project and a dependency cannot have the same name.

At least please output a command line error message stating the above reason, so that people don't have to do some Google Search just to arrive here.

**Comment by namerril** [comment]
+1 from me.  I am creating Roslyn analyzers.  I would like to consume my own analyzers (via PackageReference), and as far as I can tell, this is not possible.  

I attempted to use the above workaround, but that doesn't work in all situations.  If there is a project reference to the renamed project, it will use the restore data (project.assets.json) to populate its dependencies, so the final package will have the wrong dependencies.

Please allow DevelopmentDependency="true" or PrivateAssets="all" or some other metadata to allow cyclical dependencies.

**Comment by LukasGelke** [comment]
it seems this issue is re-appearing with DotNet 10, even with the workaround in place.

As I'm currently evaluating VS 2026 (via parallel install), it is required to install net10. And our build script (to generate NuGet Package of our internal Analyzer) fails with `NU1108` again.
Using a `global.json` works for now, as the projects are still net8

**Comment by akoeplinger** [comment]
As I just hit this in https://github.com/dotnet/symreader-converter/pull/320, the workaround needs some changes after recent nuget updates:

`PackDependsOn` now includes `_GetRestoreProjectStyle` since NuGet/NuGet.Client#6712, causing `_UpdatePackageId` to run during Restore and undo the fake PackageId. Use `$(BeforePack)` property instead to keep it Pack-only.
