### ISSUE TITLE
Restore using MSBuild EXEC and NuGet.exe + CredentialProvider.VSS.exe failing

### ISSUE THREAD

**Issue by joeloff** [NuGet/Home#6986]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 4.6.2, 4.7.0

dotnet.exe --version (if appropriate): N/A

VS version (if appropriate): 2017

OS version (i.e. win10 v1607 (14393.321)): Win10

Worked before? If so, with which NuGet version: 3.5

## Detailed repro steps so we can see the same problem

1. Create an item group that contains multiple packages with metadata representing the sources, e.g.

```
<ItemGroup>
  <Packages Include="Package.A.ID">
    <Source>https://somewhere.com/nuget/v3/index.json</Source>
  </Packages>
</ItemGroup>
```

2. Invoke Exec task in msbuild to run restore

```
<Exec Command="$(NuGetExe) install %(Packages.Identity) -source %(Source) -excludeversion -outputdirectory $(RestorePath) -noninteractive -prerelease -verbosity detail" />
```

When the Exec task is invoked on a single package it appears to work fine, but when there are multiple packages it appears to fail when using 4.2.6 or 4.7.0 copies of NuGet.exe.

Below is a stack trace I get when running with detailed verbosity

```
at NuGet.Resolver.PackageResolver.Resolve(PackageResolverContext context, CancellationToken token)
     at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__66.MoveNext()
     --- End of inner exception stack trace ---
     at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__66.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at NuGet.CommandLine.InstallCommand.<InstallPackageAsync>d__40.MoveNext()
```

**Comment by kardinal3000** [comment]
Hello guys need your assistance.

During _NuGet restore_ multiple packages, I catch the same NuGet exception that @joeloff  has.
For my needs I use **Nuget.PackageManagement.dll version - 4.7.0**  

```
InnerException : NuGet.Resolver.NuGetResolverConstraintException: Unable to resolve dependency 'bla-bla-bla'. 
					at NuGet.Resolver.PackageResolver.Resolve(PackageResolverContext context, CancellationToken token)
					at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__66.MoveNext()
TargetSite     : Void MoveNext()
StackTrace     :     at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__66.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
					at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
					at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__47.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Lego.Core.Commands.Restore.<Invoke>d__2.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
		    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
<ProcessRecordAsync>d__24.MoveNext()

```

**Comment by rohit21agrawal** [comment]
@kardinal3000 do you have a repro project we can look at ?

**Comment by rrelyea** [comment]
no repro. closing.
