### ISSUE TITLE
NuGet 4.7.0 fails to restore dotnet core 2.1 projects

### ISSUE THREAD

**Issue by AmyJeanes** [NuGet/Home#7002]
## Details about Problem

NuGet product used NuGet.exe

NuGet version 4.7.0:

dotnet.exe --version (if appropriate): 2.1.300

VS version (if appropriate): N/A

OS version (i.e. win10 v1607 (14393.321)): Windows Server 2016

Worked before? If so, with which NuGet version: N/A

## Detailed repro steps so we can see the same problem

1. Create a VS solution with a NET Core 2.1 project

2. Add any nuget package to the NET Core project

4. run nuget.exe restore Solution.sln

### Verbose Logs

```
2018-06-07T12:23:57.0181833Z NuGet.CommandLine.ExitCodeException: Exception of type 'NuGet.CommandLine.ExitCodeException' was thrown.
2018-06-07T12:23:57.0181833Z    at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__6.MoveNext()
2018-06-07T12:23:57.0181833Z --- End of stack trace from previous location where exception was thrown ---
2018-06-07T12:23:57.0181833Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-06-07T12:23:57.0181833Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-06-07T12:23:57.0181833Z    at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__48.MoveNext()
2018-06-07T12:23:57.0181833Z --- End of stack trace from previous location where exception was thrown ---
2018-06-07T12:23:57.0181833Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-06-07T12:23:57.0181833Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-06-07T12:23:57.0181833Z    at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__43.MoveNext()
2018-06-07T12:23:57.0181833Z WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
```

```
2018-06-07T12:24:02.7214468Z ##[error]C:\Program Files\dotnet\sdk\2.1.100\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5): Error : Assets file 'C:\BuildAgent\_work\84\s\<ProjectName>\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
2018-06-07T12:24:02.7214468Z      2>C:\Program Files\dotnet\sdk\2.1.100\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5): error : Assets file 'C:\BuildAgent\_work\84\s\<ProjectName>\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\BuildAgent\_work\84\s\<ProjectName>\<ProjectName>.csproj]
2018-06-07T12:24:02.7214468Z          Build continuing because "ContinueOnError" on the task "ReportAssetsLogMessages" is set to "ErrorAndContinue".
```

**Comment by AmyJeanes** [comment]
Apologies, accidentally pressed enter too early and it submitted 😢 all fixed up now

**Comment by AmyJeanes** [comment]
Actually, looks like I might have just needed to make sure I had the latest dotnet SDK during the build - will re-open if I continue to see issues but that looks like it solved it.
