### ISSUE TITLE
PackageResolver.Resolve throws ArgumentOutOfRangeException for empty list of targets

### ISSUE THREAD

**Issue by hickford** [NuGet/Home#7130]
Given empty list of targets, [PackageResolver.Resolve](https://github.com/NuGet/NuGet.Client/blob/7dec8e2bcbda2f7478f66a2c7f8095f845d98c79/src/NuGet.Core/NuGet.Resolver/PackageResolver.cs#L26) in the assembly NuGet.Resolver in package [NuGet.Resolver](https://www.nuget.org/packages/NuGet.Resolver/4.7.0) throws ArgumentOutOfRangeException.

To reproduce:

    using NuGet.Common;
    using NuGet.Configuration;
    using NuGet.Packaging;
    using NuGet.Packaging.Core;
    using NuGet.Protocol.Core.Types;
    using NuGet.Resolver;

    new PackageResolver().Resolve(new PackageResolverContext(DependencyBehavior.Highest, Array.Empty<string>(), Array.Empty<string>(), Array.Empty<PackageReference>(), Array.Empty<PackageIdentity>(), Array.Empty<SourcePackageDependencyInfo>(), Array.Empty<PackageSource>(), NullLogger.Instance), CancellationToken.None);

Expected: PackageResolver.Resolve returns empty set of packages. This is the minimal solution.

What actually happens: 

    System.ArgumentOutOfRangeException
    HResult=0x80131502
    Message=Index was out of range. Must be non-negative and less than the size of the collection.
    Parameter name: index
    Source=mscorlib
    StackTrace:
    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
    at NuGet.Resolver.CombinationSolver`1.<GetSortedList>d__18.MoveNext()
    at NuGet.Resolver.CombinationSolver`1.MoveForward(Int32 i, Boolean& consistent)
    at NuGet.Resolver.CombinationSolver`1.FindSolution(Action`1 diagnosticOutput)
    at NuGet.Resolver.CombinationSolver`1.FindSolution(IEnumerable`1 groupedItems, IComparer`1 itemSorter, Func`3 shouldRejectPairFunc, Action`1 diagnosticOutput)
    at NuGet.Resolver.PackageResolver.Resolve(PackageResolverContext context, CancellationToken token)

I am filing bug here following https://github.com/NuGet/NuGet.Client#feedback

**Comment by hickford** [comment]
The ArgumentOutOfRangeException is thrown by [CombinationSolver<T>.FindSolution](https://github.com/NuGet/NuGet.Client/blob/7dec8e2bcbda2f7478f66a2c7f8095f845d98c79/src/NuGet.Core/NuGet.Resolver/CombinationSolver.cs#L128)

**Comment by hickford** [comment]
Motivation: this bug affected my application which calls PackageResolver.Resolve. I worked around it by special casing.
