### ISSUE TITLE
Not able to include a .file in .nupkg (String cannot be empty. Parameter name: entryName)

### ISSUE THREAD

**Issue by jhenyffer** [NuGet/Home#7140]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version (x.x.x.xxx): 4.6.2.50.55

dotnet.exe --version (if appropriate): N/A

VS version (if appropriate): N/A

OS version (i.e. win10 v1607 (14393.321)): Windows 8.1

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

**1.** Create a .file archive

**2.** Create the nuspec below: 

`<?xml version="1.0"?>
<package>
  <metadata>
    <id>Automation</id>
    <version>1.0.0</version>
    <authors>Tech</authors>
    <owners>Tech</owners>    
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>SoapUI</description>
    <releaseNotes>First release</releaseNotes>
    <copyright>Copyright 2018</copyright>    
  </metadata>
  <files>    
	<file src="..\..\..\TestConfig\SoapUI-6.0.0\inst_jre.cfg" target=""/>
	<file src="..\..\..\TestConfig\SoapUI-6.0.0\MessagesDefault" target=""/>	
  </files>
</package>`

**3.** On CMD run nuget pack
**4.** The error below is displayed:
**String cannot be empty.
Parameter name: entryName**
...

Other suggested things: In my case the .file is the "MessagesDefault" file. I do not use Visual Studio and also do not have a .sln or .csproj

**Comment by zhili1208** [comment]
could you also provide the output log from nuget.exe?

**Comment by jhenyffer** [comment]
Could you guide me on how may I provide this?
If you mean the resulta of the Nuget Pack it is the error "String cannot be
empty. Parâmetro name:entryName"

Em seg, 23 de jul de 2018 18:19, Zhi Li <notifications@github.com> escreveu:

**Comment by zhili1208** [comment]
please try this: "nuget.exe pack -verbosity detailed"

**Comment by nkolev92** [comment]
@jhenyffer Can you please provide the logs/repro project?

**Comment by stephenfuqua** [comment]
I encountered this same error in a very simple nuspec file. While I do not see anything in the [documentation](https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-content-files) clearly showing that the `target` can be blank, it seems natural: if the destination file has the same name as the source file, and does not need to go into a directory, then it stands to reason that the target could be blank. For example, the following nuspec packs without a hitch (NuGet 4.52.5055):

```xml
<?xml version="1.0"?>
<package>
  <metadata>
    <id>Issue-7140</id>
    <version>1.0.0</version>
    <title>Issue 7140</title>
    <description>Sample for reproducing issue 7140</description>
    <authors>none</authors>
  </metadata>
  <files>
    <file src="Web.config" target="" />
  </files>
</package>
```

My original example had several other similar entries that did not have a problem. But when I added `<file src="SetupRequired" target="" />` - a file that does exist in the directory - NuGet throws the reported error:

```powershell
$ nuget pack sample.nuspec -verbosity detailed
NuGet Version: 4.6.2.5055
Attempting to build package from 'sample.nuspec'.
String cannot be empty.
Parameter name: entryName
System.ArgumentException: String cannot be empty.
Parameter name: entryName
   at System.IO.Compression.ZipArchive.DoCreateEntry(String entryName, Nullable`1 compressionLevel)
   at NuGet.Packaging.PackageBuilder.CreatePart(ZipArchive package, String path, Stream sourceStream, DateTimeOffset lastWriteTime)
   at NuGet.Packaging.PackageBuilder.WriteFiles(ZipArchive package, HashSet`1 filesWithoutExtensions)
   at NuGet.Packaging.PackageBuilder.Save(Stream stream)
   at NuGet.Commands.PackCommandRunner.BuildPackage(PackageBuilder builder, String outputPath)
   at NuGet.Commands.PackCommandRunner.BuildFromNuspec(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage()
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

As soon as I provide a target for this new file, then `nuget pack` works again. Other files that I was able to package without a target include `favicon.ico`, `Global.asax`, `packages.config`. All of these files, incidentally, are included in my csproj file.

**Comment by LizNettleship** [comment]
Experienced the same issue - trying to package a single file with no file extension and blank target. Worked round the issue by adding a target folder.
This errors
	<files>
		<file src="..\UltraOptions\ulpopt" target="" />
	</files>
But pack command works after adding target folder
	<files>
		<file src="..\UltraOptions\" target="UltraOptions" />
	</files>

**Comment by LizNettleship** [comment]
Had the same issue - trying to include a file with no extension in the name errored, but after adding a target for the file nuget pack works again
This errors:
`	<files>
		<file src="..\UltraOptions\ulpopt" target="" />
	</files>`

but this is OK
`	<files>
		<file src="..\UltraOptions\ulpopt" target="ulpopt" />
	</files>`

**Comment by nkolev92** [comment]
Related issue: https://github.com/NuGet/Home/issues/7601

I believe this is a longstanding issue of how extensionless paths are assumed to be folders first, but can't confirm without further investigation.
