### ISSUE TITLE
Broken Push: Error 400 (There must be exactly one package.)

### ISSUE THREAD

**Issue by dbeuchler** [NuGet/Home#7228]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe
NuGet version (x.x.x.xxx): 4.7.1, 4.8.1
dotnet.exe --version (if appropriate):
VS version (if appropriate): 
OS version (i.e. win10 v1607 (14393.321)): win10
Worked before? If so, with which NuGet version: 3.4.4

I am trying to push packages (with NuGet 4.7.1) to ProGet (5.1.5) with the nuget.exe. It is hosted on an linux docker container. I am always getting an error 400 (There must be exactly one package.). 

There are other people with the same [issue](https://inedo.com/support/questions/reply/4511) and the workaround is to use NuGet 3.4.4. I tried that and voila: It works like a charm. Every Push is a success.

For examination, I tried to put an nginx in front of ProGet. The interesting thing is that it now works "sometimes". The most cases are also error 400 (Bad Request) but sometimes the package is pushed. In the error logs the 400 occures because `client sent invalid chunked body,`.

I tried the same on an Windows Installation of ProGet and the same behavior can be observed.

What has changed from NuGet v3.4.4 to 3.5.0? The current workaround is to create packages with 4.7.x and push them with 3.4.4.

In [6691](https://inedo.com/support/questions/6691) a user is talking about problems with mono on the server side but the same problems are occuring on windows.

## Detailed repro steps so we can see the same problem

1. Use ProGet docker container
2. Publish Package with 

````sh
.\nuget.exe push Package.3.0.0-dev001611.nupkg "API:KEY" -Source "http://url-to-proget/nuget/FEED/" -Verbosity detailed
````
...

### Verbose Logs

```
NuGet Version: 4.8.0.5278
Pushing Package.3.0.0-dev001611.nupkg to http://url-to-proget/nuget/FEED/'...
  PUT http://url-to-proget/nuget/FEED/
  BadRequest http://url-to-proget/nuget/FEED/ 119ms
Response status code does not indicate success: 400 (There must be exactly one package.).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (There must be exactly one pac
kage.).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c.<PushPackageToServer>b__18_0(HttpResponseMessage response)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__32.MoveNext()
```

**Comment by nkolev92** [comment]
@dbeuchler There has been no changes that I'm aware of that could break this. 
We have not seen this problem on other feeds.

Just confirm what you are articulating. 
A nuget.exe 4+ push on Windows with a proget installation running on Windows fails consistently?

**Comment by PatoBeltran** [comment]
Closing this as there is no more info from the customer. Feel free to reopen if the issue persists.
