### ISSUE TITLE
NuGet.exe CryptographicException when pushing as a Local System account

### ISSUE THREAD

**Issue by winseros** [NuGet/Home#7244]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 4.7.1

OS version (i.e. win10 v1607 (14393.321)): Windows Server 2016 v1607 14393.2312

## Detailed repro steps so we can see the same problem

1. Running NuGet.exe `push` command from the Local System account on CI server
`nuget push my-package.0.0.1.nupkg -Source repo_path -ApiKey api_key`

2. See the output:
```
NuGet Version: 4.7.1.5393
Pushing my-package.0.0.1.nupkg to '<repo_path_here>'...
The system cannot find the path specified.
```

### Verbose Logs
```
System.Security.Cryptography.CryptographicException: The system cannot find the path specified.

   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at NuGet.Configuration.EncryptionUtility.DecryptString(String encryptedString)
   at NuGet.Configuration.PackageSourceCredential.get_Password()
   at NuGet.Protocol.HttpSourceAuthenticationHandler..ctor(PackageSource packageSource, HttpClientHandler clientHandler, ICredentialService credentialService)
   at NuGet.Protocol.HttpHandlerResourceV3Provider.CreateResource(PackageSource packageSource)
   at NuGet.Protocol.HttpHandlerResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<CreateHttpClientAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<EnsureHttpClientAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<GetThrottledResponse>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__32.MoveNext()
```

**Comment by nkolev92** [comment]
The root cause here is that there's an encrypted password in the nuget.config. 

The encryption context is user, so you need to user the same user that encrypted the credentials. 

https://github.com/NuGet/NuGet.Client/blob/2bc22f9a5efe44940b3381add2bfe2a4563314ee/src/NuGet.Core/NuGet.Configuration/Utility/EncryptionUtility.cs#L36

Since you're using an API key, the correct thing would be to make sure that the config with an encrypted password is not found on that machine when pushing.

**Comment by winseros** [comment]
Yep, you're right. The user `Local System` used `NuGet.config` copied from another user. But I'd expect a bit more explaining error message in this case.

**Comment by nkolev92** [comment]
This is an error message thrown by the crypto API, it'd be very difficult for the client to detect what's going on here.

**Comment by winseros** [comment]
Ok, anyway it is good the reason is clear and you pointed me a way to make everything work.
Thank you!
