### ISSUE TITLE
Unable to generate nuspec file from multi-target csproj

### ISSUE THREAD

**Issue by kenrachynski** [NuGet/Home#7273]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): whatever version is called by msbuild.exe

NuGet version (x.x.x.xxx): 4.7.1.5393 is installed.

dotnet.exe --version (if appropriate):

VS version (if appropriate): 
Microsoft (R) Build Engine version 15.8.168+ga8fba1ebd7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.8.168.64424

OS version : Windows 10 v1803 (17134.228)

Worked before? If so, with which NuGet version:
Don't know if it worked before. Previous project owner didn't say before handing over.

### Verbose Logs

I'm trying to figure out a build issue with a multi-target project. When running 
`msbuild /t:pack`, I get an NRE in a NuGet task.

```
"Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj" (pack target) (1) ->
(GenerateNuspec target) ->
  C:\Program Files\dotnet\sdk\2.1.401\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(19
9,5): error : Object reference not set to an instance of an object. [Z:\projects\company\messaging\src\main\csharp\
messaging_DotNet.csproj]

    46 Warning(s)
    1 Error(s)
```

It took me a few tries before I thought to turn on diagnostics and got the following output.
While I know know that the NRE is in the InitializePackageDependencies method, I can't see what that class is missing in the input to cause it.

```
Target "GenerateNuspec: (TargetId:791)" in file "C:\Program Files\dotnet\sdk\2.1.401\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets" from project "Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj" (target "Pack" depends on it):
Building target "GenerateNuspec" completely.
Output file "Z:\projects\company\messaging\src\main\csharp\target\csharp\Debug\messaging.1.0.0.nupkg" does not exist.
Using "PackTask" task from assembly "C:\Program Files\dotnet\sdk\2.1.401\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\..\Desktop\NuGet.Build.Tasks.Pack.dll".
Task "PackTask" (TaskId:676)
  Task Parameter:PackItem=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj (TaskId:676)
  Task Parameter:PackageVersion=3.1.12 (TaskId:676)
  Task Parameter:PackageId=messaging (TaskId:676)
  Task Parameter:Authors=company (TaskId:676)
  Task Parameter:Description=It messages! (TaskId:676)
  Task Parameter:Copyright=Copyright 2018 company Ltd. All rights reserved. (TaskId:676)
  Task Parameter:RequireLicenseAcceptance=False (TaskId:676)
  Task Parameter:ReleaseNotes=First release (TaskId:676)
  Task Parameter:Tags=message (TaskId:676)
  Task Parameter:
      BuildOutputInPackage=
          Z:\projects\company\messaging\src\main\csharp\obj\Debug\net35\messaging_DotNet.dll
                  FinalOutputPath=Z:\projects\company\messaging\src\main\csharp\target\csharp\Debug\net35\messaging_DotNet.dll
                  IsKeyOutput=true
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetBuildOutputFilesWithTfm
                  OriginalItemSpec=Z:\projects\company\messaging\src\main\csharp\obj\Debug\net35\messaging_DotNet.dll
                  TargetFramework=net35
                  TargetPath=messaging_DotNet.dll
          Z:\projects\company\messaging\src\main\csharp\obj\Debug\net35-unitysubsetv35\messaging_DotNet.dll
                  FinalOutputPath=Z:\projects\company\messaging\src\main\csharp\target\csharp\Debug\net35-unitysubsetv35\messaging_DotNet.dll
                  IsKeyOutput=true
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetBuildOutputFilesWithTfm
                  OriginalItemSpec=Z:\projects\company\messaging\src\main\csharp\obj\Debug\net35-unitysubsetv35\messaging_DotNet.dll
                  TargetFramework=net35-unitysubsetv35
                  TargetPath=messaging_DotNet.dll
          Z:\projects\company\messaging\src\main\csharp\obj\Debug\net40\messaging_DotNet.dll
                  FinalOutputPath=Z:\projects\company\messaging\src\main\csharp\target\csharp\Debug\net40\messaging_DotNet.dll
                  IsKeyOutput=true
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetBuildOutputFilesWithTfm
                  OriginalItemSpec=Z:\projects\company\messaging\src\main\csharp\obj\Debug\net40\messaging_DotNet.dll
                  TargetFramework=net40
                  TargetPath=messaging_DotNet.dll
          Z:\projects\company\messaging\src\main\csharp\obj\Debug\net45\messaging_DotNet.dll
                  FinalOutputPath=Z:\projects\company\messaging\src\main\csharp\target\csharp\Debug\net45\messaging_DotNet.dll
                  IsKeyOutput=true
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetBuildOutputFilesWithTfm
                  OriginalItemSpec=Z:\projects\company\messaging\src\main\csharp\obj\Debug\net45\messaging_DotNet.dll
                  TargetFramework=net45
                  TargetPath=messaging_DotNet.dll
          Z:\projects\company\messaging\src\main\csharp\obj\Debug\netstandard1.4\messaging_DotNet.dll
                  FinalOutputPath=Z:\projects\company\messaging\src\main\csharp\target\csharp\Debug\netstandard1.4\messaging_DotNet.dll
                  IsKeyOutput=true
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetBuildOutputFilesWithTfm
                  OriginalItemSpec=Z:\projects\company\messaging\src\main\csharp\obj\Debug\netstandard1.4\messaging_DotNet.dll
                  TargetFramework=netstandard1.4
                  TargetPath=messaging_DotNet.dll
          Z:\projects\company\messaging\src\main\csharp\obj\Debug\uap10.0\messaging_DotNet.dll
                  FinalOutputPath=Z:\projects\company\messaging\src\main\csharp\target\csharp\Debug\uap10.0\messaging_DotNet.dll
                  IsKeyOutput=true
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetBuildOutputFilesWithTfm
                  OriginalItemSpec=Z:\projects\company\messaging\src\main\csharp\obj\Debug\uap10.0\messaging_DotNet.dll
                  TargetFramework=uap10.0
                  TargetPath=messaging_DotNet.dll
          Z:\projects\company\messaging\src\main\csharp\target\csharp\Debug\uap10.0\messaging_DotNet.pri
                  FinalOutputPath=Z:\projects\company\messaging\src\main\csharp\target\csharp\Debug\uap10.0\messaging_DotNet.pri
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetBuildOutputFilesWithTfm
                  OriginalItemSpec=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  TargetFramework=uap10.0
                  TargetPath=messaging_DotNet.pri (TaskId:676)
  Task Parameter:
      TargetPathsToSymbols=
          Z:\projects\company\messaging\src\main\csharp\obj\Debug\net35\messaging_DotNet.pdb
                  FinalOutputPath=Z:\projects\company\messaging\src\main\csharp\target\csharp\Debug\net35\messaging_DotNet.pdb
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetDebugSymbolsWithTfm
                  OriginalItemSpec=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  TargetFramework=net35
                  TargetPath=messaging_DotNet.pdb
          Z:\projects\company\messaging\src\main\csharp\obj\Debug\net35-unitysubsetv35\messaging_DotNet.pdb
                  FinalOutputPath=Z:\projects\company\messaging\src\main\csharp\target\csharp\Debug\net35-unitysubsetv35\messaging_DotNet.pdb
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetDebugSymbolsWithTfm
                  OriginalItemSpec=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  TargetFramework=net35-unitysubsetv35
                  TargetPath=messaging_DotNet.pdb
          Z:\projects\company\messaging\src\main\csharp\obj\Debug\net40\messaging_DotNet.pdb
                  FinalOutputPath=Z:\projects\company\messaging\src\main\csharp\target\csharp\Debug\net40\messaging_DotNet.pdb
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetDebugSymbolsWithTfm
                  OriginalItemSpec=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  TargetFramework=net40
                  TargetPath=messaging_DotNet.pdb
          Z:\projects\company\messaging\src\main\csharp\obj\Debug\net45\messaging_DotNet.pdb
                  FinalOutputPath=Z:\projects\company\messaging\src\main\csharp\target\csharp\Debug\net45\messaging_DotNet.pdb
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetDebugSymbolsWithTfm
                  OriginalItemSpec=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  TargetFramework=net45
                  TargetPath=messaging_DotNet.pdb
          Z:\projects\company\messaging\src\main\csharp\obj\Debug\netstandard1.4\messaging_DotNet.pdb
                  FinalOutputPath=Z:\projects\company\messaging\src\main\csharp\target\csharp\Debug\netstandard1.4\messaging_DotNet.pdb
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetDebugSymbolsWithTfm
                  OriginalItemSpec=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  TargetFramework=netstandard1.4
                  TargetPath=messaging_DotNet.pdb
          Z:\projects\company\messaging\src\main\csharp\obj\Debug\uap10.0\messaging_DotNet.pdb
                  FinalOutputPath=Z:\projects\company\messaging\src\main\csharp\target\csharp\Debug\uap10.0\messaging_DotNet.pdb
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetDebugSymbolsWithTfm
                  OriginalItemSpec=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  TargetFramework=uap10.0
                  TargetPath=messaging_DotNet.pdb (TaskId:676)
  Task Parameter:
      TargetFrameworks=
          net35
          net35-unitysubsetv35
          net40
          net45
          netstandard1.4
          uap10.0 (TaskId:676)
  Task Parameter:AssemblyName=messaging_DotNet (TaskId:676)
  Task Parameter:PackageOutputPath=Z:\projects\company\messaging\src\main\csharp\target\csharp\Debug\ (TaskId:676)
  Task Parameter:
      FrameworkAssemblyReferences=
          System.Web
                  CopyLocal=false
                  FrameworkFile=true
                  FusionName=System.Web, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
                  ImageRuntime=v2.0.50727
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetFrameworkAssemblyReferences
                  OriginalItemSpec=System.Web
                  Redist=Microsoft-Windows-CLRCoreComp
                  ReferenceSourceTarget=ResolveAssemblyReference
                  ResolvedFrom={TargetFrameworkDirectory}
                  TargetFramework=net35
                  Version=2.0.0.0
          System.Core
                  CopyLocal=false
                  FrameworkFile=true
                  FusionName=System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
                  ImageRuntime=v2.0.50727
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetFrameworkAssemblyReferences
                  OriginalItemSpec=System.Core
                  Redist=Microsoft-Windows-CLRCoreComp-v3.5
                  ReferenceSourceTarget=ResolveAssemblyReference
                  ResolvedFrom={TargetFrameworkDirectory}
                  TargetFramework=net35-unitysubsetv35
                  Version=3.5.0.0
          System
                  CopyLocal=false
                  FrameworkFile=true
                  FusionName=System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
                  ImageRuntime=v2.0.50727
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetFrameworkAssemblyReferences
                  OriginalItemSpec=System
                  Redist=Microsoft-Windows-CLRCoreComp
                  ReferenceSourceTarget=ResolveAssemblyReference
                  ResolvedFrom={TargetFrameworkDirectory}
                  TargetFramework=net35-unitysubsetv35
                  Version=2.0.0.0
          System.Web
                  CopyLocal=false
                  FrameworkFile=true
                  FusionName=System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
                  ImageRuntime=v4.0.30319
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetFrameworkAssemblyReferences
                  OriginalItemSpec=System.Web
                  Redist=Microsoft-Windows-CLRCoreComp.4.0
                  ReferenceSourceTarget=ResolveAssemblyReference
                  ResolvedFrom={TargetFrameworkDirectory}
                  TargetFramework=net40
                  Version=4.0.0.0
          System.Web
                  CopyLocal=false
                  FrameworkFile=true
                  FusionName=System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
                  ImageRuntime=v4.0.30319
                  MSBuildSourceProjectFile=Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj
                  MSBuildSourceTargetName=_GetFrameworkAssemblyReferences
                  OriginalItemSpec=System.Web
                  Redist=Microsoft-Windows-CLRCoreComp.4.5
                  ReferenceSourceTarget=ResolveAssemblyReference
                  ResolvedFrom={TargetFrameworkDirectory}
                  TargetFramework=net45
                  Version=4.0.0.0 (TaskId:676)
  Task Parameter:ContinuePackingAfterGeneratingNuspec=True (TaskId:676)
  Task Parameter:NuspecOutputPath=Z:\projects\company\messaging\src\main\csharp\obj\Debug\ (TaskId:676)
  Task Parameter:IncludeBuildOutput=True (TaskId:676)
  Task Parameter:BuildOutputFolder=lib (TaskId:676)
  Task Parameter:
      ContentTargetFolders=
          content
          contentFiles (TaskId:676)
  Task Parameter:RestoreOutputPath=Z:\projects\company\messaging\src\main\csharp\obj\ (TaskId:676)
  Task Parameter:
      AllowedOutputExtensionsInPackageBuildOutputFolder=
          .dll
          .exe
          .winmd
          .json
          .pri
          .xml (TaskId:676)
  Task Parameter:
      AllowedOutputExtensionsInSymbolsPackageBuildOutputFolder=
          .pdb
          .mdb
          .dll
          .exe
          .winmd
          .json
          .pri
          .xml (TaskId:676)
  Task Parameter:NoWarn=1701;1702 (TaskId:676)
  Task Parameter:WarningsAsErrors=NU1605 (TaskId:676)
  Task Parameter:TreatWarningsAsErrors=false (TaskId:676)
C:\Program Files\dotnet\sdk\2.1.401\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(199,5): error : Object reference not set to an instance of an object. [Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj]
  System.NullReferenceException: Object reference not set to an instance of an object.
     at NuGet.Build.Tasks.Pack.PackTaskLogic.InitializePackageDependencies(LockFile assetsFile, Dictionary`2 dependenciesByFramework, ISet`1 frameworkWithSuppressedDependencies)
     at NuGet.Build.Tasks.Pack.PackTaskLogic.PopulateProjectAndPackageReferences(PackageBuilder packageBuilder, LockFile assetsFile, IDictionary`2 projectRefToVersionMap, ISet`1 frameworksWithSuppressedDependencies)
     at NuGet.Build.Tasks.Pack.PackTaskLogic.GetPackageBuilder(IPackTaskRequest`1 request)
     at NuGet.Build.Tasks.Pack.PackTask.Execute() (TaskId:676)
Done executing task "PackTask" -- FAILED. (TaskId:676)
Done building target "GenerateNuspec" in project "messaging_DotNet.csproj" -- FAILED.: (TargetId:791)
Done Building Project "Z:\projects\company\messaging\src\main\csharp\messaging_DotNet.csproj" (pack target(s)) -
- FAILED.
```

**Comment by rohit21agrawal** [comment]
can  you attach a repro project? also make sure there is an assets file as a result of restore in the obj directory

**Comment by kenrachynski** [comment]
I'm not sure I can repro this outside the actual project. The core I was trying to deal with was the inability to properly support Unity Subset v3.5 in my builds. I have since managed to get around this specific error by focusing on Unity itself.
