### ISSUE TITLE
NuGet Credentials Plugin does not work on MacOS

### ISSUE THREAD

**Issue by dtretyakov** [NuGet/Home#7293]
## Details about Problem

dotnet.exe --version: 2.1.401
OS version: Mac OS X, version 10.13.6

## Detailed repro steps so we can see the same problem

[Credentials plugin](https://github.com/NuGet/Home/issues/6486) for .NET CLI works fine on Window and Linux machines, but fails on MacOS machines with "error : Parameter name: culture".

### Verbose Logs

```
[12:33:07][Target "Restore"]                      Task Parameter:RestoreRecursive=True (TaskId:26)
[12:33:07][Target "Restore"]                      Task Parameter:HideWarningsAndErrors=False (TaskId:26)
[12:33:07][Target "Restore"]                      (in) RestoreGraphItems Count '6' (TaskId:26)
[12:33:07][Target "Restore"]                      (in) RestoreDisableParallel 'False' (TaskId:26)
[12:33:07][Target "Restore"]                      (in) RestoreNoCache 'False' (TaskId:26)
[12:33:07][Target "Restore"]                      (in) RestoreIgnoreFailedSources 'False' (TaskId:26)
[12:33:07][Target "Restore"]                      (in) RestoreRecursive 'True' (TaskId:26)
[12:33:07][Target "Restore"]                      (in) RestoreForce 'False' (TaskId:26)
[12:33:07][Target "Restore"]                      (in) HideWarningsAndErrors 'False' (TaskId:26)
[12:33:07][Target "Restore"]                      Running restore with 8 concurrent jobs. (TaskId:26)
[12:33:07][Target "Restore"]                      Reading project file /Users/user/teamcity_agents/build agent trunk/work/105d76f34d13c30e/DependencyFromTeamCityFeed.csproj. (TaskId:26)
[12:33:07][Target "Restore"]                      Restoring packages for /Users/user/teamcity_agents/build agent trunk/work/105d76f34d13c30e/DependencyFromTeamCityFeed.csproj... (TaskId:26)
[12:33:07][Target "Restore"]                      Restoring packages for .NETCoreApp,Version=v2.1... (TaskId:26)
[12:33:08][Target "Restore"]                      Using /Users/user/teamcity_agents/build agent trunk/plugins/nuget-agent/bin/credential-plugin/netcoreapp2.0/CredentialProvider.TeamCity.dll as a credential provider plugin. (TaskId:26)
[12:33:08][Target "Restore"] 12:33:08.533     1>/usr/local/share/dotnet/sdk/2.1.401/NuGet.targets(114,5): error : Argument cannot be null or empty.
[12:33:08][Target "Restore"] /usr/local/share/dotnet/sdk/2.1.401/NuGet.targets(114,5): error : Parameter name: culture
[12:33:08][Target "Restore"]                      System.ArgumentException: Argument cannot be null or empty.
[12:33:08][Target "Restore"]                      Parameter name: culture
[12:33:08][Target "Restore"]                         at NuGet.Protocol.Plugins.InitializeRequest..ctor(String clientVersion, String culture, TimeSpan requestTimeout)
[12:33:08][Target "Restore"]                         at NuGet.Protocol.Core.Types.PluginManager.InitializePluginAsync(IPlugin plugin, TimeSpan requestTimeout, CancellationToken cancellationToken)
[12:33:08][Target "Restore"]                         at NuGet.Protocol.Plugins.PluginMulticlientUtilities.DoOncePerPluginLifetimeAsync(String key, Func`1 taskFunc, CancellationToken cancellationToken)
[12:33:08][Target "Restore"]                         at NuGet.Protocol.Core.Types.PluginManager.PerformOneTimePluginInitializationAsync(IPlugin plugin, CancellationToken cancellationToken)
[12:33:08][Target "Restore"]                         at NuGet.Protocol.Core.Types.PluginManager.<>c__DisplayClass24_0.<<TryCreatePluginAsync>b__0>d.MoveNext()
[12:33:08][Target "Restore"]                      --- End of stack trace from previous location where exception was thrown ---
[12:33:08][Target "Restore"]                         at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
[12:33:08][Target "Restore"]                         at NuGet.Protocol.Core.Types.PluginManager.TryCreatePluginAsync(PluginDiscoveryResult result, OperationClaim requestedOperationClaim, PluginRequestKey requestKey, String packageSourceRepository, JObject serviceIndex, CancellationToken cancellationToken)
[12:33:08][Target "Restore"]                         at NuGet.Protocol.Core.Types.PluginManager.CreatePluginsAsync(SourceRepository source, CancellationToken cancellationToken)
[12:33:08][Target "Restore"]                         at NuGet.Protocol.Core.Types.PluginResourceProvider.TryCreate(SourceRepository source, CancellationToken cancellationToken)
[12:33:08][Target "Restore"]                         at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
[12:33:08][Target "Restore"]                         at NuGet.Protocol.PluginFindPackageByIdResourceProvider.TryCreate(SourceRepository source, CancellationToken cancellationToken)
[12:33:08][Target "Restore"]                         at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
[12:33:08][Target "Restore"]                         at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
[12:33:08][Target "Restore"]                         at NuGet.Commands.SourceRepositoryDependencyProvider.EnsureResource()
[12:33:08][Target "Restore"]                         at NuGet.Commands.SourceRepositoryDependencyProvider.FindLibraryCoreAsync(LibraryRange libraryRange, NuGetFramework targetFramework, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
[12:33:08][Target "Restore"]                         at NuGet.Commands.SourceRepositoryDependencyProvider.<>c__DisplayClass18_0.<<FindLibraryAsync>b__0>d.MoveNext()
[12:33:08][Target "Restore"]                      --- End of stack trace from previous location where exception was thrown ---
[12:33:08][Target "Restore"]                         at NuGet.Commands.SourceRepositoryDependencyProvider.FindLibraryAsync(LibraryRange libraryRange, NuGetFramework targetFramework, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
[12:33:08][Target "Restore"]                         at NuGet.DependencyResolver.ResolverUtility.<>c__DisplayClass7_1.<<FindLibraryFromSourcesAsync>b__0>d.MoveNext()
[12:33:08][Target "Restore"]                      --- End of stack trace from previous location where exception was thrown ---
[12:33:08][Target "Restore"]                         at NuGet.DependencyResolver.ResolverUtility.FindLibraryFromSourcesAsync(LibraryRange libraryRange, IEnumerable`1 providers, Func`2 action)
[12:33:08][Target "Restore"]                         at NuGet.DependencyResolver.ResolverUtility.FindLibraryByVersionAsync(LibraryRange libraryRange, NuGetFramework framework, IEnumerable`1 providers, SourceCacheContext cacheContext, ILogger logger, CancellationToken token)
[12:33:08][Target "Restore"]                         at NuGet.DependencyResolver.ResolverUtility.FindLibraryMatchAsync(LibraryRange libraryRange, NuGetFramework framework, GraphEdge`1 outerEdge, IEnumerable`1 remoteProviders, IEnumerable`1 localProviders, IEnumerable`1 projectProviders, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
[12:33:08][Target "Restore"]                         at NuGet.DependencyResolver.ResolverUtility.FindLibraryEntryAsync(LibraryRange libraryRange, NuGetFramework framework, GraphEdge`1 outerEdge, RemoteWalkContext context, CancellationToken cancellationToken)
[12:33:08][Target "Restore"]                         at NuGet.DependencyResolver.RemoteDependencyWalker.CreateGraphNode(LibraryRange libraryRange, NuGetFramework framework, String runtimeName, RuntimeGraph runtimeGraph, Func`2 predicate, GraphEdge`1 outerEdge)
[12:33:08][Target "Restore"]                         at NuGet.DependencyResolver.RemoteDependencyWalker.CreateGraphNode(LibraryRange libraryRange, NuGetFramework framework, String runtimeName, RuntimeGraph runtimeGraph, Func`2 predicate, GraphEdge`1 outerEdge)
[12:33:08][Target "Restore"]                         at NuGet.Commands.ProjectRestoreCommand.WalkDependenciesAsync(LibraryRange projectRange, NuGetFramework framework, String runtimeIdentifier, RuntimeGraph runtimeGraph, RemoteDependencyWalker walker, RemoteWalkContext context, CancellationToken token)
[12:33:08][Target "Restore"]                         at NuGet.Commands.ProjectRestoreCommand.TryRestoreAsync(LibraryRange projectRange, IEnumerable`1 frameworkRuntimePairs, NuGetv3LocalRepository userPackageFolder, IReadOnlyList`1 fallbackPackageFolders, RemoteDependencyWalker remoteWalker, RemoteWalkContext context, Boolean forceRuntimeGraphCreation, CancellationToken token, TelemetryActivity telemetryActivity)
[12:33:08][Target "Restore"]                         at NuGet.Commands.RestoreCommand.ExecuteRestoreAsync(NuGetv3LocalRepository userPackageFolder, IReadOnlyList`1 fallbackPackageFolders, RemoteWalkContext context, CancellationToken token, TelemetryActivity telemetryActivity)
[12:33:08][Target "Restore"]                         at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
[12:33:08][Target "Restore"]                         at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
[12:33:08][Target "Restore"]                         at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
[12:33:08][Target "Restore"]                         at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
[12:33:08][Target "Restore"]                         at NuGet.Commands.RestoreRunner.RunAsync(IEnumerable`1 restoreRequests, RestoreArgs restoreContext, CancellationToken token)
[12:33:08][Target "Restore"]                         at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token)
[12:33:08][Target "Restore"]                         at NuGet.Build.Tasks.RestoreTask.ExecuteAsync(ILogger log) (TaskId:26)
[12:33:08][Target "Restore"]                    Done executing task "RestoreTask" -- FAILED. (TaskId:26)
```

### Sample Project

[Plugin sources](https://github.com/JetBrains/teamcity-nuget-support/tree/master/nuget-extensions/nuget-plugin)

//cc @nkolev92, @dtivel, @rrelyea

**Comment by dtretyakov** [comment]
It looks like it duplicates #7223
