### ISSUE TITLE
nuget does not read AssemblyInfo attributes from UWP Class Library under certain targets

### ISSUE THREAD

**Issue by mpreyskurantov** [NuGet/Home#7437]
## Details about Problem

NuGet version (4.8.1.5435):
dotnet.exe --version (2.1.402):
VS version (15.8.4):
OS version (10.0.17134 N/A Build 17134):

## Detailed repro steps

Create a new "Windows Universal -> Class Library (Universal Windows)" project;
Choose the "Windows 10 Fall Creators Update (10.0; Build 16299)" values for "Target version" and "Minimum version";

ClassLibrary1.csproj:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    ...
    <AssemblyName>ClassLibrary1</AssemblyName>
    <TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
    <TargetPlatformVersion Condition=" '$(TargetPlatformVersion)' == '' ">10.0.16299.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.16299.0</TargetPlatformMinVersion>
    <MinimumVisualStudioVersion>14</MinimumVisualStudioVersion>
    <ProjectTypeGuids>{A5A43C5B-DE2A-4C0C-9213-0A381AF9435A};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    ...
  </PropertyGroup>
  ...
</Project>
```

Specify any non-default assembly attribute in the \Properties\AssemblyInfo.cs file or via the project's Properties;
Build a project in the Release configuration;
Use any of the latest client nuget.exe version (for example, the stable 4.7.1 or the newest 4.8.1 one).

- **Try to create a nupkg file with an existing nuspec:**

Call the following command:
"nuget spec ClassLibrary1.csproj -verbosity detailed"

Result:
"NuGet Version: 4.8.1.5435
Created 'ClassLibrary1.nuspec' successfully."

Call the following command:
"nuget pack ClassLibrary1.csproj -verbosity detailed"
 
Result:
"NuGet Version: 4.8.1.5435
Attempting to build package from 'ClassLibrary1.csproj'.
MSBuild auto-detection: using msbuild version '15.8.168.64424' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from '***\ClassLibrary1\ClassLibrary1\bin\Release'.
Using 'ClassLibrary1.nuspec' for metadata.
Authors is required.
Description is required.
System.Exception: Authors is required.
Description is required.
   at NuGet.Packaging.Manifest.Validate(Manifest manifest)
   at NuGet.Packaging.Manifest.ReadFrom(Stream stream, Func`2 propertyProvider, Boolean validateSchema)
   at NuGet.CommandLine.ProjectFactory.ProcessNuspec(PackageBuilder builder, String basePath)
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage()
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)"

*.nupkg is not created.

- **Try to create the nupkg file without the nuspec:**

Remove the 'ClassLibrary1.nuspec' if exists.

Call the following command:
"nuget pack ClassLibrary1.csproj -verbosity detailed"

Result:
"NuGet Version: 4.8.1.5435
Attempting to build package from 'ClassLibrary1.csproj'.
MSBuild auto-detection: using msbuild version '15.8.168.64424' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from '***\ClassLibrary1\bin\Release'.
Add file '***\ClassLibrary1\bin\Release\ClassLibrary1.dll' to package as 'lib\netcore50\ClassLibrary1.dll'
WARNING: NU5115: Description was not specified. Using 'Description'.
WARNING: NU5115: Author was not specified. Using '***'.

Id: ClassLibrary1
Version: 1.0.0
Authors: ***
Description: Description
Dependencies:

Added file '[Content_Types].xml'.
Added file '_rels/.rels'.
Added file 'ClassLibrary1.nuspec'.
Added file 'lib/netcore50/ClassLibrary1.dll'.
Added file 'package/services/metadata/core-properties/1edc966dd71b4c29856fdeeb97373828.psmdcp'.

Successfully created package '***\ClassLibrary1\ClassLibrary1.1.0.0.nupkg'."

While *.nupkg is created, the nested *.nuspec is populated with the default values instead of those specified in AssemblyInfo.cs.

**Comment by rrelyea** [comment]
Did this ever work? Which version of NuGet did this work in?

**Comment by mpreyskurantov** [comment]
We have tested this scenario with nuget.exe v3.4.4 - v4.8.1, but neither of them works. However, this works with nuget.exe v4.7.1 for all other .NET (including .NET Standard, Xamarin, etc.) project types.

It seems that this issue is only actual for a UWP Class Library under the specified "Windows 10 Fall Creators Update (10.0; Build 16299)" target:

Target version: Windows 10 Fall Creators Update (10.0; Build 16299)
Minimum version: Windows 10 Fall Creators Update (10.0; Build 16299)

ClassLibrary1.csproj:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    ...
    <AssemblyName>ClassLibrary1</AssemblyName>
    <TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
    <TargetPlatformVersion Condition=" '$(TargetPlatformVersion)' == '' ">10.0.16299.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.16299.0</TargetPlatformMinVersion>
    <MinimumVisualStudioVersion>14</MinimumVisualStudioVersion>
    <ProjectTypeGuids>{A5A43C5B-DE2A-4C0C-9213-0A381AF9435A};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    ...
  </PropertyGroup>
  ...
</Project>
```

It works for the UWP Class Library under another target, for example, with the following one, which is chosen by default when creating a new project in Visual Studio 2017:

Target version: Windows 10, version 1803 (10.0, Build 17134)
Minimum version: Windows 10 Creators Update (10.0, Build 15063)

ClassLibrary1.csproj:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    ...
    <AssemblyName>ClassLibrary1</AssemblyName>
    <TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
    <TargetPlatformVersion Condition=" '$(TargetPlatformVersion)' == '' ">10.0.17134.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.15063.0</TargetPlatformMinVersion>
    <MinimumVisualStudioVersion>14</MinimumVisualStudioVersion>
    <ProjectTypeGuids>{A5A43C5B-DE2A-4C0C-9213-0A381AF9435A};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
  </PropertyGroup>
</Project>
```

This nuget functionality is very useful for building nupkg files when most of details are specified in a shared (aka core) library and the final platform-specific details are overridden in particular platforms Class Library (like WinForms, WPF, Xamarin, etc.). However, this approach does not work for UWP.

**Comment by mpreyskurantov** [comment]
Is there any resolution regarding this issue? Not only this behavior is inconsistent with other .NET-based class libraries, but also between different UWP targets. Let me know if you need any clarification.

**Comment by assassin316** [comment]
I'm having the exact same issue. Any resolution on this problem??

**Comment by mpreyskurantov** [comment]
As a temporarily workaround, I have extracted the necessary AssemblyInfo attributes to the *.nuspec file manually and use it when building the *.nupkg:

Instead of:

`nuget pack ClassLibrary1.csproj`

Use:

`nuget pack ClassLibrary1.nuspec`

However, this requires manual synchronizing the changed AssemblyInfo attributes in the *.nuspec every time.
