### ISSUE TITLE
Nuget restore failing and timing out

### ISSUE THREAD

**Issue by JeffRausch** [NuGet/Home#7512]
This is similar to this issue: [Nuget restore failing and timing out](https://developercommunity.visualstudio.com/content/problem/324392/nuget-restore-failing-and-timing-out.html)

Nuget restore is timing out on one of our solutions after 2 minutes.  I've tried using multiple versions of Nuget and still get the same issue.   This is the only solution I've encountered this issue with, possibly because it's a very large solution (over 15,000 files spread out over 10 projects) but I don't know if that's the cause for sure.  We just converted this solution to .Net Standard 2.0, we didn't have issues before converting it and it builds fine inside Visual Studio.

Here is the full log from that task.

> 2018-11-15T14:18:34.2347393Z ==============================================================================
2018-11-15T14:18:34.2347606Z Task         : NuGet
2018-11-15T14:18:34.2348765Z Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Package Management and MyGet. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
2018-11-15T14:18:34.2349072Z Version      : 2.0.48
2018-11-15T14:18:34.2349204Z Author       : Microsoft Corporation
2018-11-15T14:18:34.2349384Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613747)
2018-11-15T14:18:34.2349572Z ==============================================================================
2018-11-15T14:18:35.1818770Z SYSTEMVSSCONNECTION exists true
2018-11-15T14:18:35.3256423Z SYSTEMVSSCONNECTION exists true
2018-11-15T14:18:35.6498908Z [command]C:\Windows\system32\chcp.com 65001
2018-11-15T14:18:35.6696322Z Active code page: 65001
2018-11-15T14:18:42.9699969Z Detected NuGet version 4.8.1.5435 / 4.8.1-rtm.5435+6007570d889b9392fb9826a6d31f99f6acf9e440
2018-11-15T14:18:42.9718803Z SYSTEMVSSCONNECTION exists true
2018-11-15T14:18:42.9820656Z [command]D:\VSTS_Worker01\_work\_tool\NuGet\4.8.1\x64\nuget.exe restore D:\VSTS_Worker01\_work\39\s\{REDACTED}.sln -Verbosity Detailed -NonInteractive -ConfigFile D:\Local.Nuget\_config\NuGet.Config
2018-11-15T14:20:43.8166637Z NuGet Version: 4.8.1.5435
2018-11-15T14:20:43.8167411Z MSBuild auto-detection: using msbuild version '15.8.169.51996' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
2018-11-15T14:20:43.8167931Z MSBuild P2P timeout [ms]: 120000
2018-11-15T14:20:43.8168763Z C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\msbuild.exe "C:\Users\Build.Manager\AppData\Local\Temp\NuGetScratch\b3ltzr4a.ot1.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\Build.Manager\AppData\Local\Temp\NuGetScratch\qemot1ex.tv1.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="D:\VSTS_Worker01\_work\_tool\NuGet\4.8.1\x64\nuget.exe" /p:RestoreSolutionDirectory="D:\VSTS_Worker01\_work\39\s\\" /p:RestoreConfigFile="D:\Local.Nuget\_config\NuGet.Config" /p:SolutionDir="D:\VSTS_Worker01\_work\39\s\\" /p:SolutionName="{REDACTED}"
2018-11-15T14:20:43.8170852Z NuGet.CommandLine.CommandLineException: MsBuild timeout out while trying to get project to project references.
2018-11-15T14:20:43.8171192Z    at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__6.MoveNext()
2018-11-15T14:20:43.8171511Z --- End of stack trace from previous location where exception was thrown ---
2018-11-15T14:20:43.8171798Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-11-15T14:20:43.8172171Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-11-15T14:20:43.8172572Z    at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__52.MoveNext()
2018-11-15T14:20:43.8172896Z --- End of stack trace from previous location where exception was thrown ---
2018-11-15T14:20:43.8173203Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-11-15T14:20:43.8173543Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-11-15T14:20:43.8173887Z    at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__47.MoveNext()
2018-11-15T14:20:43.8174219Z NuGet.CommandLine.CommandLineException: MsBuild timeout out while trying to get project to project references.
2018-11-15T14:20:43.8174563Z    at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__6.MoveNext()
2018-11-15T14:20:43.8174899Z --- End of stack trace from previous location where exception was thrown ---
2018-11-15T14:20:43.8176598Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-11-15T14:20:43.8176967Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-11-15T14:20:43.8177319Z    at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__52.MoveNext()
2018-11-15T14:20:43.8177676Z --- End of stack trace from previous location where exception was thrown ---
2018-11-15T14:20:43.8177991Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-11-15T14:20:43.8178335Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-11-15T14:20:43.8178720Z    at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__47.MoveNext()
2018-11-15T14:20:43.8179048Z --- End of stack trace from previous location where exception was thrown ---
2018-11-15T14:20:43.8179384Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-11-15T14:20:43.8179711Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-11-15T14:20:43.8180027Z    at NuGet.CommandLine.RestoreCommand.<DetermineRestoreInputsAsync>d__46.MoveNext()
2018-11-15T14:20:43.8180322Z --- End of stack trace from previous location where exception was thrown ---
2018-11-15T14:20:43.8180637Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-11-15T14:20:43.8181002Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-11-15T14:20:43.8181370Z    at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__36.MoveNext()
2018-11-15T14:20:43.8701047Z 
2018-11-15T14:20:43.8701547Z MsBuild timeout out while trying to get project to project references.
2018-11-15T14:20:43.8756762Z ##[error]The nuget command failed with exit code(1) and error(MsBuild timeout out while trying to get project to project references.)
2018-11-15T14:20:43.8766818Z ##[error]Packages failed to restore
2018-11-15T14:20:43.8780962Z ##[section]Finishing: NuGet restore

**Comment by nkolev92** [comment]
@JeffRausch 

Are you still able to reproduce this issue? 

Which versions of NuGet did you try?
Have you tried dotnet.exe?
Would you be able to provide a test solution for us? We can always do that privately. 

//cc @dtivel

**Comment by JeffRausch** [comment]
It looks like this is a NuGet issue because I was able to reproduce it by making the same NuGet call from the command line.  I was able to get it to work using dotnet.exe but the issue is that I have one Task Group that's used by all of my repositories (around 130) for building the solutions, which is a mix of .Net Framework and .Net Core/Standard.  To get around that I'm normally using the Nuget Restore and I added a variable to the Task Group to indicate to use Dotnet restore instead and I just have a custom run condition on the Nuget & Dotnet tasks to check that variable.  Then I only had to set that variable in the one repository that was having issues.  This wouldn't work though if the same repository had a .Net Framework project and also a .Net Standard/Core project that was having the issue though, I'm not sure how that could be handled.

I'll close this issue since I have a workaround.

**Comment by dtivel** [comment]
@JeffRausch, I'd love to get to the bottom of this.

If you have a repro you can share with me, I'd appreciate it.

**Comment by JeffRausch** [comment]
In the next few days I'll see if I can get a test repo together that causes the issue.  If I can I'll post it here and reopen this issue.

**Comment by devedse** [comment]
I'm currently having the same issue. But it only happens sometimes.
Please see this build for example:
https://github.com/devedse/DeveBlockStacker/actions/runs/1925065729/attempts/1

**Comment by Selinux24** [comment]
Same to me. Only happens sometimes.
https://github.com/Selinux24/Skirmish/actions/runs/4484578240/jobs/7885229147

**Comment by marcelom2s** [comment]
Same here. It's happening intermittently.

**Comment by dangspaceiq** [comment]
> Same to me. Only happens sometimes. https://github.com/Selinux24/Skirmish/actions/runs/4484578240/jobs/7885229147

Same here. In Azure pipeline it happens from time to time.

**Comment by eriktack** [comment]
Also getting this quite often last month in Azure Devops with the same error message - _MsBuild timeout out while trying to get project to project references._. Rerunning the pipeline usually works, but not always.

``` 
Starting: Restore nuget packages for solution
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.212.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents: shell
nuget restore "xxxxxxx.sln"
========================== Starting Command Output ===========================
"C:\Windows\system32\cmd.e***e" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\a658ac5d-12a2-4c70-8d95-e271b228e713.cmd""
MSBuild auto-detection: using msbuild version '17.7.2.37605' from 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin'.

MsBuild timeout out while trying to get project to project references.
##[error]Cmd.e***e e***ited with code '1'.
Finishing: Restore nuget packages for solution
```

**Comment by zivkan** [comment]
@eriktack Can you use `dotnet restore` or `msbuild -t:restore` instead of `nuget.exe restore`?  Doing so solves 2 problems:

1. The version of nuget.exe you use is never "out of sync" with the version of nuget built into msbuild (can cause problems in projects using PackageReference)
2. this "project to project timeout" can't possibly happen. The way NuGet gets project information from MSBuild is completely different, so this error simply can't happen.

If any of your projects use packagse.config, you need to use `msbuild -t:restore -p:RestorePakagesConfig=true`, which has been available since 16.5

**Comment by eriktack** [comment]
@zivkan 
Will do, looks like its working as expected, thanks.

Edit: I switched to using `msbuild /t:restore /p:RestorePackagesConfig=true` instead of nuget restore

**Comment by marcelom2s** [comment]
It has been resolved for me as well using the command above, the difference is that I had to specify the sln file:
run: msbuild ./MySolutionNameHere.sln /t:restore /p:RestorePackagesConfig=true

Thanks!
