### ISSUE TITLE
Address .NET Core 2.1+ System.IO Changes

### ISSUE THREAD

**Issue by PatoBeltran** [NuGet/Home#7588]
Starting on netcoreapp2.1 there were some changes made in System.IO that made the `*` character to be a legal character in paths.

PathValidator relied on the `*` character not being valid to do it's own validation. Since netcore has changed this behavior and it's different from net472, we need to update the PathValidator to take this into account. 

Relevant: https://github.com/dotnet/docs/issues/4483

**Comment by PatoBeltran** [comment]
Since .NET Core 2.1+ no longer attempts to pre-validate paths and `LocalFolderUtility.GetAndVerifyRootDirectory()` [relied](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Utility/LocalFolderUtility.cs#L742) on this to make sure the path was valid, we need to update the LocalFolderUtility to avoid take this into account.

**Comment by nkolev92** [comment]
Related: 
https://github.com/dotnet/coreclr/pull/16478

**Comment by nkolev92** [comment]
I also believe the priority of this is lower. 

Even though we were not **aware** of these changes, we've working fine on them since 2.1.300 (which was 2.1 runtime release we were in). 

This needs investigated and fixed, but it's not a P0. 
There's an argument to be had that being passive and listening to feedback might not be a bad approach as our code already handles most files accesses gracefully.

**Comment by nkolev92** [comment]
Related https://github.com/dotnet/corefx/issues/25873

**Comment by donnie-msft** [comment]
I believe this has been resolved. My testing shows that the * is considered an illegal character.

![Image](https://github.com/user-attachments/assets/a26c77f7-e15b-4f18-975b-a5d0aa36dcd5)

```
System.ArgumentException
  HResult=0x80070057
  Message=Illegal characters in path.
  Source=mscorlib
  StackTrace:
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.Path.GetFullPath(String path)
   at NuGet.Common.PathValidator.IsValidUncPath(String path) in C:\NuGet.Client\src\NuGet.Core\NuGet.Common\PathUtil\PathValidator.cs:line 74

  This exception was originally thrown at this call stack:
    [External Code]
    NuGet.Common.PathValidator.IsValidUncPath(string) in PathValidator.cs
```

**Comment by nkolev92** [comment]
Likely done, or no changes needed.
