### ISSUE TITLE
Nuget.exe sources add with -password "@foo" raises System.FormatException

### ISSUE THREAD

**Issue by sven-weber** [NuGet/Home#7707]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 4.9.2.5706

OS version (i.e. win10 v1607 (14393.321)): win10 v1709 16299.64

Worked before? If so, with which NuGet version:

Not to my knowledge

## Detailed repro steps so we can see the same problem

1. Open Command Line

2. Enter Command to add a new nuget source. e.g.

    nuget sources add -name foo.bar -source C:\NuGet\local -username foo -password "@Blah"

   Important: The first char of the password should be a '@'

3. The following Exception occures: 
```
Unhandled Exception: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)

   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)

   at System.String.Format(String format, Object[] args)

   at NuGet.Common.CommandLineResponseFile.ParseArgsResponseFiles(String[] args, Int32 parseArgsResponseFileRecursionDepth)

   at NuGet.CommandLine.Program.Main(String[] args)
```
### Verbose Logs

Verbose log was the same as the Exception provided under Step 3

### Sample Project

The issue does not apply to a certain project.

**Comment by gigaplex** [comment]
This worked in 4.5.1 and earlier, fails in 4.7.1 and later. I'm not sure exactly which version introduced the regression.

**Comment by mohammad-alam-asif** [comment]
1 year has gone but not been fixed yet

**Comment by Evangelink** [comment]
Telerik is recommending this syntax to access their nuget feed (see https://docs.telerik.com/aspnet-core/installation/nuget-install#setup-with-nuget-cli) which results in the error mentioned here.

**Comment by WillMarcouiller** [comment]
I have this issue and saw that @brann0n worked on a solution.  I wish to contribute fixing the issue as I'm impacted as well.  I read the contribution guidelines and found the issue is still opened and pr#3822's been closed and the bug is still there and pr's been abandonned.  I'm willing to take my chance at fixing it if anyone can guide me as to how must I follow the team guidelines.

**Comment by PhilParisot** [comment]
I just spent a ridiculous amount of time because of this bug, please fix.

**Comment by chucklu** [comment]
[brann0n](https://github.com/brann0n) try to fix this here, and did not pass the code review
https://github.com/NuGet/NuGet.Client/pull/3822#issuecomment-827411060

> Hi, thanks for the ping.
> I resigned from the company where fixing this issue would have improved daily tasks.
> With my new job i no longer have the time to work on this, although this issue still seems important to fix.
> 
> Maybe in the future someone else can pick it up were i left it.
> 
> Kind Regards!
