### ISSUE TITLE
Cannot use cli with a forward url

### ISSUE THREAD

**Issue by apobekiaris** [NuGet/Home#8067]
when I try to push to http://lab.nugetserver.expandframework.com I get

```
uGet Version: 4.9.4.5839
Pushing Xpand.VersionConverter.1.0.17.nupkg to 'http://lab.nugetserver.expandframework.com/nuget'...
  PUT http://lab.nugetserver.expandframework.com/nuget/
  Forbidden http://lab.nugetserver.expandframework.com/nuget/ 982ms
Response status code does not indicate success: 403 (Forbidden).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c.<PushPackageToServer>b__23_0(HttpResponseMessage response)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__32.MoveNext()
```

When I try to list 
```
The 'meta' start tag on line 8 position 4 does not match the end tag of 'head'. Line 9, position 3.
```

VS package manager can list fine for the same url and my nuget server works fine if I use the original address https://xpandnugetserver.azurewebsites.net/.

**Comment by rrelyea** [comment]
I'm not quite following your details.

When I navigate to: https://xpandnugetserver.azurewebsites.net/  -- I see:

> You are running NuGet.Server v3.1.2.0
> Click here to view your packages.
> 
> Repository URLs
> In the package manager settings, add the following URL to the list of Package Sources:
> https://xpandnugetserver.azurewebsites.net/nuget
> Use the command below to push packages to this feed using the NuGet command line tool (nuget.exe).
> nuget.exe push {package file} {apikey} -Source https://xpandnugetserver.azurewebsites.net/nuget
> 

Are you following those instructions?
What is going wrong when you do?

**Comment by joelverhagen** [comment]
I think the point is that if you push to a URL that redirects to something else, you get an error. If you inspect the first endpoint he mentioned, it redirects.

```
$ curl --head http://lab.nugetserver.expandframework.com/
HTTP/1.1 301 Moved Permanently
Server: nginx/1.12.2
Date: Mon, 06 May 2019 15:39:30 GMT
Content-Type: text/html; charset=utf-8
Connection: close
Location: https://xpandnugetserver.azurewebsites.net
```

However, @apobekiaris, it looks like the first URL (before the redirect) returns 403 when you `PUT` to it.

```
$ curl -vs -X PUT -d 'FAKE' http://lab.nugetserver.expandframework.com/
*   Trying 184.168.131.241...
* Connected to lab.nugetserver.expandframework.com (184.168.131.241) port 80 (#0)
> PUT / HTTP/1.1
> Host: lab.nugetserver.expandframework.com
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 4
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 4 out of 4 bytes
< HTTP/1.1 403 Forbidden
< Server: nginx/1.12.2
< Date: Mon, 06 May 2019 15:46:41 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: close
<
```

**Comment by joelverhagen** [comment]
Concerning `list`, can you provide the exact command you are using? This following command worked okay for me:

```
nuget.exe list -source http://lab.nugetserver.expandframework.com/nuget -verbosity detailed
```
