### ISSUE TITLE
.NET Core global tool package signature failure: local file header is corrupt

### ISSUE THREAD

**Issue by Aaronontheweb** [NuGet/Home#8111]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): 4.9.2

dotnet.exe --version (if appropriate): 2.2.103

VS version (if appropriate): 15.9.20+g88f5fadfbe

OS version (i.e. win10 v1607 (14393.321)): Win 10

Worked before? If so, with which NuGet version: Not with this project, but worked with other .NET Core global tools we've created with similar configurations.

## Detailed repro steps so we can see the same problem

1. Using the latest version of [SignService](https://github.com/dotnet/SignService) and a valid code signing certificate (DigiCert is our root CA in this case), build and sign the following .NET Core global tool: https://github.com/petabridge/Incrementalist - `Incrementalist.Cmd` is the .NET Core global tool produced in this case.

2. Once you have a SignService setup and have populated your credentials inside [appsettings.json](https://github.com/petabridge/Incrementalist/blob/dev/appsettings.json), run the following build command: `./build.cmd nuget SignClientUser={user} SignClientSecret={secret}`

3. Run `nuget verify Incrementalist.Cmd.nupkg -All -verbosity detailed`

You'll receive the following error message:

```
'D:\Downloads\Incrementalist.Cmd.0.1.0 (1).nupkg' is not a valid package file.
A local file header is corrupt.
System.IO.InvalidDataException: A local file header is corrupt.
   at System.IO.Compression.ZipArchiveEntry.ThrowIfNotOpenable(Boolean needToUncompress, Boolean needToLoadIntoMemory)
   at System.IO.Compression.ZipArchiveEntry.OpenInReadMode(Boolean checkOpenable)
   at NuGet.Packaging.PackageArchiveReader.GetStream(String path)
   at NuGet.Packaging.PackageReaderBase.get_NuspecReader()
   at NuGet.Packaging.PackageReaderBase.GetIdentity()
   at NuGet.Commands.VerifyCommandRunner.<VerifySignatureForPackageAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.VerifyCommandRunner.<ExecuteCommandAsync>d__3.MoveNext()
```

It's not clear why this happening - we have other .NET Core tools that we're able to sign no problem. One thing I do notice looking inside the guts of the project after we've signed it with SignService: there's no `.signature` file in the contents of the .nupkg afterwards, whereas there are in our other signed .NET Core global tools projects.

**Comment by rrelyea** [comment]
@heng-Liu @dtivel @rido-min

Started via twitter conversation including Oren and Rob

**Comment by clairernovotny** [comment]
Possibly relevant -- the signing code itself is executing on .NET Core (2.2 in this case). There are virtually no code changes from the `dev` branch to enable this, mainly just ensuring that the right `ifdef's` get used:

Here's the changes from `dev` that the signing code uses:
https://github.com/NuGet/NuGet.Client/pull/2545

**Comment by rrelyea** [comment]
I'm not interested in debugging why signing code doesn't work on .net core, yet.
We have not yet built, tested or released code that is supported for that.
We are doing that work as we speak.

Perhaps Damon can take a quick look when he gets a chance.

**Comment by glennawatson** [comment]
This one is definitely causing potentially issues with the sign client/sign service, which almost all the dot net foundation services use at the moment. We are getting corruption in the zip files. Oren custom builds his NuGet packages from his PR https://github.com/NuGet/NuGet.Client/pull/2545 for the code signing web service.
