### ISSUE TITLE
APEX tests: Tampered_InstallFromPMCForPC_FailAsync failing

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#8146]
## Details about Problem

NuGet product used: VS UI | Package Manager Console

NuGet version: 5.2.*

dotnet.exe --version (if appropriate):

VS version (if appropriate): 16.2.*

OS version (i.e. win10 v1607 (14393.321)):

Worked before? No

## Detailed repro steps so we can see the same problem

Trigger a CI Build

### Verbose Logs

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2691009&view=ms.vss-test-web.test-result-details

The assertions fails on each test case:

```
   at NuGet.Tests.Apex.RepositorySignedPackageTestCase.<Tampered_InstallFromPMCForPC_FailAsync>d__6.MoveNext() in E:\A\_work\12\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\NuGetPackageSigningTests\RepositorySignedPackageTestCase.cs:line 142
```

```
   at NuGet.Tests.Apex.RepositoryCountersignedPackageTestCase.<Tampered_InstallFromPMCForPC_FailAsync>d__6.MoveNext() in E:\A\_work\12\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\NuGetPackageSigningTests\RepositoryCountersignedPackageTestCase.cs:line 157
```

```
   at NuGet.Tests.Apex.RepositorySignedPackageTestCase.<Tampered_InstallFromPMCForPC_FailAsync>d__6.MoveNext() in E:\A\_work\12\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\NuGetPackageSigningTests\RepositorySignedPackageTestCase.cs:line 142
```

**Comment by rrelyea** [comment]
assigning to @dtivel to verify and close.

**Comment by nkolev92** [comment]
This one seems to be failing quite frequently, maybe we sohuld disable it? 
@dtivel

**Comment by dtivel** [comment]
Found the reason why tests are failing.  [This](https://github.com/NuGet/NuGet.Client/pull/2998) recent logging enhancement helped identify the problem.

When the test passes, PMC contains content like this:
```
2019-08-13T21:46:17.8115414Z           Install failed. Rolling back...
2019-08-13T21:46:17.8118784Z           Package 'TestPackage.1.0.0' does not exist in project 'TestProject'
2019-08-13T21:46:17.8120438Z           Package 'TestPackage.1.0.0' does not exist in folder 'E:\A\_work\2\s\.test\work\acdb1dcc\8ea50f2a\solution\packages'
2019-08-13T21:46:17.8125377Z           Executing nuget actions took 211.51 ms
2019-08-13T21:46:17.8126752Z           Install-Package : NU3008: Package 'TestPackage 1.0.0' from source 'E:\A\_work\2\s\.test\work\acdb1dcc\8ea50f2a\source': The package integrity check failed.
```
When the test fails, PMC contains content like this:
```
2019-08-14T23:24:07.8886594Z           Install failed. Rolling back...
2019-08-14T23:24:07.8888831Z           Package 'TestPackage.1.0.0' does not exist in project 'TestProject'
2019-08-14T23:24:07.8890292Z           Package 'TestPackage.1.0.0' does not exist in folder 'E:\A\_work\2\s\.test\work\9356badd\af6bed7b\solution\packages'
2019-08-14T23:24:07.8892325Z           Executing nuget actions took 194.14 ms
2019-08-14T23:24:07.8893308Z           Install-Package : NU3008: Package 'TestPackage 1.0.0' from source 
2019-08-14T23:24:07.8894904Z           'E:\A\_work\2\s\.test\work\9356badd\af6bed7b\source': The package integrity check 
2019-08-14T23:24:07.8896003Z           failed.
```
Somehow line breaks are being inserted, which causes [substring validation](https://github.com/NuGet/NuGet.Client/blob/e0bf732faf1d5288c4b59483ea3ee2f1bb845ad6/test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetPackageSigningTests/AuthorSignedPackageTestCase.cs#L170) to fail.

It's unclear how/why line breaks are being added.
