### ISSUE TITLE
Quote " characters in PATH cause "Illegal characters in path" failure in `nuget restore`

### ISSUE THREAD

**Issue by metathinker** [NuGet/Home#8168]
## Details about Problem

**NuGet product used:** nuget.exe installed from Chocolatey

**NuGet version:** `NuGet Version: 5.0.2.5988`

**OS version:** Windows 10 ver. 1903 [Version 10.0.18362.116]

**Visual Studio version:** 2019 Enterprise ver. 16.1.1

**Worked before? If so, with which NuGet version:** Yes, with nuget.exe 4.1.0.2450
- More precisely, I believe this regression was caused by the fix for https://github.com/NuGet/Home/issues/7621 (PR https://github.com/NuGet/NuGet.Client/pull/2687 ; commit https://github.com/NuGet/NuGet.Client/commit/21f2b07f2c2e84afd6602c6743d356dae8880c0c )

## Detailed repro steps so we can see the same problem

1. Open a cmd.exe command prompt
1. Reset your PATH environment variable using this exact command:
  `path C:\Windows\System32;C:\Windows;C:\ProgramData\chocolatey\lib\NuGet.CommandLine\tools;"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"`
  (if you have a different version or edition of VS, and/or have installed NuGet to another location, you can change appropriately)
1. `cd` to a directory containing a .sln VS solution file
1. Run `msbuild -version`
1. Run `nuget restore`

**Expected results:** Both the MSBuild and NuGet commands run to completion
**Actual results:** MSBuild successfully prints out its version, but NuGet fails with this message in red: `Illegal characters in path.`

### Verbose Logs

```
[nuget restore -verbosity detailed]
NuGet Version: 5.0.2.5988
Restoring NuGet packages for solution D:\GitHub\metathinker\console\OpenConsole.sln.
Illegal characters in path.
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGet.CommandLine.MsBuildUtility.GetMSBuild()
   at NuGet.CommandLine.MsBuildUtility.GetMsBuildToolset(String userVersion, IConsole console)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at NuGet.CommandLine.RestoreCommand.ProcessSolutionFile(String solutionFileFullPath, PackageRestoreInputs restoreInputs)
   at NuGet.CommandLine.RestoreCommand.<DetermineRestoreInputsAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__36.MoveNext()
```

**Comment by nkolev92** [comment]
@metathinker 

Note that `"` in the path is not really recommended for the path variable. The guidance is to not escape the paths.
Assembly resolution does not respect paths wrapped in quotes eitherr afaik. 

Personally I think it's ok not to fix, since this is not something all the tooling respects. 

//cc @rrelyea

**Comment by rrelyea** [comment]
While agreed, it is a bit weird to have quotes in a path, i think it is common for path intellisense in cmd to lead users to that. I'd lean towards fixing.
