### ISSUE TITLE
Test Collection Cleanup Failure: System.UnauthorizedAccessException : Access to the path 'hostfxr.dll' is denied.

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#8170]
Encounter failed tests in functional_tests_on_windows. The temporary folder created under .test folder could not be cleaned up as "Access to the path 'hostfxr.dll' is denied".

There're about 313 tests failed for the same reason. The build link is https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2716073

The error in the log is as following:
 Failed   Dotnet.Integration.Test.DotnetListPackageTests.DotnetListPackage_Succeed
##[warning]EXEC(0,0): Warning Message: 
EXEC : warning Message:  [E:\A\_work\258\s\build\build.proj]
  The previous error was converted to a warning because the task was called with ContinueOnError=true.
   [Test Collection Cleanup Failure (Dotnet Integration Tests)]: System.UnauthorizedAccessException : Access to the path 'hostfxr.dll' is denied.
  Stack Trace:
     at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
     at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
     at System.IO.Directory.Delete(String path, Boolean recursive)
     at Dotnet.Integration.Test.MsbuildIntegrationTestFixture.DeleteDirectory(String path) in E:\A\_work\258\s\test\NuGet.Core.FuncTests\Dotnet.Integration.Test\MsbuildIntegrationTestFixture.cs:line 468
     at Dotnet.Integration.Test.MsbuildIntegrationTestFixture.DeleteDirectory(String path) in E:\A\_work\258\s\test\NuGet.Core.FuncTests\Dotnet.Integration.Test\MsbuildIntegrationTestFixture.cs:line 455
     at Dotnet.Integration.Test.MsbuildIntegrationTestFixture.DeleteDirectory(String path) in E:\A\_work\258\s\test\NuGet.Core.FuncTests\Dotnet.Integration.Test\MsbuildIntegrationTestFixture.cs:line 455
     at Dotnet.Integration.Test.MsbuildIntegrationTestFixture.DeleteDirectory(String path) in E:\A\_work\258\s\test\NuGet.Core.FuncTests\Dotnet.Integration.Test\MsbuildIntegrationTestFixture.cs:line 455
     at Dotnet.Integration.Test.MsbuildIntegrationTestFixture.Dispose() in E:\A\_work\258\s\test\NuGet.Core.FuncTests\Dotnet.Integration.Test\MsbuildIntegrationTestFixture.cs:line 413

**Comment by heng-liu** [comment]
After adding retry logic in deleting hostfxr.dll, all the tests shows that the exception doesn't come up anymore.
