### ISSUE TITLE
Click Learn about Options link on the UI might crash VS, if link cannot opened

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#822]
Repro steps:

On a threshold machine, open package manager window, click "Learn About Options" link

Expected: works fine

Actual: VS crashed as the link cannot be opened.

**Comment by danliu** [comment]
+		$exception	{"This app can't be activated when UAC is disabled"}	System.Exception {System.ComponentModel.Win32Exception}

 at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo) in f:\dd\NDP\fx\src\services\monitoring\system\diagnosticts\Process.cs:line 2267
   at System.Diagnostics.Process.Start() in f:\dd\NDP\fx\src\services\monitoring\system\diagnosticts\Process.cs:line 1885
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo) in f:\dd\NDP\fx\src\services\monitoring\system\diagnosticts\Process.cs:line 2353
   at NuGet.PackageManagement.UI.UIUtility.LaunchExternalLink(Uri url)
   at NuGet.PackageManagement.UI.OptionsControl.ExecuteOpenExternalLink(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e) in f:\dd\wpf\src\Core\CSharp\System\Windows\Input\Command\CommandBinding.cs:line 206
   at System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding) in f:\dd\wpf\src\Core\CSharp\System\Windows\Input\Command\CommandManager.cs:line 597
   at System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, Object sender, RoutedEventArgs e, ICommand command, Boolean execute) in f:\dd\wpf\src\Core\CSharp\System\Windows\Input\Command\CommandManager.cs:line 752
   at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute) in f:\dd\wpf\src\Core\CSharp\System\Windows\Input\Command\CommandManager.cs:line 653
   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e) in f:\dd\wpf\src\Core\CSharp\System\Windows\Input\Command\CommandManager.cs:line 554
   at System.Windows.UIElement.OnExecutedThunk(Object sender, ExecutedRoutedEventArgs e) in f:\dd\wpf\src\Core\CSharp\System\Windows\Generated\UIElement.cs:line 2478
   at System.Windows.Input.ExecutedRoutedEventArgs.InvokeEventHandler(Delegate genericHandler, Object target) in f:\dd\wpf\src\Core\CSharp\System\Windows\Input\Command\ExecutedRoutedEventArgs.cs:line 72
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target) in f:\dd\wpf\src\Core\CSharp\System\Windows\RoutedEventArgs.cs:line 341
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs) in f:\dd\wpf\src\Core\CSharp\System\Windows\RoutedEventHandlerInfo.cs:line 78
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) in f:\dd\wpf\src\Core\CSharp\System\Windows\EventRoute.cs:line 203
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) in f:\dd\wpf\src\Core\CSharp\System\Windows\UIElement.cs:line 2352
   at System.Windows.ContentElement.RaiseEvent(RoutedEventArgs args, Boolean trusted) in f:\dd\wpf\src\Core\CSharp\System\Windows\Generated\ContentElement.cs:line 457
   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated) in f:\dd\wpf\src\Core\CSharp\System\Windows\Input\Command\RoutedCommand.cs:line 489
   at System.Windows.Input.RoutedCommand.ExecuteCore(Object parameter, IInputElement target, Boolean userInitiated) in f:\dd\wpf\src\Core\CSharp\System\Windows\Input\Command\RoutedCommand.cs:line 435
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated) in f:\dd\wpf\src\Framework\MS\Internal\Commands\CommandHelpers.cs:line 189
   at System.Windows.Documents.Hyperlink.OnClick() in f:\dd\wpf\src\Framework\System\Windows\Documents\Hyperlink.cs:line 730
   at System.Windows.Documents.Hyperlink.DispatchNavigation(Object sender) in f:\dd\wpf\src\Framework\System\Windows\Documents\Hyperlink.cs:line 1205
   at System.Windows.Documents.Hyperlink.DoUserInitiatedNavigation(Object sender) in f:\dd\wpf\src\Framework\System\Windows\Documents\Hyperlink.cs:line 1173
   at System.Windows.Documents.Hyperlink.OnMouseLeftButtonUp(Object sender, MouseButtonEventArgs e) in f:\dd\wpf\src\Framework\System\Windows\Documents\Hyperlink.cs:line 1116
   at System.Windows.Documents.Hyperlink.OnMouseLeftButtonUp(MouseButtonEventArgs e) in f:\dd\wpf\src\Framework\System\Windows\Documents\Hyperlink.cs:line 522
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e) in f:\dd\wpf\src\Core\CSharp\System\Windows\Generated\UIElement.cs:line 1133
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget) in f:\dd\wpf\src\Core\CSharp\System\Windows\Input\MouseButtonEventArgs.cs:line 123
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target) in f:\dd\wpf\src\Core\CSharp\System\Windows\RoutedEventArgs.cs:line 341
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs) in f:\dd\wpf\src\Core\CSharp\System\Windows\RoutedEventHandlerInfo.cs:line 78
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) in f:\dd\wpf\src\Core\CSharp\System\Windows\EventRoute.cs:line 203
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent) in f:\dd\wpf\src\Core\CSharp\System\Windows\UIElement.cs:line 2298
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e) in f:\dd\wpf\src\Core\CSharp\System\Windows\Generated\UIElement.cs:line 1023
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget) in f:\dd\wpf\src\Core\CSharp\System\Windows\Input\MouseButtonEventArgs.cs:line 123
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target) in f:\dd\wpf\src\Core\CSharp\System\Windows\RoutedEventArgs.cs:line 341
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs) in f:\dd\wpf\src\Core\CSharp\System\Windows\RoutedEventHandlerInfo.cs:line 78
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) in f:\dd\wpf\src\Core\CSharp\System\Windows\EventRoute.cs:line 203
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) in f:\dd\wpf\src\Core\CSharp\System\Windows\UIElement.cs:line 2352
   at System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args) in f:\dd\wpf\src\Core\CSharp\System\Windows\Generated\ContentElement.cs:line 478
   at System.Windows.Input.InputManager.ProcessStagingArea() in f:\dd\wpf\src\Core\CSharp\System\Windows\Input\InputManager.cs:line 1096
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input) in f:\dd\wpf\src\Core\CSharp\System\Windows\Input\InputManager.cs:line 709
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport) in f:\dd\wpf\src\Core\CSharp\System\Windows\Input\InputProviderSite.cs:line 126
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel) in f:\dd\wpf\src\Core\CSharp\System\Windows\Interop\HwndMouseInputProvider.cs:line 1383
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in f:\dd\wpf\src\Core\CSharp\System\Windows\Interop\HwndMouseInputProvider.cs:line 948
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in f:\dd\wpf\src\Core\CSharp\System\Windows\Interop\HwndSource.cs:line 1737
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in f:\dd\wpf\src\Shared\MS\Win32\HwndWrapper.cs:line 341
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) in f:\dd\wpf\src\Shared\MS\Win32\HwndSubclass.cs:line 494
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) in f:\dd\wpf\src\Base\MS\Internal\Threading\ExceptionWrapper.cs:line 104
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) in f:\dd\wpf\src\Base\MS\Internal\Threading\ExceptionWrapper.cs:line 37
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs) in f:\dd\wpf\src\Base\System\Windows\Threading\Dispatcher.cs:line 1445
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam) in f:\dd\wpf\src\Shared\MS\Win32\HwndSubclass.cs:line 392
