### ISSUE TITLE
Test:  flaky VS unit tests

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#8221]
12 unit tests fail on Windows like so:
```
Microsoft.VisualStudio.Services.Client.AccountManagement.AccountStorageException : There was a problem executing within the global mutex 'RegistryAccountStore'.\r\n---- System.IO.IOException : Cannot create a stable subkey under a volatile parent key.\r\n

   at Microsoft.VisualStudio.Services.Client.AccountManagement.AccountManagementUtilities.ExecuteInGlobalMutex[TResult](String globalMutexName, Func`1 func)
   at Microsoft.VisualStudio.Services.Client.AccountManagement.AccountManagementUtilities.ExecuteActionInGlobalMutex(String globalMutexName, Action action)
   at Microsoft.VisualStudio.Services.Client.AccountManagement.RegistryAccountStore..ctor(String registryRoot, String globalMutexName, String instanceName)
   at Microsoft.VisualStudio.Services.Client.AccountManagement.AccountManager..ctor(IAccountStore store, String instanceName)
   at Microsoft.VisualStudio.Services.Client.AccountManagement.AccountManager.<>c.<.cctor>b__43_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.Services.Client.AccountManagement.VSAccountProvider..ctor(TryGetSelfAsync self, TryGetSelfAsync azureRMSelf, GetWrappedItemsFromCache cacheLists, AcquireAdalTokenSilently acquireAdalTokenSilently, AcquireAdalTokenWithUI acquireAdalTokenWithUI, SessionTokenStorage sessionTokenStorage, ILogger logger)
   at Castle.Proxies.VSAccountProviderProxy..ctor(IInterceptor[] , String instanceName)
----- Inner Stack Trace -----
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternal(String subkey, RegistryKeyPermissionCheck permissionCheck, Object registrySecurityObj, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions options)
   at Microsoft.VisualStudio.Services.Client.AccountManagement.RegistryAccountStore.GetOrCreateRootKey(String subKey)
   at Microsoft.VisualStudio.Services.Client.AccountManagement.RegistryAccountStore.<.ctor>b__30_0()
   at Microsoft.VisualStudio.Services.Client.AccountManagement.AccountManagementUtilities.<>c__DisplayClass9_0.<ExecuteActionInGlobalMutex>b__0()
   at Microsoft.VisualStudio.Services.Client.AccountManagement.AccountManagementUtilities.ExecuteInGlobalMutex[TResult](String globalMutexName, Func`1 func)
```

The tests are:
```
Get_WhenEmptyKeychain_ThenPromptForCredentials
Get_WhenEmptyKeychainAndNonInteractive_ThenThrowsException
Get_WhenIsProxyRequest_ThenReturnsNull
Get_WhenMultipleAccountsInKeychainAndTenant_ThenPrompsUserForAccount
Get_WhenMultipleAccountsInKeychainNoneInTenant_ThenPromptsUserForAccount
VerifyContructorSetsId
Get_WhenMultipleAccountsInKeychainButOneInTenant_ThenReturnsThatToken
Get_WhenNullUri_ThenThrowsArgumentException
Get_WhenOneAccountInKeychain_ThenGetTokenFromAccount
Get_WhenOneAccountInKeychainWithoutAccessOnToTenantRetry_ThenPromptsUser
Get_WhenUriNotHTTPS_ThenReturnsNotApplicable
Get_WhenUriNotVSO_ThenReturnsNull
```

**Comment by nkolev92** [comment]
Closing in favor of https://github.com/NuGet/Client.Engineering/issues/268, as this is an infrastrucutre issue.
