### ISSUE TITLE
Test:  NuGet.Protocol.Tests.HttpRetryHandlerTests.HttpRetryHandler_TimesOutDownload is flaky

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#8392]
`NuGet.Protocol.Tests.HttpRetryHandlerTests.HttpRetryHandler_TimesOutDownload` is flaky.
```
NuGet.Protocol.Tests.HttpRetryHandlerTests.HttpRetryHandler_TimesOutDownload [FAIL]
  Assert.Throws() Failure
  Expected: typeof(System.IO.IOException)
  Actual:   (No exception was thrown)
  Stack Trace:
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
    C:\git\NuGet.Client\test\NuGet.Core.Tests\NuGet.Protocol.Tests\HttpSource\HttpRetryHandlerTests.cs(360,0): at NuGet.Protocol.Tests.HttpRetryHandlerTests.<HttpRetryHandler_TimesOutDownload>d__13.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by rrelyea** [comment]
Damon speculates that this may be a product bug...
