### ISSUE TITLE
Test:  package signing tests sometimes fail with 0xC0000001 (STATUS_UNSUCCESSFUL)

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#8418]
According to @bartonjs, this is tracked by https://github.com/dotnet/corefx/issues/37994.

Example from one CI test run:
```
NuGet.Packaging.Test.CertificateUtilityTests.IsSignatureAlgorithmSupported_WhenSupported_ReturnsTrue(algorithm: SHA384, expectedSignatureAlgorithmOid: "1.2.840.113549.1.1.12") [FAIL]
---- System.Security.Cryptography.CryptographicException : Unknown error "-1073741823".
---- The following constructor parameters did not have matching fixture data: CertificatesFixture fixture
Stack Trace:
          
    ----- Inner Stack Trace #1 (System.Security.Cryptography.CryptographicException) -----
        at System.Security.Cryptography.NCryptNative.SignHash[T](SafeNCryptKeyHandle key, Byte[] hash, T& paddingInfo, AsymmetricPaddingMode paddingMode, NCryptHashSigner`1 signer)
        at System.Security.Cryptography.NCryptNative.SignHashPkcs1(SafeNCryptKeyHandle key, Byte[] hash, String hashAlgorithm)
        at System.Security.Cryptography.RSACng.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
        at System.Security.Cryptography.RSA.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
        at System.Security.Cryptography.RSA.SignData(Byte[] data, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
        at System.Security.Cryptography.X509Certificates.RSAPkcs1X509SignatureGenerator.SignData(Byte[] data, HashAlgorithmName hashAlgorithm)
        at System.Security.Cryptography.X509Certificates.TbsCertificate.Sign(X509SignatureGenerator signatureGenerator, HashAlgorithmName hashAlgorithm)
        at System.Security.Cryptography.X509Certificates.CertificateRequest.Create(X500DistinguishedName issuerName, X509SignatureGenerator generator, DateTimeOffset notBefore, DateTimeOffset notAfter, Byte[] serialNumber)
        at System.Security.Cryptography.X509Certificates.CertificateRequest.CreateSelfSigned(DateTimeOffset notBefore, DateTimeOffset notAfter)
    E:\A\_work\118\s\test\TestUtilities\Test.Utility\Signing\SigningTestUtility.cs(309,0): at Test.Utility.Signing.SigningTestUtility.GenerateCertificate(String subjectName, Action`1 modifyGenerator, RSA rsa, HashAlgorithmName hashAlgorithm, RSASignaturePaddingMode paddingMode, ChainCertificateRequest chainCertificateRequest)
    E:\A\_work\118\s\test\TestUtilities\Test.Utility\Signing\SigningTestUtility.cs(212,0): at Test.Utility.Signing.SigningTestUtility.GenerateCertificate(String subjectName, Action`1 modifyGenerator, HashAlgorithmName hashAlgorithm, RSASignaturePaddingMode paddingMode, Int32 publicKeyLength, ChainCertificateRequest chainCertificateRequest)
    E:\A\_work\118\s\test\NuGet.Core.Tests\NuGet.Packaging.Test\SigningTests\CertificatesFixture.cs(36,0): at NuGet.Packaging.Test.CertificatesFixture..ctor()
    ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
          
System.AggregateException : One or more errors occurred.
---- System.Security.Cryptography.CryptographicException : Unknown error "-1073741823".
---- The following constructor parameters did not have matching fixture data: CertificatesFixture fixture
Stack Trace:
          
    ----- Inner Stack Trace #1 (System.Security.Cryptography.CryptographicException) -----
        at System.Security.Cryptography.NCryptNative.SignHash[T](SafeNCryptKeyHandle key, Byte[] hash, T& paddingInfo, AsymmetricPaddingMode paddingMode, NCryptHashSigner`1 signer)
        at System.Security.Cryptography.NCryptNative.SignHashPkcs1(SafeNCryptKeyHandle key, Byte[] hash, String hashAlgorithm)
        at System.Security.Cryptography.RSACng.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
        at System.Security.Cryptography.RSA.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
        at System.Security.Cryptography.RSA.SignData(Byte[] data, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
        at System.Security.Cryptography.X509Certificates.RSAPkcs1X509SignatureGenerator.SignData(Byte[] data, HashAlgorithmName hashAlgorithm)
        at System.Security.Cryptography.X509Certificates.TbsCertificate.Sign(X509SignatureGenerator signatureGenerator, HashAlgorithmName hashAlgorithm)
        at System.Security.Cryptography.X509Certificates.CertificateRequest.Create(X500DistinguishedName issuerName, X509SignatureGenerator generator, DateTimeOffset notBefore, DateTimeOffset notAfter, Byte[] serialNumber)
        at System.Security.Cryptography.X509Certificates.CertificateRequest.CreateSelfSigned(DateTimeOffset notBefore, DateTimeOffset notAfter)
    E:\A\_work\118\s\test\TestUtilities\Test.Utility\Signing\SigningTestUtility.cs(309,0): at Test.Utility.Signing.SigningTestUtility.GenerateCertificate(String subjectName, Action`1 modifyGenerator, RSA rsa, HashAlgorithmName hashAlgorithm, RSASignaturePaddingMode paddingMode, ChainCertificateRequest chainCertificateRequest)
    E:\A\_work\118\s\test\TestUtilities\Test.Utility\Signing\SigningTestUtility.cs(212,0): at Test.Utility.Signing.SigningTestUtility.GenerateCertificate(String subjectName, Action`1 modifyGenerator, HashAlgorithmName hashAlgorithm, RSASignaturePaddingMode paddingMode, Int32 publicKeyLength, ChainCertificateRequest chainCertificateRequest)
    E:\A\_work\118\s\test\NuGet.Core.Tests\NuGet.Packaging.Test\SigningTests\CertificatesFixture.cs(36,0): at NuGet.Packaging.Test.CertificatesFixture..ctor()
    ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```
Another example:
```
System.AggregateException : One or more errors occurred. (Unknown error (0xc0000001)) (The following constructor parameters did not have matching fixture data: CertificatesFixture fixture)
---- Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc0000001)
---- The following constructor parameters did not have matching fixture data: CertificatesFixture fixture

----- Inner Stack Trace #1 (Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException) -----
   at Internal.Cryptography.CngCommon.SignHash(SafeNCryptKeyHandle keyHandle, ReadOnlySpan`1 hash, AsymmetricPaddingMode paddingMode, Void* pPaddingInfo, Int32 estimatedSize)
   at System.Security.Cryptography.RSAImplementation.RSACng.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.Security.Cryptography.RSA.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.Security.Cryptography.RSA.SignData(Byte[] data, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.Security.Cryptography.X509Certificates.RSAPkcs1X509SignatureGenerator.SignData(Byte[] data, HashAlgorithmName hashAlgorithm)
   at System.Security.Cryptography.X509Certificates.TbsCertificate.Sign(X509SignatureGenerator signatureGenerator, HashAlgorithmName hashAlgorithm)
   at System.Security.Cryptography.X509Certificates.CertificateRequest.Create(X500DistinguishedName issuerName, X509SignatureGenerator generator, DateTimeOffset notBefore, DateTimeOffset notAfter, Byte[] serialNumber)
   at System.Security.Cryptography.X509Certificates.CertificateRequest.CreateSelfSigned(DateTimeOffset notBefore, DateTimeOffset notAfter)
   at Test.Utility.Signing.SigningTestUtility.GenerateSelfIssuedCertificate(Boolean isCa) in E:\A\_work\23\s\test\TestUtilities\Test.Utility\Signing\SigningTestUtility.cs:line 432
   at NuGet.Packaging.Test.CertificatesFixture..ctor() in E:\A\_work\23\s\test\NuGet.Core.Tests\NuGet.Packaging.Test\SigningTests\CertificatesFixture.cs:line 55
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

**Comment by kartheekp-ms** [comment]
This bug is not actionable now because of bug in Windows.

**Comment by donnie-msft** [comment]
Hit this error message today, it took 4 attempts before my build succeeded:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4662944&view=results
