### ISSUE TITLE
Test:  NetCoreTransitivePackageReferenceLimitAsync is flaky

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#8469]
Test `NetCoreTransitivePackageReferenceLimitAsync` is flaky.
```
Expected True because newtonsoft.json/9.0.1 should be installed in TestProject3, but found False.
```
Callstack:
```
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.BooleanAssertions.BeTrue(String because, Object[] becauseArgs)
   at NuGet.Tests.Apex.CommonUtility.AssertPackageInAssetsFile(VisualStudioHost visualStudio, ProjectTestExtension project, String packageName, String packageVersion, ILogger logger) in E:\A\_work\2\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\Utility\CommonUtility.cs:line 226
   at NuGet.Tests.Apex.NuGetConsoleTestCase.<NetCoreTransitivePackageReferenceLimitAsync>d__8.MoveNext() in E:\A\_work\2\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\NuGetEndToEndTests\NuGetConsoleTestCase.cs:line 236
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by donnie-msft** [comment]
@nkolev92  I'm reopening as Apex Test Run 3 of Build [6.9.0.379](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8705985) failed the same test with the same error/stack. Because of that, I believe PR5419 didn't actulaly address this particular flaky Apex test. 

```
 Failed NetCoreTransitivePackageReferenceLimitAsync (NetCoreConsoleApp) [1 m 14 s]
  Error Message:
   Expected boolean to be true because newtonsoft.json/9.0.1 should be installed in TestProject3, but found False.
  Stack Trace:
     at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.BooleanAssertions`1.BeTrue(String because, Object[] becauseArgs)
   at NuGet.Tests.Apex.CommonUtility.AssertPackageInAssetsFile(VisualStudioHost visualStudio, ProjectTestExtension project, String packageName, String packageVersion, ITestLogger logger) in D:\a\_work\1\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\Utility\CommonUtility.cs:line 252
   at NuGet.Tests.Apex.NuGetConsoleTestCase.<NetCoreTransitivePackageReferenceLimitAsync>d__7.MoveNext() in D:\a\_work\1\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\NuGetEndToEndTests\NuGetConsoleTestCase.cs:line 240
```
