### ISSUE TITLE
Operation failed as details for project could not be loaded during test discovery

### ISSUE THREAD

**Issue by HermannGruber** [NuGet/Home#8494]
I originally posted the problem in the Visual Studio forum... 
https://developercommunity.visualstudio.com/content/problem/685158/the-operation-failed-as-details-for-project-could-2.html
... and they reported that they migrated it to the "nuget forum", but I cannot find the issue in this github project. Unfortunately, I could not ask for a link to the migrated issue, since the original issue is closed for comments. So for completeness, I copypaste my error report again here:

I have a solution with a dozen projects in dotnet core 2.2 (some projects are dotnet standard). When I build or rebuild the solution, the build succeeds, but in the lowermost pane, a message appears “unexpected errors detected. See the tests output pane for details”. In the text output pane, I see the following:

[09.08.2019 9:59:07.635 Warning] Failed to parse target framework ‘,Version=’ for project ‘docker-compose’.
[09.08.2019 9:59:29.163 Error] System.InvalidOperationException: The operation failed as details for project NServicebusConnector could not be loaded.
at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAsync(DependencyGraphCacheContext context)
at NuGet.VisualStudio.VsPackageInstallerServices.<GetPackagesPathResolverAsync>d__8.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.VisualStudio.VsPackageInstallerServices.<>c__DisplayClass7_0.<<GetInstalledPackages>b__0>d.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
at Microsoft.VisualStudio.Threading.JoinableTask1.CompleteOnCurrentThread() at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func1 asyncMethod, JoinableTaskCreationOptions creationOptions)
at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages()
at Microsoft.VisualStudio.TestWindow.Controller.UnitTestExtensionDiscoverer.GetNugetAdapters()
— End of stack trace from previous location where exception was thrown —
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
[09.08.2019 9:59:29.163 Informational] ---------- Discovery started ----------
[09.08.2019 9:59:29.166 Informational] ========== Discovery skipped: All test containers are up to date ==========
[09.08.2019 9:59:29.179 Error] System.InvalidOperationException: The operation failed as details for project NServicebusConnector could not be loaded.
at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAsync(DependencyGraphCacheContext context)
at NuGet.VisualStudio.VsPackageInstallerServices.<GetPackagesPathResolverAsync>d__8.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.VisualStudio.VsPackageInstallerServices.<>c__DisplayClass7_0.<<GetInstalledPackages>b__0>d.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
at Microsoft.VisualStudio.Threading.JoinableTask1.CompleteOnCurrentThread() at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func1 asyncMethod, JoinableTaskCreationOptions creationOptions)
at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages()
at Microsoft.VisualStudio.TestWindow.Controller.UnitTestExtensionDiscoverer.GetNugetAdapters()
— End of stack trace from previous location where exception was thrown —
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
[09.08.2019 9:59:29.179 Informational] ---------- Discovery started ----------
[09.08.2019 9:59:30.459 Informational] NUnit Adapter 3.13.0.0: Test discovery starting
[09.08.2019 9:59:31.106 Informational] NUnit Adapter 3.13.0.0: Test discovery complete
[09.08.2019 9:59:31.940 Informational] NUnit Adapter 3.13.0.0: Test discovery starting
[09.08.2019 9:59:32.583 Informational] NUnit Adapter 3.13.0.0: Test discovery complete
[09.08.2019 9:59:32.614 Informational] ========== Discovery finished: 314 tests found (0:00:03,4346751) ==========
[09.08.2019 10:01:59.294 Error] System.InvalidOperationException: The operation failed as details for project NServicebusConnector could not be loaded.
at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAsync(DependencyGraphCacheContext context)
at NuGet.VisualStudio.VsPackageInstallerServices.<GetPackagesPathResolverAsync>d__8.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.VisualStudio.VsPackageInstallerServices.<>c__DisplayClass7_0.<<GetInstalledPackages>b__0>d.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
at Microsoft.VisualStudio.Threading.JoinableTask1.CompleteOnCurrentThread() at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func1 asyncMethod, JoinableTaskCreationOptions creationOptions)
at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages()
at Microsoft.VisualStudio.TestWindow.Controller.UnitTestExtensionDiscoverer.GetNugetAdapters()
— End of stack trace from previous location where exception was thrown —
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
[09.08.2019 10:01:59.294 Informational] ---------- Discovery started ----------
[09.08.2019 10:02:00.321 Informational] NUnit Adapter 3.13.0.0: Test discovery starting
[09.08.2019 10:02:01.020 Informational] NUnit Adapter 3.13.0.0: Test discovery complete
[09.08.2019 10:02:01.912 Informational] NUnit Adapter 3.13.0.0: Test discovery starting
[09.08.2019 10:02:02.552 Informational] NUnit Adapter 3.13.0.0: Test discovery complete
[09.08.2019 10:02:02.592 Informational] 
========== Discovery finished: 314 tests found (0:00:03,2978137) ==========

**Comment by rrelyea** [comment]
@zivkan  - related to an issue you were looking at, right?

**Comment by zivkan** [comment]
It looks related to #7717, but it's all about error handling/reporting. The root cause there was a bad project file. A common case is when developers try to make their projects multi-target without changing `<TargetFramework>` to `<TargetFrameworks>`.

@HermannGruber By any chance did this problem start happening after a project started trying to multi-target?  If you can't find any errors in your project file, can you share a minimal reproduction?

**Comment by HermannGruber** [comment]
Wow, many thanks for the feedback! That was really fast :-) We did not try to multi-target any of the projects. Every project has either 
`<TargetFramework>netcoreapp2.2</TargetFramework>`
or
`<TargetFramework>netstandard2.0</TargetFramework>`
I'll try to create a minimal example.

**EDIT:** I have a project docker-compose.dcproj, which has no target framework, of course.

**Comment by HermannGruber** [comment]
I can no longer reproduce the issue at the moment - I had raised the issue when running Visual Studio 16.2 or so before my holidays. After returning, I updated to the latest VS version 16.2.3. Also, I cannot guarantee that my codebase I tested with today was 100% in the same state (i.e. the same commit) as when I first reported the issue. Anyway, closing this since I no longer run into trouble.
