### ISSUE TITLE
PluginFactory is global and caches failed tasks, making in-proc retries impossible

### ISSUE THREAD

**Issue by bergbria** [NuGet/Home#8882]
## Details about Problem

As recommended by the Nuget team, I've been coding against the nuget binaries in an attempt to customize installation behavior (specifically to install a single package to the global cache without pulling in dependencies or making an extra copy, though that shouldn't matter here).

My installation tool runs on our distributed build machines, where high CPU load often causes processes to execute more slowly than normal from a wall-clock perspective. This in turn sometimes leads to timeout errors.

In our specific case, we want to retry on timeout. However, the nuget code currently makes doing this in-proc impossible.

This is one specific issue I've found in the nuget code. I cannot say whether there are more onion layers or not.

* There is only a single global ``PluginManager`` object (``private static readonly Lazy<IPluginManager> _lazy``).
* This in turn has a single ``IPluginFactory`` object  (``_pluginFactory``) that cannot be reset publicly and is not internally. Effectively, this means there is a single static global ``PluginFactory`` object.
* PluginFactory contains this field: ``ConcurrentDictionary<string, Lazy<Task<IPlugin>>> _plugins;``
    * Tasks are inserted and used from this dictionary regardless of whether they succeeded or not.
* Effectively, if any of the tasks in ``_plugins`` fails, the only way to retry them is to restart the process.

## Sample non-retryable stack trace
```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at NuGet.Protocol.Plugins.MessageDispatcher.<DispatchWithNewContextAsync>d__26`2.MoveNext()
   at NuGet.Protocol.Plugins.SymmetricHandshake.<HandshakeAsync>d__14.MoveNext()
   at NuGet.Protocol.Plugins.Connection.<ConnectAsync>d__25.MoveNext()
   at NuGet.Protocol.Plugins.PluginFactory.<CreatePluginAsync>d__6.MoveNext()
   at NuGet.Protocol.Plugins.PluginFactory.<GetOrCreateAsync>d__5.MoveNext()
   at NuGet.Protocol.Core.Types.PluginManager.<>c__DisplayClass24_0.<<TryCreatePluginAsync>b__0>d.MoveNext()
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__2`1.MoveNext()
   at NuGet.Protocol.Core.Types.PluginManager.<TryCreatePluginAsync>d__24.MoveNext()
   at NuGet.Protocol.Core.Types.PluginManager.<CreatePluginsAsync>d__22.MoveNext()
   at NuGet.Protocol.Core.Types.PluginResourceProvider.<TryCreate>d__3.MoveNext()
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
   at NuGet.Protocol.DownloadResourcePluginProvider.<TryCreate>d__1.MoveNext()
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()```

**Comment by donnie-msft** [comment]
Which version of NuGet are you using?

With https://github.com/NuGet/Home/issues/8528, some work on the plug-in was very recently completed, and specifically was focused on fixing some task cancelled errors.

**Comment by bergbria** [comment]
We're using 5.0.2 currently. I'll try updating our version to see if it reduces the hit count. Any chance of updating the NuGet.CommandLine package to the 5.5.0 preview? https://www.nuget.org/packages/NuGet.CommandLine/ only goes up to 5.3.1 for some reason.

Even if the newer code reduces the frequency of exceptions,, there is still a code issue here (assuming it's ever possible for ``NuGet.Protocol.Plugins.PluginFactory.CreatePluginAsync`` to throw an exception, which I believe it is). PluginFactory is still global in the head of the dev branch and it still caches failed tasks as shown in this code snippet.

```cs
        public async Task<IPlugin> GetOrCreateAsync(
            string filePath,
            IEnumerable<string> arguments,
            IRequestHandlers requestHandlers,
            ConnectionOptions options,
            CancellationToken sessionCancellationToken)
        {
            // ...

            var lazyTask = _plugins.GetOrAdd(
                filePath,
                (path) => new Lazy<Task<IPlugin>>(
                    () => CreatePluginAsync(filePath, arguments, requestHandlers, options, sessionCancellationToken)));

            await lazyTask.Value;
```

**Comment by donnie-msft** [comment]
NuGet.CommandLine is purposely behind other releases and will be updated soon to the recommended latest.

Pinging @nkolev92 about the Plugin.

**Comment by nkolev92** [comment]
Hey Brian, 

Why are you using the NuGet.CommandLine package? 
As @donnie-msft said, the release of it is purposely behind because publishing that package triggers auto update for folks running nuget update -self. It should follow a few weeks past the 5.4.0 release (which was last Tuesday). 

> Even if the newer code reduces the frequency of exceptions,, there is still a code issue here (assuming it's ever possible for NuGet.Protocol.Plugins.PluginFactory.CreatePluginAsync to throw an exception, which I believe it is). PluginFactory is still global in the head of the dev branch and it still caches failed tasks as shown in this code snippet.

We made a bunch of plugin reliability fixes: https://github.com/NuGet/Home/issues/8528 contains a list of them. 
NuGet.Protocol.Plugins.PluginFactory.CreatePluginAsync  can throw an exception and ideally the only time it does when it hits an unrecoverable and repeatable error :) 
The reason why you've hit it a bunch of times are the issues we've fixed. 

Can you use newer previews of the libraries? 
If that doesn't fix it we can consider other approaches. 

fyi @dtivel

**Comment by bergbria** [comment]
@nkolev92 I'm using Nuget.CommandLine because some of the Nuget classes I need to use aren't in any of the more granular packages. One example is ``NuGet.CommandLine.ExtensionLocator``. AFAICT, the options for using that are either to build against nuget.exe or to copy the source code.

I can manually download, check in, and reference a new nuget.exe, but referencing a nuget package is much nicer.

**Comment by nkolev92** [comment]
Hmm, ExtensionsLocator is specific to NuGet.exe only scenarios which is why I imagine is kept there. 

> I can manually download, check in, and reference a new nuget.exe, but referencing a nuget package is much nicer.

You can consider depending on https://dotnet.myget.org/gallery/nuget-build to get latest NuGet nupkgs. 

I'd love to understand your scenario more, maybe we can be of better help. 
Feel free to ping me, then we can post our findings here for others to benefit.

**Comment by bergbria** [comment]
Chatted offline with @nkolev92. We concluded that building against nuget.exe is the best approach for my case due to the number of dependencies (not just ExtensionsLocator) and the not-very-decoupled nature of the nuget code.

We also agreed it was reasonable to continue to globally cache failed PluginManager exceptions assuming all the illegitimate, retryable errors have been fixed. We also agreed a code comment in the global dictionary access should explicitly call out that task failures are unexpected and prevent retries.
