### ISSUE TITLE
NPM Install failed due to  ERR! code EMISSINGARG

### ISSUE THREAD

**Issue by narendra2509** [NuGet/Home#9186]
Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, please post in [NuGetGallery issues](http://github.com/nuget/nugetgallery/issues)
* If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), you are in the right place.

Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (4.5.0): also checked with other versions.

dotnet.exe --4.6.

VS version (if appropriate): 2015, 2017

OS version (i.e. win10 v1607 (14393.321)): WS 2012

Worked before? If so, with which NuGet version: worked with same version earlier.

## Detailed repro steps so we can see the same problem

1. We have latest stable nuget package for nodejs 5.3.0 and npm 3.5.2 from last 2 year and project was running fine, all of sudden we start getting issue while build with Team city, and we have used npm install in pre build event of vs 2017.
Project is running fine while we run from local and only issue comes when we build with team city.
Node js and npm version is same in teamcity server and local.

2. [Exec] IF EXIST D:\xx\buildagentxxx\work\e4360fded40c5cf8\xxxx.Web\node_modules\xxxx rd /s /q  D:\xx\buildagentxxx\work\e4360fded40c5cf8\xxxx.Web\node_modules\xxxxx &
D:\xx\buildagentxxx\work\e4360fded40c5cf8\xxxx.web\.bin\npm install
[11:49:18][Exec] npm WARN deprecated autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader
[11:49:22][Exec] npm WARN deprecated browserslist@1.1.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[11:49:24][Exec] npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[11:49:24][Exec] npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[11:49:33][Exec] npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
[11:49:35][Exec] npm WARN deprecated babel-preset-es2015@6.18.0: ­ƒÖî  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
[11:49:35][Exec] npm WARN deprecated extract-text-webpack-plugin@1.0.1: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
[11:49:35][Exec] npm WARN deprecated babel@6.5.2: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
[11:49:38][Exec] npm WARN deprecated array.prototype.flatten@1.2.1: This method has been renamed to "flat" - please use `array.prototype.flat` instead
[11:49:51][Exec] npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[11:49:53][Exec] WARN engine readable-stream@3.6.0: wanted: {"node":">= 6"} (current: {"node":"5.3.0","npm":"3.5.2"})
[11:49:55][Exec] npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[11:49:57][Exec] npm ERR! Windows_NT 6.3.9600
[11:49:57][Exec] npm ERR! argv "D:\\xx\\buildAgent5\\work\\e4360fded40c5cf8\\packages\\Node.js.5.3.0\\node.exe" "D:\\xx\\buildAgent5\\work\\e4360fded40c5cf8\\packages\\Npm.3.5.2\\node_modules\\npm\\bin\\npm-cli.js" "install"
[11:49:57][Exec] npm ERR! node v5.3.0
[11:49:57][Exec] npm ERR! npm  v3.5.2
[11:49:57][Exec] npm ERR! code EMISSINGARG
[11:49:57][Exec] 
[11:49:57][Exec] EXEC Missing required argument #1
[11:49:57][Exec] npm ERR! typeerror     at andLogAndFinish (D:\xx\buildagentxxx\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\lib\fetch-package-metadata.js:31:3)
[11:49:57][Exec] npm ERR! typeerror     at fetchPackageMetadata (D:\xx\buildAgent5\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\lib\fetch-package-metadata.js:51:22)
[11:49:57][Exec] npm ERR! typeerror     at resolveWithNewModule (D:\xx\buildagentxxx\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\lib\install\deps.js:456:12)
[11:49:57][Exec] npm ERR! typeerror     at D:\xx\buildAgent5\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\lib\install\deps.js:457:7
[11:49:57][Exec] npm ERR! typeerror     at D:\xx\buildAgent5\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\node_modules\iferr\index.js:13:50
[11:49:57][Exec] npm ERR! typeerror     at D:\xx\buildAgent5\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\lib\fetch-package-metadata.js:37:12
[11:49:57][Exec] npm ERR! typeerror     at addRequestedAndFinish (D:\xx\buildAgent5\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\lib\fetch-package-metadata.js:82:5)
[11:49:57][Exec] npm ERR! typeerror     at returnAndAddMetadata (D:\xx\buildAgent5\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\lib\fetch-package-metadata.js:117:7)
[11:49:57][Exec] npm ERR! typeerror     at pickVersionFromRegistryDocument (D:\xx\buildAgent5\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\lib\fetch-package-metadata.js:134:20)
[11:49:57][Exec] npm ERR! typeerror     at D:\xx\buildagentxxx\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\node_modules\iferr\index.js:13:50
[11:49:57][Exec] EXEC error at: 
[11:49:57][Exec] npm ERR! typeerror     <http://github.com/npm/npm/issues>
[11:49:57][Exec] npm ERR! Windows_NT 6.3.9600
[11:49:57][Exec] npm ERR! argv "D:\\xx\\buildAgent5\\work\\e4360fded40c5cf8\\packages\\Node.js.5.3.0\\node.exe" "D:\\xx\\buildAgent5\\work\\e4360fded40c5cf8\\packages\\Npm.3.5.2\\node_modules\\npm\\bin\\npm-cli.js" "install"
[11:49:57][Exec] npm ERR! node v5.3.0
[11:49:57][Exec] npm ERR! npm  v3.5.2
[11:49:57][Exec] npm ERR! code EMISSINGARG
[11:49:57][Exec] 
[11:49:57][Exec] EXEC Missing required argument #1
[11:49:57][Exec] npm ERR! typeerror     at andLogAndFinish (D:\xx\buildagentxxx\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\lib\fetch-package-metadata.js:31:3)
[11:49:57][Exec] npm ERR! typeerror     at fetchPackageMetadata (D:\xx\buildagentxxx\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\lib\fetch-package-metadata.js:51:22)
[11:49:57][Exec] npm ERR! typeerror     at resolveWithNewModule (D:\xx\buildagentxxx\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\lib\install\deps.js:456:12)
[11:49:57][Exec] npm ERR! typeerror     at D:\xx\buildagentxxx\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\lib\install\deps.js:457:7
[11:49:57][Exec] npm ERR! typeerror     at D:\xx\buildagentxxx\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\node_modules\iferr\index.js:13:50
[11:49:57][Exec] npm ERR! typeerror     at D:\xx\buildagentxxx\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\lib\fetch-package-metadata.js:37:12
[11:49:57][Exec] npm ERR! typeerror     at addRequestedAndFinish (D:\xx\buildagentxxx\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\lib\fetch-package-metadata.js:82:5)
[11:49:57][Exec] npm ERR! typeerror     at returnAndAddMetadata (D:\xx\buildagentxxx\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\lib\fetch-package-metadata.js:117:7)
[11:49:57][Exec] npm ERR! typeerror     at pickVersionFromRegistryDocument (D:\xx\buildagentxxx\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\lib\fetch-package-metadata.js:134:20)
[11:49:57][Exec] npm ERR! typeerror     at D:\xx\buildagentxxx\work\e4360fded40c5cf8\packages\Npm.3.5.2\node_modules\npm\node_modules\iferr\index.js:13:50
[11:49:57][Exec] EXEC error at: 

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

Could you please let us know how we can resolve, as most of the places we see resolution as upgrade node and npm but we are using nuget package and this is latest stable version available.

Thanks

**Comment by nkolev92** [comment]
Hey @narendra2509 
This repo houses the NuGet Package Manager issues.

**Comment by zkat** [comment]
This looks like an NPM error to me, but you're also using a very old version of the NPM CLI. Please try upgrading to a newer NPM, and if that doesn't work, file an issue in github.com/npm/cli instead.
