### ISSUE TITLE
Invalid characters error in nuget pack for nuspec file with absolute path in file target 

### ISSUE THREAD

**Issue by luminescent** [NuGet/Home#9329]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 5.4.0.6315

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)): Windows 10 Enterprise 1903 18362.720 

Worked before? If so, with which NuGet version: Yes but I don't remember the version (about a year ago)

## Detailed repro steps so we can see the same problem

1. Make a new `.nuspec` file containing a file node where the target that is an absolute path. Eg 

```
	<files>
		<file src="SomeFolder\someFile.txt" target="c:\SomeDestination\SomeFolder" />
	</files>
```

2. Run `nuget pack` on this `.nuspec` file. You will be getting an error like this (output I captured with `-Verbosity detailed`): 

```
Target path 'c:\SomeDestination\SomeFolder' contains invalid characters.
System.Exception: Target path 'c:\SomeDestination\SomeFolder' contains invalid characters.
   at NuGet.Packaging.Manifest.Validate(Manifest manifest)
   at NuGet.Packaging.Manifest.ReadFrom(Stream stream, Func`2 propertyProvider, Boolean validateSchema)
   at NuGet.Packaging.PackageBuilder.ReadManifest(Stream stream, String basePath, Func`2 propertyProvider)
   at NuGet.Packaging.PackageBuilder..ctor(String path, String basePath, Func`2 propertyProvider, Boolean includeEmptyDirectories, Boolean deterministic)
   at NuGet.Commands.PackCommandRunner.CreatePackageBuilderFromNuspec(String path)
   at NuGet.Commands.PackCommandRunner.BuildFromNuspec(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage()
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```
 
3. This used to work in previous versions of nuget. 
...

### Verbose Logs

NuGet.exe pack -verbosity detailed

```
Target path 'c:\SomeDestination\SomeFolder' contains invalid characters.
System.Exception: Target path 'c:\SomeDestination\SomeFolder' contains invalid characters.
   at NuGet.Packaging.Manifest.Validate(Manifest manifest)
   at NuGet.Packaging.Manifest.ReadFrom(Stream stream, Func`2 propertyProvider, Boolean validateSchema)
   at NuGet.Packaging.PackageBuilder.ReadManifest(Stream stream, String basePath, Func`2 propertyProvider)
   at NuGet.Packaging.PackageBuilder..ctor(String path, String basePath, Func`2 propertyProvider, Boolean includeEmptyDirectories, Boolean deterministic)
   at NuGet.Commands.PackCommandRunner.CreatePackageBuilderFromNuspec(String path)
   at NuGet.Commands.PackCommandRunner.BuildFromNuspec(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage()
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by kartheekp-ms** [comment]
This behavior is by design. If target path in `nuspec` file contains [these](https://github.com/NuGet/NuGet.Client/blob/dfe01104665d72e0331c5262a537b63fab0b8c12/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ManifestFile.cs#L21) invalid chars then `pack` will throw an exception. This has been the case since [March 2016](https://github.com/NuGet/NuGet.Client/commit/d497be9944feb8a4a10c01405607c0abc81d227c). Please let us know if this is an issue and why it impacts package creation experience so that we can plan next steps.

**Comment by luminescent** [comment]
Thank you for coming back so quickly. 

I need `:` because I am specifying a full absolute path in `target`, which must contain the drive. Like `C:\MyFolder`. 

How else can I put in a full path if the standard way of specifying it isn't allowed? Is there way of escaping the semicolon?

Does it support environment variables? Will `nuget install`, later on, be able to replace the environment value with the actual value from the system it runs on?

**Comment by rrelyea** [comment]
We don't allow NuGet packages to have any files, than when extracted, affect files elsewhere on the disk. This is a security concern.
In fact, starting with NuGet.exe 4.5 (or so), we also don't allow "..\" in packages and will prevent them from being created during extraction.
If you need to move a file from within the package to somewhere else, Using msbuild logic in a custom .targets file (in build directory) may be a way to accomplish that.

**Comment by luminescent** [comment]
Ok, thank you, I will close the issue as this is by design. 

By the way, I was able to use environment variables to achieve what you are trying to disallow. I set  this: `target="%ProgramData%\MyFolder"`. Perhaps it's worth adding `%` and `$` (for Linux) to the list of invalid characters.

**Comment by kartheekp-ms** [comment]
> By the way, I was able to use environment variables to achieve what you are trying to disallow. I set this: target="%ProgramData%\MyFolder". Perhaps it's worth adding % and $ (for Linux) to the list of invalid characters.

I am re-opening this issue to repro and fix it if required.

**Comment by kartheekp-ms** [comment]
> By the way, I was able to use environment variables to achieve what you are trying to disallow. I set this: target="%ProgramData%\MyFolder". Perhaps it's worth adding % and $ (for Linux) to the list of invalid characters.

@luminescent - I assumed based on this comment that `nuget install` command created a new file by expanding environment variable under the path `C:\ProgramData\MyFolder`. When I tried to reproduce the issue by following below steps the outcome proved that my assumption was false.

1. Created a package from nuspec file which contains a `<file>` entry as shown below
`<file src="texts\$one.txt" target="%UserProfile%" />`
1. Executed `nuget install` command.
1. Noticed new folder structure. `packagename -> %UserProfile% -> $one.txt`

Please let us know if you experienced a different behavior. If yes, it could be great if you can upload a sample solution for us to reproduce.

**Comment by kartheekp-ms** [comment]
Tried to repro it again and observed that NuGet is not extracting outside the package directory and environment variables were not expanded when normalizing paths during `install and restore`.
