### ISSUE TITLE
NuGet.exe suggests incorrect argument form "--force-evaluate" (should be "-ForceEvaluate") for NU1004

### ISSUE THREAD

**Issue by fowl2** [NuGet/Home#9365]
Looks like the help/error message is getting confused with the "dotnet restore" version of the argument.

## Repro Steps

`> nuget.exe restore`
> NU1004: The packages lock file is inconsistent with the project dependencies so restore can't be run in locked mode. Disable the RestoreLockedMode MSBuild property or pass an explicit **--force-evaluate** option to run restore to update the lock file.

Ok sure, let's try.
```
> nuget.exe restore  --force-evaluate
Unknown option: '--force-evaluate'
NuGet.Commands.CommandException: Unknown option: '--force-evaluate'
   at NuGet.CommandLine.CommandLineParser.GetPartialOptionMatch[TVal](IEnumerable`1 source, Func`2 getDisplayName, Func`2 getAltName, String option, String value)
   at NuGet.CommandLine.CommandLineParser.ExtractOptions(ICommand command, IEnumerator`1 argsEnumerator)
   at NuGet.CommandLine.CommandLineParser.ParseCommandLine(IEnumerable`1 commandLineArgs)
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

NuGet Version: 5.5.0
Platform: Windows 10 x64 10.0.17763.1098

**Comment by nkolev92** [comment]
Hey @fowl2 

We are prioritizing issues based on their customer impact and given that this is non breaking we are not sure we'll be able to get to this soon. 

We would happily consider a pull request.

**Comment by fowl2** [comment]
This is still an issue, and certainly not "completed".

NuGet Version: 7.6.0.59

eg. 

```
>nuget.exe restore
MSBuild auto-detection: using msbuild version '18.6.3.22110' from 'C:\Program Files\Microsoft Visual Studio\18\Enterprise\MSBuild\Current\Bin'.
NU1004: Mistmatch between the requestedVersion of a lock file dependency marked as CentralTransitive and the the version specified in the central package management file. Lock file version [10.0.7, ), central package management version [10.0.8, ).The packages lock file is inconsistent with the project dependencies so restore can't be run in locked mode. Disable the RestoreLockedMode MSBuild property or pass an explicit --force-evaluate option to run restore to update the lock file.
```

```
> nuget.exe restore --force-evaluate
Unknown option: '--force-evaluate'
NuGet.Commands.CommandException: Unknown option: '--force-evaluate'
   at NuGet.CommandLine.CommandLineParser.GetPartialOptionMatch[TVal](IEnumerable`1 source, Func`2 getDisplayName, Func`2 getAltName, String option, String value)
   at NuGet.CommandLine.CommandLineParser.ExtractOptions(ICommand command, IEnumerator`1 argsEnumerator)
   at NuGet.CommandLine.CommandLineParser.ParseCommandLine(IEnumerable`1 commandLineArgs)
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args, IEnvironmentVariableReader environmentVariableReader)
```
