### ISSUE TITLE
SolutionDir is not defined when running 'nuget.exe update'

### ISSUE THREAD

**Issue by orck-adrouin** [NuGet/Home#9405]
## Details about Problem
Hello,

I am trying to use `nuget.exe` to automate updating a package in a PowerShell script and I am getting an error because `SolutionDir` is undefined.   

In many project of my solution I `<import>` a file that includes properties/variables used in msbuild `targets` files.  My import statements are using the `SolutionDir` variable and because of that nuget.exe is unable to load the project file since the resolved path for the imported file is invalid.

I have a hundred projects in many solution I need to update so I cannot change the SolutionDir variable to another variable.

NuGet product used: NuGet.exe

NuGet version: 5.5.1.6542

VS version (if appropriate): 2019

OS version: Windows Server 2019 10.0.17763 Build 17763

## Detailed repro steps so we can see the same problem

1.  Create a new solution with one project

2. Add the NewtonSoft.Json package with version 12.0.1

3. Create a file build.props in the parent folder containing the solution with this content:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" InitialTargets="DetectPackageVersion" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <GlobalPropertiesLoaded>True</GlobalPropertiesLoaded>
  </PropertyGroup>
</Project>
```

4. Edit the project file and add this line:

```
<Import Project="$(SolutionDir)\..\build.props" />
```

5. Open a command prompt and use nuget.exe to update the package (adjust with correct path for solution

```
.\nuget.exe update -Verbosity detailed -Id Newtonsoft.Json -Version 12.0.3 "C:\repos\nugetbugreport\ConsoleApp3\ConsoleApp3.sln"
```
6. An error will be displayed on the screen

## Other suggested things

1. I looked at the documentation and some commands like `restore` and `pack` has a `-SolutionDirectory` argument.  Would it be possible to add it to the update command?

2. I found this issue (https://github.com/NuGet/Home/issues/4645) and from what I can gather the issue should be fixed however it still happens.

### Verbose Logs
```
.\nuget.exe update -Verbosity detailed -Id Newtonsoft.Json -Version 12.0.3 "C:\repos\nugetbugreport\ConsoleApp3\ConsoleApp3.sln"

NuGet Version: 5.5.1.6542
MSBuild auto-detection: using msbuild version '16.4.0.56107' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Scanning for projects...
The imported project "C:\build.props" was not found. Confirm that the expression in the Import declaration "\..\build.props" is correct, and that the file exists on disk.  C:\repos\nugetbugreport\ConsoleApp3\ConsoleApp3\ConsoleApp3.csproj
Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\build.props" was not found. Confirm that the expression in the Import declaration "\..\build.props" is correct, and that the file exists on disk.  C:\repos\nugetbugreport\ConsoleApp3\ConsoleApp3\ConsoleApp3.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1,T2](IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile)
```

### Sample Project

I created this repo with the steps above: https://github.com/orck-adrouin/nugetbugreport

**Comment by nkolev92** [comment]
Hey @orck-adrouin, 

Thank you for filing this issue. 
We are prioritizing issues based on their overall customer impact, and we don't think we'd be able to get to this soon. 

We'd be happy to consider a contribution.
