### ISSUE TITLE
Pushing package to nuget.org always gives internal server error 500

### ISSUE THREAD

**Issue by IvanStoychev** [NuGet/Home#9413]
## Details about Problem
I am trying to upload a new version of my package to Nuget through console.
It always encounters an internal server error 500, no matter what I do and try.
Even when status.nuget.org lists systems all green and trying different days.

NuGet product used:
NuGet.exe and dotnet.exe

NuGet version:
5.4.0

dotnet.exe version:
3.1.100

OS version:
win7

Worked before?
No.

## Detailed repro steps so we can see the same problem

1. Pull master of https://github.com/IvanStoychev/Useful.String.Extensions
2. Run following command "dotnet pack --configuration Release -o output"
3. Run one or both of the following commands:
3.1. "dotnet nuget push output/Useful.String.Extensions.1.4.2.nupkg -k yourAPIkey -s https://api.nuget.org/v3/index.json"
3.2. "nuget push output/Useful.String.Extensions.1.4.2.nupkg -Source https://api.nuget.org/v3/index.json" (you need to set your API key beforehand)

The 1.4.2 version does not exist on nuget.org, so it shouldn't be a problem. Besides, if that was the problem it should have returned a 403 error, instead of a 500 one.

I don't know if the above command will work if you are not using my API key, however I am reluctant to share it, of course.

...

### Verbose Logs

Nuget.exe -verbosity detailed output:
NuGet Version: 5.4.0.6315
Pushing Useful.String.Extensions.1.4.2.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  InternalServerError https://www.nuget.org/api/v2/package/ 2079ms
  PUT https://www.nuget.org/api/v2/package/
  InternalServerError https://www.nuget.org/api/v2/package/ 1218ms
  PUT https://www.nuget.org/api/v2/package/
  InternalServerError https://www.nuget.org/api/v2/package/ 1223ms
Response status code does not indicate success: 500 (Internal Server Error).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.Core.Types.PackageUpdateResource.EnsureSuccessStatusCode(HttpResponseMessage response, Nullable`1 codeNotToThrow, ILogger logger)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c__DisplayClass23_0.<PushPackageToServer>b__0(HttpResponseMessage response)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)

dotnet.exe -d output (--verbosity option not recogized):
Telemetry is: Enabled
info : Pushing Useful.String.Extensions.1.4.2.nupkg to 'https://www.nuget.org/api/v2/package'...
info :   PUT https://www.nuget.org/api/v2/package/
info :   InternalServerError https://www.nuget.org/api/v2/package/ 11764ms
info :   PUT https://www.nuget.org/api/v2/package/
info :   InternalServerError https://www.nuget.org/api/v2/package/ 575ms
info :   PUT https://www.nuget.org/api/v2/package/
info :   InternalServerError https://www.nuget.org/api/v2/package/ 565ms
error: Response status code does not indicate success: 500 (Internal Server Error).

### Sample Project
[Useful.String.Extensions 1.4.2.zip](https://github.com/NuGet/Home/files/4456251/Useful.String.Extensions.1.4.2.zip)

**Comment by dominoFire** [comment]
@IvanStoychev Have you tried publishing the package manually in nuget.org? If that's the case, do you  see any errors ?

**Comment by IvanStoychev** [comment]
@dominoFire , manual publishing through nuget.org works fine - never had problems with it, including after encountering these errors.

**Comment by IvanStoychev** [comment]
@dominoFire , never mind. For some reason the problem was with the API key. After creating a new one with the same permissions and glob pattern everything works fine.
