### ISSUE TITLE
[CPVM-OnBoard] Rejected transitive central dependencies should be removed from the restore graph.

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9483]
## Details about Problem

The Restore of projects opted-in CPVM fails with 'System.Collections.Generic.KeyNotFoundException" if a central dependency is part of a sub graph that was rejected. 
Using the attached example, the exception happens because the central dependency "System.IO.Compression.ZipFile" is added to the graph as dependency on NETStandard.Library >= 1.6.1.

However the NETStandard.Library >= 1.6.1 is rejected in the favor of NETStandard.Library >= 2.0.3 but the centrally marked dependency is not. 

The issue manifests as an exception:
 _System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
     at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
     at NuGet.Commands.LockFileBuilder.<>c__DisplayClass8_1.<AddCentralTransitiveDependencyGroupsForPackageReference>b__3(GraphItem`1 graphItem)
     at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
     at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
     at NuGet.Commands.LockFileBuilder.AddCentralTransitiveDependencyGroupsForPackageReference(PackageSpec project, LockFile lockFile, IEnumerable`1 targetGraphs)
     at NuGet.Commands.LockFileBuilder.CreateLockFile(LockFile previousLockFile, PackageSpec project, IEnumerable`1 targetGraphs, IReadOnlyList`1 localRepositories, RemoteWalkContext context)
     at NuGet.Commands.RestoreCommand.BuildAssetsFile(LockFile existingLockFile, PackageSpec project, IEnumerable`1 graphs, IReadOnlyList`1 localRepositories, RemoteWalkContext contextForProject)
     at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__33.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---_

## Detailed repro steps so we can see the same problem

1. Download the attached file

2. msbuild /t:restore  /v:d on the attached project.

### Sample Project

[RejectedCentralTransitiveDep.zip](https://github.com/NuGet/Home/files/4540920/RejectedCentralTransitiveDep.zip)

### Note 
Projects in the NuGet Client repo that manifests this issue:
NuGet.Core.Tests\NuGet.LibraryModel.Tests
NuGet.Core.Tests\NuGet.Shared.Tests
NuGet.Core.Tests\NuGet.Versioning.Test
NuGet.Core.Tests\NuGet.Resolver.Test

**Comment by rconard** [comment]
Updates to CPVM will only be included in the [.NET 5 SDK](https://dotnet.microsoft.com/download/visual-studio-sdks). You can target .NET Core and .NET Framework from the .NET 5 SDK.

.NET Core runtimes and SDK's are decoupled, but they share the same major and minor versions. Any version of the .NET Core or .NET 5 SDK can build any .NET Framework app or any .NET Core app that is equal to or lower than the version of the SDK installed if the relevant Targeting Pack is installed.

Currently, installing the .NET 5 SDK requires installing the [preview version of Visual Studio](https://visualstudio.microsoft.com/vs/preview/). In the future [when .NET 5 is released](https://devblogs.microsoft.com/dotnet/introducing-net-5/#:~:text=We%20intend%20to%20release%20.,Mac%20and%20Visual%20Studio%20Code.), it will be possible to install the .NET 5 SDK in the General Availability channel of Visual Studio.

**Comment by lippinio** [comment]
We tried the CPVM yesterday and we think it's a great feature. Today we have updated from dotnet sdk 3.1.100 to 3.1.401.
And we get the _System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary._ in the restore.  With the attached zip we could exactly reproduce the failure.
As I understand a pontential fix will only be included in the .NET 5 sdk is this correct?

`>C:\Program Files\dotnet\sdk\3.1.401\NuGet.targets(128,5): error : The given key 'System.IO.Compression.ZipFile' was not present in the dictionary. 
         System.Collections.Generic.KeyNotFoundException: The given key 'System.IO.Compression.ZipFile' was not present in the dictionary.
            at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
            at NuGet.Commands.LockFileBuilder.<>c__DisplayClass8_1.<AddCentralTransitiveDependencyGroupsForPackageReference>b__3(GraphItem`1 graphItem)
            at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
            at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
            at NuGet.Commands.LockFileBuilder.AddCentralTransitiveDependencyGroupsForPackageReference(PackageSpec project, LockFile lockFile, IEnumerable`1 targetGraphs)
            at NuGet.Commands.LockFileBuilder.CreateLockFile(LockFile previousLockFile, PackageSpec project, IEnumerable`1 targetGraphs, IReadOnlyList`1 localRepositories, RemoteWalkContext context)
            at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
            at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
            at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
            at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
            at NuGet.Commands.RestoreRunner.RunAsync(IEnumerable`1 restoreRequests, RestoreArgs restoreContext, CancellationToken token)
            at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token)
            at NuGet.Build.Tasks.BuildTasksUtility.RestoreAsync(DependencyGraphSpec dependencyGraphSpec, Boolean interactive, Boolean recursive, Boolean noCache, Boolean ignoreFailedSources, Boolean disableParallel, Boolean force, Boolean forceEvaluate, Boolean hideWarningsAndErrors, Boolean restorePC, Boolean cleanupAssetsForUnsupportedProjects, ILogger log, CancellationToken cancellationToken)
            at NuGet.Build.Tasks.RestoreTask.ExecuteAsync(ILogger log)`
@rconard @zivkan

**Comment by rconard** [comment]
@lippinio 
Fixes are included in the .NET 5 SDK, but you can use this build SDK to target .NET Core 3.1.401.
