### ISSUE TITLE
ValidateTimestampResponse doesn't work correctly if nonce got normalized

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#9536]
ValidateTimestampResponse doesn't work correctly if the generated nonce is different after normaliztion.
This will bring in flaky test, and also product issue: when requesting for timestamping, it may fail for nonces did not match.

Test TimestampSignatureAsync_TimestampingCountersignature_SucceedsAsync failed for:
Error message:
`NuGet.Packaging.Signing.TimestampException : The timestamp response is invalid. Nonces did not match.`

Stack trace
```
 at NuGet.Packaging.Signing.Rfc3161TimestampProvider.ValidateTimestampResponse(Byte[] nonce, Byte[] messageHash, IRfc3161TimestampToken timestampToken) in /Users/runner/runners/2.166.4/work/1/s/src/NuGet.Core/NuGet.Packaging/Signing/Timestamp/Rfc3161TimestampProvider.cs:line 211
   at NuGet.Packaging.Signing.Rfc3161TimestampProvider.GetTimestampAsync(TimestampRequest request, ILogger logger, CancellationToken token) in /Users/runner/runners/2.166.4/work/1/s/src/NuGet.Core/NuGet.Packaging/Signing/Timestamp/Rfc3161TimestampProvider.cs:line 126
   at NuGet.Packaging.Signing.Rfc3161TimestampProvider.TimestampSignatureAsync(PrimarySignature primarySignature, TimestampRequest request, ILogger logger, CancellationToken token) in /Users/runner/runners/2.166.4/work/1/s/src/NuGet.Core/NuGet.Packaging/Signing/Timestamp/Rfc3161TimestampProvider.cs:line 69
   at NuGet.Packaging.FuncTest.TimestampProviderTests.TimestampSignatureAsync_TimestampingCountersignature_SucceedsAsync() in /Users/runner/runners/2.166.4/work/1/s/test/NuGet.Core.FuncTests/NuGet.Packaging.FuncTest/SigningTests/TimestampProviderTests.cs:line 474
--- End of stack trace from previous location ---
```

**Comment by heng-liu** [comment]
Displayed the nonce sent and received:
sent:
`00-66-58-91-33-16-53-22-5C-25-55-82-AD-44-F6-59-DD-7C-6D-48-D1-64-8F-55-CC-1A-07-42-BA-AC-09-51`
received:
`66-58-91-33-16-53-22-5C-25-55-82-AD-44-F6-59-DD-7C-6D-48-D1-64-8F-55-CC-1A-07-42-BA-AC-09-51`

**Comment by heng-liu** [comment]
According to : https://github.com/dotnet/runtime/issues/36120

> Rfc3161TimestampRequest normalizes the nonce on construction, so if are using a random nonce and need the normalized form if it, use GetNonce() on the request.
