### ISSUE TITLE
[Bug Bash][Test Failure] Error “Collection was modified; enumeration operation may not execute.” occurred when first updating package in PMC for the solution included multiple projects

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9641]
## Details about Problem
NuGet version: NuGet Client Dev\5.7.0.6632
VS Version: Master\30202.132
OS: Windows-10-Enterprise-RS5
## Detailed repro steps 
1.	Create a solution with multiple projects included (e.g. C# Console Application(.NET Framework 4.7.2)).
2.	Install a package (not the latest version) with PackageReference format into every project.
3.	Open PMC and execute command “Update-package [PackageID]”.
## Expected
The package updated successfully without any error.
## Actual
Error “Collection was modified; enumeration operation may not execute.” occurred when first updating the package as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/83622972-4c910680-a5c3-11ea-844d-2f95e6876efe.png)
## Note
1. The error doesn’t repro and the package can be updated successfully when executing the same command for the second time.
2. It only repro on the solution with multiple projects, doesn’t repro on single project.
3. It only repro with PackageReference format, doesn’t repro on Packages.config format.
4. It didn't repro on 16.6 Preview2 – D16.6\29924.181 (implicit NuGet Client 5.6.0.6489).
5. It **didn't repro** on 16.5 GA (implicit NuGet Client release-5.5.x\5.5.0.6473), but **repro** on 16.6 Preview1 (implicit NuGet Client release-5.6.0-preview.1\5.6.0.6483).

**Comment by heng-liu** [comment]
Tried to repro on 16.7.0 Preview 3.0 .

First `update-pacakge` failed.
```
PM> Update-package newtonsoft.json
Restoring packages for C:\Users\henli\Source\Repos\ConsoleApp3\ClassLibrary1\ClassLibrary1.csproj...
Update-package : Collection was modified; enumeration operation may not execute.
At line:1 char:1
+ Update-package newtonsoft.json
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
 
Time Elapsed: 00:00:00.9608902
```
Second `update-pacakge` succeeded.
```
PM> Update-package newtonsoft.json
Restoring packages for C:\Users\henli\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.csproj...
Restoring packages for C:\Users\henli\Source\Repos\ConsoleApp3\ClassLibrary1\ClassLibrary1.csproj...
Committing restore...
Generating MSBuild file C:\Users\henli\Source\Repos\ConsoleApp3\ConsoleApp3\obj\ConsoleApp3.csproj.nuget.g.props.
Writing assets file to disk. Path: C:\Users\henli\Source\Repos\ConsoleApp3\ConsoleApp3\obj\project.assets.json
Restored C:\Users\henli\Source\Repos\ConsoleApp3\ConsoleApp3\ConsoleApp3.csproj (in 19 ms).
Successfully uninstalled 'Newtonsoft.Json 10.0.1' from ConsoleApp3
Successfully installed 'Newtonsoft.Json 12.0.3' to ConsoleApp3
Executing nuget actions took 266 ms
Committing restore...
Generating MSBuild file C:\Users\henli\Source\Repos\ConsoleApp3\ClassLibrary1\obj\ClassLibrary1.csproj.nuget.g.props.
Writing assets file to disk. Path: C:\Users\henli\Source\Repos\ConsoleApp3\ClassLibrary1\obj\project.assets.json
Restored C:\Users\henli\Source\Repos\ConsoleApp3\ClassLibrary1\ClassLibrary1.csproj (in 9 ms).
Successfully uninstalled 'Newtonsoft.Json 10.0.1' from ClassLibrary1
Successfully installed 'Newtonsoft.Json 12.0.3' to ClassLibrary1
Executing nuget actions took 260 ms
Time Elapsed: 00:00:01.0471450
```

**Comment by zivkan** [comment]
Stack trace
```text
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewUpdatePackagesForBuildIntegratedAsync>d__59.MoveNext() in C:\src\NuGet.Client\src\NuGet.Core\NuGet.PackageManagement\NuGetPackageManager.cs:line 901
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.PackageManagement.NuGetPackageManager.<>c__DisplayClass56_2.<<PreviewUpdatePackagesAsync>b__1>d.MoveNext() in C:\src\NuGet.Client\src\NuGet.Core\NuGet.PackageManagement\NuGetPackageManager.cs:line 693
```
