### ISSUE TITLE
Test: ClientCert tests are flaky

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#9684]
The HTTPS Client Certificates feature added multiple tests that cause frequent problems on Mac and Linux.  Our hypothesis that it's the dynamic generate of certificates that causes the problem.

Impacted tests:
* `test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XPlatClientCertTests.cs`
  * `ClientCertAddCommand_Fail_StoreCertificateNotExist`
  * `ClientCertAddCommand_Success_FileCertificateAbsolute`
  * `ClientCertAddCommand_Success_FileCertificateNotExistForce`
  * `ClientCertAddCommand_Success_FileCertificateRelative`
  * `ClientCertAddCommand_Success_StoreCertificate`
  * `ClientCertListCommand_Success_NotEmptyList`
  * `ClientCertRemoveCommand_Success_ItemCertificate`
  * `ClientCertUpdateCommand_Success_FileCertificateForce`
  * `ClientCertUpdatedCommand_Fail_FileCertificateNotExist`
  * `ClientCertUpdatedCommand_Fail_StoreCertificateNotExist`
* `test/NuGet.Core.Tests/NuGet.Protocol.Tests/HttpSource/ClientCertificatesTests.cs`
  * `EnsurePackageSourceClientCertificatesForwardedToV3HttpClientHandler`

**Comment by jeffkl** [comment]
Had another failure after I added diagnostics.  The test is clearly creating the certificate and installing it into the User store.


## Error message
```
Expected if (!string.IsNullOrEmpty(expectedOutputMessage)){result.Output to be 0 because nuget.exe should have succeeded with exit code 0 but returned exit code 1
Output:

Errors:
Certificate for the package source 'Contoso-5ce69af91a364d1391cf57a8b9bf9f0b' was not found in 'CurrentUser.My' storage by 'IssuerName' criteria with 'Contoso-5ce69af91a364d1391cf57a8b9bf9f0b' value.
, but found 1 (difference of 1).
```

## Stack trace
```
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Numeric.NumericAssertions`2.Be(T expected, String because, Object[] becauseArgs)
   at NuGet.CommandLine.Test.Util.VerifyResultSuccess(CommandRunnerResult result, String expectedOutputMessage, String extraDebugInfo) in D:\a\_work\1\s\test\NuGet.Clients.Tests\NuGet.CommandLine.Test\Util.cs:line 646
   at NuGet.CommandLine.Test.NuGetClientCertCommandTests.ClientCertAddCommand_Success_StoreCertificate() in D:\a\_work\1\s\test\NuGet.Clients.Tests\NuGet.CommandLine.Test\NuGetClientCertCommandTests.cs:line 298
```

## Test Output
```
Created certificate cn=Contoso-5ce69af91a364d1391cf57a8b9bf9f0b
Added certificate CN=Contoso-5ce69af91a364d1391cf57a8b9bf9f0b to store CurrentUser\My
Installed Certificates:
  CN=Contoso-5ce69af91a364d1391cf57a8b9bf9f0b
  CN=localhost
  CN=1es-hostedpools.default.microsoft.com
Running command D:\a\_work\1\s\test\NuGet.Clients.Tests\NuGet.CommandLine.Test\bin\release\net472\NuGet\NuGet.exe "client-certs" "add" -ConfigFile "D:\a\_work\1\s\.test\work\94c39d4d\ccec9e32\NuGet.config" -PackageSource "Contoso-5ce69af91a364d1391cf57a8b9bf9f0b" -StoreLocation "CurrentUser" -StoreName "My" -FindBy "IssuerName" -FindValue "Contoso-5ce69af91a364d1391cf57a8b9bf9f0b"
Exit code: 1
Output:

Errors:
Certificate for the package source 'Contoso-5ce69af91a364d1391cf57a8b9bf9f0b' was not found in 'CurrentUser.My' storage by 'IssuerName' criteria with 'Contoso-5ce69af91a364d1391cf57a8b9bf9f0b' value.

Installed Certificates:
  CN=localhost
  CN=1es-hostedpools.default.microsoft.com
```
