### ISSUE TITLE
Test:  PM UI Apex tests are flaky (UninstallPackageFromUI and so on)

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#9701]
The following  5 PM UI Apex tests are flaky recently:
```
SearchPackageFromUI
InstallPackageFromUI
InstallPackageToProjectsFromUI
UninstallPackageFromUI
UpdatePackageFromUI
```

UninstallPackageFromUI
Error message:
`System.TimeoutException : Timed out after 00:00:10 waiting for C:\school\ApexSolutions\TestCase2478\TestProject\packages.config did not exist within 00:00:10.`
Stack trace
```
   at Omni.Common.Waiter.ThrowIfExpired(String waitCondition)
   at Omni.Common.WaitFor.IsTrue(Func`1 predicate, TimeSpan timeout, Nullable`1 interval, String conditionDescription)
   at NuGet.Tests.Apex.NuGetUITestCase.WaitForFileExists(FileInfo file) in E:\A\_work\1\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\NuGetEndToEndTests\NuGetUITestCase.cs:line 161
   at NuGet.Tests.Apex.NuGetUITestCase.UninstallPackageFromUI() in E:\A\_work\1\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\NuGetEndToEndTests\NuGetUITestCase.cs:line 113
```

InstallPackageToProjectsFromUI 
```
 NuGet.Tests.Apex.NuGetUITestCase.InstallPackageToProjectsFromUI [FAIL]
        Expected True because newtonsoft.json/9.0.1 should be installed in TestProject, but found False.
        Stack Trace:
             at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
             at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
             at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
             at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
             at FluentAssertions.Primitives.BooleanAssertions.BeTrue(String because, Object[] becauseArgs)
          E:\A\_work\1\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\Utility\CommonUtility.cs(240,0): at NuGet.Tests.Apex.CommonUtility.AssertPackageInPackagesConfig(VisualStudioHost visualStudio, ProjectTestExtension project, String packageName, String packageVersion, ILogger logger)
          E:\A\_work\1\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\NuGetEndToEndTests\NuGetUITestCase.cs(93,0): at NuGet.Tests.Apex.NuGetUITestCase.InstallPackageToProjectsFromUI()
        Output:
          [test] info: Checking project newtonsoft.json
          [test] info: Exists: False
          [test] info: Package Manager Output Window Pane contents:  Added package 'Newtonsoft.Json.9.0.1' to folder 'C:\school\ApexSolutions\TestCase4302\packages'
          Added package 'Newtonsoft.Json.9.0.1' to 'packages.config'
          Executing script file 'C:\school\ApexSolutions\TestCase4302\packages\Newtonsoft.Json.9.0.1\tools\install.ps1'...
          Successfully installed 'Newtonsoft.Json 9.0.1' to NuProject
```

**Comment by zivkan** [comment]
@donnie-msft unskipped these tests a few weeks ago.
