### ISSUE TITLE
[Test Failure][Signing] ‘Value cannot be null’ error occurs when installing signed package with certificate is not trusted

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#9728]
## Details about Problem

**NuGet Version:** NuGet Client Dev\5.7.0.6677
**VS Version:** Master\30226.129
**OS Version:** Windows-10-Enterprise-RS5

## Installation steps: 
1.  Install VS Master\30226.129 from: [https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3846424&view=ms.vss-build-web.run-extensions-tab](url)
2.  Install NuGet Client: [\\\ddfiles\Drops\NuGet\Drops\CI\NuGet.Client\Dev\5.7.0.6677\artifacts\VS15\NuGet.Tools.vsix](url)

## Repro steps: 

1. Create a .NET Framework package for testing.
2. Create a new test certificate:  .\CreateTestCertificate.ps1.
3. Sign a package:  NuGet.exe sign <<PackageFilePath>PackageFilePath> -CertificatePath <<PackageFilePath>PfxFilePath>.
4. Open Package Manager UI, install the package with **package.config format** into a project.

## Expected:
There was no error and the package can be installed into the project.

## Actual:
‘Value cannot be null’ error occurs when installing package as below screenshot.
![bug0629](https://user-images.githubusercontent.com/20632775/85994208-114eef80-ba2a-11ea-9631-bcc78ad0a014.png)

## Notes: 
1. The issue didn’t repro on .Net Core project.
2. The issue didn’t repro on Master\30223.54 + NuGet Client Dev\5.7.0.6670.
3. The issue didn’t repro on Master\30226.129 with implicit NuGet Client Dev\5.7.0.6665.
4. The issue also repro when using other certificate **except for** .\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority.

**Comment by donnie-msft** [comment]
@heng-liu, does this look related to cert work, or perhaps a bug in the UI?

**Comment by heng-liu** [comment]
@donnie-msft I'm not sure yet. 
But the NuGet Client Dev\5.7.0.6670(it didn't repro on this build). is the one we just inserted into dotnet. After that, we only had some infrastructure changes.

**Comment by heng-liu** [comment]
Repro successfully with the exact version of VS and VSIX.
Install package failed when using PM UI.
Output from PM UI:
```
Attempting to gather dependency information for package 'TestPackage.1.0.0' with respect to project 'ClassLibrary1', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 1.5 sec
Attempting to resolve dependencies for package 'TestPackage.1.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'TestPackage.1.0.0'
Resolved actions to install package 'TestPackage.1.0.0'
System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at NuGet.Protocol.PackageMetadataResourceV3.<DeserializeStreamDataAsync>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.PackageMetadataResourceV3.<>c__DisplayClass9_0.<<LoadRegistrationIndexAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.Protocol.HttpSource.<>c__DisplayClass14_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<GetAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.PackageMetadataResourceV3.<LoadRegistrationIndexAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.PackageMetadataResourceV3.<GetMetadataAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.PackageMetadataResourceV3.<GetMetadataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<GetPackageMetadataAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.TaskCombinators.<>c__DisplayClass1_0`2.<<ThrottledAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.TaskCombinators.<ThrottledAsync>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<GetPackageMetadataAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<CheckLicenseAcceptanceAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<>c__DisplayClass12_0.<<PerformActionImplAsync>b__0>d.MoveNext()
Time Elapsed: 00:00:02.4048004
```

**Comment by heng-liu** [comment]
Tried to install the same package in PM console. And it succeeded.
```
PM> Install-Package TestPackage 


Attempting to gather dependency information for package 'TestPackage.1.0.0' with respect to project 'ClassLibrary1', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 1 ms
Attempting to resolve dependencies for package 'TestPackage.1.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'TestPackage.1.0.0'
Resolved actions to install package 'TestPackage.1.0.0'
Retrieving package 'TestPackage 1.0.0' from 'signedPackage'.
Adding package 'TestPackage.1.0.0' to folder 'C:\Users\henli\source\repos\ClassLibrary1\packages'
NU3027: Package 'TestPackage 1.0.0' from source 'C:\Users\henli\Desktop\TestCertGenerator\signedPackage': The signature should be timestamped to enable long-term signature validity after the certificate has expired.
NU3018: Package 'TestPackage 1.0.0' from source 'C:\Users\henli\Desktop\TestCertGenerator\signedPackage': The author primary signature found a chain building issue: UntrustedRoot: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
Added package 'TestPackage.1.0.0' to folder 'C:\Users\henli\source\repos\ClassLibrary1\packages'
Added package 'TestPackage.1.0.0' to 'packages.config'
Successfully installed 'TestPackage 1.0.0' to ClassLibrary1
Executing nuget actions took 1.77 sec
Time Elapsed: 00:00:02.0838878
```

**Comment by heng-liu** [comment]
It doesn't matter whether the package is signed or not.
We can repro with a package in a local source but it doesn't exist in a http source.

**Comment by heng-liu** [comment]
Sorry,I could not repro with usigned package and signed package anymore.
(I did clear the output window and nuget local cache everytime, but not sure how did that happen)
So it's only related to package signed with untrusted signer.
