### ISSUE TITLE
Exception thrown when trying to setapikey that starts with the @ character.

### ISSUE THREAD

**Issue by bbobrian** [NuGet/Home#9744]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): nuget.exe

NuGet version (x.x.x.xxx): 5.6.0.6591

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)): win10 v1909 (18363.900)

Worked before? If so, with which NuGet version: 3.5.0

## Detailed repro steps so we can see the same problem

1. nuget setapikey @myapikey -source http://private.nuget.local

### Verbose Logs
Unhandled Exception: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at NuGet.Common.CommandLineResponseFile.ParseArgsResponseFiles(String[] args, Int32 parseArgsResponseFileRecursionDepth)
   at NuGet.CommandLine.Program.Main(String[] args)

**Comment by rrelyea** [comment]
I'm not able to repro this exactly.

What I tried...
1. created local nuget.config file via "dotnet new nugetconfig"
2. added source via "dotnet add source http://private.nuget.local -n private" (needs dotnet.exe 3.2.100 or later i believe...other wise use nuget.exe)
3. ran `C:\repos\nuget-5.6.0.exe setapikey @myapikey -source http://private.nuget.local`

result: setApiKey: invalid arguments.
not an exception...

regardless, you cannot set an apikey that starts with a @ 

i was able to repro an exception if i added quotes around @myapikey

This same behavior also happened with nuget 4.6...so it has been this way for a while.
User report above says it worked in 3.5

**Comment by zivkan** [comment]
> I'm not able to repro this exactly.
> i was able to repro an exception if i added quotes around @myapikey

@rrelyea  I assume you were testing within powershell. [Poweshell treats @ as a special/control character](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7#long-description). You can test with `echo @myapikey`, `echo "@myapikey"`.  People using different shells that do not use `@` as a control character will not have the same experience.
