### ISSUE TITLE
DateTimeParse issue in GetMetadata result

### ISSUE THREAD

**Issue by punitganshani** [NuGet/Home#976]
I am trying to search for "EntityFramework" using the code below in a ASP.NET MVC application

```
var repo = RepositoryFactory.Create("https://api.nuget.org/v3/index.json");
var metaResource = await repo.GetResourceAsync<UIMetadataResource>();
var packagesEnum = await metaResource.GetMetadata("EntityFramework", true, false, CancellationToken.None);
var packagesFound = packagesEnum.ToList();
```

When the enumerator is converted to List, an exception is throw as below -

```
String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at NuGet.Client.V3.VisualStudio.V3UIMetadataResource.ParseMetadata(JObject metadata)
   at NuGet.Client.V3.VisualStudio.V3UIMetadataResource.<GetMetadata>b__f(JObject item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
```

My local timezone is UTC+8

**Comment by punitganshani** [comment]
When using similar code in `UISearchResource` there is no `DateTime` parsing issue

**Comment by emgarten** [comment]
Which version of the protocol packages are you using?

**Comment by punitganshani** [comment]
I am using the latest prerelease version of packages from NuGet.org. 
Here's part of my packages.config

```
  <package id="NuGet.Configuration" version="1.0.0-pre-20150220022717" targetFramework="net452" />
  <package id="NuGet.Core" version="2.8.5" targetFramework="net452" />
  <package id="NuGet.Packaging" version="1.0.0-pre-20150220044603" targetFramework="net452" />
  <package id="NuGet.Protocol.Types" version="3.0.0-pre-20150220053306" targetFramework="net452" />
  <package id="NuGet.Protocol.V2V3" version="3.0.0-pre-20150220053309" targetFramework="net452" />
  <package id="NuGet.Services.Platform.Client" version="3.0.29-r-master" targetFramework="net452" />
  <package id="NuGet.Services.Search.Client" version="3.0.75-r-master" targetFramework="net452" />
  <package id="NuGet.Versioning" version="1.0.7" targetFramework="net452" />
```

**Comment by emgarten** [comment]
Those packages are out of date, try the latest ones here: https://www.myget.org/F/nugetbuild/api/v2

**Comment by punitganshani** [comment]
Looks like the package names have also changed.  
Can not find `NuGet.Protocol.V2V3` in the new MyGet repo or am I missing something?

**Comment by emgarten** [comment]
That package no longer exists, try NuGet.Protocol.VisualStudio

**Comment by emgarten** [comment]
Please reopen this issue you are still hitting this problem with the new packages.
