### ISSUE TITLE
How to authenticate to the custom nuget repository feed with programming?

### ISSUE THREAD

**Issue by fdevGit** [NuGet/Home#9793]
## Details about Problem
I am creating a project and the task of this project is to get the packages and their versions from a private nuget server. I can get data from nuget's own public servers. I cannot authenticate on a private server. How to authenticate to the custom nuget repository feed with programming?

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Assembly NuGet.Protocol.Core.v3, Version=4.2.0.0,

dotnet.exe --version (if appropriate):
3.1.301

VS version (if appropriate):
Microsoft Visual Studio Enterprise 2019 Version 16.6.3

OS version (i.e. win10 v1607 (14393.321)):
windows 10 Enterprise 1909

Worked before? If so, with which NuGet version:
Nuget is actively working. As I mentioned above, I can't be authenticate when using it in my project

## Detailed repro steps so we can see the same problem

1.You will see the problem in the sample project

### Verbose Logs
{"Response status code does not indicate success: 401 (Unauthorized)."}
   
at NuGet.Protocol.ServiceIndexResourceV3Provider.<GetServiceIndexResourceV3>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<TryCreate>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.PackageSearchResourceV3Provider.<TryCreate>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__15`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NugetPackageVersionResolver.Program.<V4>d__5.MoveNext() in C:\Users\x\source\repos\NugetPackageVersionResolver\NugetPackageVersionResolver\Program.cs:line 124
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NugetPackageVersionResolver.Program.<Main>d__0.MoveNext() in C:\Users\x\source\repos\NugetPackageVersionResolver\NugetPackageVersionResolver\Program.cs:line 38

### Sample Project
https://github.com/fdevGit/NugetPackageVersionResolver

**Comment by aortiz-msft** [comment]
This issue was moved to NuGet/docs.microsoft.com-nuget#2107
