### ISSUE TITLE
Random behavior of Nuget on not containing content files, and some strange errors

### ISSUE THREAD

**Issue by KKacer** [NuGet/Home#9809]
I used something like the code below in my .csproj file, but still Nuget is placing these contents in its generated package:

      <ItemGroup>
        <Content Include="build\**" IncludeInPackage="false" Pack="false" />
      </ItemGroup>

--------

Want those content files just for the usage in the current source, and don't want them to be included in the nuget package.

This is a .Net Core project, and don't like to add a nuspec file as I guess it is not needed.

It seems a random behavior, cause I have hundreds of packages in my local repository, checked all generated by the same approach and seems all were correct.
Such difficulties and issues happened tens of times with other packages in different times, which solved them by dirty tricks like clearing obj/bin, close/restart VS, restart win, changing the project version, and some other things that I may not remember now.

Unfortunately about the same package I got some strange errors which
but the problem is not about the package itself.

**The errors:**

------------------

**Error 1:**

    =====================
    7/16/2020 10:13:11 AM
    LimitedFunctionality
    Microsoft.VisualStudio.ProjectSystem.ProjectException: 
    Failed to create the item 
    "C:\Users\Pc\.nuget\packages\xxxx.emailing\0.8.5\contentFiles\any\netstandard2.1\package.csproj" 
    ---> Microsoft.Assumes+InternalErrorException: 
    ProjectTree is in the invalid state: project item 'package.csproj' with flags:
    (ProjectTreeFlags: ProjectImportImplicit FileOnDisk ProjectImport FileSystemEntity) was found under '' with flags(ProjectTreeFlags: BubbleUp DisableAddItemFolder VirtualFolder).
    
       at Microsoft.Assumes.Fail(String message)
       at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.FindOrCreateItem(IProjectTree tree, IImmutableDictionary`2 projectData, ConfiguredProjectExports configuredProjectExports, String ruleName, String itemName)
       --- End of inner exception stack trace ---
       at Microsoft.VisualStudio.ProjectSystem.ProjectErrorUtilities.ThrowProjectExceptionHelper(Exception innerException, String unformattedMessage, Object[] args)
       at Microsoft.VisualStudio.ProjectSystem.ProjectErrorUtilities.ThrowProjectException(Exception innerException, String message)
       at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.FindOrCreateItem(IProjectTree tree, IImmutableDictionary`2 projectData, ConfiguredProjectExports configuredProjectExports, String ruleName, String itemName)
       at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.HandleAddedItems(IProjectTree tree, IImmutableDictionary`2 projectData, IProjectChangeDescription change, IEnumerable`1 addedItems, ConfiguredProjectExports configuredProjectExports)
       at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTree originalTree, ConfiguredProjectExports configuredProjectExports, PhysicalProjectTreeInputData updateInput, CancellationToken cancellationToken)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
       at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
       at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
       at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
    ===================

**Error 2:**
After doing some of those dirty tricks and playing more with the code, the error changed a bit

```
    =====================
    7/16/2020 12:29:30 PM
    LimitedFunctionality
    Microsoft.VisualStudio.ProjectSystem.ProjectException: 
    Failed to create the item "C:\Users\Pc\.nuget\packages\xxxx.emailing\0.8.7\contentFiles\any\netstandard2.1\build.targets" ---> Microsoft.Assumes+InternalErrorException: ProjectTree is in the invalid state: 
    project item 'build.targets' with flags:
    (ProjectTreeFlags: FileOnDisk ProjectImport FileSystemEntity) 
    was found under '' with flags(ProjectTreeFlags: 
    BubbleUp DisableAddItemFolder VirtualFolder).
       at Microsoft.Assumes.Fail(String message)
       at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.FindOrCreateItem(IProjectTree tree, IImmutableDictionary`2 projectData, ConfiguredProjectExports configuredProjectExports, String ruleName, String itemName)
       --- End of inner exception stack trace ---
       at Microsoft.VisualStudio.ProjectSystem.ProjectErrorUtilities.ThrowProjectExceptionHelper(Exception innerException, String unformattedMessage, Object[] args)
       at Microsoft.VisualStudio.ProjectSystem.ProjectErrorUtilities.ThrowProjectException(Exception innerException, String message)
       at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.FindOrCreateItem(IProjectTree tree, IImmutableDictionary`2 projectData, ConfiguredProjectExports configuredProjectExports, String ruleName, String itemName)
       at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.HandleAddedItems(IProjectTree tree, IImmutableDictionary`2 projectData, IProjectChangeDescription change, IEnumerable`1 addedItems, ConfiguredProjectExports configuredProjectExports)
       at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTree originalTree, ConfiguredProjectExports configuredProjectExports, PhysicalProjectTreeInputData updateInput, CancellationToken cancellationToken)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
       at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
       at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
       at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
    ===================
```
Had hundreds of different versions of nuget packages in my local repository, and everything was working perfectly, once I was playing and updating some of the nugets the happened.

Surprisingly, there was nothing on the internet.

This is one of the most irritating errors I got, cause don't know, and can't guess what really may happened and what could be the issue, the most probable solution remained that I can guess could be to restart windows, after clearing every possible cache.
Don't know Nuget from where and how generate those wrong contents repeatedly.

Earlier there was a project that I was forced to start it from the ground up.
For another project Nuget repeatedly was setting the location of the contents somewhere else, and got forced to add a Nuspec file to let it know where is the exact target location though I set it ealier in the .csproj file.

I could have made more issue/bug report here, but now was able to post one after seeing some kind of behavior repeatedly which these are really irritating.

Using Visual Studio latest version, built the packages via VS build menu.
Projects are as simple as:

<Project Sdk="Microsoft.NET.Sdk">

```
  <PropertyGroup>
    <!-- <TargetFrameworks>netcoreapp3.1;netstandard2.0;netstandard2.1;netcoreapp3.0;net472</TargetFrameworks> -->
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

// with some contents like the ones posted earlier.
```

**Comment by KKacer** [comment]
My problem got solved after recreating/cleaning everything, and excluding a piece of content (extra csproj) from the package which I didn't want to be placed in the contents section.
The main problem about some similar behavior of Nuget is, maybe some times it doesn't reflect the latest changes,if a part has a bug or should throw an error it doesn't, and when you made several components relied on each other, then it may appear, and it will cause huge effort to find the problem. Why some times same code is working in some projects and may cause some errors later? Some issues appeared in the part of the code that haven't had any changes.
BTW here at least wanted to report it.

Regards.
