### ISSUE TITLE
Pushing a snupkg with an invalid Symbol Server should error better than "File not found"

### ISSUE THREAD

**Issue by McMlok** [NuGet/Home#9909]
## Details about Problem
When I try to push a *.snupkg to our corporate nexus server it fail with the file not found error. But the file is on a mentioned path and I can open it with winzip. I try it via Nuget.exe and with dotnet.exe with the same result. When I push standard nupkg everything works fine on V2 and also for V3 protokol.

Nuget.exe and dotnet.exe

NuGet version: 5.6.0, 5.7.0 5.8.0-preview.1

dotnet.exe --version (if appropriate):3.1.401

VS version (if appropriate): 16.7.1

OS version: Windows 10 1809

Worked before? If so, with which NuGet version: No it's my first try to push symbols to our corporate nexus feed.

## Detailed repro steps so we can see the same problem

1. dotnet new classlib
2. dotnet pack -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
3. nuget push C:\FULL_PATH_TO_PROJECT\bin\Debug\TestLibrary.1.0.0.snupkg -Source CorporateNexus -SymbolSource CorporateNexus -verbosity detailed  -ForceEnglishOutput

...
### Verbose Logs
```
nuget push C:\FULL_PATH_TO_PROJECT\bin\Debug\TestLibrary.1.0.0.snupkg -Source CorporateNexus -SymbolSource CorporateNexus -verbosity detailed  -ForceEnglishOutput
NuGet Version: 5.6.0.6591
File does not exist (C:\FULL_PATH_TO_PROJECT\bin\Debug\TestLibrary.1.0.0.snupkg).
System.ArgumentException: File does not exist (C:\FULL_PATH_TO_PROJECT\TestLibrary\bin\Debug\KB.TestLibrary.1.0.0.snupkg).
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushSymbols>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

What I did wrong?

**Comment by donnie-msft** [comment]
I believe that the short answer is that this scenario isn't supported. Pushing to a Symbol Server is supported, but not snupkgs to a local feed. I didn't quickly find any docs explaining this, but it seems the "push snupkg" examples I see on the web involve Server feeds. @nkolev92 can correct me or elaborate more on our support here.

In your case, the file exists, but the logic can't resolve a SymbolPackageUpdateResourceV3 so https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Resources/PackageUpdateResource.cs#L179 triggers the error below, `UnableToFindFile`. Ideally the error would indicate that the scenario is unsupported to be more clear.  

I added this error message (which I agree is not ideal in your case) with my PR that went into **5.6 Preview 2** https://github.com/NuGet/NuGet.Client/pull/3140. Prior to this, **the CLI output was blank**, but the snupkg still wasn't pushed for the same reason.

In that PR, I explained what you're bumping into:
> Behavior change:  Pushing an explicit snupkg filename that does not exist will error.

**Comment by McMlok** [comment]
Thank you for your explanation. In meantime I found issue in [Nexus JIRA](https://issues.sonatype.org/browse/NEXUS-6779) which at this time doesn't support symbols repositories. Then my error is not in non-existing file but in unsupported symbol server.

If CLI report more specific error it will be helpful.
