### ISSUE TITLE
MSBuild project evaluation fails when TargetFramework property includes semicolon

### ISSUE THREAD

**Issue by dsplaisted** [NuGet/Home#9927]
The .NET SDK is now using `NuGetFramework` methods to parse the `TargetFramework` property, via MSBuild intrinsic functions that were added for this:

https://github.com/dotnet/sdk/blob/5b50ac24ecd5af91736cf81360eab5813c9e93b9/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets#L54-L55

However, this is causing MSBuild evaluation to fail with an assertion when the `TargetFramework` property has a semicolon in it (for example `netcoreapp2.0;net461`).  What is supposed to happen is for the SDK to generate an error during the build:

> error NETSDK1046: The TargetFramework value 'netcoreapp2.0;net461' is not valid. To multi-target, use the 'TargetFrameworks' property instead.

However, instead evaluation fails with the following:

> ---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
invalid folder name, this appears to contain multiple frameworks
---- Assert Long Message ----
>
>   at NuGet.Frameworks.NuGetFramework.Parse(String folderName, IFrameworkNameProvider mappings)
   at NuGet.Frameworks.NuGetFramework.Parse(String folderName)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Build.Evaluation.NuGetFrameworkWrapper.Parse(String tfm) in C:\git\msbuild\src\Build\Utilities\NuGetFrameworkWrapper.cs:line 55
   at Microsoft.Build.Evaluation.NuGetFrameworkWrapper.GetTargetFrameworkIdentifier(String tfm) in C:\git\msbuild\src\Build\Utilities\NuGetFrameworkWrapper.cs:line 60
   at Microsoft.Build.Evaluation.IntrinsicFunctions.GetTargetFrameworkIdentifier(String tfm) in C:\git\msbuild\src\Build\Evaluation\IntrinsicFunctions.cs:line 486

I think to fix this the parse methods should return "Unsupported" instead of asserting when there is a semicolon in the value passed in.

I ran into this when testing private NuGet packages based on this PR: https://github.com/NuGet/NuGet.Client/pull/3578.  As our tests didn't fail previously, this may have been a regression in that PR.

@nkolev92

**Comment by nkolev92** [comment]
Fortunately(?) this is not a bug. 

What I gave you was a debug build with my change and the code has a Debug.Assert, https://github.com/NuGet/NuGet.Client/blob/3501ddedc274ac10d4b135856b7593a6bb8a72f1/src/NuGet.Core/NuGet.Frameworks/NuGetFrameworkFactory.cs#L57.

In release bits this won't run. 

Closing this as not a bug. 

I can provide you a release build if you still need it for testing. 
If you are using the nuget feed, then 5.8.0.6783 should do it.
