### ISSUE TITLE
Provide better cli help for subcommands

### ISSUE THREAD

**Issue by patrickhousley** [NuGet/Home#9962]
## Details about Problem

Nuget should provide better help information on the CLI for sub-commands. Trying to determine what flags are available to a sub-command seems to require looking up and reading through online documentation. Most CLI tools typically provide this information in the form of a `--help` flag.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 5.7.0.6726

OS version (i.e. win10 v1607 (14393.321)): 10.0.17134 N/A Build 17134

## Detailed repro steps so we can see the same problem

1. Type `nuget config --help` into the command line

2. Receive error:
```
NuGet.Commands.CommandException: Unknown option: '--help'
   at NuGet.CommandLine.CommandLineParser.GetPartialOptionMatch[TVal](IEnumerable`1 source, Func`2 getDisplayName, Func`2 getAltName, String option, String value)
   at NuGet.CommandLine.CommandLineParser.ExtractOptions(ICommand command, IEnumerator`1 argsEnumerator)
   at NuGet.CommandLine.CommandLineParser.ParseCommandLine(IEnumerable`1 commandLineArgs)
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by patrickhousley** [comment]
Never mind, I should have paid more attention to the `help` command output. Sorry to bother.
